### ISSUE TITLE
[Feature]: Re-Authenticate from CLI less

### ISSUE THREAD

**Issue by joncarr** [Shopify/cli#1024]
### What area(s) will this request affect?

Theme, Running your code locally, Other

### What type of change do you want to see?

New feature

### Overview

I'm not sure it's really a feature, I just wanted to throw something out there for the maintainers.

In an 8-hour day, I have to re-authenticate at minimum, 4 times, sometimes more. It's not a deal breaker but it does get annoying, considering I work with the CLI every day. I'm not certain what is controlling authentication, but I've had it de-authenticate a session despite the dev never being stagnant.

### Motivation

The 4th re-authentication today.

**Comment by isaacroldan** [comment]
Hi @joncarr, are you using the latest version of the CLI? This was fixed a couple of releases ago. Please try with version `3.31.1` and let us know if it still happens to you :)

**Comment by alvaro-shopify** [comment]
Hi @joncarr , I'm glad the solution proposed by my partner @isaacroldan has worked for you. This issue is now going to be closed. Please, open other issue in case you experience any problem related with this one or other topic.
