### ISSUE TITLE
[Bug]: Upgrade theme checker

### ISSUE THREAD

**Issue by bakura10** [Shopify/cli#1049]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Currently, the CLI uses the version 1.12.1 for the theme check (https://github.com/Shopify/cli/blob/783481dd06dd147123b6b74f397a11eff21c66d7/packages/cli-kit/src/public/node/ruby.ts#L15).

The version 1.13 added support for the new "section group". The CLI should be updated as well.

Thanks :)

### Actual behavior

Shopify CLI uses an older version.

### Reproduction steps

1.
2.
3.

### Operating System

OS X

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.32

**Comment by katiewelton** [comment]
Is there no way to update theme check separately? This is beyond frustrating

**Comment by bakura10** [comment]
Hi @veken1199 

Unfrotunately, the issue has not been fixed for some reason. I have upgraded to the new Shopify CLI, but the theme checker still fails:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/1198915/211999496-12569e83-1432-4f47-9e5e-5f13e2bb0f7b.png">

So either theme-check or Shopify CLI has a bug here :)

**Comment by dazjohnsoncc** [comment]
Can confirm, same issue for me running 3.32.1. I also get a lovely big stack trace:
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/55978746/212022424-a9ebefa3-6e08-4f31-8e09-67b83e3f76d5.png">

**Comment by alvaro-shopify** [comment]
Hi @bakura10 @dazjohnsoncc ! We have released CLI 3.33.0 to fix this problem. Please, update your version when possible. Let me know if now it's working for you. Sorry for inconveniences
