### ISSUE TITLE
[Feature]: Customer account login in for theme dev

### ISSUE THREAD

**Issue by tig66208** [Shopify/cli#1055]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

It appears to me that when using the CLI to locally develop a theme, you cannot log in as a storefront user - the auth redirects back to the live site. This requires that any code changes get pushed and tested through the store and the theme editor / preview which is quite inefficient.

For building and testing theme features centered around a logged-in user experience, the CLI theme host needs to support local login

### Motivation

Building customer-facing pages with specific pricing, order history, etc. This is not for an app - we are building these capabilities natively into our theme for speed and to reflect very exact, unique use cases in our product configuration that are not efficiently or easily deal with in other apps.

**Comment by Jamiemccleave** [comment]
This is still an issue

**Comment by eentdn** [comment]
> It's not necessarily an issue - when you run the dev server from the command line it will also push a theme up to shopify. Hit the public URL and it's no different than previewing a theme from the online editor, and you can log in.

This approach allow me to work with Account page locally without live reload. Tested with @shopify/cli/3.90.1 darwin-arm64 node-v22.15.0
