### ISSUE TITLE
[Bug]: No version set for command bundle

### ISSUE THREAD

**Issue by sshaw** [Shopify/cli#1056]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Theme files are uploaded.

### Actual behavior

```
~/code/js/XXX/src/client >ruby -v
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-darwin17]
~/code/js/XXX/src/client >npx shopify theme push XXXXX
Deploying from /var/folders/fn/5bmn_rf52x54hj7lxsw5c7ch0000gn/T/product-builder-deploy-20230110-193012
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-darwin17]
npm WARN config init.author.name Use `--init-author-name` instead.
npm WARN config init.author.email Use `--init-author-email` instead.

── external error ────────────────────────────────────────────────────────────────────────────

Error coming from `bundle config set --local path /Users/sshaw/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0`

Command failed with exit code 126: bundle config set --local path /Users/sshaw/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.33.0
No version set for command bundle
Consider adding one of the following versions in your config file at
ruby 2.6.6
ruby 2.7.2
ruby 3.1.3

──────────────────────────────────────────────────────────────────────────────────────────────
```

Node.js executable that depends on Ruby that depends on configuring bundler‽ 🤯 

### Reproduction steps

1. Instal several versions of Ruby via asdf
1.  npm i -D @shopify/cli
1. npx shopify theme push 

### Operating System

Mac OS X 10.13.6

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.32.0 darwin-x64 node-v14.18.2

**Comment by colinbrogan** [comment]
I am getting the exact same error when using rbenv to install ruby (my preferred method).
Tried setting `SHOPIFY_RUBY_BINDIR` to the output of `$(which ruby)`, but doesn't solve it.

It appears to me that the trouble is finding the path of `bundle`. Not sure where shopify-cli is getting that path, but would like to try and override it if I could find out how to do that.

**Comment by dani-sanomads** [comment]
=> ruby -rrbconfig -e'p RbConfig::CONFIG["bindir"]'
-> "/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin"
@sshaw 
How can I change the version of ruby on MacOS if it is using ruby2.6 but i want it to be ruby@3.0+?

**Comment by sshaw** [comment]
@dani-sanomads there are a variety of ways, most common are: 
- [asdf](https://github.com/asdf-vm/asdf-ruby)
- [RVM](https://rvm.io/)
- [rbenv](https://github.com/rbenv/rbenv)

**Comment by jassiBV** [comment]
While pull theme from shopify theme pull command i get this error: 



Error coming from `bundle config set --local path /home/jaswinder_kaur/.cache/shopify-gems-nodejs`
Command failed with exit code 23: bundle config set --local path /home/jaswinder_kaur/.cache/shopify-gems-nodejs
There was an error while trying to write to `/usr/local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/.bundle/config`. It
is likely that you need to grant write permissions for that path.
