### ISSUE TITLE
[Bug]: shopify app build does not install devDependencies

### ISSUE THREAD

**Issue by ozzyonfire** [Shopify/cli#1072]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should install everything necessary for the build to complete. This includes devDependencies

### Actual behavior

My build keeps failing on external services (like heroku) because the devDependencies were not being installed.

### Reproduction steps

1. Create a new nodejs project from the cli 
2. Configure it to use typescript
3. `npm run build`
4. `tsc` will not work

### Operating System

Windows 10, Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.32.1

### Shell

powershell / bash

### Node version (run `node -v` if you're not sure)

16.15.1

### What language and version are you using in your application?

Node, Typescript

**Comment by matteodepalo** [comment]
Hi @ozzyonfire, have you tried setting `NODE_ENV` to `development`? Typically when build is run the env is set to `production` which doesn't install devDependencies, and this should be the default setting on Heroku.
