### ISSUE TITLE
[Bug]: Cart API - Request to `/cart/*.js` routes returns 401 error when using dev command with password flag

### ISSUE THREAD

**Issue by davidthorand** [Shopify/cli#1078]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When serving the theme via localhost (`shopify theme dev --password=<THEME_ACCESS_PASSWORD>`) requests to the Cart API (and other Ajax APIs) should work exactly like in a production/remote environment.

### Actual behavior

All requests error due to the client being unauthorized.

### Reproduction steps

1. Serve theme via `shopify theme dev --password=<THEME_ACCESS_PASSWORD>`
2. Try to add a item to the cart via `fetch('/cart/add.js', { ... })`
3. Check response

(Repeat steps without `--password` flag and login via web UI instead and it should be working again)

### Operating System

macOS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.32.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.13.0

### What language and version are you using in your application?

Node v18.13.0

**Comment by matteodepalo** [comment]
@Shopify/theme-developer-tools

**Comment by james0r** [comment]
I'm getting the 401 when trying to access `/cart.js' on the dev server as well. Looks like Cloudflare doesn't like the proxy.

**Comment by Poitrin** [comment]
I started a dev server with `shopify theme dev --store=https://….myshopify.com/ --password=shptka_…` and—besides some errors like `POST http://127.0.0.1:9292/.well-known/shopify/monorail/unstable/produce_batch 400 (Bad Request)` (which will be solved in a different issue)—I was able to add an item to my cart:
![06-25-454bd-twql5](https://user-images.githubusercontent.com/12963280/223084894-be0c4d5c-8cff-4266-a0aa-f64493a430a8.jpg)

I fear that it's more an issue of your code. (I'm using a recent version of Dawn.)
E.g., you wrote in your reproduction steps:
2. Try to add a item to the cart via `fetch('/cart/add.js', { ... })`

But shouldn't the URL be `/cart/add` instead? :)

**Comment by davidthorand** [comment]
@Poitrin this is how my fetch request looks like:

```js
const { routes } = window.Shopify;

const response = await fetch(routes.root + 'cart/add.js', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    // This is passed as an arg of the method where this fetch request is placed.
    items,
    sections: 'cart-drawer',
  }),
});
...
```

This is the body (example):

```json
{
  "items": [
    {
      "id": 123,
      "quantity": 1
    }
  ],
  "sections": "cart-drawer"
}
```

This is the response:

```json
{
  "status": "bad_request",
  "message": "must be a collection of items: items",
  "description": "must be a collection of items: items"
}
```


The request works perfectly fine (as expected) if I don't use the `theme dev` password flag.

**Comment by Poitrin** [comment]
The reason why it was initially working on my machine was because I used a [_custom app token_](https://shopify.dev/docs/apps/auth/admin-app-access-tokens) (starting with `shpat_`), instead of a _theme access token_ (starting with `shptka_`).

Even though both tokens passed via `--password` seem to be accepted by the CLI, there seems to be some incompatibilities later. I will continue my search…

**Comment by kenji-twp** [comment]
@Poitrin i’ve seen cases of old passwords that don’t even have a prefix at all, still being used. I think dating from the _private_ app / themekit / slate 0 era?

**Comment by Poitrin** [comment]
Thanks again @davidthorand for the detailed answers. This and the related issue #1537 should be fixed _in the next release_.
