### ISSUE TITLE
[Bug]: Shopify Cli Localhost IP http://127.0.0.1:9292 not working - Windows 11

### ISSUE THREAD

**Issue by kmishal** [Shopify/cli#1085]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Should  start a local server on ` http://127.0.0.1:9292`

### Actual behavior

This site can't be reached 

![image](https://user-images.githubusercontent.com/41513034/212251441-962e1547-17de-4fcc-b203-9374f9a65c0c.png)

### Reproduction steps

1.Open Terminal
2.Hit command `shopify theme dev`
3. Open localhost ip provided

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.32.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

18.12.1

**Comment by anteksiler** [comment]
Have you tried changing ports using --port=9393

**Comment by vfonic** [comment]
You could also try using `fkill` to kill any process that's running on port 9292 like this:
`fkill :9292`

https://github.com/sindresorhus/fkill-cli

**Comment by axu6705** [comment]
> Have you tried changing ports using --port=9393

![20230527231406](https://github.com/Shopify/cli/assets/5799425/1ccd0422-18b6-4659-b359-cb71b50c03b1)
![20230527231525](https://github.com/Shopify/cli/assets/5799425/61df110c-3a1a-4edb-b015-05155605e9f2)
@anteksiler @matteodepalo help me, thanks!

**Comment by shopifyexpert8** [comment]
I am facing the same issues,  anyone can show some updates about this thread?
