### ISSUE TITLE
[Bug]: Couldn't obtain a random port number

### ISSUE THREAD

**Issue by marvinhagemeister** [Shopify/cli#109]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

No error

### Actual behavior

Just got an error after restarting the dev server:

<img width="803" alt="Screenshot 2022-07-05 at 12 49 57" src="https://user-images.githubusercontent.com/1062408/177311753-cdb39636-a0c6-4811-9079-e699ca35ee1d.png">

Restarting the dev server a second time resolved the issue for me.

### Stack trace

```shell
Unable to obtain an available random port number!

    Stack trace:    at getRandomPort              …er-cool-app/node_modules/get-port-please/dist/index.mjs:129  
    at processTicksAndRejection…  node:internal/process/task_queues:95                          
    at getRandomPort              …ister-cool-app/node_modules/@shopify/cli-kit/src/port.ts:10  
    at                            …@shopify/app/src/cli/utilities/app/http-reverse-proxy.ts:42  
    at all                                                                                      
    at runConcurrentHTTPProcess…  …@shopify/app/src/cli/utilities/app/http-reverse-proxy.ts:40  
    at dev                        …l-app/node_modules/@shopify/app/src/cli/services/dev.ts:119  
    at run                        …pp/node_modules/@shopify/app/src/cli/commands/app/dev.ts:73
```

### Reproduction steps

Not sure tbh, can't reproduce it consistently.

### Operating System

macOS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0.25

**Comment by alvaro-shopify** [comment]
Hi @weeksie ! I have reviewed again the `get-port-please` code used in `getRandomPort` and follows these steps:

* Get all the local host from you local network interfaces
* Iterate over them creating a socket server (using an arbitrary port)
* In case of error or the port is contained in a hardcoded internal list, an exception is raised with the message "Unable to obtain an available random port number!"
* The port is returned only if the proccess could listen to the socket on the same port (and it is not reserved) in all the local hosts

So I think there is no retrying logic for that method. It seems that in specific cases one of the previous steps fails and the exception is raised showing the message ```Unable to obtain an available random port number!```, executing again the command ```dev``` solves the problem, so this fix should avoid to see that error again.

Please let me know if you encounter it again.
