### ISSUE TITLE
[Bug]: can't start app by running `npm run dev` command

### ISSUE THREAD

**Issue by lxinghe** [Shopify/cli#1092]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The app shall come online after running running `npm run dev` command

### Actual behavior

it returned this error:

error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  performance is not defined                                                  │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at action (@shopify/cli-kit/src/private/node/api/graphql.ts:25)           │
│      const t0 = performance.now()                                            │
│    at async handlingErrors                                                   │
│    (@shopify/cli-kit/src/private/node/api/graphql.ts:59)                     │
│      return await action()                                                   │
│    at async fetchOrganizations                                               │
│    (@shopify/app/src/cli/services/dev/fetch.ts:79)                           │
│      const result: AllOrganizationsQuerySchema = await                       │
│      partnersRequest(query, token)                                           │
│    at async selectOrg (@shopify/app/src/cli/services/environment.ts:436)     │
│      const orgs = await fetchOrganizations(token)                            │
│    at async ensureDevEnvironment                                             │
│    (@shopify/app/src/cli/services/environment.ts:135)                        │
│      const orgId = cachedInfo?.orgId || (await selectOrg(token))             │
│    at async dev (@shopify/app/src/cli/services/dev.ts:57)                    │
│      const {storeFqdn, remoteApp, updateURLs: cachedUpdateURLs,              │
│      tunnelPlugin} = await ensureDevEnvironment(options, token)              │
│    at run (@shopify/app/src/cli/commands/app/dev.ts:97)                      │
│      await dev({                                                             │
│

### Reproduction steps

1. installed shopify cli 
2.  run command `npm init @shopify/app@latest` to create an app (choose nodejs)
3. change directory (app directory) and then run `npm run dev`

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.33.0

### Shell

Powershell

### Node version (run `node -v` if you're not sure)

v14.18.2

### What language and version are you using in your application?

v14.18.2

**Comment by lxinghe** [comment]
is this problem solved?

**Comment by Gleammer** [comment]
> is this problem solved?

Doesn't seem so. Am currently facing the same problem.

**Comment by lxinghe** [comment]
@Arkham hi, is this problem solved? It looks like it still exists. And I don't see any new releases. Could you help me please, by any chance?

**Comment by Arkham** [comment]
Fix has been merged to main, a new release will be created later today.
