### ISSUE TITLE
Difference with Shopify App that runs on the ruby engine

### ISSUE THREAD

**Issue by w0rldart** [Shopify/cli#1101]
I apologise in advance if this is not rightly label or categorised. I couldn't find a better way of asking this.

Being new to Shopify app development, I have for the first time been expose to Shopify CLI and [Shopify App](https://github.com/Shopify/shopify_app) engine. 

First: some clarity between these two in the README of both repositories, would be very helpful.
Second: what is the difference between these two? When to use one over the other?

**Comment by amcaplan** [comment]
The Shopify App engine is a tool used specifically in Rails apps. However, regardless of preferred tech, I'd recommend using the CLI to generate your app. (If you generate a Ruby app, it will use `shopify_app` as a dependency.) Use the docs at shopify.dev as your guide.

**Comment by amcaplan** [comment]
You can have a look at [this getting started guide](https://shopify.dev/apps/getting-started/create), and learn more about our modern Ruby template [here](https://github.com/Shopify/shopify-app-template-ruby#readme).

**Comment by matteodepalo** [comment]
Hi @w0rldart, hopefully the documentation referenced by @amcaplan was helpful in guiding you through the first steps of app development at Shopify. I'm going to close this issue as it doesn't directly fit in our backlog, but please do open a new one if you find a problem with the docs or with app development in general!

**Comment by w0rldart** [comment]
Sorry to re-open this.

Much appreciated the feedback.
I still think that the 2 READMEs should update to reflect this. It is confusing for someone that starts from scratch, to know what is what, and their differences.

I now understand that CLI is the preferred method
