### ISSUE TITLE
[Bug]: Windows "Terminate batch job (Y/N)?"

### ISSUE THREAD

**Issue by ceri-waterscreative** [Shopify/cli#1104]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Terminal cancels task in one go

### Actual behavior

Terminal comes up with "Terminate batch job (Y/N)?", requiring an extra step to cancel the process. This doesn't always work either, it sometimes locks up. 

Additionally, if your login session expires and it comes up with "Run shopify login to sign back in" and you cancel the batch process it locks up due to the Terminate Batch Job issue. 

### Reproduction steps

1. Run shopify theme dev and wait for it to complete
2. Cancel the job via Ctrl+C
3. See Terminal for message

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.33

### Shell

Git Bash, Windows Powershell

### Node version (run `node -v` if you're not sure)

18.12.1

### What language and version are you using in your application?

N/A Shopify Theme

**Comment by ceri-waterscreative** [comment]
> I'm afraid this is a problem with `cmd.exe`, see this stackoverflow issue: https://stackoverflow.com/questions/39085380/how-can-i-suppress-terminate-batch-job-y-n-confirmation-in-powershell#:~:text=If%20you%20do%20not%20explicitly,in%20order%20to%20terminate%20execution. I'm not confident that migrating to powershell `ps1` is the desired outcome either, since it forces all windows users to use that.

Not really my area of expertise, but judging from the comments a ps1 script instead of .cmd would solve the issue?

**Comment by amcaplan** [comment]
Related: https://github.com/Shopify/cli/issues/1165

**Comment by massivecatapult** [comment]
I have always had the additional confirmation dialog appear in Windows, but now it appears to not actually end the process. Whenever I enter 'y' to confirm, it fails with this message:

> Stopping…
> Terminate batch job (Y/N)? y
> 'y' is not recognized as an internal or external command, operable program or batch file.

After that, the command prompt is left in a weird limbo where it still seems to be running the CLI, but nothing works correctly. The only solution at that point is to close the window and re-open.

**Comment by matteodepalo** [comment]
We're adding functionality to `dev` that will all you to quit by pressing `q` so it should alleviate this problem.

**Comment by superfein** [comment]
I am using shopify-cli v3.4.1 and on Windows 10, and I have this same issue. Looking forward to that `q` option.

**Comment by matteodepalo** [comment]
@superfein the functionality has been shipped so try the latest version and let us how if it works for you!

**Comment by superfein** [comment]
@matteodepalo I just updated to v3.42.0 and I can confirm that the `q` command does not work, nor does the `p` command. That bar doesn't show up either, the one that is supposed to indicate `q` and `p` command options.

**Comment by matteodepalo** [comment]
@superfein would you mind opening a separate issue for that? I've tried reproducing with a newly created app on windows and couldn't. The bar with shortcuts isn't displayed unless you have a frontend or ui extensions so it's important to know your setup in order to debug the issue.

**Comment by superfein** [comment]
@matteodepalo sure thing, I'll open a separate issue for theme development, I realize this issue is only for apps.

**Comment by tomorrowagency-preston** [comment]
confirming the same thing as Superfein. I just upgraded to 3.43 and pressing 'q' doesn't do anything.
