### ISSUE TITLE
[Bug]: "Please login again with shopify login"

### ISSUE THREAD

**Issue by ceri-waterscreative** [Shopify/cli#1114]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Console should show the correct command "shopify theme dev"

### Actual behavior

Console shows the incorrect command

### Reproduction steps

1. Run shopify theme dev
2. Wait until you get logged out
3. View the error message: 

"ERROR  » update snippets/yourfile.liquid: X Please login again with shopify login"

4. (shopify login is not a valid command)

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.33.0

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

18.12.1

### What language and version are you using in your application?

N/A

**Comment by amcaplan** [comment]
Is it possible [this fix](https://github.com/Shopify/cli/pull/1105), included in 3.34, takes care of being kicked out entirely?

At any rate, we should have better handling of this kind of case, but I'm not sure what that looks like as "logging in again" is a CLI2 concept not CLI3. Hopefully this kind of edge case goes away as we fully port commands to Node.

cc @Shopify/theme-developer-tools as maybe there's something to be done here.

**Comment by existentialstudios** [comment]
Still happening in 3.44, also breaking out of CLI causes terminal to bug out

**Comment by ceri-waterscreative** [comment]
I've not had this issue myself for a while now.. the CLI seems to auto-restart. Won't close as others are still reporting issues.

**Comment by amcaplan** [comment]
@hedgehog90 which CLI version are you on?

@existentialstudios glad to hear. What OS are you on? Did you switch from `CTRL+C` to `q`?

**Comment by Arkham** [comment]
I removed the incorrect messaging in `3.45.0`, closing this.

**Comment by knynkwl** [comment]
I am continually being told I need to login with the cli, having to stop and start. Even though I am logged in.

<img width="181" alt="Screenshot 2023-06-09 at 4 45 42 PM" src="https://github.com/Shopify/cli/assets/4225771/3c97b738-7a8a-4602-af33-699ea0fd89ed">


Will this fix this issue? When do you anticipate this being released?

**Comment by bluedge** [comment]
Same problem here!
So annoying!
CLI version: 3.46.4

**Comment by FeazeGraphics** [comment]
I have updated the software and am experiencing the same problem.
I am logged in but cannot get in.
Please do something about it.

CLI version: 3.46.4

**Comment by amcaplan** [comment]
@knynkwl @bluedge @FeazeGraphics it's not recommended to comment on closed issues. Instead, please open a new issue with full details of what you're experiencing now, and we'll do our best to assist.

**Comment by knynkwl** [comment]
Working so far! Thanks for the update
