### ISSUE TITLE
[Feature]: Add color to dev console output - CLI 3.0

### ISSUE THREAD

**Issue by yosef-grant** [Shopify/cli#1123]
### What area(s) will this request affect?

App, Running your code locally

### What type of change do you want to see?

New feature

### Overview

The ability to change the color of the server output/logs. A selection of colors should be available to meet a range of needs and specific requirements for logging data to the console during development. Alternatively alter the library to allow the use of external 'colorizing' libraries like chalk, since at the moment they can't override the preset behaviour. 

### Motivation

The default log styling/color in the CLI means all console.log output from the server follows the same format: cyan, prefixed with timestamp and backend label. This makes tracking req/res from custom endpoints quite difficult, as there is no visual distinction between them, or between various data from different endpoints.

**Comment by davidhollenbeckx** [comment]
strongly agree! we lost a lot of contrast somewhere in between 3.23 and 3.36 & it's a lot harder to parse longer logs. Looks like some of the Shopify team is discussing adding a no-color flag in issue  #1161

**Comment by matteodepalo** [comment]
Hi @yosef-grant thank you for the feedback. The decision to make the output the same color stems from the fact that many logs would output ansi escape characters that would break the flow of the logs completely, so by stripping all of these characters we can make sure that everything is indented properly and readable. However, it's true that this means contrast has been lost which is not ideal. I'll loop in the team about this and we'll discuss potential solutions.
