### ISSUE TITLE
[Feature]: Allow the creation of an app programmatically

### ISSUE THREAD

**Issue by nullndr** [Shopify/cli#1126]
### What area(s) will this request affect?

App

### What type of change do you want to see?

New feature

### Overview

The command `npm run shopify app env pull` should accept a new parameter (like `--app`) to avoid manually select the app.

Currently the app is created on the first run of `npm run dev`, I would like to see maybe a `npm run shopify app create` in order to avoid running the project just to create the app.

### Motivation

I'm building a CI/CD flow for a Shopify app.

In this flow I successfully create a preview of the database with terraform and aws, and a preview of the frontend with terraform and vercel for each branch I create.

Now it comes to Shopify, I took a look at the [docs](https://shopify.dev/apps/tools/cli/commands#help) for the `@shopify/app` package and I was wondering that there isn't anything that could really help me.

For example I am not able to automatically select the app in the first example: 

```
❯ npm run shopify app env show

> foo-bar-foobar@1.0.0 shopify
> shopify

? Which existing app is this for? Type to search…
> foo
  bar
  foobar
(Move up and down to reveal more choices)   
```

And the `--help` flag didn't show a possible solution for this:

```
❯ npm run shopify app env pull -- --help

> foo-bar-foobar@1.0.0 shopify
> shopify

Pull app and extensions environment variables.

USAGE
  $ shopify app env pull [--verbose] [--path <value>] [--env-file <value>]

FLAGS
  --env-file=<value>  [default: .env] Specify an environment file to update if the update flag is set
  --path=<value>      The path to your app directory.
  --verbose           Increase the verbosity of the logs.

DESCRIPTION
  Pull app and extensions environment variables.
```

Another thing I would aspect is to manually update the app urls, in order to set the url of each preview (currently this is possible running `npm run dev -- --tunnel-url https://foo.com:123456` but still, I have to run the project just to update the urls). 

Also, the app request to open a browser page in order to authenticate with Shopify, but maybe we could use a token for this? (Maybe for this I should open another issue, if that's the case sorry! but this was related to my request).

**Comment by amcaplan** [comment]
Hi @nullndr, thanks for the in-depth explanation and background!

A few notes come to mind initially:

1. Many actions are already possible in a CI/CD environment, see docs [here](https://shopify.dev/apps/tools/cli/ci-cd)
2. You may be interested to follow the work here: https://github.com/Shopify/cli/pull/993
3. I'm not sure why `npm run shopify app env show` should have anything to do with a store. Your app can be previewed in any development store. The store is just used for generating a preview URL but can be specified when you run `dev`.
4. What is the motivation for this?
    >  I would like to see maybe a npm run shopify app create

    When do you want to create an app without devving/deploying to it?

    (Note I could imagine a world where we want to support a flag to skip the prompt and just create the app. Would that work in your case?)

**Comment by nullndr** [comment]
Thanks @amcaplan for the feedback.

> I'm not sure why npm run shopify app env show should have anything to do with a store.

Yeah my bad, I mean the app.

> When do you want to create an app without devving/deploying to it?

Typically I use other frameworks like [remix.run](https://remix.run) and a container for ngrok.

In this case I need to manually create the app and setup the custom url that I define for the ngrok container.

Currently I can't automatize these two processes.

I want to automatize them in order to deploy a preview of my branch.

> Note I could imagine a world where we want to support a flag to skip the prompt and just create the app. Would that work in your case?

Absolutely!

> Many actions are already possible in a CI/CD environment, see docs [here](https://shopify.dev/apps/tools/cli/ci-cd)

These docs talks about app extensions, I don't know a lot about extensions, but it doesn't seem to help me.

> You may be interested to follow the work here: https://github.com/Shopify/cli/pull/993

Thank you!

**Comment by nullndr** [comment]
Hey @amcaplan, why did the bot close this issue?

**Comment by amcaplan** [comment]
Ah, I think I needed to remove the label as well!

**Comment by amcaplan** [comment]
still relevant

**Comment by karim2012** [comment]
Is there any news?

**Comment by orlade** [comment]
+1, any updates? Maybe forgotten after all..? Seems like none of CLI, GraphQL or even Playwright are viable in CI.
