### ISSUE TITLE
[Bug]: `shopify theme dev` not logging into password-protected store on Safari

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#1151]
### Expected behavior

- Run `shopify theme dev`
- Open the browser (Safari)
- Type the store password
- It must load the main page of the theme

Chrome

### Actual behavior

- Run `shopify theme dev`
- Open the browser (Safari)
- Type the store password
- It reloads the password page

**Safari:**

https://user-images.githubusercontent.com/1079279/182106288-3585af34-15e7-4adf-8478-a2bfc6f0c083.mp4

**Chrome:**

https://user-images.githubusercontent.com/1079279/182106270-0cfc49ca-2c26-4143-b6e8-b34ee72cf272.mp4

### Operating System

macOS

### CLI version (run `shopify version` if you're not sure)

2.20.1

**Comment by cazuba** [comment]
> It's not ideal by any means, but I was able to work around this by going to Chrome, logging in with the site password, then copying the token it generates as a cookie to Safari.
> 
> Open DevTools in Chrome, go to the Application tab, then Cookies on the left. Search for `storefront_digest`, and copy the value. Then in Safari, go to your site, open Web Inspector and go to the Storage tab and select Cookies. Add a new cookie with the same name, paste the value, and access another page on your store.

This worked for me!
Thanks @trvswgnr

**Comment by dspeake** [comment]
Still present using:

Safari Version 16.3 (18614.4.6.1.6)
@shopify/cli/3.44.1 darwin-x64 node-v19.7.0

**Comment by dspeake** [comment]
Still present using:

Version 16.3 (18614.4.6.1.6)
@shopify/cli/3.44.1 darwin-x64 node-v19.7.0

**Comment by MagnusFischer** [comment]
I'm having this exact issue as well.

**Comment by Jamflynt** [comment]
same issue here using
Safari version: 16.5.1
Shopify CLI version: 3.46.1

Works in Chrome but does not work in Safari

**Comment by kitkatpapi** [comment]
same issue here doesnt work on chrome or safari

**Comment by kenji-twp** [comment]
Still relevant

**Comment by lmartins** [comment]
Seeing the same thing.

**Comment by adrienpicard** [comment]
Still happening using `@shopify/cli/3.47.5 darwin-arm64 node-v20.4.0`

**Comment by Khreno** [comment]
Still happening using Shopify CLI version 3.48.3

**Comment by kenji-twp** [comment]
Still relevant

**Comment by kenji-twp** [comment]
still relevant

**Comment by u-foka** [comment]
Hi,

Definitely still having trouble with safari using shopify admin this issue is one of those...

When opening the theme editor I got these messages (found no way in site settings of safari to get rid of those) and can't get rid of that password screen.

![CleanShot 2023-10-15 at 17 25 54](https://github.com/Shopify/cli/assets/125336/01b3db8a-5997-4268-80f3-cb1d00b2410f)

**Comment by u-foka** [comment]
Ok, this is lame... YES THIS IS STILL RELEVANT! Will we need to poke it every 3 weeks arguing with a stupid robot while noone from shopify gives a * about it?! :(

**Comment by u-foka** [comment]
> Hello, 
> 
> 
> 
> I have the same problem being Nov 15, 2023. 
> 
> 
> 
> I can't connect on Safari but it works fine on Chrome. 
> 
> 
> 
> Is there a workaround?

Use firefox 🙈😇

**Comment by fawaz-alesayi** [comment]
One workaround that worked for me is to use [Cloudflare Quick Tunnels](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/trycloudflare/)

```bash
cloudflared tunnel --url http://localhost:9292
```

Then access the theme preview this way

**Comment by jbasoo** [comment]
Just ran into the same problem. Safari Version 16.6 (18615.3.12.11.2). Kinda wild that this is over a year old and doesn't seem to be any movement at all.

**Comment by superfantastic** [comment]
2024 here and yes, this is still happening, using CLI v3.53.0 and Safari v17.2.1.

**Comment by knightz0ne** [comment]
Still relevant

**Comment by nothinglastsforever** [comment]
Still happening in Chrome, latest version.

**Comment by tanguyp14** [comment]
Still relevant
