### ISSUE TITLE
[Feature]: Make it easier to scaffold things

### ISSUE THREAD

**Issue by marvinhagemeister** [Shopify/cli#1158]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

New feature

### Overview

Add support for `yarn create shopify` that opens a wizard that guides the user through what they want to do. This enables third party dev with little knowledge about our ecosystem to get started right away. A good example of this is [vite](https://github.com/vitejs/vite). They nailed the UX there.

### Motivation

I always forget the exact command to scaffold a checkout extension and typically do not have the shopify CLI installed globally. That's why the `<pkg-manager> init/create` commands were born but it looks like we're not supporting those. So I always need to go to the correct page in the docs and pick the correct command to get started.

**Comment by amcaplan** [comment]
We support `yarn create @shopify/app` or `npm init @shopify/app`. This is the recommended way to create an app, [per our docs](https://shopify.dev/apps/getting-started/create#step-1-create-a-new-app). Is there something else missing?

**Comment by marvinhagemeister** [comment]
TIL, didn't know about these. Maybe it's mostly an issue with documentation. When I go to the page about [checkout extensions](https://shopify.dev/api/checkout-extensions/checkout) there is no hint on how to get started or what the commands are.

**Comment by amcaplan** [comment]
Closing as we're tracking this further in the docs project.
