### ISSUE TITLE
Support for no-color

### ISSUE THREAD

**Issue by MeredithCastile** [Shopify/cli#1161]
We should support --no-color (and NO_COLOR?). In conversation about this, @gonzaloriestra cited [this resource](https://no-color.org/).

**Comment by amcaplan** [comment]
I started on this on [this branch](https://github.com/Shopify/cli/compare/main...no-color) but ran into challenges with CLI2 where logging isn't as centralized. I wonder if it's worth waiting until themes is fully ported over.

**Comment by matteodepalo** [comment]
Have we tried using the `FORCE_COLOR=0` flag? I think this is what `chalk` (our colorizer library) respects. Everything that is rendered by the new UI components will respect this flag.

**Comment by gonzaloriestra** [comment]
Yep, [we are checking that env var](https://github.com/Shopify/cli/blob/afe5415773d64949ee6900bf187f781cbdb3885a/packages/cli-kit/src/public/node/output.ts#L418) and it works. So I guess we just need to support the standard variable as well and the flag.

**Comment by amcaplan** [comment]
Yes, still relevant. I plan to work on this soon.
