### ISSUE TITLE
[Bug]: permissions problem when trying update-url command with partner cli token

### ISSUE THREAD

**Issue by rhyek** [Shopify/cli#1164]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

when running `shopify app update-url` command in a CI environment and having the `SHOPIFY_CLI_PARTNERS_TOKEN` environment variable set, i should be able to successfully run the command.

i am currently already able to to run `shopify app deploy` this way.

### Actual behavior

running the command results in the following error:
```bash
yarn run v1.22.1
$ shopify app update-url --api-key=xxx --app-url=https://myapp.com --redirect-urls=https://myapp.com/api/auth/callback
╭─ error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                   │
│  You do not have the necessary permissions to update this app                                                                                     │
│                                                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### Reproduction steps

1. be in a ci environment without a logged in shopify cli
2. set `SHOPIFY_CLI_PARTNERS_TOKEN` environment variable which currently successfully allows `shopify app deploy`
3. run the `shopify app update-url` command with necessary command line arguments

### Operating System

ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.36.0

### Shell

bash

### Node version (run `node -v` if you're not sure)

16

### What language and version are you using in your application?

node/javascript

**Comment by kythin** [comment]
Just his this one myself :) +1 please!
