### ISSUE TITLE
[Feature]: remove batch job termination confirmation for Windows

### ISSUE THREAD

**Issue by tomorrowagency-preston** [Shopify/cli#1165]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

New feature

### Overview

On Windows, when using _ctrl-c_ to stop the CLI I get a confirmation to terminate the CLI. I find this feature to be an annoyance. I'm never going to accidentally press that key combo in this context. Also, this confirmation didn't exist in v2, nor Theme Kit if I remember correctly. I'm requesting that you remove it, please.

![image](https://user-images.githubusercontent.com/113131178/213543269-bbd0c8c2-7caf-48c1-88b8-57283362b765.png)

### Motivation

I work at an agency, where I need to work on code for multiple shops everyday. I am starting and stopping the CLI many times per day, and this extra step to confirm the termination of the tool is annoying and slightly slows me down.

**Comment by amcaplan** [comment]
Also... closing as this is already covered by [this issue](https://github.com/Shopify/cli/issues/1104) from just a few days ago. I'll link from there.

**Comment by tomorrowagency-preston** [comment]
> It seems like you're using CLI3, I'll move the issue to that repo.

@amcaplan the URL for my issue and the one you linked me to are the same: gh.com/shopify/cli/issues

how is the other one an issue for CLI 3 but mine isn't? Could you please help me by letting me know how to post an issue for CLI 3 in case I need to in the future? I'm confused. Thank you.

**Comment by amcaplan** [comment]
You originally posted to https://github.com/Shopify/shopify-cli/issues

I've moved it to https://github.com/Shopify/cli/issues which is the right place to post CLI 3 issues.
