### ISSUE TITLE
[Feature]: Render `.` in the CLI UI kit `TokenItem[]` API without extra space

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#1171]
### What type of change do you want to see?

New feature

### Overview

Currently, when we specify a `.` in the end of sentences with the `TokenItem[]` API, we face an extra space:

![213715431-79e4890b-7c67-487a-92b4-5adf9329b31e](https://user-images.githubusercontent.com/1079279/213716034-6877c2bd-d23d-475d-a345-35c51159d3c6.png)

```typescript
renderSuccess({
  headline: [
    'The theme',
    ...themeComponent(theme),
    'is now live at',
    {
      link: {
        label: previewUrl,
        url: previewUrl,
      },
    },
    '.',
  ],
})
```

May we consider rendering `.`s differently to avoid that scenario?

**Comment by matteodepalo** [comment]
@karreiro This isn't documented well I admit it, but there is a `{ char: "." }` token which outputs a character without any extra space which you can use in this case. This week I'm going to tackle documentation of UI kit properly.
