### ISSUE TITLE
[Bug]: yarn dev / checkout extensions / --tunnel-url

### ISSUE THREAD

**Issue by awd** [Shopify/cli#118]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

extension

### Expected behavior

Running `yarn dev` with a custom tunnel url should work, and the extension preview and dev-console should also work.

Run: `yarn dev --tunnel-url=https://shopify-cli-bugs.ngrok.io`

Visit: `https://shopify-cli-bugs.ngrok.io/extensions/dev-console`

The dev console should load.

### Actual behavior

When accessing the defined tunnel url dev console, the browser shows an error like:

```
ERR_NGROK_3200
Tunnel shopify-cli-bugs.ngrok.io not found
```

### Reproduction steps

1. run: `yarn dev --tunnel-url=https://shopify-cli-bugs.ngrok.io`
2. visit: `https://shopify-cli-bugs.ngrok.io/extensions/dev-console`
3. error

You'll need to use a custom tunnel name through ngrok.

When `yarn dev` generates a random ngrok url - the dev console loads, as does the checkout ui extension preview.

### Operating System

Mac OS Monterey

### CLI version (run `shopify version` if you're not sure)

latest / 3.x

### Shell

iTerm2

### Ruby version (run `ruby -v` if you're not sure)

3.1.2

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by awd** [comment]
Hey @alvaro-shopify :wave: Thx for the detailed response!

I've setup the tunnel as you have outlined here, all works as expected in this case.

However, when the repo contains both a checkout extension and a web (embedded app), the trouble begins. The checkout extension takes the priority when visiting `dev-console` the browser resolves and the UI appears.

When trying to visit the embedded app url (generated by `yarn dev`) you'll receive an error message in the browser:
`{"message":"Route GET:/?shop=redacted.myshopify.com&host=redacted not found","error":"Not Found","statusCode":404}`

If I were only working on the checkout extension, then we have no issues, but if I were working on the embedded app - this url is not resolvable, the app cannot be installed, shopify api webhooks would fail.

It's all new, so I am trying to help share a use-case and where I am bumping into unexpected results. 

Happy to help out and try other ideas, just let me know :)

**Comment by gonzaloriestra** [comment]
@awd what Node version are you using? Could you try with Node 17 or 18? We have just found a potential issue related to this when using older versions (still investigating).

**Comment by shauns** [comment]
Hi @awd -- struggling to reproduce this one I'm afraid, and this is a scenario that internally we test out a lot. So it would be good to get to the bottom of this -- Some suggestions:

- make sure there are no other ngrok processes (or other tunnels) running, besides the one you're intending. We've seen this case internally in the past
- be sure to upgrade to the latest version of the CLI, in case of bug-fixes: we do update quite frequently
- and as @alvaro-shopify mentioned, the format of `--tunnel-url` is `https://your-tunnel-domain-name:port` - with the port number

Let us know how you get on.

**Comment by awd** [comment]
Hi @shauns - apologies for the delay in responding here.

* Confirming the only tunnel running is the one I am intending (`shopify-cli-test.ngrok.io` used in place of my own url).
* Running latest CLI version 3.8
* Confirming the tunnel url is `https://shopify-cli-test.ngrok.io:3000`


This context may help.
The project includes a theme extension, checkout extension, and web app (Rails).

Before CLI 3 - the rails app runs inside a docker container, along with a few other processes (webpacker, background job server, etc).

```docker
version: '3.2'

services:
    server:
      stdin_open: true
      tty: true
      build: .
      command: bundle exec puma -C config/puma.rb
      ports:
        - '3000:3000'
      env_file: .env
      environment:
        RAILS_ENV: development
        RACK_ENV: development
        DATABASE_HOST: host.docker.internal
      volumes:
        - .:/usr/src/app
```

Puma is configured on port 3000

Running `ngrok http --subdomain shopify-cli-test 3000` correctly points the requests to the docker service when running `docker compose up`. No issue there.

Now when running `yarn dev --store=test-store --tunnel-url=https://shopify-cli-test.ngrok.io:3000` with the web-app command in `shopify.web.toml`:
```yaml
type="frontend"

[commands]
dev = "docker compose up"
```

This fails with the error about ports already in use.

```
Command failed with exit code 1: docker compose up
Error response from daemon: Ports are not available: listen tcp 0.0.0.0:3000: bind: address already in use
```

I know this is slightly different than originally posted, but have spent more time digging into this today. When I simply remove the `service` for the web app in the docker compose file, then the checkout extension / dev tools will load - but then obviously no web service.

Please let me know if you have more questions or ideas, would any combination of setting frontend or backend ports work? Are those set as command line flags? https://shopify.dev/apps/tools/cli/migrate#provided-variables

**Comment by renatolovato** [comment]
@awd I faced the same issue, and the solution for this is that we have to start your tunnel first in a different terminal. For example:

**First terminal you will start your tunnel**

`
ngrok http --subdomain=your_subdomain 8080
`

**Second terminal you will start you app:**

`
yarn dev --tunnel-url=https://your_subdomain.ngrok.io:8080
`

**Comment by webvs2** [comment]
@pepicrft   Could you please help me figure out what's going on? I've been dealing with this for a long time.

<img width="1263" height="821" alt="Image" src="https://github.com/user-attachments/assets/09dc0313-ae8c-409d-aa64-b9220f95e18d" />

<img width="1329" height="777" alt="Image" src="https://github.com/user-attachments/assets/1d4918e4-7a05-46ad-924b-dd169629bf56" />

<img width="2517" height="1166" alt="Image" src="https://github.com/user-attachments/assets/3033ca62-006d-4415-a66e-ed4081ce2ec0" />

**Comment by gonzaloriestra** [comment]
Hi! Not sure what could be happening, but have you tried with the default cloudflare tunnel or simply localhost? You can find more info here: https://shopify.dev/docs/apps/build/cli-for-apps/networking-options

Another thing that sometimes helps with `ERR_TOO_MANY_REDIRECTS` is clearing the cookies.

**Comment by webvs2** [comment]
@gonzaloriestra  The default tunnels are almost unavailable in my area. I can try the local ones, but the current problem is that I'm following the procedures strictly according to the documentation, but it still doesn't work. I even don't know which specific steps are causing the issue.

**Comment by RStaff** [comment]
Hey awd — saw the issue you hit with Tunnel or Cloudflare issue during Shopify app development.

This is very close to a Shopify dev setup problem I recently cleaned up around preview, tunnel, and embedded loading behavior.

If it helps, I can take a quick look and point you at the fastest stable path.

**Comment by RStaff** [comment]
Hey awd — 

I’ve worked through similar Shopify dev issues and built a stable fix path for them.

Happy to take a quick look if you want another set of eyes:
http://dev.abando.ai/fix
