### ISSUE TITLE
[Bug]: Font files 500 (Internal Server Error)

### ISSUE THREAD

**Issue by anteksiler** [Shopify/cli#1199]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Fonts should work on 127.0.0.0:9292

### Actual behavior

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/1000992/214290885-edc70490-22fe-4f99-9f83-2f3b2492060f.png">

Font files are not loaded on the browser.

### Reproduction steps

1. Brew uninstall shopify-cli
2. Brew tap shopify/shopify
3. Brew install shopify-cli
4. shopify theme dev

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.36.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.4.0

### What language and version are you using in your application?

liquid

**Comment by karreiro** [comment]
(related to https://github.com/Shopify/cli/issues/1103)

**Comment by anteksiler** [comment]
Updated ruby from 3.1.2 to 3.2.0 and that did not solve it either.

**Comment by karreiro** [comment]
Thank you for the extra details, @anteksiler!

Could you please share the request ID that appears when the `http://localhost:9292` page loads? With that information, I can get much more context about the issue you're facing.

Here's how to get it:

![](https://user-images.githubusercontent.com/1079279/178477183-b83ad1cc-ea75-4cc1-b5f9-46e42fd00f0b.png)

Also, I'm assuming that fonts are not loading on `http://localhost:9292` but are working in the preview URL. Is that correct?

![image](https://user-images.githubusercontent.com/1079279/214570691-e4c14df1-0745-4af9-9182-e3159c67fc2b.png)

Thanks again, @anteksiler!

**Comment by anteksiler** [comment]
Hey @karreiro, much appreciated. The request ID is:

X-Request-Id: 88b8ac30-db4d-4701-9ce3-be66aaf4981d

Yeap, theme preview is working correctly.

**Comment by dir** [comment]
Very quick and dirty fix for those on Mac using Homebrew that need it working...

*Not recommended*

1. Uninstall shopify-cli using `brew uninstall shopify-cli`
2. Uninstall ruby using `brew uninstall ruby`

3. Copy the brew formula code for shopify-cli here: https://github.com/Shopify/homebrew-shopify/blob/master/shopify-cli.rb

4. Create a new .rb file in `$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/`, name it `custom-shopify.rb`.

5. Change the following lines:
    1. Line 7 (assuming you used the file name `custom-shopify.rb`), change `ShopifyCli` to `CustomShopify`
    2. Line 14 `depends_on "ruby"` to `depends_on "ruby@3.1"`
    3. Line 45  `Formula["ruby"]`  to `Formula["ruby@3.1"]`

6. Run `brew install custom-shopify`

7. Now you're all set to run shopify commands like before, i.e. `shopify theme dev`

I would highly recommend uninstalling this using `brew uninstall custom-shopify` and then `brew uninstall ruby@3.1` when this update gets released, as this is "broken" build of Shopify and will not be good for future updates. 

Happy coding!

**Comment by anteksiler** [comment]
Hi @Poitrin , I noticed that you created the PR in CLI version 2.0. Will it also fix the issue in CLI 3.0?

**Comment by Poitrin** [comment]
Sorry that GitHub closes issues after merging a PR, but I hope that both CLI versions will be released ASAP :)

**Comment by nelsonvassalo** [comment]
Bumping this
