### ISSUE TITLE
[Feature]: Prefer user installed node version when available.

### ISSUE THREAD

**Issue by james-prado** [Shopify/cli#1202]
### What area(s) will this request affect?

Function

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Prefer valid user installed version of nodejs if available.

### Motivation

Switching between projects sometimes requires using different versions of nodejs. [nvm](https://github.com/nvm-sh/nvm) makes switching versions much easier, but because Shopify CLI depends on node's homebrew formula I can no longer switch versions when moving between projects.

Nvm isn't compatible with node's homebrew formula. It'll always prioritize the homebrew formula which prevents any other installed node version from being used.

There is a [work around](https://github.com/nvm-sh/nvm/issues/2686#issuecomment-1010094279), it requires moving all node versions installed by nvm to the beginning of PATH. This isn't ideal though since these problems will still occur for anyone using the default "out of box" configuration of these tools.

```shell
# Dynamically add all node versions installed via nvm to beginning of PATH,
# to take precedence over any other node version
# (i.e. installed via brew install node or any formula dependencies)
for f in $HOME/.nvm/versions/node/*; do
	if [ -d "$f" ]; then
		PATH=$f/bin:$PATH
	fi
done
```

**Comment by matteodepalo** [comment]
Hi @james-prado thank you for flagging this, I'll bring it up with the team.

**Comment by matteodepalo** [comment]
@james-prado This seems to be a local setup issue as the node version picked up by your terminal environment is going to depend on how your binaries resolve. There isn't much we can do on our side to make it so nvm is picked up before homebrew by default.

**Comment by vaelu** [comment]
@matteodepalo I don't really get why this should be a setup issue, since your shopify-cli brew package has node as dependency and always downloads it, also when it's already installed via nvm.
