### ISSUE TITLE
Why not replace Partners with this CLI?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#1216]
### What area(s) will this request affect?

App

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Let's face it. The underlying utility of the CLI is nice and even, a marvel. Yay! 

Let's also face it. It is super clunky and terminal-based usage can only hit a proverbial wall and fast. 

I am curious as to why all this effort has not been motivated to replace the clunky, old, Partner aspect of using Shopify? Why spend all this effort on a CLI tool when you could dress it up with Polaris, dump it in the Partner portal, and we'd all benefit from the CLI, albeit with more concise power, and nicer experiences?

### Motivation

Logging in to Shopify, and working with the Partner dashboard to work with Apps, stores, extensions, etc, is a major drag and basically sucks. CLI seems to offer a lot of nice workflow opportunities, but terminal work is primitive at best even if the power provided is excellent. So merging the two, and throwing out the bad aspects of both, results in a sweeter Partner experience for all.

**Comment by matteodepalo** [comment]
@resistorsoftware Thank you for your feedback. The team is actively working on gradually incorporating more and more features from the Parteners Dashboard into the CLI itself. Developer experience and the CLI are very important to us so we want to make sure that when we add this functionality to the CLI it can cover all the use cases and be better than what we had. I'll bring your feedback to the team, but in the meanwhile I'll close this issue as it's not immediately actionable.
