### ISSUE TITLE
[Bug]: Windows compatibility using Bundler

### ISSUE THREAD

**Issue by gkrauthamer** [Shopify/cli#1234]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Expected to use Shopify theme CLI commands:
`shopify theme pull -d --verbose`

`shopify theme dev -t mytheme --verbose`

### Actual behavior

CLI execution stalls. Using verbose mode, execution stalls on steps invoking bundle exec. It looks like these steps may not be correct 3.x syntax:

Command:
`shopify theme pull -d --verbose`

Result: 
```
Execution stalls at
2023-01-26T23:32:58.863Z:
Running system process:
  · Command: bundle exec shopify theme pull c:/xampp/htdocs/mydir --development
  · Working directory: c:\xampp\htdocs\mydir
```

Comment: 3.x syntax does not appear to include the directory path, and there is variation in the slashes. Is this "bundle exec" line coded correctly for 3.x?

Command:
`shopify theme dev -t mytheme --verbose`

Result:
```
2023-01-26T23:36:28.378Z:
Running system process:
  · Command: bundle exec shopify theme serve . --theme mytheme --live-reload hot-reload
  · Working directory: c:\xampp\htdocs\mydir
```

Comment: "shopify theme serve" is not a 3.x command. Is this "bundle exec" line coded correctly for 3.x?

Other commands like "shopify theme init" and "shopify theme open" do work in my CLI, but these do not show Bundler usage in verbose mode, so I have been unable to determine if there is a general issue with Bundler or my overall setup, or if there is a coding issue with these commands that I have cited.

### Reproduction steps

I've followed the Windows install process at https://shopify.dev/themes/tools/cli/install. Steps to reproduce should be covered above.

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.38.0

### Shell

Node.js command prompt

### Node version (run `node -v` if you're not sure)

18.12.1

### What language and version are you using in your application?

Ruby 3.1.3p185, Bundler 2.4.5

**Comment by Arkham** [comment]
Hi there, thanks for reporting! I'll page our friends at @Shopify/theme-developer-tools which might be able to help you.
