### ISSUE TITLE
[Bug]: Running theme dev moves current directory?

### ISSUE THREAD

**Issue by lukecharle** [Shopify/cli#1251]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Run the `shopify theme dev` within my shopify directory

### Actual behavior

Appears to run in a different directory because I'm getting the following message:

"It doesn’t seem like you’re running this command in a theme directory. Are you sure you want to proceed?"

### Reproduction steps

So my webpack build I use was on 2.0, seemed simple enough to just switch over the command which was originally:

`"shopify:serve": "cd shopify && shopify theme serve",`

and have now changed to:

`"shopify:serve": "cd shopify && shopify theme dev",`

This worked absolutely fine with 2.0 but now with 3.0 I'm getting the error it isn't in the correct directory?

The main task I'm running is this:

`"start": "run-p -sr shopify:serve webpack:watch",`

Also worth mentioning, I tried changing the 'shopify:serve' task to this too:

`"shopify:serve": "cd shopify && node ../.config/path.js && shopify theme dev",`

With path.js containing:

`console.log('CURRENT PATH => ', process.cwd());` and it does indeed say its within the `shopify` directory. So I'm not sure what's going on here?

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.39.0

### Node version (run `node -v` if you're not sure)

v19.5.0

**Comment by bansavage** [comment]
hey @lukecharle , I am running into same issue!
Are you using Themelab setup? Based on these commands you listed, it seem you may be. I am using ThemeLab and CLI v3 is not recognizing the subshell directory has changed!

**Comment by lukecharle** [comment]
> hey @lukecharle , I am running into same issue!
> Are you using Themelab setup? Based on these commands you listed, it seem you may be. I am using ThemeLab and CLI v3 is not recognizing the subshell directory has changed!

I am indeed! Really don’t understand how this is any different to 2.0 though. Because it would still expect the Shopify theme structure so something is moving it out of the correct directory

**Comment by lukecharle** [comment]
@Arkham I know its another webpack build, but could you just try cloning this repo - https://github.com/uicrooks/shopify-theme-lab and changing `shopify theme serve` to `shopify theme dev`?

This is the build I've used, I don't see it being an issue with anything from it though?

I will try your suggestion

**Comment by lukecharle** [comment]
`cd shopify && npm exec -- shopify theme dev` does the job for me it seems!
