### ISSUE TITLE
[Bug]: Commands fail within npm subshell, do not respect package.json script commands

### ISSUE THREAD

**Issue by bansavage** [Shopify/cli#1253]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Shopify should recognize the npm subshell directory has changed to a directory that matches correct theme architecture.

### Actual behavior

If `package.json` contains a script:

```
"dev": "cd shopify && shopify theme dev"
```

The CLI does not respect that the directory has changed in the `npm` subshell. It errors with `It doesn't seem like you're running this command in a theme directory"`.

Shopify CLI v2.X never had this issue.

### Reproduction steps

1. Create root directory folder
2. Add `package.json` file at root that has a script of `"dev": "cd shopify && shopify theme dev"`
3. Create directory titled "shopify" that has Dawn theme code
3. Run command `npm run dev`

### Operating System

MacOS Ventura 13.2

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.39

### Shell

bash

### Node version (run `node -v` if you're not sure)

14.17.0

### What language and version are you using in your application?

Node 14.17.0, Ruby 2.7, NPM v6.14.13

**Comment by bansavage** [comment]
Similar to https://github.com/Shopify/cli/issues/1253

**Comment by lspoor** [comment]
Think you misreferenced mine @bansavage ;) #1251

**Comment by bansavage** [comment]
Yes @Arkham it does

Image below showing Shopify folder

![image](https://user-images.githubusercontent.com/15312623/215810881-51bda851-c166-48af-9ceb-6c4e624d1a13.png)

**Comment by Arkham** [comment]
can you try this fix? https://github.com/Shopify/cli/issues/1251#issuecomment-1410111016

**Comment by bansavage** [comment]
Thanks @Arkham 
Using this code fixes it for me:
`shopify theme dev --path shopify`

And, for the record, the fix in issue #1251 does NOT work for me
