### ISSUE TITLE
[Feature]: Local server

### ISSUE THREAD

**Issue by lukecharle** [Shopify/cli#1259]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

So I know when using the CLI it allows you to access at http://127.0.0.1:9292 and then also provides the site URL, e.g.  https://[site].myshopify.com/?preview_theme_id=[id].

I've setup my webpack system to split my JS into bundles and chunks, so when I'm accessing http://127.0.0.1:9292 it serves the assets like: `../assets/template.collection.js` for example. This is while I'm in development environment, so if I visited https://[site].myshopify.com/?preview_theme_id=[id] the assets will fail to load because they're not being accessed via the CDN url. I can't think of anyway to specify a different path while in development but on the actual site url. 

This would be incredible useful to have usage of especially when trying to develop the site for a mobile so needing to access it via my iPhone. 

If anyone has any ideas of how to make this possible within a webpack build rather than adding the feature to the CLI it would be great to know :)

### Motivation

Developing a theme for my mobile is difficult with the setup of JS bundling I use

**Comment by Arkham** [comment]
Hi, thanks for your proposal, I'll tag @Shopify/theme-developer-tools so they take a look at this.

**Comment by lukecharle** [comment]
Thanks @Arkham ! As mentioned not sure if if this can just be added to be webpack build or if it needs to be actually added into the CLI, either option would be fantastic :)

**Comment by lukecharle** [comment]
@karreiro What's the timeframe on this if you have one?

**Comment by mfrederico** [comment]
I'd like to post something here - maybe this can help someone in the future:

When setting up a new app via the "npm run dev":
The redirect seems to always be 127.0.0.1 .. however I am developing on a remote server.  dev.mydomain.com

If you have access to the server that you're developing on you can use ssh port-forwarding:
`ssh -L3456:127.0.0.1:3456 dev.mydomain.com`

It will time-out but that's okay because you want the link.

**Comment by karreiro** [comment]
Thank you @lukecharle for reporting this issue, and @vi- for the heads-up.

This issue has been resolved and the fix is available on Shopify CLI **3.55.0**.

**Comment by lukecharle** [comment]
@karreiro Has this definitely been fixed?

Just wanting to confirm, I've visited the preview link and files still aren't loading, for example with my Vite setup I have the following file which fails to load:

https://localhost:5173/src/entrypoints/theme.scss

Should this work, or is there a way to handle this?
