### ISSUE TITLE
[Bug]: App development don't work starter

### ISSUE THREAD

**Issue by thedarkknight197** [Shopify/cli#1266]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Following https://shopify.dev/apps/getting-started/create when start ngrok server with npm run dev, sharable app url doesn't work

### Actual behavior

<img width="1680" alt="Schermata 2023-02-01 alle 23 42 59" src="https://user-images.githubusercontent.com/37689698/216180851-58b58ba5-2ff9-447f-8b57-b4c6f20ab0aa.png">

### Reproduction steps

1. follow the guide

### Operating System

MacOS M1

### Shopify CLI version (check your project's `package.json` if you're not sure)

 "@shopify/app": "3.39.0",     "@shopify/cli": "3.39.0"

### Shell

bash

### Node version (run `node -v` if you're not sure)

v16.3.0

### What language and version are you using in your application?

Node v16.3.0

**Comment by Arkham** [comment]
Hi there, I'm afraid there is not enough information for me to debug this issue. Could you try following the tutorial here https://ngrok.com/docs/getting-started and checking if you can create an ngrok tunnel?

**Comment by thedarkknight197** [comment]
I found the problem! Every time that is run the dev script will change the ngrok tunnel.
Please write in doc that need ro change the url in the app configuration in Shopify partner dashboard to help new user to know about.

Updating here the app work well in development!
