### ISSUE TITLE
[Feature]: App extension development - Ability to customize which files are pushed 

### ISSUE THREAD

**Issue by ozzyonfire** [Shopify/cli#1271]
### What area(s) will this request affect?

Extension

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Currently when developing an app extension the CLI attempts to push all subfolders into the app. However, during development we may have other folders in that directory we want to ignore (node_modules, dist, babel.rc, webpack, etc.). 

There is no way (that I know of) to ignore or customize what gets parsed and sent up. 

We could use an included .gitignore file to specify what folders and files to ignore, or even use the .theme-check.yml file to determine extra customization on parsing.

### Motivation

I was attempting to build a simple app extension, and the inclusion of my node_modules folder seemed to absolutely destroy my CPU. It seems that ruby was doing some parsing on this folder. 

Also, I'm trying to do some weird stuff with metafields inside my {% schema %} and it is not letting me push my *.liquid files because of a parsing error. I'd like to just be able to ignore the parser and force the changes up no matter what.

**Comment by Arkham** [comment]
Hi there, just double checking, are you trying to create a `theme app extension`?
