### ISSUE TITLE
[Bug]: shopify extension check - command not found

### ISSUE THREAD

**Issue by ozzyonfire** [Shopify/cli#1273]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

According to the docs, we should be able to run `shopify extension check` to lint our extension.
https://shopify.dev/themes/tools/theme-check/commands#extension-check

### Actual behavior

`command extension:check not found`

### Reproduction steps

1. install @shopify/cli and @shopify/theme globally from npm
2. Navigate to an extension folder
3. Run `shopify extension check`

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.39

### Shell

powershell

### Node version (run `node -v` if you're not sure)

v16

### What language and version are you using in your application?

Ruby, Node

**Comment by Arkham** [comment]
Hi there, thanks for reporting! That command is gone now, I'll ping @shainaraskas to update our doc.

**Comment by Spuffynism** [comment]
Hey @Arkham, sorry for commenting on a closed issue, but what replaces `shopify extension check`? Should we downgrade to a previous version of the cli to use the command?

Thanks.
