### ISSUE TITLE
While running npm run dev, I get "Couldn't find your Shopify Partners Organization Have you confirmed your accounts from he emails you recived?

### ISSUE THREAD

**Issue by nutragenix** [Shopify/cli#1294]
I am creating a new project in Shopify from CLI using this link https://shopify.dev/apps/getting-started/create.
using following command:
**npm init @shopify/app@latest**
Once the project is created I move to the project folder and run this command **npm run dev** . I get following message in the terminal.
![shopify error](https://user-images.githubusercontent.com/124570246/216939375-f6542728-2e85-4057-bbb3-5ef0fd89072d.jpg)

I have already logged in with partner account in all the browsers, not sure what am I missing. Could you guys help me understand this?

Shopify CLI version: 3.39.0
Node version: 18.13.0
NPM version: 9.3.1

**Comment by gonzaloriestra** [comment]
Hi, thanks for creating the issue. Have you received the email and confirmed the account as the error indicates?

**Comment by nutragenix** [comment]
One of my other team mates is doing the same and he is able to get the list of all the Partners account we have created. Initially, I thought may be the account is not verified via email. But if this was the case, even my team mate would have faced the same problem. But he didn't and he is able to run the project.

**Comment by pepicrft** [comment]
@nutragenix did you get a verification email? Also, are you able to log in in https://partners.shopify.com and see the organization there?.
