### ISSUE TITLE
[Bug]: `Shopify theme push` fails in @shopify/theme v3.40 with "The above error occurred in the <BoxWithTopBottomLines> component..."

### ISSUE THREAD

**Issue by natebennett21** [Shopify/cli#1302]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The `shopify theme push` command should work without errors.

### Actual behavior

The `shopify theme push` command fails with an error (all output is pasted in the `Stack trace` section of this issue). Note that although it says `The above error`, nothing was output above that, so I'm unclear as to the actual error happening.

I'm fairly certain that this bug was introduced in the 3.40 version of @shopify/theme, because when I pin that package to version 3.39, `shopify theme push` works as expected.

### Stack trace

```shell
The above error occurred in the <BoxWithTopBottomLines> component:

    at BoxWithTopBottomLines (file:///home/circleci/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/ui/components/Banner.js:20:34)
    at Banner (file:///home/circleci/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/ui/components/Banner.js:32:19)
    at FatalError (file:///home/circleci/.local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/ui/components/FatalError.js:9:23)
    at App (/home/circleci/.local/lib/node_modules/@shopify/theme/node_modules/ink/build/components/App.js:42:9)

React will try to recreate this component tree from scratch using the error boundary you provided, InternalApp.

Exited with code exit status 1
```

### Reproduction steps

1. Install latest version of Shopify CLI (3.40)
2. Run `shopify theme push` from a valid theme folder

### Operating System

Ubuntu 22.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.40.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.13.0

### What language and version are you using in your application?

Ruby 3.0.2p107

**Comment by isaacroldan** [comment]
Hi @natebennett21, could you test with the latest version (3.44.1). We've done some improvements on that part and this should not happen again. Let me know!

**Comment by natebennett21** [comment]
Hi @isaacroldan, I just tried this again with 3.44.1 and it worked as expected. Thanks so much!
