### ISSUE TITLE
[Bug]: Unable to deploy Teme app extension

### ISSUE THREAD

**Issue by Yamashou** [Shopify/cli#1311]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

On the Cli, they say the deployment is successful, but the draft doesn't exist. Before the update, it was working and I want it to go up to draft.

### Actual behavior

Deployment Successful
<img width="596" alt="スクリーンショット 2023-02-08 15 15 49" src="https://user-images.githubusercontent.com/15344499/217449893-f706dc99-0d4e-4136-9d44-8a7af2363cd7.png">

Drafts are not created forever.
<img width="882" alt="スクリーンショット 2023-02-08 15 15 24" src="https://user-images.githubusercontent.com/15344499/217449954-fed06fd2-aeca-423e-8a51-bcea793a981b.png">

### Reproduction steps

1. Create theme app extension
2. shopify app deploy
3. Check with your browser

### Operating System

Mac OS 13.1（22C65）

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.40.2

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.10.0

**Comment by kinngh** [comment]
Bump. Running into the same issue^

**Comment by clarkdave** [comment]
Here too. Deploying a theme extension works in CLI version 3.39 but not in 3.40. The CLI reports success but the extension page doesn't report any new pushes.

**Comment by Arkham** [comment]
Hi, thanks for reporting this issue! I've released `3.41.1` which should fix this issue.

**Comment by Yamashou** [comment]
@Arkham 
We have confirmed it works! 👍
