### ISSUE TITLE
[Bug]: [LoadError] cannot load such file -- wdm

### ISSUE THREAD

**Issue by superfein** [Shopify/cli#1314]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When I type `shopify theme dev` in the terminal the "viewing theme" details appear with no wdm-related error message.

### Actual behavior

When I type `shopify theme dev` in the terminal the "viewing theme" details appear but below them this error appears:

```
[Note] You cannot use gems with Shopify CLI.
[LoadError] cannot load such file -- wdm
       They are disabled.
       Please don't modify the CLI locally.
       If you would like to contribute to the CLI project, please refer to
       https://github.com/Shopify/shopify-cli/blob/main/.github/CONTRIBUTING.md

  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```

### Reproduction steps

1. Type `shopify theme dev` in the terminal on Windows 10
2. Error appears below "viewing theme" details
3. Tried `gem install wdm` in the terminal which did not solve the issue. 

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.40.3

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

v16.17.1

### What language and version are you using in your application?

Ruby v2.7.6

**Comment by gonzaloriestra** [comment]
Hi! Thanks for creating the issue. It should be fixed in the latest version (3.43.0).

**Comment by superfein** [comment]
Yes it is fixed in the latest version, thanks @gonzaloriestra!

**Comment by tarin-swanky** [comment]
I'm on the latest version and it wasn't fixed for me
