### ISSUE TITLE
[Bug]: theme dev does not work since environment

### ISSUE THREAD

**Issue by bakura10** [Shopify/cli#1320]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Hi,

I have upgraded to version 3.41 and renamed to environmnet instead of preset. I now have strange errors related to Ruby that I did not have:

```
/Users/xxxx/Sites/shopify-prestige/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

ExternalError: Command failed with exit code 1: bundle install
rbenv: version `3.1.0' is not installed (set by /Users/xxxx/Sites/shopify-prestige/node_modules/@shopify/cli-kit/assets/cli-ruby/.ruby-version)
```

Has dependencies changed?

### Actual behavior

It did not work

### Reproduction steps

1.
2.
3.

### Operating System

OS X

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.41.1

**Comment by gonzaloriestra** [comment]
Thanks! I think it may be a conflict with rbenv, changing the Ruby version because of an internal `.ruby-version` file. Could you please try again removing that file? You could do something like this:
```
mv ~/Sites/shopify-prestige/node_modules/@shopify/cli-kit/assets/cli-ruby/.ruby-version ~/Sites/shopify-prestige/node_modules/@shopify/cli-kit/assets/cli-ruby/.ruby-version.backup
shopify theme dev
mv ~/Sites/shopify-prestige/node_modules/@shopify/cli-kit/assets/cli-ruby/.ruby-version.backup ~/Sites/shopify-prestige/node_modules/@shopify/cli-kit/assets/cli-ruby/.ruby-version
```

Now that I check your path, I'm a bit confused. Have did you install the CLI?

**Comment by bakura10** [comment]
I'm installing Shopify CLI through npm @gonzaloriestra.

This used to work in prior version (reverting to older version works) so the issue is definitely coming from Shopify CLI here :)

**Comment by gonzaloriestra** [comment]
@bakura10 but are you installing it globally with `npm install -g @shopify/cli @shopify/theme`?

We have just released a new version (3.42) that should fix this issue. Could you upgrade and try again?

**Comment by kyrylo-soulandwolf** [comment]
@gonzaloriestra is it not possible to use CLI by installing it locally? 
if not, it really defeats the purpose of being portable and being on the same version with other developers working on the project :(

**Comment by gonzaloriestra** [comment]
The idea is to install it per project for apps and extensions, as they are NPM projects. But for themes, as they don't have a package.json by default, the recommended way is to install it globally.

Could you please elaborate a bit more on your use case and needs?

**Comment by gonzaloriestra** [comment]
I see, thanks a lot! In that case, I guess it makes sense and it should work as well. Have you tried with v3.42?

**Comment by kyrylo-soulandwolf** [comment]
Yep, I tried it when I saw your comment about the new 3.42 version but unfortunately, I see the same error :(

**Comment by gonzaloriestra** [comment]
Could you check if you still have the file `~/Sites/shopify-prestige/node_modules/@shopify/cli-kit/assets/cli-ruby/.ruby-version`? Which `@shopify/cli-kit` version can you see in your `package-lock.json`?

**Comment by kyrylo-soulandwolf** [comment]
I had to lock my version at 3.39 to be able to use it locally, so there isn't `cli-ruby` directory at all. After updating to 3.42 (that's the version in the lock file) the directory is there but `.ruby-version` file isn't.

**Comment by kyrylo-soulandwolf** [comment]
Ah, I'm sorry, I should've opened another issue. I just subscribed to this thread in the hope that my error would get resolved by the updates. The error I see is in my second comment here starting with `Your user account isn't allowed to install to the system RubyGems.`.

**Comment by vi-** [comment]
Same issue for me, also solved by running `SHOPIFY_CLI_BUNDLED_THEME_CLI=1 shopify theme dev`

**Comment by chouck-pthreemedia** [comment]
prepending commands with `SHOPIFY_CLI_BUNDLED_THEME_CLI=1 ` seems to work for me.  can anyone tell me why that works?

**Comment by gonzaloriestra** [comment]
We are doing some internal refactors to easily migrate commands from Ruby to Node (because most of the theme commands still rely on the CLI 2.x under the hood), and that flag forces to run it the old way.

We are going to release a new version now that disables it by default, as there are still some issues. Sorry for the inconvenience!

**Comment by dgtlwrks** [comment]
`shopify theme check`  gave the following error on the newest cli

`bundler: not executable: /usr/local/Cellar/shopify-cli/3.44.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify`

SHOPIFY_CLI_BUNDLED_THEME_CLI=1

also fixed this issue

**Comment by syedsimanta03** [comment]
Quite impossible to do theme development on windows with shopify CLI, Themekit was far better.

**Comment by syedsimanta03** [comment]
shopify theme dev --store {zaveernishu}

Nothing running, no prompt
