### ISSUE TITLE
[Bug]: No longer bundle customer theme templates

### ISSUE THREAD

**Issue by bakura10** [Shopify/cli#1321]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Since Shopify CLI 3.39, the command shopify theme bundle no longer bundle customers/*.json template files.

### Actual behavior

None of the customers template are bundled. Reverting to Shopify CLI 3.37 fixes the issue (there is no Shopify CLI 3.38 so could not try on this).

### Reproduction steps

1.
2.
3.

### Operating System

OSX

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.39+

**Comment by Arkham** [comment]
hey @bakura10, we had to release quite a few changes this week as all teams across the company wanted to ship their new features for a huge release, which I'm happy I can finally share: https://www.shopify.com/editions/winter2023

from next week we'll regroup and figure out a better way to integrate all these changes coming at the same time, so next time we can do better at this. thanks for your patience!
