### ISSUE TITLE
[Bug]: fatal: not a git repository

### ISSUE THREAD

**Issue by superfein** [Shopify/cli#1327]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When I type `shopify theme dev` into the terminal the "viewing theme..." box appears with the temporary theme development links.

### Actual behavior

When I type `shopify theme dev` into the terminal this error appears above the "viewing theme..." box:

`fatal: not a git repository (or any of the parent directories): .git`

I at first thought this was caused by some mistake I made when initializing my local Git repo, but after carefully re-creating the local Git repo I am quite confident this error message is somehow being caused by Shopify CLI.

### Reproduction steps

1. Initialize a new local git repo in a shopify theme project folder.
2. Type `shopify theme dev` into the terminal.
3. For me, there is a git error that appears first, and appears to slow down the Shopify development server startup process.

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.41.1

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

v18.14.0

### What language and version are you using in your application?

Ruby v2.7.6

**Comment by briandesp** [comment]
I downgraded to the old version but still having now the same issues . I don't know what to do.

**Comment by briandesp** [comment]
npm install -g @shopify/cli@3.34.0  @shopify/theme

However rolling back didn't help me :( I am stuck and can't work on my shopify themes

**Comment by superfein** [comment]
I really appreciate all the hard work from the team behind shopify-cli. That being said, it sometimes feels like updates are pushed too quickly without enough consideration for work-interrupting bugs, particularly for Windows users. I know, Windows is a pain in the butt, but these interruptions make developing a Shopify theme an extra challenge.

**Comment by jesuismaxime** [comment]
> I really appreciate all the hard work from the team behind shopify-cli. That being said, it sometimes feels like updates are pushed too quickly without enough consideration for work-interrupting bugs, particularly for Windows users. I know, Windows is a pain in the butt, but these interruptions make developing a Shopify theme an extra challenge.

I feel you, juste lost an hour to try to make it works(upgrade from v2 to v3 to find all my base stack broken..).

**Comment by superfein** [comment]
For me, `shopify-cli` v3.43.0 solves this issue.
