### ISSUE TITLE
[Feature]: Introduce the `shopify theme console` command

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#1344]
## This command is currently released as a beta feature

Please, up-vote 👍 or down-vote 👎 for it.

---

### Overview

Read–Eval–Print Loop (REPL) tools are excellent for supporting experienced developers that want to try some snippets quickly but are also great for beginners during the learning process.

This issue aims to Introduce a REPL tool to support Liquid developers.

### Motivation

Reduce the feedback loop for theme developers.

**Comment by blanklob** [comment]
Hey Can you explain in more details what this command does? and an example use case 🙂

**Comment by blanklob** [comment]
Oh thats really cool, It will really save so much time, rather than output thing into HTML directly thanks for explanation!

**Comment by tobi** [comment]
heh, now i'm learning about cool features we are working on from banklob. Yes, let's definitely ship that. Very cool.

**Comment by ulgut** [comment]
This is so cool! 🚀

**Comment by blanklob** [comment]
@karreiro  I didn't manage to launch the console, its send me to a 404 page?

I used latest build of Dawn v10

```json
"@shopify/cli": "^3.46.5",
"@shopify/theme": "^3.46.5"
```
<img width="1456" alt="Capture d’écran 2023-06-21 à 04 13 44" src="https://github.com/Shopify/cli/assets/63895927/be5a0918-7cc2-4024-8073-4fad92970d02">

**Comment by octipus** [comment]
Yes please 🚀

**Comment by drobinson** [comment]
Is there a way to specify a template and page context so we can for example poke at why updates to section schema aren't working in theme editor?

**Comment by karreiro** [comment]
@drobinson that's no included in the prototype, but the plan is to incorporate that feature in the final version :)

**Comment by blanklob** [comment]
Hey @karreiro I recieved another time the error I told about, regarding when the CLI send me to a 404 page, instead of launch the liquid terminal.

Here are the logs:

```bash
2023-07-20T02:40:34.237Z: 
Running system process:
  · Command: ruby -v
  · Working directory: /Users/youness/Development/studio/theme

2023-07-20T02:40:34.247Z: 
Running system process:
  · Command: bundle -v
  · Working directory: /Users/youness/Development/studio/theme

2023-07-20T02:40:34.355Z: Reading the content of file at node_modules/.pnpm/@shopify+cli-kit@3.47.3_@types+node@20.4.1_typescript@5.1.6/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2023-07-20T02:40:34.357Z: 
Running system process:
  · Command: bundle config set --local path /Users/youness/Library/Caches/shopify-gems-nodejs
  · Working directory: /Users/youness/Development/studio/theme/node_modules/.pnpm/@shopify+cli-kit@3.47.3_@types+node@20.4.1_typescript@5.1.6/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-07-20T02:40:34.437Z: 
Running system process:
  · Command: bundle config set --local without development:test
  · Working directory: /Users/youness/Development/studio/theme/node_modules/.pnpm/@shopify+cli-kit@3.47.3_@types+node@20.4.1_typescript@5.1.6/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-07-20T02:40:34.512Z: 
Running system process:
  · Command: bundle install
  · Working directory: /Users/youness/Development/studio/theme/node_modules/.pnpm/@shopify+cli-kit@3.47.3_@types+node@20.4.1_typescript@5.1.6/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-07-20T02:40:34.676Z: 
Running system process:
  · Command: bundle exec ruby /Users/youness/Development/studio/theme/node_modules/.pnpm/@shopify+cli-kit@3.47.3_@types+node@20.4.1_typescript@5.1.6/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme console
  · Working directory: /Users/youness/Development/studio/theme

DEBUG GET https://hillsmade.myshopify.com/admin/api/unstable/themes.json with request_id: fe70c746-6ecc-4938-a656-574a9e43fa6d
[2023-07-20 04:40:35] INFO  WEBrick 1.7.0
[2023-07-20 04:40:35] INFO  ruby 3.2.2 (2023-03-30) [arm64-darwin22]
[2023-07-20 04:40:35] INFO  WEBrick::HTTPServer#start: pid=17117 port=9293
DEBUG Refreshing preview _secure_session_id cookie
DEBUG Proxying HEAD https://hillsmade.myshopify.com/?preview_theme_id=136902934786&_fd=0&pb=0
DEBUG `-> 302 request_id: 92e53943-68f2-4586-86c3-eece4d659545
DEBUG Proxying GET https://hillsmade.myshopify.com/?_fd=0&pb=0
DEBUG `-> 404 request_id: b619526b-5021-4ec1-8b8b-f1e9a0bb101e

``` 

Same issue here: https://github.com/Shopify/cli/issues/1344#issuecomment-1599968115

**Comment by karreiro** [comment]
Resolved by https://shopify.dev/changelog/liquid-console-test-and-evaluate-liquid-snippets-quickly-using-shopify-cli :)

**Comment by haroldao** [comment]
Yoo-hoo! 🍾🍾

**Comment by PaulNewton** [comment]
Recommend this gets added to https://shopify.dev/docs/api/liquid#resources_and_tools
Either as it's own card, or a very **loud** blurb within the existing CLI listing.

The term "snippet" should be avoided In descriptions or docs about the liquid-console in favor of something like code samples, experiments , liquid-code, liquid-logic, bits of code, code samples or other verbiage should be used.

It's very **very** easy to confuse new learners between snippets _of code_ and a themes template snippet _files_.
Easy to imply that a theme snippet file can be passed, or imply that ONLY a /snippet file can be evaluated.
Or imply that a FULL evaluation is possible even though it would lack a **FULL** execution context; even if you give a product url for the `--url` context param that doesn't fill the context with a sections context or snippets calling other snippets, e.g; fill in the values for render parameters ,  etc etc). 

![image](https://github.com/Shopify/cli/assets/47228209/e1142447-3f46-44ef-b5e6-2c84de26ab31)
or for doc whitespace aesthetics over information
![image](https://github.com/Shopify/cli/assets/47228209/200fb175-baf0-42bf-a931-908fbf2e6b71)

**Comment by vitalii-onopriienko** [comment]
This feature is definitely moving in the right direction, but right now it is almost the same thing as using a json flag on objects or just rendering a snippet or section on a page in the browser (but with some extra login procedures and manipulations with URL context through the console and not using the browser).

What could make it really useful is resolving issues with object debugging. For example. If we are logging a 'product' object, we will get some information about it, but the existence of such a thing as 'product.options_with_values' will not even be mentioned there. At the same time, 'product.options_with_values' will print some information. This is not the only case described. Such cases are pretty common. If it is possible to at least show the existence of this parameter and that there is some data there or not, it would be great.

Also, some really big data chunks (as product.variants etc) we don't need to be shown all at once. It could be much better to show something to identify the existence of data there and load it only when you click on that.
