### ISSUE TITLE
[Bug]: No .env file

### ISSUE THREAD

**Issue by ChaseWNorton** [Shopify/cli#135]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

cli should setup a .env file. There is no documentation of this change

### Actual behavior

none is setup

### Reproduction steps

1. install new app
2. check directory 

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0.19

**Comment by gonzaloriestra** [comment]
Hi! The `.env` file is not generated when creating an app, but only after deploying an extension. It's not required as explained here: https://shopify.dev/apps/tools/cli/structure#directory-structure
