### ISSUE TITLE
[Feature]: having a --theme-editor-sync-path option

### ISSUE THREAD

**Issue by tommypepsi** [Shopify/cli#1352]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

Substantial change to existing feature

### Overview

I would like to see a new --theme-editor-sync-path where you can specify in which folder the changes from the theme editor will be downloaded to.

### Motivation

We are using build tools so the place where we run `shopify theme dev` and where our code lives is not the same. This would allow us to run `shopify theme dev` from the dist folder and bring the synced files into our src folder where our actual code lives.

**Comment by gideonb** [comment]
I would use this. We have multiple environment folders for the JSON in different stores. 

This is my current hack -- I run this in another session to pull the JSON:
```
shopify theme pull --path=environments/foo --store=pipeline-foo-bar.myshopify.com --only='config/settings_data.json' --only='templates/*.json' --only='templates/*.*.json' --only='templates/customers/.*.json'
```

**Comment by tommypepsi** [comment]
@gideonb Yeah we use the same. Our process is, a dev works on a task and pushes it with the minimum settings for the QA person to quickly have a preview of the work. Thing is the devs often forgets to pull the settings before pushing so it ends up more work than necessary for the QA.
