### ISSUE TITLE
[Enhancement]: New Apps still do not support admin.myshopify.com

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#1363]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

When I open up a preview of my App in the merchant store, I expect it to open up without trouble, to the home page.

### Actual behavior

When the merchant gets to the homepage of the App, it comes with BIG FAT RED WARNINGS that the App is not current and has to open in a new tab. Obviously, this looks pretty stinky to the merchant. Can we please have Shopify update this install process to use templates that are modern enough so that this is no longer an issue. In particular, this happens with the stock Ruby App 

### Reproduction steps

1. Install and start new App
2. Click link to new App
3. See the Warning

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.43

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.6

### What language and version are you using in your application?

Ruby 3.2.0

**Comment by matteodepalo** [comment]
Pinging @Shopify/client-libraries-app-templates for visibility.
