### ISSUE TITLE
[Bug]: CLI Still spawns App Bridge@2 code

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#1364]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

When I spawn a new App using CLI 3, and choose Ruby as the scripting code for the backend, I would not expect the template used to be using App Bridge 2. 

### Actual behavior

When you examine the App Shopify templates delivers from the CLI 3 and Ruby, you get this for App Bridge in the templates. 

    <script src="https://unpkg.com/@shopify/app-bridge@2"></script>

So a hard-coded reference to App Bridge 2!! We should instead be getting App Bridge 3 from our package should we not? 

### Reproduction steps

1.
2.
3.

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.43

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.6

### What language and version are you using in your application?

Ruby 3.2.0

**Comment by pepicrft** [comment]
👋🏼 @resistorsoftware 
Thanks for bringing this up. The template [hasn't yet been updated](https://github.com/Shopify/shopify-app-template-ruby/blob/8707c21d30358e42a946b3b1454d35098a2a7ef5/web/app/views/layouts/embedded_app.html.erb#L29) to use the most recent version of App Bridge. I'll follow-up internally regarding what are the plans and I'll get back to you.

**Comment by matteodepalo** [comment]
Pinging @Shopify/client-libraries-app-templates for visibility
