### ISSUE TITLE
[Bug]: Ruby Version Mismatch, unable to host app with theme extensions on Digital Ocean or Heroku

### ISSUE THREAD

**Issue by Michael-Gibbons** [Shopify/cli#1373]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Part of the deploy process for a shopify application is running `theme check` on all extensions, `theme check` requires a local ruby version of at least 2.7. Digital Ocean and Heroku use [Heroku's Buildpack for nodejs](https://github.com/heroku/heroku-buildpack-nodejs#readme) which to my knowledge, currently requires ruby 2.5. This causes a version mismatch and a failure to build.

Unless I do some major fiddling by ssh'ing into my remote server and sudo updating ruby which may break the buildpack I cannot build an app with extensions since part of `shopify app deploy` is running `theme check` on the extension code, which requires that local ruby version.

The reason I am submitting this bug report rather than accepting that this is a server configuration issue and out of the scope of this package, is because the shopify cli is introducing this required local ruby version.

An alternative solution may be to disable theme check in production.

### Actual behavior

![image](https://user-images.githubusercontent.com/13829417/218827170-a088c4d4-366e-4c91-86a9-3ee79a9be197.png)

### Reproduction steps

1. Create app using theme app extensions
2. Deploy to Digital Ocean or Heroku
3. Verify ruby error when attempting to build

### Operating System

Ubuntu 18.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.43.0

### Shell

bash

### Node version (run `node -v` if you're not sure)

16.19.0

**Comment by Michael-Gibbons** [comment]
ref #1056, #1290

**Comment by Arkham** [comment]
Hi @Michael-Gibbons, I'm afraid I disagree and I think this is a server configuration issue. We use `theme-check`, which is still written in Ruby to valid the theme app extension before deploy, so it's a necessary runtime dependency of the CLI. I haven't used it in a while, but I think heroku allows to use layered buildpacks to specify your dependencies; check out this link: https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

**Comment by Michael-Gibbons** [comment]
@Arkham If it is the stance of shopify that in order to use theme app extensions you have to have a custom docker container with the required dependencies then that should be documented and a dockerfile included in all repositories. This is a node package, the fact that it requires a local ruby dependency at all is a bit odd in the first place, which is shopify's choice. Which is fine as long as you guys clearly mention and document that shopify apps built in node should be using docker.

**Comment by Arkham** [comment]
Hey @Michael-Gibbons we specify that you might need additional dependencies here, for example Ruby and Bundler for theme app extensions: https://shopify.dev/docs/apps/tools/cli/ci-cd#additional-project-dependencies

In the case of theme app extensions we reuse a lot of tooling written in Ruby dedicated to validate themes, so for now the node CLI is spawning some of that tooling. The plan for the future is for all the tooling to be in node land, but we're not there yet.
