### ISSUE TITLE
`theme pull` (CLI 2) does not show development theme (created by CLI 3) in the select list

### ISSUE THREAD

**Issue by Bilal193** [Shopify/cli#1387]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme, Other

### Expected behavior

Normally we work on the theme editor of our development theme and pull the changes to our local repo. but. Theme pull should show the development theme in the list as it was done in earlier versions of Shopify cli 3.x.the 

### Actual behavior

I've initialized them using theme init in my vs code. Now I run the Shopify theme dev command and open the link to Customize this theme in the Theme Editor. I want to pull the changes I've made in my theme editor. but when I run the Shopify theme pull command it shows me a list of themes in my store and I have to choose one of them to pull. but I don't want that I want to pull changes I've made in my development theme but it is not on the list.

### Reproduction steps

1. run Shopify theme init 
2. run Shopify theme dev and open theme customizer and do some changes in the layout.
3. now run Shopify pull command we can't pull these changes as the theme is not in the list given to pull.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.43

### Shell

powershell

### Node version (run `node -v` if you're not sure)

18.12.1

**Comment by pepicrft** [comment]
Thanks for reporting this @Bilal193. I'm looping in the @Shopify/theme-developer-tools team to assist with the debugging of the issue.

**Comment by Poitrin** [comment]
You can use `shopify theme pull -d` to pull your development theme.
I tried `pull`ing with Shopify CLI 2.x and no development theme can be selected there, so I guess it doesn't show up on purpose. But I will take a closer look again…

**Comment by Bilal193** [comment]
[image: image.png]
Shopify theme pull -d worked but earlier I was using cli 3.38(don't
remember exactly), back then I only used to do Shopify theme pull and it
worked fine. As you can see in the snap when we run Shopify theme dev it
shows a command to pull the changes from the editor, which is Shopify pull.
No clue of this -d flag even in the documentation.
Regards
Bilal

**Comment by james0r** [comment]
`shopify theme pull -d` worked for me.

My issue is that I can only see some old stale development theme when i try `shopify theme pull` and don't see the current dev theme i'm working on. I'd like to remove this old stale dev theme if anyone knows how to do that.

Current Shopify CLI version: 3.43.0

**Comment by Poitrin** [comment]
>  I'd like to remove this old stale dev theme if anyone knows how to do that.

What about running `shopify theme list --role=development` to get the ID of your stale theme, and then `shopify theme delete -t <ID>` to delete it?

**Comment by Poitrin** [comment]
> No clue of this -d flag even in the documentation.

![22-07-uzvx6-nsblu](https://user-images.githubusercontent.com/12963280/220560108-cc20fcce-51f2-48ba-bdcf-f39eb0cb54a2.jpg)

Did you check https://shopify.dev/docs/themes/tools/cli/commands#pull too? :)
