### ISSUE TITLE
[Bug]: `shopify theme dev` command not running

### ISSUE THREAD

**Issue by lockystav** [Shopify/cli#1394]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When i ran `shopify theme dev` i expected it to run the development theme onto a local host and a live preview. When i first setup the cli and theme packages through npm, it ran perfectly, then i tried to run it again at a later time and the issue occured and wasnt spinning up the local environment anymore

### Actual behavior

It shows an error in the cli and I have no clue why it is happening. I have tried reinstalling the cli and theme npm packages multiple times, reintalled node.js and also ruby but the error is still showing. 

### Stack trace

```shell
╭─ error ─────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│  command theme:serve:. not found                                                            │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

C:\Users\locky\AppData\Roaming\npm\node_modules\@shopify\cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

AbortSilentError
    at execCLI2 (file:///C:/Users/locky/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:53:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  tryMessage: null,
  type: 1,
  nextSteps: undefined
}
```

### Reproduction steps

1. Install Node.js
2. Install Ruby
3. Install `@shopify/cli` and `@shopify/theme`
4. Run `shopify theme dev`

### Operating System

Windowws 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.43.0

### Shell

Command Prompt

### Node version (run `node -v` if you're not sure)

v18.14.0

### What language and version are you using in your application?

Its a theme, so liquid and js

**Comment by mailmonir** [comment]
I've the exact same problem and unable to fix it. I uninstalled and reinstalled everything but didn't fix the problem.

**Comment by tomhooker** [comment]
Getting this issue

/opt/homebrew/Cellar/shopify-cli/3.43.0/libexec/lib/node_modules/@shopify/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

ExternalError: Command failed with exit code 5: /opt/homebrew/opt/ruby/bin/bundle install
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c
/opt/homebrew/opt/ruby/bin/ruby -I
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0 extconf.rb
checking for ffi_prep_closure_loc() in -lffi... no
checking for ffi_prep_closure_loc() in -llibffi... no
checking for ffi_prep_closure_loc() in -llibffi-8... no
checking for whether -Wl,--exclude-libs,ALL is accepted as LDFLAGS... no
checking for whether -pthread is accepted as LDFLAGS... yes
creating extconf.h
creating Makefile

current directory:
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c
make DESTDIR\= sitearchdir\=./.gem.20230221-14809-qzaha5
sitelibdir\=./.gem.20230221-14809-qzaha5 clean

current directory:
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c
make DESTDIR\= sitearchdir\=./.gem.20230221-14809-qzaha5
sitelibdir\=./.gem.20230221-14809-qzaha5
Configuring libffi
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/configure:
line 18692: readelf: command not found
clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
cd
"/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi-arm64-darwin22"
&& /Library/Developer/CommandLineTools/usr/bin/make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in include
make[3]: Nothing to be done for `all'.
Making all in testsuite
make[3]: Nothing to be done for `all'.
Making all in man
make[3]: Nothing to be done for `all'.
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c -o src/prep_cif.lo
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/prep_cif.c
libtool: compile:  clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/prep_cif.c 
-fno-common -DPIC -o src/.libs/prep_cif.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c -o src/types.lo
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/types.c
libtool: compile:  clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/types.c
-fno-common -DPIC -o src/.libs/types.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c -o src/raw_api.lo
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/raw_api.c
libtool: compile:  clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/raw_api.c
-fno-common -DPIC -o src/.libs/raw_api.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c -o src/java_raw_api.lo
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/java_raw_api.c
libtool: compile:  clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/java_raw_api.c 
-fno-common -DPIC -o src/.libs/java_raw_api.o
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/java_raw_api.c:328:46:
warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
  ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
                                             ^
include/ffi.h:299:56: note: 'ffi_java_raw_size' has been explicitly marked
deprecated here
size_t ffi_java_raw_size (ffi_cif *cif) __attribute__((deprecated));
                                                       ^
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/java_raw_api.c:331:3:
warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
  ffi_java_ptrarray_to_raw (cif, avalue, raw);
  ^
include/ffi.h:295:93: note: 'ffi_java_ptrarray_to_raw' has been explicitly
marked deprecated here
void ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw)
__attribute__((deprecated));
^
2 warnings generated.
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c -o src/closures.lo
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/closures.c
libtool: compile:  clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/closures.c 
-fno-common -DPIC -o src/.libs/closures.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c -o src/aarch64/ffi.lo
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/aarch64/ffi.c
libtool: compile:  clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-Wall -fexceptions -c
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/aarch64/ffi.c
-fno-common -DPIC -o src/aarch64/.libs/ffi.o
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-c -o src/aarch64/sysv.lo
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/aarch64/sysv.S
libtool: compile:  clang -DHAVE_CONFIG_H -I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-I.
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/include
-Iinclude
-I/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src
-c
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/src/aarch64/sysv.S 
-fno-common -DPIC -o src/aarch64/.libs/sysv.o
/bin/sh ./libtool  --tag=CC   --mode=link clang  -Wall -fexceptions   -o
libffi_convenience.la  src/prep_cif.lo src/types.lo src/raw_api.lo
src/java_raw_api.lo src/closures.lo   src/aarch64/ffi.lo src/aarch64/sysv.lo
libtool: link: ar cru .libs/libffi_convenience.a src/.libs/prep_cif.o
src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o
src/.libs/closures.o src/aarch64/.libs/ffi.o src/aarch64/.libs/sysv.o
/Library/Developer/CommandLineTools/usr/bin/ranlib: file:
.libs/libffi_convenience.a(ffi.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file:
.libs/libffi_convenience.a(sysv.o) has no symbols
libtool: link: ranlib .libs/libffi_convenience.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file:
.libs/libffi_convenience.a(ffi.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file:
.libs/libffi_convenience.a(sysv.o) has no symbols
libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s
"../libffi_convenience.la" "libffi_convenience.la" )
/bin/sh ./libtool  --tag=CC   --mode=link clang  -Wall -fexceptions
-no-undefined -version-info `grep -v '^#'
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi/libtool-version`
-o libffi.la -rpath /usr/local/lib src/prep_cif.lo src/types.lo src/raw_api.lo
src/java_raw_api.lo src/closures.lo  src/aarch64/ffi.lo src/aarch64/sysv.lo
libtool: link: clang -dynamiclib  -o .libs/libffi.8.dylib  src/.libs/prep_cif.o
src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o
src/.libs/closures.o src/aarch64/.libs/ffi.o src/aarch64/.libs/sysv.o     
-install_name  /usr/local/lib/libffi.8.dylib -compatibility_version 10
-current_version 10.0 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_ffi_call", referenced from:
      _ffi_raw_call in raw_api.o
      _ffi_java_raw_call in java_raw_api.o
  "_ffi_closure_trampoline_table_page", referenced from:
      _ffi_trampoline_table_alloc in closures.o
  "_ffi_prep_cif_machdep", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_cif_machdep_var", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_closure_loc", referenced from:
      _ffi_prep_closure in prep_cif.o
      _ffi_prep_raw_closure_loc in raw_api.o
      _ffi_prep_java_raw_closure_loc in java_raw_api.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libffi.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: ***
["/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi-arm64-darwin22"/.libs/libffi_convenience.a]
Error 2

make failed, exit code 2

Gem files will remain installed in
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/gems/ffi-1.15.5
for inspection.
Results logged to
/Users/mail/Library/Caches/shopify-cli-nodejs/vendor/ruby-cli/2.34.0/ruby/3.2.0/extensions/arm64-darwin-22/3.2.0/ffi-1.15.5/gem_make.out

/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:102:in
`run'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:51:in
`block in make'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:43:in
`each'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:43:in
`make'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in
`build'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:170:in
`build_extension'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:204:in
`block in build_extensions'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:201:in
`each'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/ext/builder.rb:201:in
`build_extensions'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/installer.rb:843:in
`build_extensions'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/rubygems_gem_installer.rb:28:in
`install'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/source/rubygems.rb:200:in
`install'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:54:in
`install'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:155:in
`do_install'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/installer/parallel_installer.rb:146:in
`block in worker_pool'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:62:in
`apply_func'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:57:in `block
in process_queue'
  /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:54:in `loop'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:54:in
`process_queue'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/bundler/worker.rb:90:in `block
(2 levels) in create_threads'

An error occurred while installing ffi (1.15.5), and Bundler cannot continue.

In Gemfile:
  shopify-cli was resolved to 2.34.0, which depends on
    listen was resolved to 3.7.1, which depends on
      rb-inotify was resolved to 0.10.1, which depends on
        ffi
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using bundler 2.4.6
Using racc 1.6.2
Using rb-fsevent 0.11.2
Using ast 2.4.2
Using concurrent-ruby 1.2.0
Using liquid 5.4.0
Using nokogiri 1.14.2 (arm64-darwin)
Using parser 3.2.1.0
Using bugsnag 6.25.2
Using theme-check 1.14.0
Installing ffi 1.15.5 with native extensions
    at makeError (file:///opt/homebrew/Cellar/shopify-cli/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///opt/homebrew/Cellar/shopify-cli/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exec (file:///opt/homebrew/Cellar/shopify-cli/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/system.js:54:9)
    at async bundleInstallShopifyCLI (file:///opt/homebrew/Cellar/shopify-cli/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:229:5)
    at async installCLIDependencies (file:///opt/homebrew/Cellar/shopify-cli/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:133:9)
    at async execCLI2 (file:///opt/homebrew/Cellar/shopify-cli/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:27:5) {
  tryMessage: null,
  type: 0,
  nextSteps: undefined,
  command: '/opt/homebrew/opt/ruby/bin/bundle',
  args: [ 'install' ]
}

**Comment by crupko93** [comment]
I got same problem runing yarn start. My package.json is bellow.
`{
  "name": "shopify-theme-lab",
  "description": "Customizable modular development environment for blazing-fast Shopify theme creation",
  "author": "Sergej Samsonenko",
  "version": "4.4.1",
  "license": "MIT",
  "scripts": {
    "start": "run-p -sr shopify:serve webpack:watch",
    "deploy": "run-s webpack:build && cd shopify && shopify theme push",
    "deploy:new": "run-s webpack:build && cd shopify && shopify theme push --unpublished",
    "webpack:watch": "cross-env NODE_ENV=development BROWSERSLIST_ENV=development BROWSERSLIST_CONFIG=.config/.browserslistrc webpack --config .config/webpack/webpack.dev.js --watch --progress",
    "webpack:build": "cross-env NODE_ENV=production BROWSERSLIST_ENV=production BROWSERSLIST_CONFIG=.config/.browserslistrc webpack --config .config/webpack/webpack.prod.js --progress",
    "shopify:serve": "cd shopify && shopify theme dev",
    "shopify:pull": "cd shopify && shopify theme pull",
    "lint": "run-s -c lint:*",
    "lint:js": "eslint src/**/*.{js,vue} --config .config/.eslintrc.js",
    "lint:css": "stylelint src/**/*.{vue,css,sass,scss} --config .config/.stylelintrc.js",
    "lint:shopify": "cd shopify && shopify theme check",
    "fix": "run-s -c fix:*",
    "fix:js": "eslint src/**/*.{js,vue} --config .config/.eslintrc.js --fix",
    "fix:css": "stylelint src/**/*.{vue,css,sass,scss} --config .config/.stylelintrc.js --fix",
    "fix:shopify": "cd shopify && shopify theme check -a"
  },
  "dependencies": {
    "@shopify/cli": "^3.43.0",
    "vue": "^3.2.26",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@babel/plugin-transform-runtime": "^7.16.4",
    "@babel/preset-env": "^7.16.4",
    "@vue/compiler-sfc": "^3.2.26",
    "autoprefixer": "^10.4.0",
    "babel-loader": "^8.2.3",
    "clean-webpack-plugin": "^4.0.0",
    "cross-env": "^7.0.3",
    "css-loader": "^6.5.1",
    "css-minimizer-webpack-plugin": "^3.2.0",
    "eslint": "^8.4.1",
    "eslint-plugin-vue": "^8.2.0",
    "eslint-webpack-plugin": "^3.1.1",
    "mini-css-extract-plugin": "^2.4.5",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.5",
    "postcss-html": "^1.3.0",
    "postcss-import": "^14.0.2",
    "postcss-loader": "^6.2.1",
    "sass": "^1.55.0",
    "sass-loader": "^13.1.0",
    "stylelint": "^14.1.0",
    "stylelint-config-recommended": "^6.0.0",
    "stylelint-webpack-plugin": "^3.1.0",
    "url-loader": "^4.1.1",
    "vue-loader": "^16.8.3",
    "webpack": "^5.65.0",
    "webpack-cli": "^4.9.1",
    "webpack-merge": "^5.8.0"
  }
}
`
![image](https://user-images.githubusercontent.com/29951259/220495880-1a0b20a6-0aa7-4640-8360-197165e069aa.png)

Interesting fact that replacing:
` "shopify:serve": "cd shopify && shopify theme dev",` -> ` "shopify:serve": "cd shopify && shopify help",` 
will work and display 
![image](https://user-images.githubusercontent.com/29951259/220496284-5807a7d6-82c8-4255-a649-914694adb743.png)

**Comment by tomhooker** [comment]
Got same issue

**Comment by mailmonir** [comment]
I got a solution for this problem. I uninstalled everything (nodejs, shopify-cli, shopify-theme, ruby), even deleted all the files and folders from appdata->roaming related to these programs. Also deleted npm-cache folder. After that reinstalled everything and now its working fine as before.

**Comment by crupko93** [comment]
> I got a solution for this problem. I uninstalled everything (nodejs, shopify-cli, shopify-theme, ruby), even deleted all the files and folders from appdata->roaming related to these programs. Also deleted npm-cache folder. After that reinstalled everything and now its working fine as before.

What OS are you using?

**Comment by chunkysteveo** [comment]
Adding the --path and the path to the theme directory helped me get the DEV command to actually fire up and not stall. Hope this gets fixed in an update.
