### ISSUE TITLE
[Bug]: Shopify cli 3 output wrong encoded characters

### ISSUE THREAD

**Issue by forwells** [Shopify/cli#1400]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

shopify cli 3 can output correctly encoded string.

### Actual behavior

shopify cli 3 output wrong encoded characters

![image](https://user-images.githubusercontent.com/32950945/219612786-d9add1ec-9702-4092-ba1c-34cc27194854.png)

### Stack trace

```shell
None trace, 
Because I don't know where to find it, I have adjusted the default terminal encoding of linux, but in fact, the final output of console characters is done by Shopify CLI, so I don't know whether it is the CLI that performs the final output of the text special code
```

### Reproduction steps

1 In the app file system, enter the web directory
2 Output a line of text from other countries, Thai, Chinese, and other Asian languages from the terminal
3 Confused character encodings appear

### Operating System

Ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.39.0 (The latest version)

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.14.1

### What language and version are you using in your application?

Nodejs

**Comment by isaacroldan** [comment]
>1 In the app file system, enter the web directory
2 Output a line of text from other countries, Thai, Chinese, and other Asian languages from the terminal
3 Confused character encodings appear

When you say output a line of text, you mean like a console.log from the frontend process?

**Comment by forwells** [comment]
> > 1 In the app file system, enter the web directory
> > 2 Output a line of text from other countries, Thai, Chinese, and other Asian languages from the terminal
> > 3 Confused character encodings appear
> 
> When you say output a line of text, you mean like a console.log from the frontend process?
In fact, it is not in the front-end process, but in the root directory of the web directory, which is the back-end program of the Shopify APP to output characters. I have tested the character encoding of the current terminal in other node programs (using nodmon to run), the fact is The character encoding of the current Ubuntu system is UTF8, so confusing characters should not be output, so I am basically sure that the encoding confusion is caused by the Context logger of Shopify Cli.

**Comment by isaacroldan** [comment]
Hi @forwells, I was able to reproduce your bug. I'll assign it to the team to prioritize. 
For the moment, I'm sorry but you'd need to avoid using non-latin characters :(

**Comment by isaacroldan** [comment]
cc/ @matteodepalo this seems related with Ink outputs, what do you think?

**Comment by isaacroldan** [comment]
Steps to reproduce:
- Add a console log with japanese characters at `./fixtures/app/web/backend/index.js:L42` (just at the start of `createServer`)
- `pnpm shopify app dev --path fixtures/app`

**Comment by forwells** [comment]
> Hi @forwells, I was able to reproduce your bug. I'll assign it to the team to prioritize. I'm sorry but for now you'd need to avoid using non-latin characters :(

Thanks
