### ISSUE TITLE
Shopify v3.0 not recognized after npm install

### ISSUE THREAD

**Issue by SpiderWizard** [Shopify/cli#1405]
### Expected behavior
shopify is installed and recognized

### Actual behavior
**C:\Users\name>** shopify version
'shopify' is not recognized as an internal or external command, operable program or batch file.   

### System Information

**C:\Users\name>** systeminfo
                                                                                
**OS Name:**                   Microsoft Windows 10 Home                                                                    
**OS Version:**                10.0.19045 N/A Build 19045                                                                   
**OS Manufacturer:**           Microsoft Corporation                                                                        
**OS Configuration:**          Standalone Workstation                                                                       
**OS Build Type:**             Multiprocessor Free                                                                                                                         
**System Type:**               x64-based PC                                
**Windows Directory:**         C:\WINDOWS                                                                                   
**System Directory:**          C:\WINDOWS\system32 

### Steps to reproduce
**C:\Users\name>** npm install -g @shopify/cli

### Shell
Command Prompt

### Version information
**C:\Users\name>** node -v
v16.17.0

**C:\Users\name>** npm -v
9.5.0

**C:\Users\name>** ruby -v
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt] 

**C:\Users\name>** git --version
git version 2.24.1.windows.2 

**C:\Users\name>** bundler -v
Bundler version 2.3.26 

### Other info
Was attempting to follow the official Shopify documentation (found [here](https://shopify.dev/docs/themes/getting-started/create))

Installing via gem works but only for v2.x

**C:\Users\name>** gem install shopify-cli

**C:\Users\name>** shopify version
\* Note that CLI 2.x will be sunset on May 31, 2023.
2.34.0

**Comment by isaacroldan** [comment]
Hi @SpiderWizard

Seems like the npm installation wasn't successful or that there is a problem with your npm environment 🤔 
After running `npm install -g @shopify/cli @shopify/theme` could you check with `npm list -g` that they are indeed installed?

And if they are, that command will show you where (usually at `C:\Users\{user_name}\AppData\Roaming\npm`).
Inside that folder there should be a `shopify.ps1` file that you can run with `shopify.ps1 --version`.
If that works, but `shopify --version` doesn't, that means that maybe that NPM is not part of the windows PATH.

Let me know if this works!

PD: Don't forget to uninstall CLI 2.0 first!

**Comment by eringuyenD** [comment]
Was having same issue. Looks like @isaacroldan is on the right path. For me, when using `npm list -g` it does show the two packages are installed and `shopify.ps1` is located in `C:\Users\{user_name}\AppData\Roaming\npm`. `shopify.ps1` does work with windows powershell but not git bash. `shopify.cmd` works git bash so it seems that's the right command.

Checking my environment variables, it does have `C:\Users\{user_name}\AppData\Roaming\npm` in my `Path` variable so I'm not sure why it doesn't work. This issue started happening after I updated npm though.

**Comment by KapilAnncode** [comment]
1. Open CMD as adminastor 
2. Check that Ruby is installed by typing
ruby --version
3. Check that Git is installed by typing:
git --version
4. Check that Shopify is installed by typing:
shopify version
5. if shopify is already installed and it's older version 2 then type in cmd
gem uninstall shopify-cli 
then again run shopify version
6. if you had shopify cli 3 then upgrade it by typing 
run shopify upgrade
7. if you had node install globally then install shopify cli 3 by typing
npm install -g @shopify/cli @shopify/theme
