### ISSUE TITLE
[Bug]: ui.Listr is not a constructor

### ISSUE THREAD

**Issue by NiklasDue** [Shopify/cli#141]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Hydrogen custom storefront

### Expected behavior

Should be able to create docker image and push new version

### Actual behavior

I am unable to create a docker images and push new updates of my Hydrogen app to Heroku. It has been working with no issue for months, but now it gives me this error "ui.Listr is not a constructor". This also happens with a new version of the Hydrogen demo store. I updated the CLI today and have been stuck with this error since

### Stack trace

```shell
=> ERROR [build-env 5/5] RUN yarn build --target node                     2.2s
------                                                                          
 > [build-env 5/5] RUN yarn build --target node:                                
#11 0.360 yarn run v1.22.19
#11 0.389 $ shopify hydrogen build --target node
#11 2.085 
#11 2.085 ━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#11 2.085     ui.Listr is not a constructor
#11 2.085 
#11 2.085     Stack trace:    at buildService  …_modules/@shopify/cli-hydrogen/src/cli/services/build.ts:38  
#11 2.085     at run           …@shopify/cli-hydrogen/src/cli/commands/hydrogen/build.ts:51  
#11 2.085 
#11 2.085 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#11 2.085 
#11 2.113 error Command failed with exit code 1.
#11 2.113 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build --target node]: exit code: 1
 ▸    Error: docker build exited with Error: 1
```

### Reproduction steps

1. Follow instructions to build a docker image from the [Hydrogen docs](https://shopify.dev/custom-storefronts/hydrogen/deployment#deploy-to-docker)
2. When it gets to the step "RUN yarn build --target node" it will crash and show the error

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0.25

### Node version (run `node -v` if you're not sure)

v18.0.0

### What language and version are you using in your application?

Hydrogen-1.0.2

**Comment by NiklasDue** [comment]
I was able to solve not being able to push a new version, by changing the following in package.json and running `gem install shopify-cli --version 2.18.1`

```
"@shopify/cli": "2.0.10",
"@shopify/cli-hydrogen": "2.0.10",
```

**Comment by gonzaloriestra** [comment]
Hi! Thanks for creating the issue.

I'm a bit confused by the CLI versions you are providing: 3.0.25, 2.18.1, 2.0.10... Let me try to clarify things.

There are two CLIs right now:
- The new version, which is installed as a Node dependency (https://github.com/Shopify/cli). Current version: 3.1.0
- The old version, which is installed globally as a Ruby gem (https://github.com/Shopify/shopify-cli). Current version: 2.20.0

For Hydrogen you should be using the new one, but it seems that you are mixing both somehow.

Could you please follow these steps to install the latest version and try again?
1. Update your `package.json`:
```
"@shopify/cli": "3.1.0",
"@shopify/cli-hydrogen": "3.1.0",
```
2. `yarn install`

**Comment by NiklasDue** [comment]
Hi! 

Sorry about the confusion. I was a bit confused about the CLI versions, so thanks for clearing that up. You can disregard the part about the gem version. I understood that wrong, so changing that version had no effect

Using v.3.1.0 in packages.json works. My apps were using v.3.0.25 and won't build with that version. I thought they were up to date, but that was only the gem file. My bad

Installing a new demo store with yarn works as well

Thank you for your time. I really appreciate you clearing things up for me
