### ISSUE TITLE
[Bug]: CLI command "shopify theme dev" error

### ISSUE THREAD

**Issue by NicholasEli** [Shopify/cli#1417]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It should have launched my theme on localhost

### Actual behavior

Returns error about `process.stdin.setRawMode` not being a function

### Stack trace

```shell
shopify theme dev --store {STORE}

To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  process.stdin.setRawMode is not a function                                  │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at (../../../../../usr/local/Cellar/shopify-cli/3.43.0/libexec/lib/node_  │
│    modules/@shopify/theme/node_modules/@shopify/cli-kit/src/public/node/ui.  │
│    tsx:366)                                                                  │
│      process.stdin.setRawMode(true)                                          │
│    at new Promise                                                            │
│    at keypress (../../../../../usr/local/Cellar/shopify-cli/3.43.0/libexec/  │
│    lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/src/public  │
│    /node/ui.tsx:351)                                                         │
│      return new Promise((resolve, reject) => {                               │
│    at authorize (../../../../../usr/local/Cellar/shopify-cli/3.43.0/libexec  │
│    /lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/src/priva  │
│    te/node/session/authorize.ts:42)                                          │
│      await keypress()                                                        │
│    at processTicksAndRejections (node:internal/process/task_queues:95)       │
│    at async executeCompleteFlow (../../../../../usr/local/Cellar/shopify-cl  │
│    i/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/c  │
│    li-kit/src/private/node/session.ts:179)                                   │
│      const code = await authorize(scopes)                                    │
│    at async ensureAuthenticated (../../../../../usr/local/Cellar/shopify-cl  │
│    i/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/c  │
│    li-kit/src/private/node/session.ts:126)                                   │
│      newSession = await executeCompleteFlow(applications, fqdn)              │
│    at async ensureAuthenticatedAdmin (../../../../../usr/local/Cellar/shopi  │
│    fy-cli/3.43.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shop  │
│    ify/cli-kit/src/public/node/session.ts:82)                                │
│      const tokens = await ensureAuthenticated({adminApi: {scopes,            │
│      storeFqdn: store}}, process.env, forceRefresh)                          │
│    at run (../../../../../usr/local/Cellar/shopify-cli/3.43.0/libexec/lib/n  │
│    ode_modules/@shopify/theme/src/cli/commands/theme/dev.ts:103)             │
│      const adminSession = await ensureAuthenticatedThemes(store,             │
│      flags.password, [], true)                                               │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```
```


### Reproduction steps

1. Install latest CLI (3.43.0)
2. Run `shopify theme dev --store {STORE}`
3. See error returned

### Operating System

Mac Book Pro (2019)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.43.0

### Shell

Terminal

### Node version (run `node -v` if you're not sure)

v16.0.0 -> v18.0.0

### What language and version are you using in your application?

_No response_

**Comment by uriel2707** [comment]
Returns error about process.stdin.setRawMode not being a function
` 
shopify theme list

To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  process.stdin.setRawMode is not a function                                  │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at (../../../AppData/Roaming/nvm/v18.13.0/node_modules/@shopify/theme/no  │
│    de_modules/@shopify/cli-kit/src/public/node/ui.tsx:457)                   │
│      process.stdin.setRawMode(true)                                          │
│    at new Promise                                                            │
│    at keypress (../../../AppData/Roaming/nvm/v18.13.0/node_modules/@shopify  │
│    /theme/node_modules/@shopify/cli-kit/src/public/node/ui.tsx:442)          │
│      return new Promise((resolve, reject) => {                               │
│    at authorize                                                              │
│    (../../../AppData/Roaming/nvm/v18.13.0/node_modules/@shopify/theme/node_  │
│    modules/@shopify/cli-kit/src/private/node/session/authorize.ts:42)        │
│      await keypress()                                                        │
│    at processTicksAndRejections (node:internal/process/task_queues:95)       │
│    at async executeCompleteFlow                                              │
│    (../../../AppData/Roaming/nvm/v18.13.0/node_modules/@shopify/theme/node_  │
│    modules/@shopify/cli-kit/src/private/node/session.ts:180)                 │
│      const code = await authorize(scopes)                                    │
│    at async ensureAuthenticated                                              │
│    (../../../AppData/Roaming/nvm/v18.13.0/node_modules/@shopify/theme/node_  │
│    modules/@shopify/cli-kit/src/private/node/session.ts:119)                 │
│      newSession = await executeCompleteFlow(applications, fqdn)              │
│    at async ensureAuthenticatedAdmin                                         │
│    (../../../AppData/Roaming/nvm/v18.13.0/node_modules/@shopify/theme/node_  │
│    modules/@shopify/cli-kit/src/public/node/session.ts:82)                   │
│      const tokens = await ensureAuthenticated({adminApi: {scopes,            │
│      storeFqdn: store}}, process.env, forceRefresh)                          │
│    at run (../../../AppData/Roaming/nvm/v18.13.0/node_modules/@shopify/them  │
│    e/src/cli/commands/theme/list.ts:36)                                      │
│      const adminSession = await ensureAuthenticatedThemes(store,             │
│      flags.password)                                                         │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

`

**Comment by amcaplan** [comment]
The terminal command is only helpful if the problem is happening.

Given that we don't have clear reproduction steps, I'm going to close. Feel free to open a new issue if this is still happening.

**Comment by syedsimanta03** [comment]
shopify theme dev

not working. 12months no solution from @shopify-admins
