### ISSUE TITLE
[Bug]: Error 'bundler: not executable' when pulling site

### ISSUE THREAD

**Issue by jxmesdev** [Shopify/cli#1428]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When running `shopify pull site` I expect the site to pull

### Actual behavior

Running `shopify theme info` gives me the expected output, so I know the theme is connected to the correct store:
```
THEME CONFIGURATION
Store                  coursej1.myshopify.com
Development Theme ID   #144093118757

TOOLING AND SYSTEM
Shopify CLI    3.44.0
OS             darwin-arm64
Shell          /bin/zsh
Node version   v19.7.0
Ruby version   3.2.1
```

But instead, I get the following error:

### Stack trace

```shell
bundler: not executable: /opt/homebrew/Cellar/shopify-cli/3.44.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify
```

### Reproduction steps

1. Connect to the store with Shopify CLI
2. Check connection with `shopify theme info`
3. Run `shopify theme pull`

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.7.0

**Comment by markdavies** [comment]
I am experiencing this when running `shopify theme dev` afer upgrading this morning

**Comment by Francesdenaro** [comment]
Same here, getting this
```
bundler: not executable: /Users/francesco/.nvm/versions/node/v16.13.1/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify
Error
    at execCLI2 (file:///Users/francesco/.nvm/versions/node/v16.13.1/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:55:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jxmesdev** [comment]
@markdavies @Francesdenaro In a separate issue, which causes the same error when running `shopify theme dev`, a dev has mentioned you can run the following to fix:

`chmod a+x /opt/homebrew/Cellar/shopify-cli/3.44.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify`

You can see that comment [here](https://github.com/Shopify/cli/issues/1425#issuecomment-1440921296). He mentions releasing a fix tomorrow as most of the team are EMEA, but in case you're as impatient as I am the above worked for me :-).

**Comment by jxmesdev** [comment]
@markdavies out of curiosity, are you running that before EVERY future command?

**Comment by markdavies** [comment]
Just the once, if I'm in the same terminal window it saves it for the
session.

**Comment by dgtlwrks** [comment]
same problem here, also the vscode extension crashes because of the same error since the update to 3.44.0

you can fix the command by adding `SHOPIFY_CLI_BUNDLED_THEME_CLI=1` (for some at least)

**Comment by mongorian346** [comment]
<img width="962" alt="スクリーンショット 2023-02-23 15 06 03" src="https://user-images.githubusercontent.com/60023453/220838667-4705b10d-a2cb-4e66-b937-6f4ad0374dcb.png">

**Comment by mongorian346** [comment]
I am beginner.I do not know what to do.

**Comment by Francesdenaro** [comment]
It worked for me putting `SHOPIFY_CLI_BUNDLED_THEME_CLI=1 ` before the commands indeed!

**Comment by Arkham** [comment]
Hey folks, we've identified the issue, merged a fix, and we shall be releasing a new patch shortly. Thank you again for reporting!
