### ISSUE TITLE
[Bug]: Try to Deploy Shopify App to AWS Amplify. Error Dockerfile No Definition Available

### ISSUE THREAD

**Issue by adithwip** [Shopify/cli#1445]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I'm using AWS Amplify to try deploying my Shopify App (Node template).
I was following [this straightforward tutorial](https://shopifylearner.com/how-to-deploy-shopify-app-on-aws-amplify/) for the deployment.

I was also authenticated with my IAM User in the Amplify first configuration.
Followed [this Amplify doc](https://docs.amplify.aws/cli/start/install/).

The result should successfully push the App to Amplify and retrieve the HTTPS URL.

### Actual behavior

**But it seems the `.Dockerfile` isn't read.**
<img width="423" alt="Screen Shot 2023-02-24 at 7 41 26" src="https://user-images.githubusercontent.com/27177332/221047404-5ebe8496-06b9-44a3-be6b-a5b9c7aaf5dd.png">

**I already put a `.Dockerfile` inside the desired directory.**
<img width="227" alt="Screen Shot 2023-02-24 at 7 41 03" src="https://user-images.githubusercontent.com/27177332/221047403-f38e9d60-7cb1-44d1-ab0c-843c24e8357e.png">

I already raise a similar issue to Amplify repo as well, [here](https://github.com/aws-amplify/amplify-cli/issues/12085#issuecomment-1442532245). But just in case I can get a clue from fellow Shopify App dev community about this specific topic.

Is there any Docker-related issue that maybe cause this?
We should just need a `.Dockerfile` itself and not needed another `docker-compose.yml` file, shouldn't we?

Here is my Dockerfile:
```dockerfile
FROM node:18-alpine
ENV SCOPES=read_products,read_orders
ENV SHOPIFY_API_KEY=<hardcoded-value>
ENV SHOPIFY_API_SECRET=<hardcoded-value>
ENV BACKEND_PORT=8081
EXPOSE 8081
WORKDIR /app
COPY web .
COPY tsconfig.json .
RUN npm install
RUN cd frontend && npm install && npm run build
CMD ["npm", "run", "serve"]

```

### Reproduction steps

1. Configure Amplify in the root of Shopify App directory
2. `amplify push` command
3. Error occurs

### Operating System

macOS 12.6 (21G115) Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.34.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.12.0

### What language and version are you using in your application?

JavaScript and TypeScript

**Comment by isaacroldan** [comment]
Hi @adithwip, this doesn't seem like a Shopify CLI bug, looks like an issue with Amplify.
For community support i'd recommend posting on the Partners [discord](https://discord.gg/shopifydevs) server.

**Comment by rizalhasbianto** [comment]
Hi @adithwip , put the .Dockerfile inside src folder, that works for me.
