### ISSUE TITLE
[Bug]: Multiple theme extensions not working. Please document number of extensions limit

### ISSUE THREAD

**Issue by Michael-Gibbons** [Shopify/cli#1449]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

![image](https://user-images.githubusercontent.com/13829417/221345331-faf4d9cc-a957-40f7-9d01-6cc9f9ddccda.png)

https://shopify.dev/docs/apps/app-extensions/list

I built a helper cli tool to manage multiple theme app extensions, only after did I learn that theme app extensions are limited to 1

I should have manually tested it myself before creating a react build process for it, but I really wish it was documented somewhere so I didn't waste several days building this tool under the premise that apps could have multiple. Thanks,

The extension limits are shown in the shopify app admin but not for cli created extensions like theme extensions. 

### Actual behavior

The actual behavior is its not possible and I look like a very sad silly goose

### Reproduction steps

1.
2.
3.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.23.0

**Comment by dani-sanomads** [comment]
Have you experienced any error while running npm run dev command. 
Error:
Preview URL: https://de10-39-59-61-169.in.ngrok.io/extensions/dev-console

── external error ────────────────────────────────────────────────────────────────

Error coming from `bundle install`

Command failed with exit code 5: bundle install
Bundler::DirectoryRemovalError: Could not delete previous installation of
`/usr/local/lib/ruby/gems/3.2.0/gems/byebug-11.1.3`.
The underlying error was Errno::EACCES: Permission denied @ apply2files -
/usr/local/lib/ruby/gems/3.2.0/gems/byebug-11.1.3/LICENSE, with backtrace:
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2342:in
`unlink'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2342:in
`block in remove_file'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2347:in
`platform_support'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2341:in
`remove_file'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2330:in
`remove'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:1470:in
`block in remove_entry'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2389:in
`block (2 levels) in postorder_traverse'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2393:in
`postorder_traverse'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2388:in
`block in postorder_traverse'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2387:in
`each'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:2387:in
`postorder_traverse'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:1468:in
`remove_entry'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/vendor/fileutils/lib/fileutils.rb:1383:in
`remove_entry_secure'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler.rb:339:in
`rm_rf'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:111:in
`strict_rm_rf'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:19:in
`install'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:200:in
`install'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/installer/parallel_installer.rb:167:in
`do_install'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/installer/parallel_installer.rb:158:in
`block in worker_pool'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:62:in
`apply_func'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:57:in
`block in process_queue'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:54:in
`loop'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:54:in
`process_queue'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

Bundler Error Backtrace:
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:115:in
`rescue in strict_rm_rf'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:110:in
`strict_rm_rf'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/rubygems_gem_installer.rb:19:in
`install'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/source/rubygems.rb:200:in
`install'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/installer/gem_installer.rb:54:in
`install'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/installer/parallel_installer.rb:167:in
`do_install'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/installer/parallel_installer.rb:158:in
`block in worker_pool'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:62:in
`apply_func'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:57:in
`block in process_queue'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:54:in
`loop'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:54:in
`process_queue'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.7/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing byebug (11.1.3), and Bundler cannot continue.

In Gemfile:
  pry-byebug was resolved to 3.10.1, which depends on
    byebug
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using rake 12.3.3
Using public_suffix 5.0.1
Using ansi 1.5.0
Using builder 3.2.4
Using bundler 2.4.7
Using coderay 1.1.3
Using colorize 0.8.1
Using rexml 3.2.5
Using cucumber-tag-expressions 4.1.0
Using cucumber-cucumber-expressions 14.0.0
Using diff-lcs 1.5.0
Using fakefs 2.4.0
Using faraday-net_http 3.0.2
Using ast 2.4.2
Fetching concurrent-ruby 1.2.2
Using cucumber-messages 17.1.1
Using mime-types-data 3.2023.0218.1
Using multi_test 0.1.2
Using ruby2_keywords 0.0.5
Using hashdiff 1.0.1
Using iniparse 1.5.0
Using json 2.6.3
Using liquid 5.4.0
Using rb-fsevent 0.11.2
Using minitest 5.17.0
Using racc 1.6.2
Using parallel 1.22.1
Using method_source 1.0.0
Using rainbow 3.1.1
Using unicode-display_width 2.4.2
Using ruby-progressbar 1.11.0
Using rack 3.0.4.1
Using regexp_parser 2.7.0
Using timecop 0.9.6
Using addressable 2.8.1
Using crack 0.4.5
Using faraday 2.7.4
Using mocha 2.0.2
Using cucumber-gherkin 22.0.0
Using cucumber-html-formatter 17.0.0
Using mime-types 3.4.1
Using nokogiri 1.14.2 (x86_64-darwin)
Using pry 0.14.2
Using minitest-fail-fast 0.1.0
Using parser 3.2.1.0
Using cucumber-core 10.1.1
Using sawyer 0.9.2
Using cucumber-wire 6.2.1
Using minitest-reporters 1.6.0
Using octokit 4.25.1
Using rubocop-ast 1.26.0
Using theme-check 1.14.0
Using rubocop 1.46.0
Using webmock 3.18.1
Using rubocop-minitest 0.28.0
Using rubocop-rake 0.6.0
Using rubocop-shopify 2.12.0
Installing byebug 11.1.3 with native extensions
Installing ffi 1.15.5 with native extensions
Installing concurrent-ruby 1.2.2
Using bugsnag 6.25.2

──────────────────────────────────────────────────────────────────────────────────

**Comment by Michael-Gibbons** [comment]
Much appreciated thank you. The only other suggestion I would have is to document the limits of each extension either on this page: https://shopify.dev/docs/apps/app-extensions/list

or on their respective pages. But that is out of the scope of this package so I will close this issue. Thanks again
