### ISSUE TITLE
[Feature]: HMR Theme Editor

### ISSUE THREAD

**Issue by montalvomiguelo** [Shopify/cli#1461]
### What area(s) will this request affect?

Theme, Running your code locally

### What type of change do you want to see?

New feature

### Overview

It would be nice if the Shopify CLI could handle hot reload within the theme editor when developers serve their themes locally and edit their theme files, so they don't have to reload the page manually to see the updates.

If that was not possible within the Shopify CLI, maybe it could give the developer the flexibility to integrate it with other tools [like Theme Kit](https://shopify.dev/docs/themes/tools/theme-kit/command-reference#integration-with-other-tools):

```bash
# --notify
# The file path or URL. The file path is to a file that you want updated on idle. The URL path is where you want a webhook posted to report on file changes.
shopify theme dev --notify /temp
```

### Motivation

The Shopify CLI currently cannot handle hot reload within the theme editor.

https://user-images.githubusercontent.com/5134470/221616575-a26c06f2-ac2b-4f9d-9d8c-b2ef90d94b9b.mp4

**Comment by alvaro-shopify** [comment]
Hi, thanks for opening this, I'll tag @Shopify/theme-developer-tools  so they can take a look at this.

**Comment by charlespwd** [comment]
We already support hot reloading. But you have to use the localhost URL.

https://shopify.dev/docs/themes/tools/cli/commands#dev

**Comment by montalvomiguelo** [comment]
@karreiro I would be very willing to implement this if it aligns with the project roadmap (:

**Comment by montalvomiguelo** [comment]
I'm open to that. I'll start working on this and share my questions and progress with you (: 
Thanks @karreiro
