### ISSUE TITLE
[Bug]: Unable to deploy extension via CI/CD

### ISSUE THREAD

**Issue by iamvishnusankar** [Shopify/cli#1471]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Deploy extensions to Shopify successfully.

### Actual behavior

The Partners GraphQL API responded unsuccessfully with the HTTP status  200 and errors

<img width="650" alt="Screenshot 2023-02-28 at 11 11 18 AM" src="https://user-images.githubusercontent.com/4602725/221764523-cc8a55a5-1b78-4fef-a950-e17c624e4b94.png">

### Reproduction steps

1. Deploy extensions via GitHub actions

### Operating System

Ubuntu 20.04.5 5 LTS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Node version (run `node -v` if you're not sure)

18

**Comment by alvaro-shopify** [comment]
Hi @iamvishnusankar . Thanks for your effort adding more context to the issue. 

Regarding the first error posted in the description of the issue

<img src="https://user-images.githubusercontent.com/105213827/223656535-38f06764-5497-4cfd-9925-d993cf6fa2fe.png" width=400/>

The error `500` in this case means that your are trying to deploy a local app with extensions that don't exist in the remote app. The CLI is trying to create those extensions remotely however the `partners token` does not have permissions for that only for modifying the app. So that's the source of the problem of that `500` error. To avoid that you should always do a manual deployment and after it's successfully finished you can configure the CI/CD with the values you will find in the `.env` file generated. These instructions are better explained [here](https://shopify.dev/docs/apps/tools/cli/ci-cd)

**Comment by alvaro-shopify** [comment]
Regarding the second error

```javascript
2023-03-01T16:30:40.4351513Z - Sec-CH-UA-PLATFORM: linux
2023-03-01T16:30:40.4352135Z - Content-Type: application/json
2023-03-01T16:30:40.4352405Z
2023-03-01T16:31:40.7382094Z ╭─ error ──────────────────────────────────────────────────────────────────────╮
2023-03-01T16:31:40.7383022Z │ │
2023-03-01T16:31:40.7383812Z │ │
2023-03-01T16:31:40.7384667Z │ The Partners GraphQL API responded unsuccessfully with the HTTP status │
2023-03-01T16:31:40.7385528Z │ 504 and errors: │
2023-03-01T16:31:40.7386259Z │ │
2023-03-01T16:31:40.7387048Z │ _** │
2023-03-01T16:31:40.7387770Z │ │
2023-03-01T16:31:40.7388466Z │ │
2023-03-01T16:31:40.7389237Z ╰──────────────────────────────────────────────────────────────────────────────╯
2023-03-01T16:31:40.7389609Z
2023-03-01T16:31:40.7608847Z 2023-03-01T16:31:40.760Z: Obtaining the dependency manager in directory /home/runner/work/appnamey/appnamey...
2023-03-01T16:31:40.7610917Z 2023-03-01T16:31:40.760Z: Obtaining the dependency manager in directory /home/runner/work/appnamey/appnamey...
2023-03-01T16:31:40.7732866Z 2023-03-01T16:31:40.773Z:
2023-03-01T16:31:40.7733729Z Running system process:
``` 

where you can see a `504` it seems to be a temporary error due to some network congestion, so it should not be persistent

**Comment by 3Wizzy** [comment]
Im still facing this issue 
`
╭─ error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                           │
│                                                                                                                                           │
│  The Partners GraphQL API responded unsuccessfully with errors:                                                                           │
│                                                                                                                                           │
│  [                                                                                                                                        │
│    {                                                                                                                                      │
│      "message": "Unexpected system error",                                                                                                │
│      "extensions": {                                                                                                                      │
│        "code": "500"                                                                                                                      │
│      }                                                                                                                                    │
│    }                                                                                                                                      │
│  ]                                                                                                                                        │
│                                                                                                                                           │
│  Request ID: 2b013ae6-1684-4149-9f79-d231d050f36a-1729786228                                                                              │
│                                                                                                                                           │
│                                                                                                                                           │
│  To investigate the issue, examine this stack trace:                                                                                      │
│    at makeRequest (Program%20Files/NVM/v20.10.0/node_modules/@shopify/cli/dist/chunk-OBGMH362.js:29869)                                   │
│    at processTicksAndRejections (node:internal/process/task_queues:95)                                                                    │
│    at async makeVerboseRequest (Program%20Files/NVM/v20.10.0/node_modules/@shopify/cli/dist/chunk-OBGMH362.js:29899)                      │
│    at async retryAwareRequest (Program%20Files/NVM/v20.10.0/node_modules/@shopify/cli/dist/chunk-OBGMH362.js:29972)                       │
│    at (Program%20Files/NVM/v20.10.0/node_modules/@shopify/cli/dist/chunk-OBGMH362.js:31486)                                               │
│    at (Program%20Files/NVM/v20.10.0/node_modules/@shopify/cli/dist/chunk-XQBHX6FC.js:29921)                                               │
│                                                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯`
