### ISSUE TITLE
[shopify-api/ERROR]: Missing Authorization header, was the request made with authenticatedFetch?

### ISSUE THREAD

**Issue by adithwip** [Shopify/cli#1480]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

For context, I had an [error relating to shopify-api](https://github.com/Shopify/shopify-api-js/issues/579) library.
Turns out the issue can be resolved if the library migrated to v6.
After migrating and also following what [the latest Node App Template source code](https://github.com/Shopify/shopify-app-template-node) looks like.

I successfully migrate my existing app without any [issues like before](https://github.com/Shopify/shopify-api-js/issues/579) (created with Shopify CLI) and **_had no issue when running `yarn dev` to test the app in the development store._**
This is my App Url config, with an auto-update option in the Shopify CLI command (I used a different Development Store and App for the dev-test).

<img width="969" alt="Screen Shot 2023-03-01 at 11 07 33" src="https://user-images.githubusercontent.com/27177332/222026301-7c58cf1a-b150-4db8-b498-61e209875fca.png">

It'll be running just fine:
```bash
2023-03-01 01:57:14 | backend    | [shopify-app/INFO] Running ensureInstalledOnShop
2023-03-01 01:57:18 | backend    | [shopify-app/INFO] Running ensureInstalledOnShop
2023-03-01 01:57:18 | backend    | [shopify-app/INFO] App is installed and ready to load | {shop: elife-test-shop-hnagai.myshopify.com}
2023-03-01 01:57:18 | backend    | [shopify-app/INFO] Running ensureInstalledOnShop
2023-03-01 01:57:18 | backend    | [shopify-app/INFO] App is installed and ready to load | {shop: elife-test-shop-hnagai.myshopify.com}
2023-03-01 01:57:19 | backend    | [shopify-app/INFO] Running validateAuthenticatedSession
2023-03-01 01:57:19 | backend    | [shopify-app/INFO] Request session has a valid access token | {shop: elife-test-shop-hnagai.myshopify.com}
2023-03-01 01:57:28 | backend    | [shopify-app/INFO] Running ensureInstalledOnShop
2023-03-01 01:57:28 | backend    | [shopify-app/INFO] App is installed and ready to load | {shop: elife-test-shop-hnagai.myshopify.com}
2023-03-01 01:57:28 | backend    | [shopify-app/INFO] Running validateAuthenticatedSession
2023-03-01 01:57:29 | backend    | [shopify-app/INFO] Request session has a valid access token | {shop: elife-test-shop-hnagai.myshopify.com}
2023-03-01 01:57:32 | backend    | [shopify-app/INFO] Running validateAuthenticatedSession
2023-03-01 01:57:33 | backend    | [shopify-app/INFO] Request session has a valid access token | {shop: elife-test-shop-hnagai.myshopify.com}
```

Then I deployed the app to AWS App Runner, which is successfully built, containerized, and deployed. I expected it'll be running just fine like in the test (with ngrok). But when I see the deployment logs, there is a **runtime error**.

### Actual behavior

In the AWS App Runner deployment logs, it shows:
```bash
03-01-2023 10:21:59 AM [shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: false}
03-01-2023 10:21:59 AM [shopify-app/INFO] Running validateAuthenticatedSession
03-01-2023 10:21:59 AM [shopify-app/INFO] Session was not valid. Redirecting to /api/auth?shop=elife-recipe-app-development.myshopify.com | {shop: elife-recipe-app-development.myshopify.com}
```
#
The app is refused to connect if I open my Development Store for the AWS App Runner deployed Shopify App.
I don't understand why if the app is `built` and `served`, it won't make the correct behavior like when I run it for a test (`dev`).
The URL from AWS App Runner has already been copied to the App Url and redirection Url(s):

<img width="677" alt="Screen Shot 2023-03-01 at 10 34 54" src="https://user-images.githubusercontent.com/27177332/222022254-dc50d273-5bb5-4f88-af62-651463c3a34f.png">

#
And this is what my Dockerfile looks like:
```dockerfile
FROM node:18-alpine

ARG SCOPES
ARG SHOPIFY_API_KEY
ARG SHOPIFY_API_SECRET
ARG HOST
ENV SCOPES=$SCOPES
ENV SHOPIFY_API_KEY=$SHOPIFY_API_KEY
ENV SHOPIFY_API_SECRET=$SHOPIFY_API_SECRET
ENV HOST=$HOST
ENV BACKEND_PORT=8081
EXPOSE 8081
WORKDIR /app
COPY web .
COPY tsconfig.json .
RUN npm install
RUN cd frontend && npm install && npm run build
CMD ["npm", "run", "serve"]
```

# Are there any configurations I missed?
I also try to make a new Node App from scratch with Shopify app cli.
Reproduced the step with Docker:
- Build the Image based on the default Dockerfile
- Run the container with 8081 Port (like in the Dockerfile)
- The issue is still the same, something wrong with the Authorization

### Stack trace

```shell
03-01-2023 10:21:58 AM [shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: false}
03-01-2023 10:21:58 AM [shopify-app/INFO] Running validateAuthenticatedSession
03-01-2023 10:21:57 AM [shopify-app/INFO] Session was not valid. Redirecting to /api/auth?shop=elife-recipe-app-development.myshopify.com | {shop: elife-recipe-app-development.myshopify.com}
03-01-2023 10:21:57 AM [shopify-app/INFO] Running validateAuthenticatedSession
03-01-2023 10:21:49 AM [shopify-app/INFO] App is installed and ready to load | {shop: elife-recipe-app-development.myshopify.com}
03-01-2023 10:21:49 AM [shopify-app/INFO] Running ensureInstalledOnShop
03-01-2023 10:21:49 AM [shopify-app/INFO] Running ensureInstalledOnShop
03-01-2023 10:21:49 AM [shopify-app/INFO] Running ensureInstalledOnShop
03-01-2023 10:21:46 AM [shopify-app/INFO] App is installed and ready to load | {shop: elife-recipe-app-development.myshopify.com}
03-01-2023 10:21:46 AM [shopify-app/INFO] Running ensureInstalledOnShop
03-01-2023 10:21:46 AM [shopify-app/INFO] Running ensureInstalledOnShop
03-01-2023 10:09:55 AM [shopify-api/INFO] version 6.2.0, environment Node v18.14.1
03-01-2023 10:09:42 AM > cross-env NODE_ENV=production ts-node index.ts
03-01-2023 10:09:42 AM > serve
```

### Reproduction steps

1. Create a release tag
2. GitHub Action spin up
3. Deployed to AWS App Runner
4. Open the Shopify test store
5. Click the app in the Admin Dashboard
6. The app broken
7. In the AWS App Runner deployment logs it shows the error above

### Operating System

ubuntu-20.04 (AWS App Runner runtime)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.34.0

### Shell

bash

### Node version (run `node -v` if you're not sure)

node:18-alpine (Dockerfile)

### What language and version are you using in your application?

TypeScript v4.7.4

**Comment by alvaro-shopify** [comment]
Hi, thanks for opening this, I'll tag @Shopify/client-libraries-app-templates so they can take a look at this.

**Comment by adithwip** [comment]
Thank you for the help.
The issue has been solved!

The root cause was there was a bug in the source code relating to authenticating merchants when opening the app.
I initially start the app I'm working on about 6 months ago, with Shopify App and CLI v3.34.0 I guess.
So the default codes like `auth.js`, `verify-request.js`, and other implementations are different from the latest version in `v3.44.1`. When I migrate the `@shopify/shopify-api` library from v5 to v6, there should be a removal of the previous codes like in the authorization logic. And fully use what Shopify has implemented in the latest version of `The node template`.

The bugs is relating to the logic that stores the user session to the preferred default database (SQLite). So when the app is installed in a different Development Store, the required `accessToken` from the database is missing. This resulted in the error as I explain above.

Hope it helps other people if they have a similar issue!

**Comment by abhinavpanse** [comment]
@adithwip  I'm still seeing this issue.

**Comment by adithwip** [comment]
Hey guys @hasnainmalikqf @abhinavpanse 
My root cause was a bug with the logic from the auth to store the accessToken to the desired DB (in default SQLite).
It was caused by a mixed logic between my previous implementation with the old version of Shopify CLI and the newest implementation of Shopify CLI and Shopify API library. There were breaking changes not long ago.

So, I had to manually check every old built-in (generated) code from the previous major version of the Shopify CLI.
I removed it and simply used the current NodeJS example code. After that, the logic for the Auth is bug-free.

So, be sure to use the code from the current NodeJS app template.

To try to reproduce the bug and make sure the bug is fixed.
Try to install SQLite tools to see the database with UI.
You can try the best one you found online.
Delete the data from the SQLite database in the app directory.
And try again.

Hope it'll fix it!

**Comment by silasbispo01** [comment]
I'm having the same problem, how can i resolve this?

**Comment by hasnainmalikqf** [comment]
> [changeyoucant](/changeyoucant)

I have manage to resolve it, Please import {useAuthenticatedFetch} from "../hooks" in frontend then assign any constant to useAuthenticatedFetch like this const fetch = useAuthtenticatedFetch(); now to your error will be gone, please let me know further if you encounter any error.
