### ISSUE TITLE
[Feature]: Add a way for UI extensions to know their (tunnelled) backend URL

### ISSUE THREAD

**Issue by pepicrft** [Shopify/cli#15]
[Reference](https://github.com/Shopify/shopify-cli-next/issues/217)

### What type of project(s) will this request affect?

Extension

### What type of change do you want to see?

New feature

### Overview

Checkout extensions (and, likely, other extensions too) need to be able to call to their own app’s backend. These extensions generally require being served over HTTPS, and all network calls those extensions make will also need to be made over HTTPS.

Currently, an extension has no way of knowing the HTTPS URL of their backend during development. We need to give them a way to do so that will work and feel nice to use both in production and development.

This feels like it should probably be an environment variable that is injected in at build/ dev time, but I am not sure if we actually know before we start the development server what the tunnel URL will be. It's also a little odd as an environment variable because during development Shopify is the only one that knows/ can set the environment variable, whereas in production, the partner is the only one that will for sure know what the correct URL is.

### Motivation

We were discussing extension network access and tunnelling in CLI 3.0, and this came up as an unknown!

**Comment by paweltatarczuk** [comment]
I'm also interested in this feature, for now I'm using a patched version of `@shopify/app` package that passes the `PUBLIC_URL` env when extension is run in development mode:

```
diff --git a/dist/cli/utilities/extensions/configuration.js b/dist/cli/utilities/extensions/configuration.js
index 48f59013f9bb49caa43ad1b4d6ced6d61d040765..9b2db52bd2d98aed30d489c97cbff83e56451369 100644
--- a/dist/cli/utilities/extensions/configuration.js
+++ b/dist/cli/utilities/extensions/configuration.js
@@ -44,7 +44,10 @@ export async function extensionConfig(options) {
                     env: options.app.dotenv?.variables ?? {},
                 },
                 develop: {
-                    env: options.app.dotenv?.variables ?? {},
+                    env: {
+                        PUBLIC_URL: options.url,
+                        ...(options.app.dotenv?.variables ?? {}),
+                    },
                 },
             },
             capabilities: extension.configuration.capabilities,
```

Not sure if that's the best approach in this case but it works for me.

**Comment by paweltatarczuk** [comment]
Isn't this resolved now thanks to this [commit](https://github.com/Shopify/cli/commit/82388a2ac6d348049494eaa3729982945b73d5e6)? It works for Subscription UI extension.

**Comment by pepicrft** [comment]
Correct. It should work for all the extension types. Thanks for pointing this out @paweltatarczuk
