### ISSUE TITLE
[Bug]: Couldn't Find App With ApiKey - when application is deleted

### ISSUE THREAD

**Issue by 1000p** [Shopify/cli#1544]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

Initializing an application with the same application name should refresh persisted local data.

### Actual behavior

Persisted local data is not refreshed upon new initialization. An error appears when starting the application:
`Couldn't Find App With ApiKey`

### Stack trace

```
│  Couldn't find App with apiKey 1b0dea9cf4ff337a4d128c0ff968b34d.             │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at appFromId (@shopify/app/src/cli/services/context.ts:200)               │
│      if (!app) throw new BugError(`Couldn't find App with apiKey             │
│      ${appId}.`)                                                             │
│    at processTicksAndRejections (node:internal/process/task_queues:95)       │
│    at all                                                                    │
│    at async ensureDevContext (@shopify/app/src/cli/services/context.ts:152)  │
│      const [organization, _selectedApp, _selectedStore] = await              │
│      Promise.all([                                                           │
│    at async dev (@shopify/app/src/cli/services/dev.ts:74)                    │
│      } = await ensureDevContext(options, token)                              │
│    at run (@shopify/app/src/cli/commands/app/dev.ts:100)                     │
│      await dev({
```

### Reproduction steps

1. `npm init @shopify/app@latest`
2. fill out all the required initialization data, project name, template, etc.
3.  `npm run dev`
4. You will be asked to enter application name - create an application with the name "choose-your-name". Take note of the application name, it will be important.
5. Install the application on your dev. store - using P from the command line after application is started
6. Go to your Shopify Partner account and delete that application that you have just created.
7. Delete local project files

Next:

1. `npm init @shopify/app@latest`
2. fill out all the required initialization data, project name, template, etc. 
3.`npm run dev`
4. You will be asked to enter the application name - you should choose the application name of the app that you just deleted
5. The for store - choose the same one as before 
6. Error is produced: `Couldn't Find App With ApiKey`

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

cmd

### Node version (run `node -v` if you're not sure)

18.14.0

### What language and version are you using in your application?

Node

**Comment by tomadelaney** [comment]
Having same issue with 
OS     Mac 11.6.5
CLI     3.44.1
Node 19.7.0

**Comment by 1000p** [comment]
> Hi there, we cache the application information in your local filesystem, if you run `npm run dev -- --reset` it should clear that information and let you dev your app.

Can you edit your answer with the cache location, please? Probably can be helpful for future reference, thanks!

**Comment by tomadelaney** [comment]
Thanks, npm run dev -- --reset cleared up the issue for me.

Two suggestions:
1) Update CLI documentation to reflect this fix to a common problem
2) If changes are made to the local development filesystem, this too should be documented.

Thanks again!

**Comment by tomadelaney** [comment]
Ju,Thanks for the follow-up.  When I was stuck on this issue, my attempts to use— reset did not work, but your suggestion to pass  — —reset with my command solved the problem.  Thank you,Tom-- Thomas A. Delaney, P.E.Email:   ***@***.***:   917-282-3317On Mar 8, 2023, at 6:12 AM, Ju Liu ***@***.***> wrote:﻿
Hey folks, just a quick update: I looked at the code and figured out we could do a quick improvement and show the suggestion with the error (PR here). So in the future people will see:
Could not find the app with API key "1234". You can pass `--reset` to your command to reset your config.

**Comment by Arkham** [comment]
Unfortunately that's just how npm scripts takes options 🤦 https://docs.npmjs.com/cli/v9/commands/npm-run-script#synopsis

If you use `yarn` or `pnpm` you can simply run: `yarn dev --reset` or `pnpm dev --reset`

**Comment by tomadelaney** [comment]
😳 My mistake!  Too used to yarn.  Learning node, polaris, apollo,  graphql, webpack, vite, and numerous libraries all at once - and something this simple got me.  I appreciate your assistance 👍-- Thomas A. Delaney, P.E.Email:   ***@***.***:   917-282-3317On Mar 8, 2023, at 6:38 AM, Ju Liu ***@***.***> wrote:﻿
Unfortunately that's just how npm scripts takes options 🤦 https://docs.npmjs.com/cli/v9/commands/npm-run-script#synopsis
If you use yarn or pnpm you can simply run: yarn dev --reset or pnpm dev --reset
