### ISSUE TITLE
[Bug]: Can't copy/paste link to Partners dashboard

### ISSUE THREAD

**Issue by NathanJolly** [Shopify/cli#1547]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

This helpful link should be easy to copy / paste

### Actual behavior

Trying to copy this results in a string like 
```
https://partners.shopify.com/9082/apps/2843795/extens  │
│      ions/pos_ui_extension/19899744257
```

<img width="986" alt="image" src="https://user-images.githubusercontent.com/29490857/222802901-a0b25d2c-ba8e-4d7e-afbc-fabace419454.png">

### Reproduction steps

1. Deploy an extension `shopify app deploy`
2. Try to follow the link that's presented

### Operating System

Ventura 13.2.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.14.0

**Comment by Arkham** [comment]
cc @matteodepalo @MeredithCastile I think we mentioned we wanted to add a summary of links at the bottom of the banners, so users can follow links. are we still committed to doing that?

**Comment by matteodepalo** [comment]
Yes good point, this has been fixed with footnotes.
