### ISSUE TITLE
[Bug]: `shopify app deploy` ignores `theme-check-disable` comments and config file

### ISSUE THREAD

**Issue by immakdas** [Shopify/cli#1549]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Expected to respect `{% # theme-check-disable %}` tag as per Shopify documentation
see 
https://shopify.dev/docs/themes/tools/theme-check/configuration#disable-checks-using-liquid-comments
https://shopify.dev/docs/themes/tools/theme-check/checks/img-width-and-height#disabling-this-check

and respect valid modern HTML code. Why do I even ask for this?

### Actual behavior

theme-check-disable tag ignored and an error returned when pushed code 
`Missing width and height attributes at blocks/conditional-app-block.liquid:348`

### Reproduction steps

1. in your app extension use code like
```
{% # theme-check-disable ImgWidthAndHeight %}
                            <img
                              data-aspectratio="1.33333"
                              sizes="auto"
                              style="max-width:100%;"
                              loading="lazy"
                              src="{{ bannerimage }}?&width=1512"
                              srcset="
                                {{ bannerimage }}?&width=180 180w,
                                {{ bannerimage }}?&width=720 720w,
                                {{ bannerimage }}?&width=900 900w,
                                {{ bannerimage }}?&width=1296 1296w,
                                {{ bannerimage }}?&width=1512 1512w,
                                {{ bannerimage }}?&width=1944 1944w,
                                {{ bannerimage }}?&width=4024 4024w
                              "
                            >
                            {% # theme-check-enable ImgWidthAndHeight %}
```

2. ` npm run deploy`

### Operating System

Ubuntu 16.04.6 LTS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Node version (run `node -v` if you're not sure)

v14.17.2

### What language and version are you using in your application?

Ruby 3.0.1

**Comment by sillycube** [comment]
I'm having the same problem. My liquid file is using Vue but the CLI doesn't let me run deploy. My script tag
```
<script src="https://unpkg.com/vue@3.2.6/dist/vue.global.prod.js"></script>
<script src="https://unpkg.com/vue-i18n@9.1.6/dist/vue-i18n.global.prod.js"></script>
```

I try to add 
`{% # theme-check-disable ParserBlockingJavaScript %}`
or 
`{% # theme-check-disable %}`. It's still the same. The error:
Missing async or defer attribute on script tag at ....

If I add the async or defer attribute, it gives me Vue is not defined error in the console. It drives me crazy. Now I'm trying to refactor my section liquid files to the theme app extension. I just want to run my files without dealing with these issues.

**Comment by immakdas** [comment]
@sillycube I have the same problems with my js libs. If set defer or async they are not working because of basic javascript loading priority. How this can be overlooked? 
And one more ugly non-professional stuff. My project works on React 18 but Shopify CLI v3.44.1 adds the React 17 as one of the dependencies so now to support "new Shopify stuff" I have to downgrade all working and live app projects to outdated code. 
Does anyone who designs new Shopify Cli have ever try to migrate real-life apps to this? Seems to me it is impossible to switch from deprecated Assets API to a new theme app extension due to a lack of sense in the Shopif CLi restrictions (old react and no support for app.metafields  in the theme app block settings (..... what?? )).

**Comment by roptch** [comment]
Same problem here, either by disabling theme check with liquid comments:
```js
{% # theme-check-disable %}
<script src="XXX"></script>
{% # theme-check-enable %}
```

or with the ` .theme-check.yml` file:
```yml
ParserBlockingJavaScript:
  enabled: false
  ignore: []

ParserBlockingScriptTag:
  enabled: false
  ignore: []
```

Neither of these solutions work, any update on this issue ?

**Comment by immakdas** [comment]
@Poitrin you run the theme check command but have to run **npm run deploy** which internally run its own theme checks and does not to deploy theme app extension

**Comment by Poitrin** [comment]
@Shopify/cli-foundations – The error appears in the [`uploadThemeExtensions` function](https://github.com/Shopify/cli/blob/main/packages/app/src/cli/services/deploy/upload.ts#L68).

When I print `result.extensionUpdateDraft.userErrors` (for my code from my previous screenshot), I get:

```JS
[
  {
    field: [ 'bundle' ],
    message: 'Undefined object `bannerimage` at blocks/my-block.liquid:28'
  },
  // ...
  {
    field: [ 'bundle' ],
    message: 'Missing async or defer attribute on script tag at blocks/my-block.liquid:42'
  },
  // ...
  {
    field: [ 'bundle' ],
    message: 'Missing width and height attributes at blocks/my-block.liquid:23'
  }
]
```

Do you have an idea how to proceed? The way _I_ see it, we would need to …
1. Either make `ExtensionUpdateDraftMutation` respect all disable comments and Theme Check config
2. Or avoid running Theme Check in this mutation, as it seems to be running already locally:
```
Running system process:
  · Command: bundle exec theme-check /Users/poitrin/src/github.com/Shopify/cli/draft-app/extensions/draft-extension -C :theme_app_extension
  · Working directory: /Users/poitrin/Library/Caches/shopify-cli-nodejs/vendor/theme-check/1.14.0

 theme_extensions │ Checking /Users/poitrin/src/github.com/Shopify/cli/draft-app/extensions/draft-extension ...
 theme_extensions │ 2 files inspected, 0 offenses detected, 0 offenses auto-correctable
```

**Comment by karreiro** [comment]
Closing, as considering the [latest comment](https://github.com/Shopify/cli/issues/1549#issuecomment-1498702649), the issue doesn't seem related to Theme Check but to the theme app extension code. Please, feel free to re-open if I'm missing something.
