### ISSUE TITLE
[Bug]: Webpixel won't update

### ISSUE THREAD

**Issue by jeff0723** [Shopify/cli#1551]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

I've tried to update my webpixel extension by deploying a new version and publishing it.

However, no matter how I try it's not updating. Try several times and no one of them succeeds.

### Actual behavior

Can successfully update webpixel by deploying and publishing new version.

### Reproduction steps

1. Create a webpixel extension
2. Deploy the first version
3. Publish the first version
4. Deploy the second version
5. Publish the second version

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.38.0

**Comment by matteodepalo** [comment]
Hi @jeff0723 thank you for reporting this issue. Could I have a minimal code reproduction for the webpixel extensions you're trying to deploy and what you're expecting to happen exactly?

**Comment by matteodepalo** [comment]
@adventuretocode have you updated to the latest CLI version?
