### ISSUE TITLE
`npm run dev` results in "429 too many requests" error on fast internet connections

### ISSUE THREAD

**Issue by emcmanus** [Shopify/cli#1552]
`npx shopify app dev --verbose` indicates that the CLI makes 5+ partner GraphQL requests in under a second (once the CLI is configured), almost always triggering a 429 rate limit on fast internet connections.

the result is that `npm run dev` rarely works, except when a GraphQL request takes a while to complete, keeping you under the rate limit.

please consider throttling. here's the relevant function:

https://github.com/Shopify/cli/blob/cb492ee535c933d548c994539c9b27bb87ecb5c0/packages/cli-kit/src/private/node/api/graphql.ts#LL12C8-L12C31

**Comment by emcmanus** [comment]
There are 2 other reports in the community forum https://community.shopify.com/c/shopify-apis-and-sdks/node-js-shopify-api-crashing-app-how-to-resolve/m-p/1972409

**Comment by zvndev** [comment]
I've just installed a new node app which ran with no problem.  When I stopped the app and restarted it with `npm run dev` I then get the same rate limit error.  I just confirmed this with a brand new app with 0 customizations.
