### ISSUE TITLE
[Bug]: Shopify theme push -u breaks translations from Translate & Adapt app

### ISSUE THREAD

**Issue by kfalkiewicz** [Shopify/cli#1562]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When store has **Translate & Adapt** app installed, the translations should be connected to every version of same theme. So for those created in the process bellow also.

Process:

1. Pull latest live version of the theme - `shopify theme pull`
2. Do local changes
3. Push your changes with `shopify theme push -u -t "New name"`

### Actual behavior

When you push local theme changes with `shopify theme push -u -t "New name"` the new theme is created, but it also "disconnected" from the **Translate & Adapt** app translations (no translations to the templates). If you instead duplicate the original theme and then push local changes with `shopify theme push -t xxxxxx` (xxxxxx - id of the duplicated theme) then all of the translations works fine.

### Reproduction steps

1. Pull latest live version of the theme - `shopify theme pull`
2. Do local changes
3. Push your changes with `shopify theme push -u -t "New name"`
4. Your new theme has missing translations from the **Translate & Adapt** app

### Operating System

macOS 11.6

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.4.0

**Comment by kfa-spyro** [comment]
> I'm sorry that you lost your precious translations. I tried to reproduce your issue, but haven’t been able to. Here’s what I did:
> 
> 1. That's my current store with its live theme and translations for English, German, French:
>    ![1](https://user-images.githubusercontent.com/12963280/224319790-d09cdbce-bd92-4d67-b114-9123a0ab97e4.jpg)
> 2. `shopify theme list` and `shopify theme pull`:
>    ![2](https://user-images.githubusercontent.com/12963280/224319949-02707450-1c38-4fd3-91e7-c60da13b7f5c.jpg)
> 3. I then added some changes.
> 4. `shopify theme push -u -t "New name"`:
>    ![3](https://user-images.githubusercontent.com/12963280/224320073-21f4fd14-6cdf-476a-8647-678065062693.jpg)
> 5. And when I open the theme preview, I still had the same German translations. I also appended `/fr` to the URL:
>    ![4](https://user-images.githubusercontent.com/12963280/224320406-a0afd5e3-8ff6-406c-bdd0-ee40bceb8b73.jpg)
> 
> Translations like _Maison_ or _Catalogue_ are only in the Translate & Adapt app, not in my theme code.
> 
> Is there something I missed?

In my case, the translations added by Translate & Adapt app for the template sections weren't properly moved when I did `shopify theme -u -t`. Try also when pulling without `--live` flag.

**Comment by kfa-spyro** [comment]
From what I remember it only affected the sections inside HopePage and other templates. Main Menu or Footer was fine. So when you translate the "ImageBanner" and retry it should be not translated.

**Comment by Poitrin** [comment]
Right, thanks for clarifying this! I actually did have a French translation for "Image banner", which did not show up in my new theme. I think the problem was that we expected Translate & Adapt translations to be connected to the store, although they are connected to a theme.
![translations](https://user-images.githubusercontent.com/12963280/225243880-8678d9f9-88ef-46b4-af17-2c7cdcf88f02.png)
So when we `theme push -u` a new theme, publish it afterwards, and go to Translate & Adapt, we might be shocked because translations are missing.

But they are still available in the previous live theme.
![1](https://user-images.githubusercontent.com/12963280/225246405-2ac2a7ba-ecae-42d7-a21d-037a1bc65b97.jpg)
![2](https://user-images.githubusercontent.com/12963280/225246413-536afafe-db3b-4e68-9f57-cd695a7c30d9.jpg)

Navigation and footer translations are store-wide though, so that explains why they were still visible.

**Comment by kfa-spyro** [comment]
Yes, duplicate is the solution, but still, this is the problem. When I change the Live theme then those translations are not re-attached. They are only in the situation when you duplicated theme first.

**Comment by nboliver-ventureweb** [comment]
This is still very much an issue. The proposed solution of manually duplicating themes in the admin is not viable in CI/CD workflows.

**Comment by Ltwrk** [comment]
Its 2026 and the issue still exists... Shopify when are you going to fix that?

**Comment by nboliver-ventureweb** [comment]
> Its 2026 and the issue still exists... Shopify when are you going to fix that?

Was just doing some testing, so far it looks like the `shopify theme duplicate` command preserves translations. Unfortunately this doesn't seem to be documented anywhere as far as I can tell...

**Comment by Ltwrk** [comment]
Yes you are right, when duplicating a theme it works. But e.g. when you connect a new branch, Shopify sees this template as a new one. This is then not containing the translations.

Just wrote a a GitHub action where I can plugin old and new theme id which is then copying all translations over.

**Comment by dspeake** [comment]
@Ltwrk would you mind sharing that action please?
