### ISSUE TITLE
[Bug]:  Package subpath './node/cli' is not defined by "exports" When running npm init @shopify/app@latest 

### ISSUE THREAD

**Issue by tman16** [Shopify/cli#1575]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The package shopify/app should be successfully installed

### Actual behavior

The following error is thrown and the install fails:

internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node/cli' is not defined by "exports" in /Users/tom/.npm/_npx/f27a05a5c3c9c53d/node_modules/@shopify/cli-kit/package.json imported from /Users/tom/.npm/_npx/f27a05a5c3c9c53d/node_modules/@shopify/create-app/dist/index.js
    at throwExportsNotFound (internal/modules/esm/resolve.js:267:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:487:3)
    at packageResolve (internal/modules/esm/resolve.js:584:14)
    at moduleResolve (internal/modules/esm/resolve.js:633:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:82:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:226:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
npm ERR! code 1
npm ERR! path /Users/tom/New App
npm ERR! command failed
npm ERR! command sh -c create-app

### Verbose output

```shell
npm verb cli /Users/tom/.nvm/versions/node/v18.11.0/bin/node /Users/tom/.nvm/versions/node/v18.11.0/bin/npm
npm info using npm@9.6.0
npm info using node@v18.11.0
npm verb title npm init @shopify/app@latest
npm verb argv "init" "@shopify/app@latest" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/Users/tom/.npm/_logs/2023-03-07T19_13_50_804Z-
npm verb logfile /Users/tom/.npm/_logs/2023-03-07T19_13_50_804Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/@shopify%2fcreate-app 1735ms (cache revalidated)
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node/cli' is not defined by "exports" in /Users/tom/.npm/_npx/f27a05a5c3c9c53d/node_modules/@shopify/cli-kit/package.json imported from /Users/tom/.npm/_npx/f27a05a5c3c9c53d/node_modules/@shopify/create-app/dist/index.js
    at throwExportsNotFound (internal/modules/esm/resolve.js:267:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:487:3)
    at packageResolve (internal/modules/esm/resolve.js:584:14)
    at moduleResolve (internal/modules/esm/resolve.js:633:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:82:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:226:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/Users/tom/.nvm/versions/node/v18.11.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:513:28)
npm verb stack     at maybeClose (node:internal/child_process:1091:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb cwd /Users/New App
npm verb Darwin 21.6.0
npm verb node v18.11.0
npm verb npm  v9.6.0
npm ERR! code 1
npm ERR! path /Users/tom/New App
npm ERR! command failed
npm ERR! command sh -c create-app
npm verb exit 1
npm verb code 1
```

### Reproduction steps

1. Following guide here: https://shopify.dev/docs/apps/getting-started/create
2. Cannot get further than: npm init @shopify/app@latest

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Node version (run `node -v` if you're not sure)

 v18.11.0

**Comment by Arkham** [comment]
Hi tom, I can create a new app just fine using `npm init @shopify/app@latest`. From your verbose output I can see references to `/Users/tom/.npm/_npx` which makes me think you might have another version of the shopify cli installed through npx?  could you try to clean out that directory with `rm -r ~/.npm/_npx/` and retry?

**Comment by tman16** [comment]
Hi Arkham

Thanks for the reply, it ended up being the CLI version, downgraded to 2.0.14 and worked. Not sure why I couldn't get it to work with v3.44.1
