### ISSUE TITLE
[Feature]: Document how to create a new Typescript app

### ISSUE THREAD

**Issue by nickjanssen** [Shopify/cli#158]
### What area(s) will this request affect?

App

### What type of change do you want to see?

New feature

### Overview

Creating a new app using `yarn create @shopify/app --template node` creates a JS project in `/web`.
Provide documentation on how to do the same for TS. I looked into this repo and issues but couldn't find how to do so.

### Motivation

TS > JS

**Comment by Curzey** [comment]
Would love to see this as well.

**Comment by stevejboyer** [comment]
Would be great if the CLI asked which language to use, when scaffolding out the app for us: Typescript or Javascript. The world is moving to Typescript, and I'm surprised it's not an option already!

**Comment by givorra-coberio** [comment]
Hey, any news on it?

**Comment by alexandrosk** [comment]
It's super important, Typescript is the only way

**Comment by Curzey** [comment]
This is still relevant.

**Comment by DanielHritcu** [comment]
This is still relevant.

**Comment by bezreyhan** [comment]
Any update on this?

**Comment by stephszeto** [comment]
Thanks for flagging! We'll follow up with our internal app templates team about offering an official Typescript template in the future, closing this out in the meantime.

**Comment by iska31** [comment]
@stephszeto any news ? Typescript is a must have nowadays :)

**Comment by frroossst** [comment]
I can't believe this still hasn't been fixed!!!

**Comment by guillegarcia** [comment]
Hello! I am also very interested in this feature. I hope they can work on it soon

**Comment by frroossst** [comment]
They use it internally for their examples on polaris, so da fook?

**Comment by martinratinaud** [comment]
Interested also
