### ISSUE TITLE
[422] API request client error with `shopify theme dev`

### ISSUE THREAD

**Issue by yojisekiya** [Shopify/cli#1589]
We keep getting `[422] API request client error` when trying to run `shopify theme dev` with shopify cli 3.  We tried everything we found in shopify community, but unfortunately none of them has worked for us.

![image](https://user-images.githubusercontent.com/89111327/224294931-93fdf1ff-a6eb-406c-94ef-f21027668b1f.png)

We got the following setup.

<img width="347" alt="image" src="https://user-images.githubusercontent.com/89111327/224294944-37333721-6fbb-4d02-9756-0e1d029869ca.png">

Any idea why we get this error?

We would appreciate any suggestions that might resolve this issue!

**Comment by Arkham** [comment]
hi @yojisekiya, first make sure you are using an account with the right privileges:

> To use a development store or Plus sandbox store with Shopify CLI, you need to be the store owner, or have a [staff account](https://help.shopify.com/manual/your-account/staff-accounts) on the store. Staff accounts are created automatically the first time you access a development store with your Partner staff account through the Partner Dashboard.

After try the following:
- `shopify auth logout`
- logout from the partners dashboard https://partners.shopify.com/auth/logout

Then try again :)

**Comment by yojisekiya** [comment]
@Arkham 

Thank you for the info, I didn't know about `--verbose`, this is really helpful!
I attached logs below, I would appreciate your feedback!

[shopify-cli-logs.txt.zip](https://github.com/Shopify/cli/files/10947956/shopify-cli-logs.txt.zip)

**Comment by Arkham** [comment]
Thank you for the update!

cc @Shopify/theme-developer-tools do you have more context on this?

**Comment by yojisekiya** [comment]
@Poitrin 
Thank so much for looking into it and creating a fix!
I see that the issue has been closed, does this mean that it has been resolved?
Should it work if we installed the latest version of cli?
Or do we need to wait?
