### ISSUE TITLE
[Feature]: deploy environment settings

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#1593]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When I deploy to the development store, using the development App API keypair, I should be able to tell that in the theme App extension code, so that it can configure itself properly. ie) if that is true, JS calls https://dev.foo.com for info and not https://prod.foo.com

the 

### Actual behavior

Theme App Extension executes the code without any clue as to whether it is development or production.

### Verbose output

```shell
yarn run deploy
```

### Reproduction steps

1.
2.
3.

### Operating System

MacOs

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.6

### What language and version are you using in your application?

Ruby 3.2.0

**Comment by alibosworth** [comment]
Somewhat related to this, when you trigger a deploy it says 

>?  Make the following changes to your functions in Shopify Partners?
> Update:  • [function name]
> y/n
>
> ?  Make the following changes to your extensions in Shopify Partners?
>  Update:  • [theme extension name]
> y/n


But you have absolute NO indication of what app it is deploying to.  If you have a staging and a production app, you probably have the functions and extensions named the same, but the CLI process is not very helpful to help you avoid a mistake.

**Comment by alibosworth** [comment]
I believe this is still relevant

**Comment by jriemann** [comment]
Still an issue, from what I can tell.

**Comment by resistorsoftware** [comment]
I'd go out on a limb and say that TAE do not get a lot of attention simply because not a lot of Apps use them. They incur a lot of mental overload, and involve a lot of fringe tech, so yes, it can take a year to get some aspects cleaned up. I have my hopes set that 2024 will see some improvements for them. Fingers crossed. They are not the most orphaned things, but they certainly are not mainline junky material either.
