### ISSUE TITLE
[Feature]: Make URIs generated during development configurable

### ISSUE THREAD

**Issue by darfire** [Shopify/cli#161]
### What area(s) will this request affect?

App, Running your code locally

### What type of change do you want to see?

Substantial change to existing feature

### Overview

When running 'dev' the cli updates the App URLs with the new ngrok tunnel URL. My app has non-standard suffixes so I always have to edit the URLs in the Partners App setup page. It would be nice if you could configure the suffixes in shopify.web.toml. As a bonus, the installation URL and the app-proxy URLs could also be configurable. Here's an idea of how the config could look like:
`
type="frontend"

[commands]
dev = "npm run dev"
build = "npm install --force"

[dev]
redirect_uris = ['/offline/callback', '/online/callback']
root_uri = '/toplevel'
proxy_uri = '/app-proxy/'
`

### Motivation

Every time your run **dev** the URLs are updated. If the app uses non-standard URLs you need to update them manually in the partners dashboard. It slows down development.

**Comment by watzing** [comment]
You can use the `--no-update` flag to stop the urls updating in the shopify app setup dashboard

**Comment by shauns** [comment]
Hi @darfire -- thanks for sharing your idea! Very timely, as we are looking generally at URL updating right now in fact, so will add your feedback to your conversation. 

In the meantime, @watzing comment is a good steer, plus probably using the `--tunnel-url` option to keep your URLs consistent over time by providing your own tunnel.

Can I ask what language/framework/etc. you're using to build your app? Am curious if those URLs are a default from some technology, or of your own choice.

**Comment by stephszeto** [comment]
On board with doing this - adding this to our backlog. I don't think we automatically update the app proxy URL though, so this would primarily just be for the top-level app URL and the redirect URLs.

**Comment by shauns** [comment]
We've added a prompt that you might have seen in `dev`. We now give you the choice to have URLs manually or automatically updated (https://github.com/Shopify/cli/blob/c1fa9ea0d9855832c25f5ed8d4dd5b94179909c5/packages/app/src/cli/prompts/dev.ts#L144 ) -- for your use case I recommend manual. Hope this helps!
