### ISSUE TITLE
Getting Ruby version 2.7.0 is not supported in Vercel

### ISSUE THREAD

**Issue by rupak222** [Shopify/cli#1626]
![gadget-demo-two-–-Deployment-Overview](https://user-images.githubusercontent.com/57125770/226163990-39138896-40f6-4ef1-b45c-46d79ecc9428.png)

when deploying my app in vercel getting this error

**Comment by ThibautRegerat** [comment]
Hello @rupak222, make sure you finish the Shopify CLI 3.X part of the Gadget tutorial. Then it should be ok https://docs.gadget.dev/guides/frontend-deployment/vercel#shopify-cli-3-x

**Comment by rupak222** [comment]
> Hello @rupak222, make sure you finish the Shopify CLI 3.X part of the Gadget tutorial. Then it should be ok https://docs.gadget.dev/guides/frontend-deployment/vercel#shopify-cli-3-x

Thank you so much for the help it's worked!

**Comment by wrightmk** [comment]
@rupak222 @ThibautRegerat This URL doesn't work anymore (Page not found). Do either of you remember the proposed solution? I'm running into this issue as well

**Comment by rupak222** [comment]
@wrightmk maybe ask to gadget support or inquire in their [Discord](https://discord.gg/tTvPergF). Now, I am directly using their frontend hosting instead of Vercel.
