### ISSUE TITLE
[Bug]: WebPixel Checkout Completed ID

### ISSUE THREAD

**Issue by ghost** [Shopify/cli#1630]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

WebPixel returning consistent order id types in checkout_completed event data across stores.

### Actual behavior

Inconsistent order id in the event data of checkout_completed. Some stores are returning 
gid://shopify/OrderIdentity/5210499102 and other stores are returning just the order id e.g 5210499102
There doesn't appear to be any link as to why this occurs on some stores vs others.

### Verbose output

```shell
N/A
```

### Reproduction steps

1. Subscribe to checkout_completed webpixel event
2. Event Data payload returns inconsistent order id in event.data.checkout.order.id

### Operating System

Win 11 & Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

**Comment by kencwng** [comment]
Hi @jake-abconvert . Do you have any more details on how to reproduce this? Is this inconsistency happening on a single shop, or between two shops? Are you using different payment providers (i.e. Shop Pay vs other providers)?

**Comment by SazzadSowmik** [comment]
> Hey @kencwng
> 
> I would like to bring to your attention another issue, this time concerning consistency in the checkout_started event. In our development store, the variant ID is being returned as part of the line item ID (event.data.checkout.lineItems.lineItem[i].id). However, upon deploying to other merchants, we've observed that this isn't consistent across all stores, as the ID could be any arbitrary identifier. We expect the line item ID type to remain consistent regardless of the merchant or store where the extension is deployed. Do you have any documentation that explains why and when we may see different behavior, so we can anticipate it during development?
> 
> Attached are screenshots for reference.
> 
> <img alt="Screenshot 2023-03-28 041312 (1)" width="302" src="https://user-images.githubusercontent.com/128238515/228020498-a1727864-3a37-4332-bb73-420fb755451e.png">
> 
> <img alt="Screenshot 2023-03-28 042832" width="292" src="https://user-images.githubusercontent.com/128238515/228020506-ad4eab01-2e9b-46d4-b0e1-0b88bcf0cab6.png">

Did you find any solution or documentation for this issue? Faced the same issue and looking for the connection with the ID and the variant_id.

**Comment by kencwng** [comment]
@SazzadSowmik do you have two shops where you can consistently reproduce this issue? That would help us to narrow down the issue.

Thanks

**Comment by aaron-barbieriaghib** [comment]
@kencwng just wanted to point out that this issue is still happening! `gid://shopify/Order/123` and `gid://shopify/OrderIdentity/123` seem to be interchangeable, yet I can't find anything about `OrderIdentity` in the docs. Would love to get consistency with the IDs!
