### ISSUE TITLE
[Feature]: Add tar.gz to the cli-kit `zip` helper

### ISSUE THREAD

**Issue by OrganicPanda** [Shopify/cli#1644]
### What area(s) will this request affect?

Other

### What type of change do you want to see?

New feature

### Overview

`zip()` is currently [hardcoded](https://github.com/Shopify/cli/blob/0aa5eb4fe34519e10297977e640dc521f9ab1676/packages/cli-kit/src/public/node/archiver.ts#L42) to `'zip'` but `archiver` supports `tar` with `gzip` so it could be good if the helper in `cli-kit` allowed this.

### Motivation

We took a copy of the function for now to add this (and a couple of other bits). I could submit that as a PR if you want? https://github.com/Shopify/shop-minis-cli/blob/922f9dc8630e07ba6dd2fa63116f66325a0f9600/src/commands/utils/archive.ts#L43

**Comment by amcaplan** [comment]
I wouldn't recommend renaming. Instead I'd move to add a generic function that accepts more options.
