### ISSUE TITLE
[Bug]: `shopify theme pull` not pulling changes from theme editor

### ISSUE THREAD

**Issue by mkudlak** [Shopify/cli#1648]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When using `shopify theme pull` :
- on windows the [development] [yours] should be visible in the list of themes and user should be able to download
- on mac the [development] [yours] is visible, files changes files should download

When `shopify theme pull -d`  is used on windows and mac everything works as expected the changes are visible 

### Actual behavior

When the theme is serving locally and making changes in customizer in theme editor (for example changing title, color etc) and after when pulling the changes from the theme with the command `shopify theme pull` :
- on windows the [development] [yours] is not visible 
- on mac the [development] [yours] is visible but not downloading the theme changes 

When `shopify theme pull -d`  is ussed on windows and mac everything works as expected the changes are visible 

### Verbose output

```shell
shopify theme pull --verbose
2023-03-23T08:15:09.013Z: Running command theme pull
  shopify:theme:pull init version: @oclif/core@2.1.4 argv: [ '--verbose' ] +0ms
2023-03-23T08:15:09.025Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-03-23T08:15:09.025Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store xxx.myshopify.com:
[]

2023-03-23T08:15:09.025Z: Getting session store...
2023-03-23T08:15:09.027Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "xxx.myshopify.com"
  }
}

2023-03-23T08:15:09.027Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-03-23T08:15:09.027Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2023-03-23T08:15:09.310Z: Request to https://accounts.shopify.com/oauth/introspection completed in 276 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"7ba680d5590ac1c3b8202d64c5c3b187"
 - x-request-id: be9cecdf-a3ae-42f4-8015-cc34d7a32c5c
    
2023-03-23T08:15:09.312Z: The identity token is valid: true
2023-03-23T08:15:09.312Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-03-23T08:15:09.317Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Applications/MAMP/htdocs/xxx

2023-03-23T08:15:09.329Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle -v
  · Working directory: /Applications/MAMP/htdocs/xxx

2023-03-23T08:15:09.455Z: Reading the content of file at /opt/homebrew/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2023-03-23T08:15:09.458Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle install
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2023-03-23T08:15:09.699Z: 
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle exec /opt/homebrew/opt/ruby/bin/ruby /opt/homebrew/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme pull /Applications/MAMP/htdocs/xxx
  · Working directory: /Applications/MAMP/htdocs/xxx

DEBUG GET https://xxx.myshopify.com/admin/api/unstable/themes.json with X-Request-Id: 2d5a6f06-a7d6-4f96-98ba-9850357a5755
? Select a theme to pull from xxx.myshopify.com (Choose with ↑ ↓
```

### Reproduction steps

1.`shopify theme pull`
2. 
- on windows the [development] [yours] is not visible 
- on mac the [development] [yours] is visible but not downloading the theme changes made in theme editor when shopify theme dev was working

### Operating System

mac ventura, windows

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Node version (run `node -v` if you're not sure)

18.13.0

**Comment by Arkham** [comment]
cc @Shopify/theme-developer-tools

**Comment by Poitrin** [comment]
The reason why the development theme you created on macOS can not be `pull`ed in Windows is because it is treated as [_foreign development_](https://github.com/Shopify/cli/blob/c8ece7a60b9ac88bb56329b46241f866787dbd99/packages/cli-kit/assets/cli-ruby/lib/project_types/theme/forms/select.rb#L17) and is therefore hidden from the select list. It's as if another developer created – for the same shop – their own development theme, which should also be hidden from you.

The ID of your development theme is saved _locally_, i.e. even though it’s saved on macOS, it is still not saved on Windows.

If you run `shopify theme list --role development` on your Windows machine, you will see the "macOS development theme". With `shopify theme pull --theme <ID>`, you can download the theme files. However, if you then run `shopify theme dev` on Windows, it will create a new development theme.

```
$ shopify theme list --role development
name                                  role                   id
────────────────────────────────────  ─────────────────────  ─────────────
Development (773a6f-MacBookPro)       [development]          #123
Development (000ea6-WINDOWSMACHINE)   [development] [yours]  #456
```

You can verify this if you run `shopify theme info` on macOS and Windows – the development theme IDs should be different, which could explain why changes do not seem to be pulled.

Feel free to ask further questions, or to close the issue if it is clearer now :)
