### ISSUE TITLE
[Bug]: Post-purchase UI extension not working

### ISSUE THREAD

**Issue by SerhiDi** [Shopify/cli#165]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

CLI not working for `Post-purchase UI`

I tried creating a new Shopify app. After that, I added `Post-purchase UI` extension.
In the console I see:

```
To view this extension:
 1. Install Shopify’s post-purchase Chrome extension...
 2. Open the Chrome extension and paste this URL into it...
 3. Run a test purchase on your store to view your extension...
 ```
 
 I create a test product, and create a test checkout: https://help.shopify.com/en/manual/checkout-settings/test-orders
 
 Again. It's a simple app, with a simple extension, without any changes, only a fresh project, created from CLI. 
 
 App working and I can see it in the admin dashboard. 
 But this extension is not.
 

 Issue number one: I don't see anything after checkout, and before thank you page.

 
 Issue number two: I tried to deploy this extension.
 And I see this:
 
 
![image](https://user-images.githubusercontent.com/10574421/179509355-849a7a36-9f47-4e87-89d6-39a83a412bbb.png)

 

### Actual behavior

Errors in the console.
hieroglyphs

### Reproduction steps

1. Install cli v3
2. create a Shopify react node app
3. add a post purchase ui extension
4. use chrome extension/use `npm deploy`

### Operating System

Windows 10 x64

### Shopify CLI version (check your project's `package.json` if you're not sure)

3

**Comment by SerhiDi** [comment]
Hello, @shauns. Thanks for your reply.
As I wrote above, I am using a new project.
In a new project, `package.json` uses `@shopify/cli": "3.2.0` as dependency
I can update to `3.3.2`, but I see the same errors.

**Comment by SerhiDi** [comment]
I'm using Windows 10, as the main OS.
For NPM command - Windows PowerShell or ConEmu terminal emulator.

**Comment by pepicrft** [comment]
@SerhiDi what's your processor's architecture? You can obtain it by running:

```bash
node -e "console.log(os.arch())"
```

**Comment by SerhiDi** [comment]
x64

**Comment by pepicrft** [comment]
Thanks @SerhiDi. It seems an internal binary that we use is not compatible with your shell or architecture but I can't figure out why. Could you try pulling the Windows binaries from this [GitHub release](https://github.com/Shopify/shopify-cli-extensions/releases/tag/v0.20.3) (on the assets) section, unzip them, and try to run it from your Powershell terminal? I'll continue investigating on my end in the meantime.

**Comment by SerhiDi** [comment]
![image](https://user-images.githubusercontent.com/10574421/180458488-12fca263-f859-4a95-8dcb-09f59c38b744.png)

**Comment by SerhiDi** [comment]
`C://Users/.../AppData/Local/shopify-cli-nodejs/Cache/vendor/binaries/extensions/v0.20.2-windows-amd64.exe`

```
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
main.main()
        /home/runner/work/shopify-cli-extensions/shopify-cli-extensions/main.go:29 +0x20f

**Comment by pepicrft** [comment]
Do you get that when you run the Shopify CLI or when you run the binary directly?

**Comment by SerhiDi** [comment]
This error when I run the binary file.
If I tried to delete `v0.20.2-windows-amd64.exe` and run the command `npm run deploy` inside the Shopify project.
The binary file is being restored, and I see the error as in first message.

**Comment by pepicrft** [comment]
Thanks 🙏🏼. I have the issue narrowed down. The uncompressing of the binary that the CLI does leads to a corrupted binary. Until we can provide a fix, you can replace the binary at this path:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/663605/180470727-0e6e5bff-0225-402f-88c2-c908fb0e005f.png">
With the one that you manually downloaded and uncompressed. Make sure it has the path is the same. After that, running `npm run deploy` should work.

**Comment by SerhiDi** [comment]
These files `v0.20.2-windows-amd64` and `shopify-extensions-windows-amd64` are the same size.

I download again `shopify-extensions-windows-amd64.exe`, move to `...binaries\extensions`, and rename it to `v0.20.2-windows-amd64`. Nothing changed, error after `npm run deploy`.

**Comment by pepicrft** [comment]
Thanks for sharing the context @SerhiDi. We are looking into it and we'll provide you with a solution as soon as possible.

**Comment by SerhiDi** [comment]
![image](https://user-images.githubusercontent.com/10574421/180989199-be8ac819-36a1-4b12-8d56-5f6f7f2722ce.png)

**Comment by pepicrft** [comment]
Would you mind trying it with the most recent version of Node, 18.6.0? You can use a tool like [nvm](https://github.com/nvm-sh/nvm) to manage different Node versions if you are not doing it already.

**Comment by SerhiDi** [comment]
So, there are problems with folder names in the library.
Old folder name: `Shopify Apps/{project name}`. Please check this naming - `Shopify Apps`. I'm confusing, why is this name not working for the `Post-purchase UI extension`.

My project was moved to another folder but that didn't help.

Currently app on the disk `W` and extension binary trying to create a folder with the wrong command.

![image](https://user-images.githubusercontent.com/10574421/181308240-706c080f-9b06-403c-8239-ebd1c14631a8.png)

**Comment by SerhiDi** [comment]
Also, the app works but I don't see the extension after checkout.

![image](https://user-images.githubusercontent.com/10574421/181309398-0140409a-1862-4d98-bd52-34d34b03c818.png)

**Comment by dmhenry** [comment]
@SerhiDi Here are the steps I'm using to create the app + extension and then serve (dev) them both. The screenshots indicate how I responded to prompts. The only times this has not worked was when I messed up either step 5 or 6, but when done correctly, the Post-Purchase Extension consistently renders for me. Would you please try this and let us know if you still have an issue? Thanks for your patience.

1. Create an app:

   `Powershell> ` `npm init @shopify/app@latest`

    <img width="904" alt="Screen Shot 2022-08-01 at 1 29 54 PM" src="https://user-images.githubusercontent.com/4490738/182207924-6f957d72-7caf-41a8-adad-ef84d8023398.png">

2. Scaffold an extension:

    `Powershell> ` `cd flat-block-app-3784`
    `Powershell> ` `npm run scaffold extension`

    <img width="904" alt="Screen Shot 2022-08-01 at 1 32 38 PM" src="https://user-images.githubusercontent.com/4490738/182208376-8182083c-421e-4067-8695-a025d9da328b.png">

3. Serve the app + extension:

    `Powershell> ` `npm run dev`

    <img width="904" alt="Screen Shot 2022-08-01 at 1 41 01 PM" src="https://user-images.githubusercontent.com/4490738/182211938-ae1304e4-f70c-4619-aac7-390876d021ef.png"> 

4. Copy/paste the _Install the App_ (from the image above) into your browser, clicking the _Install app_ button:

    <img width="904" alt="Screen Shot 2022-08-01 at 1 45 25 PM" src="https://user-images.githubusercontent.com/4490738/182212606-09c4f018-323a-440c-91d6-443fa7e7891a.png"> 

5. Copy/paste the _Configure Chrome Extension_ (from the image above) into the Chrome extension, clicking _Save_:

    <img width="552" alt="Screen Shot 2022-08-01 at 1 48 20 PM" src="https://user-images.githubusercontent.com/4490738/182213068-113057cb-f896-40e7-9527-94afd633c602.png">

 6. Navigate to your store in a normal Chrome browser tab, adding an item to your cart and checking out normally:
 
<img width="513" alt="Screen Shot 2022-08-01 at 1 43 57 PM" src="https://user-images.githubusercontent.com/4490738/182213399-926a6f0c-a721-4f60-bda6-310485040e3b.png">

7. After checkout, observe the Post-Purchase Extension render:

<img width="751" alt="Screen Shot 2022-08-01 at 1 49 51 PM" src="https://user-images.githubusercontent.com/4490738/182213465-0d4f7eb3-7e1a-468e-a62c-8e90d0d20edd.png">

**Comment by SerhiDi** [comment]
@dmhenry, hello. Thanks for your reply.

Always followed these steps before.

As I see in today's updates `extensionsBinary` changed from `v0.20.2` to `v0.20.5`.
And yes, with this binary I can see `Post-purchase extension`.

**Comment by SerhiDi** [comment]
![image](https://user-images.githubusercontent.com/10574421/182257522-ddab1a10-9631-44ed-b14c-e2872ac3de6a.png)
