### ISSUE TITLE
[Bug]: `shopify app dev` creates `package-lock.json` when using pnpm

### ISSUE THREAD

**Issue by tobiasdalhof** [Shopify/cli#1659]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Do not create `package-lock.json`

### Actual behavior

It creates `package-lock.json`

### Reproduction steps

Run `package.json` script that uses `shopify app dev` command with pnpm, e.g. `pnpm dev`

### Operating System

Debian GNU/Linux 11 (bullseye) WSL2

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.8.1

**Comment by Arkham** [comment]
hi @tobiasdalhof, I followed this steps and could not reproduce
- `pnpm create @shopify/app --template=node`
- `cd newly-created-app`
- `pnpm dev`

these are the contents of my app:
```
$ ls -l
total 152
-rw-r--r--   1 arkham staff    206 Mar 24 12:21 Dockerfile
-rw-r--r--   1 arkham staff  10597 Mar 24 12:21 README.md
-rw-r--r--   1 arkham staff   4163 Mar 24 12:21 SECURITY.md
drwxr-xr-x 373 arkham staff  11936 Mar 24 12:22 node_modules
-rw-r--r--   1 arkham staff    424 Mar 24 12:21 package.json
-rw-r--r--   1 arkham staff 118953 Mar 24 12:22 pnpm-lock.yaml
-rw-r--r--   1 arkham staff     83 Mar 24 12:21 shopify.app.toml
drwxr-xr-x  12 arkham staff    384 Mar 24 12:22 web
```

**Comment by Arkham** [comment]
I see, I'm afraid this is caused by the pnpm workspace creating a single `pnpm-lock.yaml` at the top level of the monorepo. The CLI checks for presence of `pnpm-lock.yaml` or `yarn.lock` to decide which package manager to use, but it does this only inside the app folder. We definitely want to improve our support for monorepos, so thanks for reporting this, it will help us to prioritize adding support for them.

**Comment by vrazdalovschi** [comment]
Hi @Arkham. Do you have any recommendations on developing Shopify application with extensions in a pnpm monorepo? For example, having one `shopify-X-app` in the apps folder or splitting each backend/frontend/extension in different `apps/shopixy-X-app-backend` folders? Or would it be better to have only one `package.json` file inside `shopify-X-app` and all backend/front/extension reuse that?
