### ISSUE TITLE
[Feature]: Improve DX by removing Ruby dependency

### ISSUE THREAD

**Issue by tobiasdalhof** [Shopify/cli#1660]
### What area(s) will this request affect?

Other

### What type of change do you want to see?

New feature

### Overview

The current Shopify CLI installation process requires the installation of Ruby, which can be difficult and error-prone for many developers. To improve the developer experience (DX), I suggest removing the Ruby dependency and finding an alternative solution that is easier to install and maintain. This will reduce the potential for errors and make the installation process more accessible to a wider range of developers.

### Motivation

It took me a considerable amount of time to install Ruby, and the experience was frustrating and error-prone.

**Comment by Arkham** [comment]
hi @tobiasdalhof it's in our radar, but there is a considerable amount of Ruby code to be ported to TypeScript, so can't commit to a date yet.

**Comment by tobiasdalhof** [comment]
@Arkham I understand that there is a considerable amount of Ruby code that needs to be ported to TypeScript, and I appreciate the effort that goes into this process. However, as a user, I believe that it would be more convenient and accessible to have a single executable instead of requiring users to install both Ruby and Node.js. While I understand that this may require additional effort, I believe that it would greatly improve the developer experience and reduce the potential for errors during installation. Thank you for considering this suggestion.

**Comment by Arkham** [comment]
I 100% agree :)
