### ISSUE TITLE
[Bug]: shopify theme dev suddenly stopped working

### ISSUE THREAD

**Issue by brianecook** [Shopify/cli#1664]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

I run `shopify theme dev --store store-slug` and a local development server is created for me to make changes on my machine.

### Actual behavior

Error is thrown: Cannot read properties of undefined (reading 'toString'). When I run the command with the --verbose flag, this is the last message before the error is thrown:

2023-03-24T22:55:52.557Z: Sending Identity Introspection request to URL: undefined

I'm assuming there should be a url in place of undefined.

### Verbose output

```shell
2023-03-24T22:55:52.511Z: Running command theme dev
  shopify:theme:dev init version: @oclif/core@2.1.4 argv: [ '--store', 'store-slug, '--verbose' ] +0ms
2023-03-24T22:55:52.552Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-03-24T22:55:52.552Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store store-slug.myshopify.com:
[]

2023-03-24T22:55:52.554Z: Getting session store...
2023-03-24T22:55:52.556Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "oakandeden.myshopify.com"
  }
}

2023-03-24T22:55:52.557Z: Sending Identity Introspection request to URL: undefined
╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                          │
│  Cannot read properties of undefined (reading 'toString')                                                                                │
│                                                                                                                                          │
│  To investigate the issue, examine this stack trace:                                                                                     │
│    at shopifyFetch (../../../../usr/local/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-k  │
│    it/src/public/node/http.ts:69)                                                                                                        │
│      outputDebug(outputContent`Sending ${options.method ?? 'GET'} request to URL ${url.toString()}                                       │
│    at (usr/local/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/private/node/sess  │
│    ion/identity-token-validation.js:16)                                                                                                  │
│    at async withIntrospectionURL (../../../../usr/local/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/  │
│    @shopify/cli-kit/src/private/node/session/identity-token-validation.ts:49)                                                            │
│      let result: Result<T, AbortError> = await fn(introspectionURL)                                                                      │
│    at async validateSession (../../../../usr/local/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shop  │
│    ify/cli-kit/src/private/node/session/validate.ts:37)                                                                                  │
│      const identityIsValid = await validateIdentityToken(session.identity.accessToken)                                                   │
│    at async ensureAuthenticated (../../../../usr/local/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modules/@  │
│    shopify/cli-kit/src/private/node/session.ts:113)                                                                                      │
│      const validationResult = await validateSession(scopes, applications, fqdnSession)                                                   │
│    at async ensureAuthenticatedAdmin (../../../../usr/local/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/node_modu  │
│    les/@shopify/cli-kit/src/public/node/session.ts:82)                                                                                   │
│      const tokens = await ensureAuthenticated({adminApi: {scopes, storeFqdn: store}}, process.env, forceRefresh)                         │
│    at run (../../../../usr/local/Cellar/shopify-cli/3.44.1/libexec/lib/node_modules/@shopify/theme/src/cli/commands/theme/dev.ts:103)    │
│      const adminSession = await ensureAuthenticatedThemes(store, flags.password, [], true)                                               │
│                                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

2023-03-24T22:55:52.629Z: Unable to log analytics event - no information on executed command
2023-03-24T22:55:52.648Z: Failed to report usage analytics: Couldn't find a a package.json traversing directories from /Users/briancook/repos/oak_and_eden
2023-03-24T22:55:52.648Z: Completed command theme dev
2023-03-24T22:55:52.659Z: There was an error adding metadata to the Bugsnag report; Ignoring and carrying on Error: Couldn't find a a package.json traversing directories from /Users/briancook/repos/oak_and_eden
```

### Reproduction steps

1. Upgrade to latest Shopify CLI version (3.44.1)
2. Run `shopify auth logout`
3. Run `shopify theme dev --store store-slug`

### Operating System

Mac OS Ventura 13.2.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v15.14.0

**Comment by amcaplan** [comment]
Your instincts are correct! We have a caching mechanism that is apparently failing. Can you tell me more about how you first hit this issue? Maybe related to an upgrade? Or did it just suddenly stop working?

**Comment by brianecook** [comment]
@amcaplan Suddenly stopped working. I had upgraded last Thursday and was able to do most my day's work Friday, but it stopped working some time mid-afternoon PST Friday.

**Comment by gonzaloriestra** [comment]
Have any of you checked the value of that `identity-introspection-url-accounts.shopify.com` value before deleting it? It would be useful for us to fix the issue.

**Comment by brianecook** [comment]
@gonzaloriestra Unfortunately, I don't recall exactly what it was before I deleted it, but it was a ten digit number of some kind. Maybe an ID or a timestamp?

**Comment by gonzaloriestra** [comment]
It will be fixed in the next release (next week). As a workaround, you can remove the config.json in this folder:
- macOS: `~/Library/Preferences/shopify-cli-kit-nodejs`
- Windows: `%APPDATA%\shopify-cli-kit-nodejs\Config (for example, C:\Users\USERNAME\AppData\Roaming\shopify-cli-kit-nodejs\Config)`
- Linux: `~/.config/shopify-cli-kit-nodejs or $XDG_CONFIG_HOME/shopify-cli-kit-nodejs`

**Comment by NathKaden** [comment]
Hello, I have almost the same problem but even with deleting the file on C:\Users\%USERNAME%\AppData\Roaming\shopify-cli-kit-nodejs\Config
After delete the file config.json and login on browser sometimes the output says "✔ Logged in." but nothing happends or I have this error : 
╭─ error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                    │
│  Cannot read properties of undefined (reading 'toString')                                                                          │
│                                                                                                                                    │
│  To investigate the issue, examine this stack trace:                                                                               │
│    at create (../../AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/src/public/node/themes/theme-ma  │
│    nager.ts:48)                                                                                                                    │
│      this.setTheme(theme.id.toString())                                                                                            │
│    at processTicksAndRejections (node:internal/process/task_queues:95)                                                             │
│    at findOrCreate (../../AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/src/public/node/themes/th  │
│    eme-manager.ts:19)                                                                                                              │
│      theme = await this.create()                                                                                                   │
│    at run (../../AppData/Roaming/npm/node_modules/@shopify/theme/src/cli/commands/theme/dev.ts:127)                                │
│      const theme = await new DevelopmentThemeManager(adminSession).findOrCreate()                                                  │
│    at async runCLI (../../AppData/Roaming/npm/node_modules/@shopify/cli/node_modules/@shopify/cli-kit/src/public/node/cli.ts:88)   │
│      await run(undefined, options.moduleURL)                                                                                       │
│    at async runShopifyCLI (../../AppData/Roaming/npm/node_modules/@shopify/cli/src/index.ts:42)                                    │
│      await runCLI({                                                                                                                │
│                                                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
 TypeError: Cannot read properties of undefined (reading 'toString')

Someone found a fix?

**Comment by annacaosi** [comment]
i have a similar error. I want to start a dev server to create a theme. After running shopify theme dev --store {store-name} i am logged in but cant access any further information eg. viewing theme and the urls. Thats the error

To run this command, log in to Shopify.
👉 Press any key to open the login page on your browser
✔ Logged in.
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Cannot read properties of undefined (reading 'toString')                    │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at create (opt/homebrew/Cellar/shopify-cli/3.59.1/libexec/lib/node_modul  │
│    es/@shopify/cli/dist/index.js:195941)                                     │
│    at processTicksAndRejections (node:internal/process/task_queues:95)       │
│    at findOrCreate (opt/homebrew/Cellar/shopify-cli/3.59.1/libexec/lib/node  │
│    _modules/@shopify/cli/dist/index.js:195914)                               │
│    at run (opt/homebrew/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/  │
│    @shopify/cli/dist/index.js:204557)                                        │
│    at _run (opt/homebrew/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules  │
│    /@shopify/cli/dist/chunk-3MMF34G4.js:212317)                              │
│    at runCommand (opt/homebrew/Cellar/shopify-cli/3.59.1/libexec/lib/node_m  │
│    odules/@shopify/cli/dist/chunk-3MMF34G4.js:210764)                        │
│    at run (opt/homebrew/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/  │
│    @shopify/cli/dist/chunk-3MMF34G4.js:212426)                               │
│    at async runCLI (opt/homebrew/Cellar/shopify-cli/3.59.1/libexec/lib/node  │
│    _modules/@shopify/cli/dist/index.js:194855)                               │
│    at async runShopifyCLI (opt/homebrew/Cellar/shopify-cli/3.59.1/libexec/l  │
│    ib/node_modules/@shopify/cli/dist/index.js:207961)                        │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

    TypeError: Cannot read properties of undefined (reading 'toString')

I tried logging out and deleting the cachign file but nothings changed. Please help !

**Comment by gonzaloriestra** [comment]
@annacaosi that looks like a different issue, would you mind creating a new one? And include the output with `--verbose`, please.

**Comment by AdinaSchustal** [comment]
@annacaosi I had this issue and found that store name was spelled wrond. Double check you are using the correct store name. It should match the one in the admin URL - https://admin.shopify.com/store/**store-name**/...
