### ISSUE TITLE
[bug]: dont use random port in dev mode

### ISSUE THREAD

**Issue by schapicool** [Shopify/cli#1665]
### What area(s) will this request affect?

App

### What type of change do you want to see?

New feature

### Overview

I meet some problems to develop Shopify app with my colleague at the same time. If I run the Shopify app dev which overwrites the URLs whitelist and app URL and  having to collide with  coding togetther 

So that I find the solution about this , If we use the localhost and the same port we can develop at the same and no collision in Shopify app-bright mode

But the problems is when use shopify app dev to dev app which use a random port that make me confuse why we can Specify port on Shopify app dev

### Motivation

Hoping support Specify port on Shopify app dev,  no random port

**Comment by amcaplan** [comment]
You may find [this](https://github.com/Shopify/cli/pull/1614) valuable.

Should be available in the next prerelease and minor release when they each come out.
