### ISSUE TITLE
[Bug]: It does not initiate the request through the proxy

### ISSUE THREAD

**Issue by Jarvie127** [Shopify/cli#1666]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme, App

### Expected behavior

The request is made through the proxy.

### Actual behavior

I am in China and I need to develop Shopify through a proxy.
When developing a theme locally execute `shopify theme dev` 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/27297429/227825355-d391fcf0-2b88-453c-944a-ad796d161571.png">

On MacOS, I set proxy for terminal with export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
Then I executed shopify theme dev It still doesn't make requests through the proxy.

What causes this? Does anyone know? Thanks in advance!
I am using the latest version. Everything is up to date on MacOS

### Verbose output

```shell
2023-03-27T02:25:12.641Z: Running command theme dev
  shopify:theme:dev init version: @oclif/core@2.1.4 argv: [ '--verbose' ] +0ms
2023-03-27T02:25:12.652Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-03-27T02:25:12.652Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store anony.myshopify.com:
[]

2023-03-27T02:25:12.652Z: Getting session store...
2023-03-27T02:25:12.654Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "anony.myshopify.com"
  }
}

2023-03-27T02:25:12.654Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-03-27T02:25:12.654Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.44.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  request to https://accounts.shopify.com/oauth/introspection failed,         │
│  reason: connect ETIMEDOUT 185.146.173.20:443                                │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

2023-03-27T02:26:27.731Z: Unable to log analytics event - no information on executed command
```

### Reproduction steps

1.Set proxy port in terminal
2.Execute the command `shopify theme dev`

### Operating System

MacOS Ventura, Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

zsh, cmd

### Node version (run `node -v` if you're not sure)

v19.8.1

**Comment by Jarvie127** [comment]
Currently I can only develop by installing proxifier, but that wasn't the case a week ago. I thought it might be my problem, I switched to windows11 fresh install shopify-cli and it still does the same.

**Comment by MyBaymax** [comment]
@ma-zhao-yang Did you solve this problem? If so, can you share the method?

**Comment by huanhuanhome** [comment]
我也遇到了这个问题，停下来了，等官方搞好

**Comment by MyBaymax** [comment]
Shopify Cli 要比 themekit 好用得多，现在用回 themekit，好不方便。可以使用了，大家留言提醒一下，谢谢

**Comment by Jarvie127** [comment]
Still waiting...

**Comment by zhouru1bin** [comment]
same problem Still waiting...

**Comment by Jarvie127** [comment]
> How to solve the problem of timeout auth through proxifier, can you share the configuration
@zhouru1bin I use it with Clash and there is no configuration with Authentication enabled. This should only be configured relative to the local machine. Usually there is no need to set it. Below is my configuration. 
For example, my ClashX hybrid proxy port is 7890
<img width="466" alt="image" src="https://user-images.githubusercontent.com/27297429/229670458-af330196-2265-4436-aa60-b7c34cd87f17.png">

**Comment by Jarvie127** [comment]
Any updates?

**Comment by Jarvie127** [comment]
Hello everyone, great! Now it works fine again. But don't know exactly what caused it. Or is there any update? 
If your shopify-cli terminal proxy still doesn't work, try updating. Or keep using "proxifier". Although I haven't updated any, but you can try any way. 
I'm closing this question for now.

**Comment by yeziyue** [comment]
hello, how to use Proxifier? the same qustion,
