### ISSUE TITLE
[Bug]: Authentication Context Botched

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#1683]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

This CLI should maintain working context in terms of authentication over time. Leaving my computer alone for a half-hour break should not break the CLI session.

### Actual behavior

If you stop working for any amount of time, eg: taking a break, the CLI gets fubarred, forcing you to restart your session.

### Verbose output

```shell
14:18:28 Pushed » 'my-extension' to a draft
- blocks/puddle-of-poo.liquid
Please provide this information with your report:
www-authenticate: Bearer realm="171e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6",error="invalid_token",error_description="The access token provided is expired, revoked, malformed, or invalid for other reasons."
x-request-id: c0d68972-f830-4bb4-bc1a-e57d6695f546
```

### Reproduction steps

1.
2.
3.

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19

### What language and version are you using in your application?

Ruby 3.2.1

**Comment by matteodepalo** [comment]
@Shopify/theme-developer-tools

**Comment by resistorsoftware** [comment]
This is actually one of the worst CLI problems I have run into, and ignoring it and or not addressing it just screams that it is a real issue, and real tough and that perhaps the authentication scheme selected for the CLI is permanently crippled. Perhaps. Perhaps someone will fix this issue though. Not STALE. Go away dumb bot.

**Comment by karreiro** [comment]
Thank you for reporting this, @resistorsoftware.

The @shopify/theme-code-tools team is aware of this problem and it's on our roadmap. As soon as we have an update for it, we will leave a comment here.

Thanks again for bringing this up!

**Comment by resistorsoftware** [comment]
This issue is not stale, it simply has not been fixed by anyone. Please Mr. Bot, do not confuse issues not solved or resolved with stale. I just suffered from this exact bug twice today! It is an everyday occurring thing.
