### ISSUE TITLE
[Bug]: Command `login` not found. Did you mean `plugins`?

### ISSUE THREAD

**Issue by ekwoka** [Shopify/cli#1697]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Able to login

### Actual behavior

Not able to log in

### Verbose output

```shell
Command `login` not found. Did you mean `plugins`?



auth logout               Logout from Shopify.
 commands                  list all the commands
 config autocorrect off    Disable autocorrect.
 config autocorrect on     Enable autocorrect.
 config autocorrect status Check autocorrect current status.
 help                      Display help for shopify.
 kitchen-sink async        View the UI kit components that process async tasks
 kitchen-sink prompts      View the UI kit components prompts
 kitchen-sink static       View the UI kit components that display static output
 plugins                   List installed plugins.
 plugins add               Installs a plugin into the CLI.
 plugins inspect           Displays installation properties of a plugin.
 plugins install           Installs a plugin into the CLI.
 plugins link              Links a plugin into the CLI for development.
 plugins remove            Removes a plugin from the CLI.
 plugins uninstall         Removes a plugin from the CLI.
 plugins unlink            Removes a plugin from the CLI.
 plugins update            Update installed plugins.
 theme check               Validate the theme.
 theme delete              Delete remote themes from the connected store. This command can't be undone.
 theme dev                 Uploads the current theme as a development theme to the connected store, th…
 theme info                Print basic information about your theme environment.
 theme init                Clones a Git repository to use as a starting point for building a new theme.
 theme language-server     Start a Language Server Protocol server.
 theme list                Lists your remote themes.
 theme open                Opens the preview of your remote theme.
 theme package             Package your theme into a .zip file, ready to upload to the Online Store.
 theme publish             Set a remote theme as the live theme.
 theme pull                Download your remote theme files locally.
 theme push                Uploads your local theme files to the connected store, overwriting the remo…
 theme share               Creates a shareable, unpublished, and new theme on your theme library with …
 upgrade                   Upgrade the Shopify CLI.
 version                   Shopify CLI version.
```

### Reproduction steps

1.Run `shopify login`

### Operating System

Mac OS Latest

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.44.1 Latest

### Shell

zsh

### Node version (run `node -v` if you're not sure)

Latest

### What language and version are you using in your application?

JS

**Comment by Arkham** [comment]
The `login` command doesn't exist anymore. You can run `shopify theme dev --store YOUR_STORE` to login into a store. Check this page for more docs: https://shopify.dev/docs/themes/tools/cli#connecting-to-a-store

**Comment by ekwoka** [comment]
Okay. Well, when `theme dev` kicks you out it still says to use `shopify login` to log back in.

And when running `theme dev` after it logs you out it does nothing.

So I guess this could be changed to refer to that? The app says you use `shopify login` but `shopify login` doesn't exist. Strange.

**Comment by ekwoka** [comment]
Yes, I did not mention it since that didn't seem like the error at hand. Thanks.

Separately, idk if shopify is having issues, but doing `theme dev --store STORE` just hangs for a few minutes for me...so that didn't help me solve it myself. Hopefully that is just a server thing

**Comment by Arkham** [comment]
Yeah, we're experiencing some issues with our authentication services, hopefully it should be resolved soon.
