### ISSUE TITLE
[Bug]: Function input change not applied on function deployment

### ISSUE THREAD

**Issue by h4gen** [Shopify/cli#1758]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Changing the input schema should lead to a new input provided to the function on subsequent runs. That is not the case.

### Actual behavior

The schema change has no effect. It stays the old schema. The function needs to be deleted in order to realize an input change.

### Verbose output

```shell
Too big to post here as the verbose print out the whole binary of the function.
```

### Reproduction steps

1. Change function input schema
2. Deploy via CLI
3. Run function and see that input has not changed

### Operating System

MacOS 13.12.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.43.0 darwin-x64 node-v18.14.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.14.1

### What language and version are you using in your application?

Rust/GQL

**Comment by Arkham** [comment]
hi @h4gen can you reproduce using `3.45.0` as well? If yes, could you also write down more specific reproduction steps? for example, the before and after of the schema, the contents of your `shopify.function.extension.toml`, a small repository would be great.
