### ISSUE TITLE
[Bug]: create app fails with "Unexpected system error"

### ISSUE THREAD

**Issue by agriffis** [Shopify/cli#177]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Create the app or generate a useful error message

### Actual behavior

```
✸ shopify app create node
? App name
> Disc Hovery
? What type of app are you building? (You chose: Public: An app built for a wide merchant audience.)
Partner organization Scampersand (2558153)
Using development store so-many-discs.myshopify.com
✓ node 16.15.0
✓ npm 8.14.0
┏━━ Cloning https://github.com/Shopify/shopify-app-template-node.git into disc_hovery…
┃                                                                           100%
┗━━ ✓ Cloned into disc_hovery ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (1.1s) ━━
┏━━ Installing dependencies with yarn… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✓ Dependencies installed
┗━━ Dependencies installed ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (5.92s) ━━
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗  Unexpected system error
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Reproduction steps

See "actual behavior" above

### Operating System

Fedora 36

### Shopify CLI version (check your project's `package.json` if you're not sure)

2.20.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

v16.15.0

**Comment by richardscarrott** [comment]
I'm suddenly getting this as of a few hours ago when running `yarn dev` (I was able to create the app this morning just fine).

<img width="754" alt="Screenshot 2022-07-20 at 17 24 07" src="https://user-images.githubusercontent.com/539309/180033893-8d8824ba-8c04-4bcd-a789-933b027adb90.png">

`yarn dev` was working ok this morning; hard to know how to debug such minimal information logged.

**Comment by agriffis** [comment]
Just started working!
