### ISSUE TITLE
[Feature]: Display app name within deployConfirmationPrompt summary

### ISSUE THREAD

**Issue by gil--** [Shopify/cli#1772]
### What area(s) will this request affect?

Extension, Function, Deployment

### What type of change do you want to see?

New feature

### Overview

I always get concerned when deploying as there's no visual verification for which app is being deployed to. Most concerning with functions where there's no versioning and deploying any change to the wrong app immediately goes live.

Can we please add the active app name within [deployConfirmationPrompt](https://github.com/Shopify/cli/blob/29be16fb14a2e3887a066705fc0dc376c9137544/packages/app/src/cli/services/context/prompts.ts#L38)? This would affect at a minimum the [functions](https://github.com/Shopify/cli/blob/29be16fb14a2e3887a066705fc0dc376c9137544/packages/app/src/cli/services/context/identifiers-functions.ts#L37) and [extensions](https://github.com/Shopify/cli/blob/29be16fb14a2e3887a066705fc0dc376c9137544/packages/app/src/cli/services/context/identifiers-extensions.ts#L55) deployment summary.

### Motivation

Reduce heart rate during deployment

**Comment by Arkham** [comment]
hey @gil-- thanks for reporting this, I agree. I was thinking that it would be nice to include the organization name as well. Is there anything else you can think of that would be useful?

**Comment by gil--** [comment]
@Arkham Honestly just the app name and org is sufficient for me.
