### ISSUE TITLE
Introduce the `--open` flag in the `shopify theme dev` command

### ISSUE THREAD

**Issue by nikitaourazbaev** [Shopify/cli#1777]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

`shopify theme dev` should not open a browser automatically

### Actual behavior

`shopify theme dev` opens a browser automatically and I have not found a flag to disable this newly introduced behaviour.

### Verbose output

```shell
N/A
```

### Reproduction steps

1. Run `shopify theme dev` in a theme directory

### Operating System

macOS Monterey 12.6.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.0

### Shell

Fish

### Node version (run `node -v` if you're not sure)

v18.2 (but CLI uses its own node)

### What language and version are you using in your application?

N/A, this is a theme project

### Acceptance Criteria
- [ ] `--no-open` flag exists for the `shopify theme dev` command
- [ ] shopify.dev docs have been updated accordingly to mention this flag.

**Comment by gonzaloriestra** [comment]
cc @Shopify/theme-developer-tools

**Comment by tomorrowagency-preston** [comment]
I would also like to have a flag to prevent the automatic opening of a browser window. I use a private browser window to view the UI that I'm working on, so it's a little annoying to have to close the new browser window every time.

**Comment by nikitaourazbaev** [comment]
> I was wondering if it would be okay to rename this issue to "**Introduce `--no-open` flag in the `shopify theme dev` command**"? 

Fine by me. Thank you!

**Comment by notrealdev** [comment]
+1

**Comment by nikitaourazbaev** [comment]
I would argue that the argument should be `--open`, and that the default behaviour should be that CLI does not open a new browser window as Shopify CLI has never opened a new browser window before (other than for auth).

**Comment by tomorrowagency-preston** [comment]
yeah, I like that ^ idea better. +1 for defaulting to not opening a browser and having a switch to open when wanted.

**Comment by vfonic** [comment]
I second what @nikitaourazbaev wrote. It's also better to have affirmative booleans `--open` vs `--no-open` and then in the code you'd have `if (!open)` vs `if (!noOpen) // ???`.

> This is quite a major and unexpected change to the default behaviour of a foundational command.

This really should have been reverted when it was introduced. It's really frustrating. I'm actually trying to downgrade CLI to v3.44.x today due to this bug.
