### ISSUE TITLE
[Bug]: <Missing package.json error>

### ISSUE THREAD

**Issue by akashdeep-logistiq** [Shopify/cli#1779]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The Shopify 2.0 app should have migrated to 3.0 without any errors or bugs.

### Actual behavior

While we were trying to migrate our shopify app from 2.0 to 3.0, there was this error - 

Test Title: ── external error ─────────────────────────────────────────────────────────────────────────────────────────

Error coming from npm run dev

Command failed with exit code 1: npm run dev
╭─ error ──────────────────────────────────────────────────────────────────────╮
│ │
│ The directory /Users/app/web/frontend │
│ doesn't have a package.json. │
│ │
╰──────────────────────────────────────────────────────────────────────────────╯

dev
shopify app dev

### Verbose output

```shell
The directory /Users/app/web/frontend │ frontend │ │  doesn't have a package.json
```

### Reproduction steps

1. Have a Shopify 2.0 app
2. Try to migrate it to 3.0 using shopify cli 3.0 following the doc - https://shopify.dev/docs/apps/tools/cli/migrate
3. Get the error

### Operating System

MacOS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0

### Shell

terminal

### Node version (run `node -v` if you're not sure)

v19.8.1

### What language and version are you using in your application?

Node

**Comment by alvaro-shopify** [comment]
Hi @akashdeep-logistiq!. Thanks for rising up this issue. In [this section](https://shopify.dev/docs/apps/tools/cli/migrate#step-5c-reorganize-your-dependencies) of the migration tutorial you can see that there are two alternatives to declare your dependencies and script in case you have a `node` frontend. 
* Use the package manager workspaces feature
* Move the dependencies and script to the root folder

It seems that you have chosen the second option, to the `dev` command declared in the `web/frontend/shopify.web.toml` should have access to the scripts and dependencies needed. 

To give you a further assistance, please, could you provide me with this:
* Run the `npm run dev` with the flag `--verbose` and paste the output log in this issue
* Run `npm run shopify version` and add in this issue the `CLI version` you are using.

Looking forward to hear from you soon.

**Comment by alvaro-shopify** [comment]
Hi @akashdeep-logistiq, thanks a lot for the feedback. I have taken a look at the output but I can't see the error you reported in the issue 

```
╭─ error ──────────────────────────────────────────────────────────────────────╮
│ │
│ The directory /Users/app/web/frontend │
│ doesn't have a package.json. │
│ │
╰──────────────────────────────────────────────────────────────────────────────╯
```

**Comment by mschristianjohansson** [comment]
If anyone else gets this error a fix is to just create an empty package.json file with contents `{}`
