### ISSUE TITLE
[Feature] `shopify theme push` on not found environment

### ISSUE THREAD

**Issue by msev** [Shopify/cli#1781]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

Hi,

First of all, thanks for the `shopify.theme.toml` feature.

It would be nice if when an environment is not found during a push (or pull, dev, ...), that it proposes the environments of the `shopify.theme.toml` file rather than the list of themes in the store.
Because for the moment, if you don't set the flag `--ignore` or if the `.shopifyignore` file is not present, there will be no indication of ignore in this case.

![test](https://user-images.githubusercontent.com/1529562/230636004-5443c30c-6627-4813-b16f-188aa346fce7.png)

### Motivation

To avoid files being deleted during a push

**Comment by gonzaloriestra** [comment]
Thanks a lot for the suggestion! It makes sense to me, we'll consider it internally. cc: @stephszeto
