### ISSUE TITLE
[Bug]: Theme dev stops randomly only to start again & overwrite all changes

### ISSUE THREAD

**Issue by bashrj** [Shopify/cli#1784]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

I expect ```shopify theme dev``` to keep serving files to the dev theme until I stop it.

### Actual behavior

![troubleshoot](https://user-images.githubusercontent.com/63104733/230728212-b3dd82f3-4e7b-4600-ae6b-cd4c70a55df1.png)

It's as if I pressed Ctrl^C, then re-ran ```shopify theme dev```, just without the actual command line for ```shopify theme dev``` preceding the tool's output.

This happens often and is extremely frustrating because it overwrites everything.

I usually deal with it by reverting file changes for files that existed at the moment of running ```shopify theme dev``` through the online code editor, but all newly created files are completely lost for good.

This issue never once happened with CLI 2.0

### Verbose output

```shell
//
```

### Reproduction steps

```shopify theme dev```

Make a bunch of changes, possibly manual changes to core elements like theme.liquid and settings_data.json

It's so random, I can't technically re-produce it as I can't recall a common file change that caused this several times in the past.

### Operating System

Arch Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0

### Shell

Bash

### Node version (run `node -v` if you're not sure)

v14.21.3

### What language and version are you using in your application?

ruby 3.1.0p0

**Comment by alvaro-shopify** [comment]
Hi, thanks for rising up this issue, I'll tag [theme-developer-tools](https://github.com/orgs/Shopify/teams/theme-developer-tools) so they take a look at this.

**Comment by bashrj** [comment]
> Hi, thanks for rising up this issue, I'll tag [theme-developer-tools](https://github.com/orgs/Shopify/teams/theme-developer-tools) so they take a look at this.

[theme-developer-tools](https://github.com/orgs/Shopify/teams/theme-developer-tools) is a broken link

Issue yet to be resolved
