### ISSUE TITLE
[Bug]: Unexpected system error 500

### ISSUE THREAD

**Issue by delyan-peev** [Shopify/cli#1797]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

I'm trying to deploy a theme app extension for the first time via mi CD pipeline. The command I'm using is `shopify app deploy -f` with both `SHOPIFY_CLI_PARTNERS_TOKEN` and `SHOPIFY_API_KEY` env variables provided. Unfortunately, instead of getting a deployed theme app extension, I get the error described below.

### Actual behavior

Receiving the error below:

```
─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│                                                                              │
│    The Partners GraphQL API responded unsuccessfully with the HTTP status    │
│  200 and errors:                                                             │
│                                                                              │
│    [                                                                         │
│    {                                                                         │
│      "message": "Unexpected system error",                                   │
│      "extensions": {                                                         │
│        "code": "500"                                                         │
│      }                                                                       │
│    }                                                                         │
│  ]                                                                           │
│                                                                              │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at makeRequest                                                            │
│    (@shopify/cli-kit/node_modules/graphql-request/src/index.ts:441)          │
│      throw new ClientError(                                                  │
│    at processTicksAndRejections (internal/process/task_queues.js:95)         │
│    at async debugLogResponseInfo                                             │
│    (@shopify/cli-kit/src/private/node/api.ts:25)                             │
│      response = await request                                                │
│    at async graphqlRequest                                                   │
│    (@shopify/cli-kit/src/public/node/api/graphql.ts:44)                      │
│      const response = await debugLogResponseInfo(                            │
│    at async createExtension                                                  │
│    (@shopify/app/src/cli/services/dev/create-extension.ts:38)                │
│      const result: ExtensionCreateSchema = await partnersRequest(query,      │
│      token, variables)                                                       │
│    at async createExtensions                                                 │
│    (@shopify/app/src/cli/services/context/identifiers-extensions.ts:89)      │
│      const registration = await createExtension(appId,                       │
│      extension.graphQLType, extension.configuration.name, token)             │
│    at async ensureExtensionsIds                                              │
│    (@shopify/app/src/cli/services/context/identifiers-extensions.ts:64)      │
│      const newIdentifiers = await createExtensions(extensionsToCreate,       │
│      options.appId)                                                          │
│    at async ensureDeploymentIdsPresence                                      │
│    (@shopify/app/src/cli/services/context/identifiers.ts:45)                 │
│      const extensions = await ensureExtensionsIds(options,                   │
│      remoteSpecifications.app.extensionRegistrations)                        │
│    at async ensureDeployContext                                              │
│    (@shopify/app/src/cli/services/context.ts:298)                            │
│      identifiers = await ensureDeploymentIdsPresence({                       │
│    at async deploy (@shopify/app/src/cli/services/deploy.ts:54)              │
│      let {app, identifiers, partnersApp, token, organization} = await        │
│      ensureDeployContext(options)                                            │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

### Verbose output

```shell
It's kind of hard to try with a verbose output, but I'll go the extra mile if necessary
```

### Reproduction steps

1. Create an app
2. Try to deploy a newly created theme app extension with the -f flag

### Operating System

Ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.0

**Comment by alvaro-shopify** [comment]
Hi @delyan-peev. Thanks for rising up this issue!. I guess that the `500` error is due to the fact you don't have deployed the extension the first time manually, which should be the[ first step](https://shopify.dev/docs/apps/tools/cli/ci-cd#step-1-generate-variables-for-deployment) before you integrate the deployment in you CI/CD

The problem in this case is that the partners token does not have permission to deploy new extensions in the app only to update the existing extensions. The `500` error in this case means that the token does not meet the required rights to deploy a new extension.

I'm sorry because that error message should be more clear and explain what it's really happening. We will create an issue to evaluate if it's possible to improve it.

Please, let me know if this work for you.

**Comment by alvaro-shopify** [comment]
Sorry for coming to you again. Maybe the problem could be that the id of the extension you set in your CI/CD does not match the one you deployed manually, if you have done it previously. Please, check this alternative too. Thanks

**Comment by delyan-peev** [comment]
Yeah, as I mentioned it's a first-time deployment, so I guess that is the root cause. I'll give it a try. It's just the 500 and the stacktrace that made me think it's probably not my fault, haha. Will get back to you about whether deploying it manually before trying it from the CD pipeline fixes it.

**Comment by ezmiller** [comment]
Any chance that the limitation described above requiring manual deployment of functions will be removed? For us, it's creating some awkwardness in our ci/cd workflow. It's hard to see why the limitation should exist, especially since a function won't become active on a store without being registered via some kind of customization record...
