### ISSUE TITLE
Unable to create location rule function

### ISSUE THREAD

**Issue by robhos74** [Shopify/cli#1799]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension, Function

### Expected behavior

Extension Generated without any issue

### Actual behavior

**When executing the following command:**

npm run shopify app generate extension -- --type order_routing_location_rule --name=location-rule

**The following  error is thrown:**
                                                                                                                                           │
│  Unknown extension type: order_routing_location_rule.                                                                                       │
│  The following extension types are supported: post_purchase_ui, checkout_ui, pos_ui, subscription_ui, web_pixel, theme_app_extension,       │
│  order_discounts, cart_checkout_validation, cart_transform, delivery_customization, payment_customization, product_discounts,               │
│  shipping_discounts, fulfillment_constraints   

### Verbose output

```shell
**When executing the following command:**

npm run shopify app generate extension -- --type order_routing_location_rule --name=location-rule

**The following  error is thrown:**
                                                                                                                                           │
│  Unknown extension type: order_routing_location_rule.                                                                                       │
│  The following extension types are supported: post_purchase_ui, checkout_ui, pos_ui, subscription_ui, web_pixel, theme_app_extension,       │
│  order_discounts, cart_checkout_validation, cart_transform, delivery_customization, payment_customization, product_discounts,               │
│  shipping_discounts, fulfillment_constraints
```

### Reproduction steps

package.json extract

"dependencies": {
    "@shopify/app": "^3.46.0-pre.0",
    "@shopify/checkout-ui-extensions-react": "^0.24.0",
    "@shopify/cli": "^3.46.0-pre.0",
    "graphql": "^16.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

^3.46.0-pre.0

### Node version (run `node -v` if you're not sure)

v18.12.1

### What language and version are you using in your application?

3.1.2

**Comment by alvaro-shopify** [comment]
@robinhosanee thanks for pointing me to that public documentation. Maybe it makes no sense to have to make that function type private if there is public documentation about it. I will check that with the team.
