### ISSUE TITLE
[shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: true}

### ISSUE THREAD

**Issue by abhinavpanse** [Shopify/cli#1800]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The expected behaviour is that in both the development and production environment, it should behave the same. But actual behaviour is a bit different. I have explained it below.

In the previous solution to https://github.com/Shopify/cli/issues/1480 , it was discussed that we should upgrade to, @shopify/shopify-api to v6. But as I can see in my package-lock.json it is already on v6.

### Actual behavior

When I'm running locally all the requests that are made from the frontend to the backend are working fine.

But when I deployed my Shopify app on DigitalOcean, then I'm getting a 403 error code in frontend and I'm getting -> [shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: true}
 this error is in the backend.
 
The behaviour is exactly similar to thus issue -> https://github.com/Shopify/shopify-api-js/issues/747

I have setup the shopify express app instance like following 
```
const shopify = shopifyApp({
  api: {
    apiVersion: LATEST_API_VERSION,
    restResources,
    billing: undefined, // or replace with billingConfig above to enable example billing
  },
  auth: {
    path: "/api/auth",
    callbackPath: "/api/auth/callback",
  },
  useOnlineTokens: true,
  webhooks: {
    path: "/api/webhooks",
  },
  // This should be replaced with your preferred storage strategy
  sessionStorage: new MemorySessionStorage(),
});

```
note that -> useOnlineTokens: true, 

___________
useAxiosInstance.js (I use this to get Axios instance and this instance to make API calls to the backend)

```
import React from "react";
import { useAppBridge } from "@shopify/app-bridge-react";
import { getSessionToken } from "@shopify/app-bridge-utils";
import axios from "axios";

const useAxiosInstance = () => {
  const app = useAppBridge();
  const axiosInstance = getAxiosInstance(app);
  return axiosInstance;
};

const getAxiosInstance = (app) => {
  const instance = axios.create();
  instance.interceptors.request.use(function (config) {
    return getSessionToken(app).then((token) => {
      config.headers["Authorization"] = `Bearer ${token}`;
      return config;
    });
  });

  return instance;
};

export default useAxiosInstance;

```
______________________
apart from this following is index.js similar to that what we are provided in nodejs Shopify app template.

```
app.use("/api/*", shopify.validateAuthenticatedSession());

app.use(express.json());

app.use(async (_req, res, next) => {
  const sessionName = await shopify.api.session.getCurrentId({
    isOnline: true,
    rawRequest: _req,
    rawResponse: res,
  });

  const session = await shopify.config.sessionStorage.loadSession(
    sessionName || ""
  );

  try {
    await installShop(_req, res, session);
  } catch (error) {}

  // @ts-ignore
  _req.session = session?.toObject();

  next();
});

```

### Verbose output

```shell
[embed] [2023-04-13 06:19:18] [shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: true}
[embed] [2023-04-13 06:19:18] [shopify-app/INFO] Running ensureInstalledOnShop
[embed] [2023-04-13 06:19:18] [shopify-app/INFO] App is installed and ready to load | {shop:<shop>}
[embed] [2023-04-13 06:19:18] [shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: true}
[embed] [2023-04-13 06:19:18] [shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: true}
[embed] [2023-04-13 06:19:21] [shopify-app/INFO] Running validateAuthenticatedSession
[embed] [2023-04-13 06:19:21] [shopify-app/INFO] Session was not valid. Redirecting to /api/auth?shop=<shop>| {shop:<shop>}
```

### Reproduction steps

1. Upload the app to github
2. Use the digital ocean app service to deploy.

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

 "@shopify/cli": "3.45.0"

### Node version (run `node -v` if you're not sure)

v18.15.0

### What language and version are you using in your application?

Node

**Comment by abhinavpanse** [comment]
@paulomarg 

I have attempted to use MongoDBSessionStorage and PostgreSQLSessionStorage, but the issue persists. 

The headers are being sent correctly with the request; however, when running locally, the sessions are being populated in the database but when running on production, the session data is not being populated or created in the database.

Do you see any reason for this? The db access IP is also whitelisted.

**Comment by wisniewski94** [comment]
Your best choice is to try to print a more detailed log using the `--verbose` flag or use a debugger to investigate what happens when data is saved into DB. It looks like an environment and permissions type of issue to me.

**Comment by changeyoucant** [comment]
![image](https://github.com/Shopify/cli/assets/51197525/17be2438-ebd5-431a-850f-a9ce294b8f13)
 I'm having the same problem with my webook's request too!!!

**Comment by Pooja-Parmar** [comment]
Did anyone get the solution, Kindly share it.
I am getting the same issue in my MERN project.

**Comment by savaliyanidhi** [comment]
Did anyone get the solution, Kindly share it.
I am getting the same issue in my MERN project.
