### ISSUE TITLE
[Feature]: Deploy Shopify CLI App to Linux/Nginx server

### ISSUE THREAD

**Issue by Mzn98** [Shopify/cli#1819]
### What area(s) will this request affect?

Deployment

### What type of change do you want to see?

Substantial change to existing feature

### Overview

I build a Shopify CLI App at latest version and Shopify has limited choice of deploy solution

### Motivation

Im trying to deploy my app to my existing Nginx server. Shopify deployment docs only cover for Heroku or Fly.io [https://shopify.dev/docs/apps/deployment/web]. However, it doesn't work at all

Has Shopify solved this problem? If this problem has solved, please give me a solution

**Comment by matteodepalo** [comment]
Hi @Mzn98, when you say that
>However, it doesn't work at all

Are you getting some errors when trying the steps outlined in the docs?

**Comment by Mzn98** [comment]
I solved my own problem. Thanks!

**Comment by Yatharthmakar** [comment]
how did you solve it?
