### ISSUE TITLE
[Bug]: Partner API Explorer is broken

### ISSUE THREAD

**Issue by arsnl** [Shopify/cli#1822]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

Firstly, I know this is not caused by the Shopify CLI, but your in-house Partners support agent (support@shopify.com, Olli S.) told me that this is the only place we can get support and report this kind of issue, just after telling me the place to get this kind of support is via the Community... 😅

So, I've already created a "ticket" in the community: https://community.shopify.com/c/shopify-apis-and-sdks/partner-api-explorer-is-broken/m-p/2023464#M89883

The bug is about the Partner GraphQL API. https://shopify.dev/docs/api/partner

The expected behavior is when a user follow the documentation to access the graph (https://shopify.dev/docs/api/partner) then go on the Shopify Partner API Explorer, the schema documentation should be available.

### Actual behavior

When a user go on the Shopify Partner API Explorer, the schema documentation is not available. The bug is present on every version of the API.

![Capture d’écran, le 2023-04-17 à 09 36 32](https://user-images.githubusercontent.com/763489/232500582-78732cbe-a68c-4457-811c-3224fefdccf1.png)

### Verbose output

The following message is displayed in the Docs panel.

```
Schema is invalid: Interface field Actor.name expects type String! but MerchantUser.name is type String.
```

The following message is displayed in the response panel.

```
{
  "errors": [
    {
      "message": "Interface field Actor.name expects type String! but MerchantUser.name is type String.",
      "stack": "GraphQLError: Interface field Actor.name expects type String! but MerchantUser.name is type String.\n    at t.reportError (https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_graphiql_esm_index_js-caches_app_node_modules_graphiql_graphiql_css-652dabd55d7f8cd2443a8db786ed05477cbd40b2c8c1d55d3d5cf9fbe206ee87.js:2:424573)\n    at w (https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_graphiql_esm_index_js-caches_app_node_modules_graphiql_graphiql_css-652dabd55d7f8cd2443a8db786ed05477cbd40b2c8c1d55d3d5cf9fbe206ee87.js:2:426616)\n    at E (https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_graphiql_esm_index_js-caches_app_node_modules_graphiql_graphiql_css-652dabd55d7f8cd2443a8db786ed05477cbd40b2c8c1d55d3d5cf9fbe206ee87.js:2:426184)\n    at https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_graphiql_esm_index_js-caches_app_node_modules_graphiql_graphiql_css-652dabd55d7f8cd2443a8db786ed05477cbd40b2c8c1d55d3d5cf9fbe206ee87.js:2:424073\n    at m (https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_graphiql_esm_index_js-caches_app_node_modules_graphiql_graphiql_css-652dabd55d7f8cd2443a8db786ed05477cbd40b2c8c1d55d3d5cf9fbe206ee87.js:2:424236)\n    at https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_graphiql_esm_index_js-caches_app_node_modules_graphiql_graphiql_css-652dabd55d7f8cd2443a8db786ed05477cbd40b2c8c1d55d3d5cf9fbe206ee87.js:2:288255\n    at Object.To [as useMemo] (https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_react-dom_index_js-caches_app_node_modules_react_index_js-f6116cdbe520ff77bf8552e66433e482efebd74601cd47a3d5ff541dac6bf665.js:2:65093)\n    at t.useMemo (https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_react-dom_index_js-caches_app_node_modules_react_index_js-f6116cdbe520ff77bf8552e66433e482efebd74601cd47a3d5ff541dac6bf665.js:2:125533)\n    at SchemaContextProvider (https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_graphiql_esm_index_js-caches_app_node_modules_graphiql_graphiql_css-652dabd55d7f8cd2443a8db786ed05477cbd40b2c8c1d55d3d5cf9fbe206ee87.js:2:288202)\n    at oo (https://cdn.shopify.com/shopifycloud/partners/bundles/latest/vendors-caches_app_node_modules_react-dom_index_js-caches_app_node_modules_react_index_js-f6116cdbe520ff77bf8552e66433e482efebd74601cd47a3d5ff541dac6bf665.js:2:60389)"
    }
  ]
}
```

### Reproduction steps

1. From your Partners Dashboard, navigate to Settings > Partner API clients. Next to the Partner API client that you want to explore, click View GraphiQL explorer.
2. Click on the documentation icon to display the error message

The bug by itself makes the gql schema impossible to read for the explorer, so it's impossible to use the graph without knowing the graph through and through. Which nobody does.

More importantly, the error message `Schema is invalid: Interface field Actor.name expects type String! but MerchantUser.name is type String.` show that there's a type divergence issue in one of your union types which use the Actor and the MerchantUser types. I can't tell more about which union type is broken on your schema since I do not have access to the schema... since your schema is broken.

### Operating System

Ventura 13.2.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

Latest

**Comment by Arkham** [comment]
hi @arsnl, sorry but this has nothing to do with the CLI, I'll have to close this :)
