### ISSUE TITLE
[Bug]: Packages with `-react` dependencies should use best-effort to find non-react dependency

### ISSUE THREAD

**Issue by NathanJolly** [Shopify/cli#1837]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Installing `retail-ui-extensions-react` shouldn't be required for a POS UI Extension that isn't using react.

### Actual behavior

A 3P developer installed `retail-ui-extensions` and attempted to test their extension by running `shopify app dev`. The extension looks like it should be working to the CLI, but the CLI fails to find the `retail-ui-extensions` version because the search algorithm relies on `retail-ui-extensions-react`. The extension fails to load because the POS validates this field: https://github.com/Shopify/cli/blob/fbca1710b646d366bbf971b532850ff84ba83576/packages/app/src/cli/services/dev/extension/payload.ts#L60

Granted - the scaffolding command always installs retail-ui-extensions-react regardless of whether the user chooses `react` or not, so clearly the 3P developer did something manually that broke this. However, we think there's an opportunity for the CLI to make a best-attempt to find the non-react package to populate the version field.

### Verbose output

```shell
None - CLI does not react with an error in this case.
```

### Reproduction steps

1. Create a POS UI Extension with `retail-ui-extensions`, but not `retail-ui-extensions-react` installed.
2. Run `shopify app dev`, inspect the payload from the dev server, and verify there is no `version` field set.

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.7.0

**Comment by isaacroldan** [comment]
@NathanJolly This has been solved on version 3.46, we only add react IF you decide to generate an extension with react support. Also, we won't look for the react dependency but for the base one.
