### ISSUE TITLE
[Bug]: Full page reload when any project/theme root file updated

### ISSUE THREAD

**Issue by vfonic** [Shopify/cli#1842]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

No full page reload

### Actual behavior

Full page reload occurs for any file change in the project (theme) root.

### Verbose output

```shell
/
```

### Reproduction steps

1. Start theme dev server
2. Create some file in the project/theme root: `touch some_file.txt`
3. (not necessary) Put some text inside the file and save it

### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.1

### Shell

oh my zsh

### Node version (run `node -v` if you're not sure)

v18.11.0

### What language and version are you using in your application?

/

**Comment by amcaplan** [comment]
cc @Shopify/theme-code-tools

**Comment by vfonic** [comment]
The inactivity bot seems to never close stale issues.

Yes, this issue is still valid.
