### ISSUE TITLE
[Feature]: shopify theme dev --live-reload delay

### ISSUE THREAD

**Issue by james0r** [Shopify/cli#1884]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Allow an argument that sets a delay in milliseconds for --live-reload

something like
```bash
shopify theme dev --delay 1000
```
This ability can be found in BrowserSync achievable with the reloadDelay config property [https://browsersync.io/docs/options#option-reloadDelay](https://browsersync.io/docs/options#option-reloadDelay).

### Motivation

I'm using Vite + TailwindCSS JIT compilation and the issue is that the live reload triggers once I save a liquid file and does not wait for the build system to compile my just-in-time styles forcing me to manually reload the browser to get the styles that include a class added to the liquid file.

**Comment by karreiro** [comment]
Thank you for that proposal, @james0r! I've added it into @theme-developer-tools roadmap.

**Comment by james0r** [comment]
Status bump

**Comment by montalvomiguelo** [comment]
Hi @james0r 

To help integrate `theme dev` with a reloading tool such as [Browsersync](https://browsersync.io/docs/options#option-reloadDelay), you can provide the optional `--notify` flag with a file path you want to be updated when the workers have gone idle. _E.g._ `shopify theme dev --notify /tmp/theme.update`

I created [this example](https://github.com/montalvomiguelo/skeleton-theme/tree/live-reload) using Vite for you (: 

Prolly we don't need to add more flags for this. We introduced the `notify` flag to help [integrate with other tools](https://shopify.dev/docs/themes/tools/theme-kit/command-reference#integration-with-other-tools) 
cc @karreiro

**Comment by julesgilson** [comment]
any progress on this?

**Comment by james0r** [comment]
> this example

@montalvomiguelo I don't see that this works/addresses my issue. It appears that the `--notify` flag touches /tmp/theme.update and that appears to be what FullReload vite plugin does as well.

If that's the case, then you have to dispatchers and no listeners so to speak. I believe what I need is a listener on the shopify dev watch service, and a dispatcher on the Vite service.

**Comment by montalvomiguelo** [comment]
@james0r The Vite plugin does not touch /tmp/theme.update, [it watches it to reload the page](https://github.com/ElMassimo/vite-plugin-full-reload/blob/main/src/index.ts#L64)

**Comment by montalvomiguelo** [comment]
@james0r when working with tailwind + vite + shopifycli, serving the theme with the `--live-reload full-page` flag helps. I have [this project](https://github.com/montalvomiguelo/hydrogen-theme) that uses tailwind :)

**Comment by james0r** [comment]
Thanks @montalvomiguelo. `--live-reload full-page` seems pretty solid now.
