### ISSUE TITLE
[Bug]: `shopify theme dev` opens new browser (or tab) every few hours

### ISSUE THREAD

**Issue by vfonic** [Shopify/cli#1910]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

I just upgraded to 3.45.3 and ran `shopify theme dev` with a sigh of relief that running this command _did not_ open my browser and/or created a new tab with http://127.0.0.1:9292/ url. Moments later, it did open a new tab in my browser.

I believe this was introduced in 3.45.0 or earlier. It was happening from 3.45.1 for me. I don't know which version I used before that.

Why is this an issue?

It is an issue, because it is unnecessary and disrupting whatever I was doing.
If I have the `shopify theme dev` running in the background, it will randomly (when it disconnects) relaunch Ruby ThemeKit, which will open a new tab, which is a huge issue. When this happens, my browser app gets focused and the new tab opens. I could be watching a movie, or typing in my password in another tab or having a live demo or doing anything else. There's no need for the CLI to open a new tab, especially not 2 hours after I started `shopify theme dev`.

If you cannot prevent restarts, or don't have better way to have ThemeKit (or whatever it's called) running in the background, please just _don't_ open a browser tab when the tool is restarted. It's extremely distracting.

Can you please introduce a config option for this or just remove the functionality? Or tell me which version of the CLI implemented this so that I can install the one before that.

Thank you!

### Actual behavior

/

### Verbose output

```shell
/
```

### Reproduction steps

1. Run `shopify theme dev`

### Operating System

macOS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.11.0

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by notrealdev** [comment]
same here

**Comment by elizabeth-aplo** [comment]
Same thing here.

**Comment by royvn** [comment]
Same here.

**Comment by vfonic** [comment]
@Christoph-AK how is this related to the login fix? I don't want Shopify CLI to open new browser window...ever. That includes the initial start of the server. The login fix might fix the issue where the new browser window opens after every 90-120 minutes (when login auth expires), but I still want to have the option of disabling new browser window from opening...
This is how the tool worked before and it's been recently introduced and it's interfering with my workflow. Especially when the new browser window opens and I'm in the middle of the conference call, sharing my screen!
