### ISSUE TITLE
[Bug]: deploy --force isn't working

### ISSUE THREAD

**Issue by zhernosekim** [Shopify/cli#1940]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

From shopify-cli documentation:
deploy -f, --force : Skip the deploy summary confirmation prompt. Critical prompts will still be shown.

### Actual behavior

It skips nothing

### Verbose output

```shell
npm run deploy --force
npm WARN using --force I sure hope you know what you are doing.

> project@1.0.0 deploy /path/extensions-manager
> shopify app deploy

?  Make the following changes to your extensions in Shopify Partners?

       Update:  • theme-extension

>  (y) Yes, deploy to push changes
   (n) No, cancel

   Press ↑↓ arrows to select, enter or a shortcut to confirm
```

### Reproduction steps

1. Install latest shopify-cli (my version 3.45.4)
2. Run npm run deploy --force
3. Flag --force doesn't skip confirmation

### Operating System

Ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.4

### Node version (run `node -v` if you're not sure)

v14.21.3

### What language and version are you using in your application?

npm packages @shopify/app, @shopify/cli for building theme-extension

**Comment by gonzaloriestra** [comment]
Hi!

NPM requires a separator for the arguments, as explained here: https://shopify.dev/docs/apps/tools/cli/commands#command-syntax

So you should run: `npm run deploy -- --force`.

Let me know if it doesn't work!
