### ISSUE TITLE
[Feature]: Add support for JSON file format in assets in theme app extensions

### ISSUE THREAD

**Issue by blanklob** [Shopify/cli#1962]
### What area(s) will this request affect?

Extension

### What type of change do you want to see?

New feature

### Overview

Currently, we are able to develop theme app extensions with JSON files inside Assets folder in theme app extensions. However, when attempting to deploy the theme app extension via the CLI deploy command, an error is thrown due to unsupported file extensions. Even after forking the project and attempting to ignore the error and add support, the error persists.

Here is the error:

```bash
There has been an error creating your deployment.                           │
│                                                                              │
│  copilot-ui                                                                  │
│                                                                              │
│  Validation errors                                                           │
│    • bundle: assets directory should only contain .jpg, .jpeg, .js, .css,    │
│      .png, .svg files   
```

### Motivation

I am trying to build a theme app extension that requires a JSON file as an asset, similar to how we currently use them in themes.

**Comment by alvaro-shopify** [comment]
Hi @clmntpct!. Thanks for rising up this issue. I will ping my partners from @Shopify/theme-code-tools thus they can help you with this.

**Comment by karreiro** [comment]
Hi @blanklob,

Thank you for bringing this up. I strongly agree that theme app extensions should also support JSON assets. However, this requires some changes at the platform level, as it is not limited to the Shopify CLI.

I have contacted folks responsible for theme app extensions, and they also agree. Once this feature is available on the platform, I will implement the necessary changes at the CLI level and leave a heads-up here.

Thank you again for raising this issue!

**Comment by alexandrosk** [comment]
I also want this functionality, please add it on the roadmap

**Comment by tentree-development** [comment]
slick library comes with .gif file can you also add support for gif file
