### ISSUE TITLE
[Bug]: Authentiction issue to dev store when trying to create a checkout ui extension 

### ISSUE THREAD

**Issue by qbzenker** [Shopify/cli#197]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

I'm trying to create an app with the new checkout UI extension (https://shopify.dev/api/checkout-extensions/checkout) and I keep getting an authentication error, which I do not expect to get. I created a new dev store, to which I am the owner, and am using the checkout preview dev feature for the store.

### Actual behavior

Keep getting `Looks like you need access to this dev store` error.

### Stack trace

```shell
App URL
Once everything's built, your app's shareable link will be:
<LINK>
Note that your app's URL in Shopify Partners will be updated.


━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Looks like you need access to this dev store (<STORE>)

    What to try:
    • Log in to the store directly from this URL. If you're the store owner, then that direct log in should solve your access issue.
    • If you're not the owner, create a dev store staff account for yourself. Then log in directly from the link above.


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Reproduction steps

```sh
# create a new app, use node template
yarn create @shopify/app

# run dev and login successfully to the store. ngrok is working fine
yarn dev 
```

this is when it fails:
```sh
# create a checkout UI extension
yarn scaffold extension

# run dev and login successfully to the store. ngrok is working fine
yarn dev 
```

## OUTPUT from terminal, some store details  removed
❯ yarn dev --reset
yarn run v1.22.19
$ shopify app dev --reset
✔ Dependencies installed
✔ Create this project as a new app on Shopify? · Yes, create it as a new app
✔ App Name · n1
✅ Success! n1 has been created on your Partners account.
✔ Which development store would you like to use to view your project? · Nash delivery fake store
✅ Success! The tunnel is running and you can now view your app.

App URL
Once everything's built, your app's shareable link will be:
<LINK>
Note that your app's URL in Shopify Partners will be updated.

━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Looks like you need access to this dev store (some1-fake-store)

    What to try:
    • Log in to the store directly from this URL. If you're the store owner, then that direct log in should solve your access issue.
    • If you're not the owner, create a dev store staff account for yourself. Then log in directly from the link above.

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.3.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.15.0

**Comment by pixelchutes** [comment]
Thanks for this helpful context, @pepicrft 

I am pretty sure I ran into this issue a few days ago as well. FWIW, I was able to resolve it by granting myself "**Staff**" access _(all permissions)_ in my dev store **Settings > Users and permissions**.

The error was indeed a bit confusing, as I am both a collaborator and the creator of the dev store in question. 

I can confirm `Staff` access solved it for me! 🎉

**Comment by pepicrft** [comment]
I'm so happy to hear that it solved the issue. You are not the only user experiencing this so we have some plans down the road to streamline our authorization model. 
I'll go ahead and close the issue then. Please, feel free to re-open it if you experience it again in the future and the solution doesn't work.

**Comment by rhyek** [comment]
This is confusing to say the least. I as the partner account owner created a development store. I'm trying to follow the suggestion mentioned here by adding a staff member with my same email, clicking "select all" and then inviting, but I get the error "Email has already been taken".

**Comment by rhyek** [comment]
Managed to overcome this by inviting myself with another email as staff member to both the store and the partner account. If anyone has any input so as to avoid this in the future, please share :-)

**Comment by ahmed-adly-khalil** [comment]
@pepicrft i'm facing the same issue after i created a checkout UI extension, i'm using the same user for the partner account and the dev store admin, any ideas? TY
