### ISSUE TITLE
[Bug]: deploy fails with error 500

### ISSUE THREAD

**Issue by joelclouddistrict** [Shopify/cli#1971]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The app should be deployed

### Actual behavior

The process fails with the message "Unexpected system error" and a status code "500"

### Verbose output

```shell
Request variables are redacted

2023-05-22T13:43:51.821Z: Sending "Partners" GraphQL request:
  mutation CreateDeployment(
    $apiKey: String!
    $uuid: String!
    $bundleUrl: String!
    $extensions: [ExtensionSettings!]!
    $label: String
  ) {
    deploymentCreate(
      input: {apiKey: $apiKey, uuid: $uuid, bundleUrl: $bundleUrl, extensions: $extensions, label: $label}
    ) {
      deployment {
        uuid
        id
        deployedVersions {
          extensionVersion {
            uuid
            registrationUuid
            validationErrors {
              message
              field
            }
          }
        }
      }
      userErrors {
        message
        field
      }
    }
  }
With variables:
{
  "apiKey": "",
  "uuid": "",
  "bundleUrl": "",
  "extensions": [
    {
      "uuid": "",
      "config": "",
      "context": ""
    }
  ]
}
....

The Partners GraphQL API responded unsuccessfully with the HTTP status 200 and errors:                                                                                     
[
  {
    "message": "Unexpected system error",
    "extensions": {
      "code": "500"
    }
  }
]
```

### Reproduction steps

1. Execute `npm run deploy`

### Operating System

Ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.45.4

### Shell

bash

### Node version (run `node -v` if you're not sure)

v16.15.1

### What language and version are you using in your application?

Node 16.15

**Comment by isaacroldan** [comment]
Glad to hear it works now :) 
We do print the userErrors, but this looked like a different issue, that's why we weren't printing anything else.
Thanks for reporting it!
