### ISSUE TITLE
[Bug]: Asset Urls are incorrect in Dev context

### ISSUE THREAD

**Issue by ekwoka** [Shopify/cli#1974]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When using `asset_url` you are directed to the dev theme specific files

Example: 

```html
<link href="{{ 'bundle.css' | asset_url }}" rel="stylesheet" type="text/css" media="all">
```

### Actual behavior

This directs to a link to the file on the live theme of the site, which can cause errors as you develop and things don't match up (like devtools showing all the wrong classes)

Let me know if this is more an issue with the cli or Shopify itself. The liquid transformation seems to be handling it wrong.

Notably, if the tag is instead written as 

```html
{{ 'bundle.css' | asset_url | stylesheet_tag: preload_tag: true }}
```

The url in the link on the page is still wrong (as above) but the preload link is correct, which I believe is what causes this to have strange issues when the file does exist on the live but is not the same as the current. When the file does not exist on the live site, the preload succeeds, but the direct css fails with a 401.

It also, sometimes seems to work and other times craps out completely.

### Verbose output

```shell
None, this is in a behavior of the integration of the CLI tools with Shopify, not an actual error state in the CLI
```

### Reproduction steps

1. <link href="{{ 'bundle.css' | asset_url }}" rel="stylesheet" type="text/css" media="all"> Maybe point this at a file that exists on the theme being developed and not the stores live site for extra verification
2. Load it in a dev theme
3. See it breaks

### Operating System

MacOs LAtest

### Shopify CLI version (check your project's `package.json` if you're not sure)

Latest

### Shell

zsh

### Node version (run `node -v` if you're not sure)

Latest

### What language and version are you using in your application?

Nodejs

**Comment by james0r** [comment]
Experiencing the same. Asset imports are pointing to hosted theme which fails.

What's the best way to revert versions with brew?

**Comment by ekwoka** [comment]
I've just been using the 3 url, the preview url on the site, but then I lose HMR

**Comment by lvzhenbang** [comment]
I'v two store, I am also experiencing this with Shopify CLI 3.46.0, but one normal, one abnormal

**Comment by vfonic** [comment]
Same issue here after upgrading to v3.46.1.

Can anyone please have a look? /cc @paulomarg 

This is how my Network tab looks like at http://127.0.0.1:9292/ because all of the assets are being fetched from the live theme (Dawn preview theme, but live theme is not Dawn):

![Screenshot 2023-05-26 at 11 05 11 AM](https://github.com/Shopify/cli/assets/67437/954c17aa-5c9b-4f73-9457-194da3d4795e)

**Comment by vfonic** [comment]
This is how I fixed it:

```shell
npm uninstall -g @shopify/cli @shopify/theme
npm install -g @shopify/cli@3.45.4 @shopify/theme@3.45.4
```

I don't use Homebrew because the people at Homebrew decided that every time you want to update any of the packages installed, you _have to_ upgrade all of the dependencies and it's so annoying that Homebrew upgrades my stable, working and LTS Node version to the latest, sometimes broken, version.

**Comment by max-commercetheory** [comment]
I'm also experiencing this issue. Only with some client stores.

**Comment by jwqperfect** [comment]
> I'v two store, I am also experiencing this with Shopify CLI 3.46.0, but one normal, one abnormal

I'v same problem , did u solve it ?

**Comment by jwqperfect** [comment]
> > I'v two store, I am also experiencing this with Shopify CLI 3.46.0, but one normal, one abnormal
> 
> I'v same problem , did u solve it ?

https://github.com/Shopify/cli/issues/1974#issuecomment-1564622633 it work

**Comment by jwqperfect** [comment]
> This is how I fixed it:
> 
> ```shell
> npm uninstall -g @shopify/cli @shopify/theme
> npm install -g @shopify/cli@3.45.4 @shopify/theme@3.45.4
> ```
> 
> I don't use Homebrew because the people at Homebrew decided that every time you want to update any of the packages installed, you _have to_ upgrade all of the dependencies and it's so annoying that Homebrew upgrades my stable, working and LTS Node version to the latest, sometimes broken, version.

thanks!  It work for me !

**Comment by pa-stripe** [comment]
Also experiencing this — it's basically completely broken theme development for us.
