### ISSUE TITLE
Could not start tunnel, max retries reached

### ISSUE THREAD

**Issue by girishfit4** [Shopify/cli#1980]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Kindly help

### Actual behavior

Could not start tunnel, max retries reached                                 │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at pollTunnelStatus (@shopify/app/src/cli/services/dev/urls.ts:106)       │
│      if (result.status === 'error') return reject(new                        │
│      BugError(result.message))                                               │
│    at (@shopify/app/src/cli/services/dev/urls.ts:120)                        │
│      pollTunnelStatus()                                                      │
│    at new Promise                                                            │
│    at pollTunnelURL (@shopify/app/src/cli/services/dev/urls.ts:101)          │
│      return new Promise<string>((resolve, reject) => {                       │
│    at generateFrontendURL (@shopify/app/src/cli/services/dev/urls.ts:89)     │
│      const url = await pollTunnelURL(options.tunnelClient)                   │
│    at dev (@shopify/app/src/cli/services/dev.ts:123)                         │
│      generateFrontendURL({                                                   │
│    at run (@shopify/app/src/cli/commands/app/dev.ts:106)                     │
│      await dev({                                                             │
│                                                                              

### Verbose output

```shell
-
```

### Reproduction steps

1.npm run dev
2.
3.

### Operating System

MacOS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0

### Node version (run `node -v` if you're not sure)

v20

### What language and version are you using in your application?

node

**Comment by Tomtom1410** [comment]
i have the same your bug, when i user npm run dev then have an error, I user shopify/cli": "^3.46.0 and nodejs v16.16.0 :((
![image](https://github.com/Shopify/cli/assets/87224702/6191c360-b931-4ca7-b1ef-c43178c6d240)

**Comment by girishfit4** [comment]
I found the solution today. I used cloudfare. Follow below steps:

Step 1: Run "cloudflared tunnel --url http://localhost:3000".

Step 2: One URL will be generated in the CMD for example "https://example.trycloudflare.com". Copy that and use it in Step 3.

Step 3: sudo npm run dev -- --tunnel-url https://example.trycloudflare.com:3000.

Hope it helps. Cheers :)

**Comment by Tomtom1410** [comment]
i try your solution to config cloudflared tunnel url, but i still have error, so what should i do? 
![image](https://github.com/Shopify/cli/assets/87224702/6129a6bf-38a2-4b5e-883a-b6652bc60985)

**Comment by gcaprio** [comment]
Any more movement here? I'm running into this issue too on a fresh shopify app template install.

**Comment by niinpatel** [comment]
reopened https://github.com/Shopify/cli/issues/2170
