### ISSUE TITLE
[Feature]: Do not open theme preview on `shopify theme dev` by default

### ISSUE THREAD

**Issue by davidthorand** [Shopify/cli#1997]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

Currently a new browser tab is opened everytime you run `shopify theme dev`. This also happens periodically which is somewhat annoying. I tried to add a flag for this myself but I can't get the CLI to work locally.

This is the part that needs to be adjusted: https://github.com/Shopify/cli/blob/2a04b931c89b3f5b385f1d3195b68edf65516719/packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb#L187

It should be behind a `--open` flag so users can choose whether the theme preview should be opened or not.

### Motivation

We are using our own handler to open a browser tab once the Shopify CLI is done syncing the theme. We are using an implementation of https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/openBrowser.js which has some benefits over Shopify's implementation, primarily that it does not open a new browser tab every time. Instead it focusses or reloads an existing browser tab with matching host/port.

**Comment by karreiro** [comment]
Thank you for reporting that, @davidthorand.

+1 for the `--open` flag. I'm closing because this is going to be implemented by https://github.com/Shopify/cli/issues/1997.
