### ISSUE TITLE
Add "did you mean?"

### ISSUE THREAD

**Issue by pepicrft** [Shopify/cli#2]
[Reference](https://github.com/Shopify/shopify-cli-next/issues/227)

Add oclif plugin that asks the user if they meant something else when they introduced a non-existing command.

**Comment by MeredithCastile** [comment]
Yes, exactly. Not above the cut line for this particular round of components. But it seems to be a best practice to have an affordance like this. And I do wonder if an out of the box package would suffice. For instance: [fuzzy match npm package](https://www.npmjs.com/package/did-you-mean). I wonder what that UI looks like...
