### ISSUE TITLE
[Bug]: Invalid schema: class is invalid for TailwindCSS classes

### ISSUE THREAD

**Issue by dspeake** [Shopify/cli#2003]
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

Shopify CLI does not validate TailwindCSS classes:

```
{% schema %}
{
  "name": "Featured products",
  "tag": "div",
  "class": "pt-large tablet:pt-medium pb-large",
  "settings": [
  ]
}
{% endschema %}
```

See also: Shopify/shopify-cli#1449

### Actual behavior

`Invalid schema: class is invalid`

### Reproduction steps

1. Add TailwindCSS class with special character (e.g. colon) to "class" section schema.
2. Serve theme to store (`shopify theme serve`).

### Operating System

Mac OS Monterey

### CLI version (run `shopify version` if you're not sure)

2.18.0

### Shell

bash

### Ruby version (run `ruby -v` if you're not sure)

2.7.0p0

**Comment by dspeake** [comment]
Still present in `@shopify/cli/3.46.5 darwin-x64 node-v20.3.0`

**Comment by dspeake** [comment]
Still present in `@shopify/cli/3.47.5 darwin-x64 node-v20.4.0`

**Comment by dspeake** [comment]
Still present in `@shopify/cli/3.48.0 darwin-x64 node-v20.5`

**Comment by bojandurmic** [comment]
Still present today.

**Comment by dspeake** [comment]
Still present in `@shopify/cli/3.49.3 darwin-x64 node-v20.6.1`

Perhaps this should be better placed in [theme-check](https://github.com/Shopify/theme-check)?

**Comment by adrienpicard** [comment]
Still present using `3.52.0`

**Comment by adrienpicard** [comment]
Still present `@shopify/cli/3.59.0 darwin-arm64 node-v21.7.3`
