### ISSUE TITLE
[Bug]: OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello

### ISSUE THREAD

**Issue by shestakov-vladyslav** [Shopify/cli#2016]
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

idk
![image](https://user-images.githubusercontent.com/18069756/236493415-ae1aefc3-6627-4db7-93c5-b4a891630f87.png)

### Actual behavior

idk
![image](https://user-images.githubusercontent.com/18069756/236493431-357fc78f-7954-409b-863d-ec4d59ad5934.png)

### Stack trace

```shell
C:/Ruby30-x64/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock'
C:/Ruby30-x64/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
C:/Ruby30-x64/lib/ruby/3.0.0/net/http.rb:1038:in `connect'
C:/Ruby30-x64/lib/ruby/3.0.0/net/http.rb:970:in `do_start'
C:/Ruby30-x64/lib/ruby/3.0.0/net/http.rb:959:in `start'
```

### Reproduction steps

1.
2.
3.

### Operating System

x64-mingw32

### CLI version (run `shopify version` if you're not sure)

2.35.0

### Ruby version (run `ruby -v` if you're not sure)

3.0.3p157

**Comment by Arkham** [comment]
We can close this, as it is CLI2 related.
