### ISSUE TITLE
[Question-Feature] Synchronize theme editor from prod to dev

### ISSUE THREAD

**Issue by clmntpct** [Shopify/cli#2026]
### What area(s) will this request affect?

Theme, Running your code locally, Deployment

### What type of change do you want to see?

New feature

### Overview

Hey there!

I was wondering if there was a way to synchronize the theme editor from the production to my development store using CLI ?

I know that you can add the following flag `--theme-editor-sync` while using `shopify theme dev` but is it possible to do so when pushing my theme to production ?

### Motivation

Between two requests from my client, he did change his front store using the theme editor, and I did not notice it.

Once I pushed my updates live, the whole front store changed based on what was on my development theme editor.

I don't really understand how to synchronize my development theme editor based on the production theme editor.

**Comment by clmntpct** [comment]
thanks !

**Comment by forwells** [comment]
is there any update? I want sync live theme editor change to local theme files too!
