### ISSUE TITLE
[Bug]: Using 'theme dev' outputs invalid editor/preview url when using --theme [name]

### ISSUE THREAD

**Issue by naxorn** [Shopify/cli#2036]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When running the command ```shopify theme dev --theme [theme NAME]``` the console output should show:

```
...
[2] https://munchables-staging.myshopify.com/admin/themes/[theme ID]/editor
[3] https://munchables-staging.myshopify.com/?preview_theme_id=[theme ID]
...
```

### Actual behavior

Instead the url contains the theme name rather than the id:

```
...
[2] https://munchables-staging.myshopify.com/admin/themes/[theme NAME]/editor
[3] https://munchables-staging.myshopify.com/?preview_theme_id=[theme NAME]
...
```

NOTE: Running the command ```shopify theme open --theme [theme NAME]``` uses the theme ID in the editor url.

### Verbose output

```shell
Theme NAME is only mentioned in the command used. Everywhere else uses the theme ID.
```

### Reproduction steps

1. Run shopify theme dev --theme [theme NAME]
2. The console output shows the editor and preview urls with the theme NAME, rather than the theme ID

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.1

### Shell

powershell

### Node version (run `node -v` if you're not sure)

v18.16.0

**Comment by amcaplan** [comment]
cc @Shopify/theme-code-tools
