### ISSUE TITLE
[Bug]: MacOS Ventura with M1: latest CLI update breaks theme dev

### ISSUE THREAD

**Issue by nelsonvassalo** [Shopify/cli#2089]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Running `shopify theme dev` opens development theme in a browser and runs correctly.

### Actual behavior

Running `shopify theme dev` does not throw errors. However, all scripts and style of the website now throw a 404, while the code is the same as before. Opening the theme in theme editor shows the website as expected and, weirdly, the share link from that shows the theme intact.

### Verbose output

```shell

…

[2023-06-02 13:35:50] INFO  WEBrick 1.7.0
[2023-06-02 13:35:50] INFO  ruby 3.2.2 (2023-03-30) [x86_64-darwin22]
[2023-06-02 13:35:50] INFO  WEBrick::HTTPServer#start: pid=30257 port=9292
DEBUG Refreshing preview _secure_session_id cookie
DEBUG Proxying HEAD https://▤▤▤▤▤▤▤▤.myshopify.com/?preview_theme_id=150835757373&_fd=0&pb=0
DEBUG `-> 302 request_id: 5eca834b-6042-4825-aa3c-520c5df9a3c3
DEBUG Proxying GET https://▤▤▤▤▤▤▤▤.o.myshopify.com/?_fd=0&pb=0
DEBUG `-> 200 request_id: 8bcce7e8-3515-4af1-a944-1392c268ebb8
DEBUG [HotReload] Connected to SSE stream
```

### Reproduction steps

1. CLI was running fine before update to latest
2. Updated to latest
3. Ran `shopify theme dev`
4. CLI runs fine, but the output development theme is throwing 4040 HTTP errors on all assets.
5. If opened in the shareable link the website works as expected, if opened on localhost it fails.

### Operating System

MacOS Ventura 13.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.2

### Shell

Terminal, OhMyZSH

### Node version (run `node -v` if you're not sure)

v18.10.0

**Comment by nelsonvassalo** [comment]
Can confirm this is solved by downgrading to previous version (using npm)

**Comment by karreiro** [comment]
Thank you, @nelsonvassalo, for reporting this issue. It has been fixed by https://github.com/Shopify/cli/pull/2105 and will be included in the upcoming CLI release.
