### ISSUE TITLE
[Bug]: `shopify theme dev` not working

### ISSUE THREAD

**Issue by egantz** [Shopify/cli#2133]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It should have had `shopify theme check` + `shopify theme dev` run properly

### Actual behavior

It didn't work, complaining about ffi (1.15.5) and `listen` (3.7.1)

### Verbose output

```shell
Undefined symbols for architecture x86_64:
  "_ffi_call", referenced from:
      _ffi_raw_call in raw_api.o
      _ffi_java_raw_call in java_raw_api.o
  "_ffi_closure_trampoline_table_page", referenced from:
      _ffi_trampoline_table_alloc in closures.o
  "_ffi_prep_cif_machdep", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_cif_machdep_var", referenced from:
      _ffi_prep_cif_core in prep_cif.o
  "_ffi_prep_closure_loc", referenced from:
      _ffi_prep_closure in prep_cif.o
      _ffi_prep_raw_closure_loc in raw_api.o
      _ffi_prep_java_raw_closure_loc in java_raw_api.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libffi.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: ***
["/Users/user/Library/Caches/shopify-gems-nodejs/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi-arm64-darwin22"/.libs/libffi_convenience.a]
Error 2

make failed, exit code 2

....

An error occurred while installing ffi (1.15.5), and Bundler cannot continue.

In Gemfile:
  listen was resolved to 3.7.1, which depends on
    rb-inotify was resolved to 0.10.1, which depends on
      ffi
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using ast 2.4.2
Using bundler 2.4.10
Using racc 1.7.0
Using concurrent-ruby 1.2.2
Using liquid 5.4.0
Using rb-fsevent 0.11.2
Using bugsnag 6.25.2
Using parser 3.2.2.2
Using nokogiri 1.14.5 (arm64-darwin)
Using theme-check 1.15.0
Installing ffi 1.15.5 with native extensions
```

### Reproduction steps

1. `arch -arm64 brew tap shopify/shopify`
2. `arch -arm64 brew install shopify-cli`
3. `shopify theme dev`

### Operating System

macOS Ventura 13.5

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.2.0

### What language and version are you using in your application?

Ruby 3.2.2

**Comment by amcaplan** [comment]
Hi @egantz, I'm curious why you're running under a specific architecture. That's likely to cause problems in `ffi` installation. 

I'd expect that the version of Ruby you installed when running `brew install shopify-cli` was on arm64 architecture, but per the error message, you're running x86_64 when executing `shopify theme dev` which installs dependencies under the hood. Hence the incompatibility.

I think you need to run the CLI with the same architecture as you installed it. Does that work?

**Comment by egantz** [comment]
@amcaplan Thanks a ton, Ariel! Your direction helped me find a bigger problem on my machine that I just fixed. Everything's running with arm64 homebrew now and the CLI works perfectly! Closing this issue. Thank you man!
