### ISSUE TITLE
[Bug]: [app extensions] npm run deploy: arrow keys are not working to choose the app on Windows

### ISSUE THREAD

**Issue by samanamp** [Shopify/cli#2140]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

On older version of CLI, the arrow keys were working to choose the app.

### Actual behavior

Now the arrow keys are not working here:
![image](https://github.com/Shopify/cli/assets/2099595/9f0aa889-a155-4def-aff5-eb275d374a5c)

### Verbose output

```shell
No verbose output
```

### Reproduction steps

1. On a windows machine, go to the app extensions directory and run: npm run deploy
2.?  Deploy to the same org and app as you used for dev?
✔  No, use a different org or app
3.?  Create this project as a new app on Shopify?
✔  No, connect it to an existing app
4. Now it lets you choose between apps, but the arrow keys are not working to actually choose the app.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.3

### Shell

windows command prompt

### Node version (run `node -v` if you're not sure)

v 18.14.0

### What language and version are you using in your application?

Node

**Comment by amcaplan** [comment]
@samanamp this is quite surprising, thanks for the report! I'll try and figure this out, but it would help if you can let me know what version on your machine has the arrow keys working, so I can more easily isolate the relevant change.

**Comment by amcaplan** [comment]
Here's what the search bar looks like on my machine:

<img width="526" alt="Screenshot 2023-06-12 at 14 45 46" src="https://github.com/Shopify/cli/assets/6288426/35d34b04-c9ab-4ae6-8011-a9166297ca61">

**Comment by samanamp** [comment]
I tried multiple terminals, no luck at all. Even legacy windows prompt. Interestingly I don't see the search part in front of the question. I have the latest cli. Hope these data helps:
<img width="231" alt="image" src="https://github.com/Shopify/cli/assets/2099595/2f428b28-b499-4205-b3dc-804841b26f36">
<img width="188" alt="image" src="https://github.com/Shopify/cli/assets/2099595/bb9b9756-b448-4090-952a-7c2110abcf8d">
<img width="233" alt="image" src="https://github.com/Shopify/cli/assets/2099595/4c81ca20-22ee-4b67-aaff-4c1acdd8119a">

**Comment by amcaplan** [comment]
Hi @samanamp, can you please check `npm run shopify version`? What I see is the globally installed CLI version, but that's not the version pinned in your app's `package.json`.

**Comment by samanamp** [comment]
@amcaplan here is the output of the command:
![image](https://github.com/Shopify/cli/assets/2099595/04e304d5-67cf-48ae-8549-68e2825bc5e6)

@pangiras pressing the enter worked!
