### ISSUE TITLE
[Bug]: New Extension is suddenly not rendered anymore, instead the HTML shows <!-- Failed to render app block "<id A>": app block path "shopify://apps/<app name>/blocks/app-block/<id B>" does not exist —>

### ISSUE THREAD

**Issue by felixmpaulus** [Shopify/cli#2156]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

After I publish a new version of my extension I expect the new version to load inside the merchants storefront where the previous version was successfully loading before.

### Actual behavior

The App Block of the new extension is instead rendered inside the HTML as a comment saying that the App Block failed to render because the App Block path does not exist. 
This is the commented HTML (I removed both id's and the app name):

<- Failed to render app block "<id A>": app block path "shopify://apps/<app name>/blocks/app-block/<id B>" does not exist ->

My last extension version was published in December of last year with CLI 2. I suspect the upgrade to CLI 3 has corrupted my extension somehow. FYI I did not migrate to CLI 3 but instead started fresh with the node template.

I created the extension with `npm run shopify app generate extension` and that probably created a new extension with no reference to my previous one. But then again it shows up in my Partner dashboard with all previous versions and I can version and publish it just fine. 

<img width="2408" alt="Screenshot 2023-06-12 at 13 30 53" src="https://github.com/Shopify/cli/assets/35754650/c6be6cc8-b38b-4327-a19c-73be1f5e9a1c">

### Verbose output

```shell
The deployment runs without any errors AND the deployed version shows up in my partner dashboard ready for publishing.
Here are the rather unspectacular logs:

npm run deploy

> bloom-better-bullets@1.0.0 deploy
> shopify app deploy

? Make the following changes to your extensions in Shopify Partners?
✔ Yes, deploy to push changes

Deploying your work to Shopify Partners. It will be part of Bloom: Better Bullets

theme_extensions │ Running theme check on your Theme app extension...
theme_extensions │ Checking /Users/felixpaulus/Documents/Projects/Shopify Plugins/01 Bloom Better 
Bullets/app/extensions/bloom-better-bullets ...
theme_extensions │ 2 files inspected, 0 offenses detected, 0 offenses auto-correctable

success 
Deployed to Shopify! 
Summary 
• bloom-better-bullets is deployed to Shopify but not yet live 
Next steps 
• Publish bloom-better-bullets
```

Info command returns:

```
$ npm run shopify app info

> bloom-better-bullets@1.0.0 shopify
> shopify app info

CONFIGS FOR DEV                    
App           Bloom: Better Bullets DEV
Dev store     better-bullets.myshopify.com
API key       a9d5114f51bf44cd6afdbea6af7384b9
Update URLs   Always

💡 To change these, run npm run dev -- --reset

YOUR PROJECT                       
Name            bloom-better-bullets
Root location   /Users/felixpaulus/Documents/Projects/Shopify Plugins/01 Bloom Better Bullets/app

DIRECTORY COMPONENTS               

web
📂 web
  📂 backend    web
  📂 frontend   web/frontend
  📂 backend    node_modules/shopify-app-template-node
  📂 frontend   node_modules/shopify-frontend-template-react
  📂 frontend   node_modules/shopify-app-template-node/frontend

theme_external
📂 bloom-better-bullets   extensions/bloom-better-bullets
     config file          shopify.theme.extension.toml

ACCESS SCOPES IN ROOT TOML FILE    
read_products
 read_themes

TOOLING AND SYSTEM                 
Shopify CLI       ^3.46.4
Package manager   npm
OS                darwin-arm64
Shell             /bin/zsh
Node version      v20.3.0
```

### Reproduction steps

No idea.
It works completely fine in my development environment. The App Block loads correctly.
Only once I publish the new version does it break. 
So it affects all my customers which makes it very difficult for me to debug.

### Operating System

Mac OS Ventura 13.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.3.0

**Comment by pepicrft** [comment]
Unsubscribing from the PR since I'm no longer at Shopify 🙃

**Comment by felixmpaulus** [comment]
@shopify-admins asking for this to be reopened since I am still unable to push any extension update to my paying customers. this has been going on for 2 months now. Shopify support was of no help and told me to come back here.

**Comment by felixmpaulus** [comment]
@albchu thank you for the reply.

I spend probably 40-60 hours debugging this and communicating with the support. 
Every idea you mentioned (and many many others) I most certainly tried multiple times without success.

After 6 weeks of back and forth the partner support told me they wont support me with this anymore since they can not find the cause.

I ended up deleting my extension and pushing a completely new one, forcing me to email over 400 merchants and asking them to add the app block in their theme editor again. 

This really seems to be a niche problem. 
Overall I personally do not like the new deployment process with CLI 3.0. It feels fragile to me.

**Comment by emreisik95** [comment]
Hey there, @albchu @felixmpaulus

We have exact problem, it is working perfectly on development stores, but we can't create a new release, it says `Failed to render app block`. Do you plan to resolve this issue any soon? We have to publish new release as soon as possible.

**Comment by dannye0231** [comment]
Looks like that fixed the issue.  Thanks for looking into this one!

**Comment by afunnydev** [comment]
Same problem as @emreisik95 and renaming it back to the previous name also fixed it. That's a really weird behaviour, but thanks a lot, I was pulling my hair out!

**Comment by ahs53** [comment]
Had the same issue -- switching to the old name fixes the bug.

**Comment by mehmettekn** [comment]
> Okay I got the problem. You can not change the name of the file for theme extension. If it is `theme_extension.liquid` you can not change it `theme_extension_new.liquid`. When I made a name change, my problem resolved automatically.
> 
> I think you should fix that, it should automatically connect the new file. [@albchu](https://github.com/albchu)

I had the same problem and I realized it was the name change in the block file name. However, even when I changed back to the old name, I realize that existing users can now render the block in their store but new users aren't able to add block to their store...
