### ISSUE TITLE
[Bug]:  Build error

### ISSUE THREAD

**Issue by Noostop** [Shopify/cli#2198]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Compilation ends normally。

### Actual behavior

D:\code\bundle-app>yarn build
yarn run v1.22.19
$ shopify app build
 product-discount │ Building GraphQL types...
 frontend         │
 frontend         │ > discount-frontend@1.0.0 build
 frontend         │ > vite build
 frontend         │
 frontend         │
 frontend         │ > discount-frontend@1.0.0 build
 frontend         │ > vite build
 frontend         │
 frontend         │
 frontend         │ > discount-frontend@1.0.0 build
 frontend         │ > vite build
 frontend         │
 frontend         │ node:internal/modules/cjs/loader:1078
 frontend         │   throw err;
 frontend         │   ^
 frontend         │ 
 frontend         │ Error: Cannot find module 'D:\code\bundle-app\node_modules\node_modules\vite\bin\vite.js'
 frontend         │     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
 frontend         │     at Module._load (node:internal/modules/cjs/loader:920:27)
 frontend         │     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
 frontend         │     at node:internal/main/run_main_module:23:47 {
 frontend         │   code: 'MODULE_NOT_FOUND',
 frontend         │   requireStack: []
 frontend         │ }
 frontend         │ 
 frontend         │ Node.js v18.16.0

── external error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `npm run build`

Command failed with exit code 1: npm run build
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'D:\code\bundle-app\node_modules\node_modules\vite\bin\vite.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

> discount-frontend@1.0.0 build
> vite build

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Verbose output

```shell
D:\code\bundle-app>yarn build
yarn run v1.22.19
$ shopify app build
 product-discount │ Building GraphQL types...
 frontend         │
 frontend         │ > discount-frontend@1.0.0 build
 frontend         │ > vite build
 frontend         │
 frontend         │
 frontend         │ > discount-frontend@1.0.0 build
 frontend         │ > vite build
 frontend         │
 frontend         │
 frontend         │ > discount-frontend@1.0.0 build
 frontend         │ > vite build
 frontend         │
 frontend         │ node:internal/modules/cjs/loader:1078
 frontend         │   throw err;
 frontend         │   ^
 frontend         │ 
 frontend         │ Error: Cannot find module 'D:\code\bundle-app\node_modules\node_modules\vite\bin\vite.js'
 frontend         │     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
 frontend         │     at Module._load (node:internal/modules/cjs/loader:920:27)
 frontend         │     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
 frontend         │     at node:internal/main/run_main_module:23:47 {
 frontend         │   code: 'MODULE_NOT_FOUND',
 frontend         │   requireStack: []
 frontend         │ }
 frontend         │ 
 frontend         │ Node.js v18.16.0

── external error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `npm run build`

Command failed with exit code 1: npm run build
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'D:\code\bundle-app\node_modules\node_modules\vite\bin\vite.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

> discount-frontend@1.0.0 build
> vite build


──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction steps

1. yarn install
2. yarn build

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

Current Shopify CLI version: 3.45.1

### Shell

cmd

### Node version (run `node -v` if you're not sure)

v18.16.0v18.16.0

### What language and version are you using in your application?

ruby 3.2.2

**Comment by Arkham** [comment]
can you update your version of `@shopify/cli` and `@shopify/app` to latest and retry?

**Comment by Noostop** [comment]
> Error: Cannot find module 'D:\code\bundle-app\node_modules\node_modules\vite\bin\vite.js'

The path of the compile and get command is wrong.

`Error: Cannot find module 'D:\code\bundle-app\node_modules\node_modules\vite\bin\vite.js'`
