### ISSUE TITLE
[Feature]: Allow publishing theme app extensions

### ISSUE THREAD

**Issue by boronine** [Shopify/cli#2202]
### What area(s) will this request affect?

Extension

### What type of change do you want to see?

New feature

### Overview

Currently Shopify CLI allows us to *deploy* our theme app extension, but not to *publish* it. In the documentation publishing is described as a manual process: https://shopify.dev/docs/apps/deployment/extension#step-3-create-a-version-and-publish

### Motivation

We are simply trying to automate our app deployment. Shopify has a [page on supporting CI/CD pipelines](https://shopify.dev/docs/apps/tools/cli/ci-cd), but at the moment Continuous Deployment is impossible because of this limitation.

**Comment by jessehoek** [comment]
Yes, this is coming soon! You'll be able to fully release all your extensions right from Shopify CLI with the `app deploy` command. And it will work in non-interactive environments if you use the `--force` flag 😃

**Comment by jessehoek** [comment]
Simplified deployment is now released! Once you opt in for an app, you should be able to publish your theme app extension (and all your other extensions at the same time) with the deploy command.
