### ISSUE TITLE
[Bug]: shopify app dev spawns a ruby process that takes 99.1% of CPU usage on MacOS

### ISSUE THREAD

**Issue by wisniewski94** [Shopify/cli#2213]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

CPU usage is way too high. It causes my MacOS fans to spin too loud and the machine to heat up too much.

### Actual behavior

After running npm run dev (that runs shopify app dev) on `latest` version my PC heats up too much.

`ps aux -o %cpu,%mem,rss,vsz,start_time,user,command` returns:

```
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND           %CPU %MEM    RSS      VSZ USER             COMMAND
redacted 56303  99,1  0,2 33731004  32524 s005  R    11:00     9:53.21 /Users/redacted  99,1  0,2  32524 33731004 redacted /Users/redacted/.rvm/rubies/ruby-3.0.0/bin/ruby /Users/redacted/Documents/web/
```

Note 99,1 of CPU usage

**After terminating app with cmd+c, ruby process is still running (!)**

### Reproduction steps

1. run npm run dev in node template

### Operating System

MacOS Ventura 13.2

### Shopify CLI version (check your project's `package.json` if you're not sure)

latest

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.14.2

### What language and version are you using in your application?

ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin21],

**Comment by wisniewski94** [comment]
I'm eager to provide more details, the issue is easy to reproduce as it occurs every time I'm working with any app.

**Comment by Arkham** [comment]
On the first run, ruby needs to compile native extensions, so it might take a few minutes to compile. If you wait a bit instead of Control-C, from the next time it should boot pretty quick. Let me know if that's not the case.

**Comment by Arkham** [comment]
We use Ruby gems to provide theme editing functionality inside the cli. Some Ruby gems require compiling native extensions in C in order to work. So my hypothesis is that it was getting stuck while compiling some of these dependencies. Could you share a minimal repository where you see the issue?

**Comment by wisniewski94** [comment]
Unfortunately not immediately as mostly I'm working on private projects, but I will try to reproduce the issue on the current template during the weekend. All I can share right now are what terminal return:

```
redacted 74332  96,1  0,0 33760520   7716 s009  R     4:16    35:50.66 /Users/redacted  96,1  0,0   7716 33760520 redacted /Users/redacted/.rvm/rubies/ruby-3.0.0/bin/ruby /Users/redacted/Documents/web/redacted-app/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify extension serve /Users/redacted/Documents/web/redacted-app/extensions/redacted-extension --api-key redacted --extension-id redacted
```

note the time is 35 minutes now

and here's the battery usage graph:
<img width="200" alt="image" src="https://github.com/Shopify/cli/assets/5289996/fd5be585-22b4-4e6b-bb26-001ab056f22c">

If you could guide me if there is any command that I could use to print logs just for that ruby build maybe we could shorten the time spent on this issue. Anyway I will keep you posted once I will be able to reproduce the issue on the plain template with some theme extensions in the background

**Comment by Arkham** [comment]
One suggestion would be to run that command separately from the console. Does it print any output? If not, the next step would be to use GDB and inspect which system call is the Ruby process stuck in, you can follow many tutorials online, here's one for Ruby: https://www.mikeperham.com/2016/08/05/debugging-stuck-ruby-processes/

**Comment by wisniewski94** [comment]
Perfect, thank you, will check and post the findings
