### ISSUE TITLE
[Bug]: Unable to create symbolic link for frontend dir in window 11

### ISSUE THREAD

**Issue by iserioton** [Shopify/cli#2231]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should create an app successfully.

### Actual behavior

Due to the error, the init script unexpectedly crashed

### Verbose output

```shell
EPERM: operation not permitted, symlink 'C:\Users\Dell\AppData\Local\Temp\  │
│  9c65e11c09c71ac6e434017fe15c53b9\app\web\frontend' ->                       │
│  'D:\Workspace\existing-app\node_modules\shopify-frontend-template-react'
```

### Reproduction steps

1. In window 11 try creating a new app using `npm init @shopify/app@latest`
2.  Which template would you like to use?: node
3. Wait until the dependency is installed 

### Operating System

Window 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0.0

### Shell

cmd

### Node version (run `node -v` if you're not sure)

v18.16.0

### What language and version are you using in your application?

Node v18.16.0

**Comment by mubbo** [comment]
Same issue,


@shopify/cli/3.46.5 win32-x64 node-v18.16.0
Windows 11 Pro  22H2

**Comment by Elangamani-itf** [comment]
Same issue, 

@shopify-admins 

Please give solution to resolve this issue, Can't able to install shopify app to local system. i'm using windows 11, node version: 18.16.1

**Comment by isaacroldan** [comment]
Hi everyone, thank you for reporting this. Unfortunately i'm not able to reproduce it :(
Have you tried with different shells on windows? we recommend using Terminal and Powershell, as `cmd` is very limited.

Does the error happen just after running `npm init... `?

**Comment by iserioton** [comment]
It works with PowerShell, thanks!!! @isaacroldan
