### ISSUE TITLE
[Bug]: Single process app UNINSTALLED webhook not working

### ISSUE THREAD

**Issue by juanpmarin** [Shopify/cli#2232]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I have a single process shopify app, these are my config files:

shopify.app.toml
```
scopes = "write_shipping"
```

shopify.web.toml
```
[commands]
dev = "pnpm dev:shopify"
```

My process is running in the port set by the cli in the `PORT` env var, and app in general works as expected

When I run `shopify app dev --reset` the cli tries to send an UNINSTALL webhook but I get the following error:
`APP_UNINSTALLED webhook delivery failed`

I did some research and `PORT` is getting the same value as `FRONTEND_PORT`, but the cli is trying to send the webhook payload tot `BACKEND_PORT`, which of course is not being listened as this is a single process app

### Actual behavior

Webhook should be sent to `FRONTEND_PORT`

### Verbose output

```shell
.
```

### Reproduction steps

1. Create a single process shopify app
2. Run `shopify app dev --reset` 

### Operating System

Fedora Linux 38

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.5

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.16.1

### What language and version are you using in your application?

Node 18.16.1 with clouduflare wrangler

**Comment by isaacroldan** [comment]
Hi @juanpmarin we recently added a new config in toml to specify that you are running a single process.

In your `shopify.web.toml` file, please set 
```
roles: ["frontend", "backend"]
```
(and remove any existing `type` from there)

more details: https://shopify.dev/docs/apps/tools/cli/structure#shopify-web-toml

**Comment by alvaro-shopify** [comment]
Hi @lkstc!, please, take a look at the explanation given by my partner @isaacroldan , could you try to configure the app in that way?

**Comment by juanpmarin** [comment]
@isaacroldan I'm still getting `App isn't responding yet, retrying in 5 seconds`

**Comment by shippinglob** [comment]
August 2025. Still getting the same error...

**Comment by isaacroldan** [comment]
@shippinglob This is an old issue and the CLI has changed a lot since then. Can you open a new issue with more details about your case? Thanks!
