### ISSUE TITLE
[Bug]: <CLI 3.0: [Shopify theme dev] | sudden errors over night, without code changes>

### ISSUE THREAD

**Issue by alphaasiate** [Shopify/cli#2252]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme, Other

### Expected behavior

I am currently working on the impact-theme, which has been uploaded as a repository on github and imported as a theme to Shopify.

When customising the theme via Shopify customiser or code-editor, the code shall be saved. 
And should be able to be served via the Shopify CLI command: "Shopify theme dev".
When using this, a local port get connected, and the preview of this should look and behave the same as when previewing via Shopify theme preview. 

Here is the correct output, shown via the Shopify theme preview of "impact/main":

<img width="1420" alt="image" src="https://github.com/Shopify/cli/assets/105013490/f8801c47-6d12-4469-9b10-170ba64f7228">

### Actual behavior

Yesterday, there was no issue. 
Since then, no code adjustments have been made, but now suddenly today, there are issues showing up when serving the theme-code via the Shopify CLI with the version 3.46.5.

Here a screenshot of the errors shown in the terminal when using this command. 
![image](https://github.com/Shopify/cli/assets/105013490/6a04f0a2-6476-4508-a385-12d4ad0c89ac)

also the output looks like this now and is not behaving as it should: 
<img width="1420" alt="image" src="https://github.com/Shopify/cli/assets/105013490/5b6f5045-66e3-4c36-9566-fb41c0f0008b">

of course here, are many sections/blocks missing, and are not shown correctly, as the json-settings have ben set differently then displayed here.

### Verbose output

```shell
I am not sure I understand this task correctly
it always says "command not found"
```

### Reproduction steps

1. log in to https://teeimglas.myshopify.com/admin or https://github.com/MainTea/Impact
2. open the theme "impact/main" Shopify or the GitHub repository "Impact" | Branch: "Impact/main" and open in IDE (visual studio code)
3. open terminal
4. use command: "Shopify theme dev"
5. wait for the sync and look at the errors listed in the terminal

### Operating System

Mac OS Monterey | version 12.6.7

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.46.5

### Node version (run `node -v` if you're not sure)

v18.2.0

**Comment by isaacroldan** [comment]
@Shopify/theme-code-tools
