### ISSUE TITLE
CLI 3.0 deep link UUID not available 

### ISSUE THREAD

**Issue by Sky-bits** [Shopify/cli#2333]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

CLI 2.x was sunset so I moved to the CLI 3.0 I create new extension but CLI manage all the things there end. i want provide the app block deep links.
as per the Shopify CLI generated the .env  I can find the extension UUID that was used for the deep links. 
CLI 3.0 I can't see any the any .env file or .toml file container the UUID 

deep link shall be working as per the last version. 

### Actual behavior

I want to create the theme app block extension deep link user can see the block link into the app details page.

### Verbose output

```shell
no any Error.
```

### Reproduction steps

1. create new theme app extension
2.  `npm run shopify app generate extension`
3.  https://shopify.dev/docs/apps/online-store/theme-app-extensions 
4. [npm run deploy](https://shopify.dev/docs/apps/online-store/theme-app-extensions/getting-started)
5. npm run deploy
6. npm run deploy

### Operating System

Ubuntu 20

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0

### Shell

Linux terminal

### Node version (run `node -v` if you're not sure)

v17.9.0

### What language and version are you using in your application?

node 17

**Comment by isaacroldan** [comment]
Hi @Sky-bits , not sure I understand your issue. When you run `npm run deploy` and it completes successfully, you should see a `.env` file containing all extensions UUIDs. Is that what you need? if not, could you please elaborate on your issue? :)

**Comment by isaacroldan** [comment]
Hi @Sky-bits!

Some clarifications:
- `app env show` or `app env pull` won't show extension UUIDs, only app IDs
- There is only one `.env` file, the root one. This file is updated after a successful `npm run deploy`
- In this `.env` file at the root you should see a line like `SHOPIFY_{your-extension-name}_ID={uuid}` this is the UUID of your just deployed extension.

Is your root `.env` updated? what do you see in it?

**Comment by Sky-bits** [comment]
@isaacroldan  I dont see the any shopify_  related to the UUID,

May be i think RUBY version issue ? let me try with RUBY version updates.

**Comment by Sky-bits** [comment]
@isaacroldan  Thanks for the help.  ruby version may be issue.

It was working fine Thanks for the help.
