### ISSUE TITLE
npm run dev issue !

### ISSUE THREAD

**Issue by soufianekharbouch** [Shopify/cli#2405]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension, Function

### Expected behavior

Hi , how can i keep the CLI Command "npm run dev" running, becouse once i close the connection ,  my app get off and lose the tunnel connection!
my app its created with a frontpage to edit my extension "Product discount"

### Actual behavior

once i close the connection ,  my app get off and lose the tunnel connection!

### Verbose output

```shell
no verbose
```

### Reproduction steps

1.npm run shopify app generate extension 
2.npm run deploy
3.npm run dev 

### Operating System

Ubuntu 20

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.47

### Shell

Cy

### Node version (run `node -v` if you're not sure)

V18

### What language and version are you using in your application?

Node

**Comment by alvaro-shopify** [comment]
Hi @soufianekharbouch, thanks for you question. In case you need the app to be active permanently, you should deploy it to your preferred hosting provider. Please, check this [documentation](https://shopify.dev/docs/apps/deployment/web) for more information

**Comment by soufianekharbouch** [comment]
Thank you @alvaro-shopify , solved
