### ISSUE TITLE
[Bug]: Apps generated by CLI can not call mutation mutation paymentsAppConfigure

### ISSUE THREAD

**Issue by RexClever** [Shopify/cli#2412]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I have a [Payment App](https://apps.shopify.com/cleverpay), these are my config files:

.env 
`SCOPES=write_payment_sessions,write_payment_gateways`

**Api version:**
Graphql 2022-01

My app was published and installed by serveral stores from Shopify.
Suddenly, on 12th June I received an issue can install our app without any code changes.

As I debugged, the problem came from the mutation paymentsAppConfigure

### Actual behavior

After connected Payment Gateway with our Shopify app, the app call the mutation paymentsAppConfigure to configures the payments gateway to work on the merchant's store.

Response:
`Access denied for paymentsAppConfigure field. Required access: write_payment_gateways access scope.`

### Verbose output

```shell
.
```

### Reproduction steps

You can follow this step in the link below:
https://docs.helloclever.co/docs/shopify-start

### Operating System

Ubuntu 20.04.4 LTS

### Shopify CLI version (check your project's `package.json` if you're not sure)

2.0

### Node version (run `node -v` if you're not sure)

v16.14.0

### What language and version are you using in your application?

Javascript

**Comment by luyx2412** [comment]
Same issue

**Comment by alvaro-shopify** [comment]
Hi @luyx2412 @vynguyen0205 , thanks for marking this issue as relevant. Please, could you provide us some information about your app or store/s reporting the problem?, that way we could track the requests trying to find out the source of the problem.
Thanks in advance

**Comment by luyx2412** [comment]
Hi, @alvaro-shopify Same app as @RexClever.

**Comment by alvaro-shopify** [comment]
Hi. I have contacted the `payments team` and they have checked that the app installation on the store `Cleverpay dev store` only includes the permission `write_products`. 
On the other hand, I have tried to install the app on my dev store form the store [url](https://apps.shopify.com/cleverpay) and once it was installed I checked the scopes and all of them are included
```
- write_payment_sessions
- write_payment_gateways
- write_checkouts
- write_products
```

- could you try to install the app again in one store from scratch to check if it's working as expected?
-did you install the app in the `Cleverpay dev store`  using the CLI?, in that case, please notice that you should include the desired scopes in the `shopify.app.toml`, more info [here](https://shopify.dev/docs/apps/tools/cli/structure#root-configuration-file) 

Please, let me know if some of these points works for you.

**Comment by RexClever** [comment]
Hi @alvaro-shopify , i've created a [new store](https://rex-test-17-july.myshopify.com/), and reinstalled it's works. you can check the scope of my new store.

But when tried reinstall our App with some old stores i still got same error.
- https://test-payment-store-119.myshopify.com
- https://rex-testing-store.myshopify.com

**Comment by matteodepalo** [comment]
We see no evidence that the apps are being installed with incorrect scopes. As @alvaro-shopify said, this issues happen when scopes change but old stores haven't gone through the installation process again so they aren't getting the new scopes. Could you try going through the flow again?
