### ISSUE TITLE
[Bug]: Get ETIMEDOUT when running npm run dev

### ISSUE THREAD

**Issue by jeffey3** [Shopify/cli#2447]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Run 'npm run dev ' in Shopify App folder, CLI will redirect to Shopify Partner Login Page, then CLI will login successfully and let you review the local app.

### Actual behavior

request to https://accounts.shopify.com/oauth/token?grant_type=authorization_code&code=MUt2a1JndzNUTDFVVFNOWDFpMkU4eGtpbFhxZFRsT25kM0pNelE  │
│  HR0Q255WDF5RmpFY05uYStqME1NTnNraEVzL1YvYXMrenIyUHVNSkJnNDdKQXJtc2hrOTZnRytrNGFTNWRvNmVTelNmN0hyWjFEWGxwOTBQdzdhL3l2MzRqOWk1TmlBYXhDUkhQL0N  │
│  6WUxYbk1talExbk9NWXZVdlZ0NmxRZ0pIZ0h3dHQrRGxOeStqOGdlMmRGdlhkTDJaWmlBUElBQmtZVmQ2MXdsZlNSNmx5cVN5NEI5T0FDS2twdkZ3PT0tLXBUS2F5RXZDcDVsalMwQ  │
│  UYtLTZXU2dFczFZRmQwSkYrSWNWRTFPVWc9PQ&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&code_verif  │
│  ier=sgykylHL6oyz38qB8mfwm683b2SfAju7PvobNTN-w4g failed, reason: connect ETIMEDOUT 185.146.173.20:443 

### Verbose output

```shell
npm run dev --loglevel verbose
npm verb cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@9.5.1
npm info using node@v18.16.1
npm verb title npm run dev
npm verb argv "run" "dev" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-07-14T22_33_20_341Z-
npm verb logfile C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-07-14T22_33_20_341Z-debug-0.log

> jeff-project@1.0.0 dev
> shopify app dev


To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser

Auto-open timed out. Open the login page: Log in to Shopify Partners ( http://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&state=b551f8175d1afa96d9c78d8cfadad0ddc7ce8ee67c591383785d69045c14&response_type=code&code_challenge_method=S256&code_challenge=QjxInw2eoQy90ajrPesOwue8GIi6GdJj0b2rO8mfHxo )

╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                              │
│  request to https://accounts.shopify.com/oauth/token?grant_type=authorization_code&code=MUt2a1JndzNUTDFVVFNOWDFpMkU4eGtpbFhxZFRsT25kM0pNelE  │
│  3V29PR1BFTG9ST3pxYW1nZEMxZCs0RWJveDJuTDJaUlcybGtqOXYwUmVHWEt0c0VNbEsyNEVid0tUQVlrQnBtRXVISkhEQ0pVZ2hjY2ZOK1BXTExiaGdxR1BsNWdRWG4ycHZMWGd0Z  │
│  HR0Q255WDF5RmpFY05uYStqME1NTnNraEVzL1YvYXMrenIyUHVNSkJnNDdKQXJtc2hrOTZnRytrNGFTNWRvNmVTelNmN0hyWjFEWGxwOTBQdzdhL3l2MzRqOWk1TmlBYXhDUkhQL0N  │
│  6WUxYbk1talExbk9NWXZVdlZ0NmxRZ0pIZ0h3dHQrRGxOeStqOGdlMmRGdlhkTDJaWmlBUElBQmtZVmQ2MXdsZlNSNmx5cVN5NEI5T0FDS2twdkZ3PT0tLXBUS2F5RXZDcDVsalMwQ  │
│  UYtLTZXU2dFczFZRmQwSkYrSWNWRTFPVWc9PQ&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&code_verif  │
│  ier=sgykylHL6oyz38qB8mfwm683b2SfAju7PvobNTN-w4g failed, reason: connect ETIMEDOUT 185.146.173.20:443                                        │
│                                                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

npm verb exit 1
npm verb code 1
```

### Reproduction steps

1. Jump into Shopify APP folder
2. Run 'npm run dev'
3. Input Shopify Partner account info
4. Got the error message in CLI command

----------
Tried below solution mentioned in #703 #2234 #1658 #1666  but not works

1. Using Clash as VPN and set as global mode
2. Change different VPN nodes in Clash
3. Using Proxifier and redirect all local app traffic to Clash
4. Using 'setx https_proxy' and 'setx http_proxy' to set system proxy
5. Using 'npm config set https-proxy' and  'npm config set http-proxy'  to set npm proxy
6. Using command 'npm cache clear --force' to refresh npm cache
7. Using command ' npm run shopify auth logout' to logout

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.47.5

### Shell

Powershell

### Node version (run `node -v` if you're not sure)

18.16.1

### What language and version are you using in your application?

N/A

**Comment by amcaplan** [comment]
@jeffey3 have you tried setting the env variable `SHOPIFY_CLI_DEVICE_AUTH=1` as mentioned [here](https://github.com/Shopify/cli/issues/2234#issuecomment-1620077869)?

**Comment by rainbowvs** [comment]
I have the same problem.
I have tried setting `SHOPIFY_CLI_DEVICE_AUTH=1`, but still have this problem

**Comment by Katherinaxxx** [comment]
Me too, can not fix this.

> I have the same problem. I have tried setting `SHOPIFY_CLI_DEVICE_AUTH=1`, but still have this problem
