### ISSUE TITLE
Product Discount Extension Not Showing

### ISSUE THREAD

**Issue by soufianekharbouch** [Shopify/cli#2491]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension, Function

### Expected behavior

Hi , I create a new app using CLI npm init @shopify/app@latest
Then I create a product discount extension : npm run shopify app generate extension 
Then i deply the extension and select my partner account  and install the app in test dev store "npm run dev" and "npm run deploy"
Then i select the distibution "custom app" and install the app in client store (shopify plan).

### Actual behavior

when i press "Create discount" in "Discount section" of shopify  in my dev store i see my extension at the bottom 
![image](https://github.com/Shopify/cli/assets/65112966/e5b18202-568d-4285-a081-70ceab01358c)
this Image its from my dev store, but in client store i can't see my product discount extension !
i try diff stores with diff apps but always same probleme ... can't see 
I have already try that and its work for a store but it was a shopify plus store 

### Verbose output

```shell
nothing to mentionned
```

### Reproduction steps

npm init @shopify/app@latest
npm run shopify app generate extension
"npm run dev" and "npm run deploy"

### Operating System

Ubuntu 20

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.47

### Shell

Cy

### Node version (run `node -v` if you're not sure)

V18

### What language and version are you using in your application?

Node

**Comment by amcaplan** [comment]
Hi @soufianekharbouch, thanks for getting in touch! I've verified the behavior and have forwarded this issue to the appropriate team to hear their response.

**Comment by soufianekharbouch** [comment]
> Hi @soufianekharbouch, thanks for getting in touch! I've verified the behavior and have forwarded this issue to the appropriate team to hear their response.

Thank you Caplan, really i am blocked 2 weeks with this problem , hope really get a solution

**Comment by amcaplan** [comment]
Hi @soufianekharbouch, are you working on a regular or Plus store? Functions are only available in custom apps for Plus stores, as documented in the [functions overview page](https://shopify.dev/docs/apps/functions).

**Comment by amcaplan** [comment]
@soufianekharbouch I'm not sure what I can offer you here, but I'd recommend contacting support at this point.

Closing as the CLI and platform are working correctly.
