### ISSUE TITLE
[Bug]: Installed new create app can't start dev

### ISSUE THREAD

**Issue by kuipou** [Shopify/cli#25]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The dev server should have started per the instructions stated in the instructions 
```
📁~/site/shopify ➜ yarn create @shopify/app
yarn create v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@shopify/create-app@3.0.24" with binaries:
      - create-app

Welcome. Let’s get started by naming your app. You can change it later.
✔ Your app's name? · test-cli3
✔ Which template would you like to use? · node
✔ Template downloaded
✔ App initialized
  ✔ Liquid parsed
  ✔ Updated package.json
✔ Dependencies installed with yarn
  ✔ Installed dependencies in /
  ✔ Installed dependencies in /web/
  ✔ Installed dependencies in /web/frontend/
✔ Completed clean up
✔ Git repository initialized

  test-cli3 is ready for you to build! Remember to cd test-cli3
  To preview your project, run yarn dev
  To add extensions, run yarn scaffold extension
  For more details on all that you can build, see the docs: shopify.dev (​https://shopify.dev​) ✨

  For help and a list of commands, enter yarn shopify app --help

Done in 107.02s.
```

### Actual behavior

Dev server failed to start
```
 📁test-cli3 ⬢ v16.13.0 took 6s ➜ yarn dev
yarn run v1.22.17
$ shopify app dev
✔ Dependencies installed

━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    libsecret-1.so.0: cannot open shared object file: No such file or directory

    Stack trace:    at node         node:internal/modules/cjs/loader:1183

    at load         node:internal/modules/cjs/loader:981
    at _load        node:internal/modules/cjs/loader:822
    at require      node:internal/modules/cjs/loader:1005
    at require      node:internal/modules/cjs/helpers:102
    at <anonymous>  keytar/lib/keytar.js:1                 var keytar = require('../build/Release/keytar.node')
    at _compile     node:internal/modules/cjs/loader:1101
    at js           node:internal/modules/cjs/loader:1153
    at load         node:internal/modules/cjs/loader:981
    at _load        node:internal/modules/cjs/loader:822

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Stack trace

```shell
━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    libsecret-1.so.0: cannot open shared object file: No such file or directory

    Stack trace:    at node         node:internal/modules/cjs/loader:1183

    at load         node:internal/modules/cjs/loader:981
    at _load        node:internal/modules/cjs/loader:822
    at require      node:internal/modules/cjs/loader:1005
    at require      node:internal/modules/cjs/helpers:102
    at <anonymous>  keytar/lib/keytar.js:1                 var keytar = require('../build/Release/keytar.node')
    at _compile     node:internal/modules/cjs/loader:1101
    at js           node:internal/modules/cjs/loader:1153
    at load         node:internal/modules/cjs/loader:981
    at _load        node:internal/modules/cjs/loader:822

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Reproduction steps

1. yarn create @shopify/app
2. cd test-cli3
3. yarn dev

### Operating System

Windows Linux Subsystem Ubuntu 20.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0.24

### Shell

zsh

### Node version (run `node -v` if you're not sure)

16.13.0

### What language and version are you using in your application?

Node 16.13.0

**Comment by gonzaloriestra** [comment]
Thanks for creating the issue! We are working on it, sorry for the inconvenience.

**Comment by jeannly** [comment]
Hey @gonzaloriestra. I think this might be related, although it's not a direct issue with Shopify's CLI. Just commenting this here for awareness.
I also couldn't start the dev build from a newly created app. Steps were exactly the same, except using npm. 

This issue happened because npm gave me precompiled node addons, even though they didn't match my machine's architecture. In particular, keytar and sqlite3 were giving me `x86` binaries instead of `arm` ones. 

I'm running macOS v12.3.1/Monterey with the new Apple silicon (M1), and as usual this is the root cause..

## Error 1: `npm run dev` fails

```
━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    dlopen(~/test-cli3/node_modules/keytar/build/Release/keytar.node, 0x0001): tried: '~/test-cli3/node_modules/keytar/build/Release/keytar.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

    Stack trace:    at node         node:internal/modules/cjs/loader:1196
    at load         node:internal/modules/cjs/loader:988
    at _load        node:internal/modules/cjs/loader:834
    at require      node:internal/modules/cjs/loader:1012
    at require      node:internal/modules/cjs/helpers:102
    at <anonymous>  keytar/lib/keytar.js:1                 var keytar = require('../build/Release/keytar.node')
    at _compile     node:internal/modules/cjs/loader:1112
    at js           node:internal/modules/cjs/loader:1166
    at load         node:internal/modules/cjs/loader:988
    at _load        node:internal/modules/cjs/loader:834

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

## Workaround - recompile keytar
From the initialised app directory:
1. Make sure [node-gyp](https://github.com/nodejs/node-gyp) is installed
1. `cd node_modules/keytar`
2. `node-gyp configure --arch=<target architecture here>`
    - For M1 chips, `node-gyp configure --arch=arm64`
3. `node-gyp build`

`npm run dev` should work after this.

## Error 2: Node server crashes immediately on deployment
```
backend    | node:internal/modules/cjs/loader:946
backend    |   const err = new Error(message);
backend    |               ^
backend    | 
backend    | Error: Cannot find module '~/test-cli3/web/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
```

## Workaround - recompile sqlite3
From the initialised app directory:
1. Make sure [node-pre-gyp](https://github.com/mapbox/node-pre-gyp) is installed (sqlite3's build process depends on node-pre-gyp rather than node-gyp)
2. `cd web/node_modules/sqlite3`
3. `node-pre-gyp configure --arch=<target architecture here>`
    - For M1 chips, `node-pre-gyp configure --arch=arm64`
4. `node-pre-gyp build`

After those steps everything was fine.

**Comment by stevejboyer** [comment]
Thanks @jeannly for your comment. I ran into the same issue running npm on MacOS Monterey 12.2, zsh, node 16.15.0.

In my case I was able to get `npm run dev` to work after just the first workaround, re-building keytar in arm64 architecture.
I did not need to recompile sqlite3.

**Comment by gonzaloriestra** [comment]
As a workaround for linux users, installing `libsecret` should solve this issue:

- Debian/Ubuntu: `sudo apt-get install libsecret-1-dev`
- Red Hat-based: `sudo yum install libsecret-devel`
- Arch Linux: `sudo pacman -S libsecret`

`gnome-keyring` is also required.
