### ISSUE TITLE
[Feature]: Add flag to delete unused assets on theme push

### ISSUE THREAD

**Issue by MagnusFischer** [Shopify/cli#2500]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Maybe there is a good reason why this doesn't exists, but how come assets that no longer exists in my local files are not being deleted on the remote when running `shopify theme push`?

With that said, perhaps it would be a good idea to create a new flag that makes it so assets are being deleted? 
Perhaps `--delete` (would essentially be the opposite of `--nodelete`)

### Motivation

I was having an issue that I spent a lot of time on, just to find out that the error was caused by a legacy asset file that was no longer used (that only existed on the remote). Therefore my dev env worked fine, but production didn't. I assume webpack was trying to load this asset even though it wasn't used anymore.

With that being said, I don't really see the point in not having the option for the CLI to remove assets that no longer exists in the changes I'm pushing.

**Comment by matteodepalo** [comment]
@Shopify/theme-code-tools
