### ISSUE TITLE
[Bug]: Logging in to customer account throws 400 error : "expected String to be a Hash: customer"

### ISSUE THREAD

**Issue by nboliver-ventureweb** [Shopify/cli#2502]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Login should be successful. When logging in using the same theme from the Shopify URL, everything works as expected.

### Actual behavior

When logging in to the customer account using http://127.0.0.1:9292 a Shopify error page is shown. This **only** happens using the CLI preview URL, when using the Theme Access app with a [theme environment](https://shopify.dev/docs/themes/tools/cli/environments) set up with shopify.theme.toml. Not using the environment flag and logging in via partners account seems to work fine.

<img width="768" alt="image" src="https://github.com/Shopify/cli/assets/132302189/26e01670-e54b-4a57-9098-af0c46f8ecf7">

### Verbose output

```shell
N/A
```

### Reproduction steps

1. Set up store access with Theme Access app
2. Add a theme environment like this: 
```
[environments.dev]
theme = "123456789"
store = "my-store"
password  = "shptka_123456"
ignore = ["templates/*.json", "config/*.json", "locales/*.json"]
```
4. Run `shopify theme dev --environment dev`
5. Navigate to http://127.0.0.1:9292/account/login and attempt to log in
6. See following error: 
<img width="729" alt="image" src="https://github.com/Shopify/cli/assets/132302189/2f3c78b8-2b31-441e-91d4-76ec99dbb67c">

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

Current Shopify CLI version: 3.47.5

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.6.1

### What language and version are you using in your application?

N/A

**Comment by amcaplan** [comment]
@nboliver-ventureweb thanks for getting in touch! You can't log in via the login button when previewing locally; instead you need to use the store password.

Please confirm this solves your difficulty.

**Comment by karreiro** [comment]
Thank you for reporting this, @nboliver-ventureweb!

Could you please confirm that this issue doesn't occur when you authenticate in the store without the `--password` flag? This information will help us in understanding the root cause of the issue.

Thanks again for reporting this!
