### ISSUE TITLE
[Bug]: Cannot create admin block/action

### ISSUE THREAD

**Issue by artyrcheek** [Shopify/cli#2539]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Following [these instructions](https://shopify.dev/docs/apps/admin/admin-actions-and-blocks/build-an-admin-action#step-2-create-a-new-extension) to create an admin action extension.
![CleanShot 2023-07-27 at 13 51 39@2x](https://github.com/Shopify/cli/assets/29695801/fc8172cc-62be-46bc-ab20-5547af8951d0)
Should have created a new extension

### Actual behavior

When I run
`shopify app generate extension --template admin_action --name issue-tracker-action --flavor react`
I get the error
`Expected --template=admin_action to be one of: vanilla-js, react, typescript, typescript-react, wasm, rust`
![CleanShot 2023-07-27 at 13 54 16](https://github.com/Shopify/cli/assets/29695801/17dc72d1-898e-41fd-922d-0c73f4ed2b73)

### Verbose output

```shell
> shopify app generate extension --template admin_action --name issue-tracker-action --flavor react --verbose

2023-07-27T12:54:46.001Z: Running command app generate extension
╭─ error ────────────────────────────────────────────────────────────────────────────╮
│                                                                                    │
│  Expected --template=admin_action to be one of: vanilla-js, react, typescript,     │
│  typescript-react, wasm, rust                                                      │
│  See more help with --help                                                         │
│                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────╯

2023-07-27T12:54:46.052Z: Unable to log analytics event - no information on executed command
```

### Reproduction steps

1. Run `npm run shopify app generate extension -- --template admin_action --name issue-tracker-action --flavor react --verbose`

### Operating System

Osx

### Shopify CLI version (check your project's `package.json` if you're not sure)

^3.48.0

### Shell

ITerm2

### Node version (run `node -v` if you're not sure)

v18.14.0

### What language and version are you using in your application?

ruby-3.1.2

**Comment by matteodepalo** [comment]
@artyrcheek there will be more than one package in package.json that needs to be updated. Typically there is `@shopify/cli` and `@shopify/app`. If the app package hasn't been updated you might see your error. I tried to reproduce, but couldn't with the latest version.
