### ISSUE TITLE
[Bug]: Build failed with digital ocean apps

### ISSUE THREAD

**Issue by hoannguyen02** [Shopify/cli#2545]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Build should work

### Actual behavior

![image](https://github.com/Shopify/cli/assets/16915274/6c06865d-f757-4b6e-b689-5b2cf267bb0e)

### Verbose output

```shell
$ NODE_ENV=production remix build
 info  building... (NODE_ENV=production)
 info  built (938ms)
✨  Done in 1.92s.
```

### Reproduction steps

1. Generate app
2. Deploy to Digital Ocean Apps
3. Encounter error

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

^3.48.0

### Shell

Vscode terminal

### Node version (run `node -v` if you're not sure)

v16.19.0

### What language and version are you using in your application?

Node v16.19.0

**Comment by Arkham** [comment]
Hi there, if you check the [Dockerfile](https://github.com/Shopify/shopify-app-template-remix/blob/main/Dockerfile) there's a comment that mentions how you might want to remove the line that removes the sqlite file.

**Comment by hoannguyen02** [comment]
> Hi there, if you check the [Dockerfile](https://github.com/Shopify/shopify-app-template-remix/blob/main/Dockerfile) there's a comment that mentions how you might want to remove the line that removes the sqlite file.

Thank you for fast response, let me remove and rebuild.

**Comment by Arkham** [comment]
Hey, can you try with this Dockerfile instead?
```
FROM node:18-alpine

EXPOSE 3000
WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

# You'll probably want to remove this in production, it's here to make it easier to test things!
RUN rm -f prisma/dev.sqlite
RUN npx prisma generate
RUN npx prisma migrate dev --name init

CMD ["npm", "run", "start"]
```

**Comment by hoannguyen02** [comment]
> Hey, can you try with this Dockerfile instead?
> 
> ```
> FROM node:18-alpine
> 
> EXPOSE 3000
> WORKDIR /app
> COPY . .
> 
> RUN npm install
> RUN npm run build
> 
> # You'll probably want to remove this in production, it's here to make it easier to test things!
> RUN rm -f prisma/dev.sqlite
> RUN npx prisma generate
> RUN npx prisma migrate dev --name init
> 
> CMD ["npm", "run", "start"]
> ```

let me try

**Comment by hoannguyen02** [comment]
> Hey, can you try with this Dockerfile instead?
> 
> ```
> FROM node:18-alpine
> 
> EXPOSE 3000
> WORKDIR /app
> COPY . .
> 
> RUN npm install
> RUN npm run build
> 
> # You'll probably want to remove this in production, it's here to make it easier to test things!
> RUN rm -f prisma/dev.sqlite
> RUN npx prisma generate
> RUN npx prisma migrate dev --name init
> 
> CMD ["npm", "run", "start"]
> ```



> > Hey, can you try with this Dockerfile instead?
> > ```
> > FROM node:18-alpine
> > 
> > EXPOSE 3000
> > WORKDIR /app
> > COPY . .
> > 
> > RUN npm install
> > RUN npm run build
> > 
> > # You'll probably want to remove this in production, it's here to make it easier to test things!
> > RUN rm -f prisma/dev.sqlite
> > RUN npx prisma generate
> > RUN npx prisma migrate dev --name init
> > 
> > CMD ["npm", "run", "start"]
> > ```
> 
> let me try

hi @Arkham it is same error, `Prisma Session table does not exist`
![image](https://github.com/Shopify/cli/assets/16915274/0bc73ce6-69ae-4997-a785-254bba582960)

**Comment by hoannguyen02** [comment]
Hi team, 

Still need a document/guide steps to deploy on digital ocean apps.

Thank you

**Comment by lgenter** [comment]
I'm also running into this issue (Prisma Session table does not exist) when deploying to a DO app. I was finally able to successfully deploy with the following configuration and after having pushed `dev.sqlite` to my repo, but this is far from ideal... Seconding the request for documentation on this.

`# RUN rm prisma/dev.sqlite
RUN npx prisma generate
RUN npx prisma migrate deploy`

**Comment by Siefke1** [comment]
I've had the same issue with a heroku deployment and managed to solve it by:

1. Deleting the failed migration from the DB
2. Had to change `"expires" DATETIME` to  `"expires" TIMESTAMP` in the `migration.sql` file
3. Adding this to the scripts in package json:
```
"prisma": "prisma",
"setup": "prisma generate && prisma migrate deploy",
```
4. Migrate manually by running `heroku run nom run setup` through heroku cli, there should be a possibility to do this in DA via and admin console as well i suppose.

Maybe this helps 🤞

**Comment by brdsmth** [comment]
> I've had the same issue with a heroku deployment and managed to solve it by:
> 
> 1. Deleting the failed migration from the DB
> 2. Had to change `"expires" DATETIME` to  `"expires" TIMESTAMP` in the `migration.sql` file
> 3. Adding this to the scripts in package json:
> 
> ```
> "prisma": "prisma",
> "setup": "prisma generate && prisma migrate deploy",
> ```
> 
> 4. Migrate manually by running `heroku run npm run setup` through heroku cli, there should be a possibility to do this in DA via and admin console as well i suppose.
> 
> Maybe this helps 🤞

Thank you, changing the `migration.sql` and running through the heroku cli fixed my issue 👍
