### ISSUE TITLE
Shopify CLI: npm run shopify app update-url command - prompt is filling the options with the wrong urls

### ISSUE THREAD

**Issue by japerez-sperantus** [Shopify/cli#2550]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

**The prompt should fill the options with the urls provided in the command.**

### Actual behavior

**The prompt fills the options with the urls listed in the App setup in Shopify Partners.** 

The point of using the `app-url `and `redirect-urls` flags is to create an alias for this long command:

`npm run shopify app update-url --app-url=https://$HOST/ --redirect-urls=https://$HOST/api/auth,https://$HOST/auth/callback,https://$HOST/auth/shopify/callback,https://$HOST/api/auth/callback`

I needn't my developers to manually enter each url in the prompt or in the App setup in Shopify Partners each time the ngrok url changes.

### Verbose output

```shell
/var/www/html # npm run shopify app update-url --app-url=https://da2c-2806-261-48a-8cab-cd4f-17d1-d280-48d7.ngrok-free.app/ --redirect-urls=https://da2c-2806-261-48a-8cab-cd4f-17d1-d280-48d7.ngrok-free.app/api/auth,https://
da2c-2806-261-48a-8cab-cd4f-17d1-d280-48d7.ngrok-free.app/auth/callback,https://da2c-2806-261-48a-8cab-cd4f-17d1-d280-48d7.ngrok-free.app/auth/shopify/callback,https://da2c-2806-261-48a-8cab-cd4f-17d1-d280-48d7.ngrok-free.a
pp/api/auth/callback

> dockerized-st-app@1.0.0 shopify
> shopify app update-url

?  Which existing app is this for?
✔  st-app

?  App URL:
>  https://26aa-2806-261-48a-8cab-cd4f-17d1-d280-48d7.ngrok-free.app/
   ▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔
```

### Reproduction steps

1. Run `npm run shopify app update-url --app-url=https://$HOST/ --redirect-urls=https://$HOST/api/auth,https://$HOST/auth/callback,https://$HOST/auth/shopify/callback,https://$HOST/api/auth/callback`  ($HOST must contain a url)
2. Try to change urls in prompt

### Operating System

alpine linux (Docker)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.47.5

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.17.0

### What language and version are you using in your application?

PHP 8.2.8

**Comment by Arkham** [comment]
Hi there, I think the issue is that npm scripts require a `--` between the command and the command options, so the right way to invoke that command is:
```
npm run shopify app update-url -- --app-url=https://$HOST/ --redirect-urls=https://$HOST/api/auth,https://$HOST/auth/callback,https://$HOST/auth/shopify/callback,https://$HOST/api/auth/callback
```

You can check here for the npm doc: https://docs.npmjs.com/cli/v9/commands/npm-run-script#description
