### ISSUE TITLE
[Bug]: custom fonts not loading on localhost

### ISSUE THREAD

**Issue by pietervandendungen** [Shopify/cli#2591]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

custom fonts that are present in the assets directory and loaded in the frontend to be served from the localhost (127.0.0.1(

### Actual behavior

On the local environment (127.0.0.1), custom fonts loading seems to result in a CORS-policy error because it's served from the Shopify CDN instead of the local url.

<img width="1439" alt="Screenshot 2023-08-02 at 14 09 18" src="https://github.com/Shopify/cli/assets/67514035/2bdcef06-9928-4b98-b883-c79487dfc15e">
<img width="666" alt="Screenshot 2023-08-02 at 14 14 58" src="https://github.com/Shopify/cli/assets/67514035/1dde303d-8a52-49e1-9ee9-c45b470d50b3">

### Reproduction steps

1. Add a custom font to your assets directory
2. Load the font with css (@font-face)
3. Apply the font-family on any element
4. Check your networks tab in browser dev-tools (in this example FireFox) and see the cors-policy error.

### Operating System

Mac OS Ventura (13.4.1)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.16.0

### What language and version are you using in your application?

Node 18.16.0

**Comment by lukecharle** [comment]
This is the same as #2663 ? Not just isolated to fonts. It seems its whenever using `asset_url`
