### ISSUE TITLE
[Bug]: What happened to the ruby template in v3.8.0

### ISSUE THREAD

**Issue by colinbrogan** [Shopify/cli#2600]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

If I run `npm init @shopify/app@latest'`, then the ruby template is no longer given as an option, only 'remix'. If I check package.json, I see that 'v3.8.0' is installed. If I run this instad `npm init @shopify/app@3.47.5`, rolling back only a single version, I get the ruby option as a template.

If this means you are about to deprecate the ruby template, shopify dev team must be determined to give me a headache. I've just gotten into building apps with cli 3.0 according to documentation, which makes no mention of deprecating ruby template. This would make me relearn everything once again. Please advise, and tell me that its still there in the newest version

### Actual behavior

No ruby template on v3.8.0

### Reproduction steps

1 .npm init @shopify/app@latest
2. No ruby template listed
3. npm init @shopify/app@3.47.5
4. Ruby template listed

### Operating System

Linux kernel 6.2.6-76060206-generic

### Shopify CLI version (check your project's `package.json` if you're not sure)

v3.8.0

### Node version (run `node -v` if you're not sure)

v18.17.0

**Comment by Arkham** [comment]
Hi @colinbrogan, I think you mean `3.48.0` and not `3.8.0`. That's correct, we now recommend using our new Remix template for building new Shopify apps. The advantages off the top of my head are:
- simpler authentication
- less redirects for merchants installing your app
- way easier to make graphql calls to the admin API
- a newer version of App bridge that makes building and debugging apps a much better experience

You can read more here: https://shopify.engineering/shopifys-platform-is-the-web-platform

That said, the apps you've built using the Ruby template will still work, so no need to panic. We just think that Remix is the way to go for the future.
