### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by bergstar** [Shopify/cli#2608]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

Installed according to documentation, but getting a syntax error running `shopify version`

### Actual behavior

```
~$ shopify version
file:///usr/local/lib/node_modules/@shopify/cli/node_modules/@shopify/cli-kit/dist/public/node/cli.js:11
        process.env.DEBUG = process.env.DEBUG ?? '*';
                                               ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

```

### Reproduction steps

1. sudo npm install -g @shopify/cli @shopify/theme
2. shopify version

### Operating System

Ubuntu 22.04.2 LTS

### Shopify CLI version (check your project's `package.json` if you're not sure)

can't get

### Shell

bash

### Node version (run `node -v` if you're not sure)

v12.22.9

### What language and version are you using in your application?

ruby 3.0.2p107

**Comment by Arkham** [comment]
hey @bergstar, the CLI [requires](https://shopify.dev/docs/apps/tools/cli#requirements) node 16 or higher to work. Once you update your node installation the error should go away 👍
