### ISSUE TITLE
[Bug]: '.js.liquid' files are not updated

### ISSUE THREAD

**Issue by BenGolan01** [Shopify/cli#2613]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

While working on the CLI, I encountered an issue where changes made to one of my '.js.liquid' files did not seem to reflect on the website. I have already verified that I am correctly logged in to the store, and I have conducted tests with other files like CSS and theme.liquid, which worked perfectly. Surprisingly, when I renamed the file from '.js.liquid' to just '.js', it started working as expected.

I should mention that I frequently work with '.js.liquid' files, and this is the first time I have experienced this problem. I suspect it might be due to a change in the URL from 'cdn...' to 'my-shop-name/assets/my-file'. Could you please check this possibility?

### Actual behavior

While working on the CLI, I encountered an issue where changes made to one of my '.js.liquid' files did not seem to reflect on the website. I have already verified that I am correctly logged in to the store, and I have conducted tests with other files like CSS and theme.liquid, which worked perfectly. Surprisingly, when I renamed the file from '.js.liquid' to just '.js', it started working as expected.

I should mention that I frequently work with '.js.liquid' files, and this is the first time I have experienced this problem. I suspect it might be due to a change in the URL from 'cdn...' to 'my-shop-name/assets/my-file'. Could you please check this possibility?

### Reproduction steps

1.
2.
3.

### Operating System

Mac Os

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.1

### Node version (run `node -v` if you're not sure)

v18.17.0

**Comment by gonzaloriestra** [comment]
Thanks for reporting! Let's continue in https://github.com/Shopify/cli/issues/2614, which seems to be the same issue.
