### ISSUE TITLE
[Feature]: Payment customization - Add/override text/styles payment option

### ISSUE THREAD

**Issue by hoannguyen02** [Shopify/cli#2615]
### What area(s) will this request affect?

Function

### What type of change do you want to see?

Substantial change to existing feature

### Overview

We need to add content for some payment options and highlight payment option that we are focusing so 

Can we provide an override text/styles(css) for payment options?

![image](https://github.com/Shopify/cli/assets/16915274/36e752e1-d01b-4d7e-8465-3e2ce6373495)

### Motivation

At the moment we don't  know how to add/override content for payment option and override style for payment option. Please help provide a solution. Thank you very much

**Comment by gonzaloriestra** [comment]
Hi! Thanks for the suggestion. I'm closing since this is not related to the CLI, but let me share it internally.

@nickwesselman could you please take care of this feature request?
