### ISSUE TITLE
[Bug]: Can't pass formData with multipart/form-data to proxy

### ISSUE THREAD

**Issue by javl** [Shopify/cli#2617]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

In my Theme app extension I have a form where the user can select a pdf from their computer. Selecting a file triggers a form-submit and sends the file to my server via the app proxy.

### Actual behavior

The (local development) server returns an error: `Internal server error:  the input of URI.decode_www_form must be ASCII only string `

This is caused by the [following line](https://github.com/Shopify/cli/blob/82d69806bee4beb675d7ef516d68ee7aa72941e3/packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb#L62)
`form_data = URI.decode_www_form(env["rack.input"].read).to_h`

This parses the form and uses a POST request to send it to the proxy server, but if your form data contains non-ascii characters (which it will likely do when uploading a PDF) this conversion fails.

Sending the data straight to the cloudflare url (without using prefix from the app settings) does succeed but will lead to other problems (CORS, need for hardcoded URL, etc)

### Reproduction steps

1. Create a new app with theme app extension
2. Create a form with eventhandler for triggering the upload after selecting a file

```html
  <form>
    <input type="file" name="file" id="fileUpload" />
  </form>
```

```javascript
   const input = document.querySelector('input[type="file"]')
    input.addEventListener('change', function (e) {
      submitForm(e);
    });

  function submitForm(e) {
    e.preventDefault();
    const files = document.getElementById("fileUpload");
    const formData = new FormData();
    formData.append("file", files.files[0]);
    fetch(`/prefix/app-name/upload`, {
        method: 'POST',
        body: formData,
        headers: {
          "Content-Type": "multipart/form-data",
       }
    })
```

### Operating System

Ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.16.0

### What language and version are you using in your application?

Node 18

**Comment by gonzaloriestra** [comment]
@Shopify/theme-code-tools could you please have a look?

**Comment by javl** [comment]
So I'm reopening this because I do think there is something going on.

I've used the (latest) cli tools to create an app, and then add an `app theme extension`.

In that extension, I have a receiving endpoint for an upload (`routes/upload.jsx`). For now the only content is this:
```node
import { json } from "@remix-run/node";
export const action = async ({ request }) => {
  return json({ message: "hello from upload.jsx" });
})
```
In the theme app extension I have a section with a simple form that I use to upload a small PDF file. After selecting the file I submit the file like so (below `mystore` is a placeholder for my actual app name, which I use in the proxy subpath) 

```javascript
    const formData = new FormData(form)
    fetch(`/apps/mystore/upload`, {
        method: 'POST',
        body: formData,
    })
```
As you can see in the image below, with the first line, this POST request fails. I get a 500 server error with the message "the input of URI.decode_www_form must be ASCII only string". Note I've disabled caching in the devtools.

1. Using the devtools 'resend' option, I retry and get the same result
2. Using the 'edit and resend' option I remove the payload from the body and resend (basically an empty POST request). This returns a 200
3. Using the 'resend' option I resend the original request (which has failed twice): this time it works with a 200
![image](https://github.com/Shopify/cli/assets/734644/e7809d64-7346-4d44-8d25-8d1e0e95c194)

Stopping and restarting the dev server with `npm run dev` (and updating the proxy url either in the partner dashboard or via the `.toml` file and pushing it on the commandline) doesn't seem to help.
Everything might work for a while and suddenly it stops, throwing that same 500 error even though nothing in my request was changed. 

Any suggestions as to what might be happening?

**Comment by iskurbanov** [comment]
Seem to be having an issue with this as well. I have two fetch requests both using FormData, one works but the other one errors out like described above.

**Comment by javl** [comment]
I feel like this mostly occurs when you have some other error in your code. 
In the process of throwing that error the server response is altered, which leads to the form error instead. Try commenting your code that reads from the form and replace it with some hardcoded data (so the server response doesn't matter) to see if any other error will appear.
