### ISSUE TITLE
[Bug]: <Running shopify theme package creates an empty zip file>

### ISSUE THREAD

**Issue by DrJulik** [Shopify/cli#2634]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The expected behavior is the command generating a complete theme package, ready to upload. Worked for me before on older versions (can't remember exact version).

### Actual behavior

The command generates empty zip file.
![Screenshot 2023-08-10 132527](https://github.com/Shopify/cli/assets/39019982/bf168fec-5457-450b-81b3-b068f76a68c5)

### Reproduction steps

1. Run shopify theme package
2. Zip is created
3. It is empty

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.1

### Shell

Command Prompt (also tried on GitBash)

### Node version (run `node -v` if you're not sure)

v18.17.0

**Comment by gonzaloriestra** [comment]
Hi! Thanks creating the issue. I've managed to reproduce it, it seems that it's only happening on Windows.

@Shopify/theme-code-tools could you have a look?

**Comment by DrJulik** [comment]
Anyone?
