### ISSUE TITLE
same isue <img width="588" alt="image" src="https://github.com/Shopify/cli/assets/28214740/a10439b2-5656-4bd4-b5b6-4acaaa5089bb">

### ISSUE THREAD

**Issue by looks-pk** [Shopify/cli#2640]
<img width="588" alt="image" src="https://github.com/Shopify/cli/assets/28214740/a10439b2-5656-4bd4-b5b6-4acaaa5089bb">
Facing Same issue.

This is my first Shopify experience. Any solutions are appreciated.

Tried logging out and logging in
Also tried making a new project

_Originally posted by @tiwarishikesh in https://github.com/Shopify/cli/issues/866#issuecomment-1656713656_

**Comment by matteodepalo** [comment]
Hi @looks-pk.
What's the CLI version you're using?

@Shopify/theme-code-tools
