### ISSUE TITLE
[Feature]: Add option to ignore 'unsupported' files during deployment

### ISSUE THREAD

**Issue by javl** [Shopify/cli#2646]
### What area(s) will this request affect?

Extension, Theme

### What type of change do you want to see?

New feature

### Overview

When trying to deploy my Theme app extension, I got the following error:

> Error: Invalid filename in your theme app extension: assets/<redacted>.ts
Only these filetypes are supported in assets: .jpg, .jpeg, .js, .css, .png, .svg

I understand you're only allowed to use the mentioned filetypes, but during development it makes sense to also have other files in the assets directory, like in the case of above error having a `.ts` version of my javascript file (from which I generate a `.js` file using a watcher). Same goes for `.scss` and `.css.map` files.

Currently there are three options:
1. Don't use Typescript/Sass: not really an option as they really help development
2. Keep the source files in a different directory: doable, but also a bit of a hassle. It makes sense to me to store these files in the `/extension` directory of the app. Having a `.scss` and a `.ts` file doesn't really warrant creating a separate `src` directory, which would have to be placed outside of the extension's directory to work, adding clutter.
3.  Remove all of the files before deploying: even more of a hassle.

What I would think would work best, is to have an option where this error is replaced with a warning, and the unsupported files are just ignored during deployment, building the final version of the app with only the files that _are_ supported.

### Motivation

![image](https://github.com/Shopify/cli/assets/734644/d6b5ef37-b344-4bd1-a54e-47e3594d5ec5)

**Comment by javl** [comment]
Just realized this request is similar to, but not the same as #1962, as the request is slightly wider.

**Comment by montalvomiguelo** [comment]
Hi @javl, have you tried ignoring files using a `.shopifyignore` file in your theme extension? We added it in #2097 (:

**Comment by javl** [comment]
@montalvomiguelo Oh wow, sorry, completely missed that! I still find it confusing how extensions are considered (part of) a theme + how the cli is a separate thing so I'm never sure where to look for settings like these.
 
Small sidenote: the [docs](https://shopify.dev/docs/themes/tools/cli#excluding-files-from-shopify-cli) say: 
> add them to a .shopifyignore at the root of the theme

It took me a few tries to find out this means that in a project with an theme app extension, the file shouldn't be in the main directory but you need to create the `.shopifyignore` file inside the `extensions/myextension` directory (so next to the asset directory). I guess for an theme app extension that counts as its root?

In case someone else needs this, I added 
```
assets/*.ts
assets/*.sh
assets/*.scss
assets/*.css.map
assets/*.json
```

```
project
| extensions
| | myextension
| | | .shopifyignore
| | | assets
| | | | style.scss 
| | | | style.css.map 
| | | | style.css 
```

Running `npm run shopify app deploy -- --no-release` confirms I don't get any errors anymore.
