### ISSUE TITLE
[Bug]: Don't fall back to online assets when previewing locally

### ISSUE THREAD

**Issue by javl** [Shopify/cli#2647]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension, Theme

### Expected behavior

When viewing a local development version of my app on localhost, I expect to only be served local files.

### Actual behavior

If I remove or rename a local asset, like `script.js`, I will be served an old, online, version of the asset, without any error or warning. I think this might be caused by some changes on files not triggering an update to the assets on the server.

### Reproduction steps

1. Create an app extension and have it load `script.js` from the assets directory via the schema
```
{% schema %}
{
   (...)
  "javascript": "script.js",
}
```
2. Edit `script.js` and add `console.log("TEST")`
3. Run `npm run dev`
4. Follow the editor link in the console and add Theme app extension to the page: console shows "TEST"
5. Visit `127.0.0.1:9292/`, console shows "TEST"
7. Rename `script.js` to `scriptjs` (remove dot)
8. Visit `127.0.0.1:9292/`, console still shows "TEST", even though `script.js` doesn't exist anymore.

### Operating System

Ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.16.0

**Comment by matteodepalo** [comment]
@Shopify/theme-code-tools
