### ISSUE TITLE
[Bug]: Cannot access api from web frontend

### ISSUE THREAD

**Issue by hoannguyen02** [Shopify/cli#2652]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I hope can access apis from web frontend such as`metafields`, `products`, etc

### Actual behavior

The error is `No shop provided`

### Reproduction steps

1. Go to `ProductCard` component, then change `/api/products/count` to `/api/products`
<img width="1306" alt="image" src="https://github.com/Shopify/cli/assets/16915274/0b989ee7-398b-494e-8fee-15cae70700df">
3. View app on shopify development store
4. See the error
<img width="998" alt="image" src="https://github.com/Shopify/cli/assets/16915274/4b48c4b6-4f7f-48da-a94f-5c442813a39b">

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

^3.48.0

### Shell

Vscode terminal

### Node version (run `node -v` if you're not sure)

v16.19.0

### What language and version are you using in your application?

Node v16.19.0

**Comment by isaacroldan** [comment]
Hi @hoannguyen02! This doesn't seem like a CLI issue, what template are you using? where is that code you are modifying?

**Comment by hoannguyen02** [comment]
Thanks for catch up @isaacroldan, actually I managed to resolved this issue by create custom app an interact with it.
