### ISSUE TITLE
After app scope update, update CLI warning to show the right command "npm run shopify app config"

### ISSUE THREAD

**Issue by codlp** [Shopify/cli#2655]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The CLI should say "Run `npm run shopify app config push` to push your scopes to the Partner Dashboard"

### Actual behavior

The CLI says "Run `shopify app config push` to push your scopes to the Partner Dashboard"

### Reproduction steps

1. Create an app with the official ruby Shopify app template (https://github.com/Shopify/shopify-app-template-ruby)
2. Update scopes in shopify.app.toml
3. In the terminal, run `npm run dev`
4. See the warning printed by the CLI

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.17.0

### What language and version are you using in your application?

Rails v7.0.3 and Ruby v3.1.2

**Comment by Arkham** [comment]
hey @codlp, thanks for reporting, I've fixed this and it's going to be released in the next stable :)

**Comment by michelarteta** [comment]
hello @Arkham was this fix implemented?

**Comment by WildernessStars** [comment]
> Config:push cli cmd not working.
> 
> Says i should use app deploy. But this does not change the app scope in the partner dashboard

same problem. i use app deploy but Scopes in Partner Dashboard:   • No scopes

**Comment by m20io** [comment]
I have the same issue. 
```
[build]
include_config_on_deploy = true
```
With this in the `shopify.app.toml` and `shopify app deploy` the scopes are not updating.

**Comment by wellenzhong** [comment]
> Sorry about that, turns out to be fixed in newer versions. `npm run shopify upgrade`

that works
