### ISSUE TITLE
Could not start tunnel, max retries reached

### ISSUE THREAD

**Issue by kristenzirkler** [Shopify/cli#2657]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

npm run dev should start a tunnel & start the dev server. Instead it gives an error. The previous issue https://github.com/Shopify/cli/issues/2170 was closed without resolution. The workaround to spin up a tunnel first & then use the tunnel-url with npm run dev works but I don't think is the expected workflow, if it is, it would be good for it to be documented in https://shopify.dev/docs/apps/getting-started/create.

### Actual behavior

│  Could not start Cloudflare tunnel, max retries reached.                                         │
│                                                                                                  │
│  What to try:                                                                                    │
│    • Run the command again                                                                       │
│    • Add the flag `--tunnel-url {URL}` to use a custom tunnel URL                                │
│                                                                                                  │
│  To investigate the issue, examine this stack trace:                                             │
│    at pollTunnelStatus (@shopify/app/src/cli/services/dev/urls.ts:107)                           │
│      if (result.status === 'error') return reject(new BugError(result.message,                   │
│      result.tryMessage))                                                                         │
│    at (@shopify/app/src/cli/services/dev/urls.ts:121)                                            │
│      pollTunnelStatus()                                                                          │
│    at new Promise                                                                                │
│    at pollTunnelURL (@shopify/app/src/cli/services/dev/urls.ts:102)                              │
│      return new Promise<string>((resolve, reject) => {                                           │
│    at generateFrontendURL (@shopify/app/src/cli/services/dev/urls.ts:90)                         │
│      const url = await pollTunnelURL(options.tunnelClient)                                       │
│    at dev (@shopify/app/src/cli/services/dev.ts:141)                                             │
│      generateFrontendURL({                                                                       │
│    at run (@shopify/app/src/cli/commands/app/dev.ts:111)                                         │
│      await dev({                                                                                 │
│                                                              

### Reproduction steps

1. Followed steps here: https://shopify.dev/docs/apps/tools/cli/existing
2. ran npm run dev -- --reset
3. get the above error

### Operating System

MacOS Ventura 13.4.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

20.3.0

### What language and version are you using in your application?

React

**Comment by matteodepalo** [comment]
Hi @kristenzirkler, thank you for reporting this. Cloudflare free tunnels should work in most setups but Cloudflare does put some limitations on the free tier that we leverage in the CLI, so it can happen that based on the personal setup it takes longer than expected to start a tunnel. I'd say that if the workaround works you should keep using that. You can even use ngrok if you find it more stable.

In any case, I've brought this up with the team and we'll keep tracking it internally.

**Comment by kristenzirkler** [comment]
> Hi @kristenzirkler, thank you for reporting this. Cloudflare free tunnels should work in most setups but Cloudflare does put some limitations on the free tier that we leverage in the CLI, so it can happen that based on the personal setup it takes longer than expected to start a tunnel. I'd say that if the workaround works you should keep using that. You can even use ngrok if you find it more stable.
> 
> In any case, I've brought this up with the team and we'll keep tracking it internally.

Actually the workaround is not working :/
https://docs.google.com/document/d/1D1Rxc1CpWMGRu81qg0d75_nfcIyGlcA2JCjtsbJEEm0/edit?usp=sharing
See verbose log

**Comment by matteodepalo** [comment]
@kristenzirkler I've checked the logs but I don't see the `--tunnel-url` flag being passed at any point. Have you tried doing that?

**Comment by ComicDansMS** [comment]
I'm also facing the problem of 'Could not start Cloudflare tunnel, max retries reached.'

While passing in --tunnel-url does get around this, it would be nice if we could resolve the original issue. I had been working on a project one night and all was fine, put the mac to sleep, and the next morning I was faced with this issue on the same project. I have tried it with a fresh install of the app template with the same result.
