### ISSUE TITLE
[Bug]: shopify theme share uploads files ignored in .shopifyignore

### ISSUE THREAD

**Issue by hsdonkin** [Shopify/cli#2664]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When uploading a theme via `shopify theme share`, files included in the `.shopifyignore` should not be uploaded

```
package.json
package-lock.json
node_modules
node_modules/
```

### Actual behavior

Ignored files are uploaded, and upload hangs due to number of files in `node_modules` 😅 
<img width="711" alt="image" src="https://github.com/Shopify/cli/assets/49598076/d0795dc0-2669-4e4a-87a7-d29e5be4eb49">

### Reproduction steps

1. Install any npm packages, i.e. `npm init && npm i preact`
2. Add `package.json` and `package-lock.json` and `node_modules` to `.shopifyignore`
3. `shopify theme share`

### Operating System

OSX 11.5.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.4.2

**Comment by johnphillipsdev** [comment]
Running into the same issue, moving the theme files into its own directory is helpless too as Shopify can't find them via subdirectories on the store connection.

**Comment by karreiro** [comment]
Thank you for reporting this issue, @hsdonkin. It's being solved by https://github.com/Shopify/cli/pull/4578.
