### ISSUE TITLE
[Bug]: shopify theme pull error

### ISSUE THREAD

**Issue by shawnsan-apollo** [Shopify/cli#2665]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When running `$ shopify theme pull -l --verbose` should pull live theme

### Actual behavior

I get the error - The option --development-theme-id is not supported.

```
➜  ******* shopify theme info
THEME CONFIGURATION                
Store                  ****.myshopify.com
Development Theme ID   #***theme-id***

TOOLING AND SYSTEM                 
Shopify CLI    3.48.2
OS             linux-amd64
Shell          /usr/bin/zsh
Node version   v19.6.0
Ruby version   3.2.2
➜  ******* shopify theme pull -l --verbose
2023-08-17T17:34:08.644Z: Running command theme pull
  shopify:theme:pull init version: @oclif/core@2.8.11 argv: [ '-l', '--verbose' ] +0ms
2023-08-17T17:34:08.672Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2023-08-17T17:34:08.672Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store ****.myshopify.com:
[]

2023-08-17T17:34:08.672Z: Getting session store...
2023-08-17T17:34:08.674Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "****.myshopify.com"
  }
}

2023-08-17T17:34:08.675Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2023-08-17T17:34:08.675Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.48.2
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2023-08-17T17:34:08.901Z: Request to https://accounts.shopify.com/oauth/introspection completed in 221 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"33afc8116bfb190ab7b49cf64aee7bb2"
 - x-request-id: c0b51e86-e622-41e0-b288-f95c61bcbbad
    
2023-08-17T17:34:08.903Z: The identity token is valid: true
2023-08-17T17:34:08.903Z: 
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false
  
2023-08-17T17:34:08.904Z: Getting development theme...
2023-08-17T17:34:09.264Z: Request to https://****.myshopify.com/admin/api/unstable/themes/***theme-id***.json?fields=id%2Cprocessing completed in 357 ms
With response headers:
 - content-type: application/json; charset=utf-8
 - x-request-id: cebb2fd6-996c-48d9-8004-4fcf0c3d8d58
    
2023-08-17T17:34:09.279Z: 
Running system process:
  · Command: ruby -v
  · Working directory: /home/shawn/****/*******

2023-08-17T17:34:10.407Z: 
Running system process:
  · Command: bundle -v
  · Working directory: /home/shawn/****/*******

2023-08-17T17:34:11.490Z: Creating directory at ../../.cache/shopify-cli-nodejs/vendor/ruby-cli/2.35.0...
2023-08-17T17:34:11.492Z: Reading the content of file at ../../.cache/shopify-cli-nodejs/vendor/ruby-cli/2.35.0/Gemfile...
2023-08-17T17:34:11.497Z: 
Running system process:
  · Command: bundle config set --local path /home/shawn/.cache/shopify-gems-nodejs
  · Working directory: /home/shawn/.cache/shopify-cli-nodejs/vendor/ruby-cli/2.35.0

2023-08-17T17:34:12.574Z: 
Running system process:
  · Command: bundle config set --local without development:test
  · Working directory: /home/shawn/.cache/shopify-cli-nodejs/vendor/ruby-cli/2.35.0

2023-08-17T17:34:13.642Z: 
Running system process:
  · Command: bundle install
  · Working directory: /home/shawn/.cache/shopify-cli-nodejs/vendor/ruby-cli/2.35.0

2023-08-17T17:34:14.801Z: 
Running system process:
  · Command: bundle exec shopify theme pull /home/shawn/****/******* --live --development-theme-id ***theme-id***
  · Working directory: /home/shawn/****/*******
```

### Reproduction steps

Run `$ shopify theme pull -l --verbose`

### Operating System

Windows 11 (WSL 2)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.2

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.6.0

### What language and version are you using in your application?

3.2.2

**Comment by isaacroldan** [comment]
Hi @shawnsan-apollo! Thanks for reporting this issue, unfortunately i'm not able to reproduce it :(
Is the verbose log complete? I don't see any error there, what happened after that last line?

**Comment by is4kov** [comment]
I have same issue, process is stuck after last command in the log.

**Comment by notkurt** [comment]
We've had the same issue on a new starters box, we were experiencing some issues getting the CLI setup initially and resorted to using SHOPIFY_CLI_BUNDLED_THEME_CLI set to true (#1425, [Shopify-3.38.0 Shopify Theme Dev --Store ERROR](https://community.shopify.com/c/technical-q-a/shopify-3-38-0-shopify-theme-dev-store-error/td-p/1925610))  . In the process of trying to resolve this issue we also downgraded to an older version of the CLI, however we still experienced issues. 

Removing SHOPIFY_CLI_BUNDLED_THEME_CLI = true in the environment resolved the issue.

**Comment by isaacroldan** [comment]
We are investigating this internally, hopefully we'll have a fix soon.

**Comment by karreiro** [comment]
👋 Hey everyone,

Thank you for reporting this issue and for providing such detailed information.

---

Please note that the `SHOPIFY_CLI_BUNDLED_THEME_CLI` should not be used. It's currently intended for debugging purposes only. However, if you find it absolutely necessary, kindly create a new issue detailing the specific scenario you're encountering without the `SHOPIFY_CLI_BUNDLED_THEME_CLI`. In this particular case, please open a new issue instead of commenting on an existing one.

We understand that migrations can take time, and to address this, we've created a PR to fix the following error:
```
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ The option --development-theme-id is not supported.                          
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

---

@jdlich, regarding the error you're experiencing when you unset `SHOPIFY_CLI_BUNDLED_THEME_CLI`:
```
<internal:/opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- ubygems (LoadError)
Did you mean?  rubygems
	from <internal:/opt/homebrew/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
```

It appears that your Ruby installation might be corrupted. I was able to artificially reproduce this issue by manually updating my Ruby installation, and subsequently resolved it with the following commands:
```
brew uninstall ruby --ignore-dependencies
brew install ruby
```

Thank you once again for bringing this to our attention.
