### ISSUE TITLE
[Feature]: Flag to Print cloudflare URL

### ISSUE THREAD

**Issue by abdulllrashid** [Shopify/cli#2668]
### What area(s) will this request affect?

App

### What type of change do you want to see?

New feature

### Overview

A flag that can be added with `npm run Shopify app dev` where it would print the current cloudflare tunnel URL. 

### Motivation

I'm hosting several additional APIs with Shopify App functionalities in the same node.js project. I need to expose this tunnel URL for my use case. Earlier it was possible with ngrok, but now when I migrated to the latest app version, I'm missing this feature.

**Comment by jana43** [comment]
process.env.HOST will give you the Cloudflare tunnel URL for shopify nodejs app.
