### ISSUE TITLE
[Bug]: The deployment failed when setting banner array choices

### ISSUE THREAD

**Issue by hoannguyen02** [Shopify/cli#2671]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

The build & deploy successfully

### Actual behavior

The build & deploy failed 

### Reproduction steps

1. Generate checkout ui extension
2. Setting banner status validation choices like bellow
![image](https://github.com/Shopify/cli/assets/16915274/05848cae-68e9-4f17-a5da-c7f343828854)
4. Deploy extension

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

^3.48.0

### Shell

Vscode terminal

### Node version (run `node -v` if you're not sure)

v16.19.0

### What language and version are you using in your application?

Node v16.19.0

**Comment by hoannguyen02** [comment]
> Hi! I believe the correct key for validations is `[[extensions.settings.fields.validations]]`, but I just saw it different in the docs. Please try with that key and i'll pass this info to the relevant team to review the docs. Thanks!

Hi @isaacroldan, thank you very much for the support.

By the way, could you give me the example of correct one. 
`
[[extensions.settings.fields.validations]]
name = "choices"
value = "[info', 'success', 'warning', 'critical']"
`

I am still getting error, this time is different one 
![image](https://github.com/Shopify/cli/assets/16915274/e5ea1c55-7244-49da-8723-ab2ce012d40c)

**Comment by hoannguyen02** [comment]
Thank you very much for the support

**Comment by isaacroldan** [comment]
Yep, that's the right syntax, glad is working now!
