### ISSUE TITLE
[Bug]: Simplified Deployment not updating active version on development store

### ISSUE THREAD

**Issue by mcunningham** [Shopify/cli#2672]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

I'm encountering an issue where the simplified deployment from CLI (v 3.48.3) is not propagating new active version changes to development stores. I have Development Store Preview toggled to **off** which was referenced as a solution [here](https://community.shopify.com/c/extensions/simplified-deployment-not-updating-extension/m-p/2166941/highlight/true#M727), but even with this toggled off I am still having issues.

For context, I'm developing a theme app extension (app embed block) that references a local `index.js` file within in `assets/index.js`
```liquid
{% schema %}
  {
    "name": "Test",
    "target": "body",
    "javascript": "index.js",
    "settings": []
  }
{% endschema %}
```

I'm then making changes to`index.js` locally and run `yarn deploy` to release a new version. I'm getting a confirmation from CLI that the new version was sucessfully released and the  partner dashboard shows the latest release is active. 

Expected behavior is that new active version changes will be propagated to my development store that has the theme app extension installed on page refresh. This is not the case.

### Actual behavior

Actual behavior is that when visiting my development store after the CLI release I still do not see the changes propagated and the active version is still on the previous release even after multiple page refreshes.

When I inspect the console I am also seeing the script tag being injected still with the old release number `https://cdn.shopify.com/extensions/{EMBED_ID}/appblock-embed-test-{OLD_VERSION_NUMBER}/assets/index.js`

One thing to note is that when I open development store in a new incognito window the correct version is showing properly, which makes me think this could be caching related. 

### Reproduction steps

1.  On partner dashboard for extension toggle Development Store Preview to **off**
2. Scaffold a new theme app extension with `Start by adding your first extension` option
3. Reference .js file in the theme app extension schema
5. Make changes locally to the .js file that is referenced
6. Deploy changes with `yarn deploy` and confirm Release a new version of ...? - Yes
7. Visit development store where changes should populate
8. Refresh page several times and see that changes did not populate

### Operating System

macOS Ventura 13.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.3

### Node version (run `node -v` if you're not sure)

v16.14.2

**Comment by isaacroldan** [comment]
Hi @mcunningham! thanks for reporting this issue, unfortunately i was not able to reproduce it :(
Deploying a new version with js changes works for me, after a couple minutes I can refresh my dev store and see the changes.

Maybe @Shopify/theme-code-tools can help here.
