### ISSUE TITLE
[Bug]: Flow is missing from Shopify Extensions Scaffold List on 3.8.2

### ISSUE THREAD

**Issue by keiraarts** [Shopify/cli#2673]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When selecting an extension type, "Flow Action" should be an available scaffold but is missing.

### Actual behavior

 It returns a list omitting the flow action and theme app extension
 
  Discounts and checkout
>  (1) Checkout UI
   (2) Function - Cart and Checkout Validation
   (3) Function - Cart transformer
   (4) Function - Delivery customization
   (5) Function - Order discount
   (6) Function - Payment customization
   (7) Function - Product discount
   (8) Function - Shipping discount
   (9) Post-purchase UI

   Point-of-Sale
   (10) POS UI

   Merchant admin
   (11) Subscription UI

   Analytics
   (12) Web Pixel

### Reproduction steps

1. yarn shopify app info

YOUR PROJECT                       
Name            NAME
Root location   NAME

DIRECTORY COMPONENTS               

web
📂 web

theme_external
📂 dawn-extensions   extensions/deployment
     config file     shopify.theme.extension.toml

ACCESS SCOPES IN ROOT TOML FILE    
write_products

TOOLING AND SYSTEM                 
Shopify CLI       ^3.48.3
Package manager   npm
OS                darwin-arm64
Shell             /bin/zsh
Node version      v17.6.0

yarn shopify version
Current Shopify CLI version: 3.48.3

yarn shopify app generate extension --type=FLOW --getting-started

error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Unknown extension type: FLOW.                                               │
│  The following extension types are supported: post_purchase_ui,              │
│  checkout_ui, pos_ui, subscription_ui, web_pixel, theme_app_extension,       │
│  cart_checkout_validation, cart_transform, delivery_customization,           │
│  order_discount, payment_customization, product_discount, shipping_discount  │
│                                                                              │

### Operating System

MacOS, Brew

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.8.2

### Node version (run `node -v` if you're not sure)

v18

### What language and version are you using in your application?

Node

**Comment by isaacroldan** [comment]
Hi @keiraarts, i'll be closing this issue since it's not a CLI bug, but feel free to ask any other question regarding how to upgrade or if you encounter any problem.
