### ISSUE TITLE
[Bug]: <Javascript function build error>

### ISSUE THREAD

**Issue by 0x-buidl** [Shopify/cli#2686]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Function

### Expected behavior

`npm exec -- shopify app function build` should build successfully. Was working earlier, suddenly stopped working.

### Actual behavior

```
Error coming from `npm exec -- javy compile -d -o extensions/product-discount/dist/function.wasm dist/function.js`
```

### Reproduction steps

1. `npm exec -- shopify app function build` in a typescript function directory

### Operating System

macOS Ventura 

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.2

### Shell

iterm2

### Node version (run `node -v` if you're not sure)

v19.0.0

### What language and version are you using in your application?

Typescript

**Comment by Jay-Plumb** [comment]
+1 - I thought this was an issue within the shopify function runner (https://github.com/Shopify/function-runner/issues/181). I also had no issues several hours ago but suddenly stopped working. Upgrading to `3.48.3` also made no difference.

**Comment by Jay-Plumb** [comment]
`npm exec -- shopify app function build` works okay on my end but running `cat input.json | npm run shopify app function run` no longer works since yesterday evening
