### ISSUE TITLE
[Bug]: Theme assets are not being updated

### ISSUE THREAD

**Issue by gabrielvincent** [Shopify/cli#2697]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Updated assets should replace their old version.

### Actual behavior

Asset files returned from Shopify CDN is not up to date. The only way I'm able to update a file is by manually changing it on the Admin's code editor.

### Reproduction steps

1. Change any file in `assets`, e.g.: add a new class, `.btn-background { background-color: blue; }` in `assets/style.css`
3. Make sure `assets/style.css` is not included in `.shopifyignore`
4. Push the changes using `shopify theme push`.
5. Refresh page on live site
6. Open inspector
7. Navigate to Network tab
8. Filter by `style.css`
9. Check source code of `style.css`
10. Verify that the asset file returned from `https://[YOUR_STORE]/cdn/shop/t/92/assets/style.css?v=152657644625106757401688035308` does not contain the newly added class `.btn-background`.

### Operating System

macOS Ventura 13.3

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.4

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18.16.0

**Comment by illarionvk** [comment]
We also see this issue in our projects intermittedly since Monday.
