### ISSUE TITLE
[Feature]: Add flag to make `theme push` idempotent

### ISSUE THREAD

**Issue by jeffreyguenther** [Shopify/cli#2699]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

Would it be possible to add a flag that makes `theme push` idempotent? 

Given a theme name, it would only create a single theme with that name. 

Right now, if the `--unpublished` flag is passed, it will create multiple themes with the same name. Without `--unpublished`, it will error if the theme isn't created.

What I'd like is the ability to run `theme push --theme jeff/feature-branch` multiple times and only have a single theme created.

### Motivation

To support PR reopening in a GitHub, we need the ability to push to a theme named after a branch multiple times and have only a single theme created.

In the pre-1.0 release of [Shopkeeper](https://github.com/TheBeyondGroup/shopkeeper/blob/6ec79c2df6500d7408fd1cb46c6a7c4d32d91e0e/src/cli/shopkeeper-theme-create.ts#L21-L30) I had to add a create command in order to make this possible.

I [walk through](https://github.com/TheBeyondGroup/shopkeeper/blob/jeff/add-ci-cd-to-walkthrough/docs/the_complete_guide.md#cicd-with-github-actions) how someone can use GitHub Actions to write workflows to provide a CI/CD experience for Shopify like you might have with other tools like Heroku or Vercel's branch previews.

**Comment by jeffreyguenther** [comment]
Not sure how to keep this open... The problem is a bit of a tricky one in terms of the existing command and flags. @isaacroldan do you have a sense of whether we should pursue a fix for this in the CLI or if I should continue to handle it with my plugin?

I'm happy to contribute a change, but would need guidance to align it with Shopify's vision.

**Comment by isaacroldan** [comment]
Hi @jeffreyguenther, thanks for the proposal. @karreiro or @mgmanzella would be better to answer you this question :)

**Comment by kenji-twp** [comment]
+1 This would be a great thing!

**Comment by kenji-twp** [comment]
Still relevant

**Comment by ascheucher-shopify-partner** [comment]
This issue ist still relevant and always should have been the default behavior.
