### ISSUE TITLE
[Feature]: Being able to see retrive shop access token in extension-only app

### ISSUE THREAD

**Issue by patjakubik** [Shopify/cli#2705]
### What area(s) will this request affect?

App

### What type of change do you want to see?

New feature

### Overview

Being able to retrieve access tokens from any store that has installed a custom app for things like enabling Web Pixel Extensions.

For example by running the command `shopify app access-token --shop snowdevil.myshopify.com`

Alternatively or additionally provide GraphiQL Playground in Developer Console

### Motivation

We have an extension-only app with UI Extensions and it was working pretty well, but now we would like to add Web Pixel Extension. The problem with those is that we need to [enable them using GraphQL API](https://shopify.dev/docs/apps/marketing/pixels/getting-started#step-5-create-a-web-pixel-setting-for-the-store) and we cannot do this without an access token, which extension-only app doesn't seem to provide.

**Comment by isaacroldan** [comment]
Hi @patryk-smc, unfortunately as of now Web Pixel extensions are not compatible with extensions-only apps. [This](https://shopify.dev/docs/apps/app-extensions/extension-only-apps) is the list of compatible extensions.

I'll pass the feedback to the appropriate teams both to support extensions-only apps and to include a way to generate tokens/run GraphQL queries.

**Comment by isaacroldan** [comment]
Thanks @patryk-smc, that's awesome. I passed this to the team and we are discussing possible future solutions to enable web-pixel with extension-only apps, can't provide more details yet though.

I'll close the issue for now, thanks for sharing your tool as a workaround!
