### ISSUE TITLE
[Bug]: Supply a different discount to each line item

### ISSUE THREAD

**Issue by Jay-Plumb** [Shopify/cli#2709]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Function

### Expected behavior

Noticed https://community.shopify.com/c/shopify-functions/shopify-functions-product-discount-api-multiple-discounts/td-p/1693369 but I think my case is more simple in that I just want to supply a different discount based on the quantity for each line item.

In other words, it should be possible to supply a different discount for each line item.

### Actual behavior

From a shopify store perspective, it does not work as intended:

<img width="1481" alt="Screenshot 2023-08-27 at 20 26 49" src="https://github.com/Shopify/cli/assets/12322743/37134f96-7137-49d3-a668-1ffd3dd8bf01">

<img width="1481" alt="Screenshot 2023-08-27 at 20 26 54" src="https://github.com/Shopify/cli/assets/12322743/9e0930a9-0df7-4346-8819-3e9575054cea">When using the script editor, we could easily add a unique discount per line item. I would like to achieve the same functionality using a Shopify function but it only ever applies the discount to the first line item. From a shopify function input/output perspective, it looks good:

STDIN:

```json
{
  "cart": {
    "lines": [
      {
        "quantity": 12,
        "cost": {
          "amountPerQuantity": {
            "amount": "749.95",
            "currencyCode": "GBP"
          }
        },
        "merchandise": {
          "__typename": "ProductVariant",
          "id": "gid://shopify/ProductVariant/46450105155872",
          "sku": "BEBS-C301",
          "product": {
            "id": "gid://shopify/Product/8593077960992"
          }
        }
      },
      {
        "quantity": 7,
        "cost": {
          "amountPerQuantity": {
            "amount": "2629.95",
            "currencyCode": "GBP"
          }
        },
        "merchandise": {
          "__typename": "ProductVariant",
          "id": "gid://shopify/ProductVariant/46450104795424",
          "sku": "BRBS-C301",
          "product": {
            "id": "gid://shopify/Product/8593077862688"
          }
        }
      }
    ]
  }
}
```

STDOUT:

```json
{
  "discounts": [
    {
      "message": "BULK:gid://shopify/ProductVariant/46450105155872:7",
      "targets": [
        {
          "productVariant": {
            "id": "gid://shopify/ProductVariant/46450105155872"
          }
        }
      ],
      "value": {
        "percentage": {
          "value": 7
        }
      }
    },
    {
      "message": "BULK:gid://shopify/ProductVariant/46450104795424:5",
      "targets": [
        {
          "productVariant": {
            "id": "gid://shopify/ProductVariant/46450104795424"
          }
        }
      ],
      "value": {
        "percentage": {
          "value": 5
        }
      }
    }
  ],
  "discountApplicationStrategy": "FIRST"
}
```

### Reproduction steps

1. Discount function which applies a unique discount per line item (in my case a qty of more than 5 adds a discount of 5% and a qty of more than 11 adds a discount of 7%)
2. Add two items with qty 6 and qty 12
3. Observe only first line item applying discount

### Operating System

mac (M1)

### Shopify CLI version (check your project's `package.json` if you're not sure)

 3.48.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.17

### What language and version are you using in your application?

Javascript

**Comment by amcaplan** [comment]
Closing as https://github.com/Shopify/function-examples/discussions/194 is the correct place for this conversation.
