### ISSUE TITLE
[Bug]: An unexpected error occurred.

### ISSUE THREAD

**Issue by jnetle** [Shopify/cli#2718]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

No errors occurring when running `npm run dev`. My extension appears in my theme.

### Actual behavior

An error occurs with not much of a stack track to debug. I can't see my extension in my theme.

``` 13:24:21 │ remix      │ 
13:24:21 │ remix      │  💿  remix dev
13:24:21 │ remix      │ 
13:24:21 │ extensions │ ✗ An unexpected error occurred.
13:24:21 │ extensions │ 	To ttps://github.com/Shopify/shopify-cli/issues/new?title=%5BBug%5D%3A+OpenSSL%3A%3ASSL%3A%3ASSLError%3A+SSL_connect+SYSCALL+returned%3D5+err
no%3D0+peeraddr%3D185.146.173.20%3A443+state%3Derror%3A+certificate+verify+failed&labels=type%3Abug&template=bug_report.yaml&stack_trace=%2Fusr%2Flocal%2FCellar%2Fru
by%2F3.2.2_1%2Flib%2Fruby%2F3.2.0%2Fnet%2Fprotocol.rb%3A46%3Ain+%60connect_nonblock%27%0A%2Fusr%2Flocal%2FCellar%2Fruby%2F3.2.2_1%2Flib%2Fruby%2F3.2.0%2Fnet%2Fprotoc
ol.rb%3A46%3Ain+%60ssl_socket_connect%27%0A%2Fusr%2Flocal%2FCellar%2Fruby%2F3.2.2_1%2Flib%2Fruby%2F3.2.0%2Fnet%2Fhttp.rb%3A1342%3Ain+%60connect%27%0A%2Fusr%2Flocal%2
FCellar%2Fruby%2F3.2.2_1%2Flib%2Fruby%2F3.2.0%2Fnet%2Fhttp.rb%3A1248%3Ain+%60do_start%27%0A%2Fusr%2Flocal%2FCellar%2Fruby%2F3.2.2_1%2Flib%2Fruby%2F3.2.0%2Fnet%2Fhttp
.rb%3A1237%3Ain+%60start%27&os=x86_64-darwin21&cli_version=3.48.4&ruby_version=3.2.2p53&shell=%2Fbin%2Fzshsubmit an issue;; include the stack trace.
13:24:21 │ extensions │ 
13:24:22 │ remix      │  info  building...
13:24:23 │ remix      │  info  built (1.1s)
13:24:23 │ remix      │ [shopify-api/INFO] version 7.5.2, environment Remix
13:24:24 │ remix      │ Remix App Server started at http://localhost:54448 (http://192.168.1.227:54448)
13:24:24 │ remix      │ 
```

### Reproduction steps

1. Went through the documentation to create a new app and extension. https://shopify.dev/docs/apps/getting-started/create
2. Run  `npm run dev`
3. Received error

### Operating System

macOS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.4

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.16.1

### What language and version are you using in your application?

javascript

**Comment by jnetle** [comment]
I don't believe my network is complex. I'm not behind a firewall. Looking into the error more online, it was suggested that ruby is trying to connect to rubygems and I'm missing openssl certificates. I troubleshooted following this: https://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check.

I'm still have issues. Not sure what else I can do. OpenSSL, ruby, rubygems, cert is all updated.

**Comment by amcaplan** [comment]
It seems like you're trying things in the right direction... Have you by any chance seen https://github.com/Shopify/shopify-cli/issues/1673#issuecomment-1026077210?

**Comment by jnetle** [comment]
I updated my ruby with rvm and that seemed to make the error go away. Previously, I was using homebrew to update it. I think we are good now. It's building and pushing my theme extension.
