### ISSUE TITLE
[shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline: true}

### ISSUE THREAD

**Issue by saikiruba-mj** [Shopify/cli#2726]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

I have created a theme app extension using node js with react. From the extension liquid file, I need to get the user input to update my data in the SQLite database via the REST API method.

However, I am not able to trigger that custom API method, getting a **Missing Authorization header error**. Can anyone let me know how to generate session data in order to resolve this issue? Currently, I am facing the below error when I trigger my custom app  API endpoint(like default qr-code example) in my Postman or from my development store.

```
[shopify-app/INFO] Running validateAuthenticatedSession
[shopify-app/INFO] Session was not valid. Redirecting to /api/auth?shop=[abc.myshopify.com](http://abc.myshopify.com/) | {shop: [abc.myshopify.com](http://abc.myshopify.com/)}
[shopify-api/ERROR] Missing Authorization header, was the request made with authenticatedFetch? | {isOnline:  true}
```

I have checked existing issues in issue tracker related to the scenario but none of the discussion have worked out for me. Excepted behaviour to generate the session token and pass to my custom API method.

Also, Can anyone let us know is there any example template with connecting the app and theme.

Thank you!

### Actual behavior

It didn't work

### Reproduction steps

1. Initiate the project file from npm init @shopify/app@3.47.5
2. Followed the QR code example for admin panel related code.
3. Write a custom app API like QR code example template.
4. Trigger the custom action to update the data and facing the mentioned issue.

### Operating System

Ubuntu 22.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.47.5

### Shell

bash

### Node version (run `node -v` if you're not sure)

18.16.0

### What language and version are you using in your application?

Node 18.16.0

**Comment by amcaplan** [comment]
Hi @saikiruba-mj, thanks for getting in touch!

`validateAuthenticatedSession` is meant for admin requests, but theme app extensions appear in the storefront, so that won't work.

Instead, you should look at using an [app proxy](https://shopify.dev/docs/apps/online-store/app-proxies) to have the theme app extension contact the backend.
