### ISSUE TITLE
[Bug]: Fonts from Shopify font library not loading from localhost

### ISSUE THREAD

**Issue by matedemorphy** [Shopify/cli#2807]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Theme

### Expected behavior

Fonts from the` Shopify font library ` should be loaded from a default remote host, https://fonts.shopifycdn.com perhaps.

### Actual behavior

Fonts from Shopify font library are being loaded from: http://127.0.0.1:9292/cdn/fonts/, of course that wont work, i'm getting `net::ERR_ABORTED 403 (Forbidden)
` in the console. [#2711](https://github.com/Shopify/cli/pull/2711) is supposed to be an approved fix for that bug, but at least for me it doesn't change anything.

### Reproduction steps

1. `git clone https://github.com/Shopify/dawn.git`
2. TailwindCSS instalation and basic configuration using Vite and PostCSS
3. in package.json

```
 "scripts": {
    "dev": "run-p -sr shopify:dev watch",
    "shopify:dev": "shopify theme dev -s peakseven --poll",
    "build": "vite build --minify",
    "watch": "vite build --watch"
  },
```
4. `npm run dev`

### Operating System

WSL2

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.1

### Shell

WSL2

### Node version (run `node -v` if you're not sure)

v16.16.0

### What language and version are you using in your application?

Ruby 3.2.0

**Comment by karreiro** [comment]
Hi @matedemorphy,

Thanks for reporting the issue. The problem has been resolved in [this pull request](https://github.com/Shopify/cli/pull/2796) and will be included in Shopify CLI's next patch, 3.49.3.
