### ISSUE TITLE
[Bug]:  Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by gregmaxin** [Shopify/cli#2809]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

When running `shopify app dev` it should run the application. 

### Actual behavior

The app does not run and instead outputs this error 

```

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

  ERROR  Cannot read properties of null (reading 'useContext')

 node_modules/@shopify/app/node_modules/react/cjs/react.development.js:1618:21

 - useContext (node_modules/@shopify/app/node_modules/react/cjs/react.development.js:1618:21)
 - useStdin (node_modules/@shopify/app/node_modules/ink/build/hooks/use-stdin.js:6:24)
 - Dev (node_modules/@shopify/app/dist/cli/services/dev/ui/components/Dev.js:14:53)
 - renderWithHooks (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:7478:18)
 - mountIndeterminateComponent (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:11247:13)
 - beginWork (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:12760:16)
 - beginWork$1 (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:19569:14)
 - performUnitOfWork (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18703:12)
 - workLoopSync (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18609:5)
 - renderRootSync (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18577:7)
```

### Reproduction steps

1. Install the lastest cli version (this bug appears on 3.49.X)
2. Simplified deployments is enabled 
3. Run `shopify app dev`

### Operating System

WSL 2 (Ubuntu 18). Chrome

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.2

### Node version (run `node -v` if you're not sure)

16.17.0

### What language and version are you using in your application?

Node 16

**Comment by ps-leocxy** [comment]
Ha, I have the same issue here. It just not working even the "sample" code are generated from the CLI.

**Comment by ps-leocxy** [comment]
@gregmaxin 

I figure it how. So here is the source codes
https://github.com/Shopify/example-checkout--custom-banner--react

1. Revmoed the "react", "@shopify/ui-extensions", and "@shopify/ui-extensions-react" from the root `package.json`
2. Downgrade the "@shopify/app" and "@shopify/cli" to "^3.48.0"
3. Added a `package.json` to the extension folder

**Comment by tommypepsi** [comment]
I'm getting the same error but upgrading to react 18 is not an option for me as we are using checkout extensions and the npm module for that require react 17:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=17.0.0 <18.0.0" from @shopify/ui-extensions-react@2023.7.0
npm ERR!   @shopify/ui-extensions-react@"2023.7.0" from the root project
```

My only option for now has been to downgrade to 3.48.*

**Comment by Arkham** [comment]
can you share some reproduction steps or a small repo for me to investigate?

**Comment by tommypepsi** [comment]
A minimal way to replicate my current environment:
- npm init @shopify/app@latest -- --template php
- install composer dependencies in /web
- install npm dependencies in /web/frontend
- npm run dev (this more or less works, there seems to be an issue with the template that gives a 500 error on the dashboard but the cli and server are running correctly without the error mentioned here)

Then to replicate the error:
- npm run shopify app generate extension
- select "Checkout UI"
- Javascript React
- npm run dev (this gets the error mentioned here)

Seems that creating a checkout extension installs react 17 in the root of the project which doesn't seem to be playing well with shopify CLI 3.49.2.

**Comment by matteodepalo** [comment]
We have some special behavior for npm only that adds `react` as a dependency at the top level when we generate UI extensions. Could you try removing `"react": "^17.0.2"` from the top level package.json, removing package-lock.json and node_modules and reinstalling?

**Comment by WilliamChongSDG** [comment]
@Arkham This doesn't work.

After updating and performing all steps above, running `npm run dev` generated a new error:

```
TypeError: Cannot read properties of undefined (reading 'isBatchingLegacy')
    at ensureRootIsScheduled (C:\wamp64\www\xxx\node_modules\ink\node_modules\react-reconciler\cjs\react-reconciler.development.js:17731:35)
    at scheduleUpdateOnFiber (C:\wamp64\www\xxx\node_modules\ink\node_modules\react-reconciler\cjs\react-reconciler.development.js:17636:5)
    at Object.updateContainer (C:\wamp64\www\xxx\node_modules\ink\node_modules\react-reconciler\cjs\react-reconciler.development.js:21022:5)
    at Ink.render (file:///C:/wamp64/www/xxx/node_modules/ink/build/ink.js:226:20)
    at render (file:///C:/wamp64/www/xxx/node_modules/ink/build/render.js:19:14)
    at renderString (file:///C:/wamp64/www/xxx/node_modules/@shopify/cli-kit/dist/private/node/ui.js:39:22)
    at renderOnce (file:///C:/wamp64/www/xxx/node_modules/@shopify/cli-kit/dist/private/node/ui.js:7:33)
    at renderFatalError (file:///C:/wamp64/www/xxx/node_modules/@shopify/cli-kit/dist/public/node/ui.js:207:12)
    at handler (file:///C:/wamp64/www/xxx/node_modules/@shopify/cli-kit/dist/public/node/error.js:113:5)
    at file:///C:/wamp64/www/xxx/node_modules/@shopify/cli-kit/dist/public/node/error-handler.js:27:20
C:\wamp64\www\xxx\node_modules\ink\node_modules\react-reconciler\cjs\react-reconciler.development.js:17731
      if ( ReactCurrentActQueue$1.isBatchingLegacy !== null) {
                                  ^

TypeError: Cannot read properties of undefined (reading 'isBatchingLegacy')
    at ensureRootIsScheduled (C:\wamp64\www\xxx\node_modules\ink\node_modules\react-reconciler\cjs\react-reconciler.development.js:17731:35)
    at scheduleUpdateOnFiber (C:\wamp64\www\xxx\node_modules\ink\node_modules\react-reconciler\cjs\react-reconciler.development.js:17636:5)
    at Object.updateContainer (C:\wamp64\www\xxx\node_modules\ink\node_modules\react-reconciler\cjs\react-reconciler.development.js:21022:5)
    at Ink.unmount (file:///C:/wamp64/www/xxx/node_modules/ink/build/ink.js:284:20)
    at EventEmitter.emit (node:events:526:35)
    at EventEmitter.emit (node:domain:489:12)
    at emit (C:\wamp64\www\xxx\node_modules\signal-exit\index.js:105:13)
    at process.processEmit [as emit] (C:\wamp64\www\xxx\node_modules\signal-exit\index.js:193:7)
    at process.exit (node:internal/process/per_thread:193:15)
    at process.<anonymous> (file:///C:/wamp64/www/xxx/node_modules/@shopify/cli/dist/index.js:12:13)
```

**Comment by matteodepalo** [comment]
React at the top level is actually not needed, it was added because of a quirk with `npm`, but if you upgrade to the latest version it won't be added anymore when you generate a new UI extension.

**Comment by Arkham** [comment]
In addition to what Matteo said, we've added workspaces support many months ago, so you can specify the UI extension dependency (such as react) inside the specific `package.json` for your extension. Try creating a new app from scratch in this way:
- `npm init @shopify/app@latest`
- `npm run generate extension` (choose checkout UI)
- you should have a `extensions/my-checkout-ui/package.json` that only contains the dependencies of your extension

Then you can adapt the changes into your existing app, they should be fairly straightforward.

**Comment by matteodepalo** [comment]
@stidges could you please double check the package.json version for `@shopify/app` and `@shopify/cli`? I'm asking because we've had reports of failed upgrade commands, so just want to make sure.

**Comment by justinhenricks** [comment]
I updated our app CLI and app to 3.5.0 this morning and getting this error as well currently

**Comment by matteodepalo** [comment]
I'm still unable to reproduce, but we're looking into the issue. As a workaround you should be able to use `pnpm`.

**Comment by matteodepalo** [comment]
@bpfullmetal @justinhenricks could you try putting this line in the top level package.json `dependencies` and running `npm install` again?

```
"react": "^18.0.0"
```

**Comment by justinhenricks** [comment]
> @bpfullmetal @justinhenricks could you try putting this line in the top level package.json `dependencies` and running `npm install` again?
> 
> ```
> "react": "^18.0.0"
> ```

Thanks for the help, I did this but am now getting peer dependency errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: scp-checkouts@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=17.0.0 <18.0.0" from @shopify/checkout-ui-extensions-react@0.26.2
npm ERR! node_modules/@shopify/checkout-ui-extensions-react
npm ERR!   @shopify/checkout-ui-extensions-react@"^0.26.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

This is currently my top-level package:
```
  "dependencies": {
    "@shopify/app": "^3.50.0",
    "@shopify/checkout-ui-extensions-react": "^0.26.2",
    "@shopify/cli": "^3.50.0",
    "@shopify/shopify_function": "^0.0.3",
    "@shopify/ui-extensions": "2023.7.2",
    "@shopify/ui-extensions-react": "2023.7.2",
    "dayjs": "^1.11.8",
    "javy": "^0.1.0",
    "react": "^18.0.0"
  },
  ```

**Comment by matteodepalo** [comment]
@justinhenricks what happens if you remove the `"@shopify/checkout-ui-extensions-react": "^0.26.2",` part from the top level package.json? It should be inside the checkout ui extension package.json.

**Comment by justinhenricks** [comment]
> @justinhenricks do you have `workspaces` in the top level package.json?

Hey Matt - I actually just got this working! I just manually created the package.json in each of my function/UI extensions and brought over the dependencies I saw in the latest @app/init : 


for functions:
```  
"dependencies": {
    "@shopify/shopify_function": "0.1.0",
    "javy": "0.1.1"
  },
  "devDep
```

For UI extensions:
```
  "dependencies": {
    "react": "^17.0.0",
    "@shopify/checkout-ui-extensions-react": "^0.26.0",
    "@shopify/ui-extensions": "2023.7.2",
    "@shopify/ui-extensions-react": "2023.7.2"
  },
```

I don't have the workspaces set currently in my top level package, should i set it? If it's there does that help manage the packages in the extensions themselves in some way? Thanks!

**Comment by fabiensebban** [comment]
I solved the issue by adding a `package.json` file in the `extension\[MY EXTENSION NAME]` folder with the following dependencies:
```JSON
  "dependencies": {
    "react": "^17.0.0",
    "@shopify/retail-ui-extensions-react": "^1.5.0"
  },
  "devDependencies": {
    "@types/react": "^17.0.0"
  }
```

**Comment by rtymchyk** [comment]
I'm still very much confused on what the approach should be here? 

POS UI extensions from `@shopify/retail-ui-extensions-react` utilize `@remote-ui/react` locked to `4.5.x`, which doesn't support React 18 yet, yet the CLI is instructing React 18 as a dependency. Should we be sticking to an old version of the CLI until React 18 is supported downtream in the dependency tree?

**Comment by agrohs** [comment]
Also wondering why `ink`: `4.4.1` is used (vs `4.4.0` that does not have the hard dependency on react 18)??
cc: @rsbowers
