### ISSUE TITLE
[Bug]: "theme open -e" doesnt work with shopify.theme.toml

### ISSUE THREAD

**Issue by maks-afew** [Shopify/cli#2812]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

shopify theme open -e <environment>

should take environment value from the shopify.theme.toml file as it does with other commands, like shopify theme dev

![cli_issue](https://github.com/Shopify/cli/assets/122807608/b340c4ca-7c8d-497c-b949-c5188a866f29)

### Actual behavior

Error output: Unexpected argument: <environment>

### Reproduction steps

1. create shopify.theme.toml file according to [shopify docs](https://shopify.dev/docs/themes/tools/cli/environments#configure-environments)
2. create an environment
3. try to use command: `shopify theme open -e <environment>` with your environment as a parameter

### Operating System

Windows 11 Pro, WSL2 (1.2.5.0)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.2

### Shell

bash

### Node version (run `node -v` if you're not sure)

18.14.2

**Comment by maks-afew** [comment]
@kenji-twp Thank you

**Comment by karreiro** [comment]
👋 Hey @maks-afew @kenji-twp,

Thanks a lot for reporting this issue. It's indeed an inconvenient bug.

I've added this issue on the team's radar, so we can fix this as soon as possible. In the meantime, you might workaround this problem by using the full names (`--environment`, `--editor`) to prevent conflicts. However, we're hoping to have a fix soon, so this workaround will no longer be necessary.

Once again, thanks for reporting this.
