### ISSUE TITLE
[Feature]: Add --nodelete Flag to shopify theme dev

### ISSUE THREAD

**Issue by maks-afew** [Shopify/cli#2816]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

Add --nodelete flag to the cli command `shopify theme dev` similar like in the `shopify theme push` command

### Motivation

My use case: For project that I'm working on we are using ESBuild to handle all JS files. We used slate, but since its deprecation, there was practically no real replacement to it, so we build our own quirky and slim one. The package.json script for dev looks kinda like this:

`"start": "node esbuild.watch.js & shopify theme dev"`

and as the ESBuild is still compiling for a few seconds, shopify theme is already watching and since the asset build is not yet fully completed, deletes remotes files, to upload them again a few seconds later when the asset build is done.

**Comment by maks-afew** [comment]
still relevant

**Comment by maks-afew** [comment]
still relevant

**Comment by lukeh-shopify** [comment]
Hey @maks-afew 👋🏻 

The PR that implements this feature has been merged, and will be available on the next minor version release of the CLI.

Thank you for the issue! 🙏🏻
