### ISSUE TITLE
[Bug]: Terminal resize breaks CLI output borders

### ISSUE THREAD

**Issue by mitchuman** [Shopify/cli#2826]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

CLI preview link out borders should not break the layout when the terminal is resized or moved into a split column.

### Actual behavior

Resizing the terminal causes the borders to break onto a new line, shifting the layout and resulting in an ugly layout.

### Reproduction steps

1. Run `shopify theme dev ...` and wait until the CLI outputs the preview links.
2. Resize the terminal.
3. The layout breaks.
4. The layout _does_ revert back when the terminal is resized back to its original size.

<img width="714" alt="Screen Shot 2023-09-13 at 11 30 12 AM" src="https://github.com/Shopify/cli/assets/73133191/df4a61ac-1553-433c-83d4-c6072399008f">

### Operating System

Any

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.48.0

### Shell

any

### Node version (run `node -v` if you're not sure)

any

**Comment by Arkham** [comment]
@matteodepalo do you think this is something that could be fixed?

**Comment by matteodepalo** [comment]
I don't think this can be fixed for static output like banners as borders are just text and can't be re-rendered on resize. Closing this.

**Comment by mitchuman** [comment]
May I suggest avoid a non-border approach to highlight the preview links? At least remove the side borders and/or reduce the length of the top/bottom borders?

For reference, other CLI tools like SvelteKit and Nuxt have cleaner outputs that don't break layout when resized.
