### ISSUE TITLE
[Bug]: Running shopify theme package creates an empty zip file

### ISSUE THREAD

**Issue by DrJulik** [Shopify/cli#2830]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The expected behavior is the command generating a complete theme package, ready to upload. 
Previously reported [here](https://github.com/Shopify/cli/issues/2634), but the fix didn't solve the issue. Rolling back to 3.48.4 doesn't solve the issue. Last time it was reported to be a Windows only issue.

### Actual behavior

The command generates empty zip file.
![Screenshot 2023-09-14 175907](https://github.com/Shopify/cli/assets/39019982/6f95560e-f48b-4734-91b5-9ab853bc4357)
![Screenshot 2023-09-14 175923](https://github.com/Shopify/cli/assets/39019982/d67fa71f-f6a4-4925-ba2f-0ae22221f370)

### Reproduction steps

1. Run shopify theme package
2. Zip is created.
3. It is empty.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.3

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

v18.17.1

**Comment by DrJulik** [comment]
@gonzaloriestra @isaacroldan Can you guys take a look again? Thanks!

**Comment by gonzaloriestra** [comment]
Hi! Thanks for opening the issue. I'm trying to reproduce with Git Bash and the same versions of CLI, Windows and Node, but it works for me...

Could you remove the created zip file and share the output of `shopify theme package --verbose`?

**Comment by DrJulik** [comment]
@gonzaloriestra Thanks for the reply. Here's the output:
```
$ shopify theme package --verbose
2023-09-15T15:49:33.445Z: Running command theme package
  shopify:theme:package init version: @oclif/core@2.8.11 argv: [ '--verbose' ] +0ms
2023-09-15T15:49:33.455Z: Reading the content of file at config/settings_schema.json...
2023-09-15T15:49:33.460Z: Zipping C:\Users\user\Desktop\Work\paper into Paper-6.1.1.zip
╭─ success ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                      │
│  Your local theme was packaged in Paper-6.1.1.zip                                                                                    │
│                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

2023-09-15T15:49:33.569Z: Obtaining the dependency manager in directory C:/Users/user/Desktop/Work/paper...
2023-09-15T15:49:33.584Z: 
Running system process:
  · Command: ruby -v
  · Working directory: C:/Users/user/Desktop/Work/paper

2023-09-15T15:49:33.771Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 152 ms
With response headers:
 - x-request-id: 85876f48-d58a-4687-bf78-ce09dccc9d20

2023-09-15T15:49:33.772Z: Analytics event sent: {
  "command": "theme package",
  "time_start": 1694792973446,
  "time_end": 1694792973565,
  "total_time": 119,
  "success": true,
  "cli_version": "3.49.3",
  "ruby_version": "3.2.2",
  "node_version": "18.17.1",
  "is_employee": false,
  "uname": "windows amd64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "env_shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "env_device_id": "3e050dcf8088fd5af51bb7868986b4b424d0b023",
  "env_cloud": "localhost",
  "env_package_manager": "npm",
  "cmd_all_launcher": "unknown",
  "cmd_all_topic": "theme",
  "cmd_all_plugin": "@shopify/theme",
  "args": "--verbose",
  "env_plugin_installed_all": "[\"@shopify/cli\",\"@shopify/plugin-did-you-mean\",\"@shopify/theme\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-09-15T15:49:33.773Z: Completed command theme package
```

**Comment by isaacroldan** [comment]
Does it work if you run `shopify theme package --path .` as a workaround?

**Comment by DrJulik** [comment]
Still relevant I guess. Workaround works, but it's a workaround.
