### ISSUE TITLE
[Bug]: Shopify theme console doesn't accept keyboard input in Windows Console

### ISSUE THREAD

**Issue by evangrim** [Shopify/cli#2838]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

After running `shopify theme console` in Windows Terminal CMD (with or without --url arg) console should allow keyboard entry in a repl-like manner.

### Actual behavior

After successfully signing in to shopify store, console does not accept/display keyboard input 

Can't type here:
![image](https://github.com/Shopify/cli/assets/11548185/a774c1b4-848a-45ad-abe8-d65031e9728a)

### Reproduction steps

1. Run shopify theme console in Windows 11 terminal
2. Authenticate in browser
3. Console does not appear to accept keyboard input

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.2

### Shell

Windows 11 Terminal cmd.exe

### Node version (run `node -v` if you're not sure)

v18.17.1

### What language and version are you using in your application?

liquid

**Comment by gonzaloriestra** [comment]
Hi! Thanks for creating the issue.

I'm not able to reproduce, but let me ping @karreiro in case he has any clue.

**Comment by Zetxus** [comment]
@evangrim any chance you managed to fix this? I've been trying to get the console to work for the past 5 hours. @gonzaloriestra I don't believe I can give you any specifics to reproduce this... it just doesn't work. I tried terminal emulators as well, not just cmd: Git bash, cmder, powershell, all result in the same things. No input is received but when I close the console with Ctrl + C, I get all the input that I tried to type in the console get output to the outside console.

**Comment by evangrim** [comment]
@Zetxus It's working for me now on a mac... I was on windows previously. Don't know if's a windows-specific issue though.

**Comment by Zetxus** [comment]
@evangrim Yeah I think it's Windows only, even though the bot closed this let me add this for anyone else encountering this. 

Unfortunately the fix was to use WSL and set it up on it. I'm pretty sure it had something to do with how Windows 11 console behavior is now all streamlined to the Terminal app. I've no deeper insight into what exactly the cause was though.
