### ISSUE TITLE
[Bug]: Extension CD pipeline breaks after upgrading to 3.49.3

### ISSUE THREAD

**Issue by eatoncw** [Shopify/cli#2841]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

I can resume deployment of my extension in my CD pipeline

### Actual behavior

I'm deploying a theme extension in a CD pipeline using github actions. My pipeline has worked fine until today when I got a message:
```
"error_message": "Upgrade your CLI version to run the deploy command.",
```

Fine, I upgraded from `3.45.4` to `3.49.3`.

I reran the job and encountered this error:

```
Flag not specified:                                                         │
│                                                                              │
│  client-id                                                                   │
│                                                                              │
│  This flag is required in non-interactive terminal environments, such as a   │
│  CI environment, or when piping input from another process.                  │
│                                                                              │
│  To resolve this, specify the option in the command, or run the command in   │
│  an interactive environment such as your local terminal.  
```

I don't see this documented anywhere, but I added the flag to my deployment command:

`npm run deploy:shopify-frontend -- -f -client-id`

The feedback just says flag, so I didn't add `client-id=XXXX`

I reran the job, and then encountered this deployment error:

`Couldn't find shopify.app.lient-id.toml in extensions/XXXXXX.`

I have never had this file before - also notice the likely spelling mistake in the error feedback (lient-id, not client-id). I don't see this file documented anywhere either...

What should this file contain? What do I need to do to ensure I can deploy my extension in a CD pipeline again?

### Reproduction steps

1. npm run deploy:shopify-frontend -- -f
2.
3.

### Operating System

ubuntu-latest

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.3

**Comment by alvaro-shopify** [comment]
Hi @eatoncw, thanks for raising up this issue. Right now, in your CD environment how do you set the `api-key` used to deploy?. I guess we have found a little issue because in the [documentation](https://shopify.dev/docs/apps/tools/cli/ci-cd#examples) you will see that the env variable `SHOPIFY_API_KEY` should be used but right now it's not working neither.

Please as a quick workaround, could you set the env variable `SHOPIFY_FLAG_APP_API_KEY` in your CD setup?, you should find it in the `.env` file or in the dashboard.

Please, let me know if it works for you.
