### ISSUE TITLE
[Bug]: I encountered an error when running "yarn dev" with Shopify CLI, but there is no error message. 

### ISSUE THREAD

**Issue by leeyowu** [Shopify/cli#2857]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

`yarn dev` working well

### Actual behavior

I encountered an error when running "yarn dev" with Shopify CLI, but there is no error message. The code was working fine yesterday without any changes, but today it's not working properly.
<img width="750" alt="image" src="https://github.com/Shopify/cli/assets/84018558/3eed059c-ea35-4780-bf9e-09caa75edfc0">

### Reproduction steps

1.yarn dev

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.3 & 3.49.2

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18.17.1

### What language and version are you using in your application?

React

**Comment by leeyowu** [comment]
<img width="1051" alt="image" src="https://github.com/Shopify/cli/assets/84018558/48d6778f-5adb-48af-b030-b39d6dba8b66">

<img width="939" alt="image" src="https://github.com/Shopify/cli/assets/84018558/afa9290b-3a38-42ff-aa14-dc90975ca842">
<img width="920" alt="image" src="https://github.com/Shopify/cli/assets/84018558/f23db334-9cb9-47da-992f-396f3bcafc1f">

@alvaro-shopify Hi, had shared the screenshots

**Comment by alvaro-shopify** [comment]
Hi @leeyowu!, thanks a lot for adding new information. After reviewing the output log it seems that there's a problem creating the `cloudfare` tunnel.
- It seems that your network has some restrictions to connect CloudFare servers. Please, look at this [documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips/) to check if the network meets the requirements
- In case you are not able to make the cloudfare tunnel working you can use the tunnelling solutions that fits your requirements. You'll need to create the tunnel following the proper instructions and once it's running you could run the `dev` command with the `--tunnel-url`

For example you could use `ngrok` and these should be the instructions:
- Create one `ngrok` account
- Install the ngrok CLI: https://ngrok.com/download
- Run `ngrok http 3000` and copy the URL (keep the tab open)
- Run `npm run shopify app dev -- --tunnel-url https://your-url.ngrok.com:3000`

Please let me know if this works for you or if you need further assistance

**Comment by alvaro-shopify** [comment]
Regarding the empty error message, the CLI supports a specific list of cloudfare errors. In this case the error `ERR Failed to create a new quic connection...` is not supported.

We will add it and a default error message just in case a new error appears.

**Comment by leeyowu** [comment]
> Hi @leeyowu!, thanks a lot for adding new information. After reviewing the output log it seems that there's a problem creating the `cloudfare` tunnel.
> 
> * It seems that your network has some restrictions to connect CloudFare servers. Please, look at this [documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips/) to check if the network meets the requirements
> * In case you are not able to make the cloudfare tunnel working you can use the tunnelling solutions that fits your requirements. You'll need to create the tunnel following the proper instructions and once it's running you could run the `dev` command with the `--tunnel-url`
> 
> For example you could use `ngrok` and these should be the instructions:
> 
> * Create one `ngrok` account
> * Install the ngrok CLI: https://ngrok.com/download
> * Run `ngrok http 3000` and copy the URL (keep the tab open)
> * Run `npm run shopify app dev -- --tunnel-url https://your-url.ngrok.com:3000`
> 
> Please let me know if this works for you or if you need further assistance

yes, it working well while I run  `cloudflared tunnel --protocol http2 --url http://localhost:${PORT}` and `yarn shopify app dev --tunnel-url ${url}:${PORT}`

But I still want to know why I was able to run "yarn shopify app dev" directly before, but now I need to run "cloudflared tunnel" first in order to execute "yarn shopify app dev". @alvaro-shopify

**Comment by jakejaylee123** [comment]
Hi @alvaro-shopify--Did Shopify recently switch from using Ngrok by default to using Cloudflare? I remember not having to manually create an Ngrok tunnel to get things working on my end... I am getting the same error that @leeyowu gets (well, except that I use `npm run dev` instead of `yarn dev`).

**Comment by alvaro-shopify** [comment]
Hi @jakejaylee123. Not too recently, 6 months ago more or less, do you test your connectivity against cloudfare servers as mentioned [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips/)?

**Comment by alvaro-shopify** [comment]
Fixed with version `3.49.4`

**Comment by Nikkstar07** [comment]
i try to run my app using  yarn run dev --tunnel-url=https://41ae-2405-201-2027-e06b-5c94-f6c0-3926-410.ngrok-free.app:3000
But show this 
![Screenshot_1](https://github.com/Shopify/cli/assets/147698999/37c7ed6b-9723-492e-8480-25995c966a29)
