### ISSUE TITLE
[Bug]: shopify upgrade was not found

### ISSUE THREAD

**Issue by SerhiDi** [Shopify/cli#2858]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [ ] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Documentation is written by adequate people.

### Actual behavior

Guys, you are awesome. You send links from your CLI and instructions not working. WTF?

I trying to run a theme

``` shopify theme dev```

and immediately get this:

```
* A new version of Shopify CLI is available! You have version 2.29.0 and the latest version is 2.32.0.

  To upgrade, follow the instructions for the package manager you’re using:
  https://shopify.dev/themes/tools/cli/upgrade-uninstall

Suite of commands for developing Shopify themes. See shopify theme <command> --help for usage of each command.
  Usage: shopify theme [ check | delete | init | language-server | list | open | package | publish | pull | push | serve | share ]
  ```

OK, open this link

![image](https://github.com/Shopify/cli/assets/10574421/ef628254-fbd7-429d-8240-76b5d1f42a63)

```shopify upgrade```

AND!!!!!

```shopify upgrade was not found```

BUT

```
 shopify version
2.29.0
```

Shopify sucks.

### Reproduction steps

1. Open terminal
2. `shopify theme dev`
3. Get `update` message
4. `shopify upgrade`
5. `shopify upgrade was not found`

### Operating System

Windows 10 x64

### Shopify CLI version (check your project's `package.json` if you're not sure)

2.29.0

**Comment by Arkham** [comment]
You are using CLI 2, please upgrade to CLI 3 https://shopify.dev/docs/themes/tools/cli/migrate

**Comment by SerhiDi** [comment]
Also, I already use `npm install -g @shopify/cli @shopify/theme` to install CLI 
But I am still on version 2.29
