### ISSUE TITLE
[Bug]: Cannot run development app on latest version (with npm run dev) - PHP template

### ISSUE THREAD

**Issue by dv-ahardy** [Shopify/cli#2866]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

npm run dev should proceed through the app selection (or creation) flow and I should be presented with a preview link and running app.

### Actual behavior

The app selection flow completed successfully, but when attempting to the start the app's services, I was met with an error suggesting vite was not installed.

This does not occur on older versions of the template.

![image](https://github.com/Shopify/cli/assets/129867872/dfb3e2e5-9769-4bac-923b-ab62b7d22850)

### Reproduction steps

1. npm init @shopify/app@latest -- --template php
2. [Usual PHP application setup steps]
3. npm run dev
4. App Creation (or Selection)
5. **Error!**

### Operating System

Windows 11 22H2 (with WSL 22.04), also Mac OS 13.5.2

### Shopify CLI version (check your project's `package.json` if you're not sure)

@latest, 3.49.3

### Shell

bash, zsh

### Node version (run `node -v` if you're not sure)

v20.0.0, v20.4.0

**Comment by Insomnia88** [comment]
I currently having the same issues so I wouldn't see it as completed/closed.
