### ISSUE TITLE
[Feature]: use fixed address on cloudflare tunnel

### ISSUE THREAD

**Issue by yann120** [Shopify/cli#2872]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

Substantial change to existing feature

### Overview

Hi, 
I always have problems because of the url from cloudflare that changes each time i re-launch the server in local dev.
Shopify updates the URL on the app installed on the store, so that's ok.
But when using webhooks, it will keep the subscribed URL when you installed the app on the store (I think)...
So each time, I want to test webhooks after re-launching the server, it can't reach the server because the url has changed.

My actual workaround is to use ngrok with a fixed address, and use the command `npm run dev -- --tunnel-url=`
But it would be better to have it integrated directly with cloudflared in the command

### Motivation

Problems for testing webhooks due to the url changing every time I launch the server

**Comment by gonzaloriestra** [comment]
Hi! Thanks for the suggestion.

Unfortunately, Cloudflare Quick Tunnels are always random. However, we are aware about the issues with temporary URLs and webhooks, and we'll try to improve the experience.

**Comment by subrb** [comment]
@gonzaloriestra  Hi, wondering if there was ever a solution to this?  I have fixed URLs in Flow that I need to manually update every time I run `shopify app dev`.  Thanks!

**Comment by gonzaloriestra** [comment]
@subrb not yet, but thanks for letting us know about your use case!

**Comment by subrb** [comment]
@gonzaloriestra Thanks for the reply.  Can you think of any possible workarounds in the meantime?  Would the Shopify API let you update the URLs in Flow automatically from the .toml file?  Thanks again

**Comment by gonzaloriestra** [comment]
I'm afraid the Shopify API doesn't support that.

But you can create your own tunnel and pass it to the CLI with the [tunnel-url flag](https://shopify.dev/docs/api/shopify-cli/app/app-dev#flags-propertydetail-tunnelurlvalue), so you are in control of it and the CLI doesn't generate a random one.

**Comment by subrb** [comment]
Thanks!
