### ISSUE TITLE
[Bug]: Editor won't load, keep getting The Theme you're looking for couldn't be found

### ISSUE THREAD

**Issue by shornuk** [Shopify/cli#2888]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The theme customiser should load when visiting the URL given by the CLI

### Actual behavior

Get an error message of "The Theme you're looking for couldn't be found" every time I try to load the local theme customiser/editor. 

### Reproduction steps

1.
2.
3.

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.3

**Comment by karreiro** [comment]
Thank you for bringing this issue to our attention, @shornuk!

I'm facing some challenges to reproduce the problem tho. Could you kindly re-run the command using the `--verbose` flag and share the output here?

With the extra details, I'll be able to reproduce the problem and fix it. Thanks again for reporting this!
