### ISSUE TITLE
[Bug]: For recurring change test charge fails in prod

### ISSUE THREAD

**Issue by akmittal** [Shopify/cli#289]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

When App is submitted and Shopify employees test. They do a test charge but in current app that's not allowed 

### Actual behavior

Test charge should be allowed or this behaviour should be documented somewhere 

### Reproduction steps

1. Deploy app with recurring change 
2. As a shopify employee do a test charge attempt 

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.6.2

**Comment by alvaro-shopify** [comment]
Hi!. Thank you for reporting the issue. I'm going to ask to App Review team about this problem and I will came back to you with a response as soon as possible.

**Comment by akmittal** [comment]
I trying to deploy node based app, bootstraped using shopify cli
