### ISSUE TITLE
[Bug]: Liquid console can't handle complex queries

### ISSUE THREAD

**Issue by tamir-boaideas** [Shopify/cli#2915]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Like the real engine, the REPL should be able to handle any liquid query passed to it.

### Actual behavior

When the liquid query gets complicated the REPL throws an error regarding the first element in the query.
Example:
The query:
`all_products['22mg805-002'].metafields.custom.collections_replicates.value`
works as expected, but if we go one level deeper:
`all_products['22mg805-002'].metafields.custom.collections_replicates.value.collection`
we get an error
`Liquid syntax error: Unknown tag 'all_products'`

The storefront shows the correct collection that the metafield points to.

### Reproduction steps

Write an increasingly complex liquid query until the REPL throws an error

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.7.0

### What language and version are you using in your application?

v20.7.0

**Comment by alvaro-shopify** [comment]
Hey @tamir-boaideas. Pinging the @Shopify/theme-code-tools for further assistance with this issue.
