### ISSUE TITLE
[Bug]: `shopify theme pull --only templates/*.json` flag doesn't pull new files

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#2925]
The `shopify theme pull --only templates/*.json` command doesn't download new files.

### Expected behavior

The `shopify theme pull -t <theme_id> --only templates/*.json` should download new files when they are created in the code editor.

### Actual behavior

The `shopify theme pull -t <theme_id> --only templates/*.json` doesn't download the new file.

### Reproduction steps

1. Create a new file at the admin code editor
2. `shopify theme pull -t <theme_id> --only templates/*.json` (notice nothing is downloaded)
3. `shopify theme pull -t <theme_id>` (notice the new file is downloaded)

### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.5

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.2.0

### What language and version are you using in your application?

3.1.2

**Comment by karreiro** [comment]
Closing this issue because when users use `--only templates/*`, the CLI expands to local files because the shell performs the expansion before the command is run.

If users want to download files remotely, they may pass an expression as a regex to prevent the shell from expanding it. For example, to download only JSON files from the `templates` directory, use:

```bash
--only "templates/.*\.json"
```

This ensures the command applies the wildcard pattern to the remote files.

**Comment by lukecharle** [comment]
> Closing this issue because when users use `--only templates/*`, the CLI expands to local files because the shell performs the expansion before the command is run.
> 
> If users want to download files remotely, they may pass an expression as a regex to prevent the shell from expanding it. For example, to download only JSON files from the `templates` directory, use:
> 
> --only "templates/.*\.json"
> This ensures the command applies the wildcard pattern to the remote files.

I'm not sure if this is working, I'm having an issue with templates created in the editor working, so basically all alternative templates, for example `collection.champagne-magnum.json`.

I've tried using the following command in my `package.json` but it isn't being pulled down.

```
"pull:content": "shopify theme pull --store=the-bottle-club --only config/settings_data.json --only \"templates/.*\\.json\" --only templates/customers/*.json --only templates/metaobject/*.json --only locales/*.json --only sections/*.json
```

**Comment by beppek** [comment]
I have to chime in with @lukecharle, this doesn't appear to be working. Can this issue be reopened?
