### ISSUE TITLE
Unable to create my shopify app on a store on which I have collaborator's access

### ISSUE THREAD

**Issue by abdul-ahad-devs** [Shopify/cli#2940]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I should be able to create a shopify app on a store on which I have collaborator's access

### Actual behavior

When I run `npm init @shopify/app@latest`, it does not ask me on which store to create an application, rather it creates the application on my default development store. I have another store (of my client) on which I have taken collaborator access from my client. However, I am unable to create an app on that store.

### Reproduction steps

1. Run `npm init @shopify/app@latest
2. cd into project folder
3. Run `npm run dev`

### Operating System

Macbook Pro (Intel Chip, 2017)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.5

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.13.0

### What language and version are you using in your application?

Node v18.13.0 with Remix

**Comment by alvaro-shopify** [comment]
Hey @abdul-ahad-devs . Thanks for rising up this issue. The remote app is not created when you run the `npm init @shopify/app@latest`, that's why you are not prompted to create a new remote app.

Most of the `shopify app` commands let you create a new app or connect to an existing remote one.

If you are not prompted to do that, maybe it's possible that the command is used some cached information from a previous run. In that case, I recommend you run first the command `npm run shopify auth logout` and then the `dev` command using the flag `--reset`

Please let us know if this works for you.

**Comment by alvaro-shopify** [comment]
@abdul-ahad-devs , do you have only one dev store?, in that case the CLI uses the existing one without prompting you for it

**Comment by abdul-ahad-devs** [comment]
@alvaro-shopify, thank you for the help. I just have four queries remaining. Please answer them for me.

1. Using my dev store, how can i access the products that are present on my client's store (I have collaborator's access to my client store)
2. After finishing the application, how can I transfer the ownership of this app to my client (as this app is owned by my client, I am just developing it)
3. I want to create a standalone app (not an embedded one). During development, my app is being opened inside shopify admin and not in a new link. My client wants this app to be hosted and accessed at some deployed URL (https://example.com), and not inside shopify admin.
4. I have created an app and deployed it on heroku. The problem is that when I went to my deployed URL it showed be the default screen of shopify app (see screenshot below). Although, I want my client to access the homepage of my website when he go to my deployed URL (see screenshot 2). The default page asked me to login using the shop domain. I am not exactly sure what is it and how can I create a domain on my dev store.
![Screenshot 2023-10-11 at 2 47 07 AM](https://github.com/Shopify/cli/assets/55701320/a6c5f341-60c4-4a59-8b81-771848b9a4f5)
![Screenshot 2023-10-11 at 2 55 15 AM](https://github.com/Shopify/cli/assets/55701320/76c1d70d-9f3b-4e33-9785-450e3db99862)
