### ISSUE TITLE
Invalid app URL issue with Docker on Shopify Cli 3

### ISSUE THREAD

**Issue by abdul-ahad-devs** [Shopify/cli#2942]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should have started the docker container for my app so that I can continue with my app deployment steps.

### Actual behavior

I followed steps mentioned in Shopify documentation to deploy my app on heroku. When I ran docker container using `npm run docker-start`, it gave me an error with the following error information

<img width="1650" alt="image" src="https://github.com/Shopify/cli/assets/55701320/30ff1006-2457-4917-a106-fa867245de78">

My docker file has the following code

FROM node:18-alpine

EXPOSE 3000
WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

# You'll probably want to remove this in production, it's here to make it easier to test things!
RUN rm -f prisma/dev.sqlite

CMD ["npm", "run", "docker-start"]

### Reproduction steps

1. Create Remix app using Shopify Cli 3 with `npm init @shopify/app@latest`
2. Build the app using `npm run build`
3. Run `npm run docker-start` to start the docker container

### Operating System

Macbook Pro (Intel Chip 2017)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.5

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.13.0

### What language and version are you using in your application?

Node v18.13.0 with Remix

**Comment by alvaro-shopify** [comment]
Hey @abdul-ahad-devs 👋 !. Thanks for rising up this issue. You need to [configure](https://shopify.dev/docs/apps/tools/cli/ci-cd#step-3-integrate-shopify-cli-into-your-pipeline) in your pipeline the `env` variables with the [deployment info ](https://shopify.dev/docs/apps/tools/cli/ci-cd#step-1-generate-variables-for-deployment)and the [CLI Partners Token ](https://shopify.dev/docs/apps/tools/cli/ci-cd#step-2-generate-a-cli-authentication-token)

Please, let me know if this works for you. Thanks.

**Comment by abdul-ahad-devs** [comment]
@alvaro-shopify, thank you for your feedback. I have generated the client shopify_api_key and client partner token, but can you please tell me at where should I paste my client partner token.

Secondly, I don't want to implement CI/CD on my app. I just want to deploy my code manually using heroku.

**Comment by alvaro-shopify** [comment]
Hey @abdul-ahad-devs . I have posted in another [issue](https://github.com/Shopify/cli/issues/2941#issuecomment-1755265251) a simple docker file example I have used to deploy an app with some extensions.
Please, take a look at it and check if it works for you

**Comment by abdul-ahad-devs** [comment]
@alvaro-shopify Thanks!, it worked. Now, I am closing this issue

**Comment by bkmahapatra27** [comment]
@alvaro-shopify While setting up Jenkins CI/CD with Docker, I'm encountering a recurring issue. Where should I locate my .env file and how can I grant access to this file for both Jenkins and Docker?
