### ISSUE TITLE
[Bug]: How to create a custom non-embedded Remix app using Shopify CLI 3?

### ISSUE THREAD

**Issue by abdul-ahad-devs** [Shopify/cli#2967]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I created a remix app using shopify-cli 3 and deployed it on heroku. When I accessed my deployed URL, it should have opened the website on my URL (just like facebook.com or twitter.com) and not an embedded application inside Shopify Admin.

### Actual behavior

When I accessed my deployed URL of heroku, it asked me to login into my Shopify Store and then showed me an embedded app inside my Shopify Admin. I don't want an embedded app, instead I want a standalone application just like any typical web application that we create on React and deploy it on heroku or any other platform.

Expected behavior:
![Screenshot 2023-10-12 at 5 59 08 PM](https://github.com/Shopify/cli/assets/55701320/cc132795-af92-4901-95c8-85126d83b031)

Actual behavior:
![Screenshot 2023-10-11 at 2 55 15 AM](https://github.com/Shopify/cli/assets/55701320/e0fd8ea9-d37f-49c0-bc3a-c6e7f21edb32)

### Reproduction steps

1. Create a remix app using shopify-cli 3 with `npm init @shopify/app@latest`
2. Deploy this app on heroku using heroku-cli
3. Access the application on your deployed URL.

### Operating System

Macbook Pro (Intel Chip 2017)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.5

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.13.0

### What language and version are you using in your application?

Node v18.13.0 with Remix

**Comment by isaacroldan** [comment]
Closing as this is not really related to the CLI itself and an explanation was given in the template repo :)
