### ISSUE TITLE
[Bug]: how to limit the discount number from Cart and Checkout Validation Function

### ISSUE THREAD

**Issue by BlackEyeByLee** [Shopify/cli#2976]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Function

### Expected behavior

Cart and Checkout Validation Function api  graphql input is no exist discount，i want to limit the discount number in checkout.how wo do ?
 

### Actual behavior

Cart and Checkout Validation Function api  graphql input is no exist discount，i want to limit the discount number in checkout.how wo do ?
 ?

### Reproduction steps

1. https://shopify.dev/docs/api/functions/reference/cart-checkout-validation

### Operating System

Mac os

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.6

**Comment by matteodepalo** [comment]
@BlackEyeByLee thank you for opening this issue. Could you clarify exactly which problem are you experiencing? Are you experiencing problems with the Shopify CLI?
