### ISSUE TITLE
[Bug]: Yarn berry can't be used, please bump oclif version and change `config.plugins` to `[...config.plugins.values()]`

### ISSUE THREAD

**Issue by danieltroger** [Shopify/cli#3004]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I can run `yarn shopify app dev` with yarn berry (yarn v3/v4)

### Actual behavior

Before you update `@oclif/core`:

```
╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                              │
│  command app:dev not found                                                                                                                                                   │
│                                                                                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

After you update `@oclif/core` to at least `3.4.1-dev.0`:

```
╭─ error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                │
│  config.plugins.map is not a function                                                                                                          │
│                                                                                                                                                │
│  To investigate the issue, examine this stack trace:                                                                                           │
│    at registerCleanBugsnagErrorsFromWithinPlugins                                                                                              │
│    (.yarn/unplugged/@shopify-cli-kit-npm-3.49.5-f269164f4b/node_modules/@shopify/cli-kit/src/public/node/error-handler.ts:161)                 │
│      config.plugins.map(async (plugin) => {                                                                                                    │
│    at init (.yarn/unplugged/@shopify-cli-kit-npm-3.49.5-f269164f4b/node_modules/@shopify/cli-kit/src/public/node/base-command.ts:39)           │
│      await registerCleanBugsnagErrorsFromWithinPlugins(this.config)                                                                            │
│                                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

After you have done this change: https://github.com/oclif/core/pull/839#issuecomment-1772357744, related line in your code: https://github.com/Shopify/cli/blob/0ff99666499ac206ffa0337ae7b36f3555bf1c3d/packages/cli-kit/src/public/node/error-handler.ts#L172

It should work :)

### Reproduction steps

1. Please see https://github.com/oclif/core/issues/806
2. If something's still unclear, please see https://github.com/oclif/core/pull/839

### Operating System

macOS 14.0 (23A344)

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli@3.50.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.5.0

### What language and version are you using in your application?

TypeScript 4.9.4

**Comment by isaacroldan** [comment]
Hi @danieltroger, unfortunately we can't upgrade to oclif v3 yet because we haven't formally dropped node 16 support (oclif 3 does). We will eventually, but can't promise any dates. In the meantime my only recommendation would be not to use yarn berry, sorry.

**Comment by isaacroldan** [comment]
No timeline yet, still discussing it internally, but I'll keep this issue open and update it once we have more news 
Glad that you at least have a workaround :)

**Comment by danieltroger** [comment]
Waiting for shopify to drop node 16 support. Here's some activity so the issue doesn't get closed

**Comment by isaacroldan** [comment]
We are almost there: https://github.com/Shopify/cli/pull/2975 :)

**Comment by danieltroger** [comment]
Niiice :)

**Comment by isaacroldan** [comment]
I think this is an issue with Hydrogen, they are using an older version of cli-kit without the fixes for oclif 3.
I'll talk to them to fix this.
