### ISSUE TITLE
@shopify\plugin-cloudflare error

### ISSUE THREAD

**Issue by changeyoucant** [Shopify/cli#3007]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

can download @shopify/cli and @shopify/app

### Actual behavior

can download @shopify/cli and @shopify/app
cmd error 
npm ERR! code 1
npm ERR! path C:\WINDOWS\system32\node_modules\@shopify\plugin-cloudflare
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/postinstall.js
npm ERR! file:///C:/WINDOWS/system32/node_modules/node-fetch/src/index.js:108
npm ERR!                        reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
npm ERR!                               ^
npm ERR!
npm ERR! FetchError: request to https://github.com/cloudflare/cloudflared/releases/download/2023.5.1/cloudflared-windows-amd64.exe failed, reason: connect ETIMEDOUT 20.205.243.166:443
npm ERR!     at ClientRequest.<anonymous> (file:///C:/WINDOWS/system32/node_modules/node-fetch/src/index.js:108:11)
npm ERR!     at ClientRequest.emit (node:events:517:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR!     at TLSSocket.emit (node:events:517:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   type: 'system',
npm ERR!   errno: 'ETIMEDOUT',
npm ERR!   code: 'ETIMEDOUT',
npm ERR!   erroredSysCall: 'connect'
npm ERR! }
error log is 

### Reproduction steps

1.npm i @shopify/cli @shopify/app
then error whats @shopify\plugin-cloudflare ?

### Operating System

window 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

THE LASTEST

### Node version (run `node -v` if you're not sure)

18.18.2

**Comment by changeyoucant** [comment]
its seem like @shopify/app error

**Comment by linkjie** [comment]
I also have this problem, how to solve it?
