### ISSUE TITLE
[Feature]: Don't change subpaths of application_url and redirect_urls 

### ISSUE THREAD

**Issue by sviat-bazo** [Shopify/cli#3010]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

Substantial change to existing feature

### Overview

In case `shopify.app.toml` file is already populated with application_url and/or redirect_urls, new urls should be generated with respect to subpaths provided in the configuration file

application_url = "https://rap-pricing-indiana-fire.trycloudflare.com/api/auth"
after restart should be replaced with 
application_url = "https://<new_tunnel_hostname>/api/auth"

### Motivation

Recently there was a similar change in the `generatePartnersURLs` that did that for proxyUrl so doing that for application_url and redirects_url will make configurations more consistent. That would make running application locally easier for everyone that has custom paths for Shopify App installation like me.

**Comment by sviat-bazo** [comment]
How is there no information on root url?
```
const newURLs = generatePartnersURLs(network.proxyUrl, webs.map(({ configuration }) => configuration.auth_callback_path).find((path) => path), isCurrentAppSchema(localApp.configuration) ? localApp.configuration.app_proxy : undefined);
```

Isn't `network.proxyUrl` a host and `localApp.configuration.application_url` is the existing config? It doesn't seem much different from proxy_url

**Comment by fixpunkt** [comment]
We're still running into this issue, as our Shopify app lives in a context path of the full application. Are there any plans on supporting this or merging https://github.com/Shopify/cli/pull/3023?
