### ISSUE TITLE
[Bug]: Error: command app:dev not found on fresh yarn install

### ISSUE THREAD

**Issue by saudpunjwani101** [Shopify/cli#3029]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

After creating new shopify app with remix template using yarn command "yarn create @shopify/app". I "cd" into the project and do,

1. yarn install
2. yarn run dev

The shopify app should start running

### Actual behavior

I got error "Error: command app:dev not found"

### Verbose output

```shell
Error: command app:dev not found
```

### Reproduction steps

1. yarn create @shopify/app
2. cd ./new-app
3. yarn install
4. yarn run dev

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.50.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.3.0

### What language and version are you using in your application?

yarn v4.0.0

**Comment by Arkham** [comment]
Hi there, yarn 4 is not currently supported. If you check here: https://shopify.dev/docs/apps/tools/cli#requirements we support these package managers:
- npm
- yarn 1.x
- pnpm

**Comment by saudpunjwani101** [comment]
Hi, thanks for your response. If using yarn classic (1.22.19), I get error,

 create-strapi-app@4.1.5: The engine "node" is incompatible with this module. Expected version ">=12.2
2.0 <=16.x.x".

I can't use Node 16 or earlier to install Strapi since I want to use the new Remix template and Remix officially supports **Active** and **Maintenance** and node 16 isn't either. So how do I install it using yarn classic?

**Comment by Arkham** [comment]
can you not update your version of `create-strapi-app`? I can see they support node 18 or greater in their latest version: https://www.npmjs.com/package/create-strapi-app/v/4.15.0?activeTab=code

**Comment by saudpunjwani101** [comment]
Ah yes sorry I had the create-strapi-app cli installed via yarn. Great it works.
