### ISSUE TITLE
[Bug]: gifs break app extension asset uploading

### ISSUE THREAD

**Issue by Clonkex** [Shopify/cli#3042]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

With the Shopify CLI running (`npm run dev`), I should be able to drop a small gif in `app-name\extensions\extension-name\assets` and have it automatically be pushed up to the test site.

If gifs are not supported, I would expect to see an error message in the CLI. Or at least, I would expect it to keep functioning properly.

### Actual behavior

Nothing happens. Nothing at all. As long as the gif exists in the assets folder, nothing gets synced, not even the extension's liquid files. If I remove the gif, it suddenly starts working again and I get an entry in the CLI like this (with the duplicate entry for `loading.gif`):

```shell
10:38:46 │ extensions │ Pushed » 'app-name' to a draft
10:38:46 │ extensions │ - assets/loading.gif
10:38:46 │ extensions │ - assets/loading.gif
```

I tested with a variety of files and found that the problem exists with any files with an extension other than (it seems like) `jpg` or `png`. If I create a new file `test.txt`, the problem will occur. If I then rename it to `test.jpg` (even if it's not actually a jpg) the CLI starts working again.

### Verbose output

When adding the gif to the folder, I see only this (yes, it says "Removed:" with nothing following):

```shell
10:37:34 │ extensions │ DEBUG [ReloadPage] Added: assets/loading.gif
10:37:34 │ extensions │ DEBUG [ReloadPage] Removed:
```

When removing the gif from the folder, I see this (again with nothing following `Added:`):

```shell
10:38:46 │ extensions │ Pushed » 'app-name' to a draft
10:38:46 │ extensions │ - assets/loading.gif
10:38:46 │ extensions │ - assets/loading.gif
10:38:46 │ extensions │ DEBUG [ReloadPage] Added:
10:38:46 │ extensions │ DEBUG [ReloadPage] Removed: assets/loading.gif
```

### Reproduction steps

1. `npm init @shopify/app@latest`
2. Give it a name and choose "Start by adding your first extension"
3. `cd gif-test-app`
4. `npm install`
5. `npm run dev`
6. Choose to create a new app
7. Hit "p" and install the app on your test site, then "q" to quit
8. `npm run shopify app generate extension`
9. Choose "Theme app extension" and give it a name
10. `npm run dev`
11. Wait for the extension files to be pushed to a draft
12. Copy any old gif into `gif-test-app\extensions\theme-extension\assets`
13. Notice that nothing happens in the CLI
14. Delete the gif from assets
15. Notice that the CLI suddenly catches up and shows the gif twice

Minimum reproducible project: 
[gif-test-app.zip](https://github.com/Shopify/cli/files/13222127/gif-test-app.zip)

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.50.1

### Shell

cmd

### Node version (run `node -v` if you're not sure)

v18.12.0

**Comment by shauns** [comment]
I can confirm that the supported extensions for theme app extension assets are `'.jpg', '.jpeg', '.js', '.css', '.png', '.svg'`

You should be receiving a clearer error message -- thank you for the detailed reproduction information, I'll see if we can get that improved -- am sure it was confusing when you encountered it.

**Comment by Clonkex** [comment]
@shauns In that case it might also be worth fixing the theme checker so that it doesn't tell me I'm doing it wrong by using an external asset:

![image](https://github.com/Shopify/cli/assets/4530775/a17a44b7-3d32-4207-9061-517c2bd01fee)

^That is in reference to the gif in our actual project, and it's what lead me down this rabbit hole.

And finally, it's probably worth documenting the restriction somewhere, if it's not already. I spent a long time looking for any mention of what files might be allowed, but couldn't find a single one. It just kept saying "static assets". And it was like, well ok then, this gif is a static asset and the CLI isn't telling me I can't use it so I guess it's just broken.

**Comment by salmanrf** [comment]
but why ?, why isn't .gif allowed ?
