### ISSUE TITLE
[Feature]: Machine-readable output for cli commands

### ISSUE THREAD

**Issue by iradcn** [Shopify/cli#3056]
### What area(s) will this request affect?

App

### What type of change do you want to see?

New feature

### Overview

It would be nice to have a flag that sets the output as json or something else that would be easily parsed by code.
I think this would really help with using the cli as part of CI/CD workflows.

### Motivation

We are deploying our app as a part of a CI/CD flow.
As a part of this flow, we're checking the message of the the current active app version.
When reading stdout from a node script, or even simply piping it to `grep`, lots of info gets trimmed.

Reading the code I figured out that the `versions list` command limits the columns to 75 by default, and that this can be set with the `SHOPIFY_CLI_COLUMNS` env variable.
It's a nice workaround, but a proper flag would be awesome.

**Comment by kenji-twp** [comment]
Much appreciated @isaacroldan ! That will be a huge help. hoping it can be included in the next release! 🙏
