### ISSUE TITLE
[Feature]: shopify app dev - Tunnel-less mode

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/cli#3071]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

New feature

### Overview

We don't use Shopify App CLI to run our app server locally, we only use it for developing checkout extensions. Currently, our workflow looks like this:

Terminal 1: run server process on 3000
Terminal 2: run `shopify app dev --tunnel-url=https://my-extensions-tunnel.ngrok.dev:3001`
Terminal 3: run ngrok configured for two domains: 
```
http 3000 -> https://my-app-tunnel.ngrok.dev
http 3001 -> https://my-extensions-tunnel.ngrok.dev
```

We'd love to simplify our setup so we have one port and one ngrok domain. We would like to set up our server so that during development it proxies requests to the Shopify App CLI server. 

I imagine we could run:

```
shopify app dev --port 3001 --url=https://my-app-tunnel.ngrok.dev/extensions-server
```

which exposes the Shopify App CLI server at `localhost:3001` and assumes it is accessible at  `https://my-app-tunnel.ngrok.dev/extensions-server`. 

From there, in our server we proxy requests from path /extensions-server to localhost:3001 and have everything under single ngrok domain.

### Motivation

Having multiple ngrok tunnels costs $$$. It is also cumbersome to onboard new developers

**Comment by kfalkiewicz** [comment]
Looks like a great idea. Big 👍 from me.
