### ISSUE TITLE
[Bug]: Section CSS / JavaScript in {% stylesheet %} and {% javascript %} not reliably updated on server when changed locally

### ISSUE THREAD

**Issue by binarymonkey84** [Shopify/cli#3097]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme, Other

### Expected behavior

If I change the CSS within a `{% stylesheet %}` Liquid tag (or JavaScript in `{% javascript %}`), I expect the Theme Customiser and storefront to immediately reflect the changes.

### Actual behavior

Approximately 80% of the time, the changes aren't reflected in Theme Customiser or the storefront after refreshing one or several times, or even clearing local browser cache.

To get the changes working when running `shopify theme dev`, I often have to go back into the Liquid section file, make another change, save the file, check it's been uploaded by Shopify CLI, then refresh. This sometimes requires more than one go to get it to work.

I've also noted the same behaviour when deploying theme changes via the [Shopify GitHub integration](https://shopify.dev/docs/themes/tools/github). I usually have to "reset to the latest commit" to get it to "refresh" itself.

I suspect there is some cache invalidation problem at Shopify's server level.

Obviously this makes development very slow and frustrating when using the `{% stylesheet %}` or `{% javascript %}` Liquid tag. We do quite a bit of adding custom sections to existing themes, so we try to keep our code as isolated from the theme code as possible, and avoid creating additional separate JS or CSS files.

This has been a long standing problem I've experienced over at least 2 years using multiple different OS's and machines.

### Verbose output

```shell
N/A
```

### Reproduction steps

1. Add some code to a {% stylesheet %} or {% javascript %} section, while `shopify theme dev` is running
2. Reload Theme Customiser / the storefront
3. See that your changes probably haven't been reflected

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.50.1

### Shell

Windows Powershell

### Node version (run `node -v` if you're not sure)

v19.5.0

### What language and version are you using in your application?

Liquid (Theme)

**Comment by illarionvk** [comment]
I experience the same issue for `{% stylesheet %}` blocks when using `shopify theme deploy` and `shopify theme push` commands

**Comment by alvaro-shopify** [comment]
hey everyone 👋  !, thanks for raising up this issue. Let me redirect your question to the @Shopify/theme-code-tools team

**Comment by binarymonkey84** [comment]
@alvaro-shopify Has there been any progress on this? Looks like the issue has been auto closed...
