### ISSUE TITLE
[Bug]: 3.51.0 permission errors: Gem::FilePermissionError: You don't have write permissions for the /usr/local/bin directory.

### ISSUE THREAD

**Issue by njsaunders** [Shopify/cli#3102]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Shopify theme check complete succesfully.

### Actual behavior

An explosion of Gem errors.

### Verbose output

```shell
$ shopify theme check
── external error ──────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `bundle install`

Command failed with exit code 1: bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------


Gem::FilePermissionError: You don't have write permissions for the /usr/local/bin directory.
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:965:in `ensure_writable_dir'
  /usr/lib/ruby/vendor_ruby/rubygems/installer.rb:480:in `generate_bin'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/rubygems_gem_installer.rb:32:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:203:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:130:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:121:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.22/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.22
  Platforms   ruby, x86_64-linux
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-linux]
  Full Path   /usr/bin/ruby3.0
  Config Dir  /etc
RubyGems      3.3.5
  Gem Home    /var/lib/gems/3.0.0
  Gem Path    /home/circleci/.local/share/gem/ruby/3.0.0:/var/lib/gems/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/lib/ruby/gems/3.0.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.0.0:/usr/s
hare/rubygems-integration/3.0.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0
  User Home   /home/circleci
  User Path   /home/circleci/.local/share/gem/ruby/3.0.0
  Bin Dir     /usr/local/bin
OpenSSL
  Compiled    OpenSSL 3.0.2 15 Mar 2022
  Loaded      OpenSSL 3.0.2 15 Mar 2022
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools
  Git         2.41.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-11-09
Git SHA           ec2089640
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/home/circleci/.cache/shopify-gems-nodejs"
without
  Set via BUNDLE_WITHOUT: [:development, :test]
```

### Gemfile

# NOTE: These are development-only dependencies
source "https://rubygems.org"

gem "bugsnag", "~> 6.22"
gem "listen", "~> 3.7.0"
gem "theme-check", "~> 1.15.0"
gem "nokogiri", "~> 1.14.0"

# None of these can actually be used in a development copy of dev
# They are all for CI and tests
# `dev` uses no gems
group :development, :test do
  gem "pry-byebug"
  gem "byebug"
  gem "rubocop-shopify", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-rake", require: false
  gem "iniparse", "~> 1.5"
  gem "colorize", "~> 0.8.1"
  gem "bundler", ">= 2.3.11"
  gem "rake", "~> 12.3", ">= 12.3.3"
  gem "minitest", "~> 5.0"
end

group :test do
  gem "mocha", require: false
  gem "minitest-reporters", require: false
  gem "minitest-fail-fast", require: false
  gem "fakefs", ">= 1.0", require: false
  gem "webmock", require: false
  gem "timecop", require: false
  gem "rack", require: false
  gem "cucumber", "~> 7.0", require: false
end
```

### Gemfile.lock

```
<No /usr/local/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=You+don%27t+have+write+permissions+for+the+%2Fusr%2Flocal%2Fbin+directory.&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at
https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Installing racc 1.7.3 with native extensions
Fetching listen 3.7.1
Installing listen 3.7.1

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### Reproduction steps

1. Install 3.51.0
2. Shopify theme check

### Operating System

Ubuntu

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.51.0

### Shell

Bash

### Node version (run `node -v` if you're not sure)

20.9.0

**Comment by jefferyto** [comment]
I believe I have the same issue - after upgrading to 3.51.0, when I do `shopify theme pull` I see this:

```
Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle config set --local path 'vendor/bundle'
      bundle install

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password:
```

(I am using Ubuntu 23.10 with bundler 2.3.15, which still has the "auto-sudo" feature.)

3.51.0 includes 28e6290786b9e4554d6c874099d2b8f443d8d6da which, instead of setting the [`path` config option](https://bundler.io/v2.4/man/bundle-config.1.html#REMEMBERING-OPTIONS) with `shopifyGems.cache` (which is `envPaths('shopify-gems').cache`), sets the environment variable `BUNDLE_APP_CONFIG` with `envPaths('shopify-gems').cache`.

`BUNDLE_APP_CONFIG` affects where bundler loads its [configuration settings](https://bundler.io/v2.4/man/bundle-config.1.html), not where bundler installs gems. By not setting the `path` config option, bundler installs (or tries to install) gems to the default Rubygems setting; I haven't verified what this default path is exactly but I am fairly certain it is a system path (in /usr/local for OP).

So a workaround would be to place a `config` file in `BUNDLE_APP_CONFIG` (e.g. `/home/circleci/.cache/shopify-gems-nodejs/config`) with something like this:

```
---
BUNDLE_PATH: "/home/circleci/.cache/shopify-gems-nodejs"
```

This is the equivalent of running `bundler config set --local path /home/circleci/.cache/shopify-gems-nodejs` in the working directory `/home/circleci/.cache/shopify-gems-nodejs`. This should tell bundler to install gems in `/home/circleci/.cache/shopify-gems-nodejs` instead of the default (system) path.

**Comment by amcaplan** [comment]
Thanks everyone for the great detective work! I'm working on repro and fix, but in the meantime, it seems like anyone who hits this issue should use 3.50.

By the way, can I please confirm that everyone is using a Linux system? Seems like this doesn't come up on other OSes.

**Comment by GaryBleasdale** [comment]
The issue happened when running a CI pipeline in Azure, which uses Linux, yes.

**Comment by Haris014** [comment]
> Thanks everyone for the great detective work! I'm working on repro and fix, but in the meantime, it seems like anyone who hits this issue should use 3.50.
> 
> By the way, can I please confirm that everyone is using a Linux system? Seems like this doesn't come up on other OSes.

I have tried 3.50.2 but still same issue

**Comment by GaryBleasdale** [comment]
Works fine now on my end
