### ISSUE TITLE
npm run dev issue with VDI system

### ISSUE THREAD

**Issue by ohedeffem** [Shopify/cli#3114]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

App should installed and show to preview link. In Shopify Default code should run.

### Actual behavior

I am getting below error when running the npm run dev..
error="failed to dial to edge with quic: timeout: no recent network         │
│  activity"Could not start Cloudflare tunnel: Failed to create new quic connection     │
│  error="failed to dial to edge with quic: timeout: no recent network         │
│  activity"

### Verbose output

```shell
2023-11-16T16:57:20.271Z: Obtaining the dependency manager in directory C:/xampp/htdocs/banfield/adaptive-benchmark-app...
2023-11-16T16:57:20.321Z:
Running system process:
  · Command: ruby -v
  · Working directory: C:/xampp/htdocs/banfield/adaptive-benchmark-app

2023-11-16T16:57:20.476Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 79 ms
With response headers:
 - x-request-id: 1f30ee73-deb7-4110-b324-0aaa7dedbad0

2023-11-16T16:57:20.477Z: Analytics event sent: {
  "command": "app dev",
  "time_start": 1700153799795,
  "time_end": 1700153840193,
  "total_time": 40398,
  "success": false,
  "cli_version": "3.51.0",
  "ruby_version": "3.2.2",
  "node_version": "20.9.0",
  "is_employee": false,
  "uname": "windows amd64",
  "env_ci": false,
  "env_plugin_installed_any_custom": false,
  "env_plugin_installed_shopify": "[\"@shopify/app\",\"@shopify/cli\",\"@shopify/plugin-cloudflare\",\"@shopify/plugin-did-you-mean\"]",
  "env_shell": "cmd.exe",
  "env_device_id": "ec85a75939da0b339d6489cf6f9cc13e69dc44eb",
  "env_cloud": "localhost",
  "env_package_manager": "npm",
  "cmd_app_warning_api_key_deprecation_displayed": false,
  "cmd_app_all_configs_any": true,
  "cmd_app_all_configs_clients": "{\"shopify.app.toml\":\"2384a0bf5e1f50e7587b2ed599d6dd70\"}",
  "cmd_app_linked_config_used": true,
  "cmd_app_linked_config_name": "shopify.app.toml",
  "cmd_app_linked_config_git_tracked": true,
  "cmd_app_linked_config_source": "cached",
  "partner_id": 3206173,
  "api_key": "2384a0bf5e1f50e7587b2ed599d6dd70",
  "project_type": "php",
  "app_extensions_any": false,
  "app_extensions_breakdown": "{}",
  "app_extensions_count": 0,
  "app_extensions_custom_layout": false,
  "app_extensions_function_any": false,
  "app_extensions_function_count": 0,
  "app_extensions_theme_any": false,
  "app_extensions_theme_count": 0,
  "app_extensions_ui_any": false,
  "app_extensions_ui_count": 0,
  "app_name_hash": "568cb1a718d94cc07ea9db888b4468537fa1a1e6",
  "app_path_hash": "199555c41e943007539883bcd0816267cb30509c",
  "app_scopes": "[\"write_products\"]",
  "app_web_backend_any": true,
  "app_web_backend_count": 1,
  "app_web_custom_layout": false,
  "app_web_framework": "laravel",
  "app_web_frontend_any": true,
  "app_web_frontend_count": 1,
  "env_package_manager_workspaces": true,
  "cmd_all_timing_network_ms": 2535,
  "cmd_all_timing_prompts_ms": 0,
  "cmd_all_launcher": "npm",
  "cmd_all_topic": "app",
  "cmd_all_plugin": "@shopify/app",
  "cmd_all_verbose": true,
  "cmd_all_path_override": true,
  "cmd_all_path_override_hash": "199555c41e943007539883bcd0816267cb30509c",
  "cmd_app_dependency_installation_skipped": false,
  "cmd_app_reset_used": false,
  "cmd_all_timing_active_ms": 37862,
  "cmd_all_exit": "expected_error",
  "args": "--verbose",
  "error_message": "Could not start Cloudflare tunnel: Failed to create new quic connection error=\"failed to dial to edge with quic: timeout: no recent network activity\" \n\nCould not start Cloudflare tunnel: Failed to create new quic connection error=\"failed to dial to edge with quic: timeout: no recent network activity\" \n2023-11-16T16:56:58Z INF Retrying connection in up to 8s \n",
  "app_name": "adaptive-benchmark-app",
  "env_plugin_installed_all": "[\"@shopify/app\",\"@shopify/cli\",\"@shopify/plugin-cloudflare\",\"@shopify/plugin-did-you-mean\"]",
  "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
}
2023-11-16T16:57:20.487Z: Reporting handled error to Bugsnag: Could not start Cloudflare tunnel: Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity"

Could not start Cloudflare tunnel: Failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity"
2023-11-16T16:56:58Z INF Retrying connection in up to 8s

2023-11-16T16:57:20.516Z: Obtaining the dependency manager in directory C:/xampp/htdocs/banfield/adaptive-benchmark-app...
```

### Reproduction steps

1. I installed the repo https://github.com/Shopify/shopify-app-template-php 
2. I setup laravel as mentioned
3. I am trying to run command: npm run dev

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.51

### What language and version are you using in your application?

php 8.2

**Comment by alvaro-shopify** [comment]
hey @ohedeffem !, Thanks for rising up this issue. It seems that there's some kind of issue in your network infrastructure as the `dev` command is failing to create the `cloudflare` tunnel. Please check [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/deploy-tunnels/tunnel-with-firewall/) how to check your connectivity with the `cloudflare` servers and try to fix the issue
If you are not able to do it, please, create a `ngrok` tunnel manually and use the flag `--tunnel-url`
Please, let me know if this works for you

**Comment by ohedeffem** [comment]
Thank you @alvaro-shopify for your reply, Yes, seems like it's network issue but I have tried a ngrok custom tunnel but in this case, npm run dev command works but in app backend, it's showing the default code file as we connect ngrok with localhost portal.

I kept just created a ngrok tunnel based on my localhost code 
Ngrok setup:  https://62c8-20-186-86-82.ngrok-free.app -> http://localhost:8091 
NPM Setip: npm run dev -- --reset --tunnel-url https://62c8-20-186-86-82.ngrok-free.app:8091
It's worked in command line but in App background it's still showing the same. kindly check below screenshot: https://prnt.sc/-K-T4Sg_24_h

Please let me know if there is any other way to setup ngrok in my system as I may not get the firewall issue fixed due to some permission issue from admin level.

Thanks in advance.

**Comment by isaacroldan** [comment]
Hey @ohedeffem, the CLI uses a random port and creates a tunnel with cloudflare pointing to `http://localhost:{random_port}`
If you want to use a specific port then you are doing it right by using ngrok.

But I don't understand what's the new issue, what do you mean by "but in App background it's still showing the same"? Not sure what should I see in the screenshot :/
