### ISSUE TITLE
[Bug]: I can't remove a cart-transform function from my store in order to install a new one

### ISSUE THREAD

**Issue by fcarmonaEureka** [Shopify/cli#3118]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Function

### Expected behavior

I should be able to remove my cart-transform extension by running the cartTransformDelete graphQL mutation given by the Shopify GraphiQL App, as there can't be more than one cart-transform functions in the same store.

### Actual behavior

I'm getting a "Permission denied. Unauthorized app scopes." error when I try to run the mutation, so I can't install my new cart-transform function.

### Verbose output

```shell
{
  "data": {
    "cartTransformDelete": {
      "deletedId": null,
      "userErrors": [
        {
          "field": null,
          "message": "Permission denied. Unauthorized app scopes.",
          "code": "UNAUTHORIZED_APP_SCOPE"
        }
      ]
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 10,
      "actualQueryCost": 10,
      "throttleStatus": {
        "maximumAvailable": 10000,
        "currentlyAvailable": 9990,
        "restoreRate": 500
      }
    }
  }
}
```

### Reproduction steps

1. Install an app with a cart-transform extension following 
2. Run the cartTransformCreate mutation in the Shopify GraphiQL App as stated on the documentation
3. Uninstall the app
4. Install a new app with a new cart-transform function
5. Run the cartTransformCreate mutation in the Shopify GraphiQL App as stated on the documentation (get "An API client cannot have more than 1 cart transform functions per shop" error)
6. Run the cartTransformDelete mutation in the Shopify GraphiQL app and get "Permission denied. Unauthorized app scopes."

### Operating System

MacOS Sonoma

### Shopify CLI version (check your project's `package.json` if you're not sure)

Shopify CLI 3.0

### Shell

iTerm2

### Node version (run `node -v` if you're not sure)

v20.5.0

### What language and version are you using in your application?

Node v20.5.0

**Comment by PhilipBeauford** [comment]
Same error here, trying to remove a cart transform and "Permission denied. Unauthorized app scopes."

**Comment by amcaplan** [comment]
Hey folks, I think this issue is not really related to the CLI, and should instead be reported on the [Shopify Community](community.shopify.com).

I'm closing this issue, but strongly encourage you to follow up there.

**Comment by 220usamaahmed** [comment]
@fcarmonaEureka were you able to find a solution? I am having the same problem.

**Comment by rishabh-90** [comment]
@amcaplan can you please tell me what did you pass as gid I am not able to figure out objectName for it.
