### ISSUE TITLE
[Bug]: `shopify hydrogen build` fails to find `tailwind.config.ts` when supplying `--path` flag

### ISSUE THREAD

**Issue by tempor1s** [Shopify/cli#312]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Hydrogen custom storefront

### Expected behavior

When I supply the `--path` flag when using `dev shopify hydrogen build` the build will succeed and the Hydrogen project would be built.

Note: I also talked with @cartogram about this internally who recommended I submit a bug report, so he has more context of the slack conversation.

### Actual behavior

When I supply the `--path` flag when using `dev shopify hydrogen build` the build will fail due to not being able to find the vite config file (seemingly because its using the cli directory to look for that file which you can see in the stack trace).

### Stack trace

```shell
dev shopify hydrogen build --path ../hydrogen/templates/demo-store
👩‍💻  Running yarn shopify from dev.yml
yarn run v1.22.18
$ nx build cli-main && node packages/cli-main/bin/dev.js hydrogen build --path ../hydrogen/templates/demo-store

   ✔    9/9 dependent project tasks succeeded [4 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run cli-main:build

$ tsc -b ./tsconfig.build.json

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project cli-main and 9 task(s) it depends on (9s)

   Nx read the output from the cache instead of running the command for 4 out of 10 tasks.

⠙ Building client code
⠼ Building client code
◼ Building worker code
✓ 39 modules transformed.
✖ Cannot read properties of undefined (reading 'config')
◼ Building worker code
transforming (40) ../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js
━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Cannot read properties of undefined (reading 'config')

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

failed to load config from /Users/ben/src/github.com/Shopify/cli/vite.config.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction steps

There are two separate ways to produce this error:

1. `dev clone hydrogen` 
2. `dev cd cli`
3. `dev shopify hydrogen build --path ../hydrogen/templates/demo-store`

---

1. yarn create @shopify/hydrogen
2. `dev cd cli`
3. `dev shopify hydrogen build --path path/to/wherever/you/ran/the/create/command`

Screenshot for more context:
![image](https://user-images.githubusercontent.com/29741401/185259672-fce2f216-14ec-4837-8a78-05e265c0f402.png)

### Operating System

macOS Monterey 12.5

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.7.1

### Node version (run `node -v` if you're not sure)

v18.0.0

### What language and version are you using in your application?

N/A

**Comment by cartogram** [comment]
Turns out this is an issue with tailwind and postcss config resolution and I proposed a fix in April.  https://github.com/Shopify/hydrogen/pull/1051 

Ultimately it was rejected for reasons that I still are relevant today.

I'd like to explore alternative ideas that do not require the user to modify their tailwind/postcss configs.

**Comment by cartogram** [comment]
@tempor1s in the meantime, can you use the following command instead. It should not hit the same error:

```
dev shopify hydrogen build --path ../hydrogen/templates/hello-world 
```

**Comment by cartogram** [comment]
@tempor1s does that path exist? In other words, have you cloned the hydrogen monorepo?
