### ISSUE TITLE
Unable to Run Shopify CLI Commands Without 'npx'

### ISSUE THREAD

**Issue by TonyEpicIT** [Shopify/cli#3129]
I'm new to Shopify CLI and Shopify theme development. I've diligently followed the documentation and successfully installed Ruby and Bundler, which were prerequisites for the setup. However, the main challenge I'm currently encountering is that I'm unable to execute any Shopify CLI commands without prefixing them with 'npx.'

I've already added the correct path to the system environment variables, and I've double-checked it, but unfortunately, the issue persists.

Could anyone please provide guidance on how to resolve this issue?

**Path location:**
`C:\Program Files\nodejs\node_modules\@shopify\cli`

more info:
**Windows terminal Error:**
```
shopify : The term 'shopify' is not recognized as the name of a cmdlet, function, script file, or operable program. Che
ck the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ shopify
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (shopify:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```    

    
  **Bash Terminal VSCode Error:**
`  bash: shopify: command not found`

**Comment by amcaplan** [comment]
How did you install the Shopify CLI itself?

**Comment by TonyEpicIT** [comment]
> How did you install the Shopify CLI itself?

Using npm install -g @shopify/cli @shopify/theme

**Comment by TonyEpicIT** [comment]
> How did you install the Shopify CLI itself?

Okay, for some reason, my NPM global config prefix was set to a 'C:\' location. I changed it to:

`npm config set prefix C:\Program Files\nodejs`

After that, I ran:

`npm install -g @shopify/cli @shopify/theme`

And everything worked smoothly.
