### ISSUE TITLE
[Bug]: Custom fonts in assets directory causing OTS parsing error

### ISSUE THREAD

**Issue by mzachdev** [Shopify/cli#3144]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Font files added to the assets directory should upload to the server on push, and be usable with an @font-face reference immediately with no errors in the browser's console blocking dev. 

### Actual behavior

When adding custom font files to my assets directory locally, then running `shopify theme dev --theme-editor-sync` the font files are uploaded to the temp dev server, but in the console I get this error: 

```
Failed to decode downloaded font: http://127.0.0.1:9292/cdn/shop/t/8/assets/Bayard-Regular.woff2?v=135843728640516025251700896606
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
```

What does this mean? Why do custom fonts added to the assets directory cause this to happen? This error is blocking my custom fonts from working on the frontend during development.

FYI this is a known issue [https://community.shopify.com/c/technical-q-a/has-anyone-else-had-issues-with-corrupted-woff-or-woff2-files/m-p/1732103]

If I add the font files to Files using the admin side that works, and instead of `asset_url` I use `file_url` but this should work without admin access, using assets directory instead.

### Verbose output

```shell
n/a
```

### Reproduction steps

1. Add font files to assets directory
2. Create `@font-face` rule with link to font file using `asset_url`
3. Run `shopify theme dev` and check the browser's console to see if the font pushed is causing an error to appear

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

v3.50.2

### Shell

Bash, Powershell

### Node version (run `node -v` if you're not sure)

v18.17.1

### What language and version are you using in your application?

Ruby v31

**Comment by mzachdev** [comment]
On further investigation, it seems even when I upload the font files to Files in the admin and use `file_url` it still shows that error in the console. Or, it shows `405 (Method Not Allowed)` after the URL, which is even more mysterious.

For reference:

Works: `src: url('../assets/BAYARD-Regular.woff2') format('woff2');`
Works: `src: url('https://cdn.shopify.com/s/files/1/0790/0689/2327/files/Bayard-Regular.woff2?v=1700907223') format('woff2');`

Doesn't work: `src: url("{{ 'BAYARD-Regular.woff2' | asset_url }}") format('woff2');`
Doesn't work: `src: url("{{ 'BAYARD-Regular.woff2' | file_url }}") format('woff2');`

**Comment by mzachdev** [comment]
According to your own docs, these methods should work:

`src: url("{{ '[font-file-name]' | file_url }}") format("[font-format]");`
and
`src: url("{{ '[font-file-name]' | asset_url }}") format("[font-format]");`

**Comment by gonzaloriestra** [comment]
Hi! Thanks for creating the issue. Let me ping my colleagues from @Shopify/theme-code-tools

**Comment by mzachdev** [comment]
Hi @gonzaloriestra, did you hear back from your colleagues at @shopify/theme-code-tools? This is a major issue, in my opinion, and hoping it can get resolved in the next update.

**Comment by mzachdev** [comment]
A small follow-up: the error does not occur in the theme dev customizer, only on the frontend. If I upload the fonts to the Content > Files area in the Shopify admin, then use those URLs instead of trying to use `asset_url` then it works in both the customizer and frontend. But I still think there's a custom font in assets directory bug.

**Comment by jamiestead** [comment]
Hi @lukeh-shopify thanks for the response.
We are running a custom set up using webpack and a few other plugins for our custom theme, so our commands are different.

I was loading my custom fonts in a snippet in the HEAD of the site and this has been working fine for weeks, then last week I updated Shopify CLI (due to it causing an issue where it was opening the published site locally rather than my actual dev site) and that's when I started getting the font errors as mentioned by other users here. The errors only appear on the local preview (127.0.0.1:9292) and not on the Preview link (https://storename.myshopify.com/?preview_theme_id=123456789 or the Admin preview link) where the fonts work fine.

I've removed the font code from my snippet in the header and moved it into a standard CSS file which loads along with all other CSS and no longer get the errors and the fonts load correctly on the local preview (127.0.0.1:9292). 

Strange that these errors only show on the local preview and not the standard preview, both generated by Shopify CLI. And this error only seems to have started after updating CLI. I'm the only dev at our company using Windows (11) and the devs on Linux and MacOS don't get this problem.

**Comment by mgmanzella** [comment]
👋 thanks for following up on this issue, we're investigating why this is appearing again in the new version. 

when this error occurs, do you mind also sharing the request headers for the font in local preview?? we're particularly interested in the `Content-Type` header (please remove anything sensitive like access tokens 🙏 )

**Comment by muchisx** [comment]
+1 Getting this issue aswell. 

`.woff2` font file hosted in the `/assets` directory of an existing theme connected through the Github Integration. Remote Preview works but local development does not work, sending parsing OTS errors as OP mentions.


![image](https://github.com/Shopify/cli/assets/34131801/726ff584-331c-4c38-877d-c48f0fd705e0)

**Comment by tairli** [comment]
Looks like this is not CLI or Github integration related -- I've tried uploading fonts manually to Assets and output CSS with Custom liquid section.
Luckily it worked fine with fonts in FIles.

[https://community.shopify.com/c/shopify-design/custom-fonts-in-symmetry/m-p/2640577#M692933](https://community.shopify.com/c/shopify-design/custom-fonts-in-symmetry/m-p/2640577#M692933)

**Comment by muchisx** [comment]
This is still an issue, does not work on files in the `/assets` folder. Unrelated to doing it from the `Files` in the Shopify Admin.
