### ISSUE TITLE
[Bug]: "spawn Unknown  error" when running "npm run dev" on new app

### ISSUE THREAD

**Issue by arslan308** [Shopify/cli#3148]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Running npm run dev should start up a dev server to preview my app   

### Actual behavior

throws an error which says "Spawn Unkown"

### Verbose output

```shell
spawn UNKNOWN                                                                                       │
│                                                                                                      │
│  To investigate the issue, examine this stack trace:                                                 │
│    at spawn (node:internal/child_process:413)                                                        │
│    at spawn (node:child_process:757)                                                                 │
│    at baseOpen (open/index.js:224)                                                                   │
│      const subprocess = childProcess.spawn(command, cliArguments, childProcessOptions);              │
│    at async openURL (@shopify/cli-kit/src/public/node/system.ts:30)                                  │
│      await externalOpen.default(url)                                                                 │
│    at async authorize (@shopify/cli-kit/src/private/node/session/authorize.ts:46)                    │
│      await openURL(url)                                                                              │
│    at async executeCompleteFlow (@shopify/cli-kit/src/private/node/session.ts:199)                   │
│      const code = await authorize(scopes)                                                            │
│    at async ensureAuthenticated (@shopify/cli-kit/src/private/node/session.ts:135)                   │
│      newSession = await executeCompleteFlow(applications, fqdn)                                      │
│    at async ensureAuthenticatedPartners (@shopify/cli-kit/src/public/node/session.ts:43)             │
│      const tokens = await ensureAuthenticated({partnersApi: {scopes}}, env, options)                 │
│    at async fetchPartnersSession (@shopify/app/src/cli/services/context/partner-account-info.ts:39)  │
│      const token = await ensureAuthenticatedPartners()                                               │
│    at async prepareForDev (@shopify/app/src/cli/services/dev.ts:77)                                  │
│      const partnersSession = await fetchPartnersSession()
```

### Reproduction steps

1. Following Shopify's tutorial on setting up a checkout ui extension. Run npm init @shopify/app@latest
2. cd into app directory
3. npm run shopify app generate extension
4. Hit enter. Error is thrown

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

Tried latest & also v3.23.0

### Shell

CMD

### Node version (run `node -v` if you're not sure)

v18.16.0

### What language and version are you using in your application?

Node 18.16.0

**Comment by gonzaloriestra** [comment]
Hi! I'm not able to reproduce with a similar environment, but it looks like it's crashing when trying to open a browser to log in.

Could you try with another shell like Powershell? If it doesn't work, you can also try to set up the environment variable `SHOPIFY_CLI_DEVICE_AUTH=1`, which will cause the CLI to show a URL to log in, instead of opening the browser.

**Comment by arslan308** [comment]
Hi, yeh I did fix it, its due to anti virus, you need to disable it or use the ubuntu app if you are on windows.

**Comment by saifyyy** [comment]
Thanks @arslan308 I fixed the issue. I just set the variable in node environment `$env:SHOPIFY_CLI_DEVICE_AUTH=1`
and then its working fine
