### ISSUE TITLE
[Bug]: theme translations lost when pushing theme with Shopify GitHub integration

### ISSUE THREAD

**Issue by MaxDesignFR** [Shopify/cli#3165]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Theme translations should be preserved.

### Actual behavior

Theme translations are lost. It seems translations and Shopify github integration can't coexist right now. There was a similar issue: https://github.com/Shopify/cli/issues/1562 which seems to show we can manually duplicate a translated theme in Shopify backoffice to preserve the "translation link", and then push changes to that duplicated theme (works, but still not ideal and confusing). 

But this is incompatible with github workflow which uploads a new theme every time we may need to add a new branch. I find this very problematic and haven't found any workaround.

### Verbose output

```shell
NA
```

### Reproduction steps

1. Translate theme (such as templates) in Shopify Translate & Adapt
2. `shopify theme pull` to work locally
3. Publish the local theme to a git repository
4. Add theme to store with "Connect from GitHub"

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.4

**Comment by danilichti** [comment]
Same issue here! Really hope this gets fixed soon!

**Comment by MaxDesignFR** [comment]
Still relevant

**Comment by danilichti** [comment]
Same, still relevant!

**Comment by pasquinphilippe** [comment]
Any updates on this issue? 

Driving me crazy (and clients)

**Comment by stephansp** [comment]
Yes, still relevant!!

**Comment by mgmanzella** [comment]
👋 the team is aware of this issue. in the meantime they shared this workaround to hopefully ease the friction of copying translations via CSV https://community.shopify.com/c/shopify-translate-adapt/why-did-my-theme-update-erase-most-translations/m-p/2016134#M628

**Comment by nboliver-ventureweb** [comment]
@mgmanzella This is still a ongoing issue that creates significant challenges for live stores. Closing a critical issue for "CLI housekeeping" is doesn't make it go away.
