### ISSUE TITLE
When using the CLI flow for an existing application, you can only select from the first five pages of apps in your partner dashboard

### ISSUE THREAD

**Issue by greenlemur** [Shopify/cli#317]
Problem:

When using the CLI flow for an existing application, you can only select from the first five pages of apps in your partner dashboard

<img width="690" alt="Screen Shot 2022-08-18 at 1 26 46 PM" src="https://user-images.githubusercontent.com/60752324/185460308-7412c5fb-5301-41d7-aab5-4cbfd31ab221.png">

^ You can only go as far down as the first five pages of apps in your partner dashboard. Anything beyond that will not show up in the terminal as an option to choose from. We have 11 pages of apps in our partner account (partner ID: 1362879).

**Comment by amcaplan** [comment]
@alvaro-shopify I think this is a legit issue. [We only retrieve the first 100 apps](https://github.com/Shopify/cli/blob/c54f708c59665ad4d1769a2422c2d47bdaa41997/packages/cli-kit/src/api/graphql/find_org.ts#L11) for the organization, there's no pagination beyond that.

**Comment by amcaplan** [comment]
@greenlemur thanks for bringing this case to our attention. Until it's solved, I believe there is a workaround, at least for `dev`. If you open your app's page in the admin, you'll see the API key. Copy that key, and pass it to the command using the flag `--api-key=YOURAPIKEY`.

There is no such flag for `deploy` but we've considered adding once, here's another reason to push in that direction. /cc @isaacroldan

**Comment by isaacroldan** [comment]
Yes, using the `--api-key` flag is the best (or only) workaround for this. @amcaplan not sure why we don't have this flag for deploy but I think we should! 
Maybe create a ticket for the next cycle?

**Comment by amcaplan** [comment]
@greenlemur I know it isn't the best solution, but for now note that support for the `--api-key` flag in `deploy` has been [merged](https://github.com/Shopify/cli/pull/412) and released in the latest version, 3.10.0. So you have a solid workaround for now.
