### ISSUE TITLE
Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by Natanael-Exe** [Shopify/cli#3189]
# Issue summary

After installation, when i run yarn dev, I got this error:
<img width="1290" alt="Screenshot 2023-12-10 at 2 07 55 PM" src="https://github.com/Shopify/shopify-app-template-node/assets/42002702/dd1e7ae6-2f06-40cb-916f-ea7c25bbbfca">

- `@shopify/shopify-app-express` version:^2.1.3
- Node version:18
- Operating system:MacOs

**Comment by matteodepalo** [comment]
@Shopify/cli-foundations

**Comment by remy727** [comment]
@isaacroldan,
here are the reproduction steps:
1. `yarn create @shopify/app --template=node`
2. `yarn dev`

Here are versions:
- Node: `21.5.0`
- shopify/cli: `3.53.0`
- OS: macOS

**Comment by isaacroldan** [comment]
Ah! good call, Shopify Apps need React 18+ 
Closing this issue then :)
