### ISSUE TITLE
[Bug]: Error: Unable to obtain an available random port number

### ISSUE THREAD

**Issue by jhealey5** [Shopify/cli#321]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Following the guide here, at this step https://shopify.dev/apps/tools/cli/migrate#step-4-connect-your-app-to-the-partner-dashboard

Should connect an app to the store.

### Actual behavior

Running `npm run dev` results in the following 
<img width="693" alt="image" src="https://user-images.githubusercontent.com/1771431/185616788-3d39b48f-6fa0-450b-97dc-1e4589cd87e9.png">

### Reproduction steps

1. Follow guide here on a blank folder

### Operating System

Mac Os 12.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

Shopify 3.7.1

### Node version (run `node -v` if you're not sure)

v18.5

**Comment by alvaro-shopify** [comment]
Hi!. Thank you for opening this issue. Please, could you run the command with the `--verbose` flag?. It seems there is a problem to obtain the random port used by the frontend service to serve the requests.

**Comment by amcaplan** [comment]
Hi @jhealey5, I'm not sure what @alvaro-shopify is looking for but I wanted to add that this issue crops up from time to time, and it might be related to the script for `dev` in your `package.json`. You might have taken this:

```
  "scripts": {
    "shopify": "shopify",
    "build": "shopify app build",
    "dev": "shopify app dev",
    "info": "shopify app info",
    "scaffold": "shopify app scaffold",
    "deploy": "shopify app deploy"
  },
```

which is the outer `package.json` and placed it into your frontend's `package.json` instead, which would cause infinite recursion and eventually running out of open ports. Make sure your frontend's `package.json` looks something like this:

```json
  "scripts": {
    "build": "tsc && vite build",
    "dev": "vite",
    "serve": "vite preview"
  },
```

where `dev` is a specific, non-`shopify` command.

**Comment by andreydrozd** [comment]
@jhealey5 @jeremyplt and anyone else who comes across this thread, check if you don't have `HOST` set as a system env to some public IP. 

Through the process of using Shopify I had somehow set `HOST` as a system env to my ngrok URL and so the `get-port-please` package that tries to get a random port number would try to get a port on the ngrok URL. 

The library default parameter for a host is process.env.HOST (https://github.com/unjs/get-port-please/blob/0c284cc310a49b72b43e2de9ed7dd736e0f250c2/src/index.ts#L122). Unset that env and the library will get a port on your localhost.

I think explicitly passing in localhost as the host in the `getRandomPort` function of the CLI would prevent this kind of error.

**Comment by andreydrozd** [comment]
FYI, it seems like the Shopify CLI sets the `HOST` env to the ngrok url. I was working on my CLI v3 app template yesterday and when I tried to run local again this morning, I got the "Unable to obtain an available random port number" error.

**Comment by shauns** [comment]
Hi -- the environment variables used in `dev` are documented here: https://shopify.dev/apps/tools/cli/structure#web-component-conventions

In CLI3 we pass `HOST` over when running `dev`, but we don't set it anywhere permanently on your system.

Thank you for the tip on `get-port-please` -- will get a fix scheduled!
