### ISSUE TITLE
[Bug]: Shopify CLI3 Cannot run theme extension

### ISSUE THREAD

**Issue by Chang1ng** [Shopify/cli#3210]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

"pnpm run"command  can normal operation.

### Actual behavior

<img width="1103" alt="image" src="https://github.com/Shopify/cli/assets/6593784/eeebb39c-5325-4838-b4f1-a5af0d981c6d">
<img width="805" alt="image" src="https://github.com/Shopify/cli/assets/6593784/930a67c3-60b2-4a18-8b36-b73efb55a744">

### Verbose output

```shell
ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "dev" not found
```

### Reproduction steps

1.pnpm init
2.pnpm i @shopify/app @shopify/cli
3.pnpm exec shopify app generate extension
4.pnpm dev

### Operating System

mac os

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.52.0

### Shell

iterm2

### Node version (run `node -v` if you're not sure)

20.9.0

### What language and version are you using in your application?

ruby2.7.5

**Comment by amcaplan** [comment]
Yes, this is why we [recommend](https://shopify.dev/docs/apps/app-extensions/extension-only-apps#create-an-extension-only-app) using `pnpm create @shopify/app` and select the extension-only option (i.e. no app home) if you want to create an extension-only app.

**Comment by amcaplan** [comment]
Closing as I don't think there's much more to add here.

Bottom line, create an app using the official instructions, don't try to roll your own.
