### ISSUE TITLE
[Bug]: shopify theme push unable to create context files on first push

### ISSUE THREAD

**Issue by tommypepsi** [Shopify/cli#3213]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When creating a new theme using `shopify theme push` I'm expecting files to be created in order based on dependency so that context files are created after the main template file it relies on.

### Actual behavior

When creating a new theme with `shopify theme push`, context files fails to create as they are uploaded before the main template json file they depend on.

![image](https://github.com/Shopify/cli/assets/926715/30659cf2-cdb5-4576-9eb8-b2822659d363)

We are using shopify CLI in our CI environment to create preview themes for our PRs, we've been doing this for a couple years now, but since the introduction of context files our GitHub actions are throwing errors. We've ignored it for a while since context files were not used much yet but now it's starting to be an issue.

### Reproduction steps

1. Add context files for a template
2. Delete your development theme
3. Deploy the theme using `shopify theme push --development`

### Operating System

windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.50.2

**Comment by kenji-twp** [comment]
I'm having the same issue here
