### ISSUE TITLE
[Feature]: use process env on ci/cd

### ISSUE THREAD

**Issue by michaelr231** [Shopify/cli#3217]
### What area(s) will this request affect?

App, Extension, Theme

### What type of change do you want to see?

New feature

### Overview

how we can use different vars like process.env vars in ci cd deploy?

### Motivation

robust process env support like

**Comment by amcaplan** [comment]
Hi @michaelr231, perhaps you can be a bit more detailed about what you'd like?

You should be able to use any ENV variables you want, though the CLI only looks for certain ones which are relevant to its function.

**Comment by michaelr231** [comment]
for example
i use shopify cli to deploy checkout extensions
and i have 3 different envs: dev, stage and prod
each env has their own url 

i want to ues github action deployment file for ci cd but i need to pass 
the relevant url
i cannot find a way to pass variables like process env or even use secrets to pass them into shopify app deploy command
hope it was clear
Thanks
