### ISSUE TITLE
[Bug: shopify cli You have reached the limit for the number of extensions you can create

### ISSUE THREAD

**Issue by tienvv1234** [Shopify/cli#3219]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

1. Create a fresh app using npm init @shopify/app@latest
2. Choose node
3. After completion, cd to app dir
4. Run npm run shopify app generate extension
5. CLI proceeds and allows me to choose the type of extension to create

### Actual behavior

Instead of allowing me to choose the type of extension to create, CLI displays error:
```
You have reached the limit for the number of extensions you can create.
```
![image](https://github.com/Shopify/cli/assets/34591094/af7713ff-3e2c-4e7c-a19c-fa4a1518eb18)

I am using Node.js version 18.18.1 on Ubuntu and I encountered this error as well. However, on my MacBook, which has the same Node.js version 18.18.1 and Shopify CLI version 3.52, everything is working fine.

### Verbose output

```shell
pnpm shopify app generate extension

> max-1k@ shopify /home/tien/Desktop/javis's works/max-1k
> shopify "app" "generate" "extension"

╭─ info ─────────────────────────────────────╮
│                                            │
│  Using shopify.app.toml:                   │
│                                            │
│    • Org:          home                    │
│    • App:          max-1k                  │
│                                            │
│   You can pass `--reset` to your command   │
│  to reset your app configuration.          │
│                                            │
╰────────────────────────────────────────────╯

╭─ error ────────────────────────────────────╮
│                                            │
│  You have reached the limit for the        │
│  number of extensions you can create.      │
│                                            │
╰────────────────────────────────────────────╯

 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction steps

1. Create a fresh app using npm init @shopify/app@latest
2. Choose node
3. After completion, cd to app dir
4. Run npm run shopify app generate extension

### Operating System

Ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.52

### Node version (run `node -v` if you're not sure)

v18.18.1

### What language and version are you using in your application?

node

**Comment by liam997** [comment]
You can only create 1 theme app extension per app.

Like in this issue: https://github.com/Shopify/cli/issues/3069

**Comment by tienvv1234** [comment]
Hi @isaacroldan could you give me a solution for this issue
