### ISSUE TITLE
CLI Crashing when creating new app after the release of new prisma-store-adapter version

### ISSUE THREAD

**Issue by Shine18** [Shopify/cli#3245]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should create a new app with latest versions

### Actual behavior

I think it is because of the new version release.

Peer dependency error when shopify runs npm install in the creation process of the app

peer @shopify/shopify-api@"^9.0.1" from @shopify/shopify-app-session-storage-prisma@2.0.3
npm ERR! node_modules/@shopify/shopify-app-session-storage-prisma
npm ERR!   @shopify/shopify-app-session-storage-prisma@"^2.0.0" from the root project
npm ERR!
image

### Verbose output

```shell
── external error ──────────────────────────────────────────────────────────────────────────

Error coming from `npm install`

Command failed with exit code 1: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: efficient-conversion-app@undefined
npm ERR! Found: @shopify/shopify-api@8.1.1
npm ERR! node_modules/@shopify/shopify-api
npm ERR!   @shopify/shopify-api@"^8.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @shopify/shopify-api@"^9.0.1" from @shopify/shopify-app-session-storage-prisma@2.0.3
npm ERR! node_modules/@shopify/shopify-app-session-storage-prisma
npm ERR!   @shopify/shopify-app-session-storage-prisma@"^2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/shine18/.npm/_logs/2024-01-10T20_56_50_148Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/shine18/.npm/_logs/2024-01-10T20_56_50_148Z-debug-0.log

────────────────────────────────────────────────────────────────────────────────────────────
```

### Reproduction steps

1.Run the command `npm init @shopify/app@latest `
2.Follow all the steps to create an app in Remix and Javascript

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.32.1

**Comment by kaczors** [comment]
I have the same issue.

**Comment by kaczors** [comment]
Sorry, on the newest version and

❯ npm --version
9.2.0
❯ node --version
v19.4.0

works fine now.

**Comment by miketu926** [comment]
I am getting the same error... and currently on below:

❯ npm --version
10.2.4
❯ node --version
v21.6.0

is there a quick way to update these dependencies on an ongoing basis, like do a routine check? something like npm update @shopify/app@latest or something........
