### ISSUE TITLE
[Bug]: Issue running npm run deploy (javy)

### ISSUE THREAD

**Issue by meandillar** [Shopify/cli#3252]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Function

### Expected behavior

Running `npm run deploy` should deploy a new version of my product discount function

### Actual behavior

Similar to the issue #2626 (closed)

Output after running `npm run deploy` is:

```
Error coming from `npm exec -- javy --version`

Command failed with exit code 2: npm exec -- javy --version
Downloading javy failed with status code of 404
Downloading javy v1.3.0 to /Users/[user]/Library/Caches/binarycache/javy-v1.3.0
```

Output of `npm list javy-cli` is:

```
[app-name]@ /Users/[user]/path
└─┬ @shopify/app@3.53.0
  └── javy-cli@0.1.8
```

Downgrading to `@shopify/app` and `@shopify/cli` to v3.50.0 works.

### Verbose output

```shell
Let me know if you need this, I've already reverted to previous version.
```

### Reproduction steps

1. Upgrade existing project from `@shopify/app` and `@shopify/cli` versions 3.50.0 to 3.53.0
2. Run `npm run deploy` to deploy existing product discount function

### Operating System

Mac OS Sonoma v14.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.53.0

### Node version (run `node -v` if you're not sure)

20.9.0

**Comment by amcaplan** [comment]
`javy-cli` uses GitHub releases to download the files. I can see that javy 1.3.0 was released close to the time this error happened for you. So it's not unlikely that the release was created when you posted this, but the artifact wasn't uploaded just yet.

I recommend just trying again and seeing what happens.

**Comment by meandillar** [comment]
@amcaplan thanks, tried now and it works :)

**Comment by novayadi85** [comment]
How about MacOs less then 14.x ? how to fix this issue? Is that possible?

**Comment by novayadi85** [comment]
> How about MacOs less then 14.x ? how to fix this issue? Is that possible?

I've fixed this problem on my Mac OS Catalina with FORCE_RELEASE=v1.4.0 npx javy-cli@latest 
So far no problem with my application. 
Thanks!

**Comment by jenhacool** [comment]
For anyone still got this problem, here's how I've fixed this problem on Mac M1 (OS 11.x)

1. Download javy v1.4.0 from releases page [here](https://github.com/bytecodealliance/javy/releases/tag/v1.4.0) and rename to "javy"
2. Replace javy file from "node_modules/@shopify/cli" folder with above file
3. Update permission for updated file with this command `chmod 775 node_modules/@shopify/cli/javy`

I know that's bad solution but it worked.

Thanks!
