### ISSUE TITLE
[Bug]: Tunnel option gloms onto port causing issues

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#3259]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I have a foreman script that opens a tunnel, assigned to my App, directing traffic to localhost on a port. The process also starts a basic web server on that port listening to localhost. When I run shopify app dev script on MacOS, assigning the tunnel-url parameter, it works fine. However, if I run this exact scripting on Linux, it fails. 

I am testing by using Linux as my OS and have Puma setup such that my Rails App works when I start with foreman start -f Procfile.dev which opens the webserver, compiles assets and opens an NGrok tunnel. My MacOS machine runs the same setup. BUT, on MacOS I can use the yarn dev command too! 

```
 "dev": "shopify app dev --tunnel-url=https://myapp.ngrok.io:3206",
```

So on my MacOS machine, both using foreman or yarn dev works!, and like magic, because my Linux machine is on the same wifi network, if I access the App on my laptop it too all works when MacOS started with yarn dev. So I am so close to glory.

However, if I start the tunnel on the Linux machine with yarn dev, my web server is blocked from running! I get this message from Puma!

/home/leo/.rbenv/versions/3
.2.2/lib/ruby/gems/3.2.0/gems/puma-6.3.0/lib/puma/binder.rb:334:in `initialize':
Address already in use - bind(2) for "127.0.0.1" port 3206 (Errno::EADDRINUSE)

I am not sure why the Linux setup has a problem that MacOS does not exhibit. This is my last blocker to getting Puma Dev style tunneled development (with ngrok) working. Can anyone help me to try and debug this issue with Linux and Puma?

The ONLY thing blocking Linux from working is the tunnel-url in the DEV scripting. Someone, on Linux, it is glomming onto the localhost at the port which then blocks the webserver from using localhost and the same port. WHY????

### Actual behavior

Address already in use - bind(2) for "127.0.0.1" port 3206 (Errno::EADDRINUSE)

### Verbose output

```shell
$ yarn dev
....
/home/leo/.rbenv/versions/3
.2.2/lib/ruby/gems/3.2.0/gems/puma-6.3.0/lib/puma/binder.rb:334:in `initialize':
Address already in use - bind(2) for "127.0.0.1" port 3206 (Errno::EADDRINUSE)
```

### Reproduction steps

1. start app in MacOS with yarn dev, it all works
2. start same app in Linux with yarn dev, it fails to start the web service
3.

### Operating System

MacOS, Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.52

### Shell

ZSH

### Node version (run `node -v` if you're not sure)

21.5

### What language and version are you using in your application?

Ruy 3.2.2

**Comment by isaacroldan** [comment]
Hi @resistorsoftware!

So the way the CLI works is that it either creates a tunnel to an internal port or expects to receive those values as flags.
Then it crates a proxy server listening to that port, the proxy redirects the traffic to your app and/or extensions.

So if you pass ` --tunnel-url=https://myapp.ngrok.io:3206`, the CLI will try to create a server that listens at port 3206. Because that's where external calls are going to be redirected to, so If there is something else there it won't work.

Per your comment:
> I have a foreman script that opens a tunnel, assigned to my App, directing traffic to localhost on a port. The process also starts a basic web server on that port listening to localhost

If you are already starting a process in that port, then the CLI can't use it. So I'd say that linux behavior is correct and Mac shouldn't work?

Does this makes sense? 
Can you try your linux flow without starting that extra process in that port?
I'm assuming that you are creating your ngrok tunnel to redirect to port 3206 right?

**Comment by resistorsoftware** [comment]
ngrok tunnel was tricky as they recently changed all their options but yes, I nailed that. For anyone that wants to know it, a Procfile.dev could be:

```
web: bin/rails s
js: yarn build --watch
tunnel: ngrok http --domain=myapp.ngrok.io 3206
```

The BIG killer that does not affect MacOS but affected Linux was me inadvertently, naively having a PORT=3206 in the shopify.web.toml file. Removed that and bingo, it worked. Why  felt the need to place a PORT in that file is probably due to not understanding the docs on this parameter and it's real use.

**Comment by resistorsoftware** [comment]
@isaacroldan I have many many Apps and I have not checked them all, but it is entirely possible that this is indeed the case, the only one that had a PORT set in the dot toml file. I suppose better documentation and an example of when, how and why one would use the PORT value could go a long way to ensuring no one else experiences this pain I did with the tunnels.
