### ISSUE TITLE
[Bug]: Access Token does not work

### ISSUE THREAD

**Issue by omerycll** [Shopify/cli#3261]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I created a new app and a new store. I installed the app from the store and bought the access token from the terminal and tested it, it does not work.

### Actual behavior

After the last update, there are major errors in the admin graphql and access token sections, I downgrade to the old version, but it does not fix it.

### Verbose output

```shell
[API] Invalid API key or access token (unrecognized login or wrong password)
```

### Reproduction steps

1.
2.
3.

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.53.0

### Shell

iTerm2

**Comment by gonzaloriestra** [comment]
Hi!

I don't fully understand what you are trying to do. Where are you taking that access token and how are you using it? Could you share detailed reproduction steps?

Thanks.

**Comment by punitOjha1729** [comment]
@gonzaloriestra @omerycll i created an app using **npm init @shopify/app@latest
** i did not change anything in the code 

i get offline_session which is saved in db

and then using the access token when i make a curl request to get orders with the access token recieved i get the same error

**Comment by gonzaloriestra** [comment]
The tokens created by the CLI are meant to be used by the CLI and don't have enough permissions for what you want.

To retrieve data like orders, the easiest way is to use the new integrated [GraphiQL tool](https://shopify.dev/docs/apps/tools/graphiql-admin-api).

**Comment by punitOjha1729** [comment]
@gonzaloriestra i did the changes even on the installed app it shows that permissions but it does not work

**Comment by gonzaloriestra** [comment]
Have you reinstalled the app? The new permissions need to be approved.

**Comment by punitOjha1729** [comment]
Steps to reproduce the error: 
1. run npm init @shopify/app@latest

2. change the scopes in shopify.app.toml to 
scopes="write_products,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_customers,read_fulfillments,write_fulfillments,read_locations,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,write_orders,read_shipping,write_shipping,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,unauthenticated_read_customers"

3. npm run dev

4. select the store and install it 

5. token is generated and shows that the scope is as per requirmeents 

6. when i use cURL: curl -X GET "https://<shop>.myshopify.com/admin/api/2024-01/orders.json?status=any" -H "X-Shopify-Access-Token: <my_access_token>" then i get the error : 
"errors": "[API] This app is not approved to access REST endpoints with protected customer data. See https://partners.shopify.com/3378262/apps/81685217281/customer_data for more details."

7. I go to the page given in the above error link when i save the requirement in 1st step it shows GraphQL Error unable to save
