### ISSUE TITLE
[Bug]: 413 Payload Too Large on 1,873 KB file with theme CLI

### ISSUE THREAD

**Issue by peepers-rick** [Shopify/cli#3268]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

File (`assets/section-filters-native.min.js`) should upload on save via `shopify theme dev` as it's only 1,873 kb

### Actual behavior

413 Payload Too Large file. It works with this file sometimes but not other times. Larger files work fine.

### Verbose output

```shell
DEBUG PUT https://<censored>.myshopify.com/admin/api/unstable/themes/<censored>/assets.json with request_id: 55a00c08-e9b9-447c-9bd1-f688d81ecf22
  • 13:05:05 ERROR  » update assets/section-filters-native.min.js:
  413
Payload Too Large
```

### Reproduction steps

1. run `shopify theme dev`
2. make edit to file
3. watch upload fail

### Operating System

wsl-x64 (ubuntu)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.53.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

20.9.0

**Comment by peepers-rick** [comment]
Same behavior when I try to just copy and paste the contents of the file into the theme editor and save. If I observe the network tab in Chrome dev tools, I can get the headers and whatnot. FWIW, the UI is broken here, too. "Save" button never recovers. Just spins forever without alerting me of an error. I only knew because I looked in dev tools.

```
Request URL:
https://online-store-web.shopifyapps.com/admin/online-store/admin/api/unversioned/graphql?operation=CheckThemeSnippets
Request Method:
POST
Status Code:
413 Payload Too Large
Remote Address:
185.146.173.20:443
Referrer Policy:
no-referrer
```

Request Headers
```
:authority:
online-store-web.shopifyapps.com
:method:
POST
:path:
/admin/online-store/admin/api/unversioned/graphql?operation=CheckThemeSnippets
:scheme:
https
Accept:
application/json
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-US,en;q=0.9
Authorization:
Bearer [redacted]
Content-Length:
1949396
Content-Type:
application/json
Origin:
https://online-store-web.shopifyapps.com
Sec-Fetch-Dest:
empty
Sec-Fetch-Mode:
cors
Sec-Fetch-Site:
same-origin
User-Agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1
X-Online-Store-Web:
1
X-Requested-With:
XMLHttpRequest
```

Response 413 Payload Too Large

**Comment by peepers-rick** [comment]
This is now happening to the majority of my JS files uploaded to my theme assets directory. All less than 2 mb. These all worked yesterday.

**Comment by jjdudley** [comment]
+1, experiencing the same issue...

**Comment by fredbegin11** [comment]
Same here

**Comment by drewisme** [comment]
same here

**Comment by veken1199** [comment]
👋 Thank you for reporting this issue, the team is currently looking into it.
