### ISSUE TITLE
[Bug]: `shopify theme pull` and ignore rule since 3.54.0

### ISSUE THREAD

**Issue by msev** [Shopify/cli#3312]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The `.shopifyignore` file contains the following rule:
```
config/settings_data.json
templates/*.json
```
Since version 3.54.0, when I run the shopify theme pull command, the `templates/*.json` files are pulled even though they shouldn't be.

I have the same problem if I add `templates/*.json` rule in a `shopify.theme.toml` environment: the files are still pulled.

At first I thought it might be the `*` pattern, but `shopify.theme.toml` contains a rule to ignore locales and it still works fine:
```
[environments.xxx]
store = "xxx"
theme = xxx
ignore = ["locales/*"]
```

When testing the `templates/collection.json` rule, the `templates/collection.json` file is ignored. 
It's definitely the `templates/*.json` rule that's causing the problem.

Expected behavior: The `templates/*.json` files should not be pulled because they are ignored by the `.shopifyignore` file or by an environment in the `shopify.theme.toml` file.

**Please note that the `shopify theme push` command still works correctly: files are ignored during push.**

### Actual behavior

The files are pulled

### Verbose output

```shell
2024-01-25T16:44:39.228Z: Reading the content of file at .shopifyignore...
2024-01-25T16:44:39.229Z: Ignoring theme file config/settings_data.json via .shopifyignore...
2024-01-25T16:44:39.229Z: Ignoring theme file locales/en.default.json via --ignore...
2024-01-25T16:44:39.229Z: Ignoring theme file locales/en.default.schema.json via --ignore...
2024-01-25T16:44:39.229Z: Ignoring theme file locales/fr.json via --ignore...
2024-01-25T16:44:39.229Z: Ignoring theme file locales/fr.schema.json via --ignore...
```

### Reproduction steps

1. Add `templates/*.json` rule to `.shopifyignore` file or `shopify.theme.toml` environment 
2. Run `shopify theme pull` command
3. `templates/*.json` files are pulled

### Operating System

macOS 14.2.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.54.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

20.11.0

**Comment by anders-christiansen** [comment]
--only flag is also broken...

**Comment by jonathanmoore** [comment]
This is a pretty critical bug that was introduced with 3.54.0.

Running `shopify theme pull --store store-name --theme 000000000000 --path theme --only templates/*.json` will result in **no matches found: templates/*.json**.

Or if I run `shopify theme pull --store store-name --theme 000000000000 --path theme --only config/settings_data.json` instead of pulling that one specific file locally I will see it occasionally delete some local templates/*.json files.

This change has broken our Github to Shopify integration with actions that rely on pulling down the latest changes someone might have made in the theme editor while also having the consequence of removing some files.

As a side effect, this change also breaks the `.shopifyignore` file in another way from what @msev outlined.  In my ignore file I have it set up to ignore markdown files:
```
...
*.md
```

With this in place the CLI will generate an error for these wildcard matches:

```
╭─ error ───────────────────────────────────╮
  Invalid regular expression: /*.md/: Nothing to repeat                       

  To investigate the issue, examine this stack trace:                         
    at match                                                                  
    at (../../../.bun/install/global/node_modules/@shopify/theme/src/cli/uti- 
       lities/asset-ignore.ts:25)                                             
      const match = patterns.some((pattern) => key.match(pattern))            
    at some                                                                   
    at (../../../.bun/install/global/node_modules/@shopify/theme/src/cli/uti- 
       lities/asset-ignore.ts:25)                                             
      const match = patterns.some((pattern) => key.match(pattern))            
    at filter                                                                 
    at applyIgnoreFilters (../../../.bun/install/global/node_modules/@shopif- 
       y/theme/src/cli/utilities/asset-ignore.ts:16)                          
      .filter(filterBy(shopifyIgnore, '.shopifyignore'))                      
    at async buildDownloadTasks (../../../.bun/install/global/node_modules/@- 
       shopify/theme/src/cli/utilities/theme-downloader.ts:55)                
      const checksums = await applyIgnoreFilters(remoteChecksums,             
      themeFileSystem, options)                                               
    at async downloadTheme (../../../.bun/install/global/node_modules/@shopi- 
       fy/theme/src/cli/utilities/theme-downloader.ts:23)                     
      const downloadTasks = await buildDownloadTasks(remoteChecksums, theme,  
       themeFileSystem, session, options)                                     
    at async pull (../../../.bun/install/global/node_modules/@shopify/theme/- 
       src/cli/services/pull.ts:43)                                           
      await downloadTheme(theme, session, themeChecksums, themeFileSystem,    
      options)                                                                
    at run (../../../.bun/install/global/node_modules/@shopify/theme/src/cli- 
       /commands/theme/pull.ts:90)                                            
      await pull(theme, adminSession, {path, nodelete, only, ignore, force})  
╰───────────────────────────────────────╯

    SyntaxError: Invalid regular expression: /*.md/: Nothing to repeat
```

Looking at the PRs for 3.54.0, I noticed @karreiro's change that was included which removed the requirement for ruby for `shopify theme pull`, but clearly there is an issue with it.

As recommended in #3139 I added the `--stable` flag to use the legacy ruby implementation and now the all of the CLI commands related to `shopify theme pull` work as expected.

**Comment by karreiro** [comment]
Thank you, everyone, for promptly reporting this issue with all the details!

As @jonathanmoore kindly suggested, **please use the `--stable` option in the `3.54` version of Shopify CLI**. In the next minor release, we're bringing back the legacy implementation (https://github.com/Shopify/cli/pull/3326) while the issues reported in this thread get fixed.

@anders-christiansen and @ChristiantangCC, could you please share the scenario you're facing (including the value you're passing for the `--only/--ignore` flags or the context of your `.shopifyignore` file)? With that information, we can make sure we support those use cases in upcoming releases.

Thanks again, everyone, for reporting the issues.
