### ISSUE TITLE
Auto-update Node versions used in CI pipelines

### ISSUE THREAD

**Issue by pepicrft** [Shopify/cli#332]
Addresses [this comment](https://github.com/Shopify/cli/pull/331#issuecomment-1222459788)

### Context
We pinned the [Node versions](https://github.com/Shopify/cli/pull/331) used in CI to make our builds more deterministic. However, as @gonzaloriestra pointed out, we do it at the cost of not detecting if new versions of Node break the CLI.

### What
We can reduce the cost of leaning towards determinism by automating updating the Node versions in CI pipelines. We can use a GitHub action that runs recurrently, updates the pipeline if there are newer Node versions, and opens a PR. The workflow is similar to the one that Dependabot follows when there are new dependency versions.

**Comment by amcaplan** [comment]
As an alternative, maybe we can distinguish between main vs PR builds, where PR builds are deterministic to avoid unrelated breakages blocking a PR, but we'll still get alerted on any problems with new Node versions when we merge to main, before deployment happens.

**Comment by pepicrft** [comment]
> As an alternative, maybe we can distinguish between main vs PR builds, where PR builds are deterministic to avoid unrelated breakages blocking a PR, but we'll still get alerted on any problems with new Node versions when we merge to main, before deployment happens.

I'd keep `main` and `PR` consistent. Otherwise we might see failing builds in `main` that are hard to diagnose.
