### ISSUE TITLE
[Bug]: On deploying new version of app, CLI says this will remove extension titled "Registration title" that does not exist

### ISSUE THREAD

**Issue by Jamflynt** [Shopify/cli#3327]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Normal behavior would be on running `npm run deploy`, CLI would not mention removal of any app extension as no new app extension is being added or removed.

### Actual behavior

Upon running `npm run deploy`, CLI states this will remove 5 instances of an extension titled "Registration title". 

This does not exist in our code or up in Partners. This affects deployment on all applications but have not noticed any issues with our extensions after deployment of our apps. 

Cannot find mention of this as an issue anywhere (I have started a Shopify Community thread about this issue as well as reporting it here). 

### Verbose output

```shell
?  Release a new version of theme-customizations-2?

   ┃  Includes:
   ┃  + theme-extensions
   ┃
   ┃  Removes:
   ┃  - Registration title
   ┃  - Registration title
   ┃  - Registration title
   ┃  - Registration title
   ┃  - Registration title
   ┃
   ┃  This can permanently delete app user data.

   Type theme-customizations-2 to confirm, or press Escape to cancel.
```

### Reproduction steps

1.Run `npm run deploy` in CLI/Terminal while deploying Shopify App to Partners

### Operating System

Mac OS Sonoma 14.2.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.54.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v21.6.1

**Comment by bithaolee** [comment]
same issue

**Comment by bithaolee** [comment]
I fix a bug and release a new version using npm run deploy. I get the same prompt, what happens if I select confirm

**Comment by rohitsasi720** [comment]
updating to latest cli solved the problem, npm run shopify upgrade

**Comment by xdlbdy** [comment]
`npm run shopify app config push` has same error
