### ISSUE TITLE
[Bug]: The Partners GraphQL API responded unsuccessfully with errors

### ISSUE THREAD

**Issue by jaichod** [Shopify/cli#3335]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

Normal running of command `npm run dev`. It will build the app and run in the dev site

### Actual behavior

Got an error while the app is configuring

GraphQLClientError: 
    The Partners GraphQL API responded unsuccessfully with errors:

    [
      {
        "message": "Unexpected system error",
        "extensions": {
          "code": "500"
        }
      }
    ]

    Request ID: a45a26b2-80a3-4809-810b-6e668000d6f1

### Verbose output

```shell
The Partners GraphQL API responded unsuccessfully with errors:                                                                                    │
│                                                                                                                                                    │
│  [                                                                                                                                                 │
│    {                                                                                                                                               │
│      "message": "Unexpected system error",                                                                                                         │
│      "extensions": {                                                                                                                               │
│        "code": "500"                                                                                                                               │
│      }                                                                                                                                             │
│    }                                                                                                                                               │
│  ]                                                                                                                                                 │
│                                                                                                                                                    │
│  Request ID: a45a26b2-80a3-4809-810b-6e668000d6f1                                                                                                  │
│                                                                                                                                                    │
│                                                                                                                                                    │
│  To investigate the issue, examine this stack trace:                                                                                               │
│    at makeRequest (graphql-request/src/index.ts:441)                                                                                               │
│      throw new ClientError(                                                                                                                        │
│    at processTicksAndRejections (node:internal/process/task_queues:95)                                                                             │
│    at async debugLogResponseInfo (@shopify/cli-kit/src/private/node/api.ts:27)                                                                     │
│      response = await request                                                                                                                      │
│    at (ChorleyDigital/Speedwave/node_modules/@shopify/cli-kit/dist/public/node/api/graphql.js:22)                                                  │
│    at (ChorleyDigital/Speedwave/node_modules/@shopify/cli-kit/dist/public/node/metadata.js:84)
```

### Reproduction steps

1. Run command `npm run dev`
2.
3.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli": "^3.49.6"

### Node version (run `node -v` if you're not sure)

v21.6.1

**Comment by vlalsd** [comment]
same issue

**Comment by chesterwu** [comment]
same issue

**Comment by pt2pham** [comment]
Confirmed on our end that the issue has now been fixed. Sorry for the inconvenience.

**Comment by JHBeeIT** [comment]
Hi, im still facing the same issue with the latest cli

**Comment by seven-binoche** [comment]
Hello, I've been getting a 504 on Partners GraphQL API for the last 4-6 hours, when I run `shopify app dev`. I'm attaching the logs from `shopify app dev --verbose`.

`    
╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                  │
│                                                                                                                                  │
│  The Partners GraphQL API responded unsuccessfully with the HTTP status 504 and errors:                                          │
│                                                                                                                                  │
│  {}                                                                                                                              │
│                                                                                                                                  │
│  Request ID: 6fb0762b-6937-473c-afb1-2d946eaa3cef-1723040821                                                                     │
│                                                                                                                                  │
│                                                                                                                                  │`

[shopify-partners-api-error.txt](https://github.com/user-attachments/files/16530197/shopify-partners-api-error.txt)
