### ISSUE TITLE
[Bug]: Theme check and editor integration not working correcly in repository with mutliple themes -> use relative path

### ISSUE THREAD

**Issue by Christoph-AK** [Shopify/cli#3349]
### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

We are running an automated preprocessor to convert a base theme into multiple shop themes for different countries. 
Our base theme is located in `template/` and gets enriched with snippets from a custom preprocessor. The resulting deployable themes get placed into `out/<shop>/`, so for example out/de or out/dk for our german and danish shops. 

We would love to use current features like autocompletion, theme check and format to work in this configuration

### Actual behavior

As the extension only looks at the absolute paths, it detects neither our base theme at template/... nor the deployable processed themes at out/de/... . 

We get errors like 'snippet abc not found' and 'translation for key a.b.c not found', even tho they are there - just not at the default path.

It would be helpful if we could set a template base path in config, or if the lsp could use relative paths, like `../snippets/abc.liquid` instead of `$workdir/snippets/abc.liquid`.

### Reproduction steps

Move all theme files into a subdirectory. The tooling breaks.

### Operating System

Win 11

**Comment by briandesp** [comment]
I need help - I think this is related to this issue. Just today when i started to try and follow links, such as a snippet inside my workspace. It says not found and tries to build a new file at the root of my pc not the root of the workspace where the file actually exists. What's going on? I upgraded AFTER this started happening - and it still persists. So i know it wasn't from the versions itself.

**Comment by briandesp** [comment]
Any ideas what could be going on here ? my follow links are not working
