### ISSUE TITLE
[Bug]: SHOPIFY_CLI_TTY behavior inverted when CLI crashes

### ISSUE THREAD

**Issue by njsaunders** [Shopify/cli#3391]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

CLI Errors immediately without prompting for user input.

### Actual behavior

CLI prompts for use input despite SHOPIFY_CLI_TTY being 0

### Verbose output

```shell
% shopify theme push --theme=neiltest --unpublished --json
✗ An unexpected error occurred.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.


neil@Neils-Air dist % export SHOPIFY_CLI_TTY=0
neil@Neils-Air dist % shopify theme push --theme=neiltest --unpublished --json
✗ An unexpected error occurred.
	To submit an issue include the stack trace.
	To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

? Send an anonymized error report to Shopify? (Choose with ↑ ↓ ⏎, filter with 'f')
> 1. Yes, send
  2. No, don't send
```
```


### Reproduction steps

1. Populate a store with 100 themes
2. Do a theme push to the store - Will error and die.
3. export SHOPIFY_CLI_TTY=0
4. Repeat a theme push - CLI will error, but then prompt for input about sending a bug report.

### Operating System

Ubuntu

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.55.4

### Shell

Bash

### Node version (run `node -v` if you're not sure)

v20.10.0

### What language and version are you using in your application?

Node 20

**Comment by seanwbarry** [comment]
same issue. using BitBucket Pipelines.

          - export SHOPIFY_CLI_TTY=$SHOPIFY_CLI_TTY (set to 0)

<img width="628" alt="tty issue" src="https://github.com/Shopify/cli/assets/12903479/3fafca44-2e22-4fad-86ea-5ce0ae80f1c9">
