### ISSUE TITLE
[Bug]: connect ETIMEDOUT 185.146.173.20:443 running yarn dev on CLI-generated app

### ISSUE THREAD

**Issue by nicksmithr** [Shopify/cli#3417]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should run the app.

### Actual behavior

connect ETIMEDOUT 185.146.173.20:443

### Verbose output

```shell
error ───────────────────────────────────────────────────────────────────────╮
│                                                                               │
│  request to https://partners.shopify.com/api/cli/graphql failed, reason:      │
│  connect ETIMEDOUT 185.146.173.20:443                                         │
│                                                                               │
╰───────────────────────────────────────────────────────────────────────────────╯

    FetchError: request to https://partners.shopify.com/api/cli/graphql failed, reason: connect ETIMEDOUT
    185.146.173.20:443
    Code: ETIMEDOUT
```

### Reproduction steps

1. Run `yarn dev` in a shopify 

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.53

### Shell

warp

### Node version (run `node -v` if you're not sure)

21.1.0

### What language and version are you using in your application?

Node

**Comment by nicksmithr** [comment]
Resolved now.

Closing. Probably a short outage?

**Comment by Wilmer-Rivka** [comment]
Hi Nick, 

How did you fix this issue? I've been trying to fix for a few days and nothing. I'd really appreciate if you could share your solution.

**Comment by MahmoudY3c** [comment]
For some reasons that I don't know what it's installing `shopify` as dev dependency fix that error so whenever i need to run any command, I'm run it like `yarn dev`, `yarn deploy` or `npx shopify app dev` the problem isn't happening anymore I think there's something wrong when install it globally so use it as dev dependency
