### ISSUE TITLE
How to run `shopify theme dev` for 2 different stores at the same time

### ISSUE THREAD

**Issue by tuanpham-barrel** [Shopify/cli#3440]
Hi! I am developing themes for 2 different stores `store1` and `store2`. I am able to run `shopify theme dev --store store1` and `shopify theme dev --store store 2 --port 9293` without any error. However if I update file for `store1`, the file syncing fail with this message:

```
  • 05:15:35 Synced » update assets/theme.js
  • 05:15:35 Synced » update assets/theme.min.js
  • 05:15:36 Synced » update assets/theme.min.js.map
  • 05:17:51 ERROR  » update sections/quick-cart.liquid: You can't use Shopify CLI with development stores if you only have Partner staff member access. If you want to use Shopify CLI to work on a development store, then you should be the store owner or create a staff account on the store.

If you're the store owner, then you need to log in to the store directly using the store URL at least once (for example, using barrel-base-framework.myshopify.com/admin) before you log in using Shopify CLI. Logging in to the Shopify admin directly connects the development store with your Shopify login.
```

I have to stop 2 commands and run `shopify theme dev --store store1` again in order to be able to sync file in store1 which is inconvenient. I tried theme environments but got the same result. Is there anyway to run `theme dev` on multiple stores without stopping others?

**Comment by ekwoka** [comment]
So doing each separately works, but doing a single one doesn't?

I think it's fundamental in how shopify auths. That you're only authed to one at a time.

I think you could probably do this by using separate installations.

Like, if you are using npm, have it installed locally to each project separately.

Then they should maybe both use different auths, but that might not be right.
