### ISSUE TITLE
[Feature]: Hide quick commands

### ISSUE THREAD

**Issue by kelreel** [Shopify/cli#3454]
### What area(s) will this request affect?

Other

### What type of change do you want to see?

New feature

### Overview

Now the commands take up a significant part of the screen. The ability to hide these commands would be useful.

![image](https://github.com/Shopify/cli/assets/36932151/bb934e34-d7db-44e6-b639-84e2ca807cbc)

### Motivation

This is inconvenient when developing in one window, for example in VS Code. You have to constantly expand the terminal or scroll it.

**Comment by shauns** [comment]
Thanks for the feedback @kelreel -- this is a subjective call and we feel that the quick commands are worth the trade-off. We are always looking to refine the `dev` experience and your feedback is noted.
