### ISSUE TITLE
[Bug]: `application_url` and `redirect_urls` in shopify.app.toml get overwritten instead of keeping subpaths

### ISSUE THREAD

**Issue by zakariamofaddel** [Shopify/cli#3464]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The expected behaviour is that the subpaths are maintained if they are different from the default ones that Shopify assumes.

### Actual behavior

My app is served from the `/admin` path, but the cli replaces always the whole url, omitting the subpath.

`https://suppliers-seeks-these-interested.trycloudflare.com/admin` -> `https://women-spirits-hotel-democrat.trycloudflare.com`

### Verbose output

```shell
-
```

### Reproduction steps

1. Create a Shopify app using templates
2. Run `shopify app dev`
3. Add `/admin` to `application_url`
4. Run `shopify app dev` again
5. `/admin` subpath is not there anymore with new cloudflare url

### Operating System

Windows 11 (WSL2)

### Shopify CLI version (check your project's `package.json` if you're not sure)

^3.56.2

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.18.2

**Comment by shauns** [comment]
@zakariamofaddel -- thank you for sharing this. I think in this case you're best off avoiding the automatic URL management -- there are after all limits to how accurate it can be for every scenario -- and changing this setting: https://shopify.dev/docs/apps/tools/cli/configuration#:~:text=38-,automatically_update_urls_on_dev,-%3D%20false
