### ISSUE TITLE
[Bug]: redirect_urls should not be required for managed installs

### ISSUE THREAD

**Issue by PhiloNL** [Shopify/cli#3479]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The app should deploy without the requirement to add redirection URLs when using Shopify's managed installation.

The following works:
[auth]
redirect_urls = []

But when you deploy, the CLI will update the config and remove the `redirect_urls = []` from the config, causing the next deploy to fail.

It also prevents me from updating my app via the dashboard:
![image](https://github.com/Shopify/cli/assets/1133950/86880e19-f70b-49e3-95fc-5a11558e8bb9)

### Actual behavior

The following error was thrown:

```
 Fix a schema error in shopify.app.production.toml:                                                      │
│  [                                                                                                       │
│    {                                                                                                     │
│      "code": "invalid_type",                                                                             │
│      "expected": "array",                                                                                │
│      "received": "undefined",                                                                            │
│      "path": [                                                                                           │
│        "auth",                                                                                           │
│        "redirect_urls"                                                                                   │
│      ],                                                                                                  │
│      "message": "Required"                                                                               │
│    }                                                                                                     │
│  ]      
```

### Verbose output

```shell
Reporting handled error to Bugsnag: Fix a schema error in shopify.app.production.toml:
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "auth",
      "redirect_urls"
    ],
    "message": "Required"
  }
]
```

### Reproduction steps

1. Remove the redirect `redirect_urls` from the `.toml` config
2. Run deploy command

### Operating System

MacOS darwin arm64

### Shopify CLI version (check your project's `package.json` if you're not sure)

0.0.0-nightly-20240223150810

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.17.0

**Comment by alvaro-shopify** [comment]
Hey @PhiloNL !, thanks for rising up this issue. We have found out a couple of bugs that causes this wrong behaviour. We are working on solving this as soon as possible.
In the meantime as a workaround you could set the default `redirect url` using the dashboard
```
https://shopify.dev/apps/default-app-home/api/auth
```
Once it's done the `deploy` command should start working again. As your app uses `managed installation` this should not have any impact
Sorry for the inconveniences
