### ISSUE TITLE
[Bug]: Cannot run development app on latest version (with npm run dev) - PHP template (reopen #2866)

### ISSUE THREAD

**Issue by Insomnia88** [Shopify/cli#3503]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

npm run dev should proceed through the app selection (or creation) flow and I should be presented with a preview link and running app.

### Actual behavior

I get an error saying that it can't find shopify
![grafik](https://github.com/Shopify/cli/assets/13587426/816e9dd3-8992-4b39-816b-f250efa343f6)

### Verbose output

```shell
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\Phillip\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.4.0
2 info using node@v20.10.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\Phillip\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\Dokumente\Arbeit\Shopify Apps\test4\.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\Phillip\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\Phillip\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 12ms
17 timing npm:load:configload Completed in 12ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm run dev
22 verbose argv "run" "dev" "--loglevel" "verbose"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 5ms
25 verbose logfile logs-max:10 dir:C:\Users\Phillip\AppData\Local\npm-cache\_logs\2024-02-29T14_02_46_708Z-
26 verbose logfile C:\Users\Phillip\AppData\Local\npm-cache\_logs\2024-02-29T14_02_46_708Z-debug-0.log
27 timing npm:load:logFile Completed in 10ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 58ms
31 silly logfile start cleaning logs, removing 2 files
32 silly logfile done cleaning log files
33 timing command:run Completed in 99ms
34 verbose exit 1
35 timing npm Completed in 222ms
36 verbose code 1
```

### Reproduction steps

1.npm init @shopify/app@latest -- --template php
2.[Usual PHP application setup steps]
3.npm run dev
4.Error

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.56.3

### Shell

windows cmd

### Node version (run `node -v` if you're not sure)

v20.10.0

### What language and version are you using in your application?

PHP 8.2.4

**Comment by lizkenyon** [comment]
Hi there 👋 

There are some additional steps to set up your database that are required. You can find the additional step in the templates [README](https://github.com/Shopify/shopify-app-template-php?tab=readme-ov-file#setting-up-your-laravel-app).

Sorry for the confusion!
