### ISSUE TITLE
[Bug]: npm run deploy not updating app scopes in partner dashboard for Remix application

### ISSUE THREAD

**Issue by alexshwe1** [Shopify/cli#3504]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Running npm run deploy with updated app scopes in shopify.app.toml should update app scopes for remix app in partner dashboard. Specifically, I am changing scopes in shopify.app.toml from:

`scopes = "write_products,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects"` 

to :

`scopes = "write_products,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_orders"`

### Actual behavior

After deploying new version of Remix app to AWS ECS task with updated scopes in task definition environment variables, running npm run deploy does not update app scopes in the partner dashboard. After installing the app, the app goes into a redirect loop and eventually displays the message:
<img width="746" alt="Screenshot 2024-02-29 at 10 28 55 AM" src="https://github.com/Shopify/cli/assets/71849221/c23d58b6-b982-422a-b99d-5c138133dcd3">
If I look at the version of the app released from running npm run deploy, the scopes are not updated and if I look at the configured scopes panel of API access, the scopes are not updated as well. The same issue also occurs when I run the app locally with `npm run dev`.

### Verbose output

```shell
npm run deploy runs to completion without errors.
```

### Reproduction steps

1. Update remix app scopes in shopify.app.toml
2. Deploy new version of app to AWS ECS task
3. Run npm run deploy
4. App enters url redirect loop and fails to load after installation.

### Operating System

Linux amd64

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.53.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v21.6.2

**Comment by AxelTTa** [comment]
have you found a solution?, currently stuck on the same problem

**Comment by liucka04** [comment]
Have the same problem, can't find a way to push the updated config

**Comment by alexshwe1** [comment]
No solution yet

**Comment by danpodbury** [comment]
Same issue here. Seemly, either functionality has changed or cli instructions don't match what is possible.

Making a development version of an existing custom distribution.
running: `yarn dev --reset` and selecting "(y) Yes, create it as a new app" prints this dialog
<img width="1006" alt="image" src="https://github.com/Shopify/cli/assets/29648303/95082c17-8ac2-48e0-bd77-4abfa05af514">

running: `npm run shopify app config push` gives

```
?  Make the following changes to your remote configuration?
   ┃    [access_scopes]
   ┃  - scopes = ""
   ┃  + scopes = "write_cart_transforms,write_products,write_discounts,read_orders"
 >  (y) Yes, confirm changes
```

but this gives:

`Command no longer supported.
To update your app configuration, upgrade Shopify CLI to the latest version and run the 'app deploy' command.`

currently running "@shopify/cli": "^3.50.0"

running: `yarn shopify app deploy` gives

`(y) Yes, release this new version`

which seems to succeed, but without the scopes being updated
<img width="288" alt="image" src="https://github.com/Shopify/cli/assets/29648303/b099b517-7701-43e6-8773-589dcc422131">

Not sure if I'm doing something wrong here. But certainly confusing

**Comment by isaacroldan** [comment]
Hi everyone. To be able to update scopes from the CLI you need to be on version 3.55+ (ideally the latest one, 3.57.0 at this time).

Before version 3.55 the way to do it was with the `app config push` command, that command has now been deprecated for all versions as you can see from your error message. 

From version 3.55, updating the scopes in the toml and running `app deploy` will update them in the dashboard.

Please update to 3.57, run `deploy` and let me know if it works :)

**Comment by alexshwe1** [comment]
Hey @isaacroldan,

Thanks! I had the Shopify CLI up to date globally but was using v3.53.0 in my package.json for both @shopify/app and @shopify/cli. Using `yarn upgrade @shopify/app@latest @shopify/cli@latest` upgraded local project dependencies which updated the scopes in the partner dashboard after running `yarn run deploy`.

I already had `include_config_on_deploy = true` included in the [build] section of my app.toml but thought I'd mention that for anyone else having the same issue.

**Comment by isaacroldan** [comment]
We are working on solving the issues of using global vs local :)
Thanks for the update @alexshwe1, i'm going to close this issue now.

**Comment by nadirhamid** [comment]
I was noticing the same issue and i tried to do various things with shopify CLI, none of which worked. However, i fixed this issue by manually creating a app in the Shopify partners dashboard. 

It seems like this works temporarily atleast. Not really a long term fix though.

If anyone comes across this issue, here's how I fixed it.
1. take a backup of your app TOML file. For example, if its shopify.app.toml you can rename it to shopify_config_backup.toml
2. go to the all apps section in Shopify partners dashboard and click on Create new app
3. on the next screen, click Create app manually. type in your app's name and click create. You can change any settings manually after you create the app.
4. You can then download the apps config by running 'npm run shopify app config link' locally. Make sure to select the app you just created and set the config file name to shopify.app.toml
5.  copy the API scopes along with any other changes you made to shopify_config_backup.toml back to shopify.app.toml. Make sure the client ID and any other auto generated IDs remain the same
6. finally, you can run 'npm run shopify app deploy' to sync the local changes back to the shopify partners dashboard.  

From there, you can change your local config and deploy again to sync any new changes.

I know this is a tedious workaround but its the only one that worked. Hope it can help someone else.
