### ISSUE TITLE
[Bug]: `@oclif/core` dependency is duplicated when using NPM

### ISSUE THREAD

**Issue by frandiox** [Shopify/cli#3506]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

The `@oclif/core` dependency should be unique.

### Actual behavior

In latest versions, we can find both `@oclif/core@2` and `@oclif/core@3` versions installed when using NPM.

---

The `@oclif/core` dependency has been recently bumped to v3. However, the following dependencies in `@shopify/cli` are still 1 version behind and they internally rely on v2, so it also gets installed: https://github.com/Shopify/cli/blob/44ada880bde37319d0cafc6957340e4fc4df0abf/packages/cli/package.json#L98-L100

This is not a problem in this monorepo because PNPM is overwriting the `@oclif/core` version: https://github.com/Shopify/cli/blob/44ada880bde37319d0cafc6957340e4fc4df0abf/pnpm-lock.yaml#L10

However, when using NPM to install `@shopify/cli@3.56.2`, we end up with the two versions installed.

It looks like the following versions of the packages are aligned with `@oclif/core@3.15.1`:

```
    "@oclif/plugin-commands": "3.1.0",
    "@oclif/plugin-help": "6.0.9",
    "@oclif/plugin-plugins": "4.2.6",
```

I've added this in Hydrogen to fix inconsistencies:
https://github.com/Shopify/hydrogen/blob/5c054f0bc09d73cab9d9977c035feac01e4b43a2/package.json#L94-L99

However, I'm not very familiar with the dependencies to know if we can bump them without creating other issues.

---

### Reproduction steps

1. `npm i`
2. `npm why @oclif/core` should show 2 versions installed

### Operating System

Mac latest

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.56.2

### Shell

zsh

**Comment by isaacroldan** [comment]
Hi @frandiox !

You are right, i'm working on upgrading oclif dependencies but we are waiting for a new version of some of those packages with some changes we need. After that i'll update all of them :)

**Comment by frandiox** [comment]
Still relevant (I think?) -- @isaacroldan I see the version of `@oclif/core` is still overwritten in this repo but the dependencies have been updated. Is still needed to overwrite the oclif version?

**Comment by isaacroldan** [comment]
All oclif dependencies have been updated to use the same version of core
