### ISSUE TITLE
[Bug]: Verbose log contains api key when running shopify app config link

### ISSUE THREAD

**Issue by abrzoosh** [Shopify/cli#3518]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

API key should be replaced by ***** in verbose logs in all places when running `shopify app config link`.

### Actual behavior

When running `npm run shopify app config link -- --verbose` in the output `apiKey` is replaced with *****, but the api key is still visible in `api_key ` variable (snake case version) in other places (fetchSpecifications query, Analytics Event).
Since the verbose output is required in case of opening a bug ticket, this issue should be fixed.

### Verbose output

```shell
-
```

### Reproduction steps

1. `npm run shopify app config link -- --verbose`
2. See output

### Operating System

Ubuntu 22.04.3

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.56.3

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.18.2

**Comment by mudmixer-wes** [comment]
lol literally saw this myself when opening a ticket for another issue. Yikes.
