### ISSUE TITLE
[Feature]:Base shopify.app.toml as template

### ISSUE THREAD

**Issue by stephen-christie-ss** [Shopify/cli#3544]
### What area(s) will this request affect?

App

### What type of change do you want to see?

Substantial change to existing feature

### Overview

It is possible to create a new app from scratch, or to link to an existing app and pull its configuration into an app config TOML. However, there seems to be no way to create a new app according to a template.

The current support for deployment-specific configuration files provide the capabilities needed for Continuous Deployment with a powerful GitOps-style infrastructure-as-code. However, there is currently no build-in way to prepare a new app for deployment according to specifications committed to the repository as a template configuration file.

When starting to use the Shopify CLI for app configuration management, my assumption was that an shopify.app.toml without a app's client_id would be used as a template for creating new apps, or as a base for configurations to be inherited by the other app configuration files.

Proposal: Provide a tool, alongside 'shopify app link', which lets you create a new app according to the existing configuration in `shopify.app.toml` (including oauth scopes, etc.). This tool should not require that the template configuration is fully specified with `client_id`, etc. Note: this would still be compatible with the use of the `shopify.app.toml` as the default deployment, but I believe that the development workflow would be more obvious if this approach was to deprecated in favor of using it only as the template. If necessary, a separate template file could be introduced instead.

### Motivation

We use GitLab CI for testing and deployment, and follow their recommendation to automatically deploy each feature development branch for review. This means setting up a new app for each development. Currently, this will also require managing a template of the shopify.app.toml with our own code during CI, to interface with the Shopify CLI's app configuration capabilites.

**Comment by knjshimi** [comment]
+1

**Comment by illarionvk** [comment]
This is still relevant

**Comment by gerwinbrunner** [comment]
Also interested in this
