### ISSUE TITLE
Remix server not running and there is no error in terminal. 

### ISSUE THREAD

**Issue by muke5hy** [Shopify/cli#3553]
# Issue summary
I am following tutorial at shopify.dev, but I am not able to go beyond app installtion screen. I feel like the remix server is not running on my local but I do not see any error either. 

- `@shopify/shopify-app-remix` version: ^1.1.0
- Node version: v18.16.0
- Operating system: macos

```
// Paste any relevant logs here

16:02:59 │ remix │ 
16:02:59 │ remix │  💿  remix dev
16:02:59 │ remix │ 
16:02:59 │ remix │  info  building...
16:03:00 │ remix │  info  built (985ms)
16:03:02 │ remix │ [shopify-api/INFO] version 7.6.0, environment Remix
16:03:04 │ remix │ Remix App Server started at http://localhost:55911 (http://10.187.60.46:55911)
16:03:05 │ remix │ Could not reach Remix dev server at https://edition-delete-agencies-cdna.trycloudflare.com/ping (502)
16:03:05 │ remix │ 
16:03:05 │ remix │ 
/Users/Mukesh/Projects/hunch/mayvent/flexible-consumer-app/node_modules/.pnpm/@remix-run+server-runtime@1.19.3/node_modules/@remix-run/server-runtime/dist/dev.js:34
16:03:05 │ remix │     throw Error(await response.text());
16:03:05 │ remix │           ^
16:03:05 │ remix │ Error: 502 Bad Gateway
16:03:05 │ remix │ Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared
16:03:05 │ remix │ 
16:03:05 │ remix │     at Object.broadcastDevReady 
(/Users/Mukesh/Projects/hunch/mayvent/flexible-consumer-app/node_modules/.pnpm/@remix-run+server-runtime@1.19.3/node_modules/@remix-run/server-runtime/dist/dev.js:34:11)
16:03:05 │ remix │     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
## Expected behavior

Application should run and I should be able to see default screen. 

## Actual behavior

Getting following error 

```
502 Bad Gateway
Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared
```

## Steps to reproduce the problem

1. pnpm create @shopify/app@latest
2. pnpm dev

**Comment by isaacroldan** [comment]
This is an old issue, if cloudflare fails please follow the steps above from Richard on how to use a custom tunnel.

If you think you have a different problem please open a new Issue 🙏

**Comment by danbraik** [comment]
Maybe you are missing the following file in your root dir: [https://github.com/Shopify/shopify-app-template-remix/blob/39f9e1dd2a7b092c1fe1048d2c6b1728f937db0a/...](https://github.com/Shopify/shopify-app-template-remix/blob/39f9e1dd2a7b092c1fe1048d2c6b1728f937db0a/shopify.web.toml)


shopify.web.toml
```

name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec remix vite:dev"

```
