### ISSUE TITLE
[Bug]: <Can't install Shopify CLI and make it works>

### ISSUE THREAD

**Issue by Dolotboy** [Shopify/cli#3569]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I would expect the CLI to install correctly and for the commands to works, but nothing seems to be working on the Shopify CLI 2.x

** I need the CLI 2.x version installed because my customer APP is running with CLI 2.x and we need to be able to deploy the theme app extension **

### Actual behavior

I get no error on installation, but when I try shopify commands, none works nor exists
When I type "shopify version" or "shopify login" for example I get an error saying : Error command not found

### Verbose output

```shell
━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    command version not found

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Reproduction steps

1. nvm install 16.13.0
2. nvm use 16.13.0
3. Close terminal
4. Open terminal
5. npm uninstall -g @shopify/cli
6. npm install -g @shopify/cli@2.0.14
7. Close terminal
8. Open terminal
9. shopify version

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

There is no CLI version package.json

### Node version (run `node -v` if you're not sure)

18.0.0

### What language and version are you using in your application?

PHP 8.2

**Comment by Dolotboy** [comment]
> Hi!
> 
> I'm afraid CLI 2.x has been deprecated last year: https://shopify.dev/changelog/cli-2-0-to-be-sunset-on-may-31-2023
> 
> You can find a migration guide here: https://shopify.dev/docs/apps/tools/cli/migrate

Wow, thanks for the no help. I precised we didn't wanna go for CLI3

**Comment by gonzaloriestra** [comment]
I know, but CLI2 doesn't work anymore.
