### ISSUE TITLE
[Bug]: Can't deploy extension to production environment

### ISSUE THREAD

**Issue by mudmixer-wes** [Shopify/cli#3574]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When following the guidance at this link: https://shopify.dev/docs/api/checkout-ui-extensions#scaffolding-extension

There is never an option to chose the correct store to login with or deploy to. I make sure I am logged in to the right store in my browser. When the CLI gets to the point that it needs to go to the browser to log in, it does, but choosing the store is never allowed. It just says I logged in successfully and can close the window.

Yet no matter what I do, when using the shopify CLI to attempt to deploy our extension to our production store, the CLI *will not* find or auth in to the correct store. 

<img width="738" alt="image" src="https://github.com/Shopify/cli/assets/144712683/8f4b6a4f-48f7-491d-b11c-0cd696b32da2">

### Actual behavior

As an admin for a store that is on Shopify+, has extensibility turned on already, and has active/working API calls going on, I would expect there to be a very easy way to pick the shop I want to deploy the extension to, and yet there isn't.

There seems to be a solid disconnect from Shopify devs and the way the product is presented to the end user.

Support sent me here because they said the issue is that I wasn't registered as a "partner", but I don't want to be a partner. I am a store admin. In our store, I can see all the language suggesting we already have this feature turned on: 

<img width="733" alt="image" src="https://github.com/Shopify/cli/assets/144712683/601db913-6145-499d-a8d4-7e467cc3d2fd">

Yet there is no way to actually login and deploy to this store from the CLI for some weird and undocumented reason.

### Verbose output

```shell
Pasting that here would publish our API key.
```

### Reproduction steps

1. Follow steps from your docs: https://shopify.dev/docs/api/checkout-ui-extensions#scaffolding-extension
2. Try to deploy to a store you are already the admin of.
3. Fail sauce.

### Operating System

Mac, latest

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.57.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

20.9.0

**Comment by gonzaloriestra** [comment]
I'm afraid the CLI is only compatible with [Partner development stores](https://shopify.dev/docs/apps/tools/development-stores) or [Shopify Plus Partner sandbox stores](https://help.shopify.com/en/partners/dashboard/managing-stores/plus-sandbox-store) as explained here: https://shopify.dev/docs/apps/tools/cli/commands#dev

That's why your store can't be found. I know it's annoying and we are working to improve the experience. Sorry for the inconvenience!

**Comment by mudmixer-wes** [comment]
It's not an simply an "inconvenience" when you're charging $30k+/annually
for the featureset - and it's honestly offensive to treat this so
passively.

If you want to target enterprise customers, you need to be prepared to
offer a much higher level of personal customer service and empathy than
this.
