### ISSUE TITLE
[Bug]: Error when running 'npm run dev' command using Shopify CLI and Remix

### ISSUE THREAD

**Issue by Mistydoe033** [Shopify/cli#3575]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When I generate an extension the command 'npm run dev' should allow the app to run and use the extension 

### Actual behavior

When I run 'npm run dev' only after generating the extension the app breaks (no changes to extension) an it gives this error

20:16:30 │ graphiql   │ GraphiQL server started on port 3457                                                              
20:16:32 │ remix      │ Prisma schema loaded from prisma\schema.prisma
20:16:32 │ webhooks   │ Sending APP_UNINSTALLED webhook to app server
20:16:35 │ webhooks   │ App isn't responding yet, retrying in 5 seconds
20:16:39 │ extensions │
20:16:39 │ extensions │ --------- Pushing theme files to App Ext. Host (HOSTNAME) (#140619317471) on
[SHOPNAME.myshopify.com](http://SHOPNAME.myshopify.com/)
20:16:39 │ extensions │ Pushing theme...     0%                                                                            
20:16:40 │ webhooks   │ App isn't responding yet, retrying in 5 seconds
20:16:45 │ webhooks   │ App isn't responding yet, retrying in 5 seconds
20:16:47 │ remix      │
20:16:47 │ remix      │ ✔ Generated Prisma Client (v5.11.0) to .\node_modules\@prisma\client in 15.05s
20:16:47 │ remix      │
20:16:47 │ remix      │ Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
20:16:47 │ remix      │ ```
20:16:47 │ remix      │ import { PrismaClient } from '@prisma/client'
20:16:47 │ remix      │ const prisma = new PrismaClient()
20:16:47 │ remix      │ ```
20:16:47 │ remix      │ or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
20:16:47 │ remix      │ ```
20:16:47 │ remix      │ import { PrismaClient } from '@prisma/client/edge'
20:16:47 │ remix      │ const prisma = new PrismaClient()
20:16:47 │ remix      │ ```
20:16:47 │ remix      │
20:16:47 │ remix      │ See other ways of importing Prisma Client: http://pris.ly/d/importing-client
20:16:47 │ remix      │
20:16:47 │ remix      │ ┌─────────────────────────────────────────────────────────────┐
20:16:47 │ remix      │ │  Deploying your app to serverless or edge functions?        │
20:16:47 │ remix      │ │  Try Prisma Accelerate for connection pooling and caching.  │
20:16:47 │ remix      │ │  https://pris.ly/cli/accelerate                             │
20:16:47 │ remix      │ └─────────────────────────────────────────────────────────────┘
20:16:47 │ remix      │
20:16:49 │ remix      │ Prisma schema loaded from prisma\schema.prisma
20:16:49 │ remix      │ Datasource "db": SQLite database "dev.sqlite" at "file:dev.sqlite"                                
20:16:49 │ remix      │
20:16:49 │ remix      │ 1 migration found in prisma/migrations                                                            
20:16:49 │ remix      │                                                                                                    
20:16:49 │ remix      │                                                                                                    
20:16:49 │ remix      │ No pending migrations to apply.                                                                    
20:16:50 │ webhooks   │ App hasn't started in time, giving up
20:16:50 │ webhooks   │ APP_UNINSTALLED webhook delivery failed                                                            
20:16:51 │ remix      │   ➜  Local:   http://localhost:41892/
20:16:51 │ remix      │   ➜  Network: use --host to expose                                                                
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┏━━ Error
20:17:18 │ extensions │ ┃ X Cloning into 'C:/Users/ADMINI~1/AppData/Local/Temp/d20240316-12364-zpyslc'...
20:17:18 │ extensions │ ┃ remote: Enumerating objects: 10504, done.
20:17:18 │ extensions │ ┃ remote: Counting objects:   2% (1/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:   5% (2/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:   8% (3/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  11% (4/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  14% (5/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  17% (6/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  20% (7/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  23% (8/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  26% (9/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  29% (10/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  32% (11/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  35% (12/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  38% (13/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  41% (14/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  44% (15/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  47% (16/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  50% (17/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  52% (18/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  55% (19/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  58% (20/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  61% (21/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  64% (22/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  67% (23/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  70% (24/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  73% (25/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  76% (26/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  79% (27/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  82% (28/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  85% (29/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  88% (30/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  91% (31/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  94% (32/34)
20:17:18 │ extensions │ ┃ remote: Counting objects:  97% (33/34)
20:17:18 │ extensions │ ┃ remote: Counting objects: 100% (34/34)
20:17:18 │ extensions │ ┃ remote: Counting objects: 100% (34/34), done.
20:17:18 │ extensions │ ┃ remote: Compressing objects:   3% (1/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:   7% (2/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  11% (3/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  15% (4/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  19% (5/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  23% (6/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  26% (7/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  30% (8/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  34% (9/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  38% (10/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  42% (11/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  46% (12/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  50% (13/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  53% (14/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  57% (15/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  61% (16/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  65% (17/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  69% (18/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  73% (19/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  76% (20/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  80% (21/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  84% (22/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  88% (23/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  92% (24/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects:  96% (25/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects: 100% (26/26)
20:17:18 │ extensions │ ┃ remote: Compressing objects: 100% (26/26), done.
20:17:18 │ extensions │ ┃ Receiving objects:   0% (1/10504)
20:17:18 │ extensions │ ┃ Receiving objects:   0% (28/10504), 28.00 KiB | 16.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   0% (80/10504), 44.00 KiB | 21.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   1% (106/10504), 68.00 KiB | 24.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   1% (121/10504), 84.00 KiB | 21.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   1% (151/10504), 108.00 KiB | 23.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   1% (201/10504), 140.00 KiB | 24.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   2% (211/10504), 140.00 KiB | 24.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   2% (238/10504), 164.00 KiB | 25.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   2% (286/10504), 196.00 KiB | 26.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   2% (312/10504), 212.00 KiB | 25.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   3% (316/10504), 212.00 KiB | 25.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   3% (325/10504), 220.00 KiB | 21.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   3% (338/10504), 228.00 KiB | 15.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   3% (406/10504), 268.00 KiB | 12.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   3% (419/10504), 276.00 KiB | 9.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   4% (421/10504), 276.00 KiB | 9.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   4% (447/10504), 292.00 KiB | 8.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   4% (473/10504), 308.00 KiB | 8.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   4% (512/10504), 324.00 KiB | 8.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   4% (525/10504), 340.00 KiB | 8.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   5% (526/10504), 340.00 KiB | 8.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   5% (552/10504), 348.00 KiB | 8.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   5% (579/10504), 364.00 KiB | 11.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   5% (623/10504), 404.00 KiB | 17.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   6% (631/10504), 404.00 KiB | 17.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   6% (690/10504), 444.00 KiB | 19.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   6% (718/10504), 452.00 KiB | 18.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   7% (736/10504), 468.00 KiB | 18.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   7% (757/10504), 484.00 KiB | 19.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   7% (770/10504), 492.00 KiB | 17.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   7% (785/10504), 492.00 KiB | 17.00 KiB/s
20:17:18 │ extensions │ ┃ Receiving objects:   7% (809/10504), 516.00 KiB | 15.00 KiB/s
20:17:18 │ extensions │ ┃ error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
20:17:18 │ extensions │ ┃ error: 3022 bytes of body are still expected
20:17:18 │ extensions │ ┃ fetch-pack: unexpected disconnect while reading sideband packet
20:17:18 │ extensions │ ┃ fatal: early EOF
20:17:18 │ extensions │ ┃ fatal: fetch-pack: invalid index-pack output

### Verbose output

```shell
Preview URL: https://SHOPNAME.myshopify.com/admin/oauth/redirect_from_cli?clie
nt_id=xxxxxxxxxxxxx
GraphiQL URL: http://localhost:3457/graphiql

 [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [G20:43:31 │ remix      │ 2024-03-16T18:43:31.787Z vite:hmr [no modules matched]
output.txt

────────────────────────────────────────────────────────────────────────────────

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Preview URL: https://SHOPNAME.myshopify.com/admin/oauth/redirect_from_cli?clie
nt_id=xxxxxxxx
GraphiQL URL: http://localhost:3457/graphiql

 [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [G2024-03-16T18:43:34.869Z: Sending "Partners" GraphQL request:
  query FindAppPreviewMode($apiKey: String!) {
    app(apiKey: $apiKey) {
      developmentStorePreviewEnabled
    }
  }

With variables:
{
  "apiKey": "*****"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.57.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: win32
 - Content-Type: application/json


────────────────────────────────────────────────────────────────────────────────

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Preview URL: https://SHOPNAME.myshopify.com/admin/oauth/redirect_from_cli?clie
nt_id=xxxxxxxx
GraphiQL URL: http://localhost:3457/graphiql

 [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [G2024-03-16T18:43:35.353Z: Request to https://partners.shopify.com/api/cli/graphql completed in 483 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"f9e834f7231872722829cb9dec035749"
 - x-request-id: d7883df1-2775-4dfc-a4bf-c67b8930c3cb-1710614617
    

────────────────────────────────────────────────────────────────────────────────

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Preview URL: https://SHOPNAME.myshopify.com/admin/oauth/redirect_from_cli?clie
nt_id=xxxxxxxxx
GraphiQL URL: http://localhost:3457/graphiql

 [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [G20:43:37 │ extensions │ 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━┏━━ Error

────────────────────────────────────────────────────────────────────────────────

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Preview URL: https://SHOPNAME.myshopify.com/admin/oauth/redirect_from_cli?clie
nt_id=xxxxxxxxx
GraphiQL URL: http://localhost:3457/graphiql

 [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [G20:43:37 │ extensions │ ┃ X Cloning into
'C:/Users/ADMINI~1/AppData/Local/Temp/d20240316-16004-nob20v'...
20:43:37 │ extensions │ ┃ remote: Enumerating objects: 10504, done.
20:43:37 │ extensions │ ┃ remote: Counting objects:   2% (1/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:   5% (2/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:   8% (3/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  11% (4/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  14% (5/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  17% (6/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  20% (7/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  23% (8/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  26% (9/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  29% (10/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  32% (11/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  35% (12/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  38% (13/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  41% (14/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  44% (15/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  47% (16/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  50% (17/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  52% (18/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  55% (19/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  58% (20/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  61% (21/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  64% (22/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  67% (23/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  70% (24/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  73% (25/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  76% (26/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  79% (27/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  82% (28/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  85% (29/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  88% (30/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  91% (31/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  94% (32/34)
20:43:37 │ extensions │ ┃ remote: Counting objects:  97% (33/34)
20:43:37 │ extensions │ ┃ remote: Counting objects: 100% (34/34)
20:43:37 │ extensions │ ┃ remote: Counting objects: 100% (34/34), done.
20:43:37 │ extensions │ ┃ remote: Compressing objects:   3% (1/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:   7% (2/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  11% (3/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  15% (4/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  19% (5/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  23% (6/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  26% (7/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  30% (8/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  34% (9/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  38% (10/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  42% (11/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  46% (12/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  50% (13/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  53% (14/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  57% (15/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  61% (16/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  65% (17/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  69% (18/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  73% (19/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  76% (20/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  80% (21/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  84% (22/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  88% (23/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  92% (24/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects:  96% (25/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects: 100% (26/26)
20:43:37 │ extensions │ ┃ remote: Compressing objects: 100% (26/26), done.

20:43:37 │ extensions │ ┃ Receiving objects:   0% (1/10504)
20:43:37 │ extensions │ ┃ Receiving objects:   0% (54/10504), 20.00 KiB | 18.00
KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   1% (106/10504), 68.00 KiB | 31.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   1% (110/10504), 68.00 KiB | 31.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   1% (131/10504), 92.00 KiB | 26.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   1% (151/10504), 108.00 KiB |
24.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   1% (189/10504), 132.00 KiB |
24.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   2% (211/10504), 140.00 KiB |
22.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   2% (214/10504), 140.00 KiB |
22.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   2% (238/10504), 164.00 KiB |
21.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   2% (262/10504), 180.00 KiB |
20.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   2% (299/10504), 196.00 KiB |
19.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   3% (316/10504), 196.00 KiB |
19.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   3% (338/10504), 228.00 KiB |
19.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   3% (379/10504), 252.00 KiB |
12.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   3% (406/10504), 268.00 KiB |
13.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   3% (419/10504), 276.00 KiB |
11.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   4% (421/10504), 276.00 KiB |
11.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   4% (447/10504), 292.00 KiB |
10.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   4% (461/10504), 300.00 KiB | 9.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   4% (511/10504), 332.00 KiB | 8.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   5% (526/10504), 332.00 KiB | 8.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   5% (538/10504), 348.00 KiB | 7.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   5% (592/10504), 380.00 KiB | 9.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   5% (614/10504), 396.00 KiB | 9.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   6% (631/10504), 396.00 KiB | 9.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   6% (636/10504), 412.00 KiB | 9.00
 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   6% (677/10504), 436.00 KiB |
10.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   6% (704/10504), 444.00 KiB |
12.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   6% (732/10504), 460.00 KiB |
11.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   7% (736/10504), 460.00 KiB |
11.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   7% (757/10504), 484.00 KiB |
14.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   7% (784/10504), 500.00 KiB |
13.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   7% (797/10504), 508.00 KiB |
12.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   7% (809/10504), 516.00 KiB |
14.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   7% (836/10504), 524.00 KiB |
13.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   8% (841/10504), 524.00 KiB |
13.00 KiB/s
20:43:37 │ extensions │ ┃ Receiving objects:   8% (864/10504), 540.00 KiB |
13.00 KiB/s
20:43:37 │ extensions │ ┃ error: RPC failed; curl 18 transfer closed with
outstanding read data remaining
20:43:37 │ extensions │ ┃ error: 762 bytes of body are still expected
20:43:37 │ extensions │ ┃ fetch-pack: unexpected disconnect while reading
sideband packet
20:43:37 │ extensions │ ┃ fatal: early EOF
20:43:37 │ extensions │ ┃ fatal: fetch-pack: invalid index-pack output

────────────────────────────────────────────────────────────────────────────────

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Preview URL: https://SHOPNAME.myshopify.com/admin/oauth/redirect_from_cli?clie
nt_id=xxxxxxx
GraphiQL URL: http://localhost:3457/graphiql

 [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [G20:43:37 │ extensions │ 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━┗━━

────────────────────────────────────────────────────────────────────────────────

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Preview URL: https://SHOPNAME.myshopify.com/admin/oauth/redirect_from_cli?clie
nt_id=xxxxxxxxx
GraphiQL URL: http://localhost:3457/graphiql

 [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [1A [2K [G
────────────────────────────────────────────────────────────────────────────────

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Shutting down dev because of an error ...
```

### Reproduction steps

1. Make New App 'npm init @shopify/app@latest'
2. Make new theme app extension 'npm run shopify app generate extension'
3. Choose Theme app extension
4. Start App 'npm  run dev' 

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.57.1

### Shell

PowerShell

### Node version (run `node -v` if you're not sure)

v20.11.1

### What language and version are you using in your application?

JavaScript

**Comment by shauns** [comment]
Belatedly following up on this -- from the logs this is a git issue and not one we can help with here. I appreciate git on windows can (still!) be challenging. If you still have this issue, the community support forums will be a better place to go.
