### ISSUE TITLE
[Bug]: Login only allows Shopify Partners as option

### ISSUE THREAD

**Issue by mudmixer-wes** [Shopify/cli#3576]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Logging in via the CLI allows store admins who have Shopify+ and extensibility enabled to login directly to their store, not as a partner since they're working on and deploying to their own store directly.

### Actual behavior

After successfully logging out, when the CLI attempts to facilitate the login flow, it only pushes you in to the Shopify Partners login flow, instead of allowing shop admins who have extensibility turned on to be able to login directly to their own store.
<img width="527" alt="image" src="https://github.com/Shopify/cli/assets/144712683/42ec39c9-c100-407c-ac58-c9835bbbe63d">

### Verbose output

```shell
This would publish api keys.
```

### Reproduction steps

1. After logging out run `npm run dev`
2. CLI automatically pushes you to partners auth flow rather than allowing you to choose the store.
3.

### Operating System

Mac, latest

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.57.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

20.9.0

### What language and version are you using in your application?

Node

**Comment by gonzaloriestra** [comment]
I'm afraid the CLI for apps currently requires a Shopify Partners account. But thanks for the feedback, we are aware of the issue and we are working to improve the experience.

**Comment by mudmixer-wes** [comment]
@gonzaloriestra Why was this closed as 'completed' when it is still an issue? Our UI for our existing store prominently says we have the feature but you closed this issue as 'completed' even though we still can't use it? 
<img width="807" alt="image" src="https://github.com/Shopify/cli/assets/144712683/c07b000d-6803-4b7c-ae0e-4cb97c852463">
Not sure how this is acceptable.

**Comment by gonzaloriestra** [comment]
I closed it because it's not a bug, but a feature request and we are already aware. Thanks for the suggestion!

**Comment by mudmixer-wes** [comment]
How is it not a bug when my UI shows we already have the feature but we
can't use it because the ability to is absent in the CLI?

**Comment by mudmixer-wes** [comment]
Not sure who your product owner is for Shopify+, but the way you're
communicating all of this nuanced information to your end user is anything
but clear.

Having a little sub text on a page with thousands of words on it doesn't
make it clear what features do and do not require a partner account. More
importantly, there is absolutely no explanation as to *why* some are
reserved for partners, especially when again the UI clearly says we have
Checkout Extensibility turned on.... which to any reasonable person would
communicate that we have *all* of the features, not just a very limited
subset of the features.

Yet again I share this screenshot:
[image: image.png]

To me, any reasonable person would see this and think that means we have
access to the full suite of features and functions, including deploying
custom extensions via CLI.

If you're saying that's not true, then your product team needs to really
circle back and update who gets to see this message, and if they see a
message like this, it needs to be **abundantly* *clear that you do not mean
we have all of it turned on.

Like it could say, '...pages are upgraded to Checkout Extensibility
(Basic)' - and then you could have very clear documentation in your docs
that makes it clear there is Extensibility 'Basic' and 'Advanced' and then
make it more clear on both pages that 'Basic' every one gets, and
'Advanced' only partners get, which I still think is a huge product miss
given you're targeting mid-level+ sized companies with Shopify+ who
typically have development resources, but at least then from the UI in the
admin it's abundantly clear from the get go that there is additional
functionality that I may not have access to.

**Comment by gonzaloriestra** [comment]
I'm sorry if the documentation is not clear enough, I'll share this feedback internally to improve it.

**Comment by mudmixer-wes** [comment]
Additionally, to say there are "many features available" without CLI is a bit of an oversell. The fact that clicking 'add app block' has *no* basic blocks in there (like basic input fields) makes this editor mostly useless and requires a company to have access to CLI: 
<img width="1370" alt="image" src="https://github.com/Shopify/cli/assets/144712683/aa523cd8-9b98-43f7-8c8c-ff4483599a9c">

So yet again, your product interface is communicating both implicitly and explicitly that I should be able to do more with my own store with Extensibility than I am actually able to do. 

This is a 'Bug' by omission. It is a bug by lack of empathy to the end user. I get that in startup world its "all hype all the time" but when you're rolling out an editor that doesn't actually let you 'extend' your checkout page without CLI access.... isn't your communication about extensibility being turned on just a lie?
