### ISSUE TITLE
[Bug]: theme dev throws 404 because of missing video in disabled section

### ISSUE THREAD

**Issue by vaelu** [Shopify/cli#3586]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

`theme dev` should ignore sections which are disabled and not throw a 404 on the whole page.

### Actual behavior

We had a disabled video section in a template, and this video was deleted from Shopify. When I ran `shopify theme dev` it started the theme with a 404 page (possibly because it was in the `index.json` template).

### Verbose output

```shell
Original output (german):
templates/index.json: Der Wert in der Einstellung "video" verweist nicht auf eine anwendbare, von Shopify gehostete Videoressource.
  • 22:36:14 ERROR  » update templates/index.json:

Translated:
templates/index.json: The value in the setting "video" does not point to an applicable video resource hosted by Shopify.
  • 22:36:14 ERROR  » update templates/index.json:
```

### Reproduction steps

1. Create a section and add a video to it
2. Disable this section and delete the video from Shopify's files
3. Try to start the theme with `theme dev`

### Operating System

MacOS Sonoma 14.4

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.57.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v21.2.0

**Comment by lvl99** [comment]
I just want to add my 2c here: when we're working on multiple stores with the same codebase, often files won't exist and it is a real pain when trying to push something like `templates/index.json` (especially when those files are large videos). It's a nice feature that it can provide an error, but I wish it wasn't a blocking error and was more of a warning.

What would actually be great is if we could have shared files across all linked stores (e.g. we're on Shopify Plus and this would be a super great feature), and maybe the ability to configure which stores can have shared files. But I realise this is well outside of the scope of the Shopify CLI 😅
