### ISSUE TITLE
[Bug]: The build command does not show detailed build errors

### ISSUE THREAD

**Issue by kumar303** [Shopify/cli#365]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When creating a [checkout UI extension](https://shopify.dev/apps/checkout/delivery-instructions/getting-started#step-1-scaffold-a-new-extension) with a syntax error, `yarn build` does not show the syntax error as I expected it to.

### Actual behavior

`yarn build` only says `Command failed with exit code 1: /path/to/binaries/extensions/3.8.0-darwin-arm64 build -` but it doesn't contain the syntax error.

### Reproduction steps

1. Create a [checkout UI extension](https://shopify.dev/apps/checkout/delivery-instructions/getting-started#step-1-scaffold-a-new-extension) with a syntax error like the following in `src/index.js`:

<details>
<summary>Example source</summary>

```tsx
import React from "react";
import {
  useExtensionApi,
  render,
  Banner,
} from "@shopify/checkout-ui-extensions-react";

This / is / a / syntax error;

render("Checkout::Dynamic::Render", () => <App />);

function App() {
  const { extensionPoint, i18n } = useExtensionApi();
  return <Banner>{i18n.translate("welcome", { extensionPoint })}</Banner>;
}

```

</details>

2. Run `yarn dev`. This shows the error as expected: `src/index.js:8:23: error: Expected ";" but found "error"`

<details>
<summary>Detailed error</summary>

```
extensions | Shopify CLI Extensions Server is now available at https://352b-2600-1700-5658-3c50-7c74-806b-7311-da84.ngrok.io/extensions/dev-console
extensions | kumar-june-edition-ext (successfully built localization)
extensions | 2022/08/25 13:10:52 Watcher added for: extensions/kumar-june-edition-ext/locales
extensions | kumar-june-edition-ext (Build succeeded)
extensions | kumar-june-edition-ext (Error building extension:  Error: Build failed with 1 error:
extensions | src/index.js:8:23: error: Expected ";" but found "error"
extensions |     at failureErrorWithLog (/Users/kumar/tmp/june-edition-ext/node_modules/esbuild/lib/main.js:1475:15)
extensions |     at /Users/kumar/tmp/june-edition-ext/node_modules/esbuild/lib/main.js:1133:28
extensions |     at runOnEndCallbacks (/Users/kumar/tmp/june-edition-ext/node_modules/esbuild/lib/main.js:1051:65)
extensions |     at buildResponseToResult (/Users/kumar/tmp/june-edition-ext/node_modules/esbuild/lib/main.js:1131:7)
extensions |     at /Users/kumar/tmp/june-edition-ext/node_modules/esbuild/lib/main.js:1240:14
extensions |     at /Users/kumar/tmp/june-edition-ext/node_modules/esbuild/lib/main.js:611:9
extensions |     at handleIncomingPacket (/Users/kumar/tmp/june-edition-ext/node_modules/esbuild/lib/main.js:708:9)
extensions |     at Socket.readFromStdout (/Users/kumar/tmp/june-edition-ext/node_modules/esbuild/lib/main.js:578:7)
extensions |     at Socket.emit (node:events:513:28)
extensions |     at addChunk (node:internal/streams/readable:324:12) {
extensions |   errors: [
extensions |     {
extensions |       detail: undefined,
extensions |       location: [Object],
extensions |       notes: [],
extensions |       pluginName: '',
extensions |       text: 'Expected ";" but found "error"'
extensions |     }
extensions |   ],
extensions |   warnings: []
extensions | })
```

</details>

3. Run `yarn build`. This does not show the actual error. It only shows:

```
Command failed with exit code 1: /Users/kumar/Library/Caches/shopify-cli-nodejs/vendor/binaries/extensions/3.8.0-darwin-arm64 build -
    kumar-june-edition-ext (exit status 1)
```

4. Run `yarn build --verbose`. This also does not show the error.

### Notes

* This is a **regression**. I confirmed that in CLI 3.4.0 it was working as expected
* This was reported by `pixelchutes` on Discord

### Operating System

macOS 12.5.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.8.0

### Node version (run `node -v` if you're not sure)

v18.6.0

### What language and version are you using in your application?

Node

**Comment by alfonso-noriega** [comment]
We find the bug and will ping you back as soon as the PR is approved and merged.
