### ISSUE TITLE
[Bug]: Warning message since 3.58.2

### ISSUE THREAD

**Issue by msev** [Shopify/cli#3664]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The `.shopifyignore` file contains the following rule:
```
config/settings_data.json
templates/*.json
```
Since version 3.58.2, when I run the shopify theme push command, the following message appears :

```
The pattern templates/*.json is unsafe, please use a valid regex or glob.
The pattern templates/*.json is unsafe, please use a valid regex or glob.
The pattern templates/*.json is unsafe, please use a valid regex or glob.
```

However, the documentation states that this type of wildcard can be used : [https://shopify.dev/docs/themes/tools/cli#excluding-files-from-shopify-cli](https://shopify.dev/docs/themes/tools/cli#excluding-files-from-shopify-cli)

> .shopifyignore accepts references to files in the following formats:
> 
> - Simple file names: templates/product.temp.json
> - Wildcards: config/*_secret.json, *.jpg
> - Regular expressions: /\.(txt|gif|bat)$/

### Actual behavior

A warning message is displayed

By using the `--stable` flag this message no longer appears

### Verbose output

```shell
Too long
```

### Reproduction steps

1. Add `templates/*.json` rule to `.shopifyignore` file or `shopify.theme.toml` environment 
2. Run `shopify theme push` command
3. A warning message is displayed

### Operating System

macOS 14.2.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.58.2

### Node version (run `node -v` if you're not sure)

20.11.0

**Comment by msev** [comment]
I don't understand.

I modified the `.shopifyignore` file by adding `/**/*.json` and I still get the following warning message:

```
The pattern /**/*.json is unsafe, please use a valid regex or glob.
```

**Comment by msev** [comment]
Hi @jamesmengo 

I downgraded to version 3.57.1 to test the `templates/**/*.json` pattern, but it doesn't work as it should: the `*.*.json` files in the templates folder have been deleted.
I'm working with several developers, and we won't be able to use this pattern until they update Shopify CLI to 3.58.x.

Before running the `shopify theme push` command:

![Capture d’écran 2024-04-10 à 09 07 02](https://github.com/Shopify/cli/assets/1529562/42f2f4df-1f62-449c-9311-cc2488a043fc)

After running the `shopify theme push` command:

![Capture d’écran 2024-04-10 à 09 07 45](https://github.com/Shopify/cli/assets/1529562/e6f58616-4999-4303-b868-87fe61fb41f8)

Does this mean that this type of pattern is not supported below version 3.58.x?

**Comment by jamesmengo** [comment]
Version < 3.58.x is backed by the ruby implementation, so `/**/*` means something different. That's partly why we wanted to start raising this warning

The forward-fix to address the excessive warnings has been merged and will roll out with the next release :)
