### ISSUE TITLE
[Bug]: <Getting esbuild error because my AMD CPU environment variable starts with a number "3DVPATH">

### ISSUE THREAD

**Issue by METADOODSStore** [Shopify/cli#3672]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

there should be no errors

### Actual behavior

there was an error because my environment variable is called "3DVPATH". I don't want to change the name because its from my AMD CPU driver.

### Verbose output

```shell
idk
```

### Reproduction steps

1.don't have atm.
2.
3.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.58.2

**Comment by gonzaloriestra** [comment]
Hi! Could you please share what are you trying to run and the error message? Ideally, the full output when adding `--verbose` to the CLI command.

**Comment by isaacroldan** [comment]
This was solved on CLI version 3.59
