### ISSUE TITLE
[Bug]: theme dev command shows wrong theme

### ISSUE THREAD

**Issue by nboliver-ventureweb** [Shopify/cli#3698]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

`shopify theme dev` should show the local / development theme's content

### Actual behavior

It shows the live, published theme instead. Running `shopify theme delete --development` and then `shopify theme dev` fixes the issue. 

EDIT: `theme delete` doesn't seem to work consistently for all users.

### Verbose output

```shell
Output contains private information. DM for access.
```

### Reproduction steps

1. Run `shopify theme dev` and see the wrong theme at http://127.0.0.1:9292  
2. Run `shopify theme delete --development`
3. Run `shopify theme dev` and see the correct theme

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.58.2

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.16

**Comment by shnolk** [comment]
I am experiencing the same issue, however the `shopify theme delete --development` workaround does not work.

**Comment by nboliver-ventureweb** [comment]
Looks like this may be the same issue as #3663 even though no host flag is used? Also seems like deleting the dev theme doesn't work for all users.

**Comment by nikitaourazbaev** [comment]
I am also seeing this, I’m wondering if it’s https://github.com/Shopify/cli/issues/3466 again.

**Comment by aaronkantrowitz** [comment]
Happening here as well
