### ISSUE TITLE
[Bug]: CLI 3.59.0 - Warning: Could not find ts-node. Please ensure that ts-node is a devDependency.

### ISSUE THREAD

**Issue by sameerxanand** [Shopify/cli#3729]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

Running `shopify theme dev` should not produce a ts-node warning

### Actual behavior

Getting the warning:

```
Warning: Could not find ts-node at /opt/homebrew/Cellar/shopify-cli/3.59.0/libexec/lib/node_modules/@shopify/cli/dist/index-e6f8190d.js. Please ensure that ts-node is a devDependency. Falling back to compiled source.
```

In the console.

### Verbose output

```shell
-
```

### Reproduction steps

1. Upgrade to the latest version of the Shopify CLI (using Homebrew)
2. Run `shopify theme dev`
3. Observe warning in console

### Operating System

Mac OS 14.2.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.59.0

### Node version (run `node -v` if you're not sure)

v18.18.2

### What language and version are you using in your application?

Node

**Comment by AndreaPontrandolfo** [comment]
We are also encountering this, very annoying.
@shopify/cli: v3.59.0
Node: v20.10.0
