### ISSUE TITLE
[Bug]: Development store preview on Plus Sandboxes

### ISSUE THREAD

**Issue by bastos71** [Shopify/cli#3738]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When activating the "Development store preview" feature in an app extensions panel, new draft features should appear in the Theme Editor given by the command `npm run shopify app dev`

![image](https://github.com/Shopify/cli/assets/3809299/b3e55173-fa05-436e-b025-39b044b1c24e)

### Actual behavior

On Plus Sandboxes, this does not work, `npm run shopify deploy` is mandatory to see new features.
It's annoying when you have to work on features linked to Plus only features (like B2B for instance)

### Verbose output

```shell
➜ npm run shopify app dev -- --store=b2b-accounts.myshopify.com --verbose

> shopify-b2b-accounts-app@1.0.0 shopify
> shopify app dev --store=b2b-accounts.myshopify.com --verbose

2024-04-17T10:20:04.603Z: Running command app dev
2024-04-17T10:20:04.620Z: Getting a random port...
2024-04-17T10:20:04.626Z: Random port obtained: 62539
2024-04-17T10:20:04.668Z: cloudflared already installed, skipping
...
```

### Reproduction steps

1. Run the following command to any Plus Sandbox store : 

```
npm run shopify app dev
```

2. Add a new component in the extension

3. Command output shows the component is uploaded

4. It does not appear in the Theme Editor, even after reloading the page

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.59.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.11.1

### What language and version are you using in your application?

Node

**Comment by mgmanzella** [comment]
hi @bastos71 thanks for reporting this issue and for your patience 🙏 first -- do you have the correct permissions to use dev sandbox stores for this plus merchant?? [you'll need a staff account ](https://shopify.dev/docs/api/shopify-cli/app/app-dev)

next, can you share all the verbose logs of app dev, including when you modify a theme app extension?? i only see the beginning of the logs in the issue description 

lastly, can you also confirm your folder structure matches the [expected structure of an app](https://shopify.dev/docs/apps/structure)?? if app dev isn't run in the correct directory, your changes may not be picked up while developing

thanks for your help as we investigate your issue!

**Comment by bastos71** [comment]
Hello @mgmanzella ! 

This Shopify Plus instance is a sandbox one I created from our partner dashboard, so I guess there wouldn't have any issue about right access ?

For the logs, I voluntarily gave only the first lines for several reasons : 
* full log was really long 😬
* it was not different from the log I get with a classic Shopify instance

If you still want full log, let me know, and I'll try to send it 👍

For the folder structure, my app was not created with shopify cli, but everything works with a classic Shopify instance, so I guess the problem should not come from there ?

**Comment by mgmanzella** [comment]
> If you still want full log, let me know, and I'll try to send it 👍

yes pls! and make sure it includes logs of when you're modifying your theme app extension. if you're having trouble sending it over a github issue, feel free to DM me in the partners slack `@Morisa Manzella`

> This Shopify Plus instance is a sandbox one I created from our partner dashboard, so I guess there wouldn't have any issue about right access ?

yeh looking at your account you're the owner so there _shouldnt_ be any issues. does `app dev` work for a non plus development store?? is that what you mean by a classic Shopify instance??

**Comment by knjshimi** [comment]
Hi @mgmanzella, just to add: for me it works when I create a plus sandbox store directly, but it doesn't work if I create a plus sandbox organisation and then create plus sandbox stores within the org.

**Comment by karreiro** [comment]
👋 Hey @bastos71 @knjshimi,

Thank you for reporting this!

I could reproduce this issue with new apps in the CLI 3.59; however, I can no longer reproduce it in 3.61, as we've updated the infrastructure that uploads theme app extensions.

Could you please confirm if 3.61 is also working for you? If so, we may close this issue :)

I really believe this is going to work, but in case it doesn't, feel free to DM me on Partners Slack (`@Guilherme Carreiro`) with the `--verbose` logs.

Thanks again :)
