### ISSUE TITLE
Shopify CLI changes in local files not visible in the browser

### ISSUE THREAD

**Issue by mskraban1** [Shopify/cli#3744]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Any changes in the .json or .liquid files should be reflected in the browser.

### Actual behavior

No changes in the .json or .liquid files are reflected in the browser. This is happening quite commonly. Some day's it works ok, and somedays I have to restart CLI about 10 times to see the actual changes. No errors are present in the CLI. And browser refreshes page after making changes in any files, but changes are not visible in the browser..

### Verbose output

```shell
/
```

### Reproduction steps

1. Start shopify theme dev 
2. Create any changes in .json or .liquid files
3. Check if the changes are visible in the browser

### Operating System

Windows 11, but using Ubuntu WSL 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.59.0

### Shell

Bash

### Node version (run `node -v` if you're not sure)

v18.16.0

### What language and version are you using in your application?

HTML, CSS, liquid, json

**Comment by mskraban1** [comment]
> Could you share the verbose output when you change a JSON / Liquid file?
> 
> Should look something like this: <img alt="image" width="709" src="https://private-user-images.githubusercontent.com/35415298/323666340-6d1ec61a-50dc-4aad-a6a7-b428426de6e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTg0NzMsIm5iZiI6MTcxMzQ1ODE3MywicGF0aCI6Ii8zNTQxNTI5OC8zMjM2NjYzNDAtNmQxZWM2MWEtNTBkYy00YWFkLWE2YTctYjQyODQyNmRlNmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE2MzYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YmY4MGU0MjYwMDE4MjVlNjkyYTQzNGFlYTQ1N2Q3ZmZkYmU4NWY2N2FmNTk3NTNmYmE3N2E3MDJmYTI1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-ONjYPlUo0ND8aHYGchrQ152gppOphtvXqoNrb0ParI">

![image](https://github.com/Shopify/cli/assets/97444713/7e3a57e8-c235-444f-8b0c-51700a30078f)
Right now at the moment, it works fine. This issue comes and goes. 

For example for today this issue was present for 2 hours, then 1 hour it was working fine and then again 1 hour not working...

**Comment by vivekrc** [comment]
Hello,
The same thing happens at the app dev. From the past 2-3 hours, none of the changes have been pushed to the dev store.

**Comment by anzeharej** [comment]
@karreiro same issue, my request ID: f843db94-5841-4e27-b25d-d8fff9608963-1713773320

**Comment by karreiro** [comment]
Thank you for reporting this issue, @mskraban1, @vivekrc, and @anzeharej!

The fix for this issue has been released by [`3.59.1`](https://github.com/Shopify/cli/releases/tag/3.59.1), so upgrading the CLI should resolve the problem:

![theme-dev-demo](https://github.com/Shopify/cli/assets/1079279/cc71d4b9-38ec-42df-8cc8-40fe88f28520)
