### ISSUE TITLE
[Bug] Error: Not authorized as Store Owner when running shopify theme pull

### ISSUE THREAD

**Issue by custom-werks-dev** [Shopify/cli#3795]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It should give me the themes from my shopify account.

### Actual behavior

It says I am not authorized even though I am the store owner, I have checked everywhere tried all 
 the solutions from from this issue as well which is the basically the same bug as mine: https://github.com/Shopify/cli/issues/3749

![Screenshot 2024-04-24 203406](https://github.com/Shopify/cli/assets/162807523/0be8e4c0-5720-4454-af82-54ec8e3246cf)

### Verbose output

```shell
No I am simply using `shopify theme pull`
```

### Reproduction steps

`shopify theme pull`

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.59.1

**Comment by mgmanzella** [comment]
hi @custom-werks-dev thanks for reporting this issue and for your patience 🙏 can you try the following 

```
shopify auth logout 
shopify theme pull --verbose --store=dawn.myshopify.com # login with the account that has access to this store when prompted
```

let us know if the issue still exists and share the console log output if it does. thanks in advance

**Comment by mgmanzella** [comment]
closing as we haven't heart back, if this is still a problem please re open the issue with --verbose logs. thanks!
