### ISSUE TITLE
[Bug]: Can't create new admin action

### ISSUE THREAD

**Issue by TomaIvanovTomovYotpo** [Shopify/cli#3805]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

Create an app

### Actual behavior

Command `app generate extension` not found

### Verbose output

```shell
Command `app generate extension` not found. Did you mean `version`?
This is what I get after running 

shopify app generate extension --template admin_action --name issue-tracker-action --flavor react

I am following the steps from the official docs.

https://shopify.dev/docs/apps/admin/admin-actions-and-blocks/build-an-admin-action?extension=react
```

### Reproduction steps

Execute:
`shopify app generate extension --template admin_action --name issue-tracker-action --flavor react`
Result: 
`Command `app generate extension` not found. Did you mean `version`?`
Expected result:
Generate new app

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.58

**Comment by isaacroldan** [comment]
Hi @TomaIvanovTomovYotpo, you need CLI version 3.59 or higher to use global commands. 
If you upgrade the command should work as expected :)

**Comment by isaacroldan** [comment]
Are you getting an error? or it simply doesn't appear to be updated? You might be having multiple installations of it. How are you installing the CLI? You might be using a different package manager from your original installation method.

Maybe check where the current one is installed with `which shopify`, this should tell you the path where shopify is installed and this way you can infer how you originally installed it

**Comment by TomaIvanovTomovYotpo** [comment]
Manage to do it with brew upgade :)
