### ISSUE TITLE
[Feature]: When using `shopify theme dev` prevent auto syncing between remote and local

### ISSUE THREAD

**Issue by modermo** [Shopify/cli#3810]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

New feature

### Overview

I want to be more explicit when changes should be pushed to the remote theme, not every time I `shopify theme dev`. Ideally, `shopify theme dev` should just be listening to local changes, not automatically merging upon startup.

### Motivation

Deployments should be one way, not bidirectional.

**Comment by alexmorange** [comment]
It is auto pushing my local changes to the remote as well.

**Comment by alexmorange** [comment]
Has there been an update? I am still encountering this issue.

**Comment by jameskennethrobinson** [comment]
This is also happening for me. My remote theme changes (in the production store) are being overwritten completely by my local files whenever I run "shopify theme dev"

**Comment by OctoLion** [comment]
Same issue here.
