### ISSUE TITLE
Are oclif plugins being removed from Shopify CLI?

### ISSUE THREAD

**Issue by t-kelly** [Shopify/cli#3843]
The team at Archetype relies heavily on Shopify CLI to build themes that power 100,000+ online stores. Over the years, we have invested in additional tooling that helps us ship, and have made it available to our team as a Shopify CLI plugin because of the easy setup and integration. 

One CLI to rule them all, right?

We’ve noticed over the past few months that [Shopify has been taking steps to remove plugins from Shopify CLI](https://github.com/Shopify/cli/commit/0e07b15cbbbebffeb26542f7ed32308e637cc6bb). 

Why are plugins being removed from Shopify CLI?

As an open-source tool here to serve the partner community, removing plugins only limits our collective ability to contribute our own expertise and custom solutions. 

IMO this decision is the equivalent of Shopify removing apps from the platform and only supporting in-house features. We know that would only hurt Shopify’s mission, and so does this.

**Comment by nickwesselman** [comment]
This dependency is still present, I believe looking at just this single commit. Is misleading. We do bundle it in now, so it disappears from the `package.json` when we ship.
https://github.com/Shopify/cli/blob/main/packages/cli/package.json#L101

Has something actually stopped working for y'all or was this commit just concerning?

**Comment by t-kelly** [comment]
There have also been a number of changes we've noticed over the past few months that have been raising flags for us, suggesting that Shopify is looking to hide or remove support for plugins:

- https://github.com/Shopify/cli/pull/1830/files#diff-bcba2a5686f06158cdc8fe91326071a16e0d219fd12d7a7797d05ce365a28bc6
- https://github.com/Shopify/cli/pull/2381/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938
- https://github.com/Shopify/cli/commit/36374f255d273605d403b2c90735196d96e18c6e

Plugins install via `shopify plugin install` just fine before v3.59.0, but now we receive an error:
![image](https://github.com/Shopify/cli/assets/4837696/c811b1e7-0ba9-46f3-918c-2dc4c40ae10c)

If this is purely a bug and the intent is to keep plugins then I'm happy to change this to a bug report!

**Comment by fleveillee** [comment]
We're experiencing this with two different plugins. We've tried it with a Shopify CLI npm install and Homebrew install on macOS and we get the same error.

Please note that the `shopify plugins link` command for local dev is still functional. It seems to corroborate that you are indeed including the oclif plugins/plugins module.
