### ISSUE TITLE
[Bug]: Logging should be done to STDERR by default. STDOUT should be reserved for scriptable output. 

### ISSUE THREAD

**Issue by charlespwd** [Shopify/cli#3863]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

I noticed that logging is done by default to STDOUT (even debug logging, for theme check anyway). Shouldn’t [that be sent to STDERR by default](https://clig.dev/#the-basics:~:text=Send%20messaging%20to%20stderr.%20Log%20messages%2C%20errors%2C%20and%20so%20on%20should%20all%20be%20sent%20to%20stderr.%20This%20means%20that%20when%20commands%20are%20piped%20together%2C%20these%20messages%20are%20displayed%20to%20the%20user%20and%20not%20fed%20into%20the%20next%20command)?

Logging to STDOUT when it isn’t meant to be captured by a script makes the CLI non-composable/non-scriptable.

For instance, `shopify theme check --verbose --output json` will have non-JSON output in STDOUT and makes `| jq` break.

IMO STDOUT should be intentional, not the default.

### Actual behavior

IMO all of these should use STDERR by default. STDOUT is the wrong default. 

- [outputDebug](https://github.com/Shopify/cli/blob/6a99d8e3ed40be85e2eb9324f6a29631ec044ec9/packages/cli-kit/src/public/node/output.ts#L300) should log to STDERR by default (console.error)
- outputInfo
- outputWarn

### Verbose output

```shell
$ shopify theme check --output json --verbose | jq .
jq: parse error: Invalid numeric literal at line 1, column 14
```

### Reproduction steps

1. `shopify theme check --output json --verbose | jq .` -- get malformed JSON because debug logging isn't JSON. 

### Operating System

All

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.60

**Comment by knjshimi** [comment]
+1

**Comment by gonzaloriestra** [comment]
I've created a draft PR with a potential solution for this: https://github.com/Shopify/cli/pull/4922, in case someone wants to continue

**Comment by charlespwd** [comment]
I would even suggest having a _new_ output helper named `output` that would be the only one that logs to STDOUT.

That way you can pick from the list:
- `outputInfo` - STDERR loglevel info
- `outputDebug` - STDERR loglevel debug
- `outputWarn` - STDERR loglevel warn
- `outputError` - STDERR loglevel error
- `output` - STDOUT. Use only for JSON or whatever could be piped into another bash script.
