### ISSUE TITLE
[Bug]: Unhandled rejection in telemetry

### ISSUE THREAD

**Issue by frandiox** [Shopify/cli#3867]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Hydrogen custom storefront

### Expected behavior

Errors in internal telemetry should not be shown as unhandled rejections. The error should be caught and printed nicely, and maybe only as a debug log.

### Actual behavior

For example, when running without internet connection, the following log shows up in the console when running a CLI command (e.g. `shopify hydrogen dev`):

```bash
Unhandled Rejection:  Error: getaddrinfo ENOTFOUND otlp-http-production-cli.shopifysvc.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'otlp-http-production-cli.shopifysvc.com'
}
```

### Verbose output

```shell
2024-05-08T00:34:21.293Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 6 ms
With response headers:

    
2024-05-08T00:34:21.293Z: Failed to report usage analytics: request to https://monorail-edge.shopifysvc.com/v1/produce failed, reason: getaddrinfo ENOTFOUND monorail-edge.shopifysvc.com
2024-05-08T00:34:21.293Z: Completed command hydrogen dev
Unhandled Rejection:  Error: getaddrinfo ENOTFOUND otlp-http-production-cli.shopifysvc.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'otlp-http-production-cli.shopifysvc.com'
}
```

### Reproduction steps

1. Run a command without internet connection

### Operating System

Mac OS Sonoma 14

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.59.2

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.7.1

**Comment by tomfuertes** [comment]
Spent ~3 hours tracking down some agentic copilot errors that found this issue as an entry point. 

I think what I was looking for was disabling analytics via one of these command flags e.g., `SHOPIFY_CLI_NO_ANALYTICS=1`

https://github.com/Shopify/cli/blob/main/packages/cli-kit/src/private/node/constants.ts#L16-L30

Logged comment to help SEO re-entrys

**Comment by daviareias** [comment]
I tried really hard and it seems the only way to completely disable telemetry in neovim with mason is like this:
```lua
local opts = require("lspconfig.configs.shopify_theme_ls")
opts.cmd = {
	"env",
	"SHOPIFY_CLI_NO_ANALYTICS=1",
	"shopify",
	"theme",
	"language-server",
}
lspconfig(lsp, opts)
```lua
