### ISSUE TITLE
App Proxy not always sending x-ip-metadata and x-shop-domain headers since end of April

### ISSUE THREAD

**Issue by darrynten** [Shopify/cli#3873]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

The `x-ip-metadata` and `x-shop-domain` headers should be available on all requests coming through the App Proxy like they have been for many years.

### Actual behavior

Before April 22nd the app proxy consistently sent through `x-ip-metadata` and `x-shop-domain` headers in every App Proxy request.

Since that date the rate at which these headers come through in requests has been in a steady decline, which is affecting apps that rely on information provided by these headers, and now they come through very rarely.

### Verbose output

The x-ip-metadata value looks like this normally:

```shell
asn:12345;anon:1;anonVpn:0;hostProvider:1;pubProxy:0;torExit:0;countryCode:BG;regionCode:22;regionNameBase64:U29maWEtQ2FwaXRhbA==;subRegionCode:;subRegionNameBase64:;cityNameBase64:U29maWE=;postalCode:10000;timeZone:Europe\/Sofia;lat:12.34567;long:34.56789;ssbipAnon:0;ssbipAnonVpn:0;ssbipHostProvider:0;ssbipPubProxy:0;ssbipTorExit:0
```

The x-shop-domain normally contains the shop domain. This isn't too much of a problem as it comes in the URL params.

### Reproduction steps

1. Make a call through the app proxy, logging all headers
2. You will see the `x-ip-metadata` and `x-shop-domain` are not always present

### Operating System

All

### Shopify CLI version (check your project's `package.json` if you're not sure)

3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18

### What language and version are you using in your application?

All

**Comment by darrynten** [comment]
Also reported here in case this is the wrong repo: https://github.com/Shopify/shopify-app-js/issues/867

**Comment by isaacroldan** [comment]
Hi @darrynten, unfortunately this is not the correct repository to flag this, is not a CLI issue.
I see that this issue has been raised internally already so i'll go ahead and close this.

**Comment by darrynten** [comment]
@isaacroldan how can I get an update on this?

**Comment by darrynten** [comment]
@isaacroldan where can I get an update about this?
