### ISSUE TITLE
VSCode cannot connect to the server anymore, and code synchronization in real-time is not possible.

### ISSUE THREAD

**Issue by qpa2003** [Shopify/cli#3879]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

theme watch --allow-live

### Actual behavior

request failed after 5 retries with error: Get "https://theme-kit-access.shopifyapps.com/cli/meta.json": dial tcp 185.146.173.20:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Verbose output

```shell
theme confige -t -s -p
```

### Reproduction steps

2.
3.

### Operating System

Windows11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.60

### Shell

24.5

### Node version (run `node -v` if you're not sure)

v20

### What language and version are you using in your application?

ruby 3.3

**Comment by rcasimmons** [comment]
@qpa2003 you've not clearly read the tick boxes here.

The command you're referring to is for ThemeKit, not CLI.
