### ISSUE TITLE
[Bug]: <reason: connect ETIMEDOUT 185.146.173.20:443>

### ISSUE THREAD

**Issue by hspjxm** [Shopify/cli#3882]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

1:dev
> shopify app dev

To run this command, log in to Shopify.
👉 Press any key to open the login page on your browser
╭─ error ────────────────────────────────────────────────

### Actual behavior

 npm run dev

> dev
> shopify app dev

To run this command, log in to Shopify.
👉 Press any key to open the login page on your browser
╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                  │
│  request to https://accounts.shopify.com/oauth/token?grant_type=authorization_code&code=ZFJ1YmFVd2p4dnlwTm9GajBtY1YwajlnMWE4Zm9USkY4SkJFTVVTY2F5Rk1SM3Urb0prK2s  │
│  wZEdVQmoxL1EzNkpsVGh1Q0JIMDB2TmNIWWM0L1hrckRjNDBobHZ3cE9vcHp5cUhlME5CZjU0RzNvajRUVmQyb0NVZFJyZzZDZk9vOVVXcEpJemZmQ25meW1Wak81UkUvSHR5WnJsa3lmQ2drZm00bjY3MHN2b  │
│  W5lV0wvVUpGMURDYms3dXp4UFN0dms1ejNkeG0vemhZd3FjSDZpVng4djdrY29zT0Nkc2YyQmYzZ2JtZmMwOGNtbW12ZVo0dmtIaVFVQkhVQVZMckZ1MkhJRFJ1OFU2ZXp5WWtmR1dTaUxONGtJcll4VVFoWmp  │
│  wd2I0TDEvLytOVFcwKzRUVTJPTUY1aW92V2puVC9JdjhKblplcERRPT0tLWZCUHZXTVJMZjhTdWorZ2QtLUpKZHZYZmQwNkNaNTJFT0E4bWVublE9PQ&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456  │
│  &client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&code_verifier=jFMuxpdtyuiRs_uJ2qbfq21tf95jpsesJAl7-48MJjw failed, reason: connect ETIMEDOUT 185.146.173.20:443  │
│                                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

    FetchError: request to https://accounts.shopify.com/oauth/token?grant_type=authorization_code&code=ZFJ1YmFVd2p4dnlwTm9GajBtY1YwajlnMWE4Zm9USkY4SkJFTVVTY2F5Rk1SM3Urb0prK2swZEdVQmoxL1EzNkpsVGh1Q0JIMDB2TmNIWWM0L1hrckRjNDBobHZ3cE9vcHp5cUhlME5CZ
    jU0RzNvajRUVmQyb0NVZFJyZzZDZk9vOVVXcEpJemZmQ25meW1Wak81UkUvSHR5WnJsa3lmQ2drZm00bjY3MHN2bW5lV0wvVUpGMURDYms3dXp4UFN0dms1ejNkeG0vemhZd3FjSDZpVng4djdrY29zT0Nkc2YyQmYzZ2JtZmMwOGNtbW12ZVo0dmtIaVFVQkhVQVZMckZ1MkhJRFJ1OFU2ZXp5WWtmR1dTaUxONGtJcll4V
    VFoWmpwd2I0TDEvLytOVFcwKzRUVTJPTUY1aW92V2puVC9JdjhKblplcERRPT0tLWZCUHZXTVJMZjhTdWorZ2QtLUpKZHZYZmQwNkNaNTJFT0E4bWVublE9PQ&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&code_verifier=jFMuxpdtyuiRs_
    uJ2qbfq21tf95jpsesJAl7-48MJjw failed, reason: connect ETIMEDOUT 185.146.173.20:443

### Verbose output

```shell
> dev
> shopify app dev


To run this command, log in to Shopify.
👉 Press any key to open the login page on your browser
╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                  │
│  request to https://accounts.shopify.com/oauth/token?grant_type=authorization_code&code=ZFJ1YmFVd2p4dnlwTm9GajBtY1YwajlnMWE4Zm9USkY4SkJFTVVTY2F5Rk1SM3Urb0prK2s  │
│  wZEdVQmoxL1EzNkpsVGh1Q0JIMDB2TmNIWWM0L1hrckRjNDBobHZ3cE9vcHp5cUhlME5CZjU0RzNvajRUVmQyb0NVZFJyZzZDZk9vOVVXcEpJemZmQ25meW1Wak81UkUvSHR5WnJsa3lmQ2drZm00bjY3MHN2b  │
│  W5lV0wvVUpGMURDYms3dXp4UFN0dms1ejNkeG0vemhZd3FjSDZpVng4djdrY29zT0Nkc2YyQmYzZ2JtZmMwOGNtbW12ZVo0dmtIaVFVQkhVQVZMckZ1MkhJRFJ1OFU2ZXp5WWtmR1dTaUxONGtJcll4VVFoWmp  │
│  wd2I0TDEvLytOVFcwKzRUVTJPTUY1aW92V2puVC9JdjhKblplcERRPT0tLWZCUHZXTVJMZjhTdWorZ2QtLUpKZHZYZmQwNkNaNTJFT0E4bWVublE9PQ&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456  │
│  &client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&code_verifier=jFMuxpdtyuiRs_uJ2qbfq21tf95jpsesJAl7-48MJjw failed, reason: connect ETIMEDOUT 185.146.173.20:443  │
│                                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

    FetchError: request to https://accounts.shopify.com/oauth/token?grant_type=authorization_code&code=ZFJ1YmFVd2p4dnlwTm9GajBtY1YwajlnMWE4Zm9USkY4SkJFTVVTY2F5Rk1SM3Urb0prK2swZEdVQmoxL1EzNkpsVGh1Q0JIMDB2TmNIWWM0L1hrckRjNDBobHZ3cE9vcHp5cUhlME5CZ
    jU0RzNvajRUVmQyb0NVZFJyZzZDZk9vOVVXcEpJemZmQ25meW1Wak81UkUvSHR5WnJsa3lmQ2drZm00bjY3MHN2bW5lV0wvVUpGMURDYms3dXp4UFN0dms1ejNkeG0vemhZd3FjSDZpVng4djdrY29zT0Nkc2YyQmYzZ2JtZmMwOGNtbW12ZVo0dmtIaVFVQkhVQVZMckZ1MkhJRFJ1OFU2ZXp5WWtmR1dTaUxONGtJcll4V
    VFoWmpwd2I0TDEvLytOVFcwKzRUVTJPTUY1aW92V2puVC9JdjhKblplcERRPT0tLWZCUHZXTVJMZjhTdWorZ2QtLUpKZHZYZmQwNkNaNTJFT0E4bWVublE9PQ&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&code_verifier=jFMuxpdtyuiRs_
    uJ2qbfq21tf95jpsesJAl7-48MJjw failed, reason: connect ETIMEDOUT 185.146.173.20:443
    Code: ETIMEDOUT
```

### Reproduction steps

 npm run dev

> dev
> shopify app dev

To run this command, log in to Shopify.
👉 Press any key to open the login page on your browser
╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                  │
│  request to https://accounts.shopify.com/oauth/token?grant_type=authorization_code&code=ZFJ1YmFVd2p4dnlwTm9GajBtY1YwajlnMWE4Zm9USkY4SkJFTVVTY2F5Rk1SM3Urb0prK2s  │
│  wZEdVQmoxL1EzNkpsVGh1Q0JIMDB2TmNIWWM0L1hrckRjNDBobHZ3cE9vcHp5cUhlME5CZjU0RzNvajRUVmQyb0NVZFJyZzZDZk9vOVVXcEpJemZmQ25meW1Wak81UkUvSHR5WnJsa3lmQ2drZm00bjY3MHN2b  │
│  W5lV0wvVUpGMURDYms3dXp4UFN0dms1ejNkeG0vemhZd3FjSDZpVng4djdrY29zT0Nkc2YyQmYzZ2JtZmMwOGNtbW12ZVo0dmtIaVFVQkhVQVZMckZ1MkhJRFJ1OFU2ZXp5WWtmR1dTaUxONGtJcll4VVFoWmp  │
│  wd2I0TDEvLytOVFcwKzRUVTJPTUY1aW92V2puVC9JdjhKblplcERRPT0tLWZCUHZXTVJMZjhTdWorZ2QtLUpKZHZYZmQwNkNaNTJFT0E4bWVublE9PQ&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456  │
│  &client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&code_verifier=jFMuxpdtyuiRs_uJ2qbfq21tf95jpsesJAl7-48MJjw failed, reason: connect ETIMEDOUT 185.146.173.20:443  │
│                                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

    FetchError: request to https://accounts.shopify.com/oauth/token?grant_type=authorization_code&code=ZFJ1YmFVd2p4dnlwTm9GajBtY1YwajlnMWE4Zm9USkY4SkJFTVVTY2F5Rk1SM3Urb0prK2swZEdVQmoxL1EzNkpsVGh1Q0JIMDB2TmNIWWM0L1hrckRjNDBobHZ3cE9vcHp5cUhlME5CZ
    jU0RzNvajRUVmQyb0NVZFJyZzZDZk9vOVVXcEpJemZmQ25meW1Wak81UkUvSHR5WnJsa3lmQ2drZm00bjY3MHN2bW5lV0wvVUpGMURDYms3dXp4UFN0dms1ejNkeG0vemhZd3FjSDZpVng4djdrY29zT0Nkc2YyQmYzZ2JtZmMwOGNtbW12ZVo0dmtIaVFVQkhVQVZMckZ1MkhJRFJ1OFU2ZXp5WWtmR1dTaUxONGtJcll4V
    VFoWmpwd2I0TDEvLytOVFcwKzRUVTJPTUY1aW92V2puVC9JdjhKblplcERRPT0tLWZCUHZXTVJMZjhTdWorZ2QtLUpKZHZYZmQwNkNaNTJFT0E4bWVublE9PQ&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&code_verifier=jFMuxpdtyuiRs_
    uJ2qbfq21tf95jpsesJAl7-48MJjw failed, reason: connect ETIMEDOUT 185.146.173.20:443

### Operating System

mac

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.60.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18.20.0

**Comment by isaacroldan** [comment]
Hi @hspjxm, can you please provide more details? Does this happens everytime you run `dev`? have you tried in different machines or a different internet connection? 

Does it still happen or was a one-time thing?

**Comment by hspjxm** [comment]
> Hi @hspjxm, can you please provide more details? Does this happens everytime you run `dev`? have you tried in different machines or a different internet connection?
> 
> Does it still happen or was a one-time thing?
Yes, it still is after I switched networks.
I use Macbook, shopify-Cl version 3.60.0, node 18.20.0, and clashX for network proxy
1: The network agent node used is not allowed in the United States or Canada.
2: The global proxy is used.
3: Tried the clashX configuration
4: Tried to configure vpn in the terminal, I can successfully use Google link in the terminal

This problem bothered me for two days
I am now looking at similar solutions in the community that I have tried.
But you can still open Google to log into the shopify CLI,
And let me log in successfully to close the page can be, but to my console prompt "reason: connect ETIMEDOUT 185.146.173.20:443 │",

**Comment by gaozhenbao** [comment]
I also get the same issue, I tried on Ubuntu and Windows power shell,  none works.

**Comment by effert** [comment]
same problem

**Comment by isaacroldan** [comment]
Hi everyone, there is a known issue when connecting from China, if that's your case i'll suggest to try with a different VPN provider.

**Comment by raymondmatthew** [comment]
This happens because of VPN.

If you are going to work using a VPN,
make sure to enable VPN first before opening chrome and vscode[or any IDE] or terminals
also logout,

Relogin once VPN is open and make sure the browser you are authenticated with is in sync with the VPN at this time
