### ISSUE TITLE
[Feature]: Add support for WASM file format in assets in theme app extensions

### ISSUE THREAD

**Issue by thosakwe** [Shopify/cli#3893]
### What area(s) will this request affect?

App, Extension, Function

### What type of change do you want to see?

New feature

### Overview

Please add `.wasm` to the allow list of file type extensions in theme app extensions.

### Motivation

Due to https://github.com/Shopify/function-examples/discussions/329, I had to port my Shopify Functions to Rust.

However, my app customers heavily requested to be able to use it on the storefront as well.

Initially, I wanted to reuse my Rust code in the form of a `.wasm` binary in my theme app extensions (which is, in theory, the main use case of WebAssembly).

However, because theme app extensions only allow specific files to be included assets, this is impossible, so I currently have 2 separate implementations of my logic: one in Rust, and another in TypeScript.

This leads to duplicate effort when building apps on top of Shopify's latest APIs.

**Comment by blanklob** [comment]
how would you use it in the frontend?

**Comment by thosakwe** [comment]
> how would you use it in the frontend?

@blanklob

Great question.

The goal is client-side calculations of discounts.

My app provides various logic conditions for when discounts should apply, and I'd prefer to have 1 single implementation that can be used in multiple places.

**Comment by bkspace** [comment]
You can already do this, by just hosting your WASM elsewhere. I'd be quite careful whilst doing this. WASM can be compressed very well (normally up to 50%), but you'd still be looking at sticking a ~50kb file in the storefront. The better approach is sadly to re-write the logic in Javascript, IMO. There are other big issues as well.

With Discount Kit, we run the WASM as an endpoint which can then be called from the storefront. We are working on a significantly better approach which I can share in future.

**Comment by thosakwe** [comment]
@bkspace Thanks for your response.

I'll probably stick with having a separate TS implementation, which gets built into the theme app extension. That way, I don't have to host it on my server.

**Comment by amcaplan** [comment]
Ah, sorry, I missed the reference to the other issue. @nickwesselman is there anything to update about [performance improvements](https://github.com/Shopify/function-examples/discussions/329#discussioncomment-6885564)? I wonder if this is just going to be a temporary issue anyway, and if JS will be sufficiently performant soon, then this will become a non-issue.

**Comment by itsjustriley** [comment]
👋  Hi @thosakwe!

Thanks for this suggestion. We've implemented WASM file support for theme app extension assets. This change should be available in the next minor release. 🎉 

(I saw you commented on the change itself, but am commenting here as well for visibility).
