### ISSUE TITLE
error coming from 'bundle install'

### ISSUE THREAD

**Issue by Ankitdeardigital** [Shopify/cli#3914]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme, Other

### Expected behavior

I encountered this error while running the Shopify theme development.
![Screenshot 2024-05-21 144225](https://github.com/Shopify/cli/assets/118437296/89ed6cb0-008a-43c8-b08d-98a36619da55)

[https://prnt.sc/vLKHD35jzzT0](url)

### Actual behavior

![Screenshot 2024-05-21 144225](https://github.com/Shopify/cli/assets/118437296/5a7a9abb-d255-4ee0-868c-fd4eed1d0626)

### Verbose output

```shell
using npm
```

### Reproduction steps

1. shopify theme dev 

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.60.1

### Shell

git version 2.40.0.windows.1

### Node version (run `node -v` if you're not sure)

node-v20.13.1

### What language and version are you using in your application?

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

**Comment by jamesmengo** [comment]
👋🏻 Hey @Ankitdeardigital 

This appears to be an issue with your environment setup. Unfortunately, troubleshooting and resolving environment issues falls outside the scope of the support we provide

I'd suggest looking into the `ffi` gem, or troubleshooting your ruby environment.

I'm going to close this issue for now - if the issue persists or you find a solution, please update or re-open this issue :) 

Hopefully that helps!

**Comment by navdeep-soni** [comment]
Hi @jamesmengo 

I am getting the same error.
I have switched back to rubyinstaller-devkit-3.0.7-1-x64 with MSYS2 component base installation

and currently, my Shopify CLI version is 3.60.1

**Comment by alex-suarez-pc** [comment]
@navdeep-soni 

after installing everything or run this
1.  rubyinstaller-devkit-3.0.7-1-x64 with MSYS2 component base installation

lastly you need to do this in your terminal: (open terminal as administrator)
1. ridk enable
2. gem install bundler 

open new terminal and run shopify theme dev

**Comment by navdeep-soni** [comment]
@alex-suarez-pc 

I tried that but this worked for me

https://github.com/Maher4Ever/wdm/issues/27#issuecomment-2171037041
