### ISSUE TITLE
[Bug]: Theme CLI: Shopfiy Theme Push Not Reporting 50 Char Limit Error

### ISSUE THREAD

**Issue by woodbrettm** [Shopify/cli#3950]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

If I do `shopify theme push -e <env> --unpublished`, and then enter a name when it prompts me to do so. If the name is over 50 characters, I should get an error specifying it didn't work due to too many characters. Only reason I know 50 characters is the limit is because it's mentioned in the Shopfiy admin ui if I try to change a theme name there with too many characters.

### Actual behavior

I just simply get an unexpected error occurred. Not a big deal, but would be nice to have a message for theme names too long.

### Verbose output

```shell
✗ An unexpected error occurred.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

The Submit an Issue Link I was given in the error message is broken:
https://github.com/Shopify/shopify-cli/issues/new?title=%5BBug%5D%3A+ShopifyCLI%3A%3AAPI%3A%3AAPIRequestClientError%3A+422%0A%7B%22errors%22%3A%7B%22name%22%3A%5B%22is+too+long+%28maximum+is+50+characters%29%22%5D%7D%7D&labels=type%3Abug&template=bug_report.yaml&stack_trace=%2Fpnpm%2Fglobal%2F5%2F.pnpm%2F%40shopify%2Bcli%403.60.1%2Fnode_modules%2F%40shopify%2Fcli%2Fdist%2Fassets%2Fcli-ruby%2Flib%2Fshopify_cli%2Fapi.rb%3A80%3Ain+%60block+in+request%27%0A%2Fpnpm%2Fglobal%2F5%2F.pnpm%2F%40shopify%2Bcli%403.60.1%2Fnode_modules%2F%40shopify%2Fcli%2Fdist%2Fassets%2Fcli-ruby%2Fvendor%2Fdeps%2Fcli-kit%2Flib%2Fcli%2Fkit%2Futil.rb%3A172%3Ain+%60retry_after%27%0A%2Fpnpm%2Fglobal%2F5%2F.pnpm%2F%40shopify%2Bcli%403.60.1%2Fnode_modules%2F%40shopify%2Fcli%2Fdist%2Fassets%2Fcli-ruby%2Flib%2Fshopify_cli%2Fapi.rb%3A89%3Ain+%60request%27%0A%2Fpnpm%2Fglobal%2F5%2F.pnpm%2F%40shopify%2Bcli%403.60.1%2Fnode_modules%2F%40shopify%2Fcli%2Fdist%2Fassets%2Fcli-ruby%2Flib%2Fshopify_cli%2Ftheme%2Ftheme_access_api.rb%3A41%3Ain+%60rest_request%27%0A%2Fpnpm%2Fglobal%2F5%2F.pnpm%2F%40shopify%2Bcli%403.60.1%2Fnode_modules%2F%40shopify%2Fcli%2Fdist%2Fassets%2Fcli-ruby%2Flib%2Fshopify_cli%2Ftheme%2Ftheme_admin_api.rb%3A38%3Ain+%60rest_request%27&os=x86_64-linux-gnu&cli_version=3.60.1&ruby_version=3.1.2p20&shell=%2Fbin%2Fbash
```

### Reproduction steps

1. `shopify theme push -e <env> --unpublished`
2. Enter too long name
3. General error.

### Operating System

Ubuntu 24 in Devcontainer

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.60.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

20

**Comment by itsjustriley** [comment]
Hi @woodbrettm!

I wasn't able to reproduce this issue in the latest version of the CLI, which uses the TypeScript implementation of `shopify theme push`.

![image](https://github.com/user-attachments/assets/6709dff7-82cf-418f-824e-5a54bce00d23)

When running the older Ruby implementation of `shopify theme push` I was able to reproduce the described error message. The CLI will run the Ruby implementation when you use the `--stable` or `--password` flag. Please check to see if you have `password` as an ENV variable, as this may result in the CLI using the Ruby implementation without explicitly adding an extra flag. 

Let me know if that resolves the issue, and if not we can do some more digging.
