### ISSUE TITLE
[Feature]: allows configs in sub-directories

### ISSUE THREAD

**Issue by zirkelc** [Shopify/cli#4021]
### What area(s) will this request affect?

App, Deployment

### What type of change do you want to see?

New feature

### Overview

Allow to specific the config by path for apps with multiple configs:

```sh
# uses shopify.app.test.toml
shopify app deploy --config test

# uses ./config/shopify.app.test.toml
shopify app deploy --config ./config/shopify.app.test.toml
```

### Motivation

I have an app with multiple different configs for custom apps to test new features. Currently, all configs must be in the app directory and are identified by their config name in `shopify.app.<config-name>.toml`

```
/my-shopify-app
├── /app
│   ├── root.tsx
├── package.json
├── tsconfig.json
├── shopify.app.<config-name>.toml
```

I would like to move all configs into a sub-directory like `/config` or even `/config/dev/`

```
/my-shopify-app
├── /app
│   ├── root.tsx
├── /config
│   ├── shopify.app.<config-name>.toml
│   ├── /test
│   │   ├── shopify.app.<config-name>.toml
├── package.json
├── tsconfig.json
```

**Comment by gonzaloriestra** [comment]
Thanks for the suggestion! It makes sense to me and the implementation shouldn't be complex.

@nickwesselman what do you think?

**Comment by zirkelc** [comment]
Hi @gonzaloriestra 

did you have a chance to look at this? I could work on a small PR to implement this feature, if your team agrees on implementing this in general.

**Comment by nickwesselman** [comment]
Hi @zirkelc -- This sounds reasonable, we'd accept a PR for this one!
