### ISSUE TITLE
[Bug]: Unable to deploy new extensions via CI/CD

### ISSUE THREAD

**Issue by kamdav** [Shopify/cli#4036]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

App should be updated with any new extensions

### Actual behavior

GitHub workflow action fails with an error relating to extension name. The extension doesn't currently exist within the dashboard for this particular app that I'm trying to deploy to, and if I run the command locally I am prompted with

```
Match custom-login-button (local name) with checkout-ui (name on Shopify Partners, ID: xxxxx)?
(y) Yes, match to existing extension
(n) No, create as a new extension
```

This still occurs even with the `-f` force flag. There doesn't seem to be an existing flag to make this deploy and always select 'No, create as a new extension', which is the ideal behaviour to resolve my issue. This prompt is unable to be selected via CI/CD and therefore it errors when deploying new extensions.

### Verbose output

```shell
Run shopify app deploy -f --source-control-url "$COMMIT_URL" --version v2.1.0
╭─ info ───────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Using shopify.app.toml:                                                     │
│                                                                              │
│    • Org:             xxx                                        │
│    • App:             xxxxxxx                           │
│    • Include config:  Yes                                                    │
│                                                                              │
│   You can pass `--reset` to your command to reset your app configuration.    │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Failed to prompt:                                                           │
│                                                                              │
│  Match custom-login-button (local name) with checkout-ui (name on Shopify    │
│  Partners, ID: xxxxxxxxx)?                                                │
│                                                                              │
│  This usually happens when running a command non-interactively, for example  │
│   in a CI environment, or when piping input from another process.            │
│                                                                              │
│  To resolve this, specify the option in the command, or run the command in   │
│  an interactive environment such as your local terminal.                     │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

Error: Process completed with exit code 1.
```

### Reproduction steps

1. Create a new extension under a different app config locally
2. Deploy the extension to a separate app config via CI/CI
3. The app attempting to be updated via CI/CD errors as it can't identify the new extension

### Operating System

Ubuntu

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.59.3

### Node version (run `node -v` if you're not sure)

v18.20.2

### What language and version are you using in your application?

Typescript v5.2.2

**Comment by amcaplan** [comment]
Hi @kamdav, this is actually working as designed. If you have run (for example) `app dev`, you have actually created the extension on the remote app. (It should also appear on the list of extensions in the Partners dashboard, possibly without a created version yet.)

Generally, this message is only presented when there is some ambiguity and it cannot match what you have locally to the remote list of extensions.

Are you able to do a deploy from your local environment? Deploying once from local should solve this issue.

**Comment by kamdav** [comment]
Hey @amcaplan , thanks for your reply.
Yeah if I run one of the commands locally against this config first, then I can complete the prompt and select that it's a new extension. My team work on a development version of the config, and the main app config only gets update via CI/CD. Your suggestion works, but as you mentioned it means locally running commands against the main app config, which we would rather not touch locally as it means potential for issues (for example if I accidentally ran `app deploy` instead of `app dev` pushing some unintended changes).
Can I make a request for a new flag on the deploy command which automatically creates new extensions for any that it hasn't identified in the remote app? This would mean the entire process can be resolved via CI/CD
