### ISSUE TITLE
issue with running npm run dev

### ISSUE THREAD

**Issue by ElonMuskOfficial** [Shopify/cli#4052]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Function

### Expected behavior

This should run without any errors

### Actual behavior

I am just installed Cart Transform Function  setup
and then run this and getting this error

── external error ────────────────────────────────────────────────────────────────────

Error coming from `npm exec -- javy-cli --version`

Command failed with exit code 3221225477: npm exec -- javy-cli --version

────────────────────────────────────────────────────────────────────────────────

### Verbose output

```shell
npm run dev -- --verbose

npm verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@10.8.1
npm info using node@v20.10.0
npm verbose title npm run dev
npm verbose argv "run" "dev" "--loglevel" "verbose"
npm verbose logfile logs-max:10 dir:C:\Users\ElonMusk\AppData\Local\npm-cache\_logs\2024-06-14T10_59_59_726Z-
npm verbose logfile C:\Users\ElonMusk\AppData\Local\npm-cache\_logs\2024-06-14T10_59_59_726Z-debug-0.log

> cart-transform-api@1.0.0 dev
> shopify app dev

16:30:12 │ graphiql         │ GraphiQL server started on port 3457

── external error ────────────────────────────────────────────────────────────────────

Error coming from `npm exec -- javy-cli --version`

Command failed with exit code 3221225477: npm exec -- javy-cli --version
npm verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
npm info using npm@10.8.1
npm info using node@v20.10.0
npm verbose title npm exec javy-cli --version
npm verbose argv "exec" "--" "javy-cli" "--version"
npm verbose logfile logs-max:10 dir:C:\Users\ElonMusk\AppData\Local\npm-cache\_logs\2024-06-14T11_00_12_665Z-
npm verbose logfile C:\Users\ElonMusk\AppData\Local\npm-cache\_logs\2024-06-14T11_00_12_665Z-debug-0.log
npm verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: extensions/cart-transformer
npm http fetch GET 200 https://registry.npmjs.org/javy-cli 1043ms (cache revalidated)
npm verbose cwd D:\SHOPIFY\cart-transform-api
npm verbose os Windows_NT 10.0.22631
npm verbose node v20.10.0
npm verbose npm  v10.8.1
npm verbose exit 3221225477
npm verbose code 3221225477

──────────────────────────────────────────────────────────────────────────────────────

npm verbose cwd D:\SHOPIFY\cart-transform-api
npm verbose os Windows_NT 10.0.22631
npm verbose node v20.10.0
npm verbose npm  v10.8.1
npm verbose exit 1
npm verbose code 1
```

### Reproduction steps

1. npm run dev -- --verbose
2.
3.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.61.2

### Node version (run `node -v` if you're not sure)

20.10.0

**Comment by HitenXCode** [comment]
facing same issue

**Comment by zane-wky** [comment]
https://github.com/Shopify/cli/issues/2626    Someone mentioned the same problem in this link

**Comment by ElonMuskOfficial** [comment]
@zane-wky I tried but it not working in my system

**Comment by ElonMuskOfficial** [comment]
I found a solution to the issue. Here are the steps I followed:

1. Downloaded `javy-x86_64-windows-v1.4.0.gz` from the [Javy GitHub releases page](https://github.com/bytecodealliance/javy/releases/tag/v1.4.0).

2. Extracted the file to get `javy.exe`.

3. Copied `javy.exe` to the directory: `C:\Users\<username>\AppData\Local\binarycache\Cache`.

4. Renamed `javy.exe` to `javy-v2.0.0` (removed the `.exe` extension).

5. Ran the project again, and it worked successfully.

These steps resolved the issue for me. 

Hope this helps!

**Comment by HitenXCode** [comment]
below solution worked for me!!!


I found a solution to the issue. Here are the steps I followed:

Downloaded javy-x86_64-windows-v1.4.0.gz from the [Javy GitHub releases page](https://github.com/bytecodealliance/javy/releases/tag/v1.4.0).

Extracted the file to get javy.exe.

Copied javy.exe to the directory: C:\Users\<username>\AppData\Local\binarycache\Cache.

Renamed javy.exe to javy-v2.0.0 (removed the .exe extension).

Ran the project again, and it worked successfully.

These steps resolved the issue for me.

Hope this helps!

**Comment by nickwesselman** [comment]
Installing [Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) appears to be the right solution — I would not recommend renaming binaries as there are great things in Javy 2.0 that you will want to take advantage of.

We are looking into why this dependency was introduced and whether we can remove it.

**Comment by saulecabrera** [comment]
I've opened https://github.com/bytecodealliance/javy/pull/670 and I've confirmed that it fixes the issues and restores the version of the previous version (which doesn't require installing Visual C++).

**Comment by jantnovi** [comment]
Resolved

**Comment by lucas-paiano** [comment]
what did the job for me was, as mentioned here, deleting the file located in C:\Users\<user>\AppData\Local\binarycache\Cache.
But, instead of downloading it from their repo. I updated shopify cli. That installed its latest version into that same folder. 
I also have the latest stable version of node.js and npm. I dont know if that had anything to do with this fix.
