### ISSUE TITLE
[Feature]: Where is the interface to get the shopify node tree

### ISSUE THREAD

**Issue by bxxxe** [Shopify/cli#4129]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

New feature

### Overview

now only found:
https://shopify.dev/docs/api/admin-graphql/unstable/queries/productTaxonomyNodes#field-producttaxonomynodeconnection-pageinfo
this api need to find each node extend for many times
sb. told me used to be have a api one time get all node tree data,but they say now it disappear.
so the one with the big dick can tell me if I still have the old interface

### Motivation

writing a shopify category node tree .but use now api always have problems

**Comment by isaacroldan** [comment]
Hi @bxxxe, i'm sorry but this is not a CLI question or proposal so i'll be closing this issue. 
I think this would be best posted in the community forums :)
