### ISSUE TITLE
Having issue in shopify cli 

### ISSUE THREAD

**Issue by Varunchauhan007** [Shopify/cli#4130]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It should serve theme 

### Actual behavior

Having this error during serving theme 
![Error](https://github.com/Shopify/cli/assets/107676232/d17ca401-f6e6-46e0-ab94-36767c5dc6b3)

### Verbose output

```shell
Using Npm
```

### Reproduction steps

1. Install shopify cli for theme with all the dependency .
2. Then create a dev environment using command "shopify theme dev" .

### Operating System

Windows 10 Pro

### Shopify CLI version (check your project's `package.json` if you're not sure)

Shopify CLI version: 3.63.1

### Shell

Git bash

### Node version (run `node -v` if you're not sure)

node version : v20.15.0

### What language and version are you using in your application?

ruby 3.3.3

**Comment by jamesmengo** [comment]
Hey @Varunchauhan007, thanks for raising this. This seems to be an issue with windows / ruby packaging

This looks similar to [error coming from 'bundle install' · Issue #3914 · Shopify/cli](https://github.com/Shopify/cli/issues/3914).

Could you please try the fix / workaround there and reopen this issue if it persists?

We're working on removing Ruby as a dependancy in the CLI - thanks for your patience in the meantime!
