### ISSUE TITLE
Exceeded WEBHOOK_SUBSCRIPTION registrations

### ISSUE THREAD

**Issue by fairknowe** [Shopify/cli#4139]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

`shopify app dev` should allow me to start my App. `shopify app deploy` should allow me to update my webhooks subscriptions.

### Actual behavior

In both cases, I get an error, `You cannot register 18af961860ad930c0a490aab2c65d6 because this app already has the maximum number of 100 registrations allowed for this extension type.` I can no longer test my app now.

### Verbose output

```shell
Sending "Partners" GraphQL request:
  mutation ExtensionCreate(
    $apiKey: String!
    $type: ExtensionType!
    $title: String!
    $config: JSON!
    $context: String
    $handle: String
  ) {
    extensionCreate(
      input: {apiKey: $apiKey, type: $type, title: $title, config: $config, context: $context, handle: $handle}
    ) {
      extensionRegistration {
        id
        uuid
        type
        title
        draftVersion {
          config
          registrationId
          lastUserInteractionAt
          validationErrors {
            field
            message
          }
        }
      }
      userErrors {
        field
        message
      }
    }
  }

With variables:
{
  "apiKey": "*****",
  "type": "WEBHOOK_SUBSCRIPTION",
  "title": "18af961860ad930c0a490aab2c65d6",
  "config": "{}",
  "context": "",
  "handle": "18af961860ad930c0a490aab2c65d6"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.63.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json

2024-06-30T13:02:49.268Z: Request to https://partners.shopify.com/api/cli/graphql completed in 302 ms
With response headers:
 - cache-control: max-age=0, private, must-revalidate
 - content-type: application/json; charset=utf-8
 - etag: W/"fa213da5f6fa9d7c40671a9096b94d14"
 - x-request-id: f6f40d47-b409-49ec-a31b-c159d21bcc58-1719752569
    
╭─ error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                             │
│  You cannot register 18af961860ad930c0a490aab2c65d6 because this app already has the maximum number of 100 registrations allowed for this   │
│  extension type.                                                                                                                            │
│                                                                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### Reproduction steps

1. Create `shopify.app.toml`
`# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "xxx"
name = "xxx"
handle = "xxx"
application_url = "https://xxx"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xxx.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_products,write_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://xxx/auth/callback",
  "https://xxx/auth/shopify/callback",
  "https://xxx/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "shop/update" ]
  uri = "/webhook/handler"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
`
3. Deploy `shopify.app.toml`
4. Run `shopify app dev` more than 100 times (I guess)
5. Get stopped from doing any more testing due to webhook subscription registration limit.

### Operating System

Debian 12

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.63.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

v21.7.1

### What language and version are you using in your application?

Ruby 3.3.3, Rails 7.1

**Comment by isaacroldan** [comment]
Hi @fairknowe, this has been fixed in version 3.63.2 which was just released.
Your app that reached 100 registrations i'm afraid will be blocked because of that (we are working on fixing that too)

But any new app using version 3.63.2 should never inadvertently reach that limit.
