### ISSUE TITLE
[Bug]: Admin extensions target environment

### ISSUE THREAD

**Issue by aurelienbobenrieth** [Shopify/cli#4147]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When developing extensions (admin extensions in this case) I am using React + Typescript.

I am using [`@effect`](https://github.com/Effect-TS/effect/tree/main/packages) to improve my DX + code quality. 
@effect/schema` is using Big integer literals.

However I cannot `dev` nor `deploy` the extension because admin extensions are targetting `es2015` environment.

I have many questions:
- First things first, am I missing something ?
- Why is it that such a recent feature is targetting such an outdated environment ?
- Is it something related to Shopify CLI or to Remote UI ?
- Is there anyway we can expect in the future a bump or to actually be able to specify our desired target environment ?

### Actual behavior

The bundle fails preventing me from using `@effect/schema`.

### Verbose output

```shell
X [ERROR] Big integer literals are not available in the configured target environment ("es2015")
```

### Reproduction steps

1. Add native Big Integer to your admin extension without polyfill.
2. Try to `dev` or `deploy`

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.63.1

### Node version (run `node -v` if you're not sure)

v22.3.0

### What language and version are you using in your application?

Node v22.3.0, Typescript 5.5.2

**Comment by isaacroldan** [comment]
Hey @aurelienbobenrieth, we are looking into this, i'll update the issue once we have more info 👌
