### ISSUE TITLE
Paths ~ not being recognized

### ISSUE THREAD

**Issue by arimtiaz** [Shopify/cli#4164]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

No issues should have occured as I didnt even touch the codebase. Just created app using the cli.

### Actual behavior

It is showing this error, and I posted on the shopify community and seems like a lot of other people are facing this problem recently. 

<img width="1327" alt="Screenshot 2024-07-04 at 12 23 33 PM" src="https://github.com/Shopify/cli/assets/83642378/869f92fc-54f0-452b-9fb4-98789b4c2f36">

### Verbose output

```shell
I was able to create a temporary fix by manually setting the paths from ~ to ./
```

### Reproduction steps

1. No idea
2.
3.

### Operating System

Mac Os

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.63

**Comment by shauns** [comment]
This isn't a CLI issue, so will close here, but feel free to drop a question on the support forum or the remix template repo if you think its a bug.

I think what you're seeing though is that `shopify.server.js` is a JS file: it's ran as-is through node, and isn't processed by Typescript. So, the configuration in `tsconfig.json` to support `~` style paths doesn't come into things.
