### ISSUE TITLE
[Feature]: independent extension deployment

### ISSUE THREAD

**Issue by andrewpye** [Shopify/cli#417]
### What area(s) will this request affect?

Deployment

### What type of change do you want to see?

Substantial change to existing feature

### Overview

The ability to deploy individual extensions instead of being forced to deploy all extensions associated with an app simultaneously.

### Motivation

We're developing a checkout UI extension and are targeting release at GA, meaning that our extension needs to be complete in the next couple of weeks. The extension development itself has been straightforward; however, as a team with an app that pre-dates Shopify CLI by several years, we're severely disadvantaged by the constraints imposed by the apparent requirement to use CLI v3 to create and deploy checkout UI extensions:

- the front and back ends of our app, and an existing theme app extension, all live in separate repositories and currently get deployed independently (not via Shopify CLI);
- we started developing our checkout UI extension by scaffolding via the CLI as per the [Shopify guides](https://shopify.dev/apps/checkout/delivery-instructions/getting-started#step-1-scaffold-a-new-extension); this was done in a separate repository to avoid going "monolithic" with our code;
- when we attempt to deploy our checkout UI extension to our app, the deployment fails because we have two extensions registered to the app (the theme app extension and the checkout UI extension) but the project we're deploying only contains the latter;
- our app is available on platforms other than Shopify, so restructuring our existing independent repositories into a single monolithic repo just to be able to deploy a checkout UI extension to Shopify is not viable.

**Comment by jeanffc** [comment]
same

**Comment by zakariamofaddel** [comment]
This was possible in the the V2 of the CLI and it was very flexible and allowed to keep the extension in a separate repo and for other more interesting use cases.
I could just `cd` into the extension folder and run `shopify extension push`.

It would be nice to have an optional flag on the command that allows to specify the path to the folder of the extension, for example `shopify app deploy --path="relative/path/to/extension"`.

For my use case it would be fine even if the CLI looked recursively for `.toml` files in the `extensions` folder instead of only looking for the direct sub-folders.

These are pretty big limitations :/

**Comment by gonzaloriestra** [comment]
The latest release (3.12.0) allows [custom extension directories](https://github.com/Shopify/cli/pull/454), I hope you find it useful 🙂.

But deploying extensions separately is something that we won't allow, at least in the short term. The idea is that your local environment will be the source of truth of the state of the app, meaning that if you remove an extension there, it will be unregistered from the app.

So I'm closing here, but thanks a lot for your feedback!

**Comment by andrewpye** [comment]
> The latest release (3.12.0) allows [custom extension directories](https://github.com/Shopify/cli/pull/454), I hope you find it useful 🙂.

Thanks for the update @gonzaloriestra. Is it possible to use this new functionality to maintain extensions in separate repositories? That was actually part of the reason that I opened this request. The need to maintain all extensions in a single repository is pretty opinionated and has resulted in my organisation having to merge two independent areas of work that are owned by different groups into a single shared repository, which isn't ideal. It's probably too late by now to split them back out into separate repos, but I'm curious if it'd be theoretically _possible_ (e.g. by setting something like `extensionDirectories = ["../*extension*/*/**"]` in a "master" extensions repo and having the separate extension repos in their own directories alongside that master extensions repo) 🤔 

> The idea is that your local environment will be the source of truth of the state of the app, meaning that if you remove an extension there, it will be unregistered from the app.

This seems to contradict the docs [here](https://shopify.dev/apps/checkout/delivery-instructions/getting-started#step-3-deploy-the-extension) for checkout UI extensions which says:

>After you register an extension, it can't be undone.

Is the ability to unregister an extension something that is in the pipeline, or does it only apply to certain types of extension (not including checkout UI extensions)?

**Comment by gonzaloriestra** [comment]
> Is it possible to use this new functionality to maintain extensions in separate repositories?

It should be possible, that was one of the ideas behind this change.

> Is the ability to unregister an extension something that is in the pipeline?

Yes, I was talking about our plans. I know it's not possible now, but we are working on it.

**Comment by andrewpye** [comment]
> > Is it possible to use this new functionality to maintain extensions in separate repositories?
> 
> It should be possible, that was one of the ideas behind this change.

Interesting, could you share how it was intended to be used to achieve this result? 🤔 



> > Is the ability to unregister an extension something that is in the pipeline?
> 
> Yes, I was talking about our plans. I know it's not possible now, but we are working on it.

This is interesting, thanks for sharing!
