### ISSUE TITLE
[Bug]:Failed to load assets

### ISSUE THREAD

**Issue by wren333** [Shopify/cli#4172]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It is running properly, but the js resource is not running properly

### Actual behavior

![35E564D3-7B1E-4688-8187-2D5A91774195](https://github.com/Shopify/cli/assets/147241999/4d31c807-cb75-4327-83f5-a371bc895cc9)

### Verbose output

```shell
shopify theme dev --store
```

### Reproduction steps

1.shopify theme dev --store,Switch stores and log in to the store account,Running a new template
2.When I switch back to the original store and log back into the original account,Run another template
3.The above error occurs

### Operating System

Window10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.63.2

### Shell

git

### Node version (run `node -v` if you're not sure)

v20.13.1

### What language and version are you using in your application?

Ruby 3.3.0

**Comment by jamesmengo** [comment]
Hey @wren333!
Thanks for the report.

Could you please run this command with the `--verbose` logs and share those here? Starting from when you call the command to the point where you are encountering the problem.

Any additional information would be much appreciated, such as the content of the templates you're viewing.
If these contain sensitive materials, please feel free to email me at james.meng@shopify.com

**Comment by darslu** [comment]
So much bug haven't seen ever. Should be fired all who works there. Terrible. Not acceptable. Theme Kit is amazing tool, Shopify CLI is useless time wasting peace of sh...

**Comment by jamesmengo** [comment]
@darslu thanks for your feedback!

Please remember that there are humans behind the screen working to improve the CLI offerings with the resources that are available.

Let's keep the conversation constructive. If you have any actionable information such as bug reports or feature ideas, please feel free to open an issue. Your frustration is understandable, but let's try to focus on being constructive moving forward 🙂
