### ISSUE TITLE
[Bug]: IO::TimeoutError: Failed to open TCP connection to wellnessextract-au.myshopify.com:443 (Blocking operation timed out!)

### ISSUE THREAD

**Issue by vivekwellness** [Shopify/cli#4212]

**Comment by gonzaloriestra** [comment]
Hi! Could you please add more details? The easiest way is to close this issue and open a new one from [here](https://github.com/Shopify/cli/issues/new?assignees=&labels=Type%3A+Bug&projects=&template=bug-report.yml&title=%5BBug%5D%3A+%3CYOUR+ISSUE+TITLE%3E), filling all the fields. Thanks!
