### ISSUE TITLE
[Feature]: TOML Completion and Validation with JSON Schema

### ISSUE THREAD

**Issue by patjakubik** [Shopify/cli#4250]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

New feature

### Overview

Would be pretty cool to have TOML completion and validation working when using [Even Better TOML VScode extension](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml).

More info here: https://taplo.tamasfe.dev/configuration/using-schemas.html#using-schemas

### Motivation

Some companies, such as Cloudflare do that already with their Wrangler TOML. I like that you don't need to check documentation to see what is supported by CLI.

**Comment by gonzaloriestra** [comment]
Thanks for the suggestion. This is something that's already in our radar, so I'm closing here. I hope we can have something soon!

cc: @nickwesselman @shauns @jantnovi
