### ISSUE TITLE
[Bug]: Shopify CLI version is not updating

### ISSUE THREAD

**Issue by jawadbuttoficial** [Shopify/cli#4251]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

I try to update the Shopify CLI version to latest one by running the command 
npm install -g @shopify/cli@latest
After that I run the command
shopify version
It gives me 2.36

### Actual behavior

However, It should be updated to version 3.50.0. I have updated the npm, node, and each and everything but still facing the same issue.

### Verbose output

```shell
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/--verbose - Not found
npm error 404
npm error 404  '--verbose@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: C:\Users\jawad\AppData\Local\npm-cache\_logs\2024-07-30T08_45_51_276Z-debug-0.log
```

### Reproduction steps

1. Run the command to npm install -g @shopify/cli@latest
2. Check for the version
3.

### Operating System

window 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

2.36

### Shell

cmd

### Node version (run `node -v` if you're not sure)

20.16

### What language and version are you using in your application?

ruby 3.2.5

**Comment by gonzaloriestra** [comment]
It seems you have a conflict with an old installation of the CLI 2.x. You should be able uninstall it with `gem uninstall shopify-cli`.

More info: https://shopify.dev/docs/storefronts/themes/tools/cli/migrate#step-2-uninstall-shopify-cli-2-x
