### ISSUE TITLE
[Feature]: Document how to upgrade to this CLI from the ruby CLI

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/cli#4258]
### What area(s) will this request affect?

Extension

### What type of change do you want to see?

New feature

### Overview

Please document the steps necessary to switch to this version of the CLI from the Ruby version.

### Motivation

I see that the ruby CLI is deprecated and it points to this tool, but there are no clear steps for how to upgrade to this tool. The command set is different and it seems like configuration is handled differently. It would be nice to have some documentation about how to make the switch.

**Comment by gonzaloriestra** [comment]
Hi! Sorry for the late response.

You can find a migration guide here: https://shopify.dev/docs/apps/build/cli-for-apps/migrate-to-latest-cli

Hope it helps.
