### ISSUE TITLE
[Bug]: app update-urls deprecation has no alternative for CI/CD

### ISSUE THREAD

**Issue by Kyon147** [Shopify/cli#4266]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

`app update-urls` has no alternative for CI/CD so we are no longer able to build preview builds that can update some development apps in our partners account for testing.

We have 3 apps for testing staging work, and used update-urls in our build pipeline to set the urls correctly based on the build url for that preview.

Now that this cli has been removed how can we continue to run CI/CD effectively for our apps? Not every process works well in TOML files.

### Actual behavior

Does not work

### Verbose output

```shell
NA
```

### Reproduction steps

NA

### Operating System

NA

### Shopify CLI version (check your project's `package.json` if you're not sure)

3

**Comment by rhyek** [comment]
@gonzaloriestra there is no `shopify app config deploy` documented command and I tried it with `3.65.3` and it doesn't work. I am trying `shopify app deploy --force --no-release` which is what we use in CICD and it does not update the URLs.

**Comment by Kyon147** [comment]
Hi @gonzaloriestra 

Apologies for my late reply, I'll have a test with the config files and see if this works. 

it's a bit of a bloated approach compared to the cli keeps things a lot simpler as you don't need separate config files just to run one single command in the CI/CD and you have the overhead of now managing multiple configs.

Would love to know the reasoning on how this is better than the removed cli command. Could you not have kept the cli for those that don't need the whole config?

**Comment by gonzaloriestra** [comment]
And the application URL is not being updated? Are you sure the deploy is using that TOML? It should show the used one at the beginning. And then, the application_url should be marked as updated if it changed.

![Image](https://github.com/user-attachments/assets/0cdc0c84-d31c-4584-a06b-6051e789ebf1)

Could you share the verbose output?

**Comment by rhyek** [comment]
I think it's relates to the --no-release flag. I tried on a new app and new store and it worked.
