### ISSUE TITLE
I can't resolve this error. Deployment failed because this local project doesn't seem to match the app "" in Shopify Partners.

### ISSUE THREAD

**Issue by Koala-afurubayashi** [Shopify/cli#433]
Thank you for your daily development.

https://github.com/Shopify/cli/blob/f7bb911dcc05dae60f6aa42554a041b1cb60f275/packages/app/src/cli/services/environment/identifiers.ts#L11

When I run `npm run deploy`, I get this error.
I ran this tutorial

https://shopify.dev/apps/online-store/theme-app-extensions/getting-started#step-1-create-a-new-extension

`npm run scaffold extension`

I get this error on deploy after running

It seems that you are looking at some length, but we have added a checkout UI as a test from the management screen.

Is this caused by a different number of extended APPs locally and remotely?

Also, how can I delete the extension APP added from the management screen?

```
Deployment failed because this local project doesn't seem to match the app "APP　NAME　IS　HERE" in Shopify Partners.

  What to try:
    • If you didn't intend to select this app, run yarn deploy --reset
    • If this is the app you intended, check your local project and make sure
      it contains the same number and types of extensions as the Shopify app
      you've selected. You may need to scaffold missing extensions.
```

By the way, the build of the newly created extended APP will be successful, and the display of the APP itself can be confirmed after executing dev normally.

**Comment by Koala-afurubayashi** [comment]
Because of this error, the development of the extension APP is not progressing!, Because of this error, the development of the extended APP will not proceed!

**Comment by amcaplan** [comment]
Hi @Koala-afurubayashi, thanks for letting us know about your friction around this issue.

As you confirmed, your diagnosis was correct that the local set of extensions need to match what's in the admin. This is a check we do to ensure your local environment doesn't fall out of sync with what you deployed. However, the team has been discussing ways to circumvent the check in cases where it really is necessary to deploy only a subset of the extensions in your app.

You're correct that we're looking at length, however that's just a rough way to verify whether the extensions you've defined locally match the extensions in the admin. If there are multiples of the same extension type, we make sure to identify which is which before proceeding.

**Comment by Koala-afurubayashi** [comment]
@amcaplan 
Thank you anaplan for your reply.
I understand that it is necessary to match the number of local extension applications.
Then, I would like you to tell me how to synchronize because it is roughly fine.
While I'm researching how to do that, some apps have been created that are making noise.
Extension apps suffer because there is no way to remove them.
