### ISSUE TITLE
[Bug]: Shopify CLI experiencing heavy throttling by Partners API

### ISSUE THREAD

**Issue by keiraarts** [Shopify/cli#4335]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension, Function, Theme, Other

### Expected behavior

Deploying a preview of my Shopify app should upload all of my extension points and start the development server.

### Actual behavior

Uploading more than (50) customer accounts checkout points (ex: Shopify Flow templates, customer accounts extensions, checkout ui extensions, post purchase extensions etc) is throttled by the Shopify CLI an I can't upload them.

<img width="304" alt="ff9527f9401d9488e0d56639cbe9211a" src="https://github.com/user-attachments/assets/07bc0246-58f6-44f7-874b-31f9e636e29a">

### Verbose output

```shell
thank-you-static │ thank-you-static
successfully built
  third-party-integration │ third-party-integration
successfully built
             thank-you-v2 │ thank-you-v2 successfully
built
 individual-order-summary │ individual-order-summary
successfully built
      order-status-static │ order-status-static
successfully built
     account-cancel-order │ account-cancel-order
successfully built
       customers-accounts │ customers-accounts
successfully built
     order-editing-badges │
 cart-transform-extension │ Bundling JS function...
  payment-methods-upsells │ Bundling JS function...
 cart-transform-extension │ Running javy...
  payment-methods-upsells │ Running javy...
 cart-transform-extension │ Done!
  payment-methods-upsells │ Done!

╭─ success ────────────────────────────────────────────╮
│                                                      │
│  extensions built!                                   │
│
```

### Reproduction steps

1. Create 100 extension points that have a Typescript build step.
2. yarn Shopify dev
3. Shopify builds them and fails on the last 10% because it's throttled by the Partners APi.

### Operating System

Mac OS Monetery

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.65.3

### Node version (run `node -v` if you're not sure)

v18

### What language and version are you using in your application?

Node, Typescript

**Comment by amcaplan** [comment]
Hi @keiraarts, this is related to an ongoing investigation. We will be posting updates to #4318.

Closing in favor of the existing issue, please follow the thread there.

**Comment by amcaplan** [comment]
Ah, wait, now I see this was a 429. Looks like we're throttling extension draft updates server-side, but not throttling effectively on the CLI side. So this is a CLI issue, not an API issue.

Reopening.
