### ISSUE TITLE
[Bug]: Selecting extension targets in the developer console does not work

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/cli#4421]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Clicking on extension target should load extension in specific target

### Actual behavior

I see that extensions developer console creates different links depending on which target I click but it doesn't take any effect, it always loads the first target. I have to comment out other targets in extension toml file and restart dev server

### Verbose output

N/A

### Reproduction steps

1. Create checkout extension with two targets
2. Run shopify app dev
3. Open developer console
4. Click on the name of first target - it will work
5. Click on the name of second target - it will still load in the first target
### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.66.1

**Comment by ctrlaltdylan** [comment]
This isn't a trivial bug.

It's causing developers to comment out extension targets in their toml files in order to target properly develop locally.

This introduces the real risk of deploying a version without the proper targets unless the developer takes extra care to uncomment lines before publishing.
