### ISSUE TITLE
[Bug]: Error coming from `npm install

### ISSUE THREAD

**Issue by pablocevalenzuela** [Shopify/cli#4425]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Hi everyone,

Please, could you help me?

I have an error after press enter in TypeScrip step during Shopify App setup using remix:

Your project name?
✔  ar-app-shop-eco-v5

?  Get started building your app:
✔  Start with Remix (recommended)

?  For your Remix template, which language do you want?
✔  TypeScript

Useful information:

1- I updated Node to 18.16.0
2- Node is working fine with my other React projects.

Thank you very much!

![Image](https://github.com/user-attachments/assets/e7eaef8d-9f10-49ed-adf1-d8c9eadd46d5)

### Actual behavior

With problem during setup Shopify App with CLI and using remix

### Verbose output

...

### Reproduction steps

1.
2.
3.

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.66.1

### Node version (run `node -v` if you're not sure)

v18.16.0

### What language and version are you using in your application?

Node

**Comment by isaacroldan** [comment]
@etienne-ditchlabs is correct, you need to have at least version 18.20.
I'll close this issue since the solution is clear and is not a CLI issue :)
