### ISSUE TITLE
[Bug]: @shopify/app v3.49.0 "deploy" command fails with unexpected error

### ISSUE THREAD

**Issue by sajidmasoodbscs** [Shopify/cli#4430]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

![Image](https://github.com/user-attachments/assets/5d6fc427-3f2d-4b89-8830-bcf999be3ca6)

### Actual behavior

Its  start when I do npm run dev. I was working a weak ago. Today is 10th September 2024. Its was successful working till 01 septamber2024

### Verbose output

Termail produce a lot of data in the. Not possible to copy and paste here

### Reproduction steps

1.npm run dev
2.
3.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.49.3

### Shell

cmd

### Node version (run `node -v` if you're not sure)

v18.16.1

### What language and version are you using in your application?

Node 18.16.1

**Comment by isaacroldan** [comment]
Hi @sajidmasoodbscs , It could be a temporary issue with the API.
In any case that is a pretty old version of the CLI, could you try to update to the latest one please? It should be version 3.66
