### ISSUE TITLE
[Bug]: JS assets no longer work on `theme dev` on 127.0.0.1 since 3.67.0

### ISSUE THREAD

**Issue by msev** [Shopify/cli#4479]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

With the previous version of CLI or with the `--legacy` flag, JS assets work.

### Actual behavior

JS assets no longer work on `127.0.0.1` since upgrading to Shopify CLI 3.67.0.

They're loaded, but I get a JS error in the console: 
```
Uncaught SyntaxError: missing ) after argument list (at vendors@theme.min.js?v=25063884737306468341726750322:1:131260)
```

When I go to the theme's remote url (`xxx.myshopify.com/?preview_theme_id=XXXX`), it works fine.

When I try with `theme dev --legacy`, everything works fine.

Here is the end of the JS file vendors@theme.min.js file opened from https://xxx.myshopify.com/cdn/shop/t/17/assets/vendors@theme.min.js?v=25063884737306468341726753546 (remote url):
![Image](https://github.com/user-attachments/assets/982cb67e-9e8c-4482-b832-099df89426c1)

And now here's the end of the JS vendors@theme.min.js file opened from http://127.0.0.1:9292/cdn/shop/t/17/assets/vendors@theme.min.js?v=25063884737306468341726752918 (CLI server url):
![Image](https://github.com/user-attachments/assets/987e18c5-445c-4336-b239-7e2bf50f964d)

I notice that `);` is missing at the very end of the file.

Would CLI “cut” the file?

Thanks for your help!

### Verbose output

---

### Reproduction steps

1. Run `shopify theme dev`
2. Go to 127.0.0.1

### Operating System

macOS 14.5

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.67.0

### Node version (run `node -v` if you're not sure)

v20.12.2

**Comment by khdigital94** [comment]
Hope there will be a fix asap.

Just upgraded to the latest version and my entire JS doesn't work, in normal dev and --legacy. Rolling back to an earlier version didn't help, i'm stuck now with a non working theme. Pushing it to a live theme on my dev store also doesn't make the JS work. What the fuck is happening?

**Comment by frandiox** [comment]
>I notice that ); is missing at the very end of the file.

I wasn't able to reproduce this. Does it only happen with this specific JS file or with every JS file in your local `assets` folder?
Can you create a small JS file and see if you get the same issue?

It might be related to some find-and-replace we do to proxy CDN access from JS files but not sure 🤔

**Comment by msev** [comment]
Thanks for your reply @frandiox.

It doesn't happen with all files, it seems to me that the weight of the file is not taken into account.

In my original message I had a file `vendors@theme.min.js` which was truncated but I had another JS file `theme.min.js` which was not truncated by the CLI.

Another example, when I'm in the development phase I have a single large `@dev-theme.min.js` file, it weighs 1.2mo locally and when I look at the CLI trimmed version (which doesn't work) there's only a few bytes difference.

There must be something going on on the CLI side, but I don't really understand the cutting rule.

I'm sorry if my comment doesn't help. 😅

**Comment by diegovogel** [comment]
@frandiox works for me! Thanks.

**Comment by diegovogel** [comment]
@frandiox Sorry for all the posts, but I have another data point.

This is also happening elsewhere on my site, including in content that is rendered directly by Liquid (no JS DOM generation).

Example:
![Image](https://github.com/user-attachments/assets/7b301a07-878a-4d4f-91ba-87048281b8e4)

becomes:
![Image](https://github.com/user-attachments/assets/5fdac288-912f-4503-84cf-7b9194b31926)

The character in this case is `×`.

I'd be happy to create a new issue if needed.

**Comment by changeyoucant** [comment]
I'm having [seemingly] the same problem with assets too.  cant load some assets .When I try with theme dev --legacy, everything works fine.

**Comment by frandiox** [comment]
>This is also happening elsewhere on my site, including in content that is rendered directly by Liquid (no JS DOM generation).

@diegovogel  This seems to be related to the encoding of HTML responses. Can you try this version of the CLI and let me know if it fixes it for you? https://github.com/Shopify/cli/pull/4512#issuecomment-2370609845

Aside from that, you probably don't have `<meta charset="utf-8">` in your layout, which would also fix this issue. After trying the new version to test the changes, you could also add this tag to your layout.

>I'm having [seemingly] the same problem with assets too. cant load some assets .When I try with theme dev --legacy, everything works fine.

@changeyoucant  This sounds like it might be unrelated. You can try what I mentioned above just in case but, if it doesn't work, please open a different issue with more information so that we can repro and debug it 🙏

**Comment by frandiox** [comment]
@diegovogel This is because it hadn't been released yet. It was released 2 hours after you posted your message 😅 
https://github.com/Shopify/cli/releases/tag/3.68.0

The other releases you saw were probably urgent patches and this one didn't make it there.
