### ISSUE TITLE
Getting this error: not found: bin/rails when I run `shopify app dev`

### ISSUE THREAD

**Issue by sankalpjonn** [Shopify/cli#4507]
I have followed all the instructions to set up a shopify app ruby template, ie.

1. bundle install
2. bin/rails app:template LOCATION=./template.rb

After doing this I go back to my root folder and run this command:

`shopify app dev`

This is the error I get:

 error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                        │
│  not found: bin/rails                                                                                                                  │
│                                                                                                                                        │
│  To investigate the issue, examine this stack trace:                                                                                   │
│    at getNotFoundError (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/chunk-2HGYYNE5.js:148)          │
│    at whichSync [as sync] (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/chunk-2HGYYNE5.js:202)       │
│    at checkCommandSafety (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/chunk-7QTS6ZWN.js:25192)      │
│    at buildExec (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/chunk-7QTS6ZWN.js:25172)               │
│    at exec2 (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/chunk-7QTS6ZWN.js:25150)                   │
│    at runCommands (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/index.js:168216)                     │
│    at launchWebProcess (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/index.js:168210)                │
│    at action (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/index.js:169395)                          │
│    at action (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/index.js:169015)                          │
│    at (usr/local/Cellar/shopify-cli/3.67.0/libexec/lib/node_modules/@shopify/cli/dist/chunk-7QTS6ZWN.js:30194)                         │
│                                                                                                                                        │

I am unable to get past this. Any help would be highly appreciated. Thanks in advance!

**Comment by remy727** [comment]
Same here. I didn't have the issue on `3.70.0` but I get the same error after upgrading to `3.71.1`

**Comment by gonzaloriestra** [comment]
It should be fixed in v3.71.2, sorry for the inconvenience.
