### ISSUE TITLE
shopify cli dev is so slowly

### ISSUE THREAD

**Issue by changeyoucant** [Shopify/cli#4508]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

shopify cli dev is so slowly

### Actual behavior

i use shopify cli develop shopify theme,but when i refresh page.need 20s to refresh ..............!

### Verbose output

....

### Reproduction steps

1.
2.
3.

### Operating System

windows shopify cli

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.58.0

### Shell

cmd

**Comment by GitYing** [comment]
I notice this issue only on windows try using wsl with unix maybe for a quick workaround

**Comment by changeyoucant** [comment]
> wsl with unix

yes only on windows , i will try it. thank you very much.

**Comment by karreiro** [comment]
👋 Hey @changeyoucant,

Thank you for reporting. I've noticed you're running Shopify CLI 3.58.0. Could you please try updating it to the latest version?

One of the enhancements introduced in Shopify CLI 3.67 was related to the development server performance, so you should no longer face this issue there.

Thank you for reporting this!

**Comment by jamesmengo** [comment]
@changeyoucant can you verify if this is persisting after upgrading to the new CLI - `3.67`?

@khdigital94 That's interesting! 🤔  

Could you specify which actions you notice slow performance in?
_e.g. On initialization,  When you reload the page, When you apply a change locally_

Could you run the command with `--verbose` output and leave a comment here with the information from the issue template? That may help us investigate where the slowdown is coming from :)

<details><summary>Issue Template</summary>

```
In which of these areas are you experiencing a problem?

Expected behavior

Actual behavior

Verbose output

Reproduction steps

Operating System

Shopify CLI version (check your project's package.json if you're not sure)

Shell

Node version (run node -v if you're not sure)

What language and version are you using in your application?
```

</details>

**Comment by changeyoucant** [comment]
> 👋 Hey folks,
> 
> Thank you for reporting.
> 
> We've tried to reproduce this problem on Windows, and as you may notice below, we couldn't reproduce any performance degradation there. So, we're closing this issue for now.
> 
> However, please feel free to re-open this issue or create a new one if you're still facing this problem. Please include the `--verbose` logs in the new report, so the team can understand the scenario you're facing and act on the fix for that.
> 
> ![Image](https://github.com/user-attachments/assets/c0149391-1383-426a-b48c-309d1ec3a065)
> 
> Thanks again for reporting.

thank you i update and is good!!!
