### ISSUE TITLE
[Bug]: Windows space in local yarn install directory - prevents create-app from working

### ISSUE THREAD

**Issue by richayles** [Shopify/cli#452]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

--

### Actual behavior

--

### Reproduction steps

1. Have space in user name in Windows (version 10)
2. try yarn create command
3.

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3

### Node version (run `node -v` if you're not sure)

18.1.0

**Comment by richayles** [comment]
![image](https://user-images.githubusercontent.com/984154/189650170-4b110558-4a9a-41a5-8495-53ea4f1456e3.png)
@meganmajewski

**Comment by richayles** [comment]
https://github.com/yarnpkg/yarn/issues/6851 is the underlying issue - and resolved it

**Comment by richayles** [comment]
@amcaplan came up during unite, then resolved shortly after, might be worth adding both options as a windows caveat. Feel free to close...

**Comment by amcaplan** [comment]
@shainaraskas do you think it's worth adding to docs?
