### ISSUE TITLE
[Bug]: Unexpected end of input error for JS files that contain curly apostrophes

### ISSUE THREAD

**Issue by nikitaourazbaev** [Shopify/cli#4535]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The file synced should be the same as the local file

### Actual behavior

The file does not get synced correctly, resulting in an “Uncaught SyntaxError: Unexpected end of input”

This seems to be related to https://github.com/Shopify/cli/issues/4525 and gets fixed with `npm i -g @shopify/cli@0.0.0-snapshot-20240920142835`

### Verbose output

2024-09-26T14:27:54.368Z: ← 200 (request_id: 2c1d0c57-3b07-462f-b6a7-f5bbb02e5f15-1727360873)
2024-09-26T14:27:54.832Z: Request to https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes/128731349105/assets/bulk.json completed in 952 ms
With response headers:
 - cache-control: no-cache
 - content-type: application/json; charset=utf-8
 - server-timing: processing;dur=847, socket_queue;dur=6.913, cfRequestDuration;dur=915.999889
 - x-request-id: dd4d5f17-d170-4099-8297-3f645fd92eee-1727360873

• 10:27:54 Synced » update assets/utils.js

### Reproduction steps

1. This file works: https://gist.github.com/nikitaourazbaev/99ea8d0c071662f82d3e1c5c0b585346#file-will-work-js
2. This file won’t work – only difference is the apostrophe after the word Shopify: https://gist.github.com/nikitaourazbaev/99ea8d0c071662f82d3e1c5c0b585346#file-wont-work-js

### Operating System

macOS Ventura 14.7

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.67.2

### Shell

Warp, fish

### Node version (run `node -v` if you're not sure)

v20.11.1

### What language and version are you using in your application?

Liquid

**Comment by frandiox** [comment]
@nikitaourazbaev Thanks for the reproduction files! As mentioned above, this is fixed in 3.68.0 (I've tested your files with and without the fix).
