### ISSUE TITLE
[Bug]: theme pull should not automatically delete files

### ISSUE THREAD

**Issue by vjanssens** [Shopify/cli#4562]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

**Summary**

The shopify theme pull command in Shopify CLI deletes local files not present in the remote theme by default. This behavior differs from standard version control systems like Git, where local untracked files are preserved during pull operations.

**Expected behavior**

The shopify theme pull command should:

1. Preserve local files not present in the remote theme by default, mirroring Git's behavior.
2. Only update or add files from the remote theme, without deleting local files.
3. Offer a flag (e.g., --delete) for users who want to remove local files not present remotely, rather than using this as the default behavior.

### Actual behavior

The CLI currently:

1. Deletes local files not present in the remote theme by default.
2. Offers a --nodelete flag to preserve files, which goes against the principle of least astonishment for users familiar with standard version control systems.

This personally caused a loss of several hours of work due to unexpected file deletion, highlighting the severity of this issue in real-world development scenarios.

### Verbose output

No verbose output needed.

### Reproduction steps

1. Create a new file in a theme
2. Run `shopify theme pull`
3. Observe added file to be gone

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.66.1

**Comment by rcasimmons** [comment]
Appreciate what you're saying but with regards to CLI, this is normal behaviour.

If you want to ignore files, have you tried using .shopifyignore in your directory? We use this across all projects.
