### ISSUE TITLE
[Bug]: A store without an active password can't successfully start up

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#4584]
Created from https://github.com/Shopify/cli/issues/4537#issuecomment-2385057322

> @karreiro 
> 
> 
> `shopify theme dev --store=SHOPURL.myshopify.com --theme-editor-sync --path=./shopify --verbose`
> 
> [...] # redacted
>
> ## Running it with `3.67.3`:
> I get the error my store password (NOT active) is wrong.
> <details><summary>Verbose Output</summary>
> <pre>
> 2024-10-01T07:53:24.973Z: Running command theme dev
> 2024-10-01T07:53:24.983Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
> []
> 
> 2024-10-01T07:53:24.984Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store SHOPURL.myshopify.com:
> []
> 
> 2024-10-01T07:53:24.984Z: Getting session store...
> 2024-10-01T07:53:24.985Z: Validating existing session against the scopes:
> [
>   "openid",
>   "https://api.shopify.com/auth/shop.admin.graphql",
>   "https://api.shopify.com/auth/shop.admin.themes",
>   "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
>   "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
>   "https://api.shopify.com/auth/partners.app.cli.access",
>   "https://api.shopify.com/auth/destinations.readonly"
> ]
> For applications:
> {
>   "adminApi": {
>     "scopes": [],
>     "storeFqdn": "SHOPURL.myshopify.com"
>   }
> }
> 
> 2024-10-01T07:53:24.985Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
> 2024-10-01T07:53:24.986Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:25.231Z: Request to https://accounts.shopify.com/oauth/introspection completed in 245 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"7cb82aee7d7d0d9e53c06e1f42e094f2"
>  - server-timing: processing;dur=28, socket_queue;dur=1.636, edge;dur=1.016, util;dur=0.0, cfRequestDuration;dur=165.999889
>  - x-request-id: 30e1dc43-1749-4e06-bfe6-cec28d397f15-1727769205
> 
> 2024-10-01T07:53:25.235Z: The identity token is valid: true
> 2024-10-01T07:53:25.236Z:
> The validation of the token for application/identity completed with the following results:
> - It's expired: false
> - It's invalid in identity: false
> 
> 2024-10-01T07:53:25.236Z: The current session is valid but needs refresh. Refreshing...
> 2024-10-01T07:53:25.237Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI2tTutwYQ-ozvtwZSJggBEhB9ASe8LhpBuIqpT98JCm-6GhCrYB6_DVpOGbFz7dAOD7YCEkCMWzcGKOQq3JtUNbGVbRPyldFtTPLl1hHHW9kkskKu9Rh4RsLIOjAJyvohAYUfacBVDv2rPd6Ivt1MmYx_h7QJ&refresh_token=atkn_CiEI2tTutwYQ2u6MuQaiARIKEKtgHr8NWk4ZsXPt0A4PtgISQIXH404VpcJtNJP95LQDbHE6z2QW5CzC0dNBNimdpXvfkchRkDK8F2R0-j1ij-80ZBbHr6zsU-sVilKHaiePkgc&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:25.510Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI2tTutwYQ-ozvtwZSJggBEhB9ASe8LhpBuIqpT98JCm-6GhCrYB6_DVpOGbFz7dAOD7YCEkCMWzcGKOQq3JtUNbGVbRPyldFtTPLl1hHHW9kkskKu9Rh4RsLIOjAJyvohAYUfacBVDv2rPd6Ivt1MmYx_h7QJ&refresh_token=atkn_CiEI2tTutwYQ2u6MuQaiARIKEKtgHr8NWk4ZsXPt0A4PtgISQIXH404VpcJtNJP95LQDbHE6z2QW5CzC0dNBNimdpXvfkchRkDK8F2R0-j1ij-80ZBbHr6zsU-sVilKHaiePkgc&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 272 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"c97b093b237fc4b8e55536b0458801af"
>  - server-timing: processing;dur=69, socket_queue;dur=2.206, edge;dur=2.016, util;dur=0.0, cfRequestDuration;dur=208.999872
>  - x-request-id: dad46e29-13d5-4158-8cb5-b8414a629106-1727769205
> 
> 2024-10-01T07:53:25.512Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=****
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:25.512Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=****
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:25.512Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=****
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:25.512Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2FSHOPURL.myshopify.com%2Fadmin
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:25.744Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=**** completed in 232 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"b7f9fb58e35b14965c35f4403c10d88f"
>  - server-timing: processing;dur=38, socket_queue;dur=1.413, edge;dur=1.014, util;dur=0.0, cfRequestDuration;dur=167.999983
>  - x-request-id: 33ecca3b-0252-48fa-8a6d-8efd4ddfa510-1727769205
> 
> 2024-10-01T07:53:25.769Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=**** completed in 257 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"83dbf3ebc7d619d51efeb84483d128a9"
>  - server-timing: processing;dur=42, socket_queue;dur=1.33, edge;dur=1.028, util;dur=0.05, cfRequestDuration;dur=177.000046
>  - x-request-id: 5b6abdf5-b4f6-47bf-89fd-01605b3a7d06-1727769205
> 
> 2024-10-01T07:53:25.770Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2FSHOPURL.myshopify.com%2Fadmin completed in 258 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"8281b6acc6e81553fdd8a5e615fabe38"
>  - server-timing: processing;dur=41, socket_queue;dur=1.144, edge;dur=1.02, util;dur=0.0, cfRequestDuration;dur=176.000118
>  - x-request-id: a2b789da-48ea-460b-bce4-ed30edc33398-1727769205
> 
> 2024-10-01T07:53:25.774Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=**** completed in 262 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"1b2c3546dc582c4d68478b12dba18ec7"
>  - server-timing: processing;dur=40, socket_queue;dur=1.865, edge;dur=2.016, util;dur=0.05, cfRequestDuration;dur=189.999819
>  - x-request-id: 9ce88dff-44b3-4b86-bb5d-eea29a532091-1727769205
> 
> 2024-10-01T07:53:25.775Z: Setting session store...
> 2024-10-01T07:53:25.783Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
> []
> 
> 2024-10-01T07:53:25.783Z: Getting session store...
> 2024-10-01T07:53:25.783Z: Validating existing session against the scopes:
> [
>   "openid",
>   "https://api.shopify.com/auth/shop.admin.graphql",
>   "https://api.shopify.com/auth/shop.admin.themes",
>   "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
>   "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
>   "https://api.shopify.com/auth/partners.app.cli.access",
>   "https://api.shopify.com/auth/destinations.readonly"
> ]
> For applications:
> {
>   "storefrontRendererApi": {
>     "scopes": []
>   }
> }
> 
> 2024-10-01T07:53:25.784Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
> 2024-10-01T07:53:25.784Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:26.019Z: Request to https://accounts.shopify.com/oauth/introspection completed in 236 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"db9a758dfdb3352e46697a1dab4b2c06"
>  - server-timing: processing;dur=31, socket_queue;dur=1.389, edge;dur=1.019, util;dur=0.05, cfRequestDuration;dur=171.000004
>  - x-request-id: 5a313072-9423-44ae-a109-e7db01ef1930-1727769205
> 
> 2024-10-01T07:53:26.020Z: The identity token is valid: true
> 2024-10-01T07:53:26.020Z:
> The validation of the token for application/identity completed with the following results:
> - It's expired: false
> - It's invalid in identity: false
> 
> 2024-10-01T07:53:26.020Z: Getting development theme...
> 2024-10-01T07:53:26.330Z: Request to https://SHOPURL.myshopify.com/admin/api/unstable/themes/165427315016.json?fields=id%2Cname%2Crole%2Cprocessing completed in 309 ms
> With response headers:
>  - content-type: application/json; charset=utf-8
>  - server-timing: processing;dur=194, cfRequestDuration;dur=234.999895, ipv6
>  - x-request-id: 5172edf4-2e58-425a-b2c5-5e18a2fdd30c-1727769206
> 
> ╭─ info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
> │                                                                                                                                   │
> │  You're using the new version of `shopify theme dev`.                                                                             │
> │                                                                                                                                   │
> │  Run `shopify theme dev --legacy` to switch back to the previous version.                                                         │
> │                                                                                                                                   │
> ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> 
> 2024-10-01T07:53:26.368Z: Port 9292 is free
> 2024-10-01T07:53:26.376Z: Reading the content of file at shopify/assets/FreigeistXConBlack.woff...
> 2024-10-01T07:53:26.377Z: Reading the content of file at shopify/assets/FreigeistXConBlack.woff2...
> 
> [...] # redacted
>
> 2024-10-01T07:53:26.461Z: Request to https://SHOPURL.myshopify.com/ completed in 103 ms
> With response headers:
>  - content-type: text/html; charset=utf-8
>  - server-timing: processing;dur=12, db;dur=3, asn;desc="8412", edge;desc="VIE", country;desc="AT", theme;desc="164683022664", pageType;desc="index", servedBy;desc="n8qf", requestID;desc="a0fda630-980b-4622-aff6-d6ea754fa9b9-1727769206", cfRequestDuration;dur=59.999704, ipv6
>  - x-request-id: a0fda630-980b-4622-aff6-d6ea754fa9b9-1727769206
> 
> 2024-10-01T07:53:26.461Z: Getting storefront password for shop SHOPURL.myshopify.com...
> 2024-10-01T07:53:26.524Z: Request to https://SHOPURL.myshopify.com/password completed in 63 ms
> With response headers:
>  - content-type: text/html; charset=utf-8
>  - server-timing: processing;dur=12, db;dur=2, asn;desc="8412", edge;desc="VIE", country;desc="AT", pageType;desc="password", servedBy;desc="pj8l", requestID;desc="fdef25f6-4f10-4df6-ac6d-7646ed0f9a69-1727769206", cfRequestDuration;dur=49.999952, ipv6
>  - x-request-id: fdef25f6-4f10-4df6-ac6d-7646ed0f9a69-1727769206
> 
> 2024-10-01T07:53:26.525Z: Setting storefront password for shop SHOPURL.myshopify.com...
> 2024-10-01T07:53:26.529Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
> []
> 
> 2024-10-01T07:53:26.530Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store SHOPURL.myshopify.com:
> []
> 
> 2024-10-01T07:53:26.530Z: Getting session store...
> 2024-10-01T07:53:26.530Z: Validating existing session against the scopes:
> [
>   "openid",
>   "https://api.shopify.com/auth/shop.admin.graphql",
>   "https://api.shopify.com/auth/shop.admin.themes",
>   "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
>   "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
>   "https://api.shopify.com/auth/partners.app.cli.access",
>   "https://api.shopify.com/auth/destinations.readonly"
> ]
> For applications:
> {
>   "adminApi": {
>     "scopes": [],
>     "storeFqdn": "SHOPURL.myshopify.com"
>   }
> }
> 
> 2024-10-01T07:53:26.530Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
> 2024-10-01T07:53:26.530Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:26.754Z: Request to https://accounts.shopify.com/oauth/introspection completed in 224 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"db9a758dfdb3352e46697a1dab4b2c06"
>  - server-timing: processing;dur=30, socket_queue;dur=1.312, edge;dur=1.02, util;dur=0.0, cfRequestDuration;dur=168.999910
>  - x-request-id: ae1b5b27-1391-437b-94ff-4d6bc2963f8b-1727769206
> 
> 2024-10-01T07:53:26.754Z: The identity token is valid: true
> 2024-10-01T07:53:26.755Z:
> The validation of the token for application/identity completed with the following results:
> - It's expired: false
> - It's invalid in identity: false
> 
> 2024-10-01T07:53:26.755Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
> []
> 
> 2024-10-01T07:53:26.755Z: Getting session store...
> 2024-10-01T07:53:26.763Z: Validating existing session against the scopes:
> [
>   "openid",
>   "https://api.shopify.com/auth/shop.admin.graphql",
>   "https://api.shopify.com/auth/shop.admin.themes",
>   "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
>   "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
>   "https://api.shopify.com/auth/partners.app.cli.access",
>   "https://api.shopify.com/auth/destinations.readonly"
> ]
> For applications:
> {
>   "storefrontRendererApi": {
>     "scopes": []
>   }
> }
> 
> 2024-10-01T07:53:26.763Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
> 2024-10-01T07:53:26.763Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
> With request headers:
>  - User-Agent: Shopify CLI; v=3.67.3
>  - Keep-Alive: timeout=30
>  - Sec-CH-UA-PLATFORM: darwin
>  - Content-Type: application/json
> 
> 2024-10-01T07:53:27.035Z: Request to https://accounts.shopify.com/oauth/introspection completed in 272 ms
> With response headers:
>  - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
>  - content-type: application/json; charset=utf-8
>  - etag: W/"db9a758dfdb3352e46697a1dab4b2c06"
>  - server-timing: processing;dur=37, socket_queue;dur=1.786, edge;dur=1.016, util;dur=0.05, cfRequestDuration;dur=175.999880
>  - x-request-id: e14e2408-e18b-4c69-8fb7-9b549342be36-1727769206
> 
> 2024-10-01T07:53:27.037Z: The identity token is valid: true
> 2024-10-01T07:53:27.037Z:
> The validation of the token for application/identity completed with the following results:
> - It's expired: false
> - It's invalid in identity: false
> 
> 2024-10-01T07:53:27.108Z: Request to https://SHOPURL.myshopify.com/?preview_theme_id=165427315016&_fd=0&pb=0 completed in 71 ms
> With response headers:
>  - content-type: text/html; charset=utf-8
>  - server-timing: processing;dur=18;desc="gc:1", db;dur=4, asn;desc="8412", edge;desc="VIE", country;desc="AT", theme;desc="165427315016", pageType;desc="index", servedBy;desc="g44c", requestID;desc="0dd0d955-f074-4c6c-94f4-40fbec2903fd-1727769207", cfRequestDuration;dur=55.000067, ipv6
>  - x-request-id: 0dd0d955-f074-4c6c-94f4-40fbec2903fd-1727769207
> 
> 2024-10-01T07:53:27.225Z: Request to https://SHOPURL.myshopify.com/password completed in 117 ms
> With response headers:
>  - content-type: text/html; charset=utf-8
>  - server-timing: processing;dur=13;desc="gc:1", db;dur=4, asn;desc="8412", edge;desc="VIE", country;desc="AT", pageType;desc="password", servedBy;desc="hxrz", requestID;desc="16c07c87-6e8b-46f3-8387-8e7e904d4e2a-1727769207", cfRequestDuration;dur=52.999973, ipv6
>  - x-request-id: 16c07c87-6e8b-46f3-8387-8e7e904d4e2a-1727769207
> 
> ╭─ error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
> │                                                                                                                                   │
> │  Your development session could not be created because the store password is invalid. Please, retry with a different password.    │
> │                                                                                                                                   │
> ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> 
> 2024-10-01T07:53:27.237Z:
> Running system process:
>   · Command: npm prefix
>   · Working directory: /Users/PERSONALNAME/Code/SHOPURL-shopify-shop
> 
> 2024-10-01T07:53:27.489Z: Obtaining the dependency manager in directory /Users/PERSONALNAME/Code/SHOPURL-shopify-shop...
> 2024-10-01T07:53:27.671Z:
> Running system process:
>   · Command: ruby -v
>   · Working directory: /Users/PERSONALNAME/Code/SHOPURL-shopify-shop
> 
> 2024-10-01T07:53:27.934Z: Request to https://monorail-edge.shopifysvc.com/v1/produce completed in 242 ms
> With response headers:
>  - x-request-id: 60ac9e36-c1ad-4d42-bbad-d0ca9b921ad1
> 
> 2024-10-01T07:53:27.935Z: Analytics event sent: {
>   "command": "theme dev",
>   "time_start": 1727769204974,
>   "time_end": 1727769207232,
>   "total_time": 2258,
>   "success": false,
>   "cli_version": "3.67.3",
>   "ruby_version": "3.0.0",
>   "node_version": "20.11.1",
>   "is_employee": false,
>   "uname": "darwin arm64",
>   "env_ci": false,
>   "env_plugin_installed_any_custom": false,
>   "env_plugin_installed_shopify": "[\"@shopify/cli\"]",
>   "env_shell": "zsh",
>   "env_device_id": "6b993e86433324e779d123961dbf0510687e916a",
>   "env_cloud": "localhost",
>   "env_package_manager": "yarn",
>   "env_is_global": true,
>   "cmd_app_warning_api_key_deprecation_displayed": false,
>   "cmd_all_timing_network_ms": 2174,
>   "cmd_all_timing_prompts_ms": 0,
>   "cmd_all_launcher": "unknown",
>   "cmd_all_topic": "theme",
>   "cmd_all_plugin": "@shopify/theme",
>   "cmd_all_force": false,
>   "cmd_all_verbose": true,
>   "cmd_all_path_override": true,
>   "cmd_all_path_override_hash": "f2682469e7a7aab4279b1a3e4aa55b594d034fae",
>   "cmd_all_timing_active_ms": 83,
>   "cmd_all_exit": "expected_error",
>   "args": "--store=SHOPURL.myshopify.com --theme-editor-sync --path=./shopify --verbose",
>   "error_message": "Your development session could not be created because the store password is invalid. Please, retry with a different password.",
>   "env_plugin_installed_all": "[\"@shopify/cli\"]",
>   "metadata": "{\"extraPublic\":{},\"extraSensitive\":{}}"
> }
> 2024-10-01T07:53:27.958Z: Reporting handled error to Bugsnag: Your development session could not be created because the store password is invalid. Please, retry with a different password.
> 2024-10-01T07:53:28.313Z:
> Running system process:
>   · Command: npm prefix
>   · Working directory: /Users/PERSONALNAME/Code/SHOPURL-shopify-shop
> 
> 2024-10-01T07:53:28.493Z: Obtaining the dependency manager in directory /Users/PERSONALNAME/Code/SHOPURL-shopify-shop...
> ╭─ error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
> │                                                                                                                                   │
> │                                                                                                                                   │
> │  To investigate the issue, examine this stack trace:                                                                              │
> │    at internalConnectMultiple (node:net:1114)                                                                                     │
> │    at afterConnectMultiple (node:net:1667)                                                                                        │
> │                                                                                                                                   │
> ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> 
> 2024-10-01T07:53:28.536Z: Reporting unhandled error to Bugsnag:
> 2024-10-01T07:53:28.540Z:
> Running system process:
>   · Command: npm prefix
>   · Working directory: /Users/PERSONALNAME/Code/SHOPURL-shopify-shop
> 
> 2024-10-01T07:53:28.725Z: Obtaining the dependency manager in directory /Users/PERSONALNAME/Code/SHOPURL-shopify-shop...
> AggregateError
>     at internalConnectMultiple (node:net:1114:18)
>     at afterConnectMultiple (node:net:1667:5)
> %
> 
> </pre>
> </details> 
> 
> 
> 
>

**Comment by jamesmengo** [comment]
https://github.com/Shopify/cli/issues/4737

**Comment by jamesmengo** [comment]
@Maybach91 @porobicgroup 

I've been unable to replicate this so far. Can you confirm whether you're still experiencing this issue on `3.69`+?
If so, could you please fill out a new [bug report](https://github.com/Shopify/cli/issues/new?template=bug-report.yml) and complete the requested information? 

Thanks :)
