### ISSUE TITLE
[Bug]: Theme Check - locale keys with _html and pluralisation.

### ISSUE THREAD

**Issue by pocallaghan-function** [Shopify/cli#4589]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

It should be possible to use pluralisation with html keys without a `ValidJSON` error getting triggered. 

### Actual behavior

A `ValidJSON` error is triggered. 

### Verbose output

info ─────────────────────────────────────────────────────────────────────────

locales/en.default.json

[error]: ValidJSON
Incorrect type. Expected "string".

208      "count_html": {
209        "one": "There is <span class=\"count\">{{ count }}</span> item",
210        "other": "There are <span class=\"count\">{{ count }}</span> items"
211      }

### Reproduction steps

1. Add this to your locales file:
```json
  "example": {
    "count_html": {
      "one": "There is <span class=\"count\">{{ count }}</span> item",
      "other": "There are <span class=\"count\">{{ count }}</span> items"
    }
  },
```
2. Add this to your liquid file:
```liquid
      {{ 'example.count_html' | t: count: 1 }}<br/>
      {{ 'example.count_html' | t: count: 2 }}<br/>
```
3. Run `shopify theme check`

The file is reported as invalid, however if you preview the theme the pluralisation clearly works. 

### Operating System

Mac OS Sonoma

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.68.0

### Shell

zsh

**Comment by mgmanzella** [comment]
👋 thanks for reporting, to confirm is this the same issue you're facing? https://github.com/Shopify/theme-liquid-docs/issues/798

**Comment by mgmanzella** [comment]
np! im closing as duplicate
