### ISSUE TITLE
[Bug]: Theme assets `/assets/*` returns 404

### ISSUE THREAD

**Issue by wiebekaai** [Shopify/cli#4607]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

We use Vite to serve assets in development and when an asset is referenced (such as `url('Inter-Regular.woff2')` in CSS), we proxy the `http://localhost:5173/Inter-Regular.woff2` request to `http://127.0.0.1:9292/assets/Inter-Regular.woff2`. With `--legacy` enabled these return the files.

### Actual behavior

Returns a 404.

### Verbose output

GET /assets/Inter-Regular.woff2
2024-10-09T08:31:02.851Z: → Rendering https://[...].com/assets/Inter-Regular.woff2?_fd=0&pb=0 (with )...
2024-10-09T08:31:03.148Z: Request to https://[...].com/assets/Inter-Regular.woff2?_fd=0&pb=0 completed in 297 ms
With response headers:
 - cache-control: no-cache, no-store
 - content-type: font/woff2; charset=utf-8
 - server-timing: processing;dur=83;desc="gc:49", db;dur=10, parse;dur=1, render;dur=5, asn;desc="50266", edge;desc="AMS", country;desc="NL", theme;desc="142490042499", pageType;desc="404", servedBy;desc="hq2k", requestID;desc="f4ee6045-cc21-4f63-891c-e17ddefa5ed1-1728462662", cfRequestDuration;dur=262.999773
 - x-request-id: f4ee6045-cc21-4f63-891c-e17ddefa5ed1-1728462662
    
2024-10-09T08:31:03.149Z: ← 404 (request_id: f4ee6045-cc21-4f63-891c-e17ddefa5ed1-1728462662)

### Reproduction steps

1. Add an asset to the `assets/` directory
2. Start `shopify theme dev`
3. Visit the asset, for example `http://127.0.0.1:9292/assets/Inter-Regular.woff2`

### Operating System

MacOS 14.6.1 (23G93)

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.68.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v22.6.0

**Comment by mgmanzella** [comment]
👋 thanks for reporting! i can reproduce this issue, it seems to be an unsupported feature in the new typescript only implementation of the dev server. please use the `--legacy` flag while we fix this. thanks again 🙏
