### ISSUE TITLE
Stability of releases & Beta channel

### ISSUE THREAD

**Issue by gbcatrinoiu** [Shopify/cli#4632]
Hey everyone,

First of all, thank you for always being quick to release fixes! However, there’s a concern many of us frontend developers working in e-commerce agencies have been discussing over the past few weeks, if not months.

Unfortunately, the quality of recent releases seems to have declined, causing significant issues in production stores and, perhaps even more critically, impacting the theme development process. We’ve encountered instances where the tool breaks down every few minutes, JSON templates are lost or overwritten, sometimes unrelated errors to the actual cause, and the issues only get resolved through hotfix releases (which we appreciate, by the way!).

Since this is the only tool available for developing and deploying themes, it’s essential to have a stable version that functions reliably. Would it be possible to establish a beta channel where new features can be pre-released and tested? I’d be more than happy to use the beta channel as my primary option but still have the ability to switch to a stable version in the event of a major bug.

Looking forward to hearing your thoughts on this. Thanks!

**Comment by lesterdefreitas** [comment]
Seconded! Thanks @gbcatrinoiu for proposing this.

**Comment by rcasimmons** [comment]
@karreiro

What about if we opened up the platform for third-party tools so developers have more choice on the amount of tools?

I get a first-party tool is the best case scenario but having more tools to interact with themes etc. would be much better in cases where developers can't use the first-party option.

I'm still on the opinion that we should have stable, beta and alpha channels - something that's industry standard usually.

It just doesn't strike confidence that we as developers have to report these issues in an already closed ecosystem.

**Comment by karreiro** [comment]
Thanks again for these comments, @gbcatrinoiu @rcasimmons!

We've been heavily relying on the use of snapshots [[1]](https://github.com/Shopify/cli/issues/4737#issuecomment-2457609443) [[2]](https://github.com/Shopify/cli/issues/4733#issuecomment-2472916383) [[3]](https://github.com/Shopify/cli/issues/4644#issuecomment-2416310070) as a strategy to shorten the feedback loop with CLI users and have more stable releases.

In the future, when larger changes are introduced, we're going to establish a temporary Beta channel, so we can globally validate and test the new implementation with CLI users. It should be similar to the one we did with the [dev preview](https://shopify.dev/docs/storefronts/themes/tools/cli/cli-3-67/dev-preview); however, we're going to invest even more in communication, so we can engage more developers there (we understand it wasn't the case in the case in the 3.67 release).

I'm closing this issue for now. Also, I'd like to publicly thank you, @isaacroldan, for adding the `/snapit` into the repository -- as I mentioned, that was instrumental in shortening our feedback loop with theme developers.
