### ISSUE TITLE
[Feature request / Bug?] Log in into Shopify (partner page / shops / ...) without a browser

### ISSUE THREAD

**Issue by ascheucher-shopify-partner** [Shopify/cli#4682]
## Please confirm that you have:

- [x] Searched [existing issues](https://github.com/Shopify/cli/issues/) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)

- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

## In which of these areas are you experiencing a problem?

As I try to set up a Visual Studio Code Remote Devcontainer over a tunnel, the Shopify CLI breaks as it tries to log in.

`shopify app init` & `shopify app dev` can not be run without having a browser on the system, as the login flow needs to open a URL.

Reasons for developing in a remote container:

* having a well-defined environment separated from other projects (node version, shopify cli version, own db and db version for each project, ...)
* having a cheap powerful development host (either in the office, in the cloud) and use a "normal" laptop as terminal.
* ...

Introduction Documentation:
* [Developing inside a Container](https://code.visualstudio.com/docs/devcontainers/containers)
* [Develop on a remote Docker host](https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host)
* [Developing over a tunnel](https://code.visualstudio.com/docs/remote/tunnels)

## Expected behavior

The expected behavior described, is just a hypothetical suggestion, how the problem might be solved.

Running `shopify app init --remote-login` & `shopify app dev --remote-login` in the VSC terminal over a tunnel on a remote machine, just shows a URL to be copy & pasted into a browser on the local host.

The login success confirmation screen shows a token/code to be copy & pasted into the terminal to confirm the login.
From now on, the app has access to the partner account and dev shops.

## Actual behavior

After creation of the VSC devcontainer docker-compose setup on the remote host with Node & PostgreSQL support, starting them and executing following:

```bash
node ➜ /workspaces/javascript-node-postgres (main) $ shopify app init

Welcome. Let's get started by linking this new project to an app in your organization.


To run this command, log in to Shopify.
User verification code: MVPS-PPQF
👉 Press any key to open the login page on your browser
Opened link to start the auth process: https://accounts.shopify.com/activate-with-code?device_code%5Buser_code%5D=MVPS-PPQF
Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
node ➜ /workspaces/javascript-node-postgres (main) $ 
```

The reason for the exception is the missing browser on the remote host (Ubuntu / Docker container).

## Reproduction steps

If a change or an additional way of logging in is considered, I am more than happy to supply a configuration to be run as docker-compose setup on a remote host.

**Comment by isaacroldan** [comment]
Hi @ascheucher-shopify-partner, the current auth flow should actually work without a local browser.
You should be able to copy the URL after `Opened link to start the auth process: ...` and open it in a different machine with a browser.

I understand that in your case is crashing trying to open the URL before you can copy it manually? We'll review this to fix it.

**Comment by samherrmann** [comment]
> You can force the CLI to not try to automatically open the URL by using the env var CODESPACES=1

This worked beautifully!  

@gonzaloriestra, is this documented anywhere? Maybe it could be included [here](https://shopify.dev/docs/api/shopify-cli/app/app-init)?
