### ISSUE TITLE
[Bug]: Cart AJAX API returning 404

### ISSUE THREAD

**Issue by nboliver-ventureweb** [Shopify/cli#4690]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The AJAX API endpoints `cart/add.js` and `cart/update.js` should the dev theme preview available at http://127.0.0.1:9292 

### Actual behavior

The AJAX API endpoints `cart/add.js` and `cart/update.js` are returning 404s when using the dev theme preview at http://127.0.0.1:9292
CLI version 3.66.1 seems to work, but 3.67.1 and 3.68.1 do not. 
Using the `--legacy` flag does not fix the issue. 

Request: 
![Image](https://github.com/user-attachments/assets/d16c65a5-3e3e-4c46-bfea-a9e961816dc6)

http://127.0.0.1:9292 Response: 
![Image](https://github.com/user-attachments/assets/c22f65ed-593e-4493-b1f6-a97abf5f501e)

Same request, same theme, but using the myshopify.com URL:
![Image](https://github.com/user-attachments/assets/18a0fa27-b314-43a5-abf3-7242f09150a7)

### Verbose output

Can be shared via DM

### Reproduction steps

1. Run `npm exec --package @shopify/cli@3.68.1 -- shopify theme dev --live-reload full-page` (or try v3.67.1). Note that we are currently using `npm exec` because we rely on Shopkeeper, which was broken by CLI versions > 3.58, but the `theme dev` command is broken in that version. See https://github.com/Shopify/cli/pull/4469
2. Visit http://127.0.0.1:9292 in browser
3. Try to add or update via AJAX API
4. Get a 404 response

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.68.1

### Node version (run `node -v` if you're not sure)

v22.3.0

**Comment by cesarho** [comment]
@nboliver-ventureweb  

Check if it is because the variant ID exists in your testing store. 
The `update.js` api returns a 404 error if the provided variant ID does not exist.

![Image](https://github.com/user-attachments/assets/661049a5-2706-4d97-bdf1-7ab9e467ef98)

**Comment by nboliver-ventureweb** [comment]
This seems to be resolved now, will reopen if it pops up again.
