### ISSUE TITLE
[Bug]:  Theme ID mismatch

### ISSUE THREAD

**Issue by ryan-pt** [Shopify/cli#4693]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

`shopify theme dev` should be working as always

### Actual behavior

`shopify theme dev` shuts down with error "theme id mismatch"

### Verbose output

2024-10-21T06:23:17.667Z: ← 200 (request_id: bc2ea026-2051-4416-854b-874115b76af4-1729491797)
╭─ error ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                             │
│  Theme ID mismatch: expected ***5530 but got ***2490.                                                                                             │
│  Request ID: bc2ea026-2051-4416-854b-874115b76af4-1729491797                                                                                                │
│  URL: https://www.meatkrafters.sg/account/login?return_url=%2Faccount%3F_fd%3D0%26pb%3D0                                                                    │
│                                                                                                                                                             │
│  This is likely related to an issue in upstream Shopify APIs.                                                                                               │
│  Please try again in a few minutes and report this issue:

### Reproduction steps

1.
2.
3.

### Operating System

Win 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.68.1

### Shell

git bash

### Node version (run `node -v` if you're not sure)

20.12.2

**Comment by karreiro** [comment]
Thank you for reporting this, @ryan-pt. I'm closing this issue in favor of https://github.com/shopify/cli/issues/4634. You may follow the progress of this fix there.
