### ISSUE TITLE
CLI should not clobber config files

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/cli#4703]
After running `shopify app deploy` (which failed because of #4702) I noticed that my `shopify.app.toml` file had been clobbered. I had added some comments in the file to help myself keep track of some things I needed to address and those comments are now gone. The file itself was also restructured to move things around, seemingly to have them in the "correct" order. This feels pretty hostile.

**Comment by gonzaloriestra** [comment]
Hi! Thanks for the suggestion. This is similar to https://github.com/Shopify/cli/issues/4249, so I'm closing here.
