### ISSUE TITLE
[Bug]: CI workflows that rely on Shopify CLI are broken on 3.69.0 (Authorization is required to continue)

### ISSUE THREAD

**Issue by darrynten** [Shopify/cli#4712]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

The `shopify app build` command should work as expected.

### Actual behavior

The `shopify app build` command has started throwing the following error on 3.69.0

```
To run this command, log in to shopify.

Authorization is required to continue, but the current environment does not support interactive prompts.

To resolve this, specify credentials in your environment, or run the command in an interactive environment such as yo
```

This has resulted in broken deployment pipelines.

Rolling back to 3.68.0 resolves the problem.

The closest reference I could find was [this](https://github.com/Shopify/cli/pull/4700/files#diff-df34da71cd0cfa2af821f64c530056155f86fb268a2a4b2539cbc9d044af2116R9)

Can we please get some insight into how to migrate CLI authorization from 3.69.0 onwards for CI environments to continue building and deploying as expected?

### Verbose output

To run this command, log in to shopify.

Authorization is required to continue, but the current environment does not support interactive prompts.

To resolve this, specify credentials in your environment, or run the command in an interactive environment such as yo

### Reproduction steps

1. Have hosted CI solution working on 3.68.0
2. npm update to 3.69.0
3. Broken deploys

### Operating System

Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.69.0

### Shell

bash

**Comment by Visylvius** [comment]
Same issue. I posted my logs [here](https://github.com/Shopify/cli/issues/4708)

**Comment by stevomccormack** [comment]
Same issue. When working locally and assume CI/CD is same.

**Comment by yangli1r** [comment]
Anyone know if 3.69.2 fixed this problem ?

**Comment by isaacroldan** [comment]
Hi everyone, all app commands require authentication now. (almost all commands required it already before this version, but now is all commands).

You just need to provide a token in your CI to handle authentication, here is the documentation for it: https://shopify.dev/docs/apps/launch/deployment/deploy-in-ci-cd-pipeline 
See step 2 (`Generate a CLI authentication token`) and usages of `SHOPIFY_CLI_PARTNERS_TOKEN`

**Comment by darrynten** [comment]
@isaacroldan I don't want to run `shopify app deploy` I want to run `shopify app build` in a github workflow and I'm not super excited about giving github workflows access to our partner account

**Comment by isaacroldan** [comment]
@darrynten I understand your concerns, we appreciate the feedback, i'll be sure to pass it internally to take it into consideration for future updates of the CLI. For now I'm afraid all commands require authentication.

@supa-freak If you see the prompt to select/create an app is probably because your `app.toml` doesn't have a client-id or you need to provide one via flag (`--client-id`). If you were using the `--api-key` flag, I just noticed there is a bug in that command and that flag won't work, you should use `--client-id`. If this doesn't work, please open a new issue 🙏

**Comment by isaacroldan** [comment]
The suggested fix would be to use the latest version and provide the necessary token to run your commands in CI.
In the meantime we are reevaluating if auth will be needed for all commands in a future update.

**Comment by taixes** [comment]
+1 reverting and waiting for a fix. I'm not gonna load sensitive data to run just a build

**Comment by alexissel** [comment]
How can we pass the SHOPIFY_CLI_PARTNERS_TOKEN if we just want to simply build/ and run the app without any CI/CD pipeline?

**Comment by isaacroldan** [comment]
Hi everyone, in case you missed the changelog for the latest releases, authentication is no longer required for `app build`.
I'd recommend upgrading to the latest version (and try to stay always on latest if possible).

Thanks for the feedback and sorry it took this long to fix this.
