### ISSUE TITLE
[Feature]: Shopify Theme Dev Shortcuts

### ISSUE THREAD

**Issue by ceri-waterscreative** [Shopify/cli#4713]
### What area(s) will this request affect?

Theme, Running your code locally

### What type of change do you want to see?

New feature

### Overview

You know how `shopify app dev` has shortcut commands like `p` for 'preview' in your browser'?

Could we get these for `shopify theme dev` too?

I'm thinking we need shortcuts for...
Launch localhost in browser (d?)
Launch preview in browser (p?)
Launch editor in browser (e?)

### Motivation

The number of times i accidently close my preview or later need the editor and have to scroll back (past the many many logs) to find it is saddening..

**Comment by nbsimmons** [comment]
I agree with this, especially when using `--verbose` - only so much history is retained.

Trying to get the customizer link can be frustrating.
