### ISSUE TITLE
[Bug]: CLI 'theme dev' command will not accept store password

### ISSUE THREAD

**Issue by rtnate** [Shopify/cli#4733]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The 'theme dev' command prompts for my store password.  I enter the store password as set in store > preferences.  This password successfully access the store in a web browser.  Expect to be able to launch the local development server to develop a theme by editing the theme files.

### Actual behavior

The 'theme dev' command prompts for my store password.  I enter the store password as set in store > preferences.  This password successfully access the store in a web browser.  However the CLI keeps saying Incorrect Store Password.

### Verbose output

shopify theme dev
?  Enter your store password ( 
   https://RtExDev.myshopify.com/admin/online_store/preferences ):
✔  ************

?  Incorrect store password ( 
   https://RtExDev.myshopify.com/admin/online_store/preferences ). Please try
   again:
>  █
   ▔▔▔▔▔▔▔▔

### Reproduction steps

1. Run shopify theme init to create a development theme environment 
2. Run shopify theme dev --store RtExDev
3. Redirect to web browser and successfully authenticate my user account
4. Enter my store password

### Operating System

Windows 11 and replicated with WSL/Ubunutu 22.04.3

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.69.2

### Shell

Replicated with Powershell and WSL/Bash

### Node version (run `node -v` if you're not sure)

v20.18.0

**Comment by jamesmengo** [comment]
Hey @rtnate!

I was unable to reproduce this issue locally.
Could you try a previous version (`3.69.0` and let me know if that works?)

If you could also share the full verbose log output, that may be useful in helping us debug this.

Thanks!

**Comment by rtnate** [comment]
Issue persists back to 3.67.0.  Attempting to run shopify theme dev --legacy on 3.67.0 under WSL but have yet to resolve dependency issues

**Comment by rtnate** [comment]
Re-confirmed 3.67.0 presents the same issue.  3.66.0 requires ruby, which my windows environment is not setup for and WSL is presenting issues.  I will work on getting 3.66.0/legacy versions with ruby sorted tomorrow and report back.  I am using ascii-only passwords and have had issues with multiple shells but I can investigate further tomorrow.  3.69.0 didn't work in Win 11 powershell, git bash, WSL/ubuntu bash and my Mint Linux vm as my first guess was shell encoding issues.

**Comment by frandiox** [comment]
@rtnate Can you try [this CLI version](https://github.com/Shopify/cli/pull/4832#issuecomment-2469806585)? It should print the password you are typing and the URL it tries to call. Let me know if it matches what you type in the prompt (no need to write your pass here ofc).

Also, can you try passing `--store-password ...` flag and see if that changes anything?

**Comment by frandiox** [comment]
>What is the CLI attempting to do here?

It's trying to verify your password to use it later in requests to your store, but it seems it can't verify it 🤔 

---

@karreiro do you perhaps know more about development stores? It seems we are sending the correct password to the API but we get a mismatch.

**Comment by rtnate** [comment]
Looks like the API is returning the password page as text/html from what I can tell.  I'm guessing the CLI does not expect a text/html response?

**Comment by MustagheesButt** [comment]
> Could you please try this snapshot?
> 
> pnpm i -g @shopify/cli@0.0.0-snapshot-20241113075607
> 

Yes fixed for me. thanks
