### ISSUE TITLE
Shopify CLI 3.X ngrok tunnel issue

### ISSUE THREAD

**Issue by varun-etraffic** [Shopify/cli#475]
Hello,
I was creating an app using Shopify CLI 3.X

Everything was working fine from the past two when I run the npm run dev command in the Command Prompt, I get this tunnel URL ([Attachment_1](https://prnt.sc/WWzZM7-g2DrR)) and when I visit this URL I get this ([Attachment_2](https://prnt.sc/8AzJMXwtx54m))

I tried to create new apps too and faced the same issue can anyone please help me to remove this issue.

**Comment by gonzaloriestra** [comment]
Hi! It may be a problem with Ngrok. I'd recommend trying with a Cloudflare tunnel:
- Install cloudflared: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/installation/
- `cloudflared tunnel --url http://localhost:3000`
- `shopify app dev --tunnel-url https://generated-url-by-cloudflare.trycloudflare.com:3000`

More info:
- [Cloudflare Quick Tunnels](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/do-more-with-tunnels/trycloudflare/)
- [tunnel-url flag](https://shopify.dev/apps/tools/cli/commands#flags)

I'm closing, let me know if it doesn't work.

**Comment by varun-etraffic** [comment]
I will try it thanks for the suggestion.

**Comment by varun-etraffic** [comment]
Hey I tried the cloudflare tunnel and it didn't work either ([Attachment_1](https://prnt.sc/NBS1Ktek6DO-))

Please let me know if I am doing something wrong

**Comment by gonzaloriestra** [comment]
As explained [here](https://shopify.dev/apps/tools/cli/commands#command-syntax), some package managers require a separator to pass flags to the script. Also, the port is missing.

So with npm you should run: `npm run shopify app dev -- --tunnel-url https://quotes-jackie-annotation-woman.trycloudflare.com:3000`

**Comment by gonzaloriestra** [comment]
I don't know... Ngrok is a 3rd party provider, and we know that they sometimes block accounts or IPs for different reasons, although it should return a different error. That's why I was suggesting to try with another tunnel provider.

Anyway, next week we will remove the need of tunnels in some cases and we are working on simplifying the use of other alternatives.

**Comment by varun-etraffic** [comment]
Ok, I will try to use the cloudflared again. Hope it will work out this time
