### ISSUE TITLE
[Bug]: Cloudflare url gives 502 bad getway when running local enviroment

### ISSUE THREAD

**Issue by AlonJoshua** [Shopify/cli#4756]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

npm run dev command creates an active Cloudflare URL

### Actual behavior

Cloudflare URL is returning 502 for preview in the browser and HTTP requests for the URL.

![Image](https://github.com/user-attachments/assets/c0f7303c-c347-4bb4-b14d-e56ba664ba83)

The rest of the app runs smoothly (Extensions work and get updated).

This could be a Cloudflare issue or CLI bug, but it keeps happening for several days, and a few colleagues of mine experience this.

### Verbose output

The local enviroment runs smoothly, so no verbose output as it's just too detailed and I couldn't catch it all.

### Reproduction steps

1. Run "npm run dev"
2. Press P for preview in your browser

### Operating System

MAC

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.69.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v20.14.0

### What language and version are you using in your application?

Node v20.14.0

**Comment by gonzaloriestra** [comment]
Hi!

I'm sorry you are facing issues with Cloudflare. It could be a temporary problem, or maybe related to your region or IPs.

As a workaround, you can manually create a tunnel with another provider and pass the URL. For example, with Ngrok:
- Install Ngrok from https://ngrok.com/download
- Run `ngrok http 3000` from the terminal and copy the generated URL for the next step
- `shopify app dev --tunnel-url https://generated-url.ngrok.com:3000`

**Comment by Alonboa** [comment]
@gonzaloriestra Thanks for the help.

Ngrok in this case gives me ERR_NGROK_3004

![Image](https://github.com/user-attachments/assets/748fdffb-532f-4e65-876f-eb9987148800)

I guess that it's because the local host port changes dynamically at the start of each application.

![Image](https://github.com/user-attachments/assets/acebb851-41f7-4e0a-8d86-25466f1903a5)

Is there a way to configure a static port?
