### ISSUE TITLE
[Bug]: Check Ruby support before creating theme app extension

### ISSUE THREAD

**Issue by byrichardpowell** [Shopify/cli#4783]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

When creating a theme extension the version of Ruby should be checked.  If the correct version is not present, the theme extension should not be created.

### Actual behavior

Creating a theme extension with an incompatible version of Ruby will succeed.  

Note: The ruby version is only checked when running `shopify app dev`.  It should be checked earlier so we don't generate files which won't be supported.

### Verbose output

NA

### Reproduction steps

1.  Setup your system with a version of Ruby that is not supported by theme extensions
2. `shopify app generate extension` 
3. Select a theme extension
4. The command will succeed.  It should fail.

### Operating System

Mac OS 

### Shopify CLI version (check your project's `package.json` if you're not sure)

Any

**Comment by amcaplan** [comment]
@byrichardpowell does this issue make sense if we've just removed Ruby from the CLI (to be applied in 3.70)?
