### ISSUE TITLE
[Bug]: JSON templates are unformatted

### ISSUE THREAD

**Issue by JasonHassold** [Shopify/cli#4851]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

JSON template files and settings_data.json file should be formatted correctly.

### Actual behavior

I just upgraded to Shopify CLI version 3.70.0 and started working on a theme using `shopify theme dev --theme-editor-sync` and the templates I save in the theme editor are pulling in unformatted in 1 line with no new lines or indentation. I looked in the theme code editor on shopify and the files look correctly formatted there.

### Verbose output

```shell
N/A
```

### Reproduction steps

1. `shopify theme dev --theme-editor-sync`
2. Open the theme editor and save changes to a template
3. Look at that template locally after it pulls in

### Operating System

Ubuntu 20.04.6 LTS on WLS 2 on Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.70.0

**Comment by JasonHassold** [comment]
I don't think this issue is specific to the `--theme-editor-sync` flag, but that is what I was using

**Comment by max-techyscouts** [comment]
Only `settings_data.json` is minified for me.
When I run `shopify theme pull -d`, the `settings_data.json` is not minified but when use `shopify theme dev --theme-editor-sync`, it is minified.

**Comment by mgmanzella** [comment]
thanks for reporting folks! we have a fix in progress, will let you know when it's live

**Comment by lesterdefreitas** [comment]
@mgmanzella I'm not on slack, can you please enable the fix for me somehow? Problem is I am working on tons of stores. Must I list each one for you?

Or, is there an easy way for me to roll back to an earlier cli version to avoid this?

**Comment by mgmanzella** [comment]
@lesterdefreitas we're working on getting this fix out again asap, this is purely to hold you over so you don't lose your diffs. @alexggmark workaround sounds like a good option if youre not on the partners slack

**Comment by lesterdefreitas** [comment]
@alexggmark thanks for taking the time to share your workaround btw. 🙏🏻

**Comment by karreiro** [comment]
Thank you for working on that fix, @AaronBarcos!

👋 Hey @ethancalvo,

You may try the fix that @AaronBarcos built on this snapshot:

```bash
pnpm i -g @shopify/cli@0.0.0-snapshot-20231127081555
```

Could you please confirm if that fixes the issue for you?

**Comment by JasonHassold** [comment]
@mgmanzella @lukeh-shopify I just tried upgraded back to latest version v3.70.0, but have been having this error pretty much constantly now. I was not experiencing this before when I originally upgraded to v3.70.0 and was having the formatting issue. Maybe something else on the platform site was changed or maybe the fix for the formatting issue has caused this.

![Image](https://github.com/user-attachments/assets/20c89eca-efa6-4a83-bcab-e2bc30ac55ef)

**Comment by lukeh-shopify** [comment]
> [@mgmanzella](https://github.com/mgmanzella) [@lukeh-shopify](https://github.com/lukeh-shopify) I just tried upgraded back to latest version v3.70.0, but have been having this error pretty much constantly now. I was not experiencing this before when I originally upgraded to v3.70.0 and was having the formatting issue. Maybe something else on the platform site was changed or maybe the fix for the formatting issue has caused this.
> 
> ![Image](https://github.com/user-attachments/assets/20c89eca-efa6-4a83-bcab-e2bc30ac55ef)

@JasonHassold this looks like a similar to a [known issue](https://github.com/Shopify/cli/issues/4897) that we're working on a fix for ASAP. Could you please post your verbose logs/reproduction steps in that issue? Sorry this happened to you, it must be frustrating
