### ISSUE TITLE
[Bug]: Not able to connect to CLI as store owner

### ISSUE THREAD

**Issue by meincocktailfass-tech** [Shopify/cli#4856]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

`shopify theme dev --store cocktailfassstaging.myshopify.com/admin
`

and login via store admin should grant access to CLI

### Actual behavior

![Image](https://github.com/user-attachments/assets/2ae7551c-9760-4fbd-93da-0a55874269e0)

### Verbose output

```shell
command not found although I'm using npm
```

### Reproduction steps

1. Entered line 
`shopify theme dev --store cocktailfassstaging.myshopify.com/admin
`
into command line
2. Authorised via store owner login in browser
3. Login and authorisation successful
4. Error returned in command line

I already tried all troubleshooting steps by updating all versions, granting app development in the store, deleting cache/cookies, logging out and back in, creating a staff member with all permissions but nothing seems to work.

### Operating System

Mac OS Sonoma 14.3.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.68.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v22.9.0

### What language and version are you using in your application?

Liquid

**Comment by jamesmengo** [comment]
Hey @meincocktailfass-tech!

I think the `/admin` path is messing up the authentication flow.
Could you try `shopify theme dev --store cocktailfassstaging.myshopify.com` instead?
