### ISSUE TITLE
[Bug]: Unable to deploy app with Flow extensions

### ISSUE THREAD

**Issue by patjakubik** [Shopify/cli#4894]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

It should deploy.

### Actual behavior

I recently started experimenting with Flow extensions and ran into an issue. Initially, I created an extension with a handle longer than 30 characters, unaware of the character limit. I deployed it to my staging environment, which failed, but oddly enough, the app version was released without the extension.

I then shortened the handle and redeployed to staging. Unfortunately, since then, I’ve been encountering errors like the following.

I tried deploying directly from my computer in the staging environment, and it worked fine. I was hopeful that it would now work in CI, but after retrying the release phase, the same error persists.

Next, I deleted the extension folder and redeployed to staging, and everything worked as expected - Flow extension was gone. However, when I reverted the commit that removed the folder, I’m back to encountering the same error.

### Verbose output
[redacted]

**Comment by isaacroldan** [comment]
Hi @patryk-smc, after deploying it should update the corresponding `.env` file, do you see any value at all on that file?
(just tested and it works as expected for me with a Flow Action)
