### ISSUE TITLE
[Bug]: ShopifyCLI::API::APIRequestTimeoutError: Timeout

### ISSUE THREAD

**Issue by SebiLarion** [Shopify/cli#4914]
Shopify theme dev is not working
I receive connection timeout error

**Comment by eibrahimov** [comment]
Same issue. When I run **npm run dev**  

Node: v20.16.0
Shopify CLI: @shopify/cli/3.68.1 darwin-x64 node-v20.16.0

![Image](https://github.com/user-attachments/assets/8a1810d2-c89d-4c76-a4f9-b77ffa5c5ac2)

**Comment by SebiLarion** [comment]
I'm from Romania, as far I can see for me status on cloudflarestatus.com is operational now.
But I think this( CLI authentication service uses Cloudflare ) could be an explanation as for me the problem was until this morning and today is working correctly.

**Comment by eibrahimov** [comment]
Yes, the problem is resolved now. However, the Cloudflare status has also changed @noiseymur 
![Image](https://github.com/user-attachments/assets/b62c27c0-6845-455e-946d-974294a7743d)

@aswamy I think this issue can be closed for now. Thanks
