### ISSUE TITLE
[Bug]: Windows path - Invalid Parameter

### ISSUE THREAD

**Issue by callummcmaugh-er** [Shopify/cli#498]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Expected to run the "dev" command to start development,

### Actual behavior

Testing Shopify app development, I ran the command "yarn dev" and I got an error of "exit code 1". I also tried npm. I exported the logs, and the path name seems to be an issue.

### Stack trace

```shell
yarn run v1.22.10
$ shopify logs
Invalid parameter - /Users
Done in 1.85s.
```

### Reproduction steps

1. Install @shopify/cli to latest version (3.12.0 for bug)
2. Create app using "yarn create @shopify/app"
3. Run "yarn dev"an 

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.12.0

### Shell

Powershell

### Node version (run `node -v` if you're not sure)

v16.15.0

### What language and version are you using in your application?

Node 16

**Comment by gonzaloriestra** [comment]
Hi! I'm not able to reproduce it. Could you please run `yarn dev --verbose` and share the output?
