### ISSUE TITLE
[Bug]: Asset must have a value or attachment

### ISSUE THREAD

**Issue by alexr8** [Shopify/cli#5010]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

I updated my shopify cli to the latest version (3.71.0) via Homebrew. Worth noting the following:

- I uninstalled Homebrew and reinstalled it so that it ran properly on my Mac (I had time machined from an intel mac to a silicon mac about 6 months ago, meaning my homebrew was using Rosetta so I reinstalled it at Homebrews suggestion). 
- However I had run the shopify CLI with my theme for many months on my new mac with no issues. I cannot remember if my previous install of the Shopify CLI was via npm or via homebrew unfortunately.

I ran `shopify theme dev` which should have synced my local theme to my development theme, as it had done before my CLI upgrade.

### Actual behavior

When i tried to run my usual `shopify theme dev` command to continue working on my store, i got the error:

```
Failed to perform the initial theme synchronization.
Asset must have a value or attachment 
```
I've not had issues before this upgrade. This is a custom theme, that was initially based on Dawn but then customised heavily.

I have since tried the following:
`shopify theme push` the theme - same error
`shopify theme delete` then `shopify theme dev` - same error

Below is the output of shopify theme dev with a verbose flag once i've deleted my development theme and tried `shopify theme dev` again.

### Verbose output

<details>
  <summary>Verbose output</summary>

  ```
See attached file above - character limit not long enough.
  ```

</details>

### Reproduction steps

1. Install latest shopify cli version via homebrew
2. Run shopify theme dev on an existing development theme

### Operating System

Mac OS 14.6.1 

### Shopify CLI version (`shopify --version`)

3.71.0

### Shell

VSCode 1.95.3 terminal, and iTerm2  3.5.10

### Node version (run `node -v` if you're not sure)

v23.3.0 (using the homebrew version of node)

**Comment by alexr8** [comment]
One further thing to note, i also tried deleting all files in my asset folder, and running `shopify theme delete` then `shopify theme dev` so it had no assets to upload, and i still got the same error of `Asset must have a value or attachment `.

**Comment by victor-roswell** [comment]
I am having the same exact issue.

**Comment by graygilmore** [comment]
Thank you for the report! We're fairly confident this is an issue when the CLI encounters an empty file that it tries to upload. We'll work on getting a patch out soon but in the mean time you can find all of your empty files by running the following inside your theme folder:

```bash
find . -type f -empty
```

**Comment by JasonHassold** [comment]
Can confirm I had 1 empty file as well

**Comment by jarnanchen** [comment]
anyone still having this even on the latest version?

**Comment by devinenoise** [comment]
Yike hot fix ASAP guys
