### ISSUE TITLE
Can't unlink old store from my Theme configuration

### ISSUE THREAD

**Issue by MigHerCas** [Shopify/cli#5019]
I've been having this issue for days and it blocks my daily work basis. 

I'm not authorized anymore to edit, list, or remove a theme that belongs to an old store to (which I don't have access anymore - managed by a client)

```bash
shopify theme info

THEME CONFIGURATION
Store                  {theirID}-2.myshopify.com
Development Theme ID   Not set

TOOLING AND SYSTEM
Shopify CLI    3.71.1 
OS             darwin-arm64
Shell          /bin/zsh
Node version   v23.3.0
```

This blocks me when running `shopify app dev` on my current project, which has a theme extension.

![Image](https://github.com/user-attachments/assets/a96cf951-1810-4fef-924a-012b6998792c)

![Image](https://github.com/user-attachments/assets/3a0d08a9-74e3-4771-9131-fca818ff7dbf)

Can someone help me or point me where I should be able to ask for help? I need to unlink this specific store from my current cli config. 

When I try to uninstalled & installed it again, via homebrew and npm global, it does not work.  Pulling other themes is not an issue.

**Comment by isaacroldan** [comment]
Hi @MigHerCas, seems like you need to select a different store for testing?

Just run `shopify app dev --reset` and that will force you to re-link your app and select a new store. Be sure to select the same app and a different store.

Let me know if that works

**Comment by isaacroldan** [comment]
Yes, `shopify app` and `shopify theme` commands cache their config in different places.
You can select a new store for `theme` commands by using `shopify theme dev --store <your_store>`

**Comment by MigHerCas** [comment]
Te amo
