### ISSUE TITLE
[Bug]: Validation Errors When Adding Dispute Evidence Scopes to Shopify App config

### ISSUE THREAD

**Issue by humza-sami** [Shopify/cli#5035]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

The scopes 

> read_shopify_payments_dispute_evidences

 and 

> write_shopify_payments_dispute_evidences

 should be accepted, allowing the app to submit dispute evidence programmatically.

### Actual behavior

I am building a simple Shopify app using Remix. The app is designed to trigger when a dispute is created for a purchase and automatically submit dispute evidence. I encountered a problem while syncing app scopes with the Partner Dashboard.

Here’s what I did:

- Created a new Remix app template using shopify app init.
- Navigated to the app folder (cd ./app_folder).
- Updated the shopify.app.toml file to include the following scopes:

> scopes = "write_products,read_products,read_shopify_payments_dispute_evidences,write_shopify_payments_dispute_evidences"  

### Verbose output

   

────────────────────────────────────────────────────────────────────────────────────
│                                                                                                
│  Version couldn't be created.                                                                  
│                                                                                                
│  app-access                                                                                    
│                                                                                                
│  Validation errors                                                                             
│    • scopes: read_shopify_payments_dispute_evidences,                                          
│      write_shopify_payments_dispute_evidences                                                  
│                                                                                                
╰────────────────────────────────────────────────────────────────────────────────────

### Reproduction steps

1. Install Shopify CLI version 3.71.
2. Initialize a Remix app using shopify app init.
3. Navigate to the app folder and update shopify.app.toml to include the scopes: 

> scopes = "write_products,read_products,read_shopify_payments_dispute_evidences,write_shopify_payments_dispute_evidences"  

### Operating System

Ubuntu 2024

### Shopify CLI version (`shopify --version`)

3.71.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v22.12.0

### What language and version are you using in your application?

Node

**Comment by humza-sami** [comment]
I need following permissions. Here are similar apps:
![Image](https://github.com/user-attachments/assets/0effdd11-3c49-465d-8ccf-3cbed942db1a)
![Image](https://github.com/user-attachments/assets/c137c2b2-d9f0-473e-b6d1-22ae1e75e0d7)

**Comment by isaacroldan** [comment]
This is not a CLI bug, those scopes are not in the list of available scopes ([here](https://shopify.dev/docs/api/usage/access-scopes#authenticated-access-scopes)) that your app can request so it's normal to receive a validation error.

If you are sure you need those specific scopes, i'd recommend to contact support directly but there is nothing we can do from the CLI side.

**Comment by Saad4534** [comment]
@humza-sami @isaacroldan did you figure how to add the read_shopify_payments_dispute_evidences scope to the remix app?
