### ISSUE TITLE
[Bug]: `shopify app deploy` automatically selects client-id, if not provided

### ISSUE THREAD

**Issue by Goondrious** [Shopify/cli#5053]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

`shopify app deploy` should deploy the config specified via `shopify app config use` or `--config=<path to file>`

### Actual behavior

I have two app `.toml` files for dev and prod. I previously was swapping between them with `shopify app config use` and was able to deploy both apps separately just with `shopify app deploy`. Currently, `shopify app dev` and `shopify app deploy` seem "locked" to the dev version.

Both `dev` and `deploy` always use the api key from the dev version and overwrite `.../shopify-cli-app-nodejs/config.json` with the incorrect app id, even if I set it again with `shopify app config use`.
- `dev` shows the warning (`The flag `api-key` has been deprecated in favor of `client-id`), `deploy` does not
- explicitly setting `--config` does not work
- **explicitly setting `--client-id` _does_ work**
- changing .env files did not work
- clearing all shopify npm cache directories did not work

These commands work fine:
- `shopify app versions list`
- `shopify app info`

I'm assuming it's a local setup thing, but as far as I know, I didn't change anything except upgrading the cli, so others might run into this.

### Verbose output

Sorry, I don't have time to redact the output right now! All I've got is:
- `FindApp` runs with the wrong `apiKey` value.

### Reproduction steps

I'll add exact steps later if I can but so far all I know is:

- try to run `shopify app deploy` in a project with multiple deployed `.toml` configurations, switching between them with `shopify app config use`

### Operating System

Mac 14.6 (23G80)

### Shopify CLI version (`shopify --version`)

@shopify/cli/3.71.4 darwin-arm64 node-v20.16.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

20.16.0

### What language and version are you using in your application?

node v20.16.0

**Comment by isaacroldan** [comment]
Hi @Goondrious!

So this is likely because you have some api key defined in your ENV, this line is the hint:
> The flag api-key has been deprecated in favor of client-id

Look for `SHOPIFY_API_KEY` in your terminal env (`echo $SHOPIFY_API_KEY`) or in any process that might be setting this value (`SHOPIFY_API_KEY`). This ENV value takes precedence over any other defined via `config use`.

Let me know if this works!

**Comment by Goondrious** [comment]
With all the random testing I did, I somehow did not think of directly checking system ENV. I have _no_ idea how it go there. Thank you!!!

**Comment by neel-bp** [comment]
can't thank you enough mate, i deleted shopify configs, from .config, deleted everything and pulled everything using shopify app config link --client_id and still somehow I don't know where shopify_cli was looking, but it kept pushing version to wrong app,
explicitly giving client_id shopify app deploy did the trick,

even after deleting .env file, and doing shopify app env pull, it still pulls the api_key from somewhere, maybe that was the issue.
