### ISSUE TITLE
Update esbuild version

### ISSUE THREAD

**Issue by athultuttu** [Shopify/cli#5110]
The current version of esbuild 0.19.8 has outdated dependencies like go v1.19. Please update esbuild to the latest version.

**Comment by isaacroldan** [comment]
As this is not a critical fix, we won't make a patch release. The change will be out in the next minor release, expected for early january.

In the meantime, if you really need to, you can use the `nightly` release channel (`npm i -g @shopify/cli@nightly`), but that may include other unexpected changes.

**Comment by athultuttu** [comment]
@isaacroldan will this change also update the esbuild dependency in @shopify/app package? if not how can i get that also updated?

**Comment by isaacroldan** [comment]
We stopped publishing new versions of `@shopify/app` months ago, everything is bundled inside `@shopify/cli` and that's the only package you need to use :)
