### ISSUE TITLE
[Feature]: Consistent overwrite/force pattern

### ISSUE THREAD

**Issue by cartogram** [Shopify/cli#53]
### What area(s) will this request affect?

Hydrogen custom storefront

### What type of change do you want to see?

Substantial change to existing feature

### Overview

When creating a hydrogen storefront in a directory that already exists. The CLI will prompt you to Overwrite or Abort using the `nonEmptyDirectoryPrompt` from the ui package.

<img width="744" alt="Screenshot 2022-06-24 at 19 09 20" src="https://user-images.githubusercontent.com/462077/175609457-3b61ba4f-d85f-4c3a-b69a-b043dc12387d.png">

When adding `eslint` or `tailwind`, you can pass a `--force` flag to overwrite existing config. This command will abort automatically.

<img width="480" alt="Screenshot 2022-06-24 at 19 08 29" src="https://user-images.githubusercontent.com/462077/175609334-d470aaf5-5207-4df0-8ed4-6c2045eca106.png">

These behaviours are similar enough, I think they should share a pattern. I suggest:

- Always prompt if doing a destructive operation (overwriting or deleting files/folders) where the default (first) option is Abort.
- Always allow a `--force` flag to suppress the prompt.

This should be added to the Hydrogen global flags that are shared with most commands.

### Motivation

Consistency in the UX for destructive operations will prevent users from making accidentally wrong choices and the CLI easier to use.

**Comment by keremh** [comment]
hi can i work on this issue?

**Comment by cartogram** [comment]
@keremh yeah, thanks! 🙏❤️
