### ISSUE TITLE
[Bug]: Shopify `shopify theme dev --store <storeURL>`

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#534]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

- Run `shopify theme dev --store <STORE_1>`
- The CLI (authentication mechanism) will prompt you to authenticate in the browser
- Login
- The development server starts
- Stop the development server with <kbd>Ctrl</kbd> + <kbd>C</kbd>
- Run `shopify theme dev --store <STORE_2>` (it's important to use a different store that requires a different user/email)
- The CLI (authentication mechanism) will prompt you to authenticate in the browser
- Login
- The development server starts

### Actual behavior

- Run `shopify theme dev --store <STORE_1>`
- The CLI (authentication mechanism) will prompt you to authenticate in the browser
- Login
- The development server starts
- Stop the development server with <kbd>Ctrl</kbd> + <kbd>C</kbd>
- Run `shopify theme dev --store <STORE_2>` (it's important to use a different store that requires a different user/email)
- The CLI (authentication mechanism) wont prompt you to authenticate in the browser
- The development server doesn't start

### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.13.1

**Comment by gonzaloriestra** [comment]
The authentication is saved between commands, so if you want to use a different account, you should run `shopify auth logout` first. I've checked that it works if you log out between both.

So I think this is the expected behavior. It happens the same with app development, if you want to deploy against an app from a different store, you need to log out first as well.

**Comment by isaacroldan** [comment]
We could potentially validate if the store passed via flag belongs to the current logged in organization, if it doesn't, alert the user that he needs to logout and login. What do you think?
(We already have a way to check if a store belongs to an org)

**Comment by isaacroldan** [comment]
Now that I think more about it, I think that @gonzaloriestra is right.

If you are actively trying to access a store that you know belongs to a different user, is normal to expect a "you don't have access to this store" error and should logout and login again.
The partners system is though so you only need 1 account and can be invited to as many organizations as you need, either as an owner or just as limited collaborator. And we shouldn't make accomodations to work outside this model.

@karreiro Maybe we can just improve the error message in this specific case?

**Comment by karreiro** [comment]
Thanks a lot for sharing those thoughts, @isaacroldan and @gonzaloriestra :)

Regarding the points you've mentioned:

> If they simply mistype the store, we will log them out anyway (but the current error message would be enough)

Balancing the pros and cons of each scenario, I personally believe that the benefit of avoiding a frequent extra/required step from users is higher.

> We should be consistent with how other parts work. For example, if you run shopify app dev --api-key wrong, we are just showing an error.

Indeed, I believe this is a very important constraint.

> @karreiro Maybe we can just improve the error message in this specific case?

That would help, but we'd still demand an extra step from users.

\-

Personally, as a user, I feel a bit odd about managing sessions in the CLI. As the CLI no longer requires the login, it sounds a bit counter-intuitive to perform a logout. That's why, in this case, I notice the `--store` flag in a more imperative sense.

Also, switching between stores is an operation quite frequent to many theme developers, so having a single command for this would optmize their workflow a lot.

Please, let me know what you think about these extra thoughts :)

**Comment by gonzaloriestra** [comment]
> As the CLI no longer requires the login, it sounds a bit counter-intuitive to perform a logout.

What do you mean? The CLI does require to log in to use theme commands.

> Also, switching between stores is an operation quite frequent to many theme developers

But do you think is also frequent to switch between stores from different accounts (emails)? Because if the store belongs to the same account, you don't need to log out.

**Comment by gonzaloriestra** [comment]
After [discussing about this](https://shopify.slack.com/archives/C03LLM1GCT0/p1665998379072529), we have decided to ask the user if they want to re-authenticate when we can’t find the store/app/whatever.

Related issue: https://github.com/Shopify/cli/issues/686
