### ISSUE TITLE
[Bug]: shopify theme dev session "timeout" 

### ISSUE THREAD

**Issue by ceri-waterscreative** [Shopify/cli#546]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Should be prompted to log back in

### Actual behavior

Served an error message 

"[API] Service is not valid for authentication"

### Reproduction steps

1. Run shopify theme dev
2. Leave it running until login session expires
3. Error Appears

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.15

### Shell

Git Bash

### Node version (run `node -v` if you're not sure)

16.15.1

### What language and version are you using in your application?

N/A

**Comment by notrealdev** [comment]
Same here with notice `"[API] Service is not valid for authentication"`
Is there an option to increase the sesion timeout limit?

**Comment by isaacroldan** [comment]
Just to check, are you using the latest CLI version? (3.22.1)

**Comment by notrealdev** [comment]
Hi @isaacroldan , if I do nothing after some time, it disconnects itself without giving a warning.
How can I stop this, every time like this I have to run `shopify theme dev` again, it's inconvenient

**Comment by notrealdev** [comment]
Just updated to v3.28.0 and it's fixed! After 2 hrs I'm still logged in. Thank you @isaacroldan!
