### ISSUE TITLE
npm run dev is not starting project

### ISSUE THREAD

**Issue by muhammad-hunnain786** [Shopify/cli#549]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I have create a new app using command npm init @shopify/app@latest

after creating app when i run command to run app locally it stucks on

Success! The tunnel is running now you can run your app

![image](https://user-images.githubusercontent.com/112260833/193320677-a841da58-d236-4c00-bdbb-a4d7e01b8708.png)

it does not give me app url and not starting dev server

i have already installed ngrok and added ngrok auth token

### Actual behavior

it should run dev server

### Reproduction steps

1. create new app
2. start app using npm run dev

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.15.0

### Node version (run `node -v` if you're not sure)

v16.17.1

### What language and version are you using in your application?

Node

**Comment by mahamudml** [comment]
What you can do is pass a tunnel-url to npm run dev. Check if it works

**Comment by muhammad-hunnain786** [comment]
> What you can do is pass a tunnel-url to npm run dev. Check if it works

from where i should get tunnel-url

can you please explain your answer

**Comment by isaacroldan** [comment]
Hi @muhammad-hunnain786, I wasn't able to reproduce your issue, could you run `dev` with the `--verbose` flag and report back the results? It'd help us find out why this could be happening :)

**Comment by yadsgroup** [comment]
Is there any update on this issue? I have the same problem and using yarn won't help me
