### ISSUE TITLE
[Bug]: Cannot run app dev

### ISSUE THREAD

**Issue by delyan-peev** [Shopify/cli#56]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Having the app started

### Actual behavior

I managed to workaround the libsecret issue. However, I'm stumbling across a new one that I think might be related to Docker and its credentials fetching (haven't checked the source, so I'm not sure).

Currently, when I run `npm run shopify app dev`

I'm getting the following:

![image](https://user-images.githubusercontent.com/19203780/175823677-48a2fb89-4143-400c-b31c-30d16e3c2d60.png)

### Reproduction steps

1. Run npm init @shopify/app@latest
2. Install libssl to workaround the first problem
3. npm run dev

### Operating System

Ubuntu 20.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0.24

### Node version (run `node -v` if you're not sure)

16.10

**Comment by amcaplan** [comment]
Hi @delyan-peev, thanks for opening an issue!

I'm not sure what's the libssl problem you're referring to, but it sounds like it's related to credentials. We do have a fix coming up related to credentials, but it sounds like this is probably something else.

Based on the screenshot, I'm assuming you're not using docker, which can be a bit [messy](https://anto.online/guides/cannot-autolaunch-d-bus-without-x11-display/#:~:text=What%20is%20the%20solution,need%20to%20install%20two%20applications.) with credential passthroughs (see here), but if you are then it's likely related.

It's possible [this](https://stackoverflow.com/a/53630430) would fix your problem (running `export $(dbus-launch)`), and even if it fails, it would be good to know what `dbus-launch` outputs..

**Comment by gonzaloriestra** [comment]
@delyan-peev [here ](https://github.com/Shopify/cli/issues/25#issuecomment-1167012160) you can find a workaround for that last error. It should be fixed in the next release.

**Comment by delyan-peev** [comment]
Sorry, but I went through the issue multiple times and I could not find anything that helps with the last one.

I have everything installed (libsecret-1-dev and gnome-keyring@3.36.0) and I'm still getting this error.
![image](https://user-images.githubusercontent.com/19203780/175908123-08d5abe6-a571-475d-ac81-54e9542ecac0.png)

**Comment by amcaplan** [comment]
Hi @delyan-peev, we've released a new version that includes a fix for this issue. Can you please upgrade (update the package versions in your `package.json`) and try again?

**Comment by delyan-peev** [comment]
Hey,

Thanks for looking into this.

Unfortunately, I’m on vacation until next Friday and I have no access to the machine the problem was observed on. I’ll update you next week.
