### ISSUE TITLE
[BugHunt]: The CLI is calling Ruby commands with the wrong Ruby version

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#569]
### In which of these areas are you experiencing a problem?

Other

### Expected behavior

The CLI should use the Ruby version shown in the `shopify theme info` command.

### Actual behavior

The CLI is using the one Ruby version in the `shopify theme info` command and other when it executes the `shopify theme init` command:

![image](https://user-images.githubusercontent.com/1079279/193868241-f5acae6c-4a58-4e20-a44f-a2e33fd6fe7c.png)

### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.16.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

18.10.0

**Comment by amcaplan** [comment]
OK so this is wild. `theme info` [uses](https://github.com/Shopify/cli/blob/7d056bd2a6397960198a84af248a31df5e7e726b/packages/cli-kit/src/node/ruby.ts#L282) the Homebrew-installed Ruby, referenced [here](https://github.com/Shopify/cli/blob/7d056bd2a6397960198a84af248a31df5e7e726b/packages/cli-kit/src/node/ruby.ts#L293). execCLI2 uses bundler from your Homebrew-installed Ruby as well, referenced [here](https://github.com/Shopify/cli/blob/7d056bd2a6397960198a84af248a31df5e7e726b/packages/cli-kit/src/node/ruby.ts#L298). So far so good.

However, the `shopify` executable [references](https://github.com/Shopify/shopify-cli/blob/main/bin/shopify#L1) `#! /usr/bin/env ruby` which means it's using whatever Ruby is defined there, and NOT the Ruby in your Homebrew. Which means we might need to do something in Homebrew install that will overwrite that line and force using the Homebrew Ruby.

**Comment by amcaplan** [comment]
Actually, now I'm not so sure. Playing around with the script locally, I printed out `RUBY_VERSION` in-process and it _was_ the Homebrew-installed version!

So instead, I think what's happening is that [this check](https://github.com/Shopify/shopify-cli/blob/082df62130ed78288a19e12d591b6e114225d0a6/lib/shopify_cli/environment.rb#L15) (invoked from [here](https://github.com/Shopify/shopify-cli/blob/082df62130ed78288a19e12d591b6e114225d0a6/lib/shopify_cli/command.rb)) is wrong, and we should just check the `RUBY_VERSION` global constant instead.
