### ISSUE TITLE
[Bug]: Creating web pixel extension fails

### ISSUE THREAD

**Issue by CoolTechYT** [Shopify/cli#574]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

It should create a web pixel extension associated with my app

### Actual behavior

It fails with the following message: 

`⭑ Fix the errors and run shopify extension create again.`

### Reproduction steps

1. Run `shopify extension create`
2. Select an app
3. Select Web Pixel Extension

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

2.7.1

### Node version (run `node -v` if you're not sure)

v16.15.0

**Comment by isaacroldan** [comment]
Hi @CoolTechYT !
Looks like you are using CLI 2.x, i'm afraid web pixel extensions are only supported on CLI 3.x.
[Here is a guide](https://shopify.dev/apps/tools/cli/migrate) to migrate your app to CLI3
