### ISSUE TITLE
[Bug]: Stuck in /api/auth/toplevel

### ISSUE THREAD

**Issue by rahilwazir** [Shopify/cli#585]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should redirect to request_grant i.e. https://zendesk.helpify24.com/api/auth?shop=helpify-test2.myshopify.com

### Actual behavior

When installing the app on one of the store, the URL with 200 status code stucks at: https://zendesk.helpify24.com/api/auth/toplevel?shop=helpify-test2.myshopify.com

Screenshot: https://i.imgur.com/qzUcXzR.jpg

When I manually remove the `/toplevel` from the URI, it proceeds to the expected behavior above.

### Reproduction steps

1.
2.
3.

### Operating System

Linux Ubuntu 22.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.16.2

### Shell

Bash

### Node version (run `node -v` if you're not sure)

v18.10.0

### What language and version are you using in your application?

Node v18.10.0

**Comment by alvaro-shopify** [comment]
Hi @rahilwazir !. Thank you for reporting this issue. I'm guessing you are using the command `dev`. 
* Are you updating your app`s URLs?
<img src="https://user-images.githubusercontent.com/105213827/195022075-8bc78728-f223-4f67-a3a1-ab2626a45e32.png" width=50% height=50%>

* In case you are not updating them, what URLs has the app in the dashboard currently?
<img src="https://user-images.githubusercontent.com/105213827/195023184-ee114b3a-2058-48a2-a855-70f777150ad8.png" width=50% height=50%>

I'm waiting to hear from you soon.

**Comment by rahilwazir** [comment]
Hi @alvaro-shopify Thanks for your response.

It is production deployment. App is set for Distribution and hosted on Digital Ocean.

The app is built using `npm run shopify app build` command from root of the project.

Now I need to run the backend (NodeJS), that is from the `web/` folder, I run `npm run serve` that runs the server on specified port `localhost:3000` (It is configured to be reverse proxy with NGINX so no issues there)

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1818941/195032757-2735fd16-4d8b-41f7-a84b-859cc95d996d.png">

The app URL is publicly accessible and also updated on App Setup

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/1818941/195032422-864aa33d-c246-4478-a077-9294774abe8d.png">

**Comment by rahilwazir** [comment]
Closing this, it was typo somewhere in the top-level file from our side.
