### ISSUE TITLE
Cannot use .env variables

### ISSUE THREAD

**Issue by bakura10** [Shopify/cli#589]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Hi,

I can see that the new Shopify CLI allows the usage of environment variables (for instance https://github.com/Shopify/cli/blob/971f9ef163d95b4709ca5f67dfefefb51cc4e844/packages/theme/src/cli/commands/theme/dev.ts#L49).

I have tried to create a .env file at the root of our theme, but it seems those are ignored and never pulled by the CLI tool.

How are those env variables supposed to work? They would definitely answer one of our most major concern we had with the CLI v2, but so far no luck :( (I hope this does not mean setting global PATH env variables in the computer though, because if that's the case, this limit to 0 the usability of this feature ; we have a lot of different themes so we need different store and theme ID values per project)

### Actual behavior

Shopify CLI should pull the environment variables for an ".env" file setup at the root of the folder.

### Reproduction steps

1. Create an .env file at the root of the folder.
2. Set up variables with their values.
3. Any command ignores them.

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.16

**Comment by karreiro** [comment]
@isaacroldan I believe this impacts all commands globally. Still, please, let me know if I'm missing something 🙏

**Comment by isaacroldan** [comment]
This is currently not possible, the CLI won't load variables from the `.env` file as flags. The `.env` file is used by the CLI to read information about the current APP (id, name, etc..), but this doesn't apply to theme commands.

We are [working](https://github.com/Shopify/cli/pull/543) on a way for users to define "presets". This will allow you to define customs flag values on each app/theme folder with a `shopify.presets.toml`. A beta of this feature will be available soon (probable in the next release)

For now, If you need to use the env variables only in that context, you can prepend the variable to the command: `SHOPIFY_FLAG_THEME_ID=xxxx shopify theme ...`  or create an alias that includes this env variable.

**Comment by bakura10** [comment]
Those presets seem to be exactly what we need here and the missing element to fully allow us to stop using ThemeKit. Great work! One thing: will this support allowing to run a command for different presets? One use case we have is that when we develop a theme, we have multiple demo stores, and ThemeKit has been very useful to allow me to push latest code to each demo store at one time.

**Comment by shauns** [comment]
Closing this as we can't share a reliable timeline just yet -- in the meantime @blanklob 's example is pretty great!
