### ISSUE TITLE
[Bug]: theme app extension registration not found  before that it was working fine after adding more partner account it was not working 

### ISSUE THREAD

**Issue by adventuretocode** [Shopify/cli#610]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

theme app extension was working before that after add more partner account in same it was say extension was not registered. but i can see the .evn file and  .shopify-cli.yml both are same as preview.   

when i used the  ` shopify extension push `  it was giving the error

### Actual behavior

theme app extension shall  be push to connected app  

### Stack trace

```shell
shopify extension push                                                                                           
Your environment Ruby version, 2.7.0, is outside of the range supported by the CLI, 2.7.5..<3.2.0, and might cause incompatibility issues.                                                                 
┏━━ Pushing your extension to Shopify ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Pushing code to Shopify…
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (1.07s) ━━
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ ✗ Extension Registration not found
```

### Reproduction steps

1. create new theme app extension
2. get more then one partner account in same partner email . then try to push the shopify extension push 
3.  you will get the error this was my case 

### Operating System

ubuntu 20

### Shopify CLI version (check your project's `package.json` if you're not sure)

3

### Shell

bash

### Node version (run `node -v` if you're not sure)

v16.16

### What language and version are you using in your application?

node 16

**Comment by shauns** [comment]
@adventuretocode if you're using `shopify extension push` then you will be on CLI2.0. We recommend moving to CLI3.0 without delay -- also if your Ruby version is out of the supported range for the tool then we can't promise support for it. 

Feel free to re-open or create a new issue once those upgrades are made, if you continue to have problems 👍
