### ISSUE TITLE
[Bug]: Can't deploy the extension built with CLI 3.0 when there is another extension in this app for CLI 2.0

### ISSUE THREAD

**Issue by architechpro** [Shopify/cli#619]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Deploy a new version of extension using command `npm run deploy`

### Actual behavior

Deployment fails because the amount of extensions connected to the app (2) doesn't match amount of extensions in this particular project (1) – as second extension is built with CLI v2.0.
App ID: `4918565`

### Stack trace

```shell
━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Deployment failed because this local project doesn't seem to match the app "(our app name)" in Shopify Partners.
 
    What to try:
    • If you didn't intend to select this app, run npm run deploy -- --reset
    • If this is the app you intended, check your local project and make sure
      it contains the same number and types of extensions as the Shopify app
      you've selected. You may need to generate missing extensions.


```
```


### Reproduction steps

1. Create an app 
2. Use CLI 2.0 to create and submit an extension (in our case – theme app block)
3. Use CLI 3.0 to create and submit an extension (in our case – subscription UI extension)
4. CLI 3.0 won't allow you to deploy any code updates to 3.0 extension

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.17.0

### Shell

bash

### Node version (run `node -v` if you're not sure)

v16.13.2

### What language and version are you using in your application?

PHP 7.4

**Comment by architechpro** [comment]
UPD: along with this, extension that is built with CLI v2.0 can be submitted and updated normally, so the issue is only with CLI v3.0.

**Comment by shauns** [comment]
Hi @architechpro -- the solution here is you must have the full collection of extensions in your apps code. Here's the instructions for theme app extensions &. migrating to CLI3: https://shopify.dev/apps/tools/cli/migrate#theme-app-extensions
