### ISSUE TITLE
[Feature]: Validate `shopify.ui.extension.toml` extension points

### ISSUE THREAD

**Issue by jamesvidler** [Shopify/cli#622]
### What area(s) will this request affect?

Extension

### What type of change do you want to see?

New feature

### Overview

When configuring an extension in the `toml` file, it is easy to have a typo which results in unexpected behavior. It would be nice if the dev server could detect invalid toml files and notify the developer about this.

### Motivation

A specific case I've run into several times with setting `extension_points` within the `shopify.ui.extension.toml` file:
1. Open `shopify.ui.extension.toml` and change the `extension_points` property from `Checkout::Dynamic::Render` to `Checkout::Dynamic:Render` (note the typo with the missing "::").
2. The dev server builds and does not give any error, but the extension is not rendered.

This results in wasted time trying to debug the issue, when it was just a simple typo.

**Comment by alvaro-shopify** [comment]
Hi @jamesvidler . Thank you for your proposal. We are already working on improving the experience of working with the app configuration files. There is already an opened [issue](https://github.com/Shopify/shopify-cli-planning/issues/392). I will update the status here where we make any progress on it.
