### ISSUE TITLE
App is not installed in multiple store using Shopify CLI

### ISSUE THREAD

**Issue by avinashbrst** [Shopify/cli#623]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Hello,
I wan to installed the App in Multiple store in Shopify. The App is working fine for one store but I want to installed it for multiple store.  I am trying to installed it from partner account into multiple store. But its not installing and gives error. So how can I do it using Shopify CLI etc.
Thanks

### Actual behavior

Hello,
I wan to installed the App in Multiple store in Shopify. The App is working fine for one store but I want to installed it for multiple store.  I am trying to installed it from partner account into multiple store. But its not installing and gives error. So how can I do it using Shopify CLI etc.
Thanks

### Stack trace

```shell
Hello,
I wan to installed the App in Multiple store in Shopify. The App is working fine for one store but I want to installed it for multiple store.  I am trying to installed it from partner account into multiple store. But its not installing and gives error. So how can I do it using Shopify CLI etc.
Thanks
```

### Reproduction steps

1.  npm run dev
2. choose the store
3. installed the app.

### Operating System

Window

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.1

### Node version (run `node -v` if you're not sure)

v14.02

### What language and version are you using in your application?

Ruby 3.0.3, Node 14.02, PHP 7.4

**Comment by alvaro-shopify** [comment]
Hi @avinashbrst. Thanks for reporting this issue. 

You can run the CLI command `yarn dev --reset` and select a different store to try the application on. On the other hand, what's the error message you are receiving when you try to install the app from the partner dashboard?.

Waiting to hear from you soon.
