### ISSUE TITLE
Checkout ui extension not displayed after deployment

### ISSUE THREAD

**Issue by Omdaprog** [Shopify/cli#627]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

i have deployed my app on heroku and then i deployed extension with cli command `npm run deploy` and create a version on partner dashbord , then i expected my extension will integrate with checkout page
Ps: the extension runs well locally  

### Actual behavior

after doing all those steps my extension wont appeared on checkout page 

### Reproduction steps

1. run `npm run shopify app generate extension`
2. update extension folders
3. run `npm run dev` to make sure that works fine 
4. run `npm run deploy`
5. create a version of app extension on partnre dashbord 
6. deploy my web app on heroku 

### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.15.0

### Node version (run `node -v` if you're not sure)

v16.15.1

### What language and version are you using in your application?

node

https://github.com/Shopify/cli/issues/627#tasklist-block-d513724f-0d4c-49ef-8178-e9237c160c2f

**Comment by adventuretocode** [comment]
'npm run deploy'  can you share the trace back of that command output

**Comment by adventuretocode** [comment]
@Omdaprog   extension was publish with your app go to your app then extension menu  you can see the last line link click their you will redirected to the your data-of birth extension. 

create 
![image](https://user-images.githubusercontent.com/114073623/195557665-8cf32b32-4fef-46f8-9af6-660dcd882096.png)
 
Create version and  extension in development stores. Preview is enabled by default is disable  

![image](https://user-images.githubusercontent.com/114073623/195557802-aa93ad72-7419-440a-936f-628b1567c0b2.png)

**Comment by Omdaprog** [comment]
im using container-based deployment to host my app , shopify app already comes with Dockerfile like below 
![Screen Shot 2022-10-13 at 1 22 34 PM](https://user-images.githubusercontent.com/43305769/195594957-ecce434f-9abb-48da-a9a6-03206696d1d2.png)
as you can see docker will copy only web folder and past it to app folder then run "npm run serve"
the app extension works well locally 
i tested my app on plus store and same result

**Comment by Omdaprog** [comment]
@adventuretocode can you more explaine ?

**Comment by mleandres** [comment]
Hello @Omdaprog, extensions won't be added to a live checkout until added to a checkout profile in the shop admin checkout settings. This is to allow a merchant to customize their app extension locations on their checkout and have different combinations of extensions.

When editing a checkout profile, you can add an app to your checkout there
![image](https://user-images.githubusercontent.com/35632116/202212037-a65dc870-8513-4315-8ae5-f37b5e030a57.png)

After you click customize, you should see this sidebar with the `add app` button. If the app is installed on your dev shop then you'll see it there.
![image](https://user-images.githubusercontent.com/35632116/202212521-0751fd7f-4683-4754-926b-9a3446302c8f.png)
