### ISSUE TITLE
[Bug]: The CLI should work on Windows with the latest Ruby version

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#639]
### Expected behavior

The CLI should work on Windows with the latest Ruby version.

### Actual behavior

The CLI doesn't work on Windows with the latest Ruby version.

### Reproduction steps

Given the developer has an old Ruby version on their machine
- Install Ruby 2.6.10
- Select the MSYS2 component and select the MYS2 base installation
- `gem install bundler`
- Try to execute the Shopify CLI with a command that depends on Ruby (`shopify theme init`)
- The CLI fails and guides the user to install newer Ruby versions

Then the developer tries to update Ruby to 2.7.6
- Install Ruby 2.7.6
- Select the MSYS2 component and select the MYS2 base installation
- `gem install bundler`
- Try to execute the Shopify CLI with a command that depends on Ruby (`shopify theme init`)
- This message appears

<img src="https://user-images.githubusercontent.com/1079279/196133171-10eef8e0-9d7e-48af-807f-bbc1c8ee9152.png" width="70%">

Then the developer tries to update Ruby to 3.1.2
- Install Ruby 3.1.2
- The installation is not succeeded, and users face this error

<img src="https://user-images.githubusercontent.com/1079279/196134541-3d06d54f-b728-4350-a21c-ff70a62f6a5b.png" width="30%">

- 🚫 **At this point users, cannot use the CLI Ruby commands**

### Workaround steps

- Uninstall all Ruby and MSYS2 instances on Control Panel
- Install Ruby 3.0.4
- Select the MSYS2 component and select the MYS2 base installation
- `gem install bundler`
- Try to execute the Shopify CLI with a command that depends on Ruby (`shopify theme init`)
- Notice it works

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.16

**Comment by Arkham** [comment]
Hi @karreiro, unfortunately the issue is with Ruby itself and windows https://github.com/oneclick/rubyinstaller2/issues/308#issuecomment-1268851455 I think the current workaround is the way to go until windows starts pushing the patch they were mentioning in the github thread.

**Comment by karreiro** [comment]
Thank you for that context, @Arkham!
