### ISSUE TITLE
[Shopify.dev tutorial feedback] APP::ERROR::INVALID_CONFIG: host must be provided

### ISSUE THREAD

**Issue by shainaraskas** [Shopify/cli#64]
>There needs to be a section within step 2 that talks about how to set up the config before running "npm run dev". Getting the following error
>
>localhost/:1 Uncaught 
>AppBridgeError2
>action: undefined
>message: "APP::ERROR::INVALID_CONFIG: host must be provided"
>name: "AppBridgeError"
>type: "APP::ERROR::INVALID_CONFIG"
>stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided"
>[[Prototype]]: Error

Feedback received for:
- Page: [Create an app](https://shopify.dev/apps/getting-started/create) (/apps/getting-started/create)
- Section: [Step 2: Start a local development server](https://shopify.dev/apps/getting-started/create#step-2-start-a-local-development-server)
- Sentiment: Negative

---
<details>
<summary>View User Agent Details</summary>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
</details>

**Comment by pepicrft** [comment]
@shainaraskas the templates come with that setup by default. Is this by any chance a user that's migrating an existing app or creating their own `web/` setup?

**Comment by pepicrft** [comment]
I'll go ahead and close it and tell the user to open an issue on https://github.com/shopify/cli if the issue persists.

**Comment by manuelmoreno188** [comment]
I'm having this issue, starting a new app project. I'm seeing this error in my console 
<img width="905" alt="imagen" src="https://user-images.githubusercontent.com/80382201/178624212-7e1d4c2c-9c19-40ad-8445-1c12cda7c7f2.png">

**Comment by shainaraskas** [comment]
@manuelmoreno188 What is the URL that you're navigating to? You might see this error when you navigate to the ngrok base URL (e.g. `https://<id>.ngrok.io/`), but you shouldn't see it if you're using the full URL printed in the console (e.g. `https://<id>.ngrok.io?shop=<dev_store>.myshopify.com&host=<hash>`)
