### ISSUE TITLE
[Feature]: Configure an app with the cli

### ISSUE THREAD

**Issue by gioragutt** [Shopify/cli#645]
### What area(s) will this request affect?

App, Deployment

### What type of change do you want to see?

New feature

### Overview

I'd like to be able to configure an existing app from the CLI.

Basically any input in the `App Setup` section, as well as the ability to handle extension versions in the `Extensions` section.

### Motivation

This would allow automating a big part of the workflow of the local development flow:
* Updating the URLs (App Url, Redirection URLs), e.g after creating a new ngrok tunnel
* When creating a new extension, enabling it automatically without having to go through the web ui.

This will allow faster developer onboarding (with self-documenting scripts being the source of truth of setup), as will as reduce friction during the development phase (during complex flows such as when developing a Checkout Post Purchase extension).

**Comment by gioragutt** [comment]
Hi @stephszeto, thanks for replying! I may get a more thorough response with the help of one of my (more experienced) teammates if needed, but as far as I know, our app does not use the more modern app development workflows, since it's quite an old project (approximately 7 years). We have plans to modernize in the future, but as it is now, we have a backend nodejs server that we run locally without the usage of the shopify cli.

We do have a post-purchase checkout app extension, so it does use the shopify cli, however it is not the case for the rest of the project.

In the case we want to develop locally (and test our app in a shopify context), we each have our own app, and we update the App URL and Redirection URLs when spinning up a new tunnel (which we do manually since we don't use the shopify cli).

**Comment by gioragutt** [comment]
A follow up question to what you said - say we have the current situation where we have an app the does not use the shopify cli.

Is it possible to still use the shopify cli for the purpose of creating a tunnel to the app (and setting up the URLs as mentioned)?

**Comment by gioragutt** [comment]
Something that I'd also probably want to raise is the matter of webhooks, but I'd first want to discuss it with the teammates that I know already dealt with it (I'm still super new to the Shopify development scene so I've not dealt with all of these things), to see what would be a cleaner workflow than what there is now (which, as far as I remember, is that we have to delete the app and re-install it in the store if the tunnel is changed).

**Comment by gonzaloriestra** [comment]
Hi! Since v3.32.0, you can now update the URLs from the CLI with `shopify app update-url` 🙂

**Comment by stephszeto** [comment]
Hi Giora - a few updates for you: 
- as Gonzalo mentioned above, we have a new CLI command that will allow you to update your app URLs programmatically - check it out if you haven't already
- the friction currently involved in publishing an extension version live is on our radar and something we're thinking about. I wouldn't hold your breath for a solution to come in the near future, but hoping that we'll have a better answer for you by sometime later this year. 

In the meantime, closing this out for now.
