### ISSUE TITLE
[Bug]: Old `esbuild` Dependency Causing Build Issues

### ISSUE THREAD

**Issue by joealden** [Shopify/cli#649]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App, Extension

### Expected behavior

When running `shopify app build`, the build should succeed when using [`type` Modifiers on Import Names](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names), as the versions of TypeScript (4.5) and `esbuild` (0.13.3) that support this syntax were released nearly a year ago.

### Actual behavior

Running `shopify app build` when using [`type` Modifiers on Import Names](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names) causes the build to fail. This looks to be because `@shopify/shopify-cli-extensions` is using a pretty outdated `esbuild` version (0.12.x, see [here](https://github.com/Shopify/cli/blob/8772adc7aab41a4ed3dcb41798d41b96406fa3d9/packages/ui-extensions-cli/package.json#L40)).

It's worth noting that `@shopify/app` already depends on `esbuild@0.15.7` (see [here](https://github.com/Shopify/cli/blob/8772adc7aab41a4ed3dcb41798d41b96406fa3d9/packages/app/package.json#L66)), so it looks like you are already keeping up on updating `esbuild` there, but have perhaps forgot about doing to same for `@shopify/shopify-cli-extensions`?

### Stack trace

```shell
ui-extensions    | Building UI extensions...
ui-extensions    | project (> ../../../file.ts:1:14: error: Expected "}" but found "X"
ui-extensions    |     import { type X } from "Y";
ui-extensions    |                   ~
ui-extensions    | 
ui-extensions    | 1 error
ui-extensions    | Error building extension:  Error: Build failed with 1 error:
ui-extensions    | ../../../file.ts:1:14: error: Expected "}" but found "X"
ui-extensions    |     at failureErrorWithLog (/root/app/node_modules/esbuild/lib/main.js:1475:15)
ui-extensions    |     at /root/app/node_modules/esbuild/lib/main.js:1133:28
ui-extensions    |     at runOnEndCallbacks (/root/app/node_modules/esbuild/lib/main.js:1051:65)
ui-extensions    |     at buildResponseToResult (/root/app/node_modules/esbuild/lib/main.js:1131:7)
ui-extensions    |     at /root/app/node_modules/esbuild/lib/main.js:1240:14
ui-extensions    |     at /root/app/node_modules/esbuild/lib/main.js:611:9
ui-extensions    |     at handleIncomingPacket (/root/app/node_modules/esbuild/lib/main.js:708:9)
ui-extensions    |     at Socket.readFromStdout (/root/app/node_modules/esbuild/lib/main.js:578:7)
ui-extensions    |     at Socket.emit (node:events:513:28)
ui-extensions    |     at addChunk (node:internal/streams/readable:315:12) {
ui-extensions    |   errors: [
ui-extensions    |     {
ui-extensions    |       detail: undefined,
ui-extensions    |       location: [Object],
ui-extensions    |       notes: [],
ui-extensions    |       pluginName: '',
ui-extensions    |       text: 'Expected "}" but found "X"'
ui-extensions    |     }
ui-extensions    |   ],
ui-extensions    |   warnings: []
ui-extensions    | })
```

### Reproduction steps

1. Create an app that has includes a UI extension.
2. Add a file to said extension that includes a an inline type modifer (`import { type X } from "Y"`).
3. Build the app and see the build error.

### Operating System

N/A

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.19.0

**Comment by shauns** [comment]
Thanks for raising this @joealden -- we're on the case.
