### ISSUE TITLE
[BugHunt]: `shopify theme open`/`shopify theme publish` commands fail on CI/CD workflows

### ISSUE THREAD

**Issue by karreiro** [Shopify/cli#651]
### Expected behavior

- Install [Theme Kit Access](https://apps.shopify.com/theme-kit-access) app and generate a new password
- Run `shopify auth logout`
- Run `export SHOPIFY_FLAG_STORE=<YOUR_STORE>`
- Run `export SHOPIFY_FLAG_STORE=<YOUR_THEME_ACCESS_PASSWORD>`
- Run `shopify theme open`
- Run `shopify theme publish`
- Both commands above should work

### Actual behavior

- Install [Theme Kit Access](https://apps.shopify.com/theme-kit-access) app and generate a new password
- Run `shopify auth logout`
- Run `export SHOPIFY_FLAG_STORE=<YOUR_STORE>`
- Run `export SHOPIFY_FLAG_STORE=<YOUR_THEME_ACCESS_PASSWORD>`
- Run `shopify theme open`
- Run `shopify theme publish`
- Notice that both commands show the following error

<img width="60%" alt="error1" src="https://user-images.githubusercontent.com/1079279/196946978-68659b69-29c7-47a1-937b-6d49b11e340c.png">
<img width="60%" alt="error2" src="https://user-images.githubusercontent.com/1079279/196946992-c948328f-41eb-4ad0-a7d1-22740f54ad25.png">

### Operating System

macOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.19

**Comment by stephszeto** [comment]
Hm, I feel like `theme publish` not working would be a big deal from a CI/CD perspective, no? Should this be higher in severity?

**Comment by karreiro** [comment]
That's correct, @stephszeto! I don't think it requires a higher severity.
