### ISSUE TITLE
[Bug]: Preset does not work for themes

### ISSUE THREAD

**Issue by bakura10** [Shopify/cli#672]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

* Created a "shopify.presets.toml" file at the root of my folder.
* Run the command `shopify theme dev --preset=dev`
* CLI properly extracts the variables, but fail to run the command:

<img width="477" alt="Capture d’écran 2022-10-25 à 21 39 36" src="https://user-images.githubusercontent.com/1198915/197866554-d0b86e6f-8735-47fb-a016-f0a6baf89a85.png">

### Actual behavior

* CLI should not show any error

### Reproduction steps

1.
2.
3.

### Operating System

OS X

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.20

**Comment by blanklob** [comment]
@bakura10 Hey I made an example that uses env variables in a preset file similar to the toml file you mentioned above, until the full implementation hit production and gets announced, you can use this: https://github.com/blanklob/shopify-cli-3-themes-demo

**Comment by bakura10** [comment]
@blanklob , I tried yesterday and the preset approach now works, so we can get rid of the extra dependency of your demo ;)
