### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by code-man** [Shopify/cli#679]
Upgrading to Shopify CLI v3.20.1 running on MacOS Ventura 13.0 sees this error when trying to run any of the Shopify CLI commands:

`(node:25832) UnhandledPromiseRejectionWarning: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node/cli' is not defined by "exports" in /usr/local/Cellar/shopify-cli/3.20.1/libexec/lib/node_modules/@shopify/cli/node_modules/@shopify/cli-kit/package.json imported from /usr/local/Cellar/shopify-cli/3.20.1/libexec/lib/node_modules/@shopify/cli/dist/index.js
    at throwExportsNotFound (internal/modules/esm/resolve.js:280:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at packageResolve (internal/modules/esm/resolve.js:607:14)
    at moduleResolve (internal/modules/esm/resolve.js:649:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:695:13)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by shahways** [comment]
Used `brew update` and `brew upgrade` on macOS Monterey v12.4 to update the shopify-cli package to 3.22.1.
Any shopify command on the command line now results in the following error message. Please advise or resolve.

(node:1105) ExperimentalWarning: The ESM module loader is experimental.
(node:1105) UnhandledPromiseRejectionWarning: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node/cli' is not defined by "exports" in /usr/local/Cellar/shopify-cli/3.22.1/libexec/lib/node_modules/@shopify/cli/node_modules/@shopify/cli-kit/package.json imported from /usr/local/Cellar/shopify-cli/3.22.1/libexec/lib/node_modules/@shopify/cli/dist/index.js
    at throwExportsNotFound (internal/modules/esm/resolve.js:267:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:487:3)
    at packageResolve (internal/modules/esm/resolve.js:584:14)
    at moduleResolve (internal/modules/esm/resolve.js:633:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36)
(node:1105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by shahways** [comment]
> Used `brew update` and `brew upgrade` on macOS Monterey v12.4 to update the shopify-cli package to 3.22.1. Any shopify command on the command line now results in the following error message. Please advise or resolve.
> 
> ```
> (node:1105) ExperimentalWarning: The ESM module loader is experimental.
> (node:1105) UnhandledPromiseRejectionWarning: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node/cli' is not defined by "exports" in /usr/local/Cellar/shopify-cli/3.22.1/libexec/lib/node_modules/@shopify/cli/node_modules/@shopify/cli-kit/package.json imported from /usr/local/Cellar/shopify-cli/3.22.1/libexec/lib/node_modules/@shopify/cli/dist/index.js
>     at throwExportsNotFound (internal/modules/esm/resolve.js:267:9)
>     at packageExportsResolve (internal/modules/esm/resolve.js:487:3)
>     at packageResolve (internal/modules/esm/resolve.js:584:14)
>     at moduleResolve (internal/modules/esm/resolve.js:633:14)
>     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:726:11)
>     at Loader.resolve (internal/modules/esm/loader.js:97:40)
>     at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
>     at link (internal/modules/esm/module_job.js:46:36)
> (node:1105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:1105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

It is related to nodejs. I use NVM and for some recent legacy projects, I switched to an old node.js (v12). As soon as I switched back to v16.13.2, Shopify CLI commands were working again.
