### ISSUE TITLE
Investigate and fix changesets causing major version bumps when minor changes are present

### ISSUE THREAD

**Issue by pepicrft** [Shopify/cli#68]
### Context
When there are changeset files with `minor` changes, `changeset version` might yield a major version bump. When this happened in the past, we manually changed all the `minor` changes to `patch` and ran `changeset version` again. This is not ideal because it prevents us from automating the release e2e.

### What
Investigate why the major bumps are happening and fix it.

**Comment by gonzaloriestra** [comment]
It seems to be solved after the latest changes related to peerDependencies.
