### ISSUE TITLE
[Bug]: CLI gives incorrect error when logged in account does not have access to store. 

### ISSUE THREAD

**Issue by petercampanelli** [Shopify/cli#686]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The CLI should have displayed a message saying that the currently logged in account does not have access of any kind to the store on the passed `--store` flag. Then it should prompt to log in with a different account or log them out or something. `shopify auth logout` is not included in the migration instructions, but is probably not necessary if this is done right. 

### Actual behavior

The following error was printed after running `shopify theme dev --store=myotherstorenamehere.myshopify.com`

```
┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (1.02s) ━━
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ You can't use Shopify CLI with development stores if you only have Partner staff member access. If you want to use Shopify CLI to work on a development store, then you should be the store owner or create a staff account on the store.
┃ 
┃ If you're the store owner, then you need to log in to the store directly using the store URL at least once (for example, using myotherstorenamehere.myshopify.com/admin) before you log in using Shopify CLI. Logging in to the Shopify admin directly connects the development store with your Shopify login.
┃ 
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
error Command failed with exit code 1.
```

This is an incorrect error because the store I was attempting to log into is not and never was a development store and the logged in account does not have Partner staff member access or access of any kind to this store.

### Reproduction steps

1. Log into a store with an Shopify account (a partner account to get this exact error i'm guessing, have not tried with an account that is not partner) that has access for example by running `shopify theme dev --store=mystorehere.myshopify.com` then close dev server. 
2. Switch to a different theme on a different store, etc in a different folder. This theme is one that the account from step 1 does NOT have access to of any kind. A different login is needed to sign into this different store.
3. Try running `shopify theme dev --store=myotherstorehere.myshopify.com`
4. Witness error.

### Operating System

Mac OS 13 Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.20.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.15.0

### What language and version are you using in your application?

Liquid

https://github.com/Shopify/cli/issues/686#tasklist-block-7c89a3cd-7b45-4b50-a5a8-e44c4ad3d0eb

**Comment by lananhdu** [comment]
I can't log in my theme in version 3.21.0   
![Screen Shot 2022-11-01 at 11 55 01](https://user-images.githubusercontent.com/32170415/199161903-517e438a-c6b5-4b51-aed4-7d584378b7af.png)
