### ISSUE TITLE
[Bug]: Cannot select desired dev store when creating new app

### ISSUE THREAD

**Issue by t-kelly** [Shopify/cli#691]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

My parter organization has more than 500 stores linked to it. I should be able to select any store linked to my partner account from the [selectStorePrompt](https://github.com/Shopify/cli/blob/cdf1a566646226f8b4c8b596b007164101f7c6ec/packages/app/src/cli/prompts/dev.ts#L33-L50).

### Actual behavior

The [selectStorePrompt](https://github.com/Shopify/cli/blob/cdf1a566646226f8b4c8b596b007164101f7c6ec/packages/app/src/cli/prompts/dev.ts#L33-L50) uses the [fetchAllStores](https://github.com/Shopify/cli/blob/cdf1a566646226f8b4c8b596b007164101f7c6ec/packages/app/src/cli/services/dev/fetch.ts#L89-L93) method which can only request [the first 500 stores of an organziation](https://github.com/Shopify/cli/blob/eea17b2ea5282e5fd1cdee9760812a3f23555b23/packages/cli-kit/src/api/graphql/all_stores_by_org.ts#L3-L20). I cannot then select a store that falls out of these first 500 results.

### Reproduction steps

1. Create a new app and run `npm run dev`. Make sure there are more than 500 stores linked to the organization
2. See how only the first 500 stores show during the select a store prompt

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.20.1

**Comment by amcaplan** [comment]
Hi @t-kelly, thanks for opening an issue!

We should code a proper fix for this, but in the meantime, you can use the `--store` flag on `dev` (`-s` for short) to specify your store. As long as you don't `--reset` it will get saved for future runs.

**Comment by resistorsoftware** [comment]
This is hilarious. I love these insider issues. Just make sure you have more than 500 stores linked to your partner account and see what happens! I could understand a 512 failure due to base 2 arithmetic. Or 50 as a famous Shopify limit on things. 500 is just pure comedy though. Love it! Double the 250 limit for other resources is my guess. Just limit them to twice the usual!
