### ISSUE TITLE
[Feature]: Automatable mode for authentication for theme dev command

### ISSUE THREAD

**Issue by nikitaourazbaev** [Shopify/cli#695]
### What area(s) will this request affect?

Theme

### What type of change do you want to see?

Substantial change to existing feature

### Overview

It would be great if the `shopify theme dev` command could have a mode that made it easier to include it in a `watch`-style build script.

This could either be in the form of it taking the `--password` flag, or another flag to kick off the authentication flow automatically if the user is logged out, skipping the keypress, like Shopify CLI v2, or it accepting `SHOPIFY_CLI_THEME_TOKEN`, or some other form of authentication token, like the other commands in v3 and like ThemeKit.

### Motivation

Currently, `shopify theme dev` does not accept the `--password` flag nor does it read the `SHOPIFY_CLI_THEME_TOKEN` variable from the environment. Additionally, unlike Shopify CLI v2, it does not kick off the authentication flow automatically but instead waits for a keypress from the user. 

This makes it challenging to use `shopify theme dev` in a `watch`-style continuous build script, as allowing `stdin` through makes things complicated.

It would be great if the command had an automation-friendly mode.

**Comment by GitYing** [comment]
CLI 3.0 has to be one of the worst updates for theme dev. Does anyone know a safe way to use version 2.0 without the constant logouts

**Comment by vfonic** [comment]
@nikitaourazbaev I just discovered there's `SHOPIFY_CLI_THEME_TOKEN` ENV var.

https://shopify.dev/themes/tools/cli/ci-cd#step-2-integrate-shopify-cli-into-your-pipeline

Hope it helps!

**Comment by nikitaourazbaev** [comment]
@vfonic unfortunately, that ENV var works for `shopify theme push` and other theme commands, but not for `shopify theme dev`

**Comment by isaacroldan** [comment]
the `theme dev` command now accepts the `--password` flag, at least since version 3.29. So I'll close this issue :)
