### ISSUE TITLE
[Feature]: Show me why and how to update

### ISSUE THREAD

**Issue by vfonic** [Shopify/cli#698]
### What area(s) will this request affect?

Other

### What type of change do you want to see?

New feature

### Overview

I just switched from Shopify CLI 2.x for theme development to Shopify CLI 3.x. I have `3.20.1` version and, when I ran `shopify version`, I got the following output:

```
> shopify version
Current Shopify CLI version: 3.20.1
💡 Version 3.21.0 available!
```

What can I do with this information? What changed? The number went from 3.20.1 to 3.21.0? Anything else? How can I update?

### Motivation

It's great to see the new version available. However, I don't know what I can do with this information, aside from spending 5-10+ minutes to figure out what I could/should do.

I suggest:

1. Show some changelog, some "incentive" of why I should update
2. Show instructions how I can update.

For 1. you could at least print out the URL to the CHANGELOG.md

For 2. you can print out the URL to "updating guide" (I assume you have one?). I understand that there are several ways to install the CLI so that's why it could be difficult to print the updating instructions, but you can at least show me where I can read more about updating, instead of me having to find where the updating documentation is - is it in the GitHub repo or is it somewhere on shopify.dev or...? Please improve the DX (developer experience) here.

Thank you! 🙏

**Comment by vfonic** [comment]
I discovered that there's `shopify upgrade` command:

```
> shopify upgrade
Upgrading CLI from 3.20.1 to 3.21.0...
Homebrew installation detected. Attempting to upgrade via brew upgrade...
Warning: shopify/shopify/shopify-cli 3.20.1 already installed
✅ Success! Upgraded Shopify CLI to version 3.21.0.
> shopify version
Current Shopify CLI version: 3.20.1
💡 Version 3.21.0 available!
```

![https://xkcd.com/986/](https://imgs.xkcd.com/comics/drinking_fountains.png)
https://xkcd.com/986/

**Comment by shauns** [comment]
I think for homebrew the best bet is to leave that to the developer to manage, though I suppose we could suggest to them to `brew update && brew upgrade` as the most likely command. Thanks for bringing this to our attention!
