### ISSUE TITLE
[Bug]: Auth "cookie" / session expires within just a few hours

### ISSUE THREAD

**Issue by vfonic** [Shopify/cli#705]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Other

### Expected behavior

When I login via browser to use CLI, I should stay logged in, at least a day, hopefully a week or more.

### Actual behavior

I was just asked to login again, third time in the last 8 hours or so. What can I do to keep the session running longer?

### Operating System

macOS Monterey 12.6

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.20.1

**Comment by GitYing** [comment]
Happens on windows too super annoying, thinking of going back to Cli 2.0

**Comment by isaacroldan** [comment]
Hi @vfonic, thank you for reporting this, this is definitely not the intended behaviour. 
Are you using the CLI for themes or for apps? I'll pass the bug to the team.

**Comment by vfonic** [comment]
Thank you so much! I use it exclusively for theme development at this point. Although I'm looking to use it for app development as well, but the amount and the pace of changes is too big for me that I need to dedicate few hours to figure out how to use the tool for my (existing) apps.

Thanks! 🙏
