### ISSUE TITLE
[Bug]: Invalid_target while running shopify theme dev --store xxxxxxx.com

### ISSUE THREAD

**Issue by FriedRiceNoodles** [Shopify/cli#706]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Start a local server

### Actual behavior

browser:
![image](https://user-images.githubusercontent.com/53017934/199383508-55e6d8c6-8bad-4781-bd09-f5b1c52a1fb4.png)
terminal:
![image](https://user-images.githubusercontent.com/53017934/199383422-3d9ada5f-f3eb-47e6-a9ce-c87d78a337c2.png)

### Reproduction steps

1. sudo npm install @shopify/cli -g
2. shopify theme dev --store myshopify.com

### Operating System

MacOS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.21.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

16.15.0

**Comment by vikashjajra** [comment]
Shouldn't this be marked as solved?

**Comment by blockmood** [comment]
![WechatIMG258](https://user-images.githubusercontent.com/22879524/236387093-38112278-1ea6-4e6b-a3b0-975319aa0d66.png)
How to solve it ？？

**Comment by Mystore0** [comment]
https://github.githubassets.com/assets/vendors-node_modules_github_filter-input-element_dist_index_js-node_modules_github_remote-inp-8873b7-5771678648e0.js  

this one
