### ISSUE TITLE
[Bug]: Ngrok failed to start the tunnel

### ISSUE THREAD

**Issue by devdarren7** [Shopify/cli#707]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Previously NPM run dev was working fine. Tried to upgrade to a later branch that the rest of my team was using and now I get the errors as if the Ngrok tunnel could not be launched but I have already authorised this and the commands work separately or with Shopify CLI 2.0 tunnel / serve commands in their own use cases so the problem should not be with Ngrok itself.

### Actual behavior

> jaya-app@1.0.0 dev
> shopify app dev

✔ Dependencies installed

Using your previous dev settings:
- Org:          DevDarren
- App:          jaya-app
- Dev store:    devdarren.myshopify.com
- Update URLs:  Not yet configured

To reset your default dev config, run npm run dev -- --reset

    Ngrok failed to start the tunnel
    Stack trace:
    at generateURL                @shopify/app/src/cli/services/dev/urls.ts:16  if (result.error === 'no-urls' || !result.url) throw new error.Bug('Ngrok faile…
    at processTicksAndRejection…  node:internal/process/task_queues:96

    at async dev                  @shopify/app/src/cli/services/dev.ts:66       frontendUrl = await generateURL(options.commandConfig, frontendPort)

    at run                        @shopify/app/src/cli/commands/app/dev.ts:74   await dev({``

### Reproduction steps

1.git clone project
2.Reinstalled node modules in new directory
3.NPM run gets stuck on tunnel generation 

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.1.0

### Shell

Bash

### Node version (run `node -v` if you're not sure)

v16.15 / v17.19.1

### What language and version are you using in your application?

v16.15 / v17.19.1

**Comment by devdarren7** [comment]
Hi I did try this but it didn't recognize the tunnel

**Comment by ocastx** [comment]
@devdarren7 I ran into the same issue and it was due to an outdated CLI version. I can see from your issue description that you're using CLI version 3.1.0. Could you please try to update to the latest version (3.21.0) using this command: 


```
npm run shopify -- upgrade
```
