### ISSUE TITLE
[Bug]: `shopify app dev` should update GDPR webhook URLs

### ISSUE THREAD

**Issue by tom-knight** [Shopify/cli#71]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

This is the same as [the issue](https://github.com/Shopify/shopify-cli/issues/2350) reported for Shopify CLI 2.0.

When you run `shopify app dev` it updates the App URL and Whitelist URLs with the new ngrok URLs in the Partner Dashboard but it doesn't update the mandatory GDPR webhook URLs.

### Actual behavior

The mandatory GDPR webhook URLs have the previous ngrok URL unless changed manually.

### Reproduction steps

1. Run `shopify app dev` or `npm run dev`
2. Check Partner Dashboard App Setup
3. Mandatory GDPR webhook URLs have not been updated

### Operating System

Arch Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.0.24 linux-x64 node-v16.13.0

### Shell

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Node version (run `node -v` if you're not sure)

v16.13.0

### What language and version are you using in your application?

PHP 7.4.29 (legacy app that doesn't work with PHP 8.x)

**Comment by pepicrft** [comment]
Hey @tom-knight. Apologies for this issue.
Do you mind sharing more information about what you experience as a developer when the GDPR URL is not set? I'd love to understand better why setting the base URLs is not sufficient.

**Comment by awd** [comment]
@pepicrft 

These (mandatory) GDPR webhooks are not registered through the app or cli, or associated to a shop access token. They added directly to the partner dashboard, and are dispatched (typically) after a shop has uninstalled. 

When ngrok changes the dev URL, these webhook URLs are either stale or out of date. Which means they will fail and kick off a procedure of Shopify trying to hit the URL over and over (then sending you emails, etc). 

So TLDR, setting the base url is not really how these GDPR hooks appear to be working. Would be great if they did use a single base url set on the app, and the allowed (auth) list, and GDPR list were based off of the base path instead.

Also these GDPR urls can be left blank for dev apps.. but usually better to have them to test in your dev environment. 

<img width="974" alt="Screen Shot 2022-07-11 at 1 14 10 PM" src="https://user-images.githubusercontent.com/65078/178320496-7f08b55c-5657-4c73-89e6-564666fa1488.png">
