### ISSUE TITLE
[Feature]: Named Tunnels

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#714]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

New feature

### Overview

I pay ngrok for extra features. I know that that is wrong to do on many levels. I know the ngrok team is spending the money I pay them on Lambos and drinks with umbrellas, but I don't care. They give me named tunnels! 

So I can name each and every one of my Apps with a named tunnel instead of these randomly assigned tunnels. 

I wish this CLI tool would let me provide a named tunnel and then work with ngrok to use my named tunnel. The reason this would be nice is simple. Every time I have to restart the dev with **yarn run dev** I would not get a new tunnel, I would just use my existing named tunnel. So clean! 

I know it is trivial. But I like this kind of clean. Is it possible? I think so. My Procfile.dev has a service listed for tunnels, where I just provide the named tunnel. My Rails App development environment has been trained to accept the named tunnel and I am off to the races. No troubles. 

### Motivation

I like to use the dot test domain name system with my App development. So my Shopify setup is not some random ngrok tunnel that changes all the time, but instead, I provide a reliable named tunnel and move on. I get it, this tool uses an API call to change the tunnel for me but that seems like trouble, more so than just settling on one name and re-using it. Who knows. 

But that is my motivation. To get this tool to be as nice as my old workflow, which in some respects totally sucks compared to the magic this tool does, but on the other hand, did things this tool cannot even apparently dream of, like named tunnels!

**Comment by Arkham** [comment]
You can provide your own tunnel by passing `--tunnel-url` to `yarn dev`. So if for example you have a named tunnel called `https://harris-speaker-four-gulf.proxy.com` that's mapped to your local `9292` port, you would write `yarn dev --tunnel-url=https://harris-speaker-four-gulf.proxy.com:9292`. In this way the CLI can understand the mapping between your named tunnel and the local port.

**Comment by resistorsoftware** [comment]
This does not work. I use puma-dev. So my tunnel is named with the .test domain. So I have myapp.test and in puma-dev I assign that a port, say 3150. So my ngrok tunnels with my Procfile.dev work perfect with something like this:

    tunnel: ngrok http --subdomain=myapp 3150 --log=stdout --log-level=info
    
In my Shopify App now, all I need to set is the App to go to https://myapp.test and it always works. But with your newfangled JS approach, this is busted, even though you offer the tunnel-url option. 

In my package.json my command fails to inform Shopify of the right tunnel, so things don't connect to the correct port with ngrok. 

` "scripts": {
    "shopify": "shopify",
    "build": "shopify app build",
    "dev": "shopify app dev --tunnel-url=https://myapp.test:3150",
    "push": "shopify app push",
    "generate": "shopify app generate",
    "deploy": "shopify app deploy",
    "info": "shopify app info"
  },`

What do you suggest I do here for this? I want to use my ngrok, and I want to use named tunnels. And I want them to be sent to ports of my choosing as per puma-dev. So how come the command fails with the port settings?

**Comment by artyrcheek** [comment]
Same issue here 🤔
