### ISSUE TITLE
[Feature]: Re-Think the Directory of Files Layout

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#715]
### What area(s) will this request affect?

Running your code locally

### What type of change do you want to see?

Substantial change to existing feature

### Overview

For no apparent reason, we have the root directory where we can run the commands such as 

     yarn run dev

Which brings up our App. But what if we want to use a console into our actual App code. If we spawn a new shell and it outputs a new shell for us, our muscle memory instinctively types out something like rails c to bring up a console. But alas, this is not to be, for we are not in the correct directly. We need to move to the **/web** directory to get things done. 

This is painful. Why is this? Who made this abomination? Would it have been too much to ask that we have one root and from there, get most work done without messing about with where we are exactly? 

### Motivation

I dislike having to **cd web** every single time I want to run a console on my App in a new shell.

**Comment by Arkham** [comment]
In order to support extensions work, the main app is stored inside the `web` directory. If you feel like you need to cd into the `web` directory often you can add your own shortcuts inside your `package.json`, for example:
```
  "scripts": {
    "console": "cd web && rails console"
  },
```
