### ISSUE TITLE
[Bug]: theme app extension not found

### ISSUE THREAD

**Issue by dweirich** [Shopify/cli#724]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

yarn dev should successfully start all services

### Actual behavior

Error is thrown saying that theme app extension cannot be found. If I remove the theme app extension from the extensions folder it starts correctly.

### Stack trace

```shell
error ───────────────────────────────────────────────────────────╮
│                                                                   │
│  command extension:serve:/Users/user/Work/app/extensions/  │
│  extension-theme not found                                         │
│                                                                   │
╰───────────────────────────────────────────────────────────────────╯
/Users/user/Work/app/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

AbortSilent [Error]
    at execCLI2 (file:///Users/user/Work/app/node_modules/@shopify/cli-kit/dist/node/ruby.js:46:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.action (file:///Users/user/Work/app/node_modules/@shopify/app/dist/cli/services/dev.js:125:13)
    at async file:///Users/user/Work/app/node_modules/@shopify/cli-kit/dist/private/node/ui/components/ConcurrentOutput.js:70:17
    at async Promise.all (index 2)
    at async runProcesses (file:///Users/user/Work/app/node_modules/@shopify/cli-kit/dist/private/node/ui/components/ConcurrentOutput.js:67:13) {
  tryMessage: null,
  type: 1
}
error Command failed with exit code 7.
```

### Reproduction steps

1. Generate an app using shopify-template-ruby
2. Generate a theme app extension
3. Run yarn dev

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.21.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.12.1

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by dweirich** [comment]
Figured out what was wrong with this one. The CLI was trying to install shopify-cli v2 using Ruby, but it was using the global version that rbenv had set instead of the ruby version of the project. Then it was trying to run the bundler from the project directory and only found shopify-cli v3 instead which has a different set of commands. Fixed it by setting the global ruby version to the project ruby version.

**Comment by isaacroldan** [comment]
Hi @dweirich, yes, CLI3.x still uses CLI2.x under the hood for some operations. Glad it's working already, closing this issue.
