### ISSUE TITLE
[Bug]: Theme: Cannot run `shopify theme dev` for one particular store

### ISSUE THREAD

**Issue by vfonic** [Shopify/cli#745]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

`shopify theme dev --store=asd` works

### Actual behavior

`shopify theme dev --store=asd` does not work

### Stack trace

<details><summary>Running `shopify theme dev --store=asd` output</summary>

```
┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ * Syncing theme #xxxxx on asd.myshopify.com
┃                                                                                                    100%
┃ 
┃ Serving .
┃ 
┃ Please open this URL in your browser:
┃ http://127.0.0.1:9292
┃ 
┃ Customize this theme in the Theme Editor, and use 'theme pull' to get the changes:
┃ https://asd.myshopify.com/admin/themes/xxxxxx/editor
┃ 
┃ Share this theme preview:
┃ https://asd.myshopify.com/?preview_theme_id=xxxxxx
┃ 
┃ (Use Ctrl-C to stop)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (14.54s) ━━
15:24:50 Synced » update assets/Comfortaa-Regular.woff
15:24:51 Synced » update assets/Comfortaa-Regular.woff2
15:24:51 Synced » update assets/Logo-white.svg
15:24:52 Synced » update assets/Logo.svg
15:24:54 Synced » update assets/Nunito-Bold.ttf
15:24:55 Synced » update assets/Nunito-ExtraBold.ttf
15:24:56 Synced » update assets/Nunito-Regular.ttf
15:24:57 Synced » update assets/Nunito-SemiBold.ttf
15:24:57 Synced » update assets/ajax-loader.gif
15:24:58 Synced » update assets/android-chrome-192x192.png
15:24:59 Synced » update assets/android-chrome-512x512.png
15:25:00 Synced » update assets/apple-touch-icon.png
15:25:02 Synced » update assets/da.png
15:25:03 Synced » update assets/favicon-16x16.png
15:25:04 Synced » update assets/favicon-32x32.png
15:25:04 Synced » update assets/fi.png
15:25:05 Synced » update assets/hero_slide_1.jpg
15:25:06 Synced » update assets/icons.eot
15:25:07 Synced » update assets/icons.svg
15:25:07 Synced » update assets/icons.ttf
15:25:09 Synced » update assets/icons.woff
15:25:11 Synced » update assets/img-bottom.png
15:25:12 Synced » update assets/img-top.png
15:25:12 Synced » update assets/info-circle-white.svg
15:25:14 Synced » update assets/lazysizes.min.js
15:25:14 Synced » update assets/jquery-2.2.3.min.js
15:25:15 Synced » update assets/modernizr.min.js
15:25:16 Synced » update assets/made-in-germany.png
15:25:17 Synced » update assets/nl.png
15:25:18 Synced » update assets/password-page-background.jpg
15:25:19 Synced » update assets/pinpoint.png
15:25:19 Synced » update assets/pl.png
15:25:20 Synced » update assets/sv.png
15:25:21 Synced » update assets/tlab-flags-da.png
15:25:21 Synced » update assets/tlab-flags-de.png
15:25:23 Synced » update assets/tlab-flags-fr.png
15:25:23 Synced » update assets/tlab-flags-fi.png
15:25:24 Synced » update assets/tlab-flags-nl.png
15:25:25 Synced » update assets/tlab-flags-pl.png
15:25:26 Synced » update assets/tlab-flags-pt-PT.png
15:25:27 Synced » update assets/tlab-flags-sv.png
15:25:28 Synced » update assets/tlab-flags-tr.png
15:25:28 Synced » update assets/translation-lab-language-switcher-floating.css
15:25:29 Synced » update assets/zendesk-embeddable.js
```
</details>

Everything looks good except that it doesn't work. :)

Couple of extra info:
1. It was working yesterday
2. I ran `shopify theme dev` (or `shopify theme dev --store=some-other-store`) by mistake in another project root and it started uploading theme files to "asd" store.
1. I deleted the previous development themes and that created a new development theme, but the page is still not working.
2. I tried in different browsers

<details><summary>Here's a screenshot</summary>

![Screen Shot 2022-11-08 at 15 32 46](https://user-images.githubusercontent.com/67437/200698568-caaef664-3ad3-412a-bca6-21885227d06b.jpg)

</details>

How can I investigate this? What can I do? I'm blocked and cannot do theme development now.

### Reproduction steps

1. `shopify theme dev --store=asd`

### Operating System

macOS Monterey 12.6

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.22.1

### Node version (run `node -v` if you're not sure)

v19.0.1

**Comment by shauns** [comment]
@vfonic there is a `--verbose` flag you can use

**Comment by vfonic** [comment]
Thank you @shauns!

I ran `shopify theme dev -s xxx --verbose` and saw that CLI is getting 500 response so I deleted all session/cookies for 127.0.0.1:9292 and it works now! No idea why I didn't try removing application/site data before.

Here's a bit of info that might be useful:

```
DEBUG Refreshing preview _secure_session_id cookie
DEBUG Proxying HEAD https://xxx.myshopify.com/?preview_theme_id=133577244940&_fd=0&pb=0
DEBUG `-> 302 request_id: 7e122528-b474-4776-acb0-f453eebf68f0
DEBUG Proxying GET https://xxx.myshopify.com/?_fd=0&pb=0
DEBUG `-> 500 request_id: 2d5dd8f9-1fbe-4a39-abfb-578bca584e3f
```

The myshopify url is changed, but theme ID and request ID are correct.

**Comment by mgmanzella** [comment]
Hi @vfonic, glad to hear you were able to resolve your issue! To confirm how you got into this state I wanted to clarify this step you listed:

> I ran shopify theme dev (or shopify theme dev --store=some-other-store) by mistake in another project root and it started uploading theme files to "asd" store.

You ran `shopify theme dev --store=some-other-store`, the CLI didn't listen to your `--store` param and it started uploading to `asd.myshopify.com`?

Thanks!

**Comment by vfonic** [comment]
No, the `--store` param was respected, but I ran the command in the wrong project root.

So it was one of these two scenarios:

1)

```sh
/project_a > shopify theme dev --store=project_a
Ctrl^C
/project_a > cd ../project_b
/project_b > shopify theme dev
```


2)

```sh
/project_b > shopify theme dev --store=project_a
```

**Comment by mgmanzella** [comment]
Closing this issue because it's resolved, thanks again for reporting!
