### ISSUE TITLE
[Bug]: Error: connect ECONNREFUSED 127.0.0.1:<PORT> when restarting app

### ISSUE THREAD

**Issue by wisniewski94** [Shopify/cli#750]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

nodemon should restart app normally

### Actual behavior

When running npm run dev (which runs shopify app dev) app does not restart when encounters the issue.

Somehow adding error callback to proxy.web() helps. Error still occurs but nodemon does not break.

```js
            return proxy.web(req, res, { target }, (err) => {
                console.log('Error forwarding request', err);
            });
```

### Stack trace

```shell
2022-11-09 10:32:43 | frontend   | [nodemon] restarting due to changes...
2022-11-09 10:32:43 | frontend   |
2022-11-09 10:32:43 | frontend   | [nodemon] starting `node server.js`
2022-11-09 10:32:43 | frontend   |

/Users/username/Documents/web/project/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: connect ECONNREFUSED 127.0.0.1:54284
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 54284
}
```

### Reproduction steps

1. using npm run dev command start the project in dev mode
2. throw an error somewhere in the app (ideally it should be some unexpected error)
3. you should get the same stacktrace

### Operating System

MacOS Monterey 12.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.22.1

### Shell

/bin/zsh

### Node version (run `node -v` if you're not sure)

v16.14.2

**Comment by ozzyonfire** [comment]
Having the same issue as you.

nodemon version is 2.0.20
cli version: 3.22.0

I'm trying to set up a typescript project which uses nodemon to automatically restart the server when a change is detected in the dist folder. 

Every time nodemon wants to restart, it crashes and I get the same error:

```
2022-11-11 15:21:15 | frontend | [nodemon] restarting due to changes...
2022-11-11 15:21:15 | frontend |

C:\Users\username\Development\ec\shopify\shopify-test-app\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
error Command failed with exit code 7.
```

**Comment by wisniewski94** [comment]
When the server crashes it tries to reinitialize itself of the same port but it gets ECONNREFUSED or ECONNRESET which means:
- ECONNREFUSED - there is a server running on that port and node tried to initialize a new one
- ECONNRESET - there was a server running on that port but it's being reset right now

I have no idea why logging that error in proxy.web helps to keep node up -> maybe it's like unexpected error handling.

Either way sounds like a race of who's first -> terminator or initiator. But I am just thinking out loud, hoping to get some attention around this issue
