### ISSUE TITLE
[Bug]: When asked to connect to a development store, the list contains non-development stores

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#756]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

When being prompted to connect an App to a development store, I would expect the list I get to scroll through contains just my development stores.

### Actual behavior

I am presented with a long non-sorted list of all the stores I have in my partner account, managed and development. That is pretty useless to me as the connection is ONLY ever going to work on a development store, so just show me those please. 

### Reproduction steps

1.
2.
3.

### Operating System

Mac OS 

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.15

### Shell

ZSH

### Node version (run `node -v` if you're not sure)

v18.11

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by Arkham** [comment]
hey @resistorsoftware, thanks for your report, this should be fixed on the latest version of the CLI.
