### ISSUE TITLE
[Enhancement] Introduce the `-f`/`--force` flag as a pattern for confirmation dialogues in the whole CLI

### ISSUE THREAD

**Issue by Poitrin** [Shopify/cli#760]
In CLI 2.x, the two existing confirmation dialogues (`ConfirmStore.ask`) for `theme publish` and `theme delete` both support the `--force` flag to automatically answer yes (which can potentially be helpful for e.g. CI/CD).
https://github.com/Shopify/shopify-cli/pull/2680 adds another confirmation dialogue to ask the user whether directories not looking like theme directories shall be `serve`d/`push`ed/… nevertheless.
As a discussion arose whether `--force` is a suitable name ([see discussion](https://github.com/Shopify/shopify-cli/pull/2680/files#r1017721847)), it shall be decided in this issue, and the `--force` flag stays hidden in the meantime.

Pinging @MeredithCastile to get her UX input here :)

**Comment by Poitrin** [comment]
DX team still evaluating if pattern shall be adopted.
As soon as decision has been taken, flag will be renamed or unhidden.

**Comment by illarionvk** [comment]
A lot of other tools have a `--ci` flag, as it defines a more explicit behavior than `--force`:

- Assume yes for non-critical warnings and questions
- Fail fast on errors and critical warnings

**Comment by Poitrin** [comment]
Issue still active.

**Comment by MeredithCastile** [comment]
Apologies for missing this issue. For CI/CD, I see the value of having a --force or --quiet flag correspond to a "yes" option in the confirmation prompt.

For deployment, Tom Newton recommended that we use --quiet (not --force) as the flag to bypass prompts. Curious how the team understands when to use `force` versus `quiet`. This is, possibly a question for you, @gfscott. cc: @stephszeto. 

(Note: we can update the [commands docs](https://github.com/Shopify/cli/blob/main/docs/cli-kit/command-guidelines.md) to include this note about force versus quiet.)

**Comment by jessehoek** [comment]
I've also seen that in many other CLIs, `--quiet` suppresses output. (Although interestingly [gcloud](https://cloud.google.com/sdk/gcloud/reference#--quiet) uses it to disable prompts and use defaults, if possible.) But I agree that a separate flag that accepts defaults would be more clear. 

I've looked into several other CLIs to see how they handle this and there seem to be a variety of flags used. Some examples:
- Vercel: `--yes`
- yarn install: `--non-interactive`
- fly.io: `--auto-confirm` 
- Jest: `--ci`

I don't have a strong opinion on which of these flags works best for us, but agree that `quiet` has other meaning.

@MeredithCastile thoughts?

**Comment by MeredithCastile** [comment]
Belated thanks, @gfscott. And thanks, @jessehoek, for the subsequent research.

What I'm hearing is that --force is most certainly not the right command. As Graham says, it's for:
> a potentially destructive action (i.e. deleting or overwriting data) where the default is to prompt for confirmation or bail without finishing

But I'm also hearing that we _might_ want to reserve --quiet as the opposite of --verbose. In the case of deployment, we need the flag to convey that you're suppressing output in effect and that the mechanism for doing so is telling the system to use the defaults you set. It's arguably different in nature from just "not verbose."

We'll want this flag for something other than CI or non-interactive scenarios. So I'm wondering if "--auto-confirm" would be best from the options we've explored so far.

@tdonia, curious if "--auto-confirm" is something that sounds okay to you. cc: @tomnewton, since this point came up in the GSD review.

**Comment by amcaplan** [comment]
I think `--yes` is a very strong convention in Unix-land. It comes from the [`yes` utility](https://en.m.wikipedia.org/wiki/Yes_(Unix)) which pipes an endless string of yeses into another program. This is how you install on CI, docker, etc. in any Linux system (as in `sudo apt-get install -y...`) and I think it would be the most familiar pattern for developers.

On the other hand, `--quiet` is traditionally about suppressing outputs, not inputs.

`--ci` is pleasantly declarative but I'm not sure it really communicates intent to skip all safeguards.
