### ISSUE TITLE
[Bug]: NodeJS hangs around when closing main process?

### ISSUE THREAD

**Issue by ozzyonfire** [Shopify/cli#767]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

When you close the process started from the CLI, all Node processes should be cleaned up and closed as well.

### Actual behavior

After closing the CLI, a couple Node JS processes hang around. After restarting the CLI multiple times, (because I kept getting errors related to nodemon and #750). These extra processes build up. 

Actually, when using Yarn, there are two processes that stick around during initialization, but with NPM run commands they close out earlier.

### Reproduction steps

1. npm run dev (or yarn dev)
2. Open a Task Manager and view the subprocesses
![image](https://user-images.githubusercontent.com/779491/201430284-a9afbe7e-f33f-4c95-b41c-19a2d07426f4.png)
3. Close the cli using Ctrl+C and check subprocesses again
![image](https://user-images.githubusercontent.com/779491/201430436-b7ecce14-aa76-4c44-86e7-784e04a9a59f.png)
4. If you restart the CLI again, notice a compounding of Node.Js runtimes
![image](https://user-images.githubusercontent.com/779491/201430637-78c8be3e-624d-4667-a2f3-d6a70cf7fcf3.png)

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.22.1

### Shell

Powershell

### Node version (run `node -v` if you're not sure)

16.15.1

**Comment by wisniewski94** [comment]
So when you hit CTRL+C the CLI will stop all of its processes (ngrok, backend, frontend ?). But because we are getting unexpected error, these are not being closed properly. On Mac each time I have to find the process running at 9292 port and kill it and use killall ngrok command. Basically this is a side effect of #750

**Comment by isaacroldan** [comment]
Hi @ozzyonfire, thanks for reporting this issue, i'll pass it to the team to investigate.
