### ISSUE TITLE
[Bug]: Unable use connect Shopify store from CLI with a  development stores even though I am the owner 

### ISSUE THREAD

**Issue by yinnonn** [Shopify/cli#776]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I should be able to login successfully into my development store through the CLI.

### Actual behavior

Whenever I run `yarn dev` it looks like the session runs fine:
- Opens a port 
- Creating ngrok sharable url 
- Starting node server 

But suddenly after a few seconds it throws this error: 
```
Error You can't use Shopify CLI with development stores if you only have Partner staff member access. If you want to use Shopify CLI to work on a development store, then you should be the store owner or create a staff account on the store.

If you're the store owner, then you need to log in to the store directly using the store URL at least once (for example, using avicarousel.myshopify.com/admin) before you log in using Shopify CLI. Logging in to the Shopify admin directly connects the development store with your Shopify login.

error Command failed with exit code 1.
```

What I already try:
- Logging out using the CLI 
- Creating another dev stores
- Reset all cache (as the 24/7 support suggested)

I can login into old development stores, and they are also appear here:
https://accounts.shopify.com/store-login

The newer stores are not in the store-login list so maybe it has a connection with that. 

### Reproduction steps

1. `yarn dev --reset`
2. selecting the store

### Operating System

MacOS Monerey

### Shopify CLI version (check your project's `package.json` if you're not sure)

@shopify/cli/3.16.3

### Shell

iTerm2

### Node version (run `node -v` if you're not sure)

node-v14.17.6

### What language and version are you using in your application?

Node v14.17.6

**Comment by sheshankdebugged** [comment]
I'm also facing the same issue. Till yesterday everything is working fine but today I am unable to serve my Shopify theme code. I have also tried to update and uninstall the Shopify CLI but still not able to fix this issue.

```
npm WARN enoent ENOENT: no such file or directory, open 'D:\Projects\package.json'
npm WARN Projects No description
npm WARN Projects No repository field.
npm WARN Projects No README data
npm WARN Projects No license field.

+ @shopify/cli@3.23.0
updated 1 package and audited 1278 packages in 3.729s

112 packages are looking for funding
  run `npm fund` for details

found 20 vulnerabilities (11 moderate, 9 high)
  run `npm audit fix` to fix them, or `npm audit` for details
PS D:\Projects\tony\dawn> shopify theme serve
PS D:\Projects\tony\dawn> 
```

**Comment by isaacroldan** [comment]
Hi @yinnonn , When you create a development store, the owner of that store is not by default your partner account.
You'd need to go to the store settings -> users and permissions -> and invite your partner account as staff member of the store.

Let me know if that helps!

@sheshankdebugged, that seems like a different issue. Take into account that from CLI3.x, the correct command is `shopify theme dev` not `serve`

**Comment by yinnonn** [comment]
> Hi @yinnonn , When you create a development store, the owner of that store is not by default your partner account. You'd need to go to the store settings -> users and permissions -> and invite your partner account as staff member of the store.
> 
> Let me know if that helps!
> 
> @sheshankdebugged, that seems like a different issue. Take into account that from CLI3.x, the correct command is `shopify theme dev` not `serve`

Unfortunately it cannot be done since the user that owns the store has the same email address
<img width="464" alt="image" src="https://user-images.githubusercontent.com/10031714/201930255-915cc0dd-4c6a-4f97-b22b-6010272dc39a.png">

**Comment by tourfifty** [comment]
I had the same problem. Fixed it by running in terminal

`shopify theme dev --store https://yoururl.myshopify.com`

For some reason the default login doesn't seem to connect to your store with all the correct permissions. You have to specify the store URL.

Hope that helps.
