### ISSUE TITLE
[Bug]: `shopify theme dev` stops after an hour and a half

### ISSUE THREAD

**Issue by diegovogel** [Shopify/cli#781]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When I run `shopify theme dev` I expect it to run as long as my computer is awake.

### Actual behavior

When I run `shopify theme dev` it will only run for about an hour and a half before stopping. And when I restart it I _always have to log back in_. I'm assuming the `theme dev` command stops because I'm getting automatically logged out. I'm not sure if this is a bug or a feature but it's annoying.

### Reproduction steps

1. Run `shopify theme dev`.
2. Wait about an hour and a half for it to stop.

### Operating System

macOS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.23.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v15.14.0

**Comment by diegovogel** [comment]
Thanks @habibly. We recently upgraded from 2.x to 3.x because [the docs seem to encourage that](https://shopify.dev/themes/tools/cli/migrate). But I see what you're saying about the repo suggesting otherwise. @isaacroldan can you clarify what should be used for theme dev?

**Comment by isaacroldan** [comment]
Yes, CLI 3.x is the recommended tool for themes. We are actively working on solving this and other theme issues, i'll update this issue when we have a fix.

That message from the CLI 2.x repo is outdated, i'll make sure we update that doc soon.

**Comment by notrealdev** [comment]
same here, stops after an hour and a half
need more time pls.

**Comment by notrealdev** [comment]
There a timeset called ThemeRefreshTimeoutInMinutes in the Shopify auth using the CLI to authenticate to a store, its 90 minutes, this really need to change as soon as possible or add the --password flag to use the token generated by the theme Access App.

Check here: https://github.com/Shopify/cli/blob/main/packages/theme/src/cli/commands/theme/dev.ts

**Comment by diegovogel** [comment]
Just updated to v3.28.0 and it's fixed! After 2 hrs I'm still logged in. Thank you @isaacroldan!
