### ISSUE TITLE
[Feature]: Bring back functionalities of Themekit

### ISSUE THREAD

**Issue by StickyMallrat** [Shopify/cli#794]
### What area(s) will this request affect?

Function, Theme, Deployment

### What type of change do you want to see?

New feature

### Overview

The great thing about themekit was, that it could be used programmatically in a script, because you could login via private app. With the cli, you always have to login with a browser, which makes it impossible to run on a worker for deployments or setting automation. We used this heavily in our company with sometimes more than 10 stores sharing one theme-codebase and now we can't since switching to dawn. 
Themekit would also allow us to upload single files to a theme instead of pushing the whole thing which is super important since logic and data are so tightly bound in the architecture anyway. Managing quick bug-fixes on a live store has become much more dangerous.
The github integration is great, but no replacement of the fine-grained control themekit allowed for.
Also the 3.0 version of the cli is missing features of the previous version, which is a bummer...for example quickly loging in to another store from the cli is just not possible anymore...

### Motivation

We used themekit heavily in our stores, especially in scripts running on cronjobs for various tasks like deployment and managing settings. We can't do any of that anymore with the new cli...

**Comment by shauns** [comment]
Hi @StickyMallrat 

You can run the CLI's theme commands in a CI/CD / Scripting environment if you like. https://shopify.dev/themes/tools/cli/ci-cd#step-2-integrate-shopify-cli-into-your-pipeline and `SHOPIFY_CLI_THEME_TOKEN` are what you need. It uses the same theme access app that you're familiar with 👍 

I'll pass on the suggestions for the other points -- as you're away themekit has been discouraged for new work for quite a while.

**Comment by karreiro** [comment]
Hi @StickyMallrat,

Thanks for sharing that context!

The CLI was not ideal for use cases involving many stores, indeed. However, we've recently introduced support to [Theme Access](https://shopify.dev/themes/tools/cli/ci-cd#step-1-get-a-theme-access-password-for-the-store) passwords, so we may execute commands like this now:

```
shopify theme push \
--only sections/announcement-bar.liquid \
--theme <your theme> \
--store <your store> \
--password <theme access password>
```

Instead of `sections/announcement-bar.liquid`, we may use other patterns like `sections/*` to upload all files in the section directory.

As I've mentioned, those features are a bit new in the CLI. Also, as it seems like the latest CLI version is covering the scenarios this issue reports, I believe we may leave it closed. Still, please, don't hesitate on re-opening if we're missing something.

Thanks again for reporting it!

**Comment by bakura10** [comment]
Hi @karreiro ,

I have tried to use this Theme Access feature. Unfortunately, it does work for the dev command. I could see that the --preset feature that used to not work now work... but now it's the theme access that does not work.

Shopify is adding a lot of features but, so far, we're still not having something working properly for the even most basic use case, which is kinda frustrating to be honest. Is there some plan to bring the password to the dev command as well?

**Comment by karreiro** [comment]
Hi @bakura10,

That’s correct. Currently, authentication via Theme Access is not supported in the `theme dev` command. However, the work for this is in progress.

We’ve decided to release partial support to commands like the `theme push` and `theme pull` as they are more frequently used in the CI/CD workflows, so developers could already benefit from that feature.

Still, we understand that supporting the `theme dev` command is crucial indeed. As soon as we release this feature, I will leave an update here and we're going to include the `--password` flag [here](https://shopify.dev/themes/tools/cli/commands#dev).

Thanks for sharing the perspective, @bakura10.

**Comment by bakura10** [comment]
Thanks a lot @karreiro , glad to hear this is on the roadmap :)

**Comment by bakura10** [comment]
Additionally @karreiro , it seems the --password option is not supported for the push command. Here is my `shopify.presets.toml` file:

```
[demo]
password = "XXX"
theme = "YYY"
path = "./dist"
store = "xyz.myshopify.com"
```

When running the command : ```theme push --preset demo``` it still asks me to login using the browser instead of using the password.

preset work properly for the dev command so this create a somewhat very inconsistent experience between commands here.

**Comment by bakura10** [comment]
Thanks for adding this in 3.29 @karreiro, this works like a charm. One minor thing: this --preset feature is completely undocumented (https://shopify.dev/themes/tools/cli). It is extremely useful when working with multiple developers, this should defiitely deserve some doc love :)

**Comment by amcaplan** [comment]
That's right, @karreiro! It was introduced as a prototype for internal testing, and intentionally not documented (and the `--preset` flag is hidden on purpose as well). I wouldn't build on it, as at this point it's definitely going to change.

I will also say that we have a task in the next couple of cycles to implement something resembling presets, but it'll look different from what exists now, and presets as they are will go away. Hopefully it'll be better!

We're well aware that for all its flaws, ThemeKit had some great features, and those are still missed in CLI 2.0/3.0. We are first making sure the foundation is as solid as possible, but we definitely want to bring back some of those awesome features so you can get the best of both worlds.
