### ISSUE TITLE
[Bug]: 'No shop provided' error on run

### ISSUE THREAD

**Issue by joshuaiz** [Shopify/cli#841]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

After installing the CLI, logging in to my Partners account, connecting my app + development store, the local development app should load on `pnpm run dev`.

### Actual behavior

Local app does not load with the url provided. Please see the following screenshots showing the url and then the error in the browser:

<img width="750" alt="CleanShot 2022-11-29 at 21 35 16@2x" src="https://user-images.githubusercontent.com/1096738/204838722-92cbd976-dcd7-4ba5-b7a8-9282f12b1687.png">

![CleanShot 2022-11-29 at 21 35 30@2x](https://user-images.githubusercontent.com/1096738/204838755-26fff1bb-2768-4b71-8831-6b9fc39adbf2.png)

### Reproduction steps

1. Install the Shopify app CLI with pnpm
2. Log in to my Partners account
3. Connect my development store
4. Install the app into the development store
5. Run the local development app with `pnpm run dev`

^^ these are all the steps outlined in the docs here: https://shopify.dev/apps/getting-started/create

My understanding is the CLI should handle the connection to your Partners account and development store automatically. That is seemingly not happening here.

I'm dead in the water until I can get around this.

### Operating System

macOS Ventura 13.0.1

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.23.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

19.1.0

### What language and version are you using in your application?

Node 19.1.0

**Comment by amcaplan** [comment]
Hi @joshuaiz, I think there's some confusion here related to the correct URL. If you want to preview your app, look for text like this:

```
Shareable app URL

  https://your-tunnel.ngrok.io?shop=your-shop.myshopify.com&host=somelongstringlikemxyzptlk
```

That's the link you want to hit. The other output is coming from tools that the CLI is orchestrating, which we pass on to you. We might consider changing the default level of our logging tools.

However, bottom line for you is to click a different link.

Please confirm this solves your difficulty.

**Comment by joshuaiz** [comment]
Hey @amcaplan thanks for the reply. 

Yes I can view the app in the store this way but is there no way to work locally with hot reloading?

And yes the output from the CLI is a bit confusing.

**Comment by ahorner1117** [comment]
Why is this issue closed there was no resolution
