### ISSUE TITLE
[Bug]: yarn run info bugs out

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#845]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should have worked

### Actual behavior

![Untitled 3](https://user-images.githubusercontent.com/123307/204889978-eb4c9cc6-dcd0-43fb-836e-5d6c84562a51.png)

### Stack trace

```shell
yarn run info --web-env
yarn run v1.22.19
$ shopify app info --web-env
✔ Which Partners organization is this work for? · 

━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

      The Partners GraphQL API responded unsuccessfully with the HTTP status 200 and errors:

      [
      {
        "message": "Unexpected system error",
        "extensions": {
          "code": "500"
        }
      }
    ]


    Stack trace:
    at                            graphql-request/src/index.ts:410      throw new ClientError(
    at step                       graphql-request/dist/index.js:63      op = body.call(thisArg, _);
    at next                       graphql-request/dist/index.js:44      function verb(n) { return function (v) { return step([n, v]); }; }
    at fulfilled                  graphql-request/dist/index.js:35      function fulfilled(value) { try { step(generator.next(value)); } catch (e) { re…
    at processTicksAndRejection…  node:internal/process/task_queues:95

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction steps

1.
2.
3.

### Operating System

Mac OS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.15

### Shell

Warp

### Node version (run `node -v` if you're not sure)

V18

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by amcaplan** [comment]
If that doesn't work, can you please run again with the `verbose` flag and send us the `X-Request-Id` header for the failed request?

**Comment by resistorsoftware** [comment]
@amcaplan I appreciate the sentiment. I totally understand that Shopify cannot be expected to function correctly 100% of the time and that we will have 500 errors on occasion when accessing it. I think we all agree that error handling in JS is less than stellar, and again, nothing we can do about it. The choice was made to use JS for tooling, something it is mediocre for at best, but there is no use in crying over spilled milk, right? 

It is true that one day the CLI may be considered great! I am one who for sure awaits the day. I understand the struggle is real. JS is a language that the crowd tolerates and sometimes even loves, but rarely admit that it can be a major source of frustration too.
