### ISSUE TITLE
[Bug]: Shopify theme init --clone-url

### ISSUE THREAD

**Issue by polidario** [Shopify/cli#850]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The expected behavior should be to clone the right repository provided to the `--clone-url` flag.

### Actual behavior

It clones the repository of the Shopify theme Dawn.

### Reproduction steps

1. Execute the command `shopify theme init --clone-url https://github.com/polidario/Elizabeth_Clone`
2. Enter the name of the theme project
3. There you'll see it's still cloning Dawn instead.

### Operating System

Mac OS and Windows

### Shopify CLI version (check your project's `package.json` if you're not sure)

Shopify CLI 3.23.0

### Node version (run `node -v` if you're not sure)

v18.12.1

**Comment by amcaplan** [comment]
Thanks @polidario for opening an issue. I'm glad to be the bearer of good tidings today... this has been handled in the latest release of the CLI. Install 3.24.1 and enjoy the fix!
