### ISSUE TITLE
[Bug]: Not able to run npm run dev on CLI 3.0

### ISSUE THREAD

**Issue by Andi365** [Shopify/cli#851]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

App should spin up a local env with `npm run dev`

### Actual behavior

I use the `npm run dev` command CLI ask me to login to store. The commands crashes, saying I dont have access to the dev store

### Stack trace

```shell
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Looks like you need access to this dev store (<store>                 │
│  (​https://<store>.myshopify.com​))                                    │
│                                                                              │
│  • Log in to the store directly from this URL                                │
│  (​https://<store>.myshopify.com/admin​). If you're the store owner,   │
│  then that direct log in should solve your access issue.                     │
│  • If you're not the owner, create a dev store staff account for yourself.   │
│  Then log in directly from the link above.                                   │
│                                                                              │
│                                                                              │
```

### Reproduction steps

New project and have followed [this guide](https://shopify.github.io/workshops/codelabs/checkout-ui-custom-field/index.html?index=./workshops&viewga=G-86JJCZ26ZM#1). 

1. `npm init @shopify/app@latest` 
2. cd into project
3. `npm run dev` - everything works
4. `npm run generate extension` -> checkout extension
5. `npm run dev` - now crashing

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.24.1

### Shell

Hyper

### Node version (run `node -v` if you're not sure)

v18.12.1

### What language and version are you using in your application?

Node

**Comment by dani-sanomads** [comment]
Facing Same Issue . I triedd updating the shopify and shopify-cli but still facing it:
npm: 8.1
node: 16.0 , 18.0
terminal: iTerm
OS: Mac

**Comment by amcaplan** [comment]
Glad to hear this is cleared up, @Andi365! Closing the issue.
