### ISSUE TITLE
[Bug]: Deploy theme app extension unattended e.g. in CI 

### ISSUE THREAD

**Issue by chrisntb** [Shopify/cli#859]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

This command should deploy our theme app extension using the latest version of "@shopify/app" v3.24.1

```shell
shopify app deploy
```

### Actual behavior

This command does not deploy our theme app extension using the latest version of "@shopify/app" v3.24.1

```shell
shopify app deploy
```

### Stack trace

```shell
This command successfully deploys our theme app extension using these versions of "@shopify/app" v3.10.0, v3.16.0, v3.18.0.


shopify app deploy


When using v3.19.0 "@shopify/app" or higher the following question is asked and because the deployment is happening in CI we cannot answer it:

...
The CLI prompted in a non-interactive terminal with the following questions:
Deploy *** theme app extension (local name) as theme-app-extension (name on Shopify Partners, ID: 8******1)?
Yes, that's right
No, cancel deployment
...
```

### Reproduction steps

1. Using a CI system for an unattended theme app extension deployment, we use CircleCI
2. Use "@shopify/app" v3.18.0 and the theme app extension deploys successfully using the command 'shopify app deploy'
3. Use "@shopify/app" v3.19.0 or v3.24.1 and the theme app extension does not deploy using the command 'shopify app deploy', instead it hangs asking to confirm deployment
4. Note CI=true is set in the environment

### Operating System

CircleCI Debian Linux

### Shopify CLI version (check your project's `package.json` if you're not sure)

v3.24.1

### Shell

bash

### Node version (run `node -v` if you're not sure)

18.12.1

### What language and version are you using in your application?

Node 18.12.1

**Comment by matteodepalo** [comment]
Hi @chrisntb, thank you for opening this issue. The team is aware of the inability to run certain commands in non interactive environments and will be working on a solution. I'm going to close this issue as it's being already [tracked internally](https://github.com/Shopify/internal-cli-foundations/issues/474).
