### ISSUE TITLE
[Bug]: `shopify theme dev` not working with development stores

### ISSUE THREAD

**Issue by Alexa-Green** [Shopify/cli#866]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

Running `shopify theme dev` should sync the theme to store and provide a live preview at `127.0.0.1:9292`

### Actual behavior

The "Syncing theme" freezes at a random amount each time and never fully uploads. The first time it will maybe get to around 50%, but if you abort it and try again it will get stuck at 1% and never go past it.

This is happening on a development store. I had run `shopify theme dev` around a time when the CLI was having issues and think those changes might be cached somewhere. On the same machine/CLI version, it is NOT happening when syncing to a store that is in production (for which I had not run the CLI for). Not sure if the development vs. production store has anything to do with it.

### Reproduction steps

1. Run `shopify theme dev --store https://DEVELOPMENT_STORE.myshopify.com` in a theme directory, and be sure to use a development store (e.g. password protected/created through partners dashboard)
2. Log in to the CLI when requested
3. Note that the CLI will start Syncing theme, but it will get stuck and never continue.
4. Try aborting it and trying again.
5. Note that the CLI will get stuck on 1% syncing theme and never continue

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.23.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.12.1

### What language and version are you using in your application?

None, it is a theme so liquid

**Comment by octipus** [comment]
are you running `shopify theme dev ` in a shopify theme folder? I normally get your explained behaviour if i run the command outside of a theme folder.

**Comment by Alexa-Green** [comment]
@octipus Yes, running it in a theme folder. It had been an Online Store 1.0 theme and am converting it to Online Store 2.0-- could that be part of the problem?

Also tried creating a fresh development store and the same issue happens.

**Comment by Poitrin** [comment]
I tried to reproduce the bug with a development store (`shopify theme dev --store=… --path=…`)
Initially, I also experienced a freezing CLI, which unfreezed after around 25 seconds. I took a look at the theme folder I wanted to sync, and saw that I had irrelevant files (the whole theme in a subfolder, in my case) in the directory.

So when you said …

> It had been an Online Store 1.0 theme and am converting it to Online Store 2.0-- could that be part of the problem?

… I was wondering if you have some hidden but irrelevant files in the directory, which would take ages to be uploaded?

If not, can you try with a fresh theme, by executing the following steps?
1. `shopify theme init`: Init a new theme, give it a name, e.g. `draft-theme`
2. `shopify theme dev --path="./draft-theme" --store=<your dev store>`

Does CLI still freeze?

**Comment by timdmackey** [comment]
I ran into this issue today on version `3.44.1` of the CLI. When invoked `shopify theme dev`, it would hang completely, not even showing me a progress bar.

I did some experimenting, and other commands like `shopify theme check` worked. Tried restarting my computer, but that didn't help.

What finally fixed it was logging out of the CLI using `shopify auth logout`, and then logging back in again. The theme dev command started working immediately after that.

**Comment by osama2kabdullah** [comment]
Hey @timdmackey . My CLI version is the same as yours. I facing an error. when run `hopify theme check` or `shopify theme dev`. The error-

![shopify-error](https://user-images.githubusercontent.com/109265357/229551956-bf52ee92-af61-4db7-aafc-2c326bbf38f0.png)

How can I resolve it? It says to me to grant permission. How enable permission?

**Comment by tiwarishikesh** [comment]
<img width="588" alt="image" src="https://github.com/Shopify/cli/assets/28214740/a10439b2-5656-4bd4-b5b6-4acaaa5089bb">
Facing Same issue.

This is my first Shopify experience. Any solutions are appreciated.

Tried logging out and logging in
Also tried making a new project

**Comment by renzonj** [comment]
I encountered the same error, but try the command below

shopify theme dev --store {store-name}

**Comment by syedsimanta03** [comment]
Can't shopify fix it?
