### ISSUE TITLE
[Feature]: Limit/grant access to specific themes

### ISSUE THREAD

**Issue by dungle-scrubs** [Shopify/cli#872]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

New feature

### Overview

When using Shopify CLI and deploying a theme to a non-active, but technically "live" theme, is it possible to prevent access to all but one theme?

I'm asking because when working in a shop with many themes, I get nervous about accidentally clicking on a different inactive theme than the one I'm intending.

It's far less likely to overwrite the current active theme, because there's an additional prompt, but for inactive themes, there are no prompts.

Or at least, having a prompt for all of them?

### Motivation

Fear.

**Comment by karreiro** [comment]
Thank you for raising this issue, @dungle-scrubs!

I believe that this proposal would also impact the theme library in the Admin, it that correct?

Thanks again for sharing this idea!

**Comment by dungle-scrubs** [comment]
@karreiro, you're welcome. Yes I believe it would.
