### ISSUE TITLE
[Bug]: Interactive prompt about usage and error reports prevents CI step from finishing

### ISSUE THREAD

**Issue by natebennett21** [Shopify/cli#888]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

The `shopify theme push` command should deploy a theme without following-up with an interactive prompt. Or, an environment variable could specify that the environment is a non-interactive CI/CD environment, telling the Shopify CLI to not bother with interactive prompts.

### Actual behavior

While the actual deploy works, the interactive prompt `Automatically send anonymized usage and error reports to Shopify?` prevents the deployment step from finishing from the CI/CD platform's perspective (CircleCI in my case). Eventually, the deployment step times out and the CircleCI job fails.

<img width="1144" alt="Screen Shot 2022-12-09 at 1 34 06 PM" src="https://user-images.githubusercontent.com/68073609/206794891-913c1a17-b429-4d73-a485-de735685d9ef.png">

Note: I tried using the [usage environment variable](https://shopify.dev/apps/tools/cli#usage-reporting) `SHOPIFY_CLI_NO_ANALYTICS=0` to see if that would prevent the CLI from prompting about the usage and reports question, but this didn't have any effect.

### Stack trace

```shell
N/A
```

### Reproduction steps

1. Use CI/CD platform (I use CircleCI) to install the Shopify CLI and its dependencies. Note, CI=true is a built-in environment variable in CircleCI.
2. Run `shopify theme push` to attempt deploying a theme. The theme will deploy successfully, but the CI/CD job ultimately fails since the shell hangs, waiting for a response for the interactive prompt.

### Operating System

Ubuntu 22.04

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.25.0

### Shell

bash

### Node version (run `node -v` if you're not sure)

v19.1.0

### What language and version are you using in your application?

Ruby 3.0.2p107, Node 19.1.0

**Comment by gonzaloriestra** [comment]
Hi! Sorry for the delay.

Could you try adding the environment variable `SHOPIFY_CLI_TTY=0`?

**Comment by natebennett21** [comment]
That worked! Thanks so much. I'll close this out 🤘🏻

**Comment by gonzaloriestra** [comment]
@shainaraskas what about suggesting the use of this env var (`SHOPIFY_CLI_TTY=0`) in the CI/CD documentation for themes?

**Comment by xgqfrms** [comment]
> Hi! Sorry for the delay.
> 
> Could you try adding the environment variable `SHOPIFY_CLI_TTY=0`?

which environment variable, local or global?

If I set this in my `.env` file will it work?

**Comment by natebennett21** [comment]
If your CI/CD pipeline has access to your `.env` file, I think it would work but I haven't tested that myself. For our project, we were using CircleCI to run these Shopify CLI commands, so I put the variable in our [project's environment variables](https://circleci.com/docs/set-environment-variable/) on the CircleCI web app.
