### ISSUE TITLE
[Bug]: Auto-open timed out.

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#894]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should have auto-opened a browser window.

### Actual behavior

It opened a browser window but failed to switch focus to the browser window like it used to. That is a jarring experience. Would be nice if it opened a browser window and focused on the now newly opened browser window. 

### Stack trace

```shell
Auto-open timed out.
```

### Reproduction steps

1. yarn run dev
2.
3.

### Operating System

MacOS 

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.25

### Shell

Warp

### Node version (run `node -v` if you're not sure)

v19

### What language and version are you using in your application?

Ruby 3.1.3

**Comment by gonzaloriestra** [comment]
Hi! I'm not able to reproduce it. I've tried this with MacOS Ventura + Warp:
- `yarn shopify auth logout`
- `yarn dev`
- It shows `👉 Press any key to open the login page on your browser`
- I press enter and a new tab is opened in the browser with the login page, and the focus on that window

Do you mean that it opens the browser in the background for you?
