### ISSUE TITLE
[Bug]: Infinite Authentication Redirect In Node Dev App

### ISSUE THREAD

**Issue by submergeme** [Shopify/cli#933]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

App should have started, authenticated and redirected once.

### Actual behavior

Infinite authentication redirect. Same issue in both Chrome and Edge.

### Stack trace

backend | [shopify-api/INFO] Creating new session | {shop: ..., isOnline: false}
backend | [shopify-api/INFO] Registering webhooks | {shop: ...}

[followed by the part below, which is in an infinite loop]

backend | [shopify-app/INFO] Running ensureInstalledOnShop
backend | [shopify-app/INFO] App is installed and ready to load | {shop: ...}
backend | [shopify-app/INFO] Running validateAuthenticatedSession
backend | [shopify-app/INFO] Running ensureInstalledOnShop
backend | [shopify-app/INFO] App is installed and ready to load | {shop: ...}
backend | [shopify-app/INFO] Request session has a valid access token | {shop: ...}
backend | [shopify-app/INFO] Running validateAuthenticatedSession

### Reproduction steps

I created a nodejs shopify dev app using the CLI and went through all the steps. When going to the app link (ngrok), the authentication is stuck in an infinite redirect.

Note that I have not changed anything in the project files from the template-- they are coming directly from the template populated from the shopify CLI (npm init @shopify/app@latest). **The only change I made after creating the app with the CLI was setting @shopify/app and @shopify/cli versions to 3.3.3 in dev-app/package.json (to fix vulnerability issues).**

### Operating System

Windows 10

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.3.3

### Node version (run `node -v` if you're not sure)

18.12.1

### What language and version are you using in your application?

Node v18.12.1

**Comment by Arkham** [comment]
@submergeme could you try creating a new app with the latest version of the CLI?

**Comment by submergeme** [comment]
Okay, I figured out the issue. The problem was on my end, due to CLI not finishing the initialization from template.

**Comment by emilymansw** [comment]
@submergeme ran into the same problem, may I know exactly how to solve this? thanks
