### ISSUE TITLE
Need Help with Carrier Service Setup

### ISSUE THREAD

**Issue by varun-etraffic** [Shopify/cli#936]
Hello,

I am creating a carrier service app using Shopify CLI 3.X version.
I have registered my carrier service using the Carrier Service API but when I visit the shipping page on the checkout my Callback URL is not triggering.

I am not sure what I am doing wrong please help me with it. https://prnt.sc/XB16k4ZSUFw4 | https://prnt.sc/-LQ2E4-jW9sy | https://prnt.sc/Eurv8OTcmMq1

Please help me with it.

Thanks and Regards,
Varun

**Comment by Arkham** [comment]
hi @varun-etraffic, I'm not an expert of our php template, but could it be that route should be `Route::get(/carrierservice'` (notice the initial slash).

**Comment by varun-etraffic** [comment]
@Arkham Thanks for your Response but I already have tried this yesterday and still got no results. https://prnt.sc/2UkqJA9l1DG-

**Comment by varun-etraffic** [comment]
@Arkham 

I got it resolved, I was sending a get request the callback URL needed to be a POST method.
