### ISSUE TITLE
[Bug]: Unable to obtain an available random port number

### ISSUE THREAD

**Issue by weeksie** [Shopify/cli#95]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

I should be able to run `shopify dev --tunnel-url=https://my-project.ngrok.io:8082` and start a dev server.

### Actual behavior

After following the upgrade directions on the Shopify developer website, the shopify app dev app fails:

```
shopify app dev --tunnel-url=https://my-project.ngrok.io:8082
```
Note that this command needs more documentation. It took me a while to figure out that the port number was meant to be the local port number that ngrok is mapped to. I eventually got that sorted only to be met with this error:

```
frontend | bbbbbb Error bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
frontend |     Unable to obtain an available random port number!
frontend | 
frontend |     Stack trace:    at getRandomPort              shopify/node_modules/get-port-please/dist/index.mjs:129       
frontend |     at processTicksAndRejectionb&  node:internal/process/task_queues:96                          
frontend |     at getRandomPort              shopify/node_modules/@shopify/cli-kit/src/port.ts:10          
frontend |     at dev                        shopify/node_modules/@shopify/app/src/cli/services/dev.ts:65  
frontend |     at run                        b&fy/node_modules/@shopify/app/src/cli/commands/app/dev.ts:73  
frontend | 
frontend | bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
```

The CLI seems to be falling over just after getting the tunnel host and the frontend port, then crashes on `await getRandomPort()`

I don't know what could be causing this but I doubt it's a bug in `get-port-please`. I created an empty project and was able to get a random port number directly from that library without having a crash. 

### Reproduction steps

1. run shopify dev with `tunnel-url` option set
2. choose existing organization 
3. choose existing app
4. boom

### Operating System

Mac OS Monterey

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.0.25

### Shell

zsh

### Node version (run `node -v` if you're not sure)

16.13

### What language and version are you using in your application?

Node 16.13

**Comment by amcaplan** [comment]
Hi @weeksie, thanks for opening up an issue! I've not managed to reproduced locally yet, but in the meantime, I'm curious if you've tried creating a new app and seeing if the same error appears. (I did exactly that on the same CLI version and didn't see anything...)

Are you using Docker? It's possible that interferes with things as well.

**Comment by weeksie** [comment]
Hi @amcaplan thanks for the response. Just now I was able to use `yarn create @shopify/app` and start a server in a bare directory with a scaffold project. 

I figured out the problem—entirely on me. In the shuffle of moving package.json files, I had a copy of the generated package.json in my `/web` directory so the startup script was calling `shopify dev --tunnel-url=...` instead of `vite dev`

my b. Thanks again for the response.

**Comment by amcaplan** [comment]
Hey @weeksie, thanks for the update! I appreciate you keeping us in the loop, as it frees up our time to help other users who have run into issues.

I'm glad it worked out!

**Comment by weeksie** [comment]
Sure thing, @amcaplan . The documentation for the cli is extremely sparse and I am still finding myself reading through your source code for answers to questions like:

* How is my backend being proxied now? 
* Why were my callback urls overwritten in my app settings?
* What exactly _is_ that port number for in the `tunnel-url`?

And several more, I'm sure, since I'm still on this magical journey of discovery ;)

In any case, Shopify seems to write perfectly good code but as a client developer it's a little frustrating not to have clear documentation of what's happening behind the scenes. Would love to know if there's a roadmap for documenting that functionality. I'm migrating an app that was already in development so I may not be the most common use case, but the lack of documentation is causing a fair bit of friction since the happy path is clearly not working out for my configuration and I keep ending up in dark corners.

**Comment by gonzaloriestra** [comment]
We know the experience is not as smooth as it should be sometimes, but we are working hard to improve it.

Regarding the URL update, we are planning to improve it by overwriting only tunnel-like URLs.
