### ISSUE TITLE
[Bug]: Malformed css var if I have more than one color picker set in a block schema

### ISSUE THREAD

**Issue by levitanong** [Shopify/cli#962]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

Properly formatted css vars like so:

```css
:root {
  --shopify-editor-app-c2da8ae9-8078-41a4-9575-ee43973f524f-block-6174823716744025243-setting-title_color: #ffffff;
  --shopify-editor-app-c2da8ae9-8078-41a4-9575-ee43973f524f-block-6174823716744025243-setting-subtitle_color: #ffffff;
}
```

### Actual behavior

Malformed css vars. A missing semicolon makes it so that there is only one field`--shopify-editor-app-c2da8ae9-8078-41a4-9575-ee43973f524f-block-6174823716744025243-setting-title_color`, with value: `#ffffff --shopify-editor-app-c2da8ae9-8078-41a4-9575-ee43973f524f-block-6174823716744025243-setting-subtitle_color: #ffffff;`.

```css
:root {
  --shopify-editor-app-c2da8ae9-8078-41a4-9575-ee43973f524f-block-6174823716744025243-setting-title_color: #ffffff --shopify-editor-app-c2da8ae9-8078-41a4-9575-ee43973f524f-block-6174823716744025243-setting-subtitle_color: #ffffff;
}
```

<img width="236" alt="image" src="https://user-images.githubusercontent.com/869638/208798883-a7d99c15-a63f-4aae-8feb-2e925276e407.png">

### Reproduction steps

1. Make a theme app extension
2. In the block schema, specify two color picker input settings (e.g. color1, color2)
3. Make a `{% style %}` that defines one css class per color picker (e.g. heading--color1, heading--color2)
4. Make some UI with text elements that use those css classes (e.g. `<h1 class="heading--color1">test</h1>`)
5. Inspect element, and follow the generated css vars.

### Operating System

Windows 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.29

### Shell

bash

### Node version (run `node -v` if you're not sure)

v18.12.1

### What language and version are you using in your application?

n/a

**Comment by levitanong** [comment]
This is still relevant as far as I know.

**Comment by levitanong** [comment]
I have no reason to believe the shopify team has addressed this bug.

**Comment by levitanong** [comment]
"this ping" doesn't look like plaintext, and is rendered properly. I guess it is indeed because your internal teams aren't visible. So I suppose they're busy :P

**Comment by levitanong** [comment]
@Poitrin Should I still keep trying to keep this alive?

**Comment by Poitrin** [comment]
This is how my block’s code looks like:
```
<span class="heading--color1">1234</span>
<span class="heading--color2">5678</span>
{% schema %}
{
    "name": "Hello World",
    "target": "section",
    "stylesheet": "app.css",
    "settings": [
        { "label": "Color 1", "id": "color1", "type": "color", "default": "#2c639a" },
        { "label": "Color 2", "id": "color2", "type": "color", "default": "#b23e3e" }
    ]
}
{% endschema %}
{% style %}
.heading--color1 {
    color: {{ block.settings.color1 }}
}
.heading--color2 {
    color: {{ block.settings.color2 }}
}
{% endstyle %}
```

It's coloring in #2c639a and #b23e3e, as expected.

Where exactly do the CSS vars come into play? :)

**Comment by Poitrin** [comment]
Sorry that it took such a long time. I personally didn't further investigate, as it was assigned to another team.
Indeed, the `--shopify-editor-app-…` variable is something that the _platform_ generates, so even if you manage to reproduce the issue, none of our two teams could fix the issue and we can only transmit the issue to the team responsible for Liquid rendering (except if this issue only happens locally).
