### ISSUE TITLE
[Bug]: v3.29 / v3.30 theme dev ERR_UNHANDLED_REJECTION

### ISSUE THREAD

**Issue by nickjohnford** [Shopify/cli#963]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

connect local theme code to Shopify store

### Actual behavior

Error below is thrown.

**At time of writing*** it looks like v3.29 has now been removed leaving v3.21 as the latest version, however Homebrew only has v3.29, so reinstalling does not fix the problem.

***Edit:** v3.29 now seems to be available again, tried another reinstall, but exactly the same error showing
**Edit2:** I've tested on an intel MacOS Ventura machine that still running cli v3.24.1 (also via Homebrew) with node 19.2.0 and it's still working fine. So the differences between that setup and my own is I'm on an M2 chip, using cli v3.29, and node 19.3.0.
**Edit3:** upgraded to the new v3.30: same error unfortunately

### Stack trace

```shell
/opt/homebrew/Cellar/shopify-cli/3.29.0/libexec/lib/node_modules/@shopify/cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Promise>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v19.3.0
```
```


### Reproduction steps

1. go to dir with existing Shopify theme
2. `shopify theme dev --store=MYSTORE`

### Operating System

M2 MacOS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.29 (edit: same error happening on 3.30)

### Shell

iTerm2

### Node version (run `node -v` if you're not sure)

v19.3.0

### What language and version are you using in your application?

_No response_

**Comment by MathewKostiuk** [comment]
I was getting this same error today when trying to run `shopify theme dev --store=MYSTORE`. In my case, `MYSTORE` had a spelling mistake. The error isn't so helpful but might be worth double-checking what store name you're using as a parameter in the command

**Comment by pea2quared** [comment]
I'm getting this error today too, after updating Shopify CLI with brew. What I'm confused on (based on difference help docs around the web) is it that I need to enter an actual name in place of 'MYSTORE' or am I putting my dev store's URL there?

**Comment by MathewKostiuk** [comment]
You want the Shopify URL for the store you want to upload to. The one with `myshopify.com` in it

**Comment by nickjohnford** [comment]
@MathewKostiuk
> I was getting this same error today when trying to run `shopify theme dev --store=MYSTORE`. In my case, `MYSTORE` had a spelling mistake. The error isn't so helpful but might be worth double-checking what store name you're using as a parameter in the command

A very good suggestion, however I've double checked and my store name is correct; I'm using exactly the same command as I did before the update to v3.29
