### ISSUE TITLE
[Bug]: theme app extension - running 'npm run dev --theme=123721580618'

### ISSUE THREAD

**Issue by rustypaul** [Shopify/cli#965]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

running ```npm run dev --theme=123721580618``` should run a local development environment with the theme specified, but it always uses dawn.

### Actual behavior

The theme used in the local version is always Dawn

I've tried a variety of versions of the command as I wasn't entirely sure it was paying any attention to what I typed. I found the theme ID by opening the theme editor from within Shopify

Using a space errored
```npm run dev --theme 123721580618``` the error was ```command app:dev:123721580618 not found```
Same with quotes
```npm run dev --theme "123721580618"```

Using an equals sign and a name or id just ran the local dev with dawn but it didn't error
```npm run dev --theme=Select-Empire-Theme-2023/development```
Putting quotes around the theme ID or name just used Dawn
```npm run dev --theme="Select-Empire-Theme-2023/development"```

### Stack trace

```shell
terminal output is (I've changed some of the store names)

npm run dev --theme=123721580618                       

> extra-theme-blocks@1.0.0 dev
> shopify app dev

✔ Dependencies installed

Using your previous dev settings:
- Org:          Test
- App:          extra-theme-blocks
- Dev store:    my-test-development.myshopify.com
- Update URLs:  Always

To reset your default dev config, run npm run dev -- --reset

✅ Success! The tunnel is running and you can now view your app.
✔ URL updated


Shareable app URL

  https://efa7-212-82-65-87.eu.ngrok.io?shop=my-test-development.myshopify.com&host=c2VsZWN0LWxpdmluZy0yMDIzLWRldmVsb3BtZW50Lm15c2hvcGlmeS5jb20vYWRtaW4

theme-blocks (Theme app extension)
Follow the dev doc instructions by deploying your work as a draft

2022-12-21 15:20:35 | backend    |
2022-12-21 15:20:35 | backend    | > dev
2022-12-21 15:20:35 | backend    | > cross-env NODE_ENV=development nodemon index.js --ignore ./frontend
2022-12-21 15:20:35 | backend    |
2022-12-21 15:20:35 | frontend   |
2022-12-21 15:20:35 | frontend   | > dev
2022-12-21 15:20:35 | frontend   | > vite
2022-12-21 15:20:35 | frontend   |
2022-12-21 15:20:35 | backend    | [nodemon] 2.0.20
2022-12-21 15:20:35 | backend    | [nodemon] to restart at any time, enter `rs`
2022-12-21 15:20:35 | backend    | [nodemon] watching path(s): *.*
2022-12-21 15:20:35 | backend    | [nodemon] watching extensions: js,mjs,json
2022-12-21 15:20:35 | backend    | [nodemon] starting `node index.js`
2022-12-21 15:20:35 | frontend   |
2022-12-21 15:20:35 | frontend   |   vite v2.9.15 dev server running at:
2022-12-21 15:20:35 | frontend   |
2022-12-21 15:20:35 | frontend   |   > Local:    http://localhost:55532/
2022-12-21 15:20:35 | frontend   |   > Network:  http://192.168.10.49:55532/
2022-12-21 15:20:35 | frontend   |
2022-12-21 15:20:35 | frontend   |   ready in 523ms.
2022-12-21 15:20:35 | frontend   |

┏━━ Viewing extension… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Enable your theme app extension:
┃ https://partners.shopify.com/1810452/apps/15780052994/extensions/theme_app_extension/18102681603
┃ 
┃ Setup your theme app extension in the host theme:
┃ https://my-test-development.myshopify.com/admin/themes/123747044234/editor
┃ 
┃ Preview your theme app extension:
┃ http://127.0.0.1:9292
┃ 
┃ (Use Ctrl-C to stop)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (0.0s) ━━
```

### Reproduction steps

1. Create an app, and an app extension as per the Shopify guide https://shopify.dev/apps/online-store/theme-app-extensions/getting-started
2. In step 3, when you run ```npm run dev``` try to specify a theme used on your development store. e.g. ```npm run dev --theme=123721580618```
3. It will start with Dawn running locally

### Operating System

Mac OS Big Sur

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.29.0

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v16.17.0

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by rustypaul** [comment]
Hey @karreiro

That works for me. Thank you :) I have to say, I would never have thought to try that from the documentation!

**Comment by isaacroldan** [comment]
Some package managers (`npm` and `pnpm`) require an extra `--` when passing parameters to a script. ([more info](https://shopify.dev/apps/tools/cli/commands#command-syntax))

This is because `dev` is a script defined in the package.json of the app.
Another possibility is to call `dev` directly using the full command: `npm shopify app dev --theme 123721580618`

Closing this issue as it seems resolved :)
