### ISSUE TITLE
[Feature]: Option to delay automatic logout

### ISSUE THREAD

**Issue by brianecook** [Shopify/cli#977]
### What type of project(s) will this request affect?

theme

### What type of change do you want to see?

Substantial change to existing feature

### Overview

I am automatically logged out of the store I'm working often all too often throughout the work day when using Shopify command line for themes. It seems to happen once an hour, maybe two. Could you provide an option to set a custom timeout on the connection to the theme from the command line, so that this does not occur as frequently?

### Motivation

I am automatically disconnected (logged out) from the store I'm working on. It would be very convenient if I could set a custom timeout to log out from a store so I don't have to log back in as often.

**Comment by isaacroldan** [comment]
Closing this issue as the fix for the automatic logout was shipped with version 3.30.
Feel free to open a new issue if you find any other problem!
