### ISSUE TITLE
Create GitHub releases aggregating the CHANGELOG changes

### ISSUE THREAD

**Issue by pepicrft** [Shopify/cli#98]
### Context
Each package in this monorepo has its CHANGELOG.md file where [changesets](https://github.com/changesets/changesets) writes the changes every time we release new versions of the packages. Because we have a changelog file per package, it's cumbersome to get an overview of all the changes of a given version. It requires the user to go through all the CHANGELOGs in the repository.

### What
We are not the only ones with this need so the aggregation [feature is being implemented](https://github.com/changesets/action/pull/193). Once it's merged, we can leverage it to create GitHub releases aggregating all the CHANGELOG updates.

**Comment by wisniewski94** [comment]
Any updates on this? Changelog would be good to have. There are lots of new releases recently

**Comment by pepicrft** [comment]
👋🏼 Viktor,
We don't have updates yet unfortunately. Out of curiosity, how do you keep up with platform updates?

**Comment by pepicrft** [comment]
100% agree with you we need to get better at this. There are ongoing efforts to minimize the channels/surfaces you need to keep an eye on to know what's new and has changed. Using GitHub releases will be one of the first steps towards that but not the only one :)

**Comment by wisniewski94** [comment]
Shoo...  *making bot go away*

Maybe enforcing changelog edits in each PR would solve the issue :)?
