### ISSUE TITLE
[Bug]: Errno::EACCES: Permission denied - bind(2) for 127.0.0.1:9292

### ISSUE THREAD

**Issue by jameslegoff92** [Shopify/cli#984]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

I should be able to preview the dawn theme in the browser by using  http://127.0.0.1:9292. 

### Actual behavior

The browser reports the message "The site cannot be reached".

### Stack trace

```shell
PS C:\Users\james\Desktop\shopify\themes\legoffecomm> shopify theme dev --store legoffecomm.myshopify.com

To run this command, log in to Shopify Partners.
👉 Press any key to open the login page on your browser
✔ Logged in.
┏━━ Viewing theme… ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ * Syncing theme #140718899514 on legoffecomm.myshopify.com
┃                                                                           100%
┃
┃ Serving .
┃
┃ Please open this URL in your browser:
┃ http://127.0.0.1:9292
┃
┃ Customize this theme in the Theme Editor, and use 'theme pull' to get the changes:
┃ https://legoffecomm.myshopify.com/admin/themes/140718899514/editor
┃
┃ Share this theme preview:
┃ https://legoffecomm.myshopify.com/?preview_theme_id=140718899514
┃
┃ (Use Ctrl-C to stop)
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (4.77s) ━━━
X An unexpected error occured.
        To submit an issue include the stack trace.
        To print the stack trace, add the environment variable SHOPIFY_CLI_STACKTRACE=1.

C:\Users\james\AppData\Roaming\npm\node_modules\@shopify\cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

AbortSilent [Error]
    at execCLI2 (file:///C:/Users/james/AppData/Roaming/npm/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/dist/public/node/ruby.js:47:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  tryMessage: null,
  type: 1,
  nextSteps: undefined
}
```

### Reproduction steps

1. shopify theme dev --store legoffecomm.myshopify.com

### Operating System

Window 11

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.30.1

### Shell

Windows PowerShell

### Node version (run `node -v` if you're not sure)

16.17.1

**Comment by alvaro-shopify** [comment]
Hi @jameslegoff92 . Thank for rising up this issue.
- what Ruby version are you using?
- could you run the command using `SHOPIFY_CLI_STACKTRACE=1` and post the result here
Thanks.

**Comment by kmishal** [comment]
Facing same issue.. Ruby Version => `ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]`

**Comment by Anshul-Pradhan** [comment]
Can you please give me steps on how to change the port

**Comment by kmishal** [comment]
> @kmishal Can you please give me steps on how to change the port as I am new to this technology

@Anshul-Pradhan  Use command 
`shopify theme dev --port=9393` for cli 3.x 
 `shopify theme serve --port=9393` for cli 2.x

**Comment by Anshul-Pradhan** [comment]
@kmishal Still not working same issue occurs.
