### ISSUE TITLE
[Bug]: tunneling bugs out

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#987]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

App

### Expected behavior

It should have worked, this same patterns works on another store using the Shopify App typical pattern with vite and a frontend. My tunnel here though, used by the CLI fails.

My App root has a shopify.app.toml file. My web/ Shopify Rails App has a shopify.web.toml file to start the rails App. What else do I need? 

### Actual behavior

It did not work. I click on the shareable link, or visit the App in my store, and boom. Tunnel blows out. Why? Help? As a side bonus, this also leaves the server PID file for me to manually delete everytime the App blows up this way.

I am not using anything but Rails so I have no front-end code per se. I am not using Vite. I just do esbuild on my Rails JS files... my Procfile.dev that works is like this:

    web: bin/rails s
    js: yarn build --watch 
    css: yarn build:css --watch
    tunnel: ngrok http --subdomain=dumbo 3153 --log=stdout --log-level=info

So by using foreman start with this file, I get everything working perfect in Shopify, but apparently I cannot do this with the CLI 3... so what am I supposed to do?

### Stack trace

```shell
yarn dev
yarn run v1.22.19
$ shopify app dev --tunnel-url=https://dumbo-sports.test:3153

Using your previous dev settings:
- Org:          Software
- App:          Dumbo (localhost)
- Dev store:    dumbo.myshopify.com
- Update URLs:  Never

To reset your default dev config, run yarn dev --reset

✔ Dependencies installed

To make URL updates manually, you can add the following URLs as redirects in your Partners Dashboard 
  https://dumbo-sports.test/auth/callback
  https://dumbo-sports.test/auth/shopify/callback
  https://dumbo-sports.test/api/auth/callback


Shareable app URL

  https://dumbo-sports.test?shop=dumbo.myshopify.com&host=aG90d2lyZS1yZXNpc3Rvci5teXNob3BpZnkuY29tL2FkbWlu

2022-12-30 02:37:17 | frontend |
2022-12-30 02:37:17 | frontend | $ esbuild app/javascript/*.* --bundle --outdir=app/assets/builds
2022-12-30 02:37:18 | frontend |
2022-12-30 02:37:18 | frontend |   app/assets/builds/application.js  652.2kb
2022-12-30 02:37:18 | frontend |
2022-12-30 02:37:18 | backend  | => Booting Puma
2022-12-30 02:37:18 | backend  | => Rails 7.0.4 application starting in development
2022-12-30 02:37:18 | backend  | => Run `bin/rails server --help` for more startup options
2022-12-30 02:37:20 | backend  | Puma starting in single mode...
2022-12-30 02:37:20 | backend  | * Puma version: 5.6.5 (ruby 3.1.2-p20) ("Birdie's Version")
2022-12-30 02:37:20 | backend  | *  Min threads: 5
2022-12-30 02:37:20 | backend  | *  Max threads: 5
2022-12-30 02:37:20 | backend  | *  Environment: development
2022-12-30 02:37:20 | backend  | *          PID: 76085
2022-12-30 02:37:20 | backend  | * Listening on http://127.0.0.1:62773
2022-12-30 02:37:20 | backend  | * Listening on http://[::1]:62773
2022-12-30 02:37:20 | backend  | Use Ctrl-C to stop

/Users/beer/Documents/Workspace/Apps/2022/hoobles/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: connect ECONNREFUSED ::1:62777
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1471:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 62777
}

Node.js v19.3.0
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction steps

1.
2.
3.

### Operating System

Macos

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.30.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.3

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by bakura10** [comment]
Hi @resistorsoftware ! I found the exact same issue here. How did you solve it? :)

**Comment by bakura10** [comment]
Yes, I am killing all the ports all the time, this is not the issue here. The shopify app dev command runs proeplry and execute all the backend and frontend commands. However, as soon as I try to open the app, I have the error. It seems to be happening when the CLI forward requests to ngrok, but I am unsure at this stage why it is happening.

**Comment by resistorsoftware** [comment]
I have an account with ngrok, so I am able to use that to see my existing tunnels. Try the same with the ngrok CLI on your machine, and if it tells you have a tunnel open from a previous process, kill that!

**Comment by shreyas707** [comment]
> Yes, I am killing all the ports all the time, this is not the issue here. The shopify app dev command runs proeplry and execute all the backend and frontend commands. However, as soon as I try to open the app, I have the error. It seems to be happening when the CLI forward requests to ngrok, but I am unsure at this stage why it is happening.

@bakura10 I'm having the same exact issue as you. The app boots up properly, but as soon as I open the ngrok (or cloudflare with latest shopify cli), the app crashes with the same error.
Did you find any fix for it?
