### ISSUE TITLE
[Feature]: Update proxy app URL

### ISSUE THREAD

**Issue by ccanete** [Shopify/cli#990]
### What area(s) will this request affect?

App, Other

### What type of change do you want to see?

New feature

### Overview

Add an option to the `shopify app dev` command to also update the Proxy url of the App proxy or an option is the app config file (`shopify.app.toml`). 

Exemple, add an option `proxy_path` the same way `auth_callback_path` works. If the option is provided, the proxy_url of the proxy app is updated as followed: `NGROK_URL` + `proxy_path`

### Motivation

Shopify CLI is handling Ngrok tunnelling and updates the app URLs but as it does not update the App proxy URL, when running an application that provides a customer portal using the app proxy, it requires to update manually the Proxy URL every time the local app is restarted.

**Comment by alvaro-shopify** [comment]
Hi @ccanete . Thanks for rising up this issue. The problem here is that the app only updates the webhook once the `oauth` callback is run, which happens when there is no session or the current session is expired.
In your case, if you run the `dev` command several times while the session is valid the `webhooks` are not going to work after the second execution.
There are two manual workarounds to solve the problem:
- wipe their development database before relaunch the `dev` command
- manually trigger oauth calback. Paste this in the browser `https://ngrok-address/api/auth?shop=shop-address`
Please let me know if this works for you.
I will leave this issue open to find a better solution for this problem.

**Comment by ccanete** [comment]
Hi @alvaro-shopify, no problem for the missed-mention and thanks for looking into it.

**Comment by stephszeto** [comment]
Thanks for raising, Cyril! Your request makes sense - will see where we can fit this into our upcoming roadmap!

**Comment by EdvinasKilbauskas** [comment]
Same here, I have to manually re-enter the proxy host everytime i restart the app (and this happens pretty often)

**Comment by artyrcheek** [comment]
Yeah, this would save a lot of time for me

**Comment by rohanrajpal** [comment]
+1 its quite painful to update

**Comment by rohanrajpal** [comment]
Until this is done. Has anyone figured out the internal api request by tapping the graphql request via chrome devtools? I tried but its quite a huge one, so am confused finding the bare minimum needed to update this URL

**Comment by rohanrajpal** [comment]
It is still relevant, ngrok URL changes with almost every restart & changing it manually via the dashboard is not a good developer experience.

**Comment by rnovacek** [comment]
Still active.

**Comment by EdvinasKilbauskas** [comment]
Still relevant

**Comment by ccanete** [comment]
Hi @alvaro-shopify @stephszeto, any news on your side regarding the planning ? Should we open a PR with a proposal ?

**Comment by davidizac** [comment]
Hi @alvaro-shopify @stephszeto, when can we have this feature ?

**Comment by BaggioGiacomo** [comment]
+1

**Comment by yannlombard** [comment]
Still relevant

**Comment by agrohs** [comment]
??

**Comment by alvaro-shopify** [comment]
Hi everyone. Sorry for my late response. As @stephszeto [commented out ](https://github.com/Shopify/cli/issues/990#issuecomment-1396074651) some time ago, we needed to study how to add this request to our roadmap. We have done a little research on how we can include this in the CLI so we think it could be feasible giving support to it in the future. However, right now, we are focused on other issues that requires our attention first. So I'm not able to confirm you when this feature will be added to the CLI but it will be on our roadmap.
I hope our explanation works for you and sorry for the inconveniences.

**Comment by agrohs** [comment]
I have been working on implementing this and have a fork that is nearly ready w/ this (shooting to send over as a PR in the next week or two) and happy to share the link here as soon as I get a few things cleaned up if anyone wants to take a peak.

**Comment by sebastianpisula** [comment]
+1

**Comment by joalphasprouts** [comment]
> pify CLI is handling Ngrok tunnelling and updates the app URLs but as it does not update the App proxy URL, when running an application that provides a customer portal using the app proxy, it requires to update manually the Proxy URL every time the local app is restarted.

Can we please have this? Any timeline? BRB I have to manually update the app proxy url on my app for the 400th time today.

**Comment by joalphasprouts** [comment]
<img width="941" alt="image" src="https://github.com/Shopify/cli/assets/124207031/28054b1a-b439-44be-899a-eb3fdc20c833">

**Comment by Nedi11** [comment]
+111111111111111111

**Comment by fxdave** [comment]
> I've hacked this into my local version as described below, but it would be great to have it in the Shopify module properly. The update below simply takes the applicationUrl and uses it for your proxyUrl as well.
> 
> Edit `@shopify/app/dist/cli/api/graphql/update_urls.js` and update the mutation so it accepts `AppProxyInput`:
> 
> ```
> mutation appUpdate($apiKey: String!, $applicationUrl: Url!, $redirectUrlWhitelist: [Url]!, $appProxyInput: AppProxyInput!) {
>   appUpdate(input: {apiKey: $apiKey, applicationUrl: $applicationUrl, redirectUrlWhitelist: $redirectUrlWhitelist, appProxy: $appProxyInput}) {
> ```
> 
> Then in `@shopify/app/dist/cli/services/dev/urls.js` find the following line:
> 
> ```
> const variables = { apiKey, ...urls };
> ```
> 
> and replace this with
> 
> ```
>     const appProxyInput = {
>       appProxyInput: {
>           proxySubPathPrefix: 'apps',
>           proxySubPath: 'your-app',
>           proxyUrl: urls.applicationUrl,
>       }
>   }
>   const variables = { apiKey, ...urls, ...appProxyInput };
> ```

Thanks! I made a script from your instructions.
`./hack_proxy_updater_into_shopify.sh`:
```bash
#!/bin/bash
PROXY_SUB_PATH="your path"

# License: GPLv3, except the settings above

FILE1="./node_modules/@shopify/app/dist/cli/api/graphql/update_urls.js"
FILE2="./node_modules/@shopify/app/dist/cli/services/dev/urls.js"

SEARCH1="\\\$redirectUrlWhitelist: \\[Url\\]\\!)"
REPLACE1="\\\$redirectUrlWhitelist: \\[Url\\]\\!, \\\$appProxyInput: AppProxyInput\\!\\)"
SEARCH2="\\\$redirectUrlWhitelist\\}"
REPLACE2="\\\$redirectUrlWhitelist, appProxy: \\\$appProxyInput\\}"

cat $FILE1 |
    sed "s/$SEARCH1/$REPLACE1/" |
    sed "s/$SEARCH2/$REPLACE2/" > ./.temp.js

mv ./.temp.js $FILE1

SEARCH="const variables = { apiKey, ...urls };"
REPLACE="const appProxyInput = {\n\
        appProxyInput: {\n\
            proxySubPathPrefix: 'apps',\n\
            proxySubPath: '$PROXY_SUB_PATH',\n\
            proxyUrl: urls.applicationUrl,\n\
        }\n\
    }\n\
    const variables = { apiKey, ...urls, ...appProxyInput };"

cat $FILE2 |
    sed "s/$SEARCH/$REPLACE/" >  ./.temp.js

mv ./.temp.js $FILE2

echo "Proxy updater has been hacked into @shopify/app successfully."
```

**Comment by Arkham** [comment]
Hey folks, we've recently released 3.48.0 which includes support for specifying your app proxy url using config as code. Check out the documentation here:

https://shopify.dev/docs/apps/tools/cli/configuration
https://shopify.dev/docs/apps/tools/cli/managing-app-configuration-files

**Comment by javl** [comment]
@Arkham While this is a welcome update, it doesn't fix the problem at hand, which is that we still need to manually update our `proxy_url` while in development.

For example: with `automatically_update_urls_on_dev` set to `true` in settings I can start my server using `npm run serve` and it will automatically update the `redirect_urls` of my app to point to the generated `.trycloudflare.com` url (in both the `.toml` and the partners dashboard). However, my `proxy_url` does not change and I still need to, manually, copy and paste the `redirect_url` into the `app_proxy` url field.

What we need is a value like `automatically_match_proxy_url_on_dev` which will update `app_proxy.url` to match the URLs in `redirect_urls` as soon as those are changed.

Also, it seems the `.toml` can contain other `app_proxy` information than the dashboard and neither seem to update the other when changed? Not sure which one takes precedent or how this now works.

**Comment by Arkham** [comment]
Hey @javl, I've been working today on a better approach here: https://github.com/Shopify/cli/pull/2594 It should solve this problem in a more elegant way :)
