### ISSUE TITLE
[Bug]: Post Purchase Checkout Extension fires once only

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/cli#992]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

It should have worked

### Actual behavior

I am trying out Post Purchase Extension. Running my App, I get a code for the Chrome extension to test and develop. I paste in the address issued by Shopify when I run my App. I open up that store in Chrome and buy something. 

The first time I bought something, the extension picked up the purchase, and I was able to play with the UI in the extension a little and see how it rendered and worked. Eventually, that petered out and we ended at the Thank you Page. 

Now I have booked 6 other orders, and that post-purchase extension never fires up? So what is up with that? Nothing else has changed. It is like a one-trick pony? What is the secret to having the extension work more than once? 

### Reproduction steps

1. Set the Post Purchase extension URL in the Chrome extension
2. Buy something from a store with the App installed running this extension
3. Checkout

### Operating System

MacOS

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.30.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v19.3

### What language and version are you using in your application?

Ruby 3.1.2

**Comment by resistorsoftware** [comment]
All I know is this. I used **yarn dev** to start an App that has an extension for post-purchase. I was issued an URL to paste into a Chrome extension. I did that, and hit save. Using the same said Chrome browser, I did a few orders, none of which were captured by the extension. Eventually, I did get one, and then I was able to debug. Perhaps it was because I had added code to the extension Shopify did not like. That led me to examine the console. 

- it seems my console.logs in the extension are not relayed to console in Chrome from the extension? 
- while I was able to see a bug for an unknown object, hitting refresh sent me to the Thank You page. 

So instead, when issuing code changes live, I hit enter on the URL to reload the same page with the URL extension that Chrome then picks up. OK. Awkward but it works. 

Also, I could not for the life of me get other API points in the purchase extension. A simple thing like the shop or the total amount in the cart? How do we surface that data in the post-purchase? 

And then, upon closer inspection of the docs, I finally noticed, I cannot even use this extension for the merchant as he is not subscribed to Plus... nonetheless, I want to know how to finish this extension!

**Comment by isaacroldan** [comment]
If there is an issue with the extension code, that might be the primary reason for it not to show up. A quick check would be to revert back to the stock template code and see if it loads that way.

Here is a doc about the available API points: https://shopify.dev/api/checkout-extensions/extension-points/api#inputdata 
You should be able to access info about the shop and the order total.

Let me know if the first point solve the issue of the extension not loading :)
